cplus2asp: as2transition/lemon/lemon.c File Reference
lemon.c File Reference
#include <stdio.h>
#include <stdarg.h>
#include <string.h>
#include <ctype.h>
#include <stdlib.h>
#include <assert.h>
#include <unistd.h>
Classes
struct s_options
struct symbol
struct rule
struct config
struct action
struct state
struct plink
struct lemon
struct lookahead_action
struct acttab
struct pstate
struct axset
struct s_x1
struct s_x1node
struct s_x2
struct s_x2node
struct s_x3
struct s_x3node
struct s_x4
struct s_x4node
Macros
#define PRIVATE
#define MAXRHS 1000
#define lemonStrlen(X) ((int)strlen(X))
#define SetFind(X, Y) (X[Y]) /* True if Y is in set X */
#define NO_OFFSET (-2147483647)
#define MemoryCheck(X)
#define acttab_size(X) ((X)->nAction)
#define acttab_yyaction(X, N) ((X)->aAction[N].action)
#define acttab_yylookahead(X, N) ((X)->aAction[N].lookahead)
#define NEXT(A) (*(char**)(((char*)A)+offset))
#define LISTSIZE 30
#define ISOPT(X) ((X)[0]=='-'||(X)[0]=='+'||strchr((X),'=')!=0)
#define LINESIZE 1000
Typedefs
typedef struct acttab acttab
typedef struct s_x1node x1node
typedef struct s_x2node x2node
typedef struct s_x3node x3node
typedef struct s_x4node x4node
Enumerations
enum option_type {
OPT_FLAG =1, OPT_INT, OPT_DBL, OPT_STR,
OPT_FFLAG, OPT_FINT, OPT_FDBL, OPT_FSTR,
OPT_FLAG =1, OPT_INT, OPT_DBL, OPT_STR,
OPT_FFLAG, OPT_FINT, OPT_FDBL, OPT_FSTR
}
enum Boolean { LEMON_FALSE =0, LEMON_TRUE, LEMON_FALSE =0, LEMON_TRUE }
enum symbol_type {
TERMINAL, NONTERMINAL, MULTITERMINAL, TERMINAL,
NONTERMINAL, MULTITERMINAL
}
enum e_assoc {
LEFT, RIGHT, NONE, UNK,
LEFT, RIGHT, NONE, UNK
}
enum cfgstatus { COMPLETE, INCOMPLETE, COMPLETE, INCOMPLETE }
enum e_action {
SHIFT, ACCEPT, REDUCE, ERROR,
SSCONFLICT, SRCONFLICT, RRCONFLICT, SH_RESOLVED,
RD_RESOLVED, NOT_USED, SHIFT, ACCEPT,
REDUCE, ERROR, SSCONFLICT, SRCONFLICT,
RRCONFLICT, SH_RESOLVED, RD_RESOLVED, NOT_USED
}
enum e_state {
INITIALIZE, WAITING_FOR_DECL_OR_RULE, WAITING_FOR_DECL_KEYWORD, WAITING_FOR_DECL_ARG,
WAITING_FOR_PRECEDENCE_SYMBOL, WAITING_FOR_ARROW, IN_RHS, LHS_ALIAS_1,
LHS_ALIAS_2, LHS_ALIAS_3, RHS_ALIAS_1, RHS_ALIAS_2,
PRECEDENCE_MARK_1, PRECEDENCE_MARK_2, RESYNC_AFTER_RULE_ERROR, RESYNC_AFTER_DECL_ERROR,
WAITING_FOR_DESTRUCTOR_SYMBOL, WAITING_FOR_DATATYPE_SYMBOL, WAITING_FOR_FALLBACK_ID, WAITING_FOR_WILDCARD_ID,
WAITING_FOR_CLASS_ID, WAITING_FOR_CLASS_TOKEN, INITIALIZE, WAITING_FOR_DECL_OR_RULE,
WAITING_FOR_DECL_KEYWORD, WAITING_FOR_DECL_ARG, WAITING_FOR_PRECEDENCE_SYMBOL, WAITING_FOR_ARROW,
IN_RHS, LHS_ALIAS_1, LHS_ALIAS_2, LHS_ALIAS_3,
RHS_ALIAS_1, RHS_ALIAS_2, PRECEDENCE_MARK_1, PRECEDENCE_MARK_2,
RESYNC_AFTER_RULE_ERROR, RESYNC_AFTER_DECL_ERROR, WAITING_FOR_DESTRUCTOR_SYMBOL, WAITING_FOR_DATATYPE_SYMBOL,
WAITING_FOR_FALLBACK_ID, WAITING_FOR_WILDCARD_ID, WAITING_FOR_CLASS_ID, WAITING_FOR_CLASS_TOKEN
}
Functions
void FindRulePrecedences ()
void FindFirstSets ()
void FindStates ()
void FindLinks ()
void FindFollowSets ()
void FindActions ()
void Configlist_init (void)
struct config * Configlist_add (struct rule *, int)
struct config * Configlist_addbasis (struct rule *, int)
void Configlist_closure (struct lemon *)
void Configlist_sort (void)
void Configlist_sortbasis (void)
struct config * Configlist_return (void)
struct config * Configlist_basis (void)
void Configlist_eat (struct config *)
void Configlist_reset (void)
void ErrorMsg (const char *, int, const char *,...)
int OptInit (char **, struct s_options *, FILE *)
int OptNArgs (void)
char * OptArg (int)
void OptErr (int)
void OptPrint (void)
void Parse (struct lemon *lemp)
struct plink * Plink_new (void)
void Plink_add (struct plink **, struct config *)
void Plink_copy (struct plink **, struct plink *)
void Plink_delete (struct plink *)
void Reprint (struct lemon *)
void ReportOutput (struct lemon *)
void ReportTable (struct lemon *, int)
void ReportHeader (struct lemon *)
void CompressTables (struct lemon *)
void ResortStates (struct lemon *)
void SetSize (int)
char * SetNew (void)
void SetFree (char *)
int SetAdd (char *, int)
int SetUnion (char *, char *)
const char * Strsafe (const char *)
void Strsafe_init (void)
int Strsafe_insert (const char *)
const char * Strsafe_find (const char *)
struct symbol * Symbol_new (const char *)
int Symbolcmpp (const void *, const void *)
void Symbol_init (void)
int Symbol_insert (struct symbol *, const char *)
struct symbol * Symbol_find (const char *)
struct symbol * Symbol_Nth (int)
int Symbol_count (void)
struct symbol ** Symbol_arrayof (void)
int Configcmp (const char *, const char *)
struct state * State_new (void)
void State_init (void)
int State_insert (struct state *, struct config *)
struct state * State_find (struct config *)
struct state ** State_arrayof ()
void Configtable_init (void)
int Configtable_insert (struct config *)
struct config * Configtable_find (struct config *)
void Configtable_clear (int(*)(struct config *))
void Action_add (struct action **app, enum e_action type, struct symbol *sp, char *arg)
void acttab_free (acttab *p)
acttab * acttab_alloc (void)
void acttab_action (acttab *p, int lookahead, int action)
int acttab_insert (acttab *p)
void FindRulePrecedences (struct lemon *xp)
void FindFirstSets (struct lemon *lemp)
PRIVATE struct state * getstate (struct lemon *)
void FindStates (struct lemon *lemp)
PRIVATE void buildshifts (struct lemon *, struct state *)
int same_symbol (struct symbol *a, struct symbol *b)
void FindLinks (struct lemon *lemp)
void FindFollowSets (struct lemon *lemp)
void FindActions (struct lemon *lemp)
PRIVATE struct config * newconfig ()
PRIVATE void deleteconfig (struct config *old)
void memory_error ()
int main (int argc, char **argv)
PRIVATE char * file_makename (struct lemon *lemp, const char *suffix)
PRIVATE FILE * file_open (struct lemon *lemp, const char *suffix, const char *mode)
void ConfigPrint (FILE *fp, struct config *cfp)
int PrintAction (struct action *ap, FILE *fp, int indent)
PRIVATE char * pathsearch (char *argv0, char *name, int modemask)
PRIVATE int compute_action (struct lemon *lemp, struct action *ap)
PRIVATE void tplt_xfer (char *name, FILE *in, FILE *out, int *lineno)
PRIVATE FILE * tplt_open (struct lemon *lemp)
PRIVATE void tplt_linedir (FILE *out, int lineno, char *filename)
PRIVATE void tplt_print (FILE *out, struct lemon *lemp, char *str, int *lineno)
void emit_destructor_code (FILE *out, struct symbol *sp, struct lemon *lemp, int *lineno)
int has_destructor (struct symbol *sp, struct lemon *lemp)
PRIVATE char * append_str (const char *zText, int n, int p1, int p2)
PRIVATE void translate_code (struct lemon *lemp, struct rule *rp)
PRIVATE void emit_code (FILE *out, struct rule *rp, struct lemon *lemp, int *lineno)
void print_stack_union (FILE *out, struct lemon *lemp, int *plineno, int mhflag)
PRIVATE unsigned strhash (const char *x)
PRIVATE int statecmp (struct config *a, struct config *b)
PRIVATE unsigned statehash (struct config *a)
PRIVATE unsigned confighash (struct config *a)
Macro Definition Documentation
#define acttab_size (X) ((X)->nAction)
Definition at line 566 of file lemon.c.
Referenced by ReportTable().
#define acttab_yyaction (X, N) ((X)->aAction[N].action)
Definition at line 569 of file lemon.c.
Referenced by ReportTable().
#define acttab_yylookahead (X, N) ((X)->aAction[N].lookahead)
Definition at line 572 of file lemon.c.
Referenced by ReportTable().
#define ISOPT (X) ((X)[0]=='-'||(X)[0]=='+'||strchr((X),'=')!=0)
Definition at line 1751 of file lemon.c.
Referenced by OptNArgs().
#define lemonStrlen (X) ((int)strlen(X))
Definition at line 51 of file lemon.c.
Referenced by append_str(), file_makename(), OptPrint(), pathsearch(), print_stack_union(), ReportTable(), Reprint(), and Strsafe().
#define LINESIZE 1000
Definition at line 3173 of file lemon.c.
Referenced by ReportHeader(), ReportTable(), and tplt_xfer().
#define LISTSIZE 30
Definition at line 1720 of file lemon.c.
#define MAXRHS 1000
Definition at line 40 of file lemon.c.
Referenced by translate_code().
#define MemoryCheck (X)
Value:
if((X)==0){ \
  extern void memory_error(); \
  memory_error(); \
}
Definition at line 395 of file lemon.c.
Referenced by getstate(), State_new(), Strsafe(), and Symbol_new().
#define NEXT (A) (*(char**)(((char*)A)+offset))
Definition at line 1652 of file lemon.c.
#define NO_OFFSET (-2147483647)
Definition at line 345 of file lemon.c.
Referenced by ReportTable(), and ResortStates().
#define PRIVATE
Definition at line 35 of file lemon.c.
#define SetFind (X, Y) (X[Y]) /* True if Y is in set X */
Definition at line 223 of file lemon.c.
Referenced by FindActions(), and ReportOutput().
Typedef Documentation
typedef struct acttab acttab
Definition at line 551 of file lemon.c.
typedef struct s_x1node x1node
typedef struct s_x2node x2node
typedef struct s_x3node x3node
typedef struct s_x4node x4node
Enumeration Type Documentation
enum Boolean
Enumerator
LEMON_FALSE
LEMON_TRUE
LEMON_FALSE
LEMON_TRUE
Definition at line 230 of file lemon.c.
 {LEMON_FALSE=0, LEMON_TRUE} Boolean;
enum cfgstatus
Enumerator
COMPLETE
INCOMPLETE
COMPLETE
INCOMPLETE
Definition at line 293 of file lemon.c.
                {
   COMPLETE,
   INCOMPLETE
 };
enum e_action
Enumerator
SHIFT
ACCEPT
REDUCE
ERROR
SSCONFLICT
SRCONFLICT
RRCONFLICT
SH_RESOLVED
RD_RESOLVED
NOT_USED
SHIFT
ACCEPT
REDUCE
ERROR
SSCONFLICT
SRCONFLICT
RRCONFLICT
SH_RESOLVED
RD_RESOLVED
NOT_USED
Definition at line 309 of file lemon.c.
               {
   SHIFT,
   ACCEPT,
   REDUCE,
   ERROR,
   SSCONFLICT,              /* A shift/shift conflict */
   SRCONFLICT,              /* Was a reduce, but part of a conflict */
   RRCONFLICT,              /* Was a reduce, but part of a conflict */
   SH_RESOLVED,             /* Was a shift.  Precedence resolved conflict */
   RD_RESOLVED,             /* Was reduce.  Precedence resolved conflict */
   NOT_USED                 /* Deleted by compression */
 };
enum e_assoc
Enumerator
LEFT
RIGHT
NONE
UNK
LEFT
RIGHT
NONE
UNK
Definition at line 239 of file lemon.c.
              {
     LEFT,
     RIGHT,
     NONE,
     UNK
 };
enum e_state
Enumerator
INITIALIZE
WAITING_FOR_DECL_OR_RULE
WAITING_FOR_DECL_KEYWORD
WAITING_FOR_DECL_ARG
WAITING_FOR_PRECEDENCE_SYMBOL
WAITING_FOR_ARROW
IN_RHS
LHS_ALIAS_1
LHS_ALIAS_2
LHS_ALIAS_3
RHS_ALIAS_1
RHS_ALIAS_2
PRECEDENCE_MARK_1
PRECEDENCE_MARK_2
RESYNC_AFTER_RULE_ERROR
RESYNC_AFTER_DECL_ERROR
WAITING_FOR_DESTRUCTOR_SYMBOL
WAITING_FOR_DATATYPE_SYMBOL
WAITING_FOR_FALLBACK_ID
WAITING_FOR_WILDCARD_ID
WAITING_FOR_CLASS_ID
WAITING_FOR_CLASS_TOKEN
INITIALIZE
WAITING_FOR_DECL_OR_RULE
WAITING_FOR_DECL_KEYWORD
WAITING_FOR_DECL_ARG
WAITING_FOR_PRECEDENCE_SYMBOL
WAITING_FOR_ARROW
IN_RHS
LHS_ALIAS_1
LHS_ALIAS_2
LHS_ALIAS_3
RHS_ALIAS_1
RHS_ALIAS_2
PRECEDENCE_MARK_1
PRECEDENCE_MARK_2
RESYNC_AFTER_RULE_ERROR
RESYNC_AFTER_DECL_ERROR
WAITING_FOR_DESTRUCTOR_SYMBOL
WAITING_FOR_DATATYPE_SYMBOL
WAITING_FOR_FALLBACK_ID
WAITING_FOR_WILDCARD_ID
WAITING_FOR_CLASS_ID
WAITING_FOR_CLASS_TOKEN
Definition at line 2026 of file lemon.c.
              {
   INITIALIZE,
   WAITING_FOR_DECL_OR_RULE,
   WAITING_FOR_DECL_KEYWORD,
   WAITING_FOR_DECL_ARG,
   WAITING_FOR_PRECEDENCE_SYMBOL,
   WAITING_FOR_ARROW,
   IN_RHS,
   LHS_ALIAS_1,
   LHS_ALIAS_2,
   LHS_ALIAS_3,
   RHS_ALIAS_1,
   RHS_ALIAS_2,
   PRECEDENCE_MARK_1,
   PRECEDENCE_MARK_2,
   RESYNC_AFTER_RULE_ERROR,
   RESYNC_AFTER_DECL_ERROR,
   WAITING_FOR_DESTRUCTOR_SYMBOL,
   WAITING_FOR_DATATYPE_SYMBOL,
   WAITING_FOR_FALLBACK_ID,
   WAITING_FOR_WILDCARD_ID,
   WAITING_FOR_CLASS_ID,
   WAITING_FOR_CLASS_TOKEN
 };
enum option_type
Enumerator
OPT_FLAG
OPT_INT
OPT_DBL
OPT_STR
OPT_FFLAG
OPT_FINT
OPT_FDBL
OPT_FSTR
OPT_FLAG
OPT_INT
OPT_DBL
OPT_STR
OPT_FFLAG
OPT_FINT
OPT_FDBL
OPT_FSTR
Definition at line 186 of file lemon.c.
                  { OPT_FLAG=1,  OPT_INT,  OPT_DBL,  OPT_STR,
          OPT_FFLAG, OPT_FINT, OPT_FDBL, OPT_FSTR};
enum symbol_type
Enumerator
TERMINAL
NONTERMINAL
MULTITERMINAL
TERMINAL
NONTERMINAL
MULTITERMINAL
Definition at line 234 of file lemon.c.
                  {
   TERMINAL,
   NONTERMINAL,
   MULTITERMINAL
 };
Function Documentation
void Action_add (struct action ** app, enum e_action type, struct symbol * sp, char * arg)
Definition at line 504 of file lemon.c.
References action::next, action::rp, SHIFT, action::sp, action::stp, action::type, and action::x.
Referenced by buildshifts(), and FindActions().
  {
   struct action *newaction;
   newaction = Action_new();
   newaction->next = *app;
   *app = newaction;
   newaction->type = type;
   newaction->sp = sp;
   if( type==SHIFT ){
     newaction->x.stp = (struct state *)arg;
   }else{
     newaction->x.rp = (struct rule *)arg;
   }
 }
void acttab_action (acttab * p, int lookahead, int action)
Definition at line 597 of file lemon.c.
References lookahead_action::action, acttab::aLookahead, lookahead_action::lookahead, acttab::mnAction, acttab::mnLookahead, acttab::mxLookahead, acttab::nLookahead, and acttab::nLookaheadAlloc.
Referenced by ReportTable().
{
   if( p->nLookahead>=p->nLookaheadAlloc ){
     p->nLookaheadAlloc += 25;
     p->aLookahead = (struct lookahead_action *) realloc( p->aLookahead,
                              sizeof(p->aLookahead[0])*p->nLookaheadAlloc );
     if( p->aLookahead==0 ){
       fprintf(stderr,"malloc failed\n");
       exit(1);
     }
   }
   if( p->nLookahead==0 ){
     p->mxLookahead = lookahead;
     p->mnLookahead = lookahead;
     p->mnAction = action;
   }else{
     if( p->mxLookahead<lookahead ) p->mxLookahead = lookahead;
     if( p->mnLookahead>lookahead ){
       p->mnLookahead = lookahead;
       p->mnAction = action;
     }
   }
   p->aLookahead[p->nLookahead].lookahead = lookahead;
   p->aLookahead[p->nLookahead].action = action;
   p->nLookahead++;
 }
acttab* acttab_alloc (void)
Definition at line 582 of file lemon.c.
Referenced by ReportTable().
{
   acttab *p = (acttab *) calloc( 1, sizeof(*p) );
   if( p==0 ){
     fprintf(stderr,"Unable to allocate memory for a new acttab.");
     exit(1);
   }
   memset(p, 0, sizeof(*p));
   return p;
 }
void acttab_free (acttab * p)
Definition at line 575 of file lemon.c.
References acttab::aAction, and acttab::aLookahead.
{
   free( p->aAction );
   free( p->aLookahead );
   free( p );
 }
int acttab_insert (acttab * p)
Definition at line 630 of file lemon.c.
References acttab::aAction, lookahead_action::action, acttab::aLookahead, lookahead_action::lookahead, acttab::mnAction, acttab::mnLookahead, acttab::mxLookahead, acttab::nAction, acttab::nActionAlloc, and acttab::nLookahead.
Referenced by ReportTable().
{
   int i, j, k, n;
   assert( p->nLookahead>0 );
   /* Make sure we have enough space to hold the expanded action table
   ** in the worst case.  The worst case occurs if the transaction set
   ** must be appended to the current action table
   */
   n = p->mxLookahead + 1;
   if( p->nAction + n >= p->nActionAlloc ){
     int oldAlloc = p->nActionAlloc;
     p->nActionAlloc = p->nAction + n + p->nActionAlloc + 20;
     p->aAction = (struct lookahead_action *) realloc( p->aAction,
                           sizeof(p->aAction[0])*p->nActionAlloc);
     if( p->aAction==0 ){
       fprintf(stderr,"malloc failed\n");
       exit(1);
     }
     for(i=oldAlloc; i<p->nActionAlloc; i++){
       p->aAction[i].lookahead = -1;
       p->aAction[i].action = -1;
     }
   }
   /* Scan the existing action table looking for an offset that is a
   ** duplicate of the current transaction set.  Fall out of the loop
   ** if and when the duplicate is found.
   **
   ** i is the index in p->aAction[] where p->mnLookahead is inserted.
   */
   for(i=p->nAction-1; i>=0; i--){
     if( p->aAction[i].lookahead==p->mnLookahead ){
       /* All lookaheads and actions in the aLookahead[] transaction
       ** must match against the candidate aAction[i] entry. */
       if( p->aAction[i].action!=p->mnAction ) continue;
       for(j=0; j<p->nLookahead; j++){
         k = p->aLookahead[j].lookahead - p->mnLookahead + i;
         if( k<0 || k>=p->nAction ) break;
         if( p->aLookahead[j].lookahead!=p->aAction[k].lookahead ) break;
         if( p->aLookahead[j].action!=p->aAction[k].action ) break;
       }
       if( j<p->nLookahead ) continue;
       /* No possible lookahead value that is not in the aLookahead[]
       ** transaction is allowed to match aAction[i] */
       n = 0;
       for(j=0; j<p->nAction; j++){
         if( p->aAction[j].lookahead<0 ) continue;
         if( p->aAction[j].lookahead==j+p->mnLookahead-i ) n++;
       }
       if( n==p->nLookahead ){
         break;  /* An exact match is found at offset i */
       }
     }
   }
   /* If no existing offsets exactly match the current transaction, find an
   ** an empty offset in the aAction[] table in which we can add the
   ** aLookahead[] transaction.
   */
   if( i<0 ){
     /* Look for holes in the aAction[] table that fit the current
     ** aLookahead[] transaction.  Leave i set to the offset of the hole.
     ** If no holes are found, i is left at p->nAction, which means the
     ** transaction will be appended. */
     for(i=0; i<p->nActionAlloc - p->mxLookahead; i++){
       if( p->aAction[i].lookahead<0 ){
         for(j=0; j<p->nLookahead; j++){
           k = p->aLookahead[j].lookahead - p->mnLookahead + i;
           if( k<0 ) break;
           if( p->aAction[k].lookahead>=0 ) break;
         }
         if( j<p->nLookahead ) continue;
         for(j=0; j<p->nAction; j++){
           if( p->aAction[j].lookahead==j+p->mnLookahead-i ) break;
         }
         if( j==p->nAction ){
           break;  /* Fits in empty slots */
         }
       }
     }
   }
   /* Insert transaction set at index i. */
   for(j=0; j<p->nLookahead; j++){
     k = p->aLookahead[j].lookahead - p->mnLookahead + i;
     p->aAction[k] = p->aLookahead[j];
     if( k>=p->nAction ) p->nAction = k+1;
   }
   p->nLookahead = 0;
   /* Return the offset that is added to the lookahead in order to get the
   ** index into yy_action of the action */
   return i - p->mnLookahead;
 }
PRIVATE char* append_str (const char * zText, int n, int p1, int p2)
Definition at line 3362 of file lemon.c.
References lemonStrlen.
Referenced by translate_code().
{
   static char empty[1] = { 0 };
   static char *z = 0;
   static int alloced = 0;
   static int used = 0;
   int c;
   char zInt[40];
   if( zText==0 ){
     used = 0;
     return z;
   }
   if( n<=0 ){
     if( n<0 ){
       used += n;
       assert( used>=0 );
     }
     n = lemonStrlen(zText);
   }
   if( (int) (n+sizeof(zInt)*2+used) >= alloced ){
     alloced = n + sizeof(zInt)*2 + used + 200;
     z = (char *) realloc(z,  alloced);
   }
   if( z==0 ) return empty;
   while( n-- > 0 ){
     c = *(zText++);
     if( c=='%' && n>0 && zText[0]=='d' ){
       lemon_sprintf(zInt, "%d", p1);
       p1 = p2;
       lemon_strcpy(&z[used], zInt);
       used += lemonStrlen(&z[used]);
       zText++;
       n--;
     }else{
       z[used++] = c;
     }
   }
   z[used] = 0;
   return z;
 }
PRIVATE void buildshifts (struct lemon * lemp, struct state * stp)
Definition at line 951 of file lemon.c.
References Action_add(), state::ap, config::bplp, state::cfp, COMPLETE, Configlist_addbasis(), Configlist_reset(), config::dot, getstate(), INCOMPLETE, MULTITERMINAL, config::next, rule::nrhs, symbol::nsubsym, Plink_add(), rule::rhs, config::rp, same_symbol(), SHIFT, config::status, symbol::subsym, and symbol::type.
Referenced by getstate().
 {
   struct config *cfp;  /* For looping thru the config closure of "stp" */
   struct config *bcfp; /* For the inner loop on config closure of "stp" */
   struct config *newcfg;  /* */
   struct symbol *sp;   /* Symbol following the dot in configuration "cfp" */
   struct symbol *bsp;  /* Symbol following the dot in configuration "bcfp" */
   struct state *newstp; /* A pointer to a successor state */
   /* Each configuration becomes complete after it contibutes to a successor
   ** state.  Initially, all configurations are incomplete */
   for(cfp=stp->cfp; cfp; cfp=cfp->next) cfp->status = INCOMPLETE;
   /* Loop through all configurations of the state "stp" */
   for(cfp=stp->cfp; cfp; cfp=cfp->next){
     if( cfp->status==COMPLETE ) continue;    /* Already used by inner loop */
     if( cfp->dot>=cfp->rp->nrhs ) continue;  /* Can't shift this config */
     Configlist_reset();                      /* Reset the new config set */
     sp = cfp->rp->rhs[cfp->dot];             /* Symbol after the dot */
     /* For every configuration in the state "stp" which has the symbol "sp"
     ** following its dot, add the same configuration to the basis set under
     ** construction but with the dot shifted one symbol to the right. */
     for(bcfp=cfp; bcfp; bcfp=bcfp->next){
       if( bcfp->status==COMPLETE ) continue;    /* Already used */
       if( bcfp->dot>=bcfp->rp->nrhs ) continue; /* Can't shift this one */
       bsp = bcfp->rp->rhs[bcfp->dot];           /* Get symbol after dot */
       if( !same_symbol(bsp,sp) ) continue;      /* Must be same as for "cfp" */
       bcfp->status = COMPLETE;                  /* Mark this config as used */
       newcfg = Configlist_addbasis(bcfp->rp,bcfp->dot+1);
       Plink_add(&newcfg->bplp,bcfp);
     }
     /* Get a pointer to the state described by the basis configuration set
     ** constructed in the preceding loop */
     newstp = getstate(lemp);
     /* The state "newstp" is reached from the state "stp" by a shift action
     ** on the symbol "sp" */
     if( sp->type==MULTITERMINAL ){
       int i;
       for(i=0; i<sp->nsubsym; i++){
         Action_add(&stp->ap,SHIFT,sp->subsym[i],(char*)newstp);
       }
     }else{
       Action_add(&stp->ap,SHIFT,sp,(char *)newstp);
     }
   }
 }
void CompressTables (struct lemon * lemp)
Definition at line 4201 of file lemon.c.
References state::ap, rule::lhsStart, action::next, NOT_USED, lemon::nstate, REDUCE, action::rp, SHIFT, lemon::sorted, action::sp, Symbol_new(), action::type, lemon::wildcard, and action::x.
Referenced by main().
 {
   struct state *stp;
   struct action *ap, *ap2;
   struct rule *rp, *rp2, *rbest;
   int nbest, n;
   int i;
   int usesWildcard;
   for(i=0; i<lemp->nstate; i++){
     stp = lemp->sorted[i];
     nbest = 0;
     rbest = 0;
     usesWildcard = 0;
     for(ap=stp->ap; ap; ap=ap->next){
       if( ap->type==SHIFT && ap->sp==lemp->wildcard ){
         usesWildcard = 1;
       }
       if( ap->type!=REDUCE ) continue;
       rp = ap->x.rp;
       if( rp->lhsStart ) continue;
       if( rp==rbest ) continue;
       n = 1;
       for(ap2=ap->next; ap2; ap2=ap2->next){
         if( ap2->type!=REDUCE ) continue;
         rp2 = ap2->x.rp;
         if( rp2==rbest ) continue;
         if( rp2==rp ) n++;
       }
       if( n>nbest ){
         nbest = n;
         rbest = rp;
       }
     }
     /* Do not make a default if the number of rules to default
     ** is not at least 1 or if the wildcard token is a possible
     ** lookahead.
     */
     if( nbest<1 || usesWildcard ) continue;
     /* Combine matching REDUCE actions into a single default */
     for(ap=stp->ap; ap; ap=ap->next){
       if( ap->type==REDUCE && ap->x.rp==rbest ) break;
     }
     assert( ap );
     ap->sp = Symbol_new("{default}");
     for(ap=ap->next; ap; ap=ap->next){
       if( ap->type==REDUCE && ap->x.rp==rbest ) ap->type = NOT_USED;
     }
     stp->ap = Action_sort(stp->ap);
   }
 }
PRIVATE int compute_action (struct lemon * lemp, struct action * ap)
Definition at line 3160 of file lemon.c.
References ACCEPT, ERROR, rule::index, lemon::nrule, lemon::nstate, REDUCE, action::rp, SHIFT, state::statenum, action::stp, action::type, and action::x.
Referenced by ReportTable(), and ResortStates().
 {
   int act;
   switch( ap->type ){
     case SHIFT:  act = ap->x.stp->statenum;            break;
     case REDUCE: act = ap->x.rp->index + lemp->nstate; break;
     case ERROR:  act = lemp->nstate + lemp->nrule;     break;
     case ACCEPT: act = lemp->nstate + lemp->nrule + 1; break;
     default:     act = -1; break;
   }
   return act;
 }
int Configcmp (const char * _a, const char * _b)
Definition at line 4730 of file lemon.c.
References config::dot, rule::index, and config::rp.
Referenced by Configlist_sort(), Configlist_sortbasis(), Configtable_find(), and Configtable_insert().
 {
   const struct config *a = (struct config *) _a;
   const struct config *b = (struct config *) _b;
   int x;
   x = a->rp->index - b->rp->index;
   if( x==0 ) x = a->dot - b->dot;
   return x;
 }
PRIVATE unsigned confighash (struct config * a)
Definition at line 4909 of file lemon.c.
References config::dot, rule::index, and config::rp.
Referenced by Configtable_find(), and Configtable_insert().
 {
   unsigned h=0;
   h = h*571 + a->rp->index*37 + a->dot;
   return h;
 }
struct config * Configlist_add (struct rule * rp, int dot)
Definition at line 1278 of file lemon.c.
References config::bp, config::bplp, Configtable_find(), Configtable_insert(), config::dot, config::fplp, config::fws, newconfig(), config::next, config::rp, SetNew(), and config::stp.
Referenced by Configlist_closure().
  {
   struct config *cfp, model;
   assert( currentend!=0 );
   model.rp = rp;
   model.dot = dot;
   cfp = Configtable_find(&model);
   if( cfp==0 ){
     cfp = newconfig();
     cfp->rp = rp;
     cfp->dot = dot;
     cfp->fws = SetNew();
     cfp->stp = 0;
     cfp->fplp = cfp->bplp = 0;
     cfp->next = 0;
     cfp->bp = 0;
     *currentend = cfp;
     currentend = &cfp->next;
     Configtable_insert(cfp);
   }
   return cfp;
 }
struct config * Configlist_addbasis (struct rule * rp, int dot)
Definition at line 1305 of file lemon.c.
References config::bp, config::bplp, Configtable_find(), Configtable_insert(), config::dot, config::fplp, config::fws, newconfig(), config::next, config::rp, SetNew(), and config::stp.
Referenced by buildshifts(), and FindStates().
 {
   struct config *cfp, model;
   assert( basisend!=0 );
   assert( currentend!=0 );
   model.rp = rp;
   model.dot = dot;
   cfp = Configtable_find(&model);
   if( cfp==0 ){
     cfp = newconfig();
     cfp->rp = rp;
     cfp->dot = dot;
     cfp->fws = SetNew();
     cfp->stp = 0;
     cfp->fplp = cfp->bplp = 0;
     cfp->next = 0;
     cfp->bp = 0;
     *currentend = cfp;
     currentend = &cfp->next;
     *basisend = cfp;
     basisend = &cfp->bp;
     Configtable_insert(cfp);
   }
   return cfp;
 }
struct config * Configlist_basis (void)
Definition at line 1403 of file lemon.c.
Referenced by getstate().
{
   struct config *old;
   old = basis;
   basis = 0;
   basisend = 0;
   return old;
 }
void Configlist_closure (struct lemon * lemp)
Definition at line 1333 of file lemon.c.
References Configlist_add(), config::dot, lemon::errorcnt, ErrorMsg(), lemon::errsym, lemon::filename, symbol::firstset, config::fplp, config::fws, symbol::index, symbol::lambda, LEMON_FALSE, rule::line, MULTITERMINAL, symbol::name, config::next, rule::nextlhs, NONTERMINAL, rule::nrhs, symbol::nsubsym, Plink_add(), rule::rhs, config::rp, symbol::rule, SetAdd(), SetUnion(), symbol::subsym, TERMINAL, and symbol::type.
Referenced by getstate().
 {
   struct config *cfp, *newcfp;
   struct rule *rp, *newrp;
   struct symbol *sp, *xsp;
   int i, dot;
   assert( currentend!=0 );
   for(cfp=current; cfp; cfp=cfp->next){
     rp = cfp->rp;
     dot = cfp->dot;
     if( dot>=rp->nrhs ) continue;
     sp = rp->rhs[dot];
     if( sp->type==NONTERMINAL ){
       if( sp->rule==0 && sp!=lemp->errsym ){
         ErrorMsg(lemp->filename,rp->line,"Nonterminal \"%s\" has no rules.",
           sp->name);
         lemp->errorcnt++;
       }
       for(newrp=sp->rule; newrp; newrp=newrp->nextlhs){
         newcfp = Configlist_add(newrp,0);
         for(i=dot+1; i<rp->nrhs; i++){
           xsp = rp->rhs[i];
           if( xsp->type==TERMINAL ){
             SetAdd(newcfp->fws,xsp->index);
             break;
           }else if( xsp->type==MULTITERMINAL ){
             int k;
             for(k=0; k<xsp->nsubsym; k++){
               SetAdd(newcfp->fws, xsp->subsym[k]->index);
             }
             break;
           }else{
             SetUnion(newcfp->fws,xsp->firstset);
             if( xsp->lambda==LEMON_FALSE ) break;
           }
         }
         if( i==rp->nrhs ) Plink_add(&cfp->fplp,newcfp);
       }
     }
   }
   return;
 }
void Configlist_eat (struct config * cfp)
Definition at line 1412 of file lemon.c.
References config::bplp, deleteconfig(), config::fplp, config::fws, config::next, and SetFree().
Referenced by getstate().
 {
   struct config *nextcfp;
   for(; cfp; cfp=nextcfp){
     nextcfp = cfp->next;
     assert( cfp->fplp==0 );
     assert( cfp->bplp==0 );
     if( cfp->fws ) SetFree(cfp->fws);
     deleteconfig(cfp);
   }
   return;
 }
void Configlist_init (void)
Definition at line 1258 of file lemon.c.
References Configtable_init().
Referenced by FindStates().
                       {
   current = 0;
   currentend = &current;
   basis = 0;
   basisend = &basis;
   Configtable_init();
   return;
 }
void Configlist_reset (void)
Definition at line 1268 of file lemon.c.
References Configtable_clear().
Referenced by buildshifts().
{
   current = 0;
   currentend = &current;
   basis = 0;
   basisend = &basis;
   Configtable_clear(0);
   return;
 }
struct config * Configlist_return (void)
Definition at line 1393 of file lemon.c.
Referenced by getstate().
{
   struct config *old;
   old = current;
   current = 0;
   currentend = 0;
   return old;
 }
void Configlist_sort (void)
Definition at line 1378 of file lemon.c.
References Configcmp(), and config::next.
Referenced by getstate().
                       {
   current = (struct config *)msort((char *)current,(char **)&(current->next),Configcmp);
   currentend = 0;
   return;
 }
void Configlist_sortbasis (void)
Definition at line 1385 of file lemon.c.
References config::bp, and Configcmp().
Referenced by getstate().
{
   basis = (struct config *)msort((char *)current,(char **)&(current->bp),Configcmp);
   basisend = 0;
   return;
 }
void ConfigPrint (FILE * fp, struct config * cfp)
Definition at line 2937 of file lemon.c.
References config::dot, rule::lhs, MULTITERMINAL, symbol::name, rule::nrhs, symbol::nsubsym, rule::rhs, config::rp, symbol::subsym, and symbol::type.
Referenced by ReportOutput().
 {
   struct rule *rp;
   struct symbol *sp;
   int i, j;
   rp = cfp->rp;
   fprintf(fp,"%s ::=",rp->lhs->name);
   for(i=0; i<=rp->nrhs; i++){
     if( i==cfp->dot ) fprintf(fp," *");
     if( i==rp->nrhs ) break;
     sp = rp->rhs[i];
     if( sp->type==MULTITERMINAL ){
       fprintf(fp," %s", sp->subsym[0]->name);
       for(j=1; j<sp->nsubsym; j++){
         fprintf(fp,"|%s",sp->subsym[j]->name);
       }
     }else{
       fprintf(fp," %s", sp->name);
     }
   }
 }
void Configtable_clear (int(*)(struct config *) f)
Definition at line 5032 of file lemon.c.
References s_x4::count, s_x4node::data, s_x4::ht, s_x4::size, and s_x4::tbl.
Referenced by Configlist_reset().
 {
   int i;
   if( x4a==0 || x4a->count==0 ) return;
   if( f ) for(i=0; i<x4a->count; i++) (*f)(x4a->tbl[i].data);
   for(i=0; i<x4a->size; i++) x4a->ht[i] = 0;
   x4a->count = 0;
   return;
 }
struct config * Configtable_find (struct config * key)
Definition at line 5015 of file lemon.c.
References Configcmp(), confighash(), s_x4node::data, s_x4::ht, s_x4node::next, and s_x4::size.
Referenced by Configlist_add(), and Configlist_addbasis().
 {
   int h;
   x4node *np;
   if( x4a==0 ) return 0;
   h = confighash(key) & (x4a->size-1);
   np = x4a->ht[h];
   while( np ){
     if( Configcmp((const char *) np->data,(const char *) key)==0 ) break;
     np = np->next;
   }
   return np ? np->data : 0;
 }
void Configtable_init (void)
Definition at line 4941 of file lemon.c.
References s_x4::count, s_x4::ht, s_x4::size, and s_x4::tbl.
Referenced by Configlist_init().
{
   if( x4a ) return;
   x4a = (struct s_x4*)malloc( sizeof(struct s_x4) );
   if( x4a ){
     x4a->size = 64;
     x4a->count = 0;
     x4a->tbl = (x4node*)calloc(64, sizeof(x4node) + sizeof(x4node*));
     if( x4a->tbl==0 ){
       free(x4a);
       x4a = 0;
     }else{
       int i;
       x4a->ht = (x4node**)&(x4a->tbl[64]);
       for(i=0; i<64; i++) x4a->ht[i] = 0;
     }
   }
 }
int Configtable_insert (struct config * data)
Definition at line 4960 of file lemon.c.
References Configcmp(), confighash(), s_x4::count, s_x4node::data, s_x4node::from, s_x4::ht, s_x4node::next, s_x4::size, and s_x4::tbl.
Referenced by Configlist_add(), and Configlist_addbasis().
 {
   x4node *np;
   unsigned h;
   unsigned ph;
   if( x4a==0 ) return 0;
   ph = confighash(data);
   h = ph & (x4a->size-1);
   np = x4a->ht[h];
   while( np ){
     if( Configcmp((const char *) np->data,(const char *) data)==0 ){
       /* An existing entry with the same key is found. */
       /* Fail because overwrite is not allows. */
       return 0;
     }
     np = np->next;
   }
   if( x4a->count>=x4a->size ){
     /* Need to make the hash table bigger */
     int i,size;
     struct s_x4 array;
     array.size = size = x4a->size*2;
     array.count = x4a->count;
     array.tbl = (x4node*)calloc(size, sizeof(x4node) + sizeof(x4node*));
     if( array.tbl==0 ) return 0;  /* Fail due to malloc failure */
     array.ht = (x4node**)&(array.tbl[size]);
     for(i=0; i<size; i++) array.ht[i] = 0;
     for(i=0; i<x4a->count; i++){
       x4node *oldnp, *newnp;
       oldnp = &(x4a->tbl[i]);
       h = confighash(oldnp->data) & (size-1);
       newnp = &(array.tbl[i]);
       if( array.ht[h] ) array.ht[h]->from = &(newnp->next);
       newnp->next = array.ht[h];
       newnp->data = oldnp->data;
       newnp->from = &(array.ht[h]);
       array.ht[h] = newnp;
     }
     free(x4a->tbl);
     *x4a = array;
   }
   /* Insert the new data */
   h = ph & (x4a->size-1);
   np = &(x4a->tbl[x4a->count++]);
   np->data = data;
   if( x4a->ht[h] ) x4a->ht[h]->from = &(np->next);
   np->next = x4a->ht[h];
   x4a->ht[h] = np;
   np->from = &(x4a->ht[h]);
   return 1;
 }
PRIVATE void deleteconfig (struct config * old)
Definition at line 1251 of file lemon.c.
References config::next.
Referenced by Configlist_eat().
 {
   old->next = freelist;
   freelist = old;
 }
PRIVATE void emit_code (FILE * out, struct rule * rp, struct lemon * lemp, int * lineno)
Definition at line 3498 of file lemon.c.
References rule::code, lemon::filename, rule::line, lemon::nolinenosflag, lemon::outname, and tplt_linedir().
Referenced by ReportTable().
  {
  const char *cp;
  /* Generate code to do the reduce action */
  if( rp->code ){
    if (!lemp->nolinenosflag) { (*lineno)++; tplt_linedir(out,rp->line,lemp->filename); }
    fprintf(out,"{%s",rp->code);
    for(cp=rp->code; *cp; cp++){
      if( *cp=='\n' ) (*lineno)++;
    } /* End loop */
    fprintf(out,"}\n"); (*lineno)++;
    if (!lemp->nolinenosflag) { (*lineno)++; tplt_linedir(out,*lineno,lemp->outname); }
  } /* End if( rp->code ) */
  return;
 }
void emit_destructor_code (FILE * out, struct symbol * sp, struct lemon * lemp, int * lineno)
Definition at line 3296 of file lemon.c.
References symbol::destLineno, symbol::destructor, symbol::dtnum, lemon::filename, lemon::nolinenosflag, lemon::outname, TERMINAL, lemon::tokendest, tplt_linedir(), symbol::type, and lemon::vardest.
Referenced by ReportTable().
  {
  char *cp = 0;
  if( sp->type==TERMINAL ){
    cp = lemp->tokendest;
    if( cp==0 ) return;
    fprintf(out,"{\n"); (*lineno)++;
  }else if( sp->destructor ){
    cp = sp->destructor;
    fprintf(out,"{\n"); (*lineno)++;
    if (!lemp->nolinenosflag) { (*lineno)++; tplt_linedir(out,sp->destLineno,lemp->filename); }
  }else if( lemp->vardest ){
    cp = lemp->vardest;
    if( cp==0 ) return;
    fprintf(out,"{\n"); (*lineno)++;
  }else{
    assert( 0 );  /* Cannot happen */
  }
  for(; *cp; cp++){
    if( *cp=='$' && cp[1]=='$' ){
      fprintf(out,"(yypminor->yy%d)",sp->dtnum);
      cp++;
      continue;
    }
    if( *cp=='\n' ) (*lineno)++;
    fputc(*cp,out);
  }
  fprintf(out,"\n"); (*lineno)++;
  if (!lemp->nolinenosflag) {
    (*lineno)++; tplt_linedir(out,*lineno,lemp->outname);
  }
  fprintf(out,"}\n"); (*lineno)++;
  return;
 }
void ErrorMsg (const char * filename, int lineno, const char * format, ...)
Definition at line 1429 of file lemon.c.
Referenced by Configlist_closure(), FindActions(), FindStates(), Parse(), and translate_code().
{
   va_list ap;
   fprintf(stderr, "%s:%d: ", filename, lineno);
   va_start(ap, format);
   vfprintf(stderr,format,ap);
   va_end(ap);
   fprintf(stderr, "\n");
 }
PRIVATE char* file_makename (struct lemon * lemp, const char * suffix)
Definition at line 2850 of file lemon.c.
References lemon::filename, and lemonStrlen.
Referenced by file_open(), and ReportTable().
 {
   char *name;
   char *cp;
   name = (char*)malloc( lemonStrlen(lemp->filename) + lemonStrlen(suffix) + 5 );
   if( name==0 ){
     fprintf(stderr,"Can't allocate space for a filename.\n");
     exit(1);
   }
   lemon_strcpy(name,lemp->filename);
   cp = strrchr(name,'.');
   if( cp ) *cp = 0;
   lemon_strcat(name,suffix);
   return name;
 }
PRIVATE FILE* file_open (struct lemon * lemp, const char * suffix, const char * mode)
Definition at line 2870 of file lemon.c.
References lemon::errorcnt, file_makename(), and lemon::outname.
Referenced by ReportHeader(), ReportOutput(), and ReportTable().
  {
   FILE *fp;
   if( lemp->outname ) free(lemp->outname);
   lemp->outname = file_makename(lemp, suffix);
   fp = fopen(lemp->outname,mode);
   if( fp==0 && *mode=='w' ){
     fprintf(stderr,"Can't open file \"%s\".\n",lemp->outname);
     lemp->errorcnt++;
     return 0;
   }
   return fp;
 }
void FindActions ()
Referenced by main().
void FindActions (struct lemon * lemp)
Definition at line 1075 of file lemon.c.
References ACCEPT, Action_add(), state::ap, rule::canReduce, state::cfp, config::dot, lemon::errorcnt, ErrorMsg(), lemon::filename, config::fws, LEMON_FALSE, LEMON_TRUE, rule::lhs, lemon::nconflict, rule::next, config::next, action::next, rule::nrhs, lemon::nstate, lemon::nterminal, REDUCE, config::rp, action::rp, lemon::rule, rule::ruleline, SetFind, lemon::sorted, action::sp, lemon::start, Symbol_find(), lemon::symbols, action::type, and action::x.
 {
   int i,j;
   struct config *cfp;
   struct state *stp;
   struct symbol *sp;
   struct rule *rp;
   /* Add all of the reduce actions
   ** A reduce action is added for each element of the followset of
   ** a configuration which has its dot at the extreme right.
   */
   for(i=0; i<lemp->nstate; i++){   /* Loop over all states */
     stp = lemp->sorted[i];
     for(cfp=stp->cfp; cfp; cfp=cfp->next){  /* Loop over all configurations */
       if( cfp->rp->nrhs==cfp->dot ){        /* Is dot at extreme right? */
         for(j=0; j<lemp->nterminal; j++){
           if( SetFind(cfp->fws,j) ){
             /* Add a reduce action to the state "stp" which will reduce by the
             ** rule "cfp->rp" if the lookahead symbol is "lemp->symbols[j]" */
             Action_add(&stp->ap,REDUCE,lemp->symbols[j],(char *)cfp->rp);
           }
         }
       }
     }
   }
   /* Add the accepting token */
   if( lemp->start ){
     sp = Symbol_find(lemp->start);
     if( sp==0 ) sp = lemp->rule->lhs;
   }else{
     sp = lemp->rule->lhs;
   }
   /* Add to the first state (which is always the starting state of the
   ** finite state machine) an action to ACCEPT if the lookahead is the
   ** start nonterminal.  */
   Action_add(&lemp->sorted[0]->ap,ACCEPT,sp,0);
   /* Resolve conflicts */
   for(i=0; i<lemp->nstate; i++){
     struct action *ap, *nap;
     struct state *stp;
     stp = lemp->sorted[i];
     /* assert( stp->ap ); */
     stp->ap = Action_sort(stp->ap);
     for(ap=stp->ap; ap && ap->next; ap=ap->next){
       for(nap=ap->next; nap && nap->sp==ap->sp; nap=nap->next){
          /* The two actions "ap" and "nap" have the same lookahead.
          ** Figure out which one should be used */
          lemp->nconflict += resolve_conflict(ap,nap);
       }
     }
   }
   /* Report an error for each rule that can never be reduced. */
   for(rp=lemp->rule; rp; rp=rp->next) rp->canReduce = LEMON_FALSE;
   for(i=0; i<lemp->nstate; i++){
     struct action *ap;
     for(ap=lemp->sorted[i]->ap; ap; ap=ap->next){
       if( ap->type==REDUCE ) ap->x.rp->canReduce = LEMON_TRUE;
     }
   }
   for(rp=lemp->rule; rp; rp=rp->next){
     if( rp->canReduce ) continue;
     ErrorMsg(lemp->filename,rp->ruleline,"This rule can not be reduced.\n");
     lemp->errorcnt++;
   }
 }
void FindFirstSets ()
Referenced by main().
void FindFirstSets (struct lemon * lemp)
Definition at line 769 of file lemon.c.
References symbol::firstset, symbol::index, symbol::lambda, LEMON_FALSE, LEMON_TRUE, rule::lhs, MULTITERMINAL, rule::next, NONTERMINAL, rule::nrhs, symbol::nsubsym, lemon::nsymbol, lemon::nterminal, rule::rhs, lemon::rule, SetAdd(), SetNew(), SetUnion(), symbol::subsym, lemon::symbols, TERMINAL, and symbol::type.
 {
   int i, j;
   struct rule *rp;
   int progress;
   for(i=0; i<lemp->nsymbol; i++){
     lemp->symbols[i]->lambda = LEMON_FALSE;
   }
   for(i=lemp->nterminal; i<lemp->nsymbol; i++){
     lemp->symbols[i]->firstset = SetNew();
   }
   /* First compute all lambdas */
   do{
     progress = 0;
     for(rp=lemp->rule; rp; rp=rp->next){
       if( rp->lhs->lambda ) continue;
       for(i=0; i<rp->nrhs; i++){
         struct symbol *sp = rp->rhs[i];
         assert( sp->type==NONTERMINAL || sp->lambda==LEMON_FALSE );
         if( sp->lambda==LEMON_FALSE ) break;
       }
       if( i==rp->nrhs ){
         rp->lhs->lambda = LEMON_TRUE;
         progress = 1;
       }
     }
   }while( progress );
   /* Now compute all first sets */
   do{
     struct symbol *s1, *s2;
     progress = 0;
     for(rp=lemp->rule; rp; rp=rp->next){
       s1 = rp->lhs;
       for(i=0; i<rp->nrhs; i++){
         s2 = rp->rhs[i];
         if( s2->type==TERMINAL ){
           progress += SetAdd(s1->firstset,s2->index);
           break;
         }else if( s2->type==MULTITERMINAL ){
           for(j=0; j<s2->nsubsym; j++){
             progress += SetAdd(s1->firstset,s2->subsym[j]->index);
           }
           break;
         }else if( s1==s2 ){
           if( s1->lambda==LEMON_FALSE ) break;
         }else{
           progress += SetUnion(s1->firstset,s2->firstset);
           if( s2->lambda==LEMON_FALSE ) break;
         }
       }
     }
   }while( progress );
   return;
 }
void FindFollowSets ()
Referenced by main().
void FindFollowSets (struct lemon * lemp)
Definition at line 1039 of file lemon.c.
References state::cfp, plink::cfp, COMPLETE, config::fplp, config::fws, INCOMPLETE, config::next, plink::next, lemon::nstate, SetUnion(), lemon::sorted, and config::status.
 {
   int i;
   struct config *cfp;
   struct plink *plp;
   int progress;
   int change;
   for(i=0; i<lemp->nstate; i++){
     for(cfp=lemp->sorted[i]->cfp; cfp; cfp=cfp->next){
       cfp->status = INCOMPLETE;
     }
   }
   do{
     progress = 0;
     for(i=0; i<lemp->nstate; i++){
       for(cfp=lemp->sorted[i]->cfp; cfp; cfp=cfp->next){
         if( cfp->status==COMPLETE ) continue;
         for(plp=cfp->fplp; plp; plp=plp->next){
           change = SetUnion(plp->cfp->fws,cfp->fws);
           if( change ){
             plp->cfp->status = INCOMPLETE;
             progress = 1;
           }
         }
         cfp->status = COMPLETE;
       }
     }
   }while( progress );
 }
void FindLinks ()
Referenced by main().
void FindLinks (struct lemon * lemp)
Definition at line 1004 of file lemon.c.
References config::bplp, state::cfp, plink::cfp, config::fplp, config::next, plink::next, lemon::nstate, Plink_add(), lemon::sorted, and config::stp.
 {
   int i;
   struct config *cfp, *other;
   struct state *stp;
   struct plink *plp;
   /* Housekeeping detail:
   ** Add to every propagate link a pointer back to the state to
   ** which the link is attached. */
   for(i=0; i<lemp->nstate; i++){
     stp = lemp->sorted[i];
     for(cfp=stp->cfp; cfp; cfp=cfp->next){
       cfp->stp = stp;
     }
   }
   /* Convert all backlinks into forward links.  Only the forward
   ** links are used in the follow-set computation. */
   for(i=0; i<lemp->nstate; i++){
     stp = lemp->sorted[i];
     for(cfp=stp->cfp; cfp; cfp=cfp->next){
       for(plp=cfp->bplp; plp; plp=plp->next){
         other = plp->cfp;
         Plink_add(&other->fplp,cfp);
       }
     }
   }
 }
void FindRulePrecedences ()
Referenced by main().
void FindRulePrecedences (struct lemon * xp)
Definition at line 740 of file lemon.c.
References MULTITERMINAL, rule::next, rule::nrhs, symbol::nsubsym, symbol::prec, rule::precsym, rule::rhs, lemon::rule, symbol::subsym, and symbol::type.
 {
   struct rule *rp;
   for(rp=xp->rule; rp; rp=rp->next){
     if( rp->precsym==0 ){
       int i, j;
       for(i=0; i<rp->nrhs && rp->precsym==0; i++){
         struct symbol *sp = rp->rhs[i];
         if( sp->type==MULTITERMINAL ){
           for(j=0; j<sp->nsubsym; j++){
             if( sp->subsym[j]->prec>=0 ){
               rp->precsym = sp->subsym[j];
               break;
             }
           }
         }else if( sp->prec>=0 ){
           rp->precsym = rp->rhs[i];
         }
       }
     }
   }
   return;
 }
void FindStates ()
Referenced by main().
void FindStates (struct lemon * lemp)
Definition at line 832 of file lemon.c.
References Configlist_addbasis(), Configlist_init(), lemon::errorcnt, ErrorMsg(), lemon::filename, config::fws, getstate(), rule::lhs, rule::lhsStart, symbol::name, rule::next, rule::nextlhs, rule::nrhs, rule::rhs, symbol::rule, lemon::rule, SetAdd(), lemon::start, and Symbol_find().
 {
   struct symbol *sp;
   struct rule *rp;
   Configlist_init();
   /* Find the start symbol */
   if( lemp->start ){
     sp = Symbol_find(lemp->start);
     if( sp==0 ){
       ErrorMsg(lemp->filename,0,
 "The specified start symbol \"%s\" is not \
 in a nonterminal of the grammar.  \"%s\" will be used as the start \
 symbol instead.",lemp->start,lemp->rule->lhs->name);
       lemp->errorcnt++;
       sp = lemp->rule->lhs;
     }
   }else{
     sp = lemp->rule->lhs;
   }
   /* Make sure the start symbol doesn't occur on the right-hand side of
   ** any rule.  Report an error if it does.  (YACC would generate a new
   ** start symbol in this case.) */
   for(rp=lemp->rule; rp; rp=rp->next){
     int i;
     for(i=0; i<rp->nrhs; i++){
       if( rp->rhs[i]==sp ){   /* FIX ME:  Deal with multiterminals */
         ErrorMsg(lemp->filename,0,
 "The start symbol \"%s\" occurs on the \
 right-hand side of a rule. This will result in a parser which \
 does not work properly.",sp->name);
         lemp->errorcnt++;
       }
     }
   }
   /* The basis configuration set for the first state
   ** is all rules which have the start symbol as their
   ** left-hand side */
   for(rp=sp->rule; rp; rp=rp->nextlhs){
     struct config *newcfp;
     rp->lhsStart = 1;
     newcfp = Configlist_addbasis(rp,0);
     SetAdd(newcfp->fws,0);
   }
   /* Compute the first state.  All other states will be
   ** computed automatically during the computation of the first one.
   ** The returned pointer to the first state is not used. */
   (void)getstate(lemp);
   return;
 }
PRIVATE struct state * getstate (struct lemon * lemp)
Definition at line 891 of file lemon.c.
References state::ap, config::bp, state::bp, config::bplp, buildshifts(), state::cfp, Configlist_basis(), Configlist_closure(), Configlist_eat(), Configlist_return(), Configlist_sort(), Configlist_sortbasis(), config::fplp, MemoryCheck, lemon::nstate, Plink_copy(), Plink_delete(), State_find(), State_insert(), State_new(), state::statenum, and config::stp.
Referenced by buildshifts(), and FindStates().
 {
   struct config *cfp, *bp;
   struct state *stp;
   /* Extract the sorted basis of the new state.  The basis was constructed
   ** by prior calls to "Configlist_addbasis()". */
   Configlist_sortbasis();
   bp = Configlist_basis();
   /* Get a state with the same basis */
   stp = State_find(bp);
   if( stp ){
     /* A state with the same basis already exists!  Copy all the follow-set
     ** propagation links from the state under construction into the
     ** preexisting state, then return a pointer to the preexisting state */
     struct config *x, *y;
     for(x=bp, y=stp->bp; x && y; x=x->bp, y=y->bp){
       Plink_copy(&y->bplp,x->bplp);
       Plink_delete(x->fplp);
       x->fplp = x->bplp = 0;
     }
     cfp = Configlist_return();
     Configlist_eat(cfp);
   }else{
     /* This really is a new state.  Construct all the details */
     Configlist_closure(lemp);    /* Compute the configuration closure */
     Configlist_sort();           /* Sort the configuration closure */
     cfp = Configlist_return();   /* Get a pointer to the config list */
     stp = State_new();           /* A new state structure */
     MemoryCheck(stp);
     stp->bp = bp;                /* Remember the configuration basis */
     stp->cfp = cfp;              /* Remember the configuration closure */
     stp->statenum = lemp->nstate++; /* Every state gets a sequence number */
     stp->ap = 0;                 /* No actions, yet. */
     State_insert(stp,stp->bp);   /* Add to the state table */
     buildshifts(lemp,stp);       /* Recursively compute successor states */
   }
   return stp;
 }
int has_destructor (struct symbol * sp, struct lemon * lemp)
Definition at line 3339 of file lemon.c.
References symbol::destructor, TERMINAL, lemon::tokendest, symbol::type, and lemon::vardest.
Referenced by translate_code().
 {
   int ret;
   if( sp->type==TERMINAL ){
     ret = lemp->tokendest!=0;
   }else{
     ret = lemp->vardest!=0 || sp->destructor!=0;
   }
   return ret;
 }
int main (int argc, char ** argv)
Definition at line 1485 of file lemon.c.
References lemon::argv0, lemon::basisflag, CompressTables(), lemon::errorcnt, lemon::errsym, lemon::filename, FindActions(), FindFirstSets(), FindFollowSets(), FindLinks(), FindRulePrecedences(), FindStates(), symbol::index, MULTITERMINAL, symbol::name, lemon::nconflict, lemon::nolinenosflag, lemon::nrule, lemon::nstate, lemon::nsymbol, lemon::nterminal, OPT_FLAG, OPT_FSTR, OptArg(), OptInit(), OptNArgs(), Parse(), ReportHeader(), ReportOutput(), ReportTable(), Reprint(), ResortStates(), SetSize(), lemon::sorted, State_arrayof(), State_init(), Strsafe_init(), Symbol_arrayof(), Symbol_count(), Symbol_init(), Symbol_new(), Symbolcmpp(), lemon::symbols, lemon::tablesize, symbol::type, and symbol::useCnt.
 {
   static int version = 0;
   static int rpflag = 0;
   static int basisflag = 0;
   static int compress = 0;
   static int quiet = 0;
   static int statistics = 0;
   static int mhflag = 0;
   static int nolinenosflag = 0;
   static int noResort = 0;
   static struct s_options options[] = {
     {OPT_FLAG, "b", (char*)&basisflag, "Print only the basis in report."},
     {OPT_FLAG, "c", (char*)&compress, "Don't compress the action table."},
     {OPT_FSTR, "D", (char*)handle_D_option, "Define an %ifdef macro."},
     {OPT_FSTR, "T", (char*)handle_T_option, "Specify a template file."},
     {OPT_FLAG, "g", (char*)&rpflag, "Print grammar without actions."},
     {OPT_FLAG, "m", (char*)&mhflag, "Output a makeheaders compatible file."},
     {OPT_FLAG, "l", (char*)&nolinenosflag, "Do not print #line statements."},
     {OPT_FLAG, "p", (char*)&showPrecedenceConflict,
                     "Show conflicts resolved by precedence rules"},
     {OPT_FLAG, "q", (char*)&quiet, "(Quiet) Don't print the report file."},
     {OPT_FLAG, "r", (char*)&noResort, "Do not sort or renumber states"},
     {OPT_FLAG, "s", (char*)&statistics,
                                    "Print parser stats to standard output."},
     {OPT_FLAG, "x", (char*)&version, "Print the version number."},
     {OPT_FLAG,0,0,0}
   };
   int i;
   int exitcode;
   struct lemon lem;
   OptInit(argv,options,stderr);
   if( version ){
      printf("Lemon version 1.0\n");
      exit(0);
   }
   if( OptNArgs()!=1 ){
     fprintf(stderr,"Exactly one filename argument is required.\n");
     exit(1);
   }
   memset(&lem, 0, sizeof(lem));
   lem.errorcnt = 0;
   /* Initialize the machine */
   Strsafe_init();
   Symbol_init();
   State_init();
   lem.argv0 = argv[0];
   lem.filename = OptArg(0);
   lem.basisflag = basisflag;
   lem.nolinenosflag = nolinenosflag;
   Symbol_new("$");
   lem.errsym = Symbol_new("error");
   lem.errsym->useCnt = 0;
   /* Parse the input file */
   Parse(&lem);
   if( lem.errorcnt ) exit(lem.errorcnt);
   if( lem.nrule==0 ){
     fprintf(stderr,"Empty grammar.\n");
     exit(1);
   }
   /* Count and index the symbols of the grammar */
   Symbol_new("{default}");
   lem.nsymbol = Symbol_count();
   lem.symbols = Symbol_arrayof();
   for(i=0; i<lem.nsymbol; i++) lem.symbols[i]->index = i;
   qsort(lem.symbols,lem.nsymbol,sizeof(struct symbol*), Symbolcmpp);
   for(i=0; i<lem.nsymbol; i++) lem.symbols[i]->index = i;
   while( lem.symbols[i-1]->type==MULTITERMINAL ){ i--; }
   assert( strcmp(lem.symbols[i-1]->name,"{default}")==0 );
   lem.nsymbol = i - 1;
   for(i=1; isupper(lem.symbols[i]->name[0]); i++);
   lem.nterminal = i;
   /* Generate a reprint of the grammar, if requested on the command line */
   if( rpflag ){
     Reprint(&lem);
   }else{
     /* Initialize the size for all follow and first sets */
     SetSize(lem.nterminal+1);
     /* Find the precedence for every production rule (that has one) */
     FindRulePrecedences(&lem);
     /* Compute the lambda-nonterminals and the first-sets for every
     ** nonterminal */
     FindFirstSets(&lem);
     /* Compute all LR(0) states.  Also record follow-set propagation
     ** links so that the follow-set can be computed later */
     lem.nstate = 0;
     FindStates(&lem);
     lem.sorted = State_arrayof();
     /* Tie up loose ends on the propagation links */
     FindLinks(&lem);
     /* Compute the follow set of every reducible configuration */
     FindFollowSets(&lem);
     /* Compute the action tables */
     FindActions(&lem);
     /* Compress the action tables */
     if( compress==0 ) CompressTables(&lem);
     /* Reorder and renumber the states so that states with fewer choices
     ** occur at the end.  This is an optimization that helps make the
     ** generated parser tables smaller. */
     if( noResort==0 ) ResortStates(&lem);
     /* Generate a report of the parser generated.  (the "y.output" file) */
     if( !quiet ) ReportOutput(&lem);
     /* Generate the source code for the parser */
     ReportTable(&lem, mhflag);
     /* Produce a header file for use by the scanner.  (This step is
     ** omitted if the "-m" option is used because makeheaders will
     ** generate the file for us.) */
     if( !mhflag ) ReportHeader(&lem);
   }
   if( statistics ){
     printf("Parser statistics: %d terminals, %d nonterminals, %d rules\n",
       lem.nterminal, lem.nsymbol - lem.nterminal, lem.nrule);
     printf("                   %d states, %d parser table entries, %d conflicts\n",
       lem.nstate, lem.tablesize, lem.nconflict);
   }
   if( lem.nconflict > 0 ){
     fprintf(stderr,"%d parsing conflicts.\n",lem.nconflict);
   }
   /* return 0 on success, 1 on failure. */
   exitcode = ((lem.errorcnt > 0) || (lem.nconflict > 0)) ? 1 : 0;
   exit(exitcode);
   return (exitcode);
 }
void memory_error ()
Definition at line 1445 of file lemon.c.
Referenced by SetNew().
                    {
   fprintf(stderr,"Out of memory.  Aborting...\n");
   exit(1);
 }
PRIVATE struct config* newconfig ()
Definition at line 1232 of file lemon.c.
References config::next.
Referenced by Configlist_add(), and Configlist_addbasis().
{
   struct config *newcfg;
   if( freelist==0 ){
     int i;
     int amt = 3;
     freelist = (struct config *)calloc( amt, sizeof(struct config) );
     if( freelist==0 ){
       fprintf(stderr,"Unable to allocate memory for a new configuration.");
       exit(1);
     }
     for(i=0; i<amt-1; i++) freelist[i].next = &freelist[i+1];
     freelist[amt-1].next = 0;
   }
   newcfg = freelist;
   freelist = freelist->next;
   return newcfg;
 }
char * OptArg (int n)
Definition at line 1957 of file lemon.c.
Referenced by main().
 {
   int i;
   i = argindex(n);
   return i>=0 ? argv[i] : 0;
 }
void OptErr (int n)
Definition at line 1964 of file lemon.c.
 {
   int i;
   i = argindex(n);
   if( i>=0 ) errline(i,0,errstream);
 }
int OptInit (char ** a, struct s_options * o, FILE * err)
Definition at line 1920 of file lemon.c.
References OptPrint().
Referenced by main().
 {
   int errcnt = 0;
   argv = a;
   op = o;
   errstream = err;
   if( argv && *argv && op ){
     int i;
     for(i=1; argv[i]; i++){
       if( argv[i][0]=='+' || argv[i][0]=='-' ){
         errcnt += handleflags(i,err);
       }else if( strchr(argv[i],'=') ){
         errcnt += handleswitch(i,err);
       }
     }
   }
   if( errcnt>0 ){
     fprintf(err,"Valid command line options for \"%s\" are:\n",*a);
     OptPrint();
     exit(1);
   }
   return 0;
 }
int OptNArgs (void)
Definition at line 1944 of file lemon.c.
References ISOPT.
Referenced by main().
               {
   int cnt = 0;
   int dashdash = 0;
   int i;
   if( argv!=0 && argv[0]!=0 ){
     for(i=1; argv[i]; i++){
       if( dashdash || !ISOPT(argv[i]) ) cnt++;
       if( strcmp(argv[i],"--")==0 ) dashdash = 1;
     }
   }
   return cnt;
 }
void OptPrint (void)
Definition at line 1971 of file lemon.c.
References s_options::label, lemonStrlen, s_options::message, OPT_DBL, OPT_FDBL, OPT_FFLAG, OPT_FINT, OPT_FLAG, OPT_FSTR, OPT_INT, and OPT_STR.
Referenced by OptInit().
                {
   int i;
   int max, len;
   max = 0;
   for(i=0; op[i].label; i++){
     len = lemonStrlen(op[i].label) + 1;
     switch( op[i].type ){
       case OPT_FLAG:
       case OPT_FFLAG:
         break;
       case OPT_INT:
       case OPT_FINT:
         len += 9;       /* length of "<integer>" */
         break;
       case OPT_DBL:
       case OPT_FDBL:
         len += 6;       /* length of "<real>" */
         break;
       case OPT_STR:
       case OPT_FSTR:
         len += 8;       /* length of "<string>" */
         break;
     }
     if( len>max ) max = len;
   }
   for(i=0; op[i].label; i++){
     switch( op[i].type ){
       case OPT_FLAG:
       case OPT_FFLAG:
         fprintf(errstream,"  -%-*s  %s\n",max,op[i].label,op[i].message);
         break;
       case OPT_INT:
       case OPT_FINT:
         fprintf(errstream,"  %s=<integer>%*s  %s\n",op[i].label,
           (int)(max-lemonStrlen(op[i].label)-9),"",op[i].message);
         break;
       case OPT_DBL:
       case OPT_FDBL:
         fprintf(errstream,"  %s=<real>%*s  %s\n",op[i].label,
           (int)(max-lemonStrlen(op[i].label)-6),"",op[i].message);
         break;
       case OPT_STR:
       case OPT_FSTR:
         fprintf(errstream,"  %s=<string>%*s  %s\n",op[i].label,
           (int)(max-lemonStrlen(op[i].label)-8),"",op[i].message);
         break;
     }
   }
 }
void Parse (struct lemon * lemp)
Definition at line 2633 of file lemon.c.
References lemon::errorcnt, pstate::errorcnt, ErrorMsg(), lemon::filename, pstate::filename, pstate::firstrule, pstate::gp, INITIALIZE, lemon::rule, pstate::state, pstate::tokenlineno, and pstate::tokenstart.
Referenced by main().
 {
   struct pstate ps;
   FILE *fp;
   char *filebuf;
   int filesize;
   int lineno;
   int c;
   char *cp, *nextcp;
   int startline = 0;
   memset(&ps, '\0', sizeof(ps));
   ps.gp = gp;
   ps.filename = gp->filename;
   ps.errorcnt = 0;
   ps.state = INITIALIZE;
   /* Begin by reading the input file */
   fp = fopen(ps.filename,"rb");
   if( fp==0 ){
     ErrorMsg(ps.filename,0,"Can't open this file for reading.");
     gp->errorcnt++;
     return;
   }
   fseek(fp,0,2);
   filesize = ftell(fp);
   rewind(fp);
   filebuf = (char *)malloc( filesize+1 );
   if( filesize>100000000 || filebuf==0 ){
     ErrorMsg(ps.filename,0,"Input file too large.");
     gp->errorcnt++;
     fclose(fp);
     return;
   }
   if( fread(filebuf,1,filesize,fp)!=filesize ){
     ErrorMsg(ps.filename,0,"Can't read in all %d bytes of this file.",
       filesize);
     free(filebuf);
     gp->errorcnt++;
     fclose(fp);
     return;
   }
   fclose(fp);
   filebuf[filesize] = 0;
   /* Make an initial pass through the file to handle %ifdef and %ifndef */
   preprocess_input(filebuf);
   /* Now scan the text of the input file */
   lineno = 1;
   for(cp=filebuf; (c= *cp)!=0; ){
     if( c=='\n' ) lineno++;              /* Keep track of the line number */
     if( isspace(c) ){ cp++; continue; }  /* Skip all white space */
     if( c=='/' && cp[1]=='/' ){          /* Skip C++ style comments */
       cp+=2;
       while( (c= *cp)!=0 && c!='\n' ) cp++;
       continue;
     }
     if( c=='/' && cp[1]=='*' ){          /* Skip C style comments */
       cp+=2;
       while( (c= *cp)!=0 && (c!='/' || cp[-1]!='*') ){
         if( c=='\n' ) lineno++;
         cp++;
       }
       if( c ) cp++;
       continue;
     }
     ps.tokenstart = cp;                /* Mark the beginning of the token */
     ps.tokenlineno = lineno;           /* Linenumber on which token begins */
     if( c=='\"' ){                     /* String literals */
       cp++;
       while( (c= *cp)!=0 && c!='\"' ){
         if( c=='\n' ) lineno++;
         cp++;
       }
       if( c==0 ){
         ErrorMsg(ps.filename,startline,
 "String starting on this line is not terminated before the end of the file.");
         ps.errorcnt++;
         nextcp = cp;
       }else{
         nextcp = cp+1;
       }
     }else if( c=='{' ){               /* A block of C code */
       int level;
       cp++;
       for(level=1; (c= *cp)!=0 && (level>1 || c!='}'); cp++){
         if( c=='\n' ) lineno++;
         else if( c=='{' ) level++;
         else if( c=='}' ) level--;
         else if( c=='/' && cp[1]=='*' ){  /* Skip comments */
           int prevc;
           cp = &cp[2];
           prevc = 0;
           while( (c= *cp)!=0 && (c!='/' || prevc!='*') ){
             if( c=='\n' ) lineno++;
             prevc = c;
             cp++;
           }
         }else if( c=='/' && cp[1]=='/' ){  /* Skip C++ style comments too */
           cp = &cp[2];
           while( (c= *cp)!=0 && c!='\n' ) cp++;
           if( c ) lineno++;
         }else if( c=='\'' || c=='\"' ){    /* String a character literals */
           int startchar, prevc;
           startchar = c;
           prevc = 0;
           for(cp++; (c= *cp)!=0 && (c!=startchar || prevc=='\\'); cp++){
             if( c=='\n' ) lineno++;
             if( prevc=='\\' ) prevc = 0;
             else              prevc = c;
           }
         }
       }
       if( c==0 ){
         ErrorMsg(ps.filename,ps.tokenlineno,
 "C code starting on this line is not terminated before the end of the file.");
         ps.errorcnt++;
         nextcp = cp;
       }else{
         nextcp = cp+1;
       }
     }else if( isalnum(c) ){          /* Identifiers */
       while( (c= *cp)!=0 && (isalnum(c) || c=='_') ) cp++;
       nextcp = cp;
     }else if( c==':' && cp[1]==':' && cp[2]=='=' ){ /* The operator "::=" */
       cp += 3;
       nextcp = cp;
     }else if( (c=='/' || c=='|') && isalpha(cp[1]) ){
       cp += 2;
       while( (c = *cp)!=0 && (isalnum(c) || c=='_') ) cp++;
       nextcp = cp;
     }else{                          /* All other (one character) operators */
       cp++;
       nextcp = cp;
     }
     c = *cp;
     *cp = 0;                        /* Null terminate the token */
     parseonetoken(&ps);             /* Parse the token */
     *cp = c;                        /* Restore the buffer */
     cp = nextcp;
   }
   free(filebuf);                    /* Release the buffer after parsing */
   gp->rule = ps.firstrule;
   gp->errorcnt = ps.errorcnt;
 }
PRIVATE char* pathsearch (char * argv0, char * name, int modemask)
Definition at line 3112 of file lemon.c.
References lemonStrlen.
Referenced by tplt_open().
 {
   const char *pathlist;
   char *pathbufptr;
   char *pathbuf;
   char *path,*cp;
   char c;
 #ifdef __WIN32__
   cp = strrchr(argv0,'\\');
 #else
   cp = strrchr(argv0,'/');
 #endif
   if( cp ){
     c = *cp;
     *cp = 0;
     path = (char *)malloc( lemonStrlen(argv0) + lemonStrlen(name) + 2 );
     if( path ) lemon_sprintf(path,"%s/%s",argv0,name);
     *cp = c;
   }else{
     pathlist = getenv("PATH");
     if( pathlist==0 ) pathlist = ".:/bin:/usr/bin";
     pathbuf = (char *) malloc( lemonStrlen(pathlist) + 1 );
     path = (char *)malloc( lemonStrlen(pathlist)+lemonStrlen(name)+2 );
     if( (pathbuf != 0) && (path!=0) ){
       pathbufptr = pathbuf;
       lemon_strcpy(pathbuf, pathlist);
       while( *pathbuf ){
         cp = strchr(pathbuf,':');
         if( cp==0 ) cp = &pathbuf[lemonStrlen(pathbuf)];
         c = *cp;
         *cp = 0;
         lemon_sprintf(path,"%s/%s",pathbuf,name);
         *cp = c;
         if( c==0 ) pathbuf[0] = 0;
         else pathbuf = &cp[1];
         if( access(path,modemask)==0 ) break;
       }
       free(pathbufptr);
     }
   }
   return path;
 }
void Plink_add (struct plink ** plpp, struct config * cfp)
Definition at line 2808 of file lemon.c.
References plink::cfp, plink::next, and Plink_new().
Referenced by buildshifts(), Configlist_closure(), and FindLinks().
 {
   struct plink *newlink;
   newlink = Plink_new();
   newlink->next = *plpp;
   *plpp = newlink;
   newlink->cfp = cfp;
 }
void Plink_copy (struct plink ** to, struct plink * from)
Definition at line 2818 of file lemon.c.
References plink::next.
Referenced by getstate().
 {
   struct plink *nextpl;
   while( from ){
     nextpl = from->next;
     from->next = *to;
     *to = from;
     from = nextpl;
   }
 }
void Plink_delete (struct plink * plp)
Definition at line 2830 of file lemon.c.
References plink::next.
Referenced by getstate().
 {
   struct plink *nextpl;
   while( plp ){
     nextpl = plp->next;
     plp->next = plink_freelist;
     plink_freelist = plp;
     plp = nextpl;
   }
 }
struct plink * Plink_new (void)
Definition at line 2787 of file lemon.c.
References plink::next.
Referenced by Plink_add().
{
   struct plink *newlink;
   if( plink_freelist==0 ){
     int i;
     int amt = 100;
     plink_freelist = (struct plink *)calloc( amt, sizeof(struct plink) );
     if( plink_freelist==0 ){
       fprintf(stderr,
       "Unable to allocate memory for a new follow-set propagation link.\n");
       exit(1);
     }
     for(i=0; i<amt-1; i++) plink_freelist[i].next = &plink_freelist[i+1];
     plink_freelist[amt-1].next = 0;
   }
   newlink = plink_freelist;
   plink_freelist = plink_freelist->next;
   return newlink;
 }
void print_stack_union (FILE * out, struct lemon * lemp, int * plineno, int mhflag)
Definition at line 3527 of file lemon.c.
References symbol::datatype, symbol::dtnum, lemon::errsym, lemonStrlen, symbol::name, lemon::name, NONTERMINAL, lemon::nsymbol, lemon::symbols, lemon::tokentype, symbol::type, symbol::useCnt, and lemon::vartype.
Referenced by ReportTable().
  {
   int lineno = *plineno;    /* The line number of the output */
   char **types;             /* A hash table of datatypes */
   int arraysize;            /* Size of the "types" array */
   int maxdtlength;          /* Maximum length of any ".datatype" field. */
   char *stddt;              /* Standardized name for a datatype */
   int i,j;                  /* Loop counters */
   unsigned hash;            /* For hashing the name of a type */
   const char *name;         /* Name of the parser */
   /* Allocate and initialize types[] and allocate stddt[] */
   arraysize = lemp->nsymbol * 2;
   types = (char**)calloc( arraysize, sizeof(char*) );
   if( types==0 ){
     fprintf(stderr,"Out of memory.\n");
     exit(1);
   }
   for(i=0; i<arraysize; i++) types[i] = 0;
   maxdtlength = 0;
   if( lemp->vartype ){
     maxdtlength = lemonStrlen(lemp->vartype);
   }
   for(i=0; i<lemp->nsymbol; i++){
     int len;
     struct symbol *sp = lemp->symbols[i];
     if( sp->datatype==0 ) continue;
     len = lemonStrlen(sp->datatype);
     if( len>maxdtlength ) maxdtlength = len;
   }
   stddt = (char*)malloc( maxdtlength*2 + 1 );
   if( stddt==0 ){
     fprintf(stderr,"Out of memory.\n");
     exit(1);
   }
   /* Build a hash table of datatypes. The ".dtnum" field of each symbol
   ** is filled in with the hash index plus 1.  A ".dtnum" value of 0 is
   ** used for terminal symbols.  If there is no %default_type defined then
   ** 0 is also used as the .dtnum value for nonterminals which do not specify
   ** a datatype using the %type directive.
   */
   for(i=0; i<lemp->nsymbol; i++){
     struct symbol *sp = lemp->symbols[i];
     char *cp;
     if( sp==lemp->errsym ){
       sp->dtnum = arraysize+1;
       continue;
     }
     if( sp->type!=NONTERMINAL || (sp->datatype==0 && lemp->vartype==0) ){
       sp->dtnum = 0;
       continue;
     }
     cp = sp->datatype;
     if( cp==0 ) cp = lemp->vartype;
     j = 0;
     while( isspace(*cp) ) cp++;
     while( *cp ) stddt[j++] = *cp++;
     while( j>0 && isspace(stddt[j-1]) ) j--;
     stddt[j] = 0;
     if( lemp->tokentype && strcmp(stddt, lemp->tokentype)==0 ){
       sp->dtnum = 0;
       continue;
     }
     hash = 0;
     for(j=0; stddt[j]; j++){
       hash = hash*53 + stddt[j];
     }
     hash = (hash & 0x7fffffff)%arraysize;
     while( types[hash] ){
       if( strcmp(types[hash],stddt)==0 ){
         sp->dtnum = hash + 1;
         break;
       }
       hash++;
       if( hash>=(unsigned)arraysize ) hash = 0;
     }
     if( types[hash]==0 ){
       sp->dtnum = hash + 1;
       types[hash] = (char*)malloc( lemonStrlen(stddt)+1 );
       if( types[hash]==0 ){
         fprintf(stderr,"Out of memory.\n");
         exit(1);
       }
       lemon_strcpy(types[hash],stddt);
     }
   }
   /* Print out the definition of YYTOKENTYPE and YYMINORTYPE */
   name = lemp->name ? lemp->name : "Parse";
   lineno = *plineno;
   if( mhflag ){ fprintf(out,"#if INTERFACE\n"); lineno++; }
   fprintf(out,"#define %sTOKENTYPE %s\n",name,
     lemp->tokentype?lemp->tokentype:"void*");  lineno++;
   if( mhflag ){ fprintf(out,"#endif\n"); lineno++; }
   fprintf(out,"typedef union {\n"); lineno++;
   fprintf(out,"  int yyinit;\n"); lineno++;
   fprintf(out,"  %sTOKENTYPE yy0;\n",name); lineno++;
   for(i=0; i<arraysize; i++){
     if( types[i]==0 ) continue;
     fprintf(out,"  %s yy%d;\n",types[i],i+1); lineno++;
     free(types[i]);
   }
   if( lemp->errsym->useCnt ){
     fprintf(out,"  int yy%d;\n",lemp->errsym->dtnum); lineno++;
   }
   free(stddt);
   free(types);
   fprintf(out,"} YYMINORTYPE;\n"); lineno++;
   *plineno = lineno;
 }
int PrintAction (struct action * ap, FILE * fp, int indent)
Definition at line 2998 of file lemon.c.
References ACCEPT, ERROR, rule::index, symbol::name, NOT_USED, RD_RESOLVED, REDUCE, action::rp, RRCONFLICT, SH_RESOLVED, SHIFT, action::sp, SRCONFLICT, SSCONFLICT, state::statenum, action::stp, action::type, and action::x.
Referenced by ReportOutput().
{
   int result = 1;
   switch( ap->type ){
     case SHIFT:
       fprintf(fp,"%*s shift  %d",indent,ap->sp->name,ap->x.stp->statenum);
       break;
     case REDUCE:
       fprintf(fp,"%*s reduce %d",indent,ap->sp->name,ap->x.rp->index);
       break;
     case ACCEPT:
       fprintf(fp,"%*s accept",indent,ap->sp->name);
       break;
     case ERROR:
       fprintf(fp,"%*s error",indent,ap->sp->name);
       break;
     case SRCONFLICT:
     case RRCONFLICT:
       fprintf(fp,"%*s reduce %-3d ** Parsing conflict **",
         indent,ap->sp->name,ap->x.rp->index);
       break;
     case SSCONFLICT:
       fprintf(fp,"%*s shift  %-3d ** Parsing conflict **",
         indent,ap->sp->name,ap->x.stp->statenum);
       break;
     case SH_RESOLVED:
       if( showPrecedenceConflict ){
         fprintf(fp,"%*s shift  %-3d -- dropped by precedence",
                 indent,ap->sp->name,ap->x.stp->statenum);
       }else{
         result = 0;
       }
       break;
     case RD_RESOLVED:
       if( showPrecedenceConflict ){
         fprintf(fp,"%*s reduce %-3d -- dropped by precedence",
                 indent,ap->sp->name,ap->x.rp->index);
       }else{
         result = 0;
       }
       break;
     case NOT_USED:
       result = 0;
       break;
   }
   return result;
 }
void ReportHeader (struct lemon * lemp)
Definition at line 4159 of file lemon.c.
References file_open(), rule::line, LINESIZE, symbol::name, lemon::nterminal, lemon::symbols, and lemon::tokenprefix.
Referenced by main().
 {
   FILE *out, *in;
   const char *prefix;
   char line[LINESIZE];
   char pattern[LINESIZE];
   int i;
   if( lemp->tokenprefix ) prefix = lemp->tokenprefix;
   else                    prefix = "";
   in = file_open(lemp,".h","rb");
   if( in ){
     int nextChar;
     for(i=1; i<lemp->nterminal && fgets(line,LINESIZE,in); i++){
       lemon_sprintf(pattern,"#define %s%-30s %3d\n",
                     prefix,lemp->symbols[i]->name,i);
       if( strcmp(line,pattern) ) break;
     }
     nextChar = fgetc(in);
     fclose(in);
     if( i==lemp->nterminal && nextChar==EOF ){
       /* No change in the file.  Don't rewrite it. */
       return;
     }
   }
   out = file_open(lemp,".h","wb");
   if( out ){
     for(i=1; i<lemp->nterminal; i++){
       fprintf(out,"#define %s%-30s %3d\n",prefix,lemp->symbols[i]->name,i);
     }
     fclose(out);
   }
   return;
 }
void ReportOutput (struct lemon * lemp)
Definition at line 3046 of file lemon.c.
References state::ap, lemon::basisflag, config::bp, state::bp, config::bplp, state::cfp, ConfigPrint(), config::dot, file_open(), symbol::firstset, config::fplp, config::fws, rule::index, symbol::lambda, symbol::name, config::next, action::next, NONTERMINAL, rule::nrhs, lemon::nstate, lemon::nsymbol, lemon::nterminal, PrintAction(), config::rp, SetFind, lemon::sorted, state::statenum, lemon::symbols, and symbol::type.
Referenced by main().
 {
   int i;
   struct state *stp;
   struct config *cfp;
   struct action *ap;
   FILE *fp;
   fp = file_open(lemp,".out","wb");
   if( fp==0 ) return;
   for(i=0; i<lemp->nstate; i++){
     stp = lemp->sorted[i];
     fprintf(fp,"State %d:\n",stp->statenum);
     if( lemp->basisflag ) cfp=stp->bp;
     else                  cfp=stp->cfp;
     while( cfp ){
       char buf[20];
       if( cfp->dot==cfp->rp->nrhs ){
         lemon_sprintf(buf,"(%d)",cfp->rp->index);
         fprintf(fp,"    %5s ",buf);
       }else{
         fprintf(fp,"          ");
       }
       ConfigPrint(fp,cfp);
       fprintf(fp,"\n");
 #if 0
       SetPrint(fp,cfp->fws,lemp);
       PlinkPrint(fp,cfp->fplp,"To  ");
       PlinkPrint(fp,cfp->bplp,"From");
 #endif
       if( lemp->basisflag ) cfp=cfp->bp;
       else                  cfp=cfp->next;
     }
     fprintf(fp,"\n");
     for(ap=stp->ap; ap; ap=ap->next){
       if( PrintAction(ap,fp,30) ) fprintf(fp,"\n");
     }
     fprintf(fp,"\n");
   }
   fprintf(fp, "----------------------------------------------------\n");
   fprintf(fp, "Symbols:\n");
   for(i=0; i<lemp->nsymbol; i++){
     int j;
     struct symbol *sp;
     sp = lemp->symbols[i];
     fprintf(fp, "  %3d: %s", i, sp->name);
     if( sp->type==NONTERMINAL ){
       fprintf(fp, ":");
       if( sp->lambda ){
         fprintf(fp, " <lambda>");
       }
       for(j=0; j<lemp->nterminal; j++){
         if( sp->firstset && SetFind(sp->firstset, j) ){
           fprintf(fp, " %s", lemp->symbols[j]->name);
         }
       }
     }
     fprintf(fp, "\n");
   }
   fclose(fp);
   return;
 }
void ReportTable (struct lemon * lemp, int mhflag)
Definition at line 3715 of file lemon.c.
References lemon::accept, acttab_action(), acttab_alloc(), acttab_insert(), acttab_size, acttab_yyaction, acttab_yylookahead, state::ap, lemon::arg, rule::code, compute_action(), symbol::destructor, symbol::dtnum, emit_code(), emit_destructor_code(), lemon::error, lemon::errsym, lemon::extracode, lemon::failure, symbol::fallback, file_makename(), file_open(), lemon::has_fallback, state::iDflt, lemon::include, symbol::index, rule::index, state::iNtOfst, axset::iOrder, axset::isTkn, state::iTknOfst, lemonStrlen, rule::lhs, LINESIZE, axset::nAction, symbol::name, lemon::name, rule::next, action::next, state::nNtAct, NO_OFFSET, rule::nrhs, lemon::nrule, lemon::nstate, lemon::nsymbol, lemon::nterminal, state::nTknAct, lemon::overflow, print_stack_union(), lemon::rule, lemon::sorted, action::sp, lemon::stacksize, axset::stp, lemon::symbols, TERMINAL, lemon::tokendest, lemon::tokenprefix, tplt_open(), tplt_print(), tplt_xfer(), translate_code(), symbol::type, symbol::useCnt, lemon::vardest, and lemon::wildcard.
Referenced by main().
  {
   FILE *out, *in;
   char line[LINESIZE];
   int  lineno;
   struct state *stp;
   struct action *ap;
   struct rule *rp;
   struct acttab *pActtab;
   int i, j, n;
   const char *name;
   int mnTknOfst, mxTknOfst;
   int mnNtOfst, mxNtOfst;
   struct axset *ax;
   in = tplt_open(lemp);
   if( in==0 ) return;
   out = file_open(lemp,".c","wb");
   if( out==0 ){
     fclose(in);
     return;
   }
   lineno = 1;
   tplt_xfer(lemp->name,in,out,&lineno);
   /* Generate the include code, if any */
   tplt_print(out,lemp,lemp->include,&lineno);
   if( mhflag ){
     char *name = file_makename(lemp, ".h");
     fprintf(out,"#include \"%s\"\n", name); lineno++;
     free(name);
   }
   tplt_xfer(lemp->name,in,out,&lineno);
   /* Generate #defines for all tokens */
   if( mhflag ){
     const char *prefix;
     fprintf(out,"#if INTERFACE\n"); lineno++;
     if( lemp->tokenprefix ) prefix = lemp->tokenprefix;
     else                    prefix = "";
     for(i=1; i<lemp->nterminal; i++){
       fprintf(out,"#define %s%-30s %2d\n",prefix,lemp->symbols[i]->name,i);
       lineno++;
     }
     fprintf(out,"#endif\n"); lineno++;
   }
   tplt_xfer(lemp->name,in,out,&lineno);
   /* Generate the defines */
   fprintf(out,"#define YYCODETYPE %s\n",
     minimum_size_type(0, lemp->nsymbol+1)); lineno++;
   fprintf(out,"#define YYNOCODE %d\n",lemp->nsymbol+1);  lineno++;
   fprintf(out,"#define YYACTIONTYPE %s\n",
     minimum_size_type(0, lemp->nstate+lemp->nrule+5));  lineno++;
   if( lemp->wildcard ){
     fprintf(out,"#define YYWILDCARD %d\n",
        lemp->wildcard->index); lineno++;
   }
   print_stack_union(out,lemp,&lineno,mhflag);
   fprintf(out, "#ifndef YYSTACKDEPTH\n"); lineno++;
   if( lemp->stacksize ){
     fprintf(out,"#define YYSTACKDEPTH %s\n",lemp->stacksize);  lineno++;
   }else{
     fprintf(out,"#define YYSTACKDEPTH 100\n");  lineno++;
   }
   fprintf(out, "#endif\n"); lineno++;
   if( mhflag ){
     fprintf(out,"#if INTERFACE\n"); lineno++;
   }
   name = lemp->name ? lemp->name : "Parse";
   if( lemp->arg && lemp->arg[0] ){
     int i;
     i = lemonStrlen(lemp->arg);
     while( i>=1 && isspace(lemp->arg[i-1]) ) i--;
     while( i>=1 && (isalnum(lemp->arg[i-1]) || lemp->arg[i-1]=='_') ) i--;
     fprintf(out,"#define %sARG_SDECL %s;\n",name,lemp->arg);  lineno++;
     fprintf(out,"#define %sARG_PDECL ,%s\n",name,lemp->arg);  lineno++;
     fprintf(out,"#define %sARG_FETCH %s = yypParser->%s\n",
                  name,lemp->arg,&lemp->arg[i]);  lineno++;
     fprintf(out,"#define %sARG_STORE yypParser->%s = %s\n",
                  name,&lemp->arg[i],&lemp->arg[i]);  lineno++;
   }else{
     fprintf(out,"#define %sARG_SDECL\n",name);  lineno++;
     fprintf(out,"#define %sARG_PDECL\n",name);  lineno++;
     fprintf(out,"#define %sARG_FETCH\n",name); lineno++;
     fprintf(out,"#define %sARG_STORE\n",name); lineno++;
   }
   if( mhflag ){
     fprintf(out,"#endif\n"); lineno++;
   }
   fprintf(out,"#define YYNSTATE %d\n",lemp->nstate);  lineno++;
   fprintf(out,"#define YYNRULE %d\n",lemp->nrule);  lineno++;
   if( lemp->errsym->useCnt ){
     fprintf(out,"#define YYERRORSYMBOL %d\n",lemp->errsym->index);  lineno++;
     fprintf(out,"#define YYERRSYMDT yy%d\n",lemp->errsym->dtnum);  lineno++;
   }
   if( lemp->has_fallback ){
     fprintf(out,"#define YYFALLBACK 1\n");  lineno++;
   }
   tplt_xfer(lemp->name,in,out,&lineno);
   /* Generate the action table and its associates:
   **
   **  yy_action[]        A single table containing all actions.
   **  yy_lookahead[]     A table containing the lookahead for each entry in
   **                     yy_action.  Used to detect hash collisions.
   **  yy_shift_ofst[]    For each state, the offset into yy_action for
   **                     shifting terminals.
   **  yy_reduce_ofst[]   For each state, the offset into yy_action for
   **                     shifting non-terminals after a reduce.
   **  yy_default[]       Default action for each state.
   */
   /* Compute the actions on all states and count them up */
   ax = (struct axset *) calloc(lemp->nstate*2, sizeof(ax[0]));
   if( ax==0 ){
     fprintf(stderr,"malloc failed\n");
     exit(1);
   }
   for(i=0; i<lemp->nstate; i++){
     stp = lemp->sorted[i];
     ax[i*2].stp = stp;
     ax[i*2].isTkn = 1;
     ax[i*2].nAction = stp->nTknAct;
     ax[i*2+1].stp = stp;
     ax[i*2+1].isTkn = 0;
     ax[i*2+1].nAction = stp->nNtAct;
   }
   mxTknOfst = mnTknOfst = 0;
   mxNtOfst = mnNtOfst = 0;
   /* Compute the action table.  In order to try to keep the size of the
   ** action table to a minimum, the heuristic of placing the largest action
   ** sets first is used.
   */
   for(i=0; i<lemp->nstate*2; i++) ax[i].iOrder = i;
   qsort(ax, lemp->nstate*2, sizeof(ax[0]), axset_compare);
   pActtab = acttab_alloc();
   for(i=0; i<lemp->nstate*2 && ax[i].nAction>0; i++){
     stp = ax[i].stp;
     if( ax[i].isTkn ){
       for(ap=stp->ap; ap; ap=ap->next){
         int action;
         if( ap->sp->index>=lemp->nterminal ) continue;
         action = compute_action(lemp, ap);
         if( action<0 ) continue;
         acttab_action(pActtab, ap->sp->index, action);
       }
       stp->iTknOfst = acttab_insert(pActtab);
       if( stp->iTknOfst<mnTknOfst ) mnTknOfst = stp->iTknOfst;
       if( stp->iTknOfst>mxTknOfst ) mxTknOfst = stp->iTknOfst;
     }else{
       for(ap=stp->ap; ap; ap=ap->next){
         int action;
         if( ap->sp->index<lemp->nterminal ) continue;
         if( ap->sp->index==lemp->nsymbol ) continue;
         action = compute_action(lemp, ap);
         if( action<0 ) continue;
         acttab_action(pActtab, ap->sp->index, action);
       }
       stp->iNtOfst = acttab_insert(pActtab);
       if( stp->iNtOfst<mnNtOfst ) mnNtOfst = stp->iNtOfst;
       if( stp->iNtOfst>mxNtOfst ) mxNtOfst = stp->iNtOfst;
     }
   }
   free(ax);
   /* Output the yy_action table */
   n = acttab_size(pActtab);
   fprintf(out,"#define YY_ACTTAB_COUNT (%d)\n", n); lineno++;
   fprintf(out,"static const YYACTIONTYPE yy_action[] = {\n"); lineno++;
   for(i=j=0; i<n; i++){
     int action = acttab_yyaction(pActtab, i);
     if( action<0 ) action = lemp->nstate + lemp->nrule + 2;
     if( j==0 ) fprintf(out," /* %5d */ ", i);
     fprintf(out, " %4d,", action);
     if( j==9 || i==n-1 ){
       fprintf(out, "\n"); lineno++;
       j = 0;
     }else{
       j++;
     }
   }
   fprintf(out, "};\n"); lineno++;
   /* Output the yy_lookahead table */
   fprintf(out,"static const YYCODETYPE yy_lookahead[] = {\n"); lineno++;
   for(i=j=0; i<n; i++){
     int la = acttab_yylookahead(pActtab, i);
     if( la<0 ) la = lemp->nsymbol;
     if( j==0 ) fprintf(out," /* %5d */ ", i);
     fprintf(out, " %4d,", la);
     if( j==9 || i==n-1 ){
       fprintf(out, "\n"); lineno++;
       j = 0;
     }else{
       j++;
     }
   }
   fprintf(out, "};\n"); lineno++;
   /* Output the yy_shift_ofst[] table */
   fprintf(out, "#define YY_SHIFT_USE_DFLT (%d)\n", mnTknOfst-1); lineno++;
   n = lemp->nstate;
   while( n>0 && lemp->sorted[n-1]->iTknOfst==NO_OFFSET ) n--;
   fprintf(out, "#define YY_SHIFT_COUNT (%d)\n", n-1); lineno++;
   fprintf(out, "#define YY_SHIFT_MIN   (%d)\n", mnTknOfst); lineno++;
   fprintf(out, "#define YY_SHIFT_MAX   (%d)\n", mxTknOfst); lineno++;
   fprintf(out, "static const %s yy_shift_ofst[] = {\n",
           minimum_size_type(mnTknOfst-1, mxTknOfst)); lineno++;
   for(i=j=0; i<n; i++){
     int ofst;
     stp = lemp->sorted[i];
     ofst = stp->iTknOfst;
     if( ofst==NO_OFFSET ) ofst = mnTknOfst - 1;
     if( j==0 ) fprintf(out," /* %5d */ ", i);
     fprintf(out, " %4d,", ofst);
     if( j==9 || i==n-1 ){
       fprintf(out, "\n"); lineno++;
       j = 0;
     }else{
       j++;
     }
   }
   fprintf(out, "};\n"); lineno++;
   /* Output the yy_reduce_ofst[] table */
   fprintf(out, "#define YY_REDUCE_USE_DFLT (%d)\n", mnNtOfst-1); lineno++;
   n = lemp->nstate;
   while( n>0 && lemp->sorted[n-1]->iNtOfst==NO_OFFSET ) n--;
   fprintf(out, "#define YY_REDUCE_COUNT (%d)\n", n-1); lineno++;
   fprintf(out, "#define YY_REDUCE_MIN   (%d)\n", mnNtOfst); lineno++;
   fprintf(out, "#define YY_REDUCE_MAX   (%d)\n", mxNtOfst); lineno++;
   fprintf(out, "static const %s yy_reduce_ofst[] = {\n",
           minimum_size_type(mnNtOfst-1, mxNtOfst)); lineno++;
   for(i=j=0; i<n; i++){
     int ofst;
     stp = lemp->sorted[i];
     ofst = stp->iNtOfst;
     if( ofst==NO_OFFSET ) ofst = mnNtOfst - 1;
     if( j==0 ) fprintf(out," /* %5d */ ", i);
     fprintf(out, " %4d,", ofst);
     if( j==9 || i==n-1 ){
       fprintf(out, "\n"); lineno++;
       j = 0;
     }else{
       j++;
     }
   }
   fprintf(out, "};\n"); lineno++;
   /* Output the default action table */
   fprintf(out, "static const YYACTIONTYPE yy_default[] = {\n"); lineno++;
   n = lemp->nstate;
   for(i=j=0; i<n; i++){
     stp = lemp->sorted[i];
     if( j==0 ) fprintf(out," /* %5d */ ", i);
     fprintf(out, " %4d,", stp->iDflt);
     if( j==9 || i==n-1 ){
       fprintf(out, "\n"); lineno++;
       j = 0;
     }else{
       j++;
     }
   }
   fprintf(out, "};\n"); lineno++;
   tplt_xfer(lemp->name,in,out,&lineno);
   /* Generate the table of fallback tokens.
   */
   if( lemp->has_fallback ){
     int mx = lemp->nterminal - 1;
     while( mx>0 && lemp->symbols[mx]->fallback==0 ){ mx--; }
     for(i=0; i<=mx; i++){
       struct symbol *p = lemp->symbols[i];
       if( p->fallback==0 ){
         fprintf(out, "    0,  /* %10s => nothing */\n", p->name);
       }else{
         fprintf(out, "  %3d,  /* %10s => %s */\n", p->fallback->index,
           p->name, p->fallback->name);
       }
       lineno++;
     }
   }
   tplt_xfer(lemp->name, in, out, &lineno);
   /* Generate a table containing the symbolic name of every symbol
   */
   for(i=0; i<lemp->nsymbol; i++){
     lemon_sprintf(line,"\"%s\",",lemp->symbols[i]->name);
     fprintf(out,"  %-15s",line);
     if( (i&3)==3 ){ fprintf(out,"\n"); lineno++; }
   }
   if( (i&3)!=0 ){ fprintf(out,"\n"); lineno++; }
   tplt_xfer(lemp->name,in,out,&lineno);
   /* Generate a table containing a text string that describes every
   ** rule in the rule set of the grammar.  This information is used
   ** when tracing REDUCE actions.
   */
   for(i=0, rp=lemp->rule; rp; rp=rp->next, i++){
     assert( rp->index==i );
     fprintf(out," /* %3d */ \"", i);
     writeRuleText(out, rp);
     fprintf(out,"\",\n"); lineno++;
   }
   tplt_xfer(lemp->name,in,out,&lineno);
   /* Generate code which executes every time a symbol is popped from
   ** the stack while processing errors or while destroying the parser.
   ** (In other words, generate the %destructor actions)
   */
   if( lemp->tokendest ){
     int once = 1;
     for(i=0; i<lemp->nsymbol; i++){
       struct symbol *sp = lemp->symbols[i];
       if( sp==0 || sp->type!=TERMINAL ) continue;
       if( once ){
         fprintf(out, "      /* TERMINAL Destructor */\n"); lineno++;
         once = 0;
       }
       fprintf(out,"    case %d: /* %s */\n", sp->index, sp->name); lineno++;
     }
     for(i=0; i<lemp->nsymbol && lemp->symbols[i]->type!=TERMINAL; i++);
     if( i<lemp->nsymbol ){
       emit_destructor_code(out,lemp->symbols[i],lemp,&lineno);
       fprintf(out,"      break;\n"); lineno++;
     }
   }
   if( lemp->vardest ){
     struct symbol *dflt_sp = 0;
     int once = 1;
     for(i=0; i<lemp->nsymbol; i++){
       struct symbol *sp = lemp->symbols[i];
       if( sp==0 || sp->type==TERMINAL ||
           sp->index<=0 || sp->destructor!=0 ) continue;
       if( once ){
         fprintf(out, "      /* Default NON-TERMINAL Destructor */\n"); lineno++;
         once = 0;
       }
       fprintf(out,"    case %d: /* %s */\n", sp->index, sp->name); lineno++;
       dflt_sp = sp;
     }
     if( dflt_sp!=0 ){
       emit_destructor_code(out,dflt_sp,lemp,&lineno);
     }
     fprintf(out,"      break;\n"); lineno++;
   }
   for(i=0; i<lemp->nsymbol; i++){
     struct symbol *sp = lemp->symbols[i];
     if( sp==0 || sp->type==TERMINAL || sp->destructor==0 ) continue;
     fprintf(out,"    case %d: /* %s */\n", sp->index, sp->name); lineno++;
     /* Combine duplicate destructors into a single case */
     for(j=i+1; j<lemp->nsymbol; j++){
       struct symbol *sp2 = lemp->symbols[j];
       if( sp2 && sp2->type!=TERMINAL && sp2->destructor
           && sp2->dtnum==sp->dtnum
           && strcmp(sp->destructor,sp2->destructor)==0 ){
          fprintf(out,"    case %d: /* %s */\n",
                  sp2->index, sp2->name); lineno++;
          sp2->destructor = 0;
       }
     }
     emit_destructor_code(out,lemp->symbols[i],lemp,&lineno);
     fprintf(out,"      break;\n"); lineno++;
   }
   tplt_xfer(lemp->name,in,out,&lineno);
   /* Generate code which executes whenever the parser stack overflows */
   tplt_print(out,lemp,lemp->overflow,&lineno);
   tplt_xfer(lemp->name,in,out,&lineno);
   /* Generate the table of rule information
   **
   ** Note: This code depends on the fact that rules are number
   ** sequentually beginning with 0.
   */
   for(rp=lemp->rule; rp; rp=rp->next){
     fprintf(out,"  { %d, %d },\n",rp->lhs->index,rp->nrhs); lineno++;
   }
   tplt_xfer(lemp->name,in,out,&lineno);
   /* Generate code which execution during each REDUCE action */
   for(rp=lemp->rule; rp; rp=rp->next){
     translate_code(lemp, rp);
   }
   /* First output rules other than the default: rule */
   for(rp=lemp->rule; rp; rp=rp->next){
     struct rule *rp2;               /* Other rules with the same action */
     if( rp->code==0 ) continue;
     if( rp->code[0]=='\n' && rp->code[1]==0 ) continue; /* Will be default: */
     fprintf(out,"      case %d: /* ", rp->index);
     writeRuleText(out, rp);
     fprintf(out, " */\n"); lineno++;
     for(rp2=rp->next; rp2; rp2=rp2->next){
       if( rp2->code==rp->code ){
         fprintf(out,"      case %d: /* ", rp2->index);
         writeRuleText(out, rp2);
         fprintf(out," */ yytestcase(yyruleno==%d);\n", rp2->index); lineno++;
         rp2->code = 0;
       }
     }
     emit_code(out,rp,lemp,&lineno);
     fprintf(out,"        break;\n"); lineno++;
     rp->code = 0;
   }
   /* Finally, output the default: rule.  We choose as the default: all
   ** empty actions. */
   fprintf(out,"      default:\n"); lineno++;
   for(rp=lemp->rule; rp; rp=rp->next){
     if( rp->code==0 ) continue;
     assert( rp->code[0]=='\n' && rp->code[1]==0 );
     fprintf(out,"      /* (%d) ", rp->index);
     writeRuleText(out, rp);
     fprintf(out, " */ yytestcase(yyruleno==%d);\n", rp->index); lineno++;
   }
   fprintf(out,"        break;\n"); lineno++;
   tplt_xfer(lemp->name,in,out,&lineno);
   /* Generate code which executes if a parse fails */
   tplt_print(out,lemp,lemp->failure,&lineno);
   tplt_xfer(lemp->name,in,out,&lineno);
   /* Generate code which executes when a syntax error occurs */
   tplt_print(out,lemp,lemp->error,&lineno);
   tplt_xfer(lemp->name,in,out,&lineno);
   /* Generate code which executes when the parser accepts its input */
   tplt_print(out,lemp,lemp->accept,&lineno);
   tplt_xfer(lemp->name,in,out,&lineno);
   /* Append any addition code the user desires */
   tplt_print(out,lemp,lemp->extracode,&lineno);
   fclose(in);
   fclose(out);
   return;
 }
void Reprint (struct lemon * lemp)
Definition at line 2890 of file lemon.c.
References lemon::filename, symbol::index, lemonStrlen, rule::lhs, MULTITERMINAL, symbol::name, rule::next, rule::nrhs, symbol::nsubsym, lemon::nsymbol, rule::precsym, rule::rhs, lemon::rule, symbol::subsym, lemon::symbols, and symbol::type.
Referenced by main().
 {
   struct rule *rp;
   struct symbol *sp;
   int i, j, maxlen, len, ncolumns, skip;
   printf("// Reprint of input file \"%s\".\n// Symbols:\n",lemp->filename);
   maxlen = 10;
   for(i=0; i<lemp->nsymbol; i++){
     sp = lemp->symbols[i];
     len = lemonStrlen(sp->name);
     if( len>maxlen ) maxlen = len;
   }
   ncolumns = 76/(maxlen+5);
   if( ncolumns<1 ) ncolumns = 1;
   skip = (lemp->nsymbol + ncolumns - 1)/ncolumns;
   for(i=0; i<skip; i++){
     printf("//");
     for(j=i; j<lemp->nsymbol; j+=skip){
       sp = lemp->symbols[j];
       assert( sp->index==j );
       printf(" %3d %-*.*s",j,maxlen,maxlen,sp->name);
     }
     printf("\n");
   }
   for(rp=lemp->rule; rp; rp=rp->next){
     printf("%s",rp->lhs->name);
     /*    if( rp->lhsalias ) printf("(%s)",rp->lhsalias); */
     printf(" ::=");
     for(i=0; i<rp->nrhs; i++){
       sp = rp->rhs[i];
       if( sp->type==MULTITERMINAL ){
         printf(" %s", sp->subsym[0]->name);
         for(j=1; j<sp->nsubsym; j++){
           printf("|%s", sp->subsym[j]->name);
         }
       }else{
         printf(" %s", sp->name);
       }
       /* if( rp->rhsalias[i] ) printf("(%s)",rp->rhsalias[i]); */
     }
     printf(".");
     if( rp->precsym ) printf(" [%s]",rp->precsym->name);
     /* if( rp->code ) printf("\n    %s",rp->code); */
     printf("\n");
   }
 }
void ResortStates (struct lemon * lemp)
Definition at line 4285 of file lemon.c.
References state::ap, compute_action(), state::iDflt, symbol::index, state::iNtOfst, state::iTknOfst, action::next, state::nNtAct, NO_OFFSET, lemon::nrule, lemon::nstate, lemon::nsymbol, lemon::nterminal, state::nTknAct, lemon::sorted, action::sp, and state::statenum.
Referenced by main().
 {
   int i;
   struct state *stp;
   struct action *ap;
   for(i=0; i<lemp->nstate; i++){
     stp = lemp->sorted[i];
     stp->nTknAct = stp->nNtAct = 0;
     stp->iDflt = lemp->nstate + lemp->nrule;
     stp->iTknOfst = NO_OFFSET;
     stp->iNtOfst = NO_OFFSET;
     for(ap=stp->ap; ap; ap=ap->next){
       if( compute_action(lemp,ap)>=0 ){
         if( ap->sp->index<lemp->nterminal ){
           stp->nTknAct++;
         }else if( ap->sp->index<lemp->nsymbol ){
           stp->nNtAct++;
         }else{
           stp->iDflt = compute_action(lemp, ap);
         }
       }
     }
   }
   qsort(&lemp->sorted[1], lemp->nstate-1, sizeof(lemp->sorted[0]),
         stateResortCompare);
   for(i=0; i<lemp->nstate; i++){
     lemp->sorted[i]->statenum = i;
   }
 }
int same_symbol (struct symbol * a, struct symbol * b)
Definition at line 935 of file lemon.c.
References MULTITERMINAL, symbol::nsubsym, symbol::subsym, and symbol::type.
Referenced by buildshifts().
 {
   int i;
   if( a==b ) return 1;
   if( a->type!=MULTITERMINAL ) return 0;
   if( b->type!=MULTITERMINAL ) return 0;
   if( a->nsubsym!=b->nsubsym ) return 0;
   for(i=0; i<a->nsubsym; i++){
     if( a->subsym[i]!=b->subsym[i] ) return 0;
   }
   return 1;
 }
int SetAdd (char * s, int e)
Definition at line 4349 of file lemon.c.
Referenced by Configlist_closure(), FindFirstSets(), and FindStates().
 {
   int rv;
   assert( e>=0 && e<size );
   rv = s[e];
   s[e] = 1;
   return !rv;
 }
void SetFree (char * s)
Definition at line 4342 of file lemon.c.
Referenced by Configlist_eat().
 {
   free(s);
 }
char * SetNew (void)
Definition at line 4331 of file lemon.c.
References memory_error().
Referenced by Configlist_add(), Configlist_addbasis(), and FindFirstSets().
               {
   char *s;
   s = (char*)calloc( size, 1);
   if( s==0 ){
     extern void memory_error();
     memory_error();
   }
   return s;
 }
void SetSize (int n)
Definition at line 4325 of file lemon.c.
Referenced by main().
 {
   size = n+1;
 }
int SetUnion (char * s1, char * s2)
Definition at line 4359 of file lemon.c.
Referenced by Configlist_closure(), FindFirstSets(), and FindFollowSets().
 {
   int i, progress;
   progress = 0;
   for(i=0; i<size; i++){
     if( s2[i]==0 ) continue;
     if( s1[i]==0 ){
       progress = 1;
       s1[i] = 1;
     }
   }
   return progress;
 }
struct state ** State_arrayof ()
Definition at line 4895 of file lemon.c.
References s_x3::count, s_x3node::data, and s_x3::tbl.
Referenced by main().
 {
   struct state **array;
   int i,size;
   if( x3a==0 ) return 0;
   size = x3a->count;
   array = (struct state **)calloc(size, sizeof(struct state *));
   if( array ){
     for(i=0; i<size; i++) array[i] = x3a->tbl[i].data;
   }
   return array;
 }
struct state * State_find (struct config * key)
Definition at line 4877 of file lemon.c.
References s_x3node::data, s_x3::ht, s_x3node::key, s_x3node::next, s_x3::size, statecmp(), and statehash().
Referenced by getstate().
 {
   unsigned h;
   x3node *np;
   if( x3a==0 ) return 0;
   h = statehash(key) & (x3a->size-1);
   np = x3a->ht[h];
   while( np ){
     if( statecmp(np->key,key)==0 ) break;
     np = np->next;
   }
   return np ? np->data : 0;
 }
void State_init (void)
Definition at line 4801 of file lemon.c.
References s_x3::count, s_x3::ht, s_x3::size, and s_x3::tbl.
Referenced by main().
                  {
   if( x3a ) return;
   x3a = (struct s_x3*)malloc( sizeof(struct s_x3) );
   if( x3a ){
     x3a->size = 128;
     x3a->count = 0;
     x3a->tbl = (x3node*)calloc(128, sizeof(x3node) + sizeof(x3node*));
     if( x3a->tbl==0 ){
       free(x3a);
       x3a = 0;
     }else{
       int i;
       x3a->ht = (x3node**)&(x3a->tbl[128]);
       for(i=0; i<128; i++) x3a->ht[i] = 0;
     }
   }
 }
int State_insert (struct state * data, struct config * key)
Definition at line 4820 of file lemon.c.
References s_x3::count, s_x3node::data, s_x3node::from, s_x3::ht, s_x3node::key, s_x3node::next, s_x3::size, statecmp(), statehash(), and s_x3::tbl.
Referenced by getstate().
 {
   x3node *np;
   unsigned h;
   unsigned ph;
   if( x3a==0 ) return 0;
   ph = statehash(key);
   h = ph & (x3a->size-1);
   np = x3a->ht[h];
   while( np ){
     if( statecmp(np->key,key)==0 ){
       /* An existing entry with the same key is found. */
       /* Fail because overwrite is not allows. */
       return 0;
     }
     np = np->next;
   }
   if( x3a->count>=x3a->size ){
     /* Need to make the hash table bigger */
     int i,size;
     struct s_x3 array;
     array.size = size = x3a->size*2;
     array.count = x3a->count;
     array.tbl = (x3node*)calloc(size, sizeof(x3node) + sizeof(x3node*));
     if( array.tbl==0 ) return 0;  /* Fail due to malloc failure */
     array.ht = (x3node**)&(array.tbl[size]);
     for(i=0; i<size; i++) array.ht[i] = 0;
     for(i=0; i<x3a->count; i++){
       x3node *oldnp, *newnp;
       oldnp = &(x3a->tbl[i]);
       h = statehash(oldnp->key) & (size-1);
       newnp = &(array.tbl[i]);
       if( array.ht[h] ) array.ht[h]->from = &(newnp->next);
       newnp->next = array.ht[h];
       newnp->key = oldnp->key;
       newnp->data = oldnp->data;
       newnp->from = &(array.ht[h]);
       array.ht[h] = newnp;
     }
     free(x3a->tbl);
     *x3a = array;
   }
   /* Insert the new data */
   h = ph & (x3a->size-1);
   np = &(x3a->tbl[x3a->count++]);
   np->key = key;
   np->data = data;
   if( x3a->ht[h] ) x3a->ht[h]->from = &(np->next);
   np->next = x3a->ht[h];
   x3a->ht[h] = np;
   np->from = &(x3a->ht[h]);
   return 1;
 }
struct state * State_new (void)
Definition at line 4767 of file lemon.c.
References MemoryCheck.
Referenced by getstate().
 {
   struct state *newstate;
   newstate = (struct state *)calloc(1, sizeof(struct state) );
   MemoryCheck(newstate);
   return newstate;
 }
PRIVATE int statecmp (struct config * a, struct config * b)
Definition at line 4741 of file lemon.c.
References config::bp, config::dot, rule::index, and config::rp.
Referenced by State_find(), and State_insert().
 {
   int rc;
   for(rc=0; rc==0 && a && b;  a=a->bp, b=b->bp){
     rc = a->rp->index - b->rp->index;
     if( rc==0 ) rc = a->dot - b->dot;
   }
   if( rc==0 ){
     if( a ) rc = 1;
     if( b ) rc = -1;
   }
   return rc;
 }
PRIVATE unsigned statehash (struct config * a)
Definition at line 4756 of file lemon.c.
References config::bp, config::dot, rule::index, and config::rp.
Referenced by State_find(), and State_insert().
 {
   unsigned h=0;
   while( a ){
     h = h*571 + a->rp->index*37 + a->dot;
     a = a->bp;
   }
   return h;
 }
PRIVATE unsigned strhash (const char * x)
Definition at line 4385 of file lemon.c.
Referenced by Strsafe_find(), Strsafe_insert(), Symbol_find(), and Symbol_insert().
 {
   unsigned h = 0;
   while( *x ) h = h*13 + *(x++);
   return h;
 }
const char * Strsafe (const char * y)
Definition at line 4396 of file lemon.c.
References lemonStrlen, MemoryCheck, Strsafe_find(), and Strsafe_insert().
Referenced by Symbol_new(), and translate_code().
 {
   const char *z;
   char *cpy;
   if( y==0 ) return 0;
   z = Strsafe_find(y);
   if( z==0 && (cpy=(char *)malloc( lemonStrlen(y)+1 ))!=0 ){
     lemon_strcpy(cpy,y);
     z = cpy;
     Strsafe_insert(z);
   }
   MemoryCheck(z);
   return z;
 }
const char * Strsafe_find (const char * key)
Definition at line 4511 of file lemon.c.
References s_x1node::data, s_x1::ht, s_x1node::next, s_x1::size, and strhash().
Referenced by Strsafe().
 {
   unsigned h;
   x1node *np;
   if( x1a==0 ) return 0;
   h = strhash(key) & (x1a->size-1);
   np = x1a->ht[h];
   while( np ){
     if( strcmp(np->data,key)==0 ) break;
     np = np->next;
   }
   return np ? np->data : 0;
 }
void Strsafe_init (void)
Definition at line 4437 of file lemon.c.
References s_x1::count, s_x1::ht, s_x1::size, and s_x1::tbl.
Referenced by main().
                    {
   if( x1a ) return;
   x1a = (struct s_x1*)malloc( sizeof(struct s_x1) );
   if( x1a ){
     x1a->size = 1024;
     x1a->count = 0;
     x1a->tbl = (x1node*)calloc(1024, sizeof(x1node) + sizeof(x1node*));
     if( x1a->tbl==0 ){
       free(x1a);
       x1a = 0;
     }else{
       int i;
       x1a->ht = (x1node**)&(x1a->tbl[1024]);
       for(i=0; i<1024; i++) x1a->ht[i] = 0;
     }
   }
 }
int Strsafe_insert (const char * data)
Definition at line 4456 of file lemon.c.
References s_x1::count, s_x1node::data, s_x1node::from, s_x1::ht, s_x1node::next, s_x1::size, strhash(), and s_x1::tbl.
Referenced by Strsafe().
 {
   x1node *np;
   unsigned h;
   unsigned ph;
   if( x1a==0 ) return 0;
   ph = strhash(data);
   h = ph & (x1a->size-1);
   np = x1a->ht[h];
   while( np ){
     if( strcmp(np->data,data)==0 ){
       /* An existing entry with the same key is found. */
       /* Fail because overwrite is not allows. */
       return 0;
     }
     np = np->next;
   }
   if( x1a->count>=x1a->size ){
     /* Need to make the hash table bigger */
     int i,size;
     struct s_x1 array;
     array.size = size = x1a->size*2;
     array.count = x1a->count;
     array.tbl = (x1node*)calloc(size, sizeof(x1node) + sizeof(x1node*));
     if( array.tbl==0 ) return 0;  /* Fail due to malloc failure */
     array.ht = (x1node**)&(array.tbl[size]);
     for(i=0; i<size; i++) array.ht[i] = 0;
     for(i=0; i<x1a->count; i++){
       x1node *oldnp, *newnp;
       oldnp = &(x1a->tbl[i]);
       h = strhash(oldnp->data) & (size-1);
       newnp = &(array.tbl[i]);
       if( array.ht[h] ) array.ht[h]->from = &(newnp->next);
       newnp->next = array.ht[h];
       newnp->data = oldnp->data;
       newnp->from = &(array.ht[h]);
       array.ht[h] = newnp;
     }
     free(x1a->tbl);
     *x1a = array;
   }
   /* Insert the new data */
   h = ph & (x1a->size-1);
   np = &(x1a->tbl[x1a->count++]);
   np->data = data;
   if( x1a->ht[h] ) x1a->ht[h]->from = &(np->next);
   np->next = x1a->ht[h];
   x1a->ht[h] = np;
   np->from = &(x1a->ht[h]);
   return 1;
 }
struct symbol ** Symbol_arrayof (void)
Definition at line 4716 of file lemon.c.
References s_x2::count, s_x2node::data, and s_x2::tbl.
Referenced by main().
 {
   struct symbol **array;
   int i,size;
   if( x2a==0 ) return 0;
   size = x2a->count;
   array = (struct symbol **)calloc(size, sizeof(struct symbol *));
   if( array ){
     for(i=0; i<size; i++) array[i] = x2a->tbl[i].data;
   }
   return array;
 }
int Symbol_count (void)
Definition at line 4708 of file lemon.c.
References s_x2::count.
Referenced by main().
 {
   return x2a ? x2a->count : 0;
 }
struct symbol * Symbol_find (const char * key)
Definition at line 4680 of file lemon.c.
References s_x2node::data, s_x2::ht, s_x2node::key, s_x2node::next, s_x2::size, and strhash().
Referenced by FindActions(), FindStates(), and Symbol_new().
 {
   unsigned h;
   x2node *np;
   if( x2a==0 ) return 0;
   h = strhash(key) & (x2a->size-1);
   np = x2a->ht[h];
   while( np ){
     if( strcmp(np->key,key)==0 ) break;
     np = np->next;
   }
   return np ? np->data : 0;
 }
void Symbol_init (void)
Definition at line 4604 of file lemon.c.
References s_x2::count, s_x2::ht, s_x2::size, and s_x2::tbl.
Referenced by main().
                   {
   if( x2a ) return;
   x2a = (struct s_x2*)malloc( sizeof(struct s_x2) );
   if( x2a ){
     x2a->size = 128;
     x2a->count = 0;
     x2a->tbl = (x2node*)calloc(128, sizeof(x2node) + sizeof(x2node*));
     if( x2a->tbl==0 ){
       free(x2a);
       x2a = 0;
     }else{
       int i;
       x2a->ht = (x2node**)&(x2a->tbl[128]);
       for(i=0; i<128; i++) x2a->ht[i] = 0;
     }
   }
 }
int Symbol_insert (struct symbol * data, const char * key)
Definition at line 4623 of file lemon.c.
References s_x2::count, s_x2node::data, s_x2node::from, s_x2::ht, s_x2node::key, s_x2node::next, s_x2::size, strhash(), and s_x2::tbl.
Referenced by Symbol_new().
 {
   x2node *np;
   unsigned h;
   unsigned ph;
   if( x2a==0 ) return 0;
   ph = strhash(key);
   h = ph & (x2a->size-1);
   np = x2a->ht[h];
   while( np ){
     if( strcmp(np->key,key)==0 ){
       /* An existing entry with the same key is found. */
       /* Fail because overwrite is not allows. */
       return 0;
     }
     np = np->next;
   }
   if( x2a->count>=x2a->size ){
     /* Need to make the hash table bigger */
     int i,size;
     struct s_x2 array;
     array.size = size = x2a->size*2;
     array.count = x2a->count;
     array.tbl = (x2node*)calloc(size, sizeof(x2node) + sizeof(x2node*));
     if( array.tbl==0 ) return 0;  /* Fail due to malloc failure */
     array.ht = (x2node**)&(array.tbl[size]);
     for(i=0; i<size; i++) array.ht[i] = 0;
     for(i=0; i<x2a->count; i++){
       x2node *oldnp, *newnp;
       oldnp = &(x2a->tbl[i]);
       h = strhash(oldnp->key) & (size-1);
       newnp = &(array.tbl[i]);
       if( array.ht[h] ) array.ht[h]->from = &(newnp->next);
       newnp->next = array.ht[h];
       newnp->key = oldnp->key;
       newnp->data = oldnp->data;
       newnp->from = &(array.ht[h]);
       array.ht[h] = newnp;
     }
     free(x2a->tbl);
     *x2a = array;
   }
   /* Insert the new data */
   h = ph & (x2a->size-1);
   np = &(x2a->tbl[x2a->count++]);
   np->key = key;
   np->data = data;
   if( x2a->ht[h] ) x2a->ht[h]->from = &(np->next);
   np->next = x2a->ht[h];
   x2a->ht[h] = np;
   np->from = &(x2a->ht[h]);
   return 1;
 }
struct symbol * Symbol_new (const char * x)
Definition at line 4529 of file lemon.c.
References symbol::assoc, symbol::datatype, symbol::destLineno, symbol::destructor, symbol::fallback, symbol::firstset, symbol::lambda, LEMON_FALSE, MemoryCheck, symbol::name, NONTERMINAL, symbol::prec, symbol::rule, Strsafe(), Symbol_find(), Symbol_insert(), TERMINAL, symbol::type, UNK, and symbol::useCnt.
Referenced by CompressTables(), and main().
 {
   struct symbol *sp;
   sp = Symbol_find(x);
   if( sp==0 ){
     sp = (struct symbol *)calloc(1, sizeof(struct symbol) );
     MemoryCheck(sp);
     sp->name = Strsafe(x);
     sp->type = isupper(*x) ? TERMINAL : NONTERMINAL;
     sp->rule = 0;
     sp->fallback = 0;
     sp->prec = -1;
     sp->assoc = UNK;
     sp->firstset = 0;
     sp->lambda = LEMON_FALSE;
     sp->destructor = 0;
     sp->destLineno = 0;
     sp->datatype = 0;
     sp->useCnt = 0;
     Symbol_insert(sp,sp->name);
   }
   sp->useCnt++;
   return sp;
 }
struct symbol * Symbol_Nth (int n)
Definition at line 4696 of file lemon.c.
References s_x2node::data, and s_x2::tbl.
 {
   struct symbol *data;
   if( x2a && n>0 && n<=x2a->count ){
     data = x2a->tbl[n-1].data;
   }else{
     data = 0;
   }
   return data;
 }
int Symbolcmpp (const void * _a, const void * _b)
Definition at line 4569 of file lemon.c.
References symbol::index, MULTITERMINAL, symbol::name, and symbol::type.
Referenced by main().
 {
   const struct symbol *a = *(const struct symbol **) _a;
   const struct symbol *b = *(const struct symbol **) _b;
   int i1 = a->type==MULTITERMINAL ? 3 : a->name[0]>'Z' ? 2 : 1;
   int i2 = b->type==MULTITERMINAL ? 3 : b->name[0]>'Z' ? 2 : 1;
   return i1==i2 ? a->index - b->index : i1 - i2;
 }
PRIVATE void tplt_linedir (FILE * out, int lineno, char * filename)
Definition at line 3262 of file lemon.c.
Referenced by emit_code(), emit_destructor_code(), and tplt_print().
 {
   fprintf(out,"#line %d \"",lineno);
   while( *filename ){
     if( *filename == '\\' ) putc('\\',out);
     putc(*filename,out);
     filename++;
   }
   fprintf(out,"\"\n");
 }
PRIVATE FILE* tplt_open (struct lemon * lemp)
Definition at line 3208 of file lemon.c.
References lemon::argv0, lemon::errorcnt, lemon::filename, and pathsearch().
Referenced by ReportTable().
 {
   static char templatename[] = "lempar.c";
   char buf[1000];
   FILE *in;
   char *tpltname;
   char *cp;
   /* first, see if user specified a template filename on the command line. */
   if (user_templatename != 0) {
     if( access(user_templatename,004)==-1 ){
       fprintf(stderr,"Can't find the parser driver template file \"%s\".\n",
         user_templatename);
       lemp->errorcnt++;
       return 0;
     }
     in = fopen(user_templatename,"rb");
     if( in==0 ){
       fprintf(stderr,"Can't open the template file \"%s\".\n",user_templatename);
       lemp->errorcnt++;
       return 0;
     }
     return in;
   }
   cp = strrchr(lemp->filename,'.');
   if( cp ){
     lemon_sprintf(buf,"%.*s.lt",(int)(cp-lemp->filename),lemp->filename);
   }else{
     lemon_sprintf(buf,"%s.lt",lemp->filename);
   }
   if( access(buf,004)==0 ){
     tpltname = buf;
   }else if( access(templatename,004)==0 ){
     tpltname = templatename;
   }else{
     tpltname = pathsearch(lemp->argv0,templatename,0);
   }
   if( tpltname==0 ){
     fprintf(stderr,"Can't find the parser driver template file \"%s\".\n",
     templatename);
     lemp->errorcnt++;
     return 0;
   }
   in = fopen(tpltname,"rb");
   if( in==0 ){
     fprintf(stderr,"Can't open the template file \"%s\".\n",templatename);
     lemp->errorcnt++;
     return 0;
   }
   return in;
 }
PRIVATE void tplt_print (FILE * out, struct lemon * lemp, char * str, int * lineno)
Definition at line 3274 of file lemon.c.
References lemon::nolinenosflag, lemon::outname, and tplt_linedir().
Referenced by ReportTable().
 {
   if( str==0 ) return;
   while( *str ){
     putc(*str,out);
     if( *str=='\n' ) (*lineno)++;
     str++;
   }
   if( str[-1]!='\n' ){
     putc('\n',out);
     (*lineno)++;
   }
   if (!lemp->nolinenosflag) {
     (*lineno)++; tplt_linedir(out,*lineno,lemp->outname);
   }
   return;
 }
PRIVATE void tplt_xfer (char * name, FILE * in, FILE * out, int * lineno)
Definition at line 3183 of file lemon.c.
References LINESIZE.
Referenced by ReportTable().
 {
   int i, iStart;
   char line[LINESIZE];
   while( fgets(line,LINESIZE,in) && (line[0]!='%' || line[1]!='%') ){
     (*lineno)++;
     iStart = 0;
     if( name ){
       for(i=0; line[i]; i++){
         if( line[i]=='P' && strncmp(&line[i],"Parse",5)==0
           && (i==0 || !isalpha(line[i-1]))
         ){
           if( i>iStart ) fprintf(out,"%.*s",i-iStart,&line[iStart]);
           fprintf(out,"%s",name);
           i += 4;
           iStart = i+1;
         }
       }
     }
     fprintf(out,"%s",&line[iStart]);
   }
 }
PRIVATE void translate_code (struct lemon * lemp, struct rule * rp)
Definition at line 3407 of file lemon.c.
References append_str(), rule::code, symbol::dtnum, lemon::errorcnt, ErrorMsg(), lemon::filename, has_destructor(), symbol::index, rule::lhs, rule::lhsalias, rule::line, MAXRHS, MULTITERMINAL, symbol::name, rule::nrhs, rule::rhs, rule::rhsalias, rule::ruleline, Strsafe(), symbol::subsym, and symbol::type.
Referenced by ReportTable().
{
   char *cp, *xp;
   int i;
   char lhsused = 0;    /* True if the LHS element has been used */
   char used[MAXRHS];   /* True for each RHS element which is used */
   for(i=0; i<rp->nrhs; i++) used[i] = 0;
   lhsused = 0;
   if( rp->code==0 ){
     static char newlinestr[2] = { '\n', '\0' };
     rp->code = newlinestr;
     rp->line = rp->ruleline;
   }
   append_str(0,0,0,0);
   /* This const cast is wrong but harmless, if we're careful. */
   for(cp=(char *)rp->code; *cp; cp++){
     if( isalpha(*cp) && (cp==rp->code || (!isalnum(cp[-1]) && cp[-1]!='_')) ){
       char saved;
       for(xp= &cp[1]; isalnum(*xp) || *xp=='_'; xp++);
       saved = *xp;
       *xp = 0;
       if( rp->lhsalias && strcmp(cp,rp->lhsalias)==0 ){
         append_str("yygotominor.yy%d",0,rp->lhs->dtnum,0);
         cp = xp;
         lhsused = 1;
       }else{
         for(i=0; i<rp->nrhs; i++){
           if( rp->rhsalias[i] && strcmp(cp,rp->rhsalias[i])==0 ){
             if( cp!=rp->code && cp[-1]=='@' ){
               /* If the argument is of the form @X then substituted
               ** the token number of X, not the value of X */
               append_str("yymsp[%d].major",-1,i-rp->nrhs+1,0);
             }else{
               struct symbol *sp = rp->rhs[i];
               int dtnum;
               if( sp->type==MULTITERMINAL ){
                 dtnum = sp->subsym[0]->dtnum;
               }else{
                 dtnum = sp->dtnum;
               }
               append_str("yymsp[%d].minor.yy%d",0,i-rp->nrhs+1, dtnum);
             }
             cp = xp;
             used[i] = 1;
             break;
           }
         }
       }
       *xp = saved;
     }
     append_str(cp, 1, 0, 0);
   } /* End loop */
   /* Check to make sure the LHS has been used */
   if( rp->lhsalias && !lhsused ){
     ErrorMsg(lemp->filename,rp->ruleline,
       "Label \"%s\" for \"%s(%s)\" is never used.",
         rp->lhsalias,rp->lhs->name,rp->lhsalias);
     lemp->errorcnt++;
   }
   /* Generate destructor code for RHS symbols which are not used in the
   ** reduce code */
   for(i=0; i<rp->nrhs; i++){
     if( rp->rhsalias[i] && !used[i] ){
       ErrorMsg(lemp->filename,rp->ruleline,
         "Label %s for \"%s(%s)\" is never used.",
         rp->rhsalias[i],rp->rhs[i]->name,rp->rhsalias[i]);
       lemp->errorcnt++;
     }else if( rp->rhsalias[i]==0 ){
       if( has_destructor(rp->rhs[i],lemp) ){
         append_str("  yy_destructor(yypParser,%d,&yymsp[%d].minor);\n", 0,
            rp->rhs[i]->index,i-rp->nrhs+1);
       }else{
         /* No destructor defined for this term */
       }
     }
   }
   if( rp->code ){
     cp = append_str(0,0,0,0);
     rp->code = Strsafe(cp?cp:"");
   }
 }