cplus2asp: bcplusparser/src/bcplus/parser/BCParser.cpp File Reference
BCParser.cpp File Reference
#include <string>
#include <iostream>
#include <boost/foreach.hpp>
#include <boost/filesystem.hpp>
#include "babb/utils/memory.h"
#include "memwrappers.h"
#include "bcplus/Configuration.h"
#include "bcplus/statements/Statement.h"
#include "bcplus/statements/blocks.h"
#include "bcplus/parser/detail/lemon_parser.h"
#include "bcplus/parser/BCParser.h"
#include "bcplus/parser/Token.h"
#include "bcplus/parser/detail/Scanner.h"
#include "bcplus/symbols/Symbol.h"
#include "bcplus/symbols/SymbolTable.h"
#include "bcplus/symbols/NumberRangeSymbol.h"
Namespaces
bcplus
bcplus::parser
Functions
void * lemon_parserAlloc (void *(*mallocProc)(size_t))
void * lemon_parserFree (void *yyp, void(*freeProc)(void *))
void lemon_parser (void *yyp, int tokentype, bcplus::parser::Token const *token, bcplus::parser::BCParser *parser)
int lemon_parserPreInject (void *yyp, int pop, bcplus::parser::Token const **token)
void lemon_parserAttemptReduce (void *yyp, bcplus::parser::BCParser *parser)
void lemon_parserTrace (FILE *TraceFILE, char const *zTracePrompt)
Function Documentation
void lemon_parser (void * yyp, int tokentype, bcplus::parser::Token const * token, bcplus::parser::BCParser * parser)
Referenced by bcplus::parser::BCParser::parse().
void* lemon_parserAlloc (void *(*)(size_t) mallocProc)
Definition at line 2418 of file lemon_parser.cpp.
References yyParser::yyidx, yyParser::yylookmajor, yyParser::yylookminor, YYNOCODE, yyParser::yystack, yyParser::yystksz, and yyParser::yysyntaxerr.
Referenced by bcplus::parser::BCParser::BCParser(), and bcplus::parser::BCParser::reset().
{
   yyParser *pParser;
   pParser = (yyParser*)(*mallocProc)( (size_t)sizeof(yyParser) );
   if( pParser ){
     pParser->yyidx = -1;
 #ifdef YYTRACKMAXSTACKDEPTH
     pParser->yyidxMax = 0;
 #endif
 #if YYSTACKDEPTH<=0
     pParser->yystack = NULL;
     pParser->yystksz = 0;
     yyGrowStack(pParser);
 #endif
     pParser->yylookmajor = YYNOCODE;
     pParser->yylookminor = yyzerominor;
     pParser->yysyntaxerr = 0;
   }
   return pParser;
 }
void lemon_parserAttemptReduce (void * yyp, bcplus::parser::BCParser * parser)
Referenced by bcplus::parser::BCParser::parse().
void* lemon_parserFree (void * yyp, void(*)(void *) freeProc)
Definition at line 3056 of file lemon_parser.cpp.
References YYCODETYPE, yyParser::yyidx, yyParser::yylookmajor, yyParser::yylookminor, YYNOCODE, and yyParser::yystack.
Referenced by bcplus::parser::BCParser::reset(), and bcplus::parser::BCParser::~BCParser().
  {
   yyParser *pParser = (yyParser*)p;
   if( pParser==0 ) return;
   if( pParser->yylookmajor != YYNOCODE ) yy_destructor(pParser, (YYCODETYPE)pParser->yylookmajor, &pParser->yylookminor);
   while( pParser->yyidx>=0 ) yy_pop_parser_stack(pParser);
 #if YYSTACKDEPTH<=0
   free(pParser->yystack);
 #endif
   (*freeProc)((void*)pParser);
 }
int lemon_parserPreInject (void * yyp, int pop, bcplus::parser::Token const ** token)
void lemon_parserTrace (FILE * TraceFILE, char const * zTracePrompt)
Definition at line 1839 of file lemon_parser.cpp.
Referenced by bcplus::parser::BCParser::parse().
{
   yyTraceFILE = TraceFILE;
   yyTracePrompt = zTracePrompt;
   if( yyTraceFILE==0 ) yyTracePrompt = 0;
   else if( yyTracePrompt==0 ) yyTraceFILE = 0;
 }