cplus2asp: bcplus::statements::QueryStatement Class Reference
bcplus::statements::QueryStatement Class Reference
A structure for handling queries.
#include <QueryStatement.h>
Public Types
typedef ReferencedList
< babb::utils::ref_ptr< const
elements::Formula > >::type FormulaList
typedef FormulaList::iterator iterator
typedef FormulaList::const_iterator const_iterator
Public Member Functions
QueryStatement (symbols::QuerySymbol const *symbol, FormulaList *formulas, Location const &begin=Location(NULL, 0, 0), Location const &end=Location(NULL, 0, 0))
Basic constructor.
virtual ~QueryStatement ()
Destructor stub.
symbols::QuerySymbol const * symbol () const
Get's the query's symbol.
ReferencedString const * label () const
Gets the query label, if any.
int maxmax () const
Gets the query maxstep range definition, if any (negative values mean undefined)
int minmax () const
size_t size () const
Gets the number of formulas that should be included.
iterator begin ()
Iterate over the formula list.
const_iterator begin () const
iterator end ()
const_iterator end () const
void push_back (elements::Formula const *formula)
Adds a formula to the query.
virtual Statement * copy () const
Perform a dep copy of this statement.
Public Member Functions inherited from bcplus::statements::Statement
Statement (Type::type type, Location const &begin=Location(NULL, 0, 0), Location const &end=Location(NULL, 0, 0))
Basic Contructor.
~Statement ()
Destructor Stub.
Type::type type () const
Get the type of this statement.
char const * typeString () const
Get the string representation of the statement type.
Location const & beginLoc () const
Get the beginning location of this statement.
Location const & endLoc () const
Get the ending location of this statement.
Public Member Functions inherited from babb::utils::Referenced
Referenced ()
Referenced ()
Additional Inherited Members
Protected Member Functions inherited from babb::utils::Referenced
virtual ~Referenced ()
virtual ~Referenced ()
Detailed Description
A structure for handling queries.
Definition at line 15 of file QueryStatement.h.
Member Typedef Documentation
typedef FormulaList::const_iterator bcplus::statements::QueryStatement::const_iterator
Definition at line 24 of file QueryStatement.h.
typedef ReferencedList<babb::utils::ref_ptr<const elements::Formula> >::type bcplus::statements::QueryStatement::FormulaList
Definition at line 21 of file QueryStatement.h.
typedef FormulaList::iterator bcplus::statements::QueryStatement::iterator
Definition at line 23 of file QueryStatement.h.
Constructor & Destructor Documentation
bcplus::statements::QueryStatement::QueryStatement (symbols::QuerySymbol const * symbol, FormulaList * formulas, Location const & begin = Location(NULL, 0, 0), Location const & end = Location(NULL, 0, 0))
Basic constructor.
Parameters
symbol The symbol for this query
formulas The list of formulas within the query (or NULL to create an empty query)
begin The beginning location for this statement
end The ending location for this statement
Definition at line 18 of file QueryStatement.cpp.
Referenced by copy().
     : Statement(Statement::Type::QUERY, begin, end), _sym(sym) {
     if (formulas) _formulas = formulas;
     else _formulas = new FormulaList();
     /* Intentionally left blank */
 }
bcplus::statements::QueryStatement::~QueryStatement () virtual
Destructor stub.
Definition at line 25 of file QueryStatement.cpp.
{
     /* Intentionally left blank */
 }
Member Function Documentation
iterator bcplus::statements::QueryStatement::begin () inline
Iterate over the formula list.
Definition at line 64 of file QueryStatement.h.
 { return _formulas->begin(); }
const_iterator bcplus::statements::QueryStatement::begin () const inline
Definition at line 65 of file QueryStatement.h.
 { return _formulas->begin(); }
Statement * bcplus::statements::QueryStatement::copy () const virtual
Perform a dep copy of this statement.
Implements bcplus::statements::Statement.
Definition at line 29 of file QueryStatement.cpp.
References bcplus::statements::Statement::beginLoc(), bcplus::statements::Statement::endLoc(), QueryStatement(), and symbol().
{
     // copy the formula list
     babb::utils::ref_ptr<FormulaList> l = new FormulaList();
     BOOST_FOREACH(elements::Formula const* f, *this) {
         l->push_back(f);
     }
     return new QueryStatement(symbol(), l, beginLoc(), endLoc());
 }
iterator bcplus::statements::QueryStatement::end () inline
Definition at line 66 of file QueryStatement.h.
 { return _formulas->end(); }
const_iterator bcplus::statements::QueryStatement::end () const inline
Definition at line 67 of file QueryStatement.h.
 { return _formulas->end(); }
ReferencedString const* bcplus::statements::QueryStatement::label () const inline
Gets the query label, if any.
Definition at line 54 of file QueryStatement.h.
 { return _sym->base(); }
int bcplus::statements::QueryStatement::maxmax () const inline
Gets the query maxstep range definition, if any (negative values mean undefined)
Definition at line 57 of file QueryStatement.h.
Referenced by cplus2asp::cplus2asp_bin::Translator::translate().
 { return _sym->maxmax(); }
int bcplus::statements::QueryStatement::minmax () const inline
Definition at line 58 of file QueryStatement.h.
Referenced by cplus2asp::cplus2asp_bin::Translator::translate().
 { return _sym->minmax(); }
void bcplus::statements::QueryStatement::push_back (elements::Formula const * formula) inline
Adds a formula to the query.
Definition at line 70 of file QueryStatement.h.
 { _formulas->push_back(formula); }
size_t bcplus::statements::QueryStatement::size () const inline
Gets the number of formulas that should be included.
Definition at line 61 of file QueryStatement.h.
 { return _formulas->size(); }
symbols::QuerySymbol const* bcplus::statements::QueryStatement::symbol () const inline
Get's the query's symbol.
Definition at line 51 of file QueryStatement.h.
Referenced by copy(), and cplus2asp::cplus2asp_bin::Translator::translate().
 { return _sym; }
The documentation for this class was generated from the following files:
bcplusparser/include/bcplus/statements/QueryStatement.h
bcplusparser/src/bcplus/statements/QueryStatement.cpp