cplus2asp: cplus2asp::cplus2asp_bin::SortData Class Reference
cplus2asp::cplus2asp_bin::SortData Class Reference
Metadata container for sorts.
#include <SortData.h>
Public Types
typedef std::set
< babb::utils::weak_ptr< const
bcplus::symbols::SortSymbol > > SortSet
A set of sorts.
typedef SortSet::iterator iterator
typedef SortSet::const_iterator const_iterator
Public Member Functions
SortData (bcplus::symbols::SortSymbol const *symbol)
Basic constructor.
virtual ~SortData ()
Destructor stub.
bcplus::symbols::SortSymbol const * sort () const
Get the sort this data is attached to.
bool translated () const
get/set whether the sort declaration has been translated.
void translated (bool t)
bool translatedSubSort (bcplus::symbols::SortSymbol const *s) const
Determine whether the provided subsort/supersort relation has already been translated.
bool translatedSuperSort (bcplus::symbols::SortSymbol const *s) const
void addTranslatedSubSort (bcplus::symbols::SortSymbol const *s)
Registers the provided sort as being a translated sub/super sort relation.
void addTranslatedSuperSort (bcplus::symbols::SortSymbol const *s)
Public Member Functions inherited from babb::utils::Referenced
Referenced ()
Referenced ()
Additional Inherited Members
Protected Member Functions inherited from babb::utils::Referenced
virtual ~Referenced ()
virtual ~Referenced ()
Detailed Description
Metadata container for sorts.
Definition at line 14 of file SortData.h.
Member Typedef Documentation
typedef SortSet::const_iterator cplus2asp::cplus2asp_bin::SortData::const_iterator
Definition at line 25 of file SortData.h.
typedef SortSet::iterator cplus2asp::cplus2asp_bin::SortData::iterator
Definition at line 24 of file SortData.h.
typedef std::set<babb::utils::weak_ptr<const bcplus::symbols::SortSymbol> > cplus2asp::cplus2asp_bin::SortData::SortSet
A set of sorts.
Definition at line 22 of file SortData.h.
Constructor & Destructor Documentation
cplus2asp::cplus2asp_bin::SortData::SortData (bcplus::symbols::SortSymbol const * symbol)
Basic constructor.
Parameters
symbol The constant this data is attached to
Definition at line 13 of file SortData.cpp.
     : _sort(sort), _translated(false) {
     /* Intentionally left blank */
 }
cplus2asp::cplus2asp_bin::SortData::~SortData () virtual
Destructor stub.
Definition at line 18 of file SortData.cpp.
                     {
     /* Intentionally left blank */
 }
Member Function Documentation
void cplus2asp::cplus2asp_bin::SortData::addTranslatedSubSort (bcplus::symbols::SortSymbol const * s)
Registers the provided sort as being a translated sub/super sort relation.
These also update the provided sort's metadata
Definition at line 23 of file SortData.cpp.
References bcplus::symbols::Symbol::metadata(), and sort().
{
     if (_translatedSubSorts.insert(s).second) {
         // add our sort to their translated super sorts
         //s->metadata<SortData>()->addTranslatedSuperSort(sort());
         ((SortData*)(s->metadata()))->addTranslatedSuperSort(sort());
     }
 }
void cplus2asp::cplus2asp_bin::SortData::addTranslatedSuperSort (bcplus::symbols::SortSymbol const * s)
Definition at line 33 of file SortData.cpp.
References bcplus::symbols::Symbol::metadata(), and sort().
{
     if (_translatedSuperSorts.insert(s).second) {
         // add our sort to their translated sub sorts
         //s->metadata<SortData>()->addTranslatedSubSort(sort());
         ((SortData*)(s->metadata()))->addTranslatedSubSort(sort());
     }
 }
bcplus::symbols::SortSymbol const* cplus2asp::cplus2asp_bin::SortData::sort () const inline
Get the sort this data is attached to.
Definition at line 62 of file SortData.h.
Referenced by addTranslatedSubSort(), and addTranslatedSuperSort().
 { return _sort; }
bool cplus2asp::cplus2asp_bin::SortData::translated () const inline
get/set whether the sort declaration has been translated.
Definition at line 65 of file SortData.h.
 { return _translated; }
void cplus2asp::cplus2asp_bin::SortData::translated (bool t) inline
Definition at line 66 of file SortData.h.
 { _translated = t; }
bool cplus2asp::cplus2asp_bin::SortData::translatedSubSort (bcplus::symbols::SortSymbol const * s) const inline
Determine whether the provided subsort/supersort relation has already been translated.
Definition at line 69 of file SortData.h.
 { return _translatedSubSorts.count(s) != 0; }
bool cplus2asp::cplus2asp_bin::SortData::translatedSuperSort (bcplus::symbols::SortSymbol const * s) const inline
Definition at line 70 of file SortData.h.
 { return _translatedSuperSorts.count(s) != 0; }
The documentation for this class was generated from the following files:
cplus2asp.bin/SortData.h
cplus2asp.bin/SortData.cpp