cplus2asp: bcplus::symbols::detail::BaseSymbol Class Reference
bcplus::symbols::detail::BaseSymbol Class Reference abstract
Base symbol class for objects and constants.
#include <BaseSymbol.h>
Public Types
typedef ReferencedVector
< babb::utils::ref_ptr< const
SortSymbol > >::type SortList
typedef SortList::iterator iterator
typedef SortList::const_iterator const_iterator
Public Member Functions
BaseSymbol (Symbol::Type::type type, ReferencedString const *name, SortList const *args=NULL)
Basic constructor.
BaseSymbol (Symbol::Type::type type, boost::property_tree::ptree const &node, Resolver const *resolver, std::ostream *err=NULL)
Loads the sort from the property tree node.
virtual ~BaseSymbol ()
Destructor stub.
const_iterator begin () const
Gets an iterator for the beginning of the parameters.
const_iterator end () const
Gets an iterator for the end of the parameters.
virtual bool operator== (Symbol const &other) const
Check to see if two symbols are equal.
virtual void save (boost::property_tree::ptree &node) const
Outputs the symbol to the provided property tree node.
virtual void outputDefinition (std::ostream &out) const
virtual DomainType::type domainType () const =0
Determine the domain type of this symbol.
Public Member Functions inherited from bcplus::symbols::Symbol
Symbol (Type::type type, babb::utils::ReferencedString const *base, size_t arity)
Basic Constructor.
Symbol (Type::type type, boost::property_tree::ptree const &node, std::ostream *err=NULL)
Attempts to load the symbol from the property tree node.
virtual ~Symbol ()
Destructor stub.
Type::type type () const
Get the symbol type.
char const * typeString () const
Get the symbol type as a cstring.
size_t arity () const
Get the arity of the symbol.
babb::utils::ReferencedString
const * base () const
Get the base name of the symbol.
babb::utils::ReferencedString
const * name () const
Get the full name of the symbol.
bool good () const
Determines if the symbol has been successfully loaded.
bool match (std::string const &b, size_t a) const
Determine if this symbol matches the provided detail.
bool match (std::string const &n) const
Determine if this symbol matches the provided detail.
Referenced * metadata () const
Get/set the metadata.
template<typename T >
T * metadata () const
Referenced * metadata ()
template<typename T >
T * metadata ()
void metadata (Referenced *data)
bool operator!= (Symbol const &other) const
Public Member Functions inherited from babb::utils::Referenced
Referenced ()
Referenced ()
Additional Inherited Members
Static Public Member Functions inherited from bcplus::symbols::Symbol
static std::string genName (std::string const &base, size_t arity=0)
Generate the symbol's name from its base and arity.
Protected Member Functions inherited from bcplus::symbols::Symbol
void good (bool l)
Set the good flag.
Protected Member Functions inherited from babb::utils::Referenced
virtual ~Referenced ()
virtual ~Referenced ()
Detailed Description
Base symbol class for objects and constants.
Definition at line 25 of file BaseSymbol.h.
Member Typedef Documentation
typedef SortList::const_iterator bcplus::symbols::detail::BaseSymbol::const_iterator
Definition at line 34 of file BaseSymbol.h.
typedef SortList::iterator bcplus::symbols::detail::BaseSymbol::iterator
Definition at line 33 of file BaseSymbol.h.
typedef ReferencedVector<babb::utils::ref_ptr<const SortSymbol> >::type bcplus::symbols::detail::BaseSymbol::SortList
Definition at line 32 of file BaseSymbol.h.
Constructor & Destructor Documentation
bcplus::symbols::detail::BaseSymbol::BaseSymbol (Symbol::Type::type type, ReferencedString const * name, SortList const * args = NULL)
Basic constructor.
Parameters
type The type of symbol this is.
name The name of the symbol
args A list of argument sorts or NULL to indicate there are no sorts.
Definition at line 21 of file BaseSymbol.cpp.
     : Symbol(type, base, (args ? args->size() : 0)) {
     if (args) _args = args;
     else _args = new SortList();
 }
bcplus::symbols::detail::BaseSymbol::BaseSymbol (Symbol::Type::type type, boost::property_tree::ptree const & node, Resolver const * resolver, std::ostream * err = NULL)
Loads the sort from the property tree node.
Parameters
type The type of symbol this is.
node The node to load the symbol from
err An error stream to write to (or NULL) Sets the symbol's good flag if it was successful
Definition at line 28 of file BaseSymbol.cpp.
References bcplus::symbols::Symbol::arity(), bcplus::symbols::Symbol::good(), bcplus::symbols::Symbol::name(), bcplus::symbols::Resolver::resolve(), and bcplus::symbols::Symbol::Type::SORT.
     : Symbol(type, node, err) {
     u::ref_ptr<SortList> l = new SortList();
     // Get all of the sorts for each of the arguments
     for (size_t i = 0; i < arity(); i++) {
         try {
             std::string sort_name = node.get<std::string>("<xmlattr>.arg" + boost::lexical_cast<std::string>(i));
             SortSymbol const* sort = (SortSymbol const*)resolver->resolve(Symbol::Type::SORT, sort_name);
             if (!sort) {
                 good(false);
                 if (err) *err << "ERROR: An error occurred scanning the definition of \"" << *name() << "\". \"" << sort_name << "\" is not a declared sort." << std::endl;
             } else {
                 l->push_back(sort);
             }
         } catch (boost::property_tree::ptree_error& e) {
             good(false);
             if (err) *err << "ERROR: An error occurred scanning the definition of \"" << *name() << "\". The sort for argument " << i << " is not properly declared. Please ensure there is an 'arg" << i << "' attribute attached to the declaration." << std::endl;
         }
     }
     _args = l;
 }
bcplus::symbols::detail::BaseSymbol::~BaseSymbol () virtual
Destructor stub.
Definition at line 54 of file BaseSymbol.cpp.
{
     // Intentionally left blank
 }
Member Function Documentation
const_iterator bcplus::symbols::detail::BaseSymbol::begin () const inline
Gets an iterator for the beginning of the parameters.
Definition at line 70 of file BaseSymbol.h.
Referenced by cplus2asp::cplus2asp_bin::Translator::epilogue(), operator==(), and outputDefinition().
 { return _args->begin(); }
virtual DomainType::type bcplus::symbols::detail::BaseSymbol::domainType () const pure virtual
Determine the domain type of this symbol.
Implements bcplus::symbols::Symbol.
Implemented in bcplus::symbols::ConstantSymbol, and bcplus::symbols::ObjectSymbol.
const_iterator bcplus::symbols::detail::BaseSymbol::end () const inline
Gets an iterator for the end of the parameters.
Definition at line 73 of file BaseSymbol.h.
Referenced by cplus2asp::cplus2asp_bin::Translator::epilogue(), operator==(), and outputDefinition().
 { return _args->end(); }
bool bcplus::symbols::detail::BaseSymbol::operator== (Symbol const & other) const virtual
Check to see if two symbols are equal.
Parameters
other The other symbol to compare this one to
Returns
True if they are equal, false otherwise.
Reimplemented from bcplus::symbols::Symbol.
Reimplemented in bcplus::symbols::ConstantSymbol, and bcplus::symbols::AttributeSymbol.
Definition at line 58 of file BaseSymbol.cpp.
References begin(), and end().
{
     if (!Symbol::operator==(other)) return false;
     BaseSymbol const& o = (BaseSymbol const&)other;
     // check argument sorts
     // we can use pointer comparison as we draw from the same set of symbols
     const_iterator oit = o.begin();
     for (const_iterator it = begin(); it != end(); it++) {
         if (oit == o.end()) return false;
         if (*it != *oit) return false;
         oit++;
     }
     if (oit != o.end()) return false;
     return true;
 }
void bcplus::symbols::detail::BaseSymbol::outputDefinition (std::ostream & out) const virtual
Definition at line 82 of file BaseSymbol.cpp.
References bcplus::symbols::Symbol::arity(), bcplus::symbols::Symbol::base(), begin(), and end().
{
     out << *base();
     if (arity()) {
         out << "(";
         for (const_iterator it = begin(); it != end(); ) {
             out << *(*it)->base();
             it++;
             if (it != end()) {
                 out << ", ";
             }
         }
         out << ")";
     }
 }
void bcplus::symbols::detail::BaseSymbol::save (boost::property_tree::ptree & node) const virtual
Outputs the symbol to the provided property tree node.
Parameters
node The node to write to
Reimplemented from bcplus::symbols::Symbol.
Reimplemented in bcplus::symbols::ConstantSymbol, and bcplus::symbols::AttributeSymbol.
Definition at line 74 of file BaseSymbol.cpp.
References bcplus::symbols::Symbol::base(), and bcplus::symbols::Symbol::save().
Referenced by bcplus::symbols::SortSymbol::save().
{
     Symbol::save(node);
     size_t arg = 0;
     BOOST_FOREACH(SortSymbol const* sort, *_args) {
         node.put("<xmlattr>.arg" + boost::lexical_cast<std::string>(arg++), *(sort->base()));
     }
 }
The documentation for this class was generated from the following files:
bcplusparser/include/bcplus/symbols/detail/BaseSymbol.h
bcplusparser/src/bcplus/symbols/detail/BaseSymbol.cpp