cplus2asp: bcplus::symbols::SymbolTable Class Reference
bcplus::symbols::SymbolTable Class Reference
The bcplus's symbol table.
#include <SymbolTable.h>
Classes
struct BuiltinObject
Builtin object symbols.
struct BuiltinSort
Builtin sort symbols.
struct get_second
Simple functor to get the second element in a pair.
class SymbolMetadataInitializer
Functor interface for call to initialize metadata on a symbol.
Public Types
typedef std::map< std::string,
babb::utils::ref_ptr< Symbol > > SymbolMap
typedef std::map
< Symbol::Type::type,
SymbolMap > TypeMap
typedef
boost::transform_iterator
< get_second,
SymbolMap::iterator > iterator
typedef
boost::transform_iterator
< get_second,
SymbolMap::const_iterator > const_iterator
typedef std::map< std::string,
babb::utils::ref_ptr< const
ReferencedString > > DataMap
Public Member Functions
SymbolTable (Configuration const *config, SymbolMetadataInitializer const *metaInit=NULL)
Creates a symbol table based on the provided configuration information.
virtual ~SymbolTable ()
Destructor for the symbol table.
iterator begin (Symbol::Type::type type)
Iterate over the list of symbols matching the provided type.
const_iterator begin (Symbol::Type::type type) const
iterator end (Symbol::Type::type type)
const_iterator end (Symbol::Type::type type) const
bool good () const
Determines if the symbol table was successfully loaded.
ReferencedString const * getData (std::string const &key) const
Get the metadata for the given key, or NULL.
bool setData (std::string const &key, ReferencedString const *data, bool ovrd=false)
Set the metadata for the given key.
SortSymbol const * bsort (BuiltinSort::type sort) const
Get the specified builtin sort symbol.
SortSymbol * bsort (BuiltinSort::type sort)
ObjectSymbol const * bobj (BuiltinObject::type obj) const
Get the specified builtin object symbol.
ObjectSymbol * bobj (BuiltinObject::type obj)
virtual Symbol const * resolve (size_t typemask, std::string const &name, size_t arity=0) const
Find a specific type of symbol matching the provided name/arity.
virtual Symbol * resolve (size_t typemask, std::string const &name, size_t arity=0)
virtual bool create (Symbol *symbol)
Attempt to create register the provided symbol in the table.
SortSymbol * carrot (SortSymbol *parent)
Creates a "carrot" sort from the parent containing "unknown" if the parent doesn't already have it.
SortSymbol * star (SortSymbol *parent)
Creates a "star" sort from the parent containing "none" if the parent doesn't already have it.
SortSymbol * plus (SortSymbol *parent, ObjectSymbol const *obj)
Creates a super sort from the parent containing the providing object if the parent doesn't already have it.
size_t cmask () const
Gets a mask of the constant types that we've encountered so far...
Public Member Functions inherited from bcplus::symbols::Resolver
template<typename T >
T const * resolve (std::string const &name, size_t arity=0) const
Convenience resolve call for a single type.
template<typename T >
T * resolve (std::string const &name, size_t arity=0)
template<typename T >
T * resolveOrCreate (T *symbol)
Attempts to resolve a symbol matching the provided object and attempts to create it if not found.
template<typename T >
T * resolveOrCreate (babb::utils::ref_ptr< T > symbol)
Public Member Functions inherited from babb::utils::Referenced
Referenced ()
Referenced ()
Additional Inherited Members
Protected Member Functions inherited from babb::utils::Referenced
virtual ~Referenced ()
virtual ~Referenced ()
Detailed Description
The bcplus's symbol table.
Definition at line 24 of file SymbolTable.h.
Member Typedef Documentation
typedef boost::transform_iterator<get_second, SymbolMap::const_iterator> bcplus::symbols::SymbolTable::const_iterator
Definition at line 80 of file SymbolTable.h.
typedef std::map<std::string, babb::utils::ref_ptr<const ReferencedString> > bcplus::symbols::SymbolTable::DataMap
Definition at line 82 of file SymbolTable.h.
typedef boost::transform_iterator<get_second, SymbolMap::iterator> bcplus::symbols::SymbolTable::iterator
Definition at line 79 of file SymbolTable.h.
typedef std::map<std::string,babb::utils::ref_ptr<Symbol> > bcplus::symbols::SymbolTable::SymbolMap
Definition at line 76 of file SymbolTable.h.
typedef std::map<Symbol::Type::type, SymbolMap> bcplus::symbols::SymbolTable::TypeMap
Definition at line 77 of file SymbolTable.h.
Constructor & Destructor Documentation
bcplus::symbols::SymbolTable::SymbolTable (Configuration const * config, SymbolMetadataInitializer const * metaInit = NULL)
Creates a symbol table based on the provided configuration information.
Parameters
config The system-wide configuration information to read from.
metaInit An object which is used to initialize the metadata fields in new symbols.
Definition at line 33 of file SymbolTable.cpp.
References bcplus::symbols::Symbol::Type::_LARGEST_, bcplus::symbols::SymbolTable::BuiltinSort::_LENGTH_, bcplus::symbols::SymbolTable::BuiltinObject::_LENGTH_, bcplus::symbols::SymbolTable::BuiltinSort::ADDITIVE, bcplus::symbols::SymbolTable::BuiltinSort::BOOLEAN, bcplus::symbols::SymbolTable::BuiltinSort::COMPUTED, bcplus::Verb::ERROR, bcplus::symbols::SymbolTable::BuiltinObject::FALSE, bcplus::symbols::SymbolTable::BuiltinObject::NONE, bcplus::Configuration::ostream(), bcplus::symbols::Resolver::resolveOrCreate(), bcplus::Configuration::symtabInput(), bcplus::symbols::SymbolTable::BuiltinObject::TRUE, and bcplus::symbols::SymbolTable::BuiltinObject::UNKNOWN.
     : _config(config), _metaInit(metaInit), _cmask(0) {
     _good = true;
     // setup the maps
     size_t type = 0x0001;
     while (type <= Symbol::Type::_LARGEST_) {
         _symbols[(Symbol::Type::type)type];
         type = type << 1;
     }
     // See if we should load anything from a file
     if (config->symtabInput()) _good = load(*(config->symtabInput()));
     _good = _good && loadMacros(config);
     _bsorts[BuiltinSort::ADDITIVE]  = resolveOrCreate(new SortSymbol(new ReferencedString("afValue")));
     _bsorts[BuiltinSort::BOOLEAN]   = resolveOrCreate(new SortSymbol(new ReferencedString("boolean")));
     _bsorts[BuiltinSort::COMPUTED]  = resolveOrCreate(new SortSymbol(new ReferencedString("computed")));
     // setup the boolean sort
     _bobjs[BuiltinObject::TRUE]     = resolveOrCreate(new ObjectSymbol(new ReferencedString("true")));
     _bobjs[BuiltinObject::FALSE]    = resolveOrCreate(new ObjectSymbol(new ReferencedString("false")));
     _bobjs[BuiltinObject::NONE]     = resolveOrCreate(new ObjectSymbol(new ReferencedString("none")));
     _bobjs[BuiltinObject::UNKNOWN]  = resolveOrCreate(new ObjectSymbol(new ReferencedString("unknown")));
     for (size_t i = 0; i < BuiltinSort::_LENGTH_; i++) {
         if (!_bsorts[i]) _good = false;
     }
     for (size_t i = 0; i < BuiltinObject::_LENGTH_; i++) {
         if (!_bobjs[i]) _good = false;
     }
     if (_good) {
         _bsorts[BuiltinSort::ADDITIVE]->add(resolveOrCreate(
             new NumberRangeSymbol(
                 new ReferencedString("_afValue_range"),
                 new elements::UnaryTerm(elements::UnaryTerm::Operator::NEGATIVE,
                     new elements::NullaryTerm(elements::NullaryTerm::Operator::MAXADDITIVE)),
                 new elements::NullaryTerm(elements::NullaryTerm::Operator::MAXADDITIVE))));
         _bsorts[BuiltinSort::BOOLEAN]->add(_bobjs[BuiltinObject::TRUE]);
         _bsorts[BuiltinSort::BOOLEAN]->add(_bobjs[BuiltinObject::FALSE]);
     } else {
         config->ostream(Verb::ERROR) << "ERROR: INTERNAL ERROR: An error occurred initializing the builtin constants in the symbol table." << std::endl;
     }
 }
bcplus::symbols::SymbolTable::~SymbolTable () virtual
Destructor for the symbol table.
Saves the table state according to the configuration information.
Definition at line 90 of file SymbolTable.cpp.
References good().
{
     // See if we should write anything to a file
     if (_config->symtabOutput() && good()) save(*(_config->symtabOutput()));
 }
Member Function Documentation
iterator bcplus::symbols::SymbolTable::begin (Symbol::Type::type type) inline
Iterate over the list of symbols matching the provided type.
Definition at line 141 of file SymbolTable.h.
References begin().
Referenced by begin(), and main().
 { return iterator(_symbols[type].begin()); }
const_iterator bcplus::symbols::SymbolTable::begin (Symbol::Type::type type) const inline
Definition at line 142 of file SymbolTable.h.
 { return const_iterator(_symbols.find(type)->second.begin()); }
ObjectSymbol const* bcplus::symbols::SymbolTable::bobj (BuiltinObject::type obj) const inline
Get the specified builtin object symbol.
Definition at line 165 of file SymbolTable.h.
Referenced by carrot(), and star().
 { return _bobjs[obj]; }
ObjectSymbol* bcplus::symbols::SymbolTable::bobj (BuiltinObject::type obj) inline
Definition at line 166 of file SymbolTable.h.
 { return _bobjs[obj]; }
SortSymbol const* bcplus::symbols::SymbolTable::bsort (BuiltinSort::type sort) const inline
Get the specified builtin sort symbol.
Definition at line 161 of file SymbolTable.h.
 { return _bsorts[sort]; }
SortSymbol* bcplus::symbols::SymbolTable::bsort (BuiltinSort::type sort) inline
Definition at line 162 of file SymbolTable.h.
 { return _bsorts[sort]; }
SortSymbol * bcplus::symbols::SymbolTable::carrot (SortSymbol * parent)
Creates a "carrot" sort from the parent containing "unknown" if the parent doesn't already have it.
Parameters
parent The parent sort
Returns
Either the parent (if parent contains unknown) or a supersort of parent containing unknown.
Definition at line 163 of file SymbolTable.cpp.
References bobj(), plus(), and bcplus::symbols::SymbolTable::BuiltinObject::UNKNOWN.
{
     return plus(parent, bobj(BuiltinObject::UNKNOWN));
 }
size_t bcplus::symbols::SymbolTable::cmask () const inline
Gets a mask of the constant types that we've encountered so far...
Definition at line 188 of file SymbolTable.h.
Referenced by cplus2asp::cplus2asp_bin::Translator::epilogue(), and main().
 { return _cmask; }
bool bcplus::symbols::SymbolTable::create (Symbol * symbol) virtual
Attempt to create register the provided symbol in the table.
Parameters
symbol The symbol to register.
Returns
True if successful, false othwerise.
Implements bcplus::symbols::Resolver.
Definition at line 119 of file SymbolTable.cpp.
References bcplus::symbols::Symbol::arity(), bcplus::symbols::Symbol::base(), bcplus::symbols::Symbol::Type::CONSTANT, bcplus::symbols::Symbol::name(), bcplus::symbols::Symbol::Type::QUERY, bcplus::symbols::Symbol::Type::RANGE, bcplus::symbols::Symbol::Type::SORT, bcplus::Verb::TRACE_SYMTAB, bcplus::symbols::Symbol::type(), and bcplus::symbols::Symbol::typeString().
{
     // check for uniqueness
     // sorts, queries, and ranges are distinguished from other symbols
     _config->ostream(Verb::TRACE_SYMTAB) << "TRACE: Creating \"" << *symbol->name() << "\" of type \"" << symbol->typeString() << "\"... ";
     size_t mask;
     switch (symbol->type()) {
     case Symbol::Type::SORT:
     case Symbol::Type::RANGE:
         mask = Symbol::Type::SORT | Symbol::Type::RANGE;
         break;
     case Symbol::Type::QUERY:
         mask = Symbol::Type::QUERY;
         break;
     default:
         mask = ~(Symbol::Type::SORT | Symbol::Type::QUERY | Symbol::Type::RANGE);
         break;
     }
     if (_resolve(mask, *(symbol->base()), symbol->arity(), false)) {
         _config->ostream(Verb::TRACE_SYMTAB) << "Failed." << std::endl;
         return false;
     }
     // Add the symbol
     _symbols[symbol->type()][*(symbol->name())] = symbol;
     _config->ostream(Verb::TRACE_SYMTAB) << "Success!" << std::endl;
     // If this is a constant, make sure to log the type in our mask...
     if (symbol->type() == Symbol::Type::CONSTANT) {
         _cmask |= ((ConstantSymbol const*)symbol)->constType();
     }
     // initialize the metadata
     if (_metaInit) {
         _metaInit->initMetadata(symbol);
     }
     return true;
 }
iterator bcplus::symbols::SymbolTable::end (Symbol::Type::type type) inline
Definition at line 144 of file SymbolTable.h.
References end().
Referenced by end(), cplus2asp::cplus2asp_bin::Translator::epilogue(), main(), and cplus2asp::cplus2asp_bin::Translator::translate().
 { return iterator(_symbols[type].end()); }
const_iterator bcplus::symbols::SymbolTable::end (Symbol::Type::type type) const inline
Definition at line 145 of file SymbolTable.h.
 { return const_iterator(_symbols.find(type)->second.end()); }
ReferencedString const * bcplus::symbols::SymbolTable::getData (std::string const & key) const
Get the metadata for the given key, or NULL.
Definition at line 96 of file SymbolTable.cpp.
Referenced by main(), and setData().
{
     DataMap::const_iterator it = _metadata.find(key);
     if (it == _metadata.end()) return NULL;
     else return it->second;
 }
bool bcplus::symbols::SymbolTable::good () const inline
Determines if the symbol table was successfully loaded.
Definition at line 148 of file SymbolTable.h.
Referenced by cplus2asp::bcbridge::Driver::symtab(), and ~SymbolTable().
 { return _good; }
SortSymbol * bcplus::symbols::SymbolTable::plus (SortSymbol * parent, ObjectSymbol const * obj)
Creates a super sort from the parent containing the providing object if the parent doesn't already have it.
Returns
Either the parent (if the parent contains obj) or a supersort of parent containing the object.
Definition at line 171 of file SymbolTable.cpp.
References bcplus::symbols::Symbol::base(), bcplus::symbols::SortSymbol::contains(), and bcplus::symbols::Resolver::resolveOrCreate().
Referenced by carrot(), and star().
{
     u::ref_ptr<SortSymbol> ret = parent;
     if (!parent->contains(obj)) {
         // make a new  sort symbol symbol...
         ret = resolveOrCreate(new SortSymbol(new ReferencedString(*parent->base() + "__" + *obj->base())));
         ret->addSubSort(parent);
         ret->add(obj);
     }
     return ret;
 }
Symbol const * bcplus::symbols::SymbolTable::resolve (size_t typemask, std::string const & name, size_t arity = 0) const virtual
Find a specific type of symbol matching the provided name/arity.
Parameters
typemask A mask of types that we should look for
base The base name of the symbol
arity The arity of the symbol
Returns
The symbol matching the parameters or NULL if it doesn't exist.
Implements bcplus::symbols::Resolver.
Definition at line 114 of file SymbolTable.cpp.
Referenced by cplus2asp::cplus2asp_bin::Translator::translate().
{
     return _resolve(typemask, name, arity, true);
 }
Symbol * bcplus::symbols::SymbolTable::resolve (size_t typemask, std::string const & name, size_t arity = 0) virtual
Implements bcplus::symbols::Resolver.
Definition at line 110 of file SymbolTable.cpp.
{
     return _resolve(typemask, name, arity, true);
 }
bool bcplus::symbols::SymbolTable::setData (std::string const & key, ReferencedString const * data, bool ovrd = false)
Set the metadata for the given key.
Parameters
key The key for the data
data The new data for the key
ovrd Whether to override existing data
Returns
True if successful, false if the data exists and we didn't override it.
Definition at line 102 of file SymbolTable.cpp.
References getData().
Referenced by cplus2asp::cplus2asp_bin::Translator::translate().
{
     u::ref_ptr<const ReferencedString> data_ptr = data;
     if (!ovrd && getData(key)) return false;
     _metadata[key] = data;
     return true;
 }
SortSymbol * bcplus::symbols::SymbolTable::star (SortSymbol * parent)
Creates a "star" sort from the parent containing "none" if the parent doesn't already have it.
Returns
Either the parent (if parent contains none) or a supersort of parent containing none.
Definition at line 167 of file SymbolTable.cpp.
References bobj(), bcplus::symbols::SymbolTable::BuiltinObject::NONE, and plus().
{
     return plus(parent, bobj(BuiltinObject::NONE));
 }
The documentation for this class was generated from the following files:
bcplusparser/include/bcplus/symbols/SymbolTable.h
bcplusparser/src/bcplus/symbols/SymbolTable.cpp