cplus2asp: as2transition::Predicate Class Reference
as2transition::Predicate Class Reference
Specialized predicate container used primarily for formatting.
#include <Predicate.h>
Classes
struct Type
The type of constant that this predicate is...
Public Member Functions
Predicate (ReferencedString const *base, ElementList *args=NULL, bool negated=false)
Full Constructor.
virtual ~Predicate ()
Basic destructor.
int timestep () const
Gets the timestep for the predicate (or TIMELESS if there isn't one)
Type::type constType () const
Gets the type of constant that this is.
int predmask () const
Gets the predicate typemask for this predicate.
virtual PredElement * format (Config const *config) const
Reformats the predicate according to the format rules.
Public Member Functions inherited from as2transition::PredElement
PredElement (Type::type type, ReferencedString const *base, ElementList *args=NULL)
Basic constructor.
PredElement (Type::type type, ReferencedString const *base, PredElement *arg)
Basic constructor for unary predelement.
virtual ~PredElement ()
Basic Destructor.
ReferencedString const * base () const
Gets the base name of the element.
Type::type type () const
Gets the type of the element.
size_t arity () const
Get the number of arguments the element has.
iterator begin ()
Iterate over the arguments.
const_iterator begin () const
iterator end ()
const_iterator end () const
PredElement * get (size_t i)
Get a specific argument.
PredElement const * get (size_t i) const
PredElement * operator[] (int i)
PredElement const * operator[] (int i) const
bool operator< (PredElement const &other) const
comparison operators
bool operator> (PredElement const &other) const
bool operator== (PredElement const &other) const
bool operator!= (PredElement const &other) const
Public Member Functions inherited from babb::utils::Referenced
Referenced ()
Referenced ()
Static Public Attributes
static const int TIMELESS = -1
Static time step.
Additional Inherited Members
Public Types inherited from as2transition::PredElement
typedef ReferencedVector
< babb::utils::ref_ptr
< PredElement > >::type ElementList
typedef ElementList::iterator iterator
typedef ElementList::const_iterator const_iterator
Protected Member Functions inherited from babb::utils::Referenced
virtual ~Referenced ()
virtual ~Referenced ()
Detailed Description
Specialized predicate container used primarily for formatting.
Definition at line 14 of file Predicate.h.
Constructor & Destructor Documentation
as2transition::Predicate::Predicate (ReferencedString const * base, ElementList * args = NULL, bool negated = false)
Full Constructor.
Parameters
base The base name of the predicate
args The arguments for the predicate (or NULL)
strongNegation Whether this predicate is strongly negated
Definition at line 17 of file Predicate.cpp.
References as2transition::Predicate::Type::ACTION, as2transition::PredElement::arity(), as2transition::PredElement::base(), as2transition::Config::PredType::CONTRIBUTION, as2transition::Predicate::Type::EXT_ACTION, as2transition::Predicate::Type::EXT_FLUENT, as2transition::Predicate::Type::FLUENT, babb::utils::fromString(), as2transition::Config::PredType::NEGATIVE, as2transition::PredElement::Type::OBJECT, as2transition::Config::PredType::POSITIVE, as2transition::PredElement::PredElement(), as2transition::Predicate::Type::RIGID, as2transition::Config::PredType::STRONG_NEGATION, as2transition::Config::PredType::UNKNOWN, as2transition::Predicate::Type::UNKNOWN, and as2transition::Config::PredType::XPREDICATE.
     : PredElement(PredElement::Type::PREDICATE, b, args),
       _type(Type::UNKNOWN), _timestep(TIMELESS), _predmask(0),
       _eq(false) {
     // Figure out what format we're in....
     bool is_h = (*base() == "h");
     bool is_o = ((*base() == "o") || (*base() == "occ"));
     if (negated) _predmask |= Config::PredType::STRONG_NEGATION;
     if (is_h || is_o) {
         // h(...,t) / o(...,t)...
         bool good = false;
         switch (arity()) {
         case 1:
             // this may be or h(eql(c,v)) ....
             if (*get(0)->base() == "eq" && get(0)->arity() == 2) {
                 _eq = true;
                 _inner = get(0)->get(0);
                 _value = get(0)->get(1);
                 good = true;
             } else if (*get(0)->base() == "eql" && get(0)->arity() == 2) {
                 _inner = get(0)->get(0);
                 _value = get(0)->get(1);
                 good = true;
             }
             break;
         case 2:
             // this is probably h(eql(c,v),t) or o(eql(c,v),t)
             if (*get(0)->base() == "eq" && get(0)->arity() == 2) {
                 _eq = true;
                 _inner = get(0)->get(0);
                 _value = get(0)->get(1);
                 good = true;
                 _ts = get(1);
             } else if (*get(0)->base() == "eql" && get(0)->arity() == 2) {
                 _inner = get(0)->get(0);
                 _value = get(0)->get(1);
                 good = true;
                 _ts = get(1);
             }
             break;
         case 3:
             // this is probably h(c,v,t) or o(c,v,t)
             _inner = get(0);
             _value = get(1);
             _ts = get(2);
             good = true;
             break;
         default:
             // false alarm, we don't recognize the arity...
             break;
         }
         if (good) {
             if (_ts) _type = (is_h ? Type::FLUENT : Type::ACTION);
             else _type = Type::RIGID;
         }
     } else {
         // perhaps c_x_x_ or e_x_x ?
         if (base()->find("c_") == 0 || base()->find("e_") == 0) {
             Type::type t = Type::UNKNOWN;
             size_t l1 = base()->find("_", 2);
             size_t l2 = (l1 != std::string::npos ? base()->find("_",l1+1) : std::string::npos);
             if (l1 != std::string::npos && l2 != std::string::npos) {
                 // figure out the constant type
                 switch (base()->at(2)) {
                 case 'a': t = Type::ACTION; break;
                 case 'r': t = Type::RIGID;  break;
                 case 'f': t = Type::FLUENT; break;
                 default:                    break;
                 }
                 // and the arity...
                 std::string arity_string = base()->substr(l1+1,l2-l1-1);
                 size_t iarity;
                 if (!u::fromString(arity_string.c_str(), iarity)) {
                     t = Type::UNKNOWN;
                 }
                 // verify arity...
                 if (t == Type::RIGID && iarity + 1 != arity()) t = Type::UNKNOWN;
                 else if (t != Type::RIGID && iarity + 2!= arity()) t = Type::UNKNOWN;
                 if (t != Type::UNKNOWN) {
                     // success so far... parse the arguments...
                     _type = t;
                     _value = get(iarity);
                     if (_type != Type::RIGID) _ts = get(iarity+1);
                     // construct a new inner type...
                     u::ref_ptr<ElementList> newargs = new ElementList();
                     for (size_t i = 0; i < iarity; i++) {
                         newargs->push_back(get(i));
                     }
                     _inner = new PredElement(PredElement::Type::OBJECT, base(), newargs);
                     if (base()->at(0) == 'e') {
                         // external constant...
                         if (t == Type::ACTION) t = Type::EXT_ACTION;
                         else t = Type::EXT_FLUENT;
                     }
                 }
             }
         }
         // contrib_* ?
         else if (base()->find("contrib_") == 0) {
             // this looks like a contribution...
             if (arity() == 4) {
                 // contrib(c,a,v,t)
                 _type = Type::ACTION;
                 _value = get(2);
                 _ts = get(3);
                 // construct a new inner type...
                 u::ref_ptr<ElementList> newargs = new ElementList();
                 newargs->push_back(get(0));
                 newargs->push_back(get(1));
                 _inner = new PredElement(PredElement::Type::OBJECT, new ReferencedString("contribution"), newargs);
             }
         }
     }
     // almost done... now we just need to extract the timestep and some additional information about the inner type...
     // time stamp...
     if (_ts && _ts->arity() == 0) {
         u::fromString(_ts->base()->c_str(), _timestep);
     }
     if (_value) {
         if (_value->arity() == 0
             && (*_value->base() == "none" || *_value->base() == "o_none"
                 || *_value->base() == "false" || *_value->base() == "o_false"))
             _predmask |= Config::PredType::NEGATIVE;
         else _predmask |= Config::PredType::POSITIVE;
     } else _predmask |= Config::PredType::UNKNOWN;
     if (_inner) {
         if (*_inner->base() == "contribution") _predmask |= Config::PredType::CONTRIBUTION;
         else if (_inner->base()->find("x_") == 0) _predmask |= Config::PredType::XPREDICATE;
     } else _predmask |= Config::PredType::UNKNOWN;
 }
as2transition::Predicate::~Predicate () virtual
Basic destructor.
Definition at line 186 of file Predicate.cpp.
                       {
     // Intentionally left blank
 }
Member Function Documentation
Type::type as2transition::Predicate::constType () const inline
Gets the type of constant that this is.
Definition at line 84 of file Predicate.h.
Referenced by as2transition::Timestep::add().
 { return _type; }
PredElement * as2transition::Predicate::format (Config const * config) const virtual
Reformats the predicate according to the format rules.
Parameters
config The format rules to apply
Returns
The newly formatted element or NULL if the format rules specify the element should be removed.
Cull things we shouldn't show...
Reimplemented from as2transition::PredElement.
Definition at line 192 of file Predicate.cpp.
References as2transition::Config::PredFormat::EQL, as2transition::PredElement::format(), as2transition::Config::format(), as2transition::Config::PredFormat::INNER, as2transition::PredElement::Type::OBJECT, as2transition::PredElement::PredElement(), predmask(), as2transition::Config::PredFormat::RAW, babb::utils::ref_ptr< T >::release(), as2transition::Config::PredFormat::SHORT, as2transition::Config::show(), and as2transition::Config::PredType::STRONG_NEGATION.
{
     if (!config->show(predmask())) return NULL;
     // If this predicate isn't well formed, just return this
     if (!_value || !_inner) return PredElement::format(config);
     u::ref_ptr<ElementList> args = new ElementList();
     u::ref_ptr<PredElement> ret;
     switch (config->format()) {
     case Config::PredFormat::RAW:
         // just return this...
         ret = PredElement::format(config);
         if ((predmask() & Config::PredType::STRONG_NEGATION))
             ret = new PredElement(PredElement::Type::OBJECT, new ReferencedString("~"), ret);
         return ret.release();
     case Config::PredFormat::INNER:
         args->push_back(_inner->format(config));
         args->push_back(_value->format(config));
         ret = new PredElement(PredElement::Type::OBJECT, new ReferencedString((_eq ? "eq" : "eql")), args);
         if ((predmask() & Config::PredType::STRONG_NEGATION))
             ret = new PredElement(PredElement::Type::OBJECT, new ReferencedString("~"), ret);
         return ret.release();
     case Config::PredFormat::SHORT:
         if (_value->arity() == 0 && (*_value->base() == "true" || *_value->base() == "o_true")) return _inner->format(config);
         if (_value->arity() == 0 && (*_value->base() == "false" || *_value->base() == "o_false")) {
             args->push_back(_inner->format(config));
             return new PredElement(PredElement::Type::OBJECT, new ReferencedString("-"),
                 ((predmask() & Config::PredType::STRONG_NEGATION) ?
                       new PredElement(PredElement::Type::OBJECT, new ReferencedString("~"), _inner->format(config))
                     : _inner->format(config)));
         }
         /* no break */
     case Config::PredFormat::EQL:
         args->push_back(_inner->format(config));
         args->push_back(_value->format(config));
         ret = new PredElement(PredElement::Type::OBJECT, new ReferencedString("="), args);
         if ((predmask() & Config::PredType::STRONG_NEGATION))
             ret = new PredElement(PredElement::Type::OBJECT, new ReferencedString("~"), ret);
         return ret.release();
     default:
         // just return this...
         ret = PredElement::format(config);
         if ((predmask() & Config::PredType::STRONG_NEGATION))
             ret = new PredElement(PredElement::Type::OBJECT, new ReferencedString("~"), ret);
         return ret.release();
     }
 }
int as2transition::Predicate::predmask () const inline
Gets the predicate typemask for this predicate.
Definition at line 87 of file Predicate.h.
Referenced by format().
 { return _predmask; }
int as2transition::Predicate::timestep () const inline
Gets the timestep for the predicate (or TIMELESS if there isn't one)
Definition at line 81 of file Predicate.h.
Referenced by as2transition::TransitionPath::add().
 { return _timestep; }
Member Data Documentation
const int as2transition::Predicate::TIMELESS = -1 static
Static time step.
Definition at line 35 of file Predicate.h.
The documentation for this class was generated from the following files:
as2transition/include/as2transition/Predicate.h
as2transition/src/as2transition/Predicate.cpp