cplus2asp: as2transition::TransitionPath Class Reference
as2transition::TransitionPath Class Reference
Represents a path through a transition system consisting of a number of timesteps (with assoicated states / actions / abnormalities)
#include <TransitionPath.h>
Public Types
typedef std::vector
< babb::utils::ref_ptr
< Timestep > > StepList
typedef StepList::iterator iterator
typedef StepList::const_iterator const_iterator
Public Member Functions
TransitionPath (Config const *config)
Basic Constructor.
~TransitionPath ()
Basic Destructor.
iterator begin ()
Gets an iterator pointing to the beginning of the path.
const_iterator begin () const
iterator end ()
Gets an iterator pointing to the end of the path.
const_iterator end () const
size_t length () const
Gets the number of steps in the path.
Timestep * step (size_t t)
Gets the specified timestep in the path (or NULL).
Timestep const * step (size_t t) const
bool add (Predicate *pred)
Adds the predicate to the path at the appropriate timestep, creating it if neccessary.
std::ostream & output (std::ostream &out) const
Prints the path to the provided output stream.
Public Member Functions inherited from babb::utils::Referenced
Referenced ()
Referenced ()
Static Public Attributes
static size_t const TIMELESS = Timestep::TIMELESS
Additional Inherited Members
Protected Member Functions inherited from babb::utils::Referenced
virtual ~Referenced ()
virtual ~Referenced ()
Detailed Description
Represents a path through a transition system consisting of a number of timesteps (with assoicated states / actions / abnormalities)
Definition at line 39 of file TransitionPath.h.
Member Typedef Documentation
typedef StepList::const_iterator as2transition::TransitionPath::const_iterator
Definition at line 46 of file TransitionPath.h.
typedef StepList::iterator as2transition::TransitionPath::iterator
Definition at line 45 of file TransitionPath.h.
typedef std::vector<babb::utils::ref_ptr<Timestep> > as2transition::TransitionPath::StepList
Definition at line 44 of file TransitionPath.h.
Constructor & Destructor Documentation
as2transition::TransitionPath::TransitionPath (Config const * config) inline
Basic Constructor.
Definition at line 64 of file TransitionPath.h.
         : _config(config) {
         _timeless = new Timestep(config);
     }
as2transition::TransitionPath::~TransitionPath () inline
Basic Destructor.
Definition at line 70 of file TransitionPath.h.
     { /* Intentionally Left Blank */ }
Member Function Documentation
bool as2transition::TransitionPath::add (Predicate * pred)
Adds the predicate to the path at the appropriate timestep, creating it if neccessary.
Parameters
pred The predicate to add.
Returns
True if the predicate resulted in a new time step being created.
Definition at line 33 of file TransitionPath.cpp.
References as2transition::Timestep::add(), length(), step(), and as2transition::Predicate::timestep().
Referenced by as2transition::TransitionFormatter::format().
{
     size_t time = pred->timestep();
     Timestep* ts = step(time);
     if (ts) {
         ts->add(pred);
         return false;
     } else {
         size_t max = length();
         while (max <= time) {
             _steps.push_back(new Timestep(_config,max++));
         }
         _steps[time]->add(pred);
         return true;
     }
 }
iterator as2transition::TransitionPath::begin () inline
Gets an iterator pointing to the beginning of the path.
Definition at line 77 of file TransitionPath.h.
 { return _steps.begin(); }
const_iterator as2transition::TransitionPath::begin () const inline
Definition at line 78 of file TransitionPath.h.
 { return _steps.begin(); }
iterator as2transition::TransitionPath::end () inline
Gets an iterator pointing to the end of the path.
Definition at line 81 of file TransitionPath.h.
 { return _steps.end(); }
const_iterator as2transition::TransitionPath::end () const inline
Definition at line 82 of file TransitionPath.h.
 { return _steps.end(); }
size_t as2transition::TransitionPath::length () const inline
Gets the number of steps in the path.
Definition at line 85 of file TransitionPath.h.
Referenced by add(), and step().
 { return _steps.size(); }
std::ostream & as2transition::TransitionPath::output (std::ostream & out) const
Prints the path to the provided output stream.
Parameters
out The output stream to print to.
Returns
out
Definition at line 50 of file TransitionPath.cpp.
Referenced by as2transition::operator<<().
{
     if (_timeless->num()) {
         out << *_timeless;
         out << std::endl;
     }
     for (Timestep const* ts : *this) {
         out << *ts;
         out << std::endl;
     }
     return out;
 }
Timestep* as2transition::TransitionPath::step (size_t t) inline
Gets the specified timestep in the path (or NULL).
Definition at line 88 of file TransitionPath.h.
References length(), and TIMELESS.
Referenced by add().
{
         if (t == TIMELESS) return _timeless;
         else return (t < length()) ? _steps[t] : NULL;
     }
Timestep const* as2transition::TransitionPath::step (size_t t) const inline
Definition at line 93 of file TransitionPath.h.
References length(), and TIMELESS.
{
         if (t == TIMELESS) return _timeless;
         else return (t < length()) ? _steps[t] : NULL;
     }
Member Data Documentation
size_t const as2transition::TransitionPath::TIMELESS = Timestep::TIMELESS static
Definition at line 48 of file TransitionPath.h.
Referenced by step().
The documentation for this class was generated from the following files:
as2transition/include/as2transition/TransitionPath.h
as2transition/src/as2transition/TransitionPath.cpp