cplus2asp: Interpreter Class Reference
Interpreter Class Reference
A static helper class to assist with interpreting interactive input.
#include <Interpreter.h>
Public Types
enum Action {
SHOW_QUERIES, SHOW_CONFIG, SET_QUERY, SET_NUMSOLN,
SET_MAXSTEP, SET_MINSTEP, EXIT, SHOW_HELP,
INVALID
}
The user actions recognized by the interpreter.
Static Public Member Functions
static void showHelp (std::ostream &output)
Prints a help dialog to the provided output stream detaling the options accepted by the interpreter.
static Action interpret (std::string const &command, std::string &outVal)
Interprets the provided command.
Detailed Description
A static helper class to assist with interpreting interactive input.
Definition at line 34 of file Interpreter.h.
Member Enumeration Documentation
enum Interpreter::Action
The user actions recognized by the interpreter.
Enumerator
SHOW_QUERIES
SHOW_CONFIG
SET_QUERY
SET_NUMSOLN
SET_MAXSTEP
SET_MINSTEP
EXIT
SHOW_HELP
INVALID
Definition at line 43 of file Interpreter.h.
                  {
         SHOW_QUERIES,
         SHOW_CONFIG,
         SET_QUERY,
         SET_NUMSOLN,
         SET_MAXSTEP,
         SET_MINSTEP,
         EXIT,
         SHOW_HELP,
         INVALID
     } Action;
Member Function Documentation
Interpreter::Action Interpreter::interpret (std::string const & command, std::string & outVal) static
Interprets the provided command.
Parameters
command THe command to interpret.
[out] outVal A string containing any value accompanying the command, or empty if not applicable.
Returns
The action requested by the user, or INVALID if the command wasn't recognized.
Definition at line 61 of file Interpreter.cpp.
References INVALID, and utils::trimWhitespace().
Referenced by queryUserForQuery().
{
     size_t pos;
     Action action;
     // Figure out the action.
     if ((pos = command.find("=")) != std::string::npos) {
         action = lex(utils::trimWhitespace(command.substr(0,pos)));
     } else {
         action = lex(utils::trimWhitespace(command));
     }
     // get the associated value if applicable.
     if (action != INVALID && pos != std::string::npos && pos + 1 <= command.size()) {
         outVal = utils::trimWhitespace(command.substr(pos+1));
     } else {
         outVal = "";
     }
     return action;
 }
void Interpreter::showHelp (std::ostream & output) static
Prints a help dialog to the provided output stream detaling the options accepted by the interpreter.
Parameters
output The output stream to print to.
Definition at line 36 of file Interpreter.cpp.
References CONST_DEFAULT, and CONST_MAXSTEP_INFINITE.
Referenced by queryUserForQuery().
{
     std::cout
         << "You may specify one or more of the following options, each followed by a return.\n"
         << std::endl
         << '\t' << std::setw(15) << std::left << "queries" << "- Displays the list of queries that are available to run.\n"
         << '\t' << std::setw(15) << std::left << "config" << "- Displays the current run configuration.\n"
         << '\t' << std::setw(15) << std::left << "query=ID " << "- Selects and runs an available query.\n"
         << '\t' << std::setw(15) << std::left << "sol=#" << "- Sets the number of solutions to find to #.\n"
         << '\t' << std::setw(15) << "" << "- Specifying '" << CONST_DEFAULT << "' for # resets the option to the default value.\n"
         << '\t' << std::setw(15) << std::left << "maxstep=#" << "- Overrides the maximum step on the next query.\n"
         << '\t' << std::setw(15) << "" << "- Specifying '" << CONST_MAXSTEP_INFINITE << "' indicates that there should be no maximum step.\n"
         << '\t' << std::setw(15) << "" << "- Specifying '" << CONST_DEFAULT << "' for # resets the option to the default value.\n"
         << '\t' << std::setw(15) << std::left << "minstep=#" << "- Overrides the minimum step on the next query, setting it to #.\n"
         << '\t' << std::setw(15) << "" << "- Specifying '" << CONST_DEFAULT << "' for # resets the option to the default value.\n"
         << '\t' << std::setw(15) << std::left << "help" << "- Displays this dialog.\n"
         << '\t' << std::setw(15) << std::left << "exit" << "- Exits the program.\n";
 }
The documentation for this class was generated from the following files:
cplus2asp/Interpreter.h
cplus2asp/Interpreter.cpp