cplus2asp: bcplus::statements::detail::ImplLawForm< type, head_t, body_t, where_t > Class Template Reference
bcplus::statements::detail::ImplLawForm< type, head_t, body_t, where_t > Class Template Reference
Base law form for simple implications with a head and body (and where)
#include <ImplLawForm.h>
Public Types
typedef head_t head_type
typedef body_t body_type
typedef where_t where_type
Public Member Functions
ImplLawForm (head_t const *head, body_t const *body, where_t const *where, Location const &begin=Location(NULL, 0, 0), Location const &end=Location(NULL, 0, 0))
virtual ~ImplLawForm ()
head_t const * head () const
Get the head element.
body_t const * body () const
Get the body element.
where_t const * where () const
Get the 'where' clause.
virtual Statement * copy () const
Perform a dep copy of this statement.
Public Member Functions inherited from bcplus::statements::Statement
Statement (Type::type type, Location const &begin=Location(NULL, 0, 0), Location const &end=Location(NULL, 0, 0))
Basic Contructor.
~Statement ()
Destructor Stub.
Type::type type () const
Get the type of this statement.
char const * typeString () const
Get the string representation of the statement type.
Location const & beginLoc () const
Get the beginning location of this statement.
Location const & endLoc () const
Get the ending location of this statement.
Public Member Functions inherited from babb::utils::Referenced
Referenced ()
Referenced ()
Additional Inherited Members
Protected Member Functions inherited from babb::utils::Referenced
virtual ~Referenced ()
virtual ~Referenced ()
Detailed Description
template<Statement::Type::type type, typename head_t, typename body_t, typename where_t>
class bcplus::statements::detail::ImplLawForm< type, head_t, body_t, where_t >
Base law form for simple implications with a head and body (and where)
Definition at line 15 of file ImplLawForm.h.
Member Typedef Documentation
template<Statement::Type::type type, typename head_t , typename body_t , typename where_t > typedef body_t bcplus::statements::detail::ImplLawForm< type, head_t, body_t, where_t >::body_type
Definition at line 22 of file ImplLawForm.h.
template<Statement::Type::type type, typename head_t , typename body_t , typename where_t > typedef head_t bcplus::statements::detail::ImplLawForm< type, head_t, body_t, where_t >::head_type
Definition at line 21 of file ImplLawForm.h.
template<Statement::Type::type type, typename head_t , typename body_t , typename where_t > typedef where_t bcplus::statements::detail::ImplLawForm< type, head_t, body_t, where_t >::where_type
Definition at line 23 of file ImplLawForm.h.
Constructor & Destructor Documentation
template<Statement::Type::type t, typename head_t , typename body_t , typename where_t > bcplus::statements::detail::ImplLawForm< t, head_t, body_t, where_t >::ImplLawForm (head_t const * head, body_t const * body, where_t const * where, Location const & begin = Location(NULL, 0, 0), Location const & end = Location(NULL, 0, 0))
Definition at line 13 of file ImplLawForm.impl.h.
     : Statement(t, begin, end), _head(head), _body(body), _where(where) {
     /* Intentionally left blank */
 }
template<Statement::Type::type t, typename head_t , typename body_t , typename where_t > bcplus::statements::detail::ImplLawForm< t, head_t, body_t, where_t >::~ImplLawForm () virtual
Definition at line 20 of file ImplLawForm.impl.h.
{
     /* Intentionally left blank */
 }
Member Function Documentation
template<Statement::Type::type type, typename head_t , typename body_t , typename where_t > body_t const* bcplus::statements::detail::ImplLawForm< type, head_t, body_t, where_t >::body () const inline
Get the body element.
Definition at line 59 of file ImplLawForm.h.
Referenced by cplus2asp::cplus2asp_bin::Translator::translate().
 { return _body; }
template<Statement::Type::type t, typename head_t , typename body_t , typename where_t > Statement * bcplus::statements::detail::ImplLawForm< t, head_t, body_t, where_t >::copy () const virtual
Perform a dep copy of this statement.
Implements bcplus::statements::Statement.
Definition at line 25 of file ImplLawForm.impl.h.
{
     return new ImplLawForm<t, head_t, body_t, where_t>(head(), body(), where(), beginLoc(), endLoc());
 }
template<Statement::Type::type type, typename head_t , typename body_t , typename where_t > head_t const* bcplus::statements::detail::ImplLawForm< type, head_t, body_t, where_t >::head () const inline
Get the head element.
Definition at line 56 of file ImplLawForm.h.
Referenced by cplus2asp::cplus2asp_bin::Translator::translate().
 { return _head; }
template<Statement::Type::type type, typename head_t , typename body_t , typename where_t > where_t const* bcplus::statements::detail::ImplLawForm< type, head_t, body_t, where_t >::where () const inline
Get the 'where' clause.
Definition at line 62 of file ImplLawForm.h.
Referenced by cplus2asp::cplus2asp_bin::Translator::translate().
 { return _where; }
The documentation for this class was generated from the following files:
bcplusparser/include/bcplus/statements/detail/ImplLawForm.h
bcplusparser/include/bcplus/statements/detail/ImplLawForm.impl.h