cplus2asp: bcplus::languages::Language Class Reference
bcplus::languages::Language Class Reference abstract
#include <Language.h>
Classes
struct Feature
Container for language features to be supported.
Public Member Functions
char const * featureDescription (Feature::type feature) const
Get the description of the provided feature.
virtual char const * name () const =0
Get the name of this language.
virtual bool support (Feature::type feature) const =0
Determine if this language supports the provided feature.
virtual size_t id () const =0
Get a unique integral identifier for this language.
Public Member Functions inherited from babb::utils::Referenced
Referenced ()
Referenced ()
Additional Inherited Members
Protected Member Functions inherited from babb::utils::Referenced
virtual ~Referenced ()
virtual ~Referenced ()
Detailed Description
Definition at line 8 of file Language.h.
Member Function Documentation
char const* bcplus::languages::Language::featureDescription (Feature::type feature) const inline
Get the description of the provided feature.
Definition at line 133 of file Language.h.
References bcplus::languages::Language::Feature::descr().
Referenced by bcplus::parser::BCParser::_feature_error(), and bcplus::parser::detail::MacroParser::_feature_error().
 { return Feature::descr(feature); }
virtual size_t bcplus::languages::Language::id () const pure virtual
Get a unique integral identifier for this language.
Implemented in bcplus::languages::BC, bcplus::languages::BCPlus, bcplus::languages::CPlus, bcplus::languages::MVPF, and bcplus::languages::OBCPlus.
virtual char const* bcplus::languages::Language::name () const pure virtual
Get the name of this language.
Returns
The language name
Implemented in bcplus::languages::BC, bcplus::languages::BCPlus, bcplus::languages::CPlus, bcplus::languages::MVPF, and bcplus::languages::OBCPlus.
Referenced by bcplus::parser::BCParser::_feature_error(), and bcplus::parser::detail::MacroParser::_feature_error().
virtual bool bcplus::languages::Language::support (Feature::type feature) const pure virtual
Determine if this language supports the provided feature.
Parameters
feature The feature to check
True if the language supports the feature, false otherwise.
The documentation for this class was generated from the following file:
bcplusparser/include/bcplus/languages/Language.h