cplus2asp: bcplus::elements::detail::IdentifierElement< BaseType, type, SymbolType, ArgType > Class Template Reference
bcplus::elements::detail::IdentifierElement< BaseType, type, SymbolType, ArgType > Class Template Reference
Version of IdentifierElement with arguments.
#include <IdentifierElement.h>
Public Types
typedef ArgType Argument
Argument type aliases.
typedef ReferencedVector
< babb::utils::ref_ptr< const
Argument > >::type ArgumentList
typedef
ArgumentList::const_iterator iterator
Argument iterators.
typedef
ArgumentList::const_iterator const_iterator
Public Member Functions
IdentifierElement (SymbolType const *symbol, ArgumentList const *args=NULL, Location const &begin=Location(NULL, 0, 0), Location const &end=Location(NULL, 0, 0), bool parens=false)
Full constructor.
virtual ~IdentifierElement ()
Destructor stub.
size_t arity () const
Get the number of arguments.
const_iterator begin () const
Argument list iterators.
const_iterator end () const
virtual Element * copy () const
virtual void output (std::ostream &out) const
Public Member Functions inherited from bcplus::elements::detail::IdentifierElement_bare< BaseType, type, SymbolType >
IdentifierElement_bare (SymbolType const *symbol, Location const &begin=Location(NULL, 0, 0), Location const &end=Location(NULL, 0, 0), bool parens=false)
Full constructor.
virtual ~IdentifierElement_bare ()
Destructor stub.
SymbolType const * symbol () const
The symbol entry for this identifier.
virtual DomainType::type domainType () const
Protected Member Functions
ArgumentList const * args () const
The argument list.
Detailed Description
template<typename BaseType, int type, typename SymbolType, typename ArgType>
class bcplus::elements::detail::IdentifierElement< BaseType, type, SymbolType, ArgType >
Version of IdentifierElement with arguments.
Parameters
BaseType The base class for this template
type The type flag to indicate the specialization of the type
SymbolType The type that the SymbolTable is of.
ArgType The type that the arguments are allowed to take.
Definition at line 69 of file IdentifierElement.h.
Member Typedef Documentation
template<typename BaseType, int type, typename SymbolType, typename ArgType> typedef ArgType bcplus::elements::detail::IdentifierElement< BaseType, type, SymbolType, ArgType >::Argument
Argument type aliases.
Definition at line 77 of file IdentifierElement.h.
template<typename BaseType, int type, typename SymbolType, typename ArgType> typedef ReferencedVector<babb::utils::ref_ptr<const Argument> >::type bcplus::elements::detail::IdentifierElement< BaseType, type, SymbolType, ArgType >::ArgumentList
Definition at line 78 of file IdentifierElement.h.
template<typename BaseType, int type, typename SymbolType, typename ArgType> typedef ArgumentList::const_iterator bcplus::elements::detail::IdentifierElement< BaseType, type, SymbolType, ArgType >::const_iterator
Definition at line 83 of file IdentifierElement.h.
template<typename BaseType, int type, typename SymbolType, typename ArgType> typedef ArgumentList::const_iterator bcplus::elements::detail::IdentifierElement< BaseType, type, SymbolType, ArgType >::iterator
Argument iterators.
Definition at line 82 of file IdentifierElement.h.
Constructor & Destructor Documentation
template<typename BaseType , int type, typename SymbolType, typename ArgType > bcplus::elements::detail::IdentifierElement< BaseType, type, SymbolType, ArgType >::IdentifierElement (SymbolType const * symbol, ArgumentList const * args = NULL, Location const & begin = Location(NULL, 0, 0), Location const & end = Location(NULL, 0, 0), bool parens = false)
Full constructor.
Parameters
symbol The symbol entry in the symbol table.
args The argument list for this identifier.
begin The beginning location of this element
end The ending location of this element
parens Whether the element is surrounded by parentheses
Definition at line 55 of file IdentifierElement.impl.h.
References bcplus::elements::detail::IdentifierElement< BaseType, type, SymbolType, ArgType >::args().
     : IdentifierElement_bare<BaseType, type, SymbolType>(symbol, begin, end, parens) {
     if (args) _args = args;
     else _args = new ArgumentList();
     if (boost::is_base_of<el::Element, ArgType>::value) {
             // update list of constants
             // this is a bit of a hack for efficiency since we know that we just instantiated it
             typename BaseType::ConstantSet* consts = const_cast<typename BaseType::ConstantSet*>(BaseType::constants());
             BOOST_FOREACH(void const* elem, *this) {
                 BaseType::insertConstants(consts, (el::Element const*)elem);
             }
             BaseType::constants(consts);
             // update list of free variables
             // this is a bit of a hack for efficiency since we know that we just instantiated it
             typename BaseType::VariableSet* vars = const_cast<typename BaseType::VariableSet*>(BaseType::freeVariables());
             BOOST_FOREACH(void const* elem, *this) {
                 BaseType::insertVariables(vars, (el::Element const*)elem);
             }
             BaseType::freeVariables(vars);
     }
 }
template<typename BaseType , int type, typename SymbolType , typename ArgType > bcplus::elements::detail::IdentifierElement< BaseType, type, SymbolType, ArgType >::~IdentifierElement () virtual
Destructor stub.
Definition at line 87 of file IdentifierElement.impl.h.
{
     /* Intentionally left blank */
 }
Member Function Documentation
template<typename BaseType, int type, typename SymbolType, typename ArgType> ArgumentList const* bcplus::elements::detail::IdentifierElement< BaseType, type, SymbolType, ArgType >::args () const inline protected
The argument list.
Definition at line 127 of file IdentifierElement.h.
Referenced by bcplus::elements::detail::IdentifierElement< BaseType, type, SymbolType, ArgType >::IdentifierElement().
 { return _args; }
template<typename BaseType, int type, typename SymbolType, typename ArgType> size_t bcplus::elements::detail::IdentifierElement< BaseType, type, SymbolType, ArgType >::arity () const inline
Get the number of arguments.
Definition at line 114 of file IdentifierElement.h.
 { return _args->size(); }
template<typename BaseType, int type, typename SymbolType, typename ArgType> const_iterator bcplus::elements::detail::IdentifierElement< BaseType, type, SymbolType, ArgType >::begin () const inline
Argument list iterators.
Definition at line 117 of file IdentifierElement.h.
 { return _args->begin(); }
template<typename BaseType , int type, typename SymbolType , typename ArgType > Element * bcplus::elements::detail::IdentifierElement< BaseType, type, SymbolType, ArgType >::copy () const virtual
Reimplemented from bcplus::elements::detail::IdentifierElement_bare< BaseType, type, SymbolType >.
Definition at line 92 of file IdentifierElement.impl.h.
References bcplus::elements::detail::IdentifierElement_bare< BaseType, type, SymbolType >::symbol().
{
     // Create a new list
     u::ref_ptr<ArgumentList> l = new ArgumentList();
     for (const_iterator it = begin(); it != end(); it++) {
         l->push_back((ArgType*)(*it)->copy());
     }
     return new IdentifierElement<BaseType, type, SymbolType, ArgType>(IdentifierElement_bare<BaseType, type, SymbolType>::symbol(), l, ((BaseType const*)this)->beginLoc(), ((BaseType const*)this)->endLoc(), ((BaseType const*)this)->parens());
 }
template<typename BaseType, int type, typename SymbolType, typename ArgType> const_iterator bcplus::elements::detail::IdentifierElement< BaseType, type, SymbolType, ArgType >::end () const inline
Definition at line 118 of file IdentifierElement.h.
 { return _args->end(); }
template<typename BaseType , int type, typename SymbolType , typename ArgType > void bcplus::elements::detail::IdentifierElement< BaseType, type, SymbolType, ArgType >::output (std::ostream & out) const virtual
Reimplemented from bcplus::elements::detail::IdentifierElement_bare< BaseType, type, SymbolType >.
Definition at line 104 of file IdentifierElement.impl.h.
References bcplus::elements::detail::IdentifierElement_bare< BaseType, type, SymbolType >::output().
Referenced by bcplus::elements::AtomicFormula::output().
{
     IdentifierElement_bare<BaseType, type, SymbolType>::output(out);
     if (arity() > 0) {
         out << "(";
         for (const_iterator it = begin(); it != end(); ) {
             (*it)->output(out);
             it++;
             if (it != end()) {
                 out << ", ";
             }
         }
         out << ")";
     }
 }
The documentation for this class was generated from the following files:
bcplusparser/include/bcplus/elements/detail/IdentifierElement.h
bcplusparser/include/bcplus/elements/detail/IdentifierElement.impl.h