cplus2asp: as2transition::Timestep Class Reference
as2transition::Timestep Class Reference
Holds information about the predicates that are true at a given time step.
#include <Timestep.h>
Public Types
typedef std::list
< babb::utils::ref_ptr
< Predicate > > PredList
typedef PredList::iterator iterator
typedef PredList::const_iterator const_iterator
Public Member Functions
Timestep (Config const *config, size_t time=TIMELESS)
Constructor.
virtual ~Timestep ()
Destructor. Deallocated associated predicates.
size_t time () const
Accessor for timeStep.
void add (Predicate *newPredicate)
Adds a predicate to our list of predicates.
const_iterator begin () const
Gets an iterator for the beginning of the list of all constants associated with the timestep.
const_iterator end () const
Gets an iterator for the end of the list of all constants associated with the timestep.
size_t num () const
Gets the number of constants in the timestep.
const_iterator beginFluents () const
Gets an iterator for the beginning of the list of fluents in the timestep.
const_iterator endFluents () const
Gets an iterator for the end the list of fluents in the timestep.
size_t numFluents () const
Gets the number of fluents in the timestep.
const_iterator beginExtFluents () const
Gets an iterator for the beginning of the list of static abnormalities in the timestep.
const_iterator endExtFluents () const
Gets an iterator for the end the list of static abnormalities in the timestep.
size_t numExtFluents () const
Gets the number of static abnormalities in teh timestep.
const_iterator beginActions () const
Gets an iterator for the beginning of the list of actions occurring in the transition.
const_iterator endActions () const
Gets an iterator for the beginning of the list of actions occurring in the transition.
size_t numActions ()
Gets the number of actions in the timestep.
const_iterator beginExtActions () const
Gets an iterator for the beginning of the list of dynamnic abnormalities occurring in the transition.
const_iterator endExtActions () const
Gets an iterator for the beginning of the list of dynamic abnormalities occurring in the transition.
size_t numExtActions () const
Gets the number of dynamic abnormalities in the timestep.
size_t output (std::ostream &out) const
Outputs the contents of this timestep to one or more output streams.
Public Member Functions inherited from babb::utils::Referenced
Referenced ()
Referenced ()
Static Public Attributes
static const size_t TIMELESS = Predicate::TIMELESS
Time value to indicate that the timestep is not associated with a step in the transition system.
Additional Inherited Members
Protected Member Functions inherited from babb::utils::Referenced
virtual ~Referenced ()
virtual ~Referenced ()
Detailed Description
Holds information about the predicates that are true at a given time step.
Definition at line 40 of file Timestep.h.
Member Typedef Documentation
typedef PredList::const_iterator as2transition::Timestep::const_iterator
Definition at line 48 of file Timestep.h.
typedef PredList::iterator as2transition::Timestep::iterator
Definition at line 47 of file Timestep.h.
typedef std::list<babb::utils::ref_ptr<Predicate> > as2transition::Timestep::PredList
Definition at line 46 of file Timestep.h.
Constructor & Destructor Documentation
as2transition::Timestep::Timestep (Config const * config, size_t time = TIMELESS) inline
Constructor.
Parameters
config The AS2Transition configuration used to format the timestep.
time The time stamp associated with this timestep (or TIMELESS).
Definition at line 79 of file Timestep.h.
         : _time(time), _config(config)
     { /* Intentionally left blank */ }
virtual as2transition::Timestep::~Timestep () inline virtual
Destructor. Deallocated associated predicates.
Definition at line 84 of file Timestep.h.
{
         // intentionally left blank
     }
Member Function Documentation
void as2transition::Timestep::add (Predicate * newPredicate)
Adds a predicate to our list of predicates.
Automatically keeps the predicates sorted.
Parameters
newPredicate - The predicate object to add.
Definition at line 41 of file Timestep.cpp.
References as2transition::Predicate::Type::ACTION, as2transition::Predicate::constType(), as2transition::Predicate::Type::EXT_ACTION, as2transition::Predicate::Type::EXT_FLUENT, as2transition::Predicate::Type::FLUENT, as2transition::Predicate::Type::RIGID, and as2transition::Predicate::Type::UNKNOWN.
Referenced by as2transition::TransitionPath::add().
 {
     insert(_constants, newPredicate);
     switch (newPredicate->constType()) {
     case Predicate::Type::EXT_FLUENT:
         insert(_extFluents, newPredicate);
         break;
     case Predicate::Type::EXT_ACTION:
         insert(_extActions, newPredicate);
         break;
     case Predicate::Type::ACTION:
         insert(_actions, newPredicate);
         break;
     case Predicate::Type::RIGID:
     case Predicate::Type::UNKNOWN:
     case Predicate::Type::FLUENT:
     default:
         insert(_fluents, newPredicate);
         break;
     }
 }
const_iterator as2transition::Timestep::begin () const inline
Gets an iterator for the beginning of the list of all constants associated with the timestep.
Definition at line 102 of file Timestep.h.
 { return _constants.begin(); }
const_iterator as2transition::Timestep::beginActions () const inline
Gets an iterator for the beginning of the list of actions occurring in the transition.
Definition at line 124 of file Timestep.h.
 { return _actions.begin(); }
const_iterator as2transition::Timestep::beginExtActions () const inline
Gets an iterator for the beginning of the list of dynamnic abnormalities occurring in the transition.
Definition at line 131 of file Timestep.h.
 { return _extActions.begin(); }
const_iterator as2transition::Timestep::beginExtFluents () const inline
Gets an iterator for the beginning of the list of static abnormalities in the timestep.
Definition at line 116 of file Timestep.h.
 { return _extFluents.begin(); }
const_iterator as2transition::Timestep::beginFluents () const inline
Gets an iterator for the beginning of the list of fluents in the timestep.
Definition at line 109 of file Timestep.h.
 { return _fluents.begin(); }
const_iterator as2transition::Timestep::end () const inline
Gets an iterator for the end of the list of all constants associated with the timestep.
Definition at line 104 of file Timestep.h.
 { return _constants.end(); }
const_iterator as2transition::Timestep::endActions () const inline
Gets an iterator for the beginning of the list of actions occurring in the transition.
Definition at line 126 of file Timestep.h.
 { return _actions.end(); }
const_iterator as2transition::Timestep::endExtActions () const inline
Gets an iterator for the beginning of the list of dynamic abnormalities occurring in the transition.
Definition at line 133 of file Timestep.h.
 { return _extActions.end(); }
const_iterator as2transition::Timestep::endExtFluents () const inline
Gets an iterator for the end the list of static abnormalities in the timestep.
Definition at line 118 of file Timestep.h.
 { return _extFluents.end(); }
const_iterator as2transition::Timestep::endFluents () const inline
Gets an iterator for the end the list of fluents in the timestep.
Definition at line 111 of file Timestep.h.
 { return _fluents.end(); }
size_t as2transition::Timestep::num () const inline
Gets the number of constants in the timestep.
Definition at line 106 of file Timestep.h.
 { return _constants.size(); }
size_t as2transition::Timestep::numActions () inline
Gets the number of actions in the timestep.
Definition at line 128 of file Timestep.h.
 { return _actions.size(); }
size_t as2transition::Timestep::numExtActions () const inline
Gets the number of dynamic abnormalities in the timestep.
Definition at line 135 of file Timestep.h.
 { return _extActions.size(); }
size_t as2transition::Timestep::numExtFluents () const inline
Gets the number of static abnormalities in teh timestep.
Definition at line 120 of file Timestep.h.
 { return _extFluents.size(); }
size_t as2transition::Timestep::numFluents () const inline
Gets the number of fluents in the timestep.
Definition at line 113 of file Timestep.h.
 { return _fluents.size(); }
size_t as2transition::Timestep::output (std::ostream & out) const
Outputs the contents of this timestep to one or more output streams.
Parameters
out - The stream to output to.
Returns
The number of predicates output in this timestep.
Definition at line 77 of file Timestep.cpp.
References time(), and TIMELESS.
Referenced by as2transition::operator<<().
{
     size_t counter = 0;
     if (time() == TIMELESS) {
         out << "\t";
     } else {
         // Output time step header and appropriate trailing whitespace.
         out << "\t" << time() << ": ";
     }
     counter += print(out, _fluents);
     if (!_config->separateActions()) {
         counter += print(out, _actions);
     }
     counter += print(out, _extFluents,
         (_config->separateExternal()) ? "EXTERNAL FLUENTS" : NULL);
     if (_config->separateActions()) {
         counter += print(out, _actions, "ACTIONS");
     }
     counter += print(out, _extActions,
         (_config->separateExternal()) ? "EXTERNAL ACTIONS" : NULL);
     out << std::endl;
     return counter;
 }
size_t as2transition::Timestep::time () const inline
Accessor for timeStep.
Returns
The value of timeStep.
Definition at line 92 of file Timestep.h.
Referenced by output().
 { return _time; }
Member Data Documentation
const size_t as2transition::Timestep::TIMELESS = Predicate::TIMELESS static
Time value to indicate that the timestep is not associated with a step in the transition system.
Definition at line 52 of file Timestep.h.
Referenced by output().
The documentation for this class was generated from the following files:
as2transition/include/as2transition/Timestep.h
as2transition/src/as2transition/Timestep.cpp