cplus2asp: bcplus::symbols::MacroSymbol Class Reference
bcplus::symbols::MacroSymbol Class Reference
#include <MacroSymbol.h>
Public Types
typedef ReferencedVector
< babb::utils::ref_ptr< const
ReferencedString > >::type ArgumentList
typedef ArgumentList::iterator iterator
typedef
ArgumentList::const_iterator const_iterator
typedef ReferencedVector
< babb::utils::ref_ptr< const
elements::Element > >::type ElementList
typedef ReferencedVector
< babb::utils::ref_ptr< const
parser::Token > >::type TokenList
Public Member Functions
MacroSymbol (ReferencedString const *base, ReferencedString const *text, ArgumentList *args=NULL)
Initializes the macro symbol.
MacroSymbol (boost::property_tree::ptree const &node, std::ostream *err)
Attempts to load the symbol from the property tree node.
virtual ~MacroSymbol ()
Destructor.
const_iterator begin () const
Iterate over the formal arguments.
const_iterator end () const
ReferencedString const * text () const
Get the macro definition text.
std::string expand (ArgumentList const *args=NULL) const
Expand the macro given the provided arguments list.
std::string expand (ElementList const *args) const
std::string expand (TokenList const *args) const
virtual void save (boost::property_tree::ptree &node) const
Outputs the symbol to the provided property tree node.
virtual void outputDefinition (std::ostream &out) const
DomainType::type domainType () const
Determine the domain type of this symbol.
Public Member Functions inherited from bcplus::symbols::Symbol
Symbol (Type::type type, babb::utils::ReferencedString const *base, size_t arity)
Basic Constructor.
Symbol (Type::type type, boost::property_tree::ptree const &node, std::ostream *err=NULL)
Attempts to load the symbol from the property tree node.
virtual ~Symbol ()
Destructor stub.
Type::type type () const
Get the symbol type.
char const * typeString () const
Get the symbol type as a cstring.
size_t arity () const
Get the arity of the symbol.
babb::utils::ReferencedString
const * base () const
Get the base name of the symbol.
babb::utils::ReferencedString
const * name () const
Get the full name of the symbol.
bool good () const
Determines if the symbol has been successfully loaded.
bool match (std::string const &b, size_t a) const
Determine if this symbol matches the provided detail.
bool match (std::string const &n) const
Determine if this symbol matches the provided detail.
Referenced * metadata () const
Get/set the metadata.
template<typename T >
T * metadata () const
Referenced * metadata ()
template<typename T >
T * metadata ()
void metadata (Referenced *data)
virtual bool operator== (Symbol const &other) const
Check to see if two symbols are equal.
bool operator!= (Symbol const &other) const
Public Member Functions inherited from babb::utils::Referenced
Referenced ()
Referenced ()
Additional Inherited Members
Static Public Member Functions inherited from bcplus::symbols::Symbol
static std::string genName (std::string const &base, size_t arity=0)
Generate the symbol's name from its base and arity.
Protected Member Functions inherited from bcplus::symbols::Symbol
void good (bool l)
Set the good flag.
Protected Member Functions inherited from babb::utils::Referenced
virtual ~Referenced ()
virtual ~Referenced ()
Detailed Description
Definition at line 19 of file MacroSymbol.h.
Member Typedef Documentation
typedef ReferencedVector<babb::utils::ref_ptr<const ReferencedString> >::type bcplus::symbols::MacroSymbol::ArgumentList
Definition at line 24 of file MacroSymbol.h.
typedef ArgumentList::const_iterator bcplus::symbols::MacroSymbol::const_iterator
Definition at line 26 of file MacroSymbol.h.
typedef ReferencedVector<babb::utils::ref_ptr<const elements::Element> >::type bcplus::symbols::MacroSymbol::ElementList
Definition at line 28 of file MacroSymbol.h.
typedef ArgumentList::iterator bcplus::symbols::MacroSymbol::iterator
Definition at line 25 of file MacroSymbol.h.
typedef ReferencedVector<babb::utils::ref_ptr<const parser::Token> >::type bcplus::symbols::MacroSymbol::TokenList
Definition at line 29 of file MacroSymbol.h.
Constructor & Destructor Documentation
bcplus::symbols::MacroSymbol::MacroSymbol (ReferencedString const * base, ReferencedString const * text, ArgumentList * args = NULL)
Initializes the macro symbol.
Parameters
base The base name for the macro.
text The text that will be used as an expansion template.
args formal arguments for the macro to be expanded (or NULL for no arguments).
Definition at line 29 of file MacroSymbol.cpp.
     : Symbol(Symbol::Type::MACRO, base, (args ? args->size() : 0)), _text(text) {
     if (args) _args = args;
     else _args = new ArgumentList();
     compileArgMap();
 }
bcplus::symbols::MacroSymbol::MacroSymbol (boost::property_tree::ptree const & node, std::ostream * err)
Attempts to load the symbol from the property tree node.
Parameters
node The node to load the symbol from
err An error stream to write to or NULL. Sets the symbol's good flag if it was successful.
Definition at line 37 of file MacroSymbol.cpp.
References bcplus::symbols::Symbol::arity(), bcplus::symbols::Symbol::good(), and bcplus::symbols::Symbol::name().
     : Symbol(Symbol::Type::MACRO, node, err) {
     babb::utils::ref_ptr<ArgumentList> args = new ArgumentList();
     // Get the text definition of the macro
     try {
         _text = new ReferencedString(node.get<std::string>("<xmlattr>.text"));
     } catch (boost::property_tree::ptree_error const& e) {
         good(false);
         if (err) *err << "ERROR: An error occurred scanning the definition of \"" << *name() << "\". Expected a 'text' attribute containing the macro expansion text." << std::endl;
     }
     // Get all of the sorts for each of the arguments
     for (size_t i = 0; i < arity(); i++) {
         try {
             std::string arg = node.get<std::string>("<xmlattr>.arg" + boost::lexical_cast<std::string>(i));
             args->push_back(new ReferencedString(arg));
         } catch (boost::property_tree::ptree_error& e) {
             good(false);
             if (err) *err << "ERROR: An error occurred scanning the definition of \"" << *name() << "\". The value for argument " << i << " is not properly declared. Please ensure there is an 'arg" << i << "' attribute attached to the declaration." << std::endl;
         }
     }
     _args = args;
     if (good()) compileArgMap();
 }
bcplus::symbols::MacroSymbol::~MacroSymbol () virtual
Destructor.
Definition at line 66 of file MacroSymbol.cpp.
{
     delete[] _arg_map;
 }
Member Function Documentation
const_iterator bcplus::symbols::MacroSymbol::begin () const inline
Iterate over the formal arguments.
Definition at line 69 of file MacroSymbol.h.
Referenced by outputDefinition().
 { return _args->begin(); }
DomainType::type bcplus::symbols::MacroSymbol::domainType () const virtual
Determine the domain type of this symbol.
Implements bcplus::symbols::Symbol.
Definition at line 169 of file MacroSymbol.cpp.
References bcplus::DomainType::NO_DOMAIN.
{
     return DomainType::NO_DOMAIN;
 }
const_iterator bcplus::symbols::MacroSymbol::end () const inline
Definition at line 70 of file MacroSymbol.h.
Referenced by outputDefinition().
 { return _args->end(); }
std::string bcplus::symbols::MacroSymbol::expand (ArgumentList const * args = NULL) const
Expand the macro given the provided arguments list.
Definition at line 98 of file MacroSymbol.cpp.
References bcplus::symbols::Symbol::arity().
Referenced by bcplus::elements::Macro::Macro().
{
     if (!args && !arity()) return *_text;
     else if (!args) return "<MACRO_ERROR>";
     if (args->size() != arity()) return "<MACRO_ERROR>";
     // start with macro definition
     std::string result = *_text;
     for (size_t i = 0; i < arity(); i++) {
         size_t j = _arg_map[i];
         boost::replace_all(result, *(*_args)[j], *(*args)[j]);
     }
     return result;
 }
std::string bcplus::symbols::MacroSymbol::expand (ElementList const * args) const
std::string bcplus::symbols::MacroSymbol::expand (TokenList const * args) const
void bcplus::symbols::MacroSymbol::outputDefinition (std::ostream & out) const virtual
Definition at line 149 of file MacroSymbol.cpp.
References bcplus::symbols::Symbol::arity(), bcplus::symbols::Symbol::base(), begin(), and end().
{
     out << *base();
     if (arity()) {
         out << "(";
         for (const_iterator it = begin(); it != end(); ) {
             out << **it;
             it++;
             if (it != end()) {
                 out << ", ";
             }
         }
         out << ")";
     }
     out << " -> " << *_text;
 }
void bcplus::symbols::MacroSymbol::save (boost::property_tree::ptree & node) const virtual
Outputs the symbol to the provided property tree node.
Parameters
node The node to write to
Reimplemented from bcplus::symbols::Symbol.
Definition at line 70 of file MacroSymbol.cpp.
References bcplus::symbols::Symbol::save().
{
     Symbol::save(node);
     node.put("<xmlattr>.text", *_text);
     size_t arg = 0;
     BOOST_FOREACH(ReferencedString const* argval, *_args) {
         node.put("<xmlattr>.arg" + boost::lexical_cast<std::string>(arg++), *argval);
     }
 }
ReferencedString const* bcplus::symbols::MacroSymbol::text () const inline
Get the macro definition text.
Definition at line 74 of file MacroSymbol.h.
 { return _text; }
The documentation for this class was generated from the following files:
bcplusparser/include/bcplus/symbols/MacroSymbol.h
bcplusparser/src/bcplus/symbols/MacroSymbol.cpp