cplus2asp: BaseLikeElement Class Reference
BaseLikeElement Class Reference abstract
Child of ParseElement that acts as a base class for parsed elements like constants and objects.
#include <parser_types.h>
Public Member Functions
BaseLikeElement (ParseElementType elemType, std::string const &baseName, Element const *symbolRef, ParseElementList *params=NULL, bool parens=false)
Full constructor.
virtual std::ostream & translate (std::ostream &out, Context &context) const =0
Method that generates a translated string representation of the element with preceeding @ if a symbol is understood as a lua function call.
virtual bool hasConstants (unsigned int types, bool includeParams=true, bool includeEq=true) const =0
Returns true if the element (or any of its children) are constants of the provided types.
virtual bool isDefinite (bool allowComparison=false, bool allowChoice=false, bool allowAtomicNegation=false) const =0
Determines if the element contains a single atom, a unary expression w/ a single atom, or a conjunction thereof.
virtual bool isSingleAtom (bool allowAtomicNegation=false) const =0
Whether the formula is a single atom.
virtual bool isArithExpr () const
Determines if the element is a valid arithmetic expression.
virtual bool hasLuaCalls (bool includeParams=true, bool includeEq=true) const =0
Determines if the element contains any calls to LUA.
virtual IPart determineQueryIPart () const =0
Determines the proper IPart to place the formula in.
virtual std::ostream & fullName (std::ostream &out) const
Prints the untranslated element string.
virtual ParseElement * copy () const =0
Returns an exact copy of the parse element.
virtual void aggregateUndefined (BaseElementList &outIdentifiers)
Aggregates all of the undefined identifiers (which are assumed to be constants).
virtual bool isNumeric () const =0
Determines if the element ranges over numeric values.
virtual bool isBoolean () const =0
Determines if the element ranges over boolean values.
std::string const & baseName () const
Gets the base name for the element.
Element const * ref () const
Gets a reference to the global symbol which this element is an instance of.
void ref (Element const *_ref)
Sets the global symbol which this element is an instance of.
ParseElementList::const_iterator paramsBegin () const
Gets an iterator for the beginning of the parameter list.
ParseElementList::const_iterator paramsEnd () const
Gets an iterator for the end of the parameter list.
size_t arity () const
Gets the number of parameters the element has.
void detachParams ()
Clears the list of parameters without deallocating them.
virtual bool guessParamSorts (ConstSortList &outSorts)
Attempts to guess the sorts of each parameter.
virtual std::ostream & translateParams (std::ostream &out, Context &context, bool force=false) const
Internal helper to translate, creates a list of translated params.
virtual ~BaseLikeElement ()
Destructor.
Public Member Functions inherited from ParseElement
ParseElement (ParseElementType elemType, bool parens=false)
Default constructor.
bool isTrivial (bool includeParams=true, bool includeEq=true) const
Determines if the element contains no (real) constants.
std::string fullName () const
Alternative helper to fullName(std::ostream&).
ParseElementType getType () const
Gets the type of the parse element.
void parens (bool parens)
Sets whether the expression is wrapped in parentheses.
bool parens () const
Gets whether the element is encompassed in parens.
virtual ~ParseElement ()
Destructor.
Protected Member Functions
ParseElementList::iterator paramsBegin ()
Gets an iterator for the beginning of the parameter list.
ParseElementList::iterator paramsEnd ()
Gets an iterator for the end of the parameter list.
bool hasLuaCallParameters () const
Determines if the base element has a LUA call in its parameter list.
bool hasConstantParameters (unsigned int types) const
Checks to see if there is a nested constant matching the type mask within the parameter list.
Protected Member Functions inherited from ParseElement
bool hasParens () const
Determines if the element has parentheses around it.
std::string translateBeforeParen (bool forceParens=false) const
Helper to translate that intelligently handles the value of parenBefore.
std::string translateAfterParen (bool forceParens=false) const
Helper to translate that intelligently handles the value of parenAfter.
Additional Inherited Members
Public Types inherited from ParseElement
enum ParseElementType {
PELEM_PELEM, PELEM_UOP, PELEM_BOP, PELEM_QUANT,
PELEM_BASELIKE, PELEM_CONSTLIKE, PELEM_OBJLIKE, PELEM_VARLIKE
}
The possible types of a ParseElement instance.
enum ConstMask {
MASK_ACTION = 0x01, MASK_FLUENT = 0x02, MASK_RIGID = 0x04, MASK_STATIC_AB = 0x08,
MASK_DYNAMIC_AB = 0x10, MASK_TRUE_FALSE = 0x20, MASK_SDFLUENT = 0x40, MASK_AB = MASK_STATIC_AB | MASK_DYNAMIC_AB,
MASK_NON_TRIVIAL = ~MASK_TRUE_FALSE, MASK_NON_RIGID = MASK_NON_TRIVIAL & ~MASK_RIGID, MASK_NON_AB = MASK_NON_TRIVIAL & ~MASK_AB
}
Mask values for the various kinds of constants that can be in a formula.
Static Public Member Functions inherited from ParseElement
static std::string getNewVar ()
Gets a new variable whose name is unique within the rule we're translating.
Detailed Description
Child of ParseElement that acts as a base class for parsed elements like constants and objects.
Definition at line 587 of file parser_types.h.
Constructor & Destructor Documentation
BaseLikeElement::BaseLikeElement (ParseElementType elemType, std::string const & baseName, Element const * symbolRef, ParseElementList * params = NULL, bool parens = false) inline
Full constructor.
Parameters
elemType The concrete type that's being instantiated.
baseName The base name of the element that's being instantiated (without parameters).
symbolRef A pointer to the symbol that this element is an instance of.
params The list of parameters associated with this instance. Null if there are no parameters.
parens Whether the element should be encased in parens.
Definition at line 606 of file parser_types.h.
         : ParseElement(elemType, parens), mBaseName(baseName), mSymbolRef(symbolRef)
     {
         if (params) mParams = *params;
     }
BaseLikeElement::~BaseLikeElement () virtual
Destructor.
Deallocates contents of params.
Definition at line 1045 of file parser_types.cpp.
References paramsBegin(), and paramsEnd().
 {
     for(ParseElementList::iterator vIter = paramsBegin(); vIter != paramsEnd(); vIter++) {
         if(*vIter) delete *vIter;
     }
 }
Member Function Documentation
virtual void BaseLikeElement::aggregateUndefined (BaseElementList & outIdentifiers) inline virtual
Aggregates all of the undefined identifiers (which are assumed to be constants).
Parameters
outIdentifiers The undefined identifiers.
Implements ParseElement.
Definition at line 622 of file parser_types.h.
References ref().
 { if (!ref()) outIdentifiers.push_back(this); }
size_t BaseLikeElement::arity () const inline
Gets the number of parameters the element has.
Definition at line 652 of file parser_types.h.
Referenced by fullName(), ObjectLikeElement::hasConstants(), and translateParams().
 { return mParams.size(); }
std::string const& BaseLikeElement::baseName () const inline
Gets the base name for the element.
Definition at line 637 of file parser_types.h.
Referenced by ConstantLikeElement::copy(), ObjectLikeElement::copy(), VariableLikeElement::copy(), fullName(), ObjectLikeElement::hasConstants(), ObjectLikeElement::isBoolean(), ObjectLikeElement::isDefinite(), ConstantLikeElement::translate(), ObjectLikeElement::translate(), ConstantLikeElement::translateAsConstant(), VariableLikeElement::translateAsConstant(), and VariableLikeElement::translateAsVariable().
 { return mBaseName; }
virtual ParseElement* BaseLikeElement::copy () const pure virtual
Returns an exact copy of the parse element.
Implements ParseElement.
Implemented in VariableLikeElement, ObjectLikeElement, and ConstantLikeElement.
void BaseLikeElement::detachParams () inline
Clears the list of parameters without deallocating them.
Definition at line 656 of file parser_types.h.
Referenced by Translator::translateIncrementLaw().
 { mParams.clear(); }
virtual IPart BaseLikeElement::determineQueryIPart () const pure virtual
Determines the proper IPart to place the formula in.
Returns
IPART_BASE if the formula is 0:(...), IPART_VOLATILE if the formula is X:(...), and IPART_CUMULATIVE if the formula is anything else.
Implements ParseElement.
Implemented in VariableLikeElement, ObjectLikeElement, and ConstantLikeElement.
std::ostream & BaseLikeElement::fullName (std::ostream & out) const virtual
Prints the untranslated element string.
Parameters
out The output stream to print to.
Returns
out.
Implements ParseElement.
Definition at line 1004 of file parser_types.cpp.
References arity(), baseName(), paramsBegin(), and paramsEnd().
Referenced by SimpleUnaryOperator::translate().
 {
     out << baseName();
     if(arity()) {
         out << "(";
         int i = 0;
         for(ParseElementList::const_iterator vIter = paramsBegin(); vIter != paramsEnd(); vIter++) {
             if(*vIter)
             {
                 if(i++ > 0) out <<",";
                 (*vIter)->fullName(out);
             }
         }
         out << ")";
     }
     return out;
 }
bool BaseLikeElement::guessParamSorts (ConstSortList & outSorts) virtual
Attempts to guess the sorts of each parameter.
This really will only work if every parameter is a variable.
Parameters
outSorts The list of sorts that we've guess (entries may be NULL if we don't know.).
Returns
True if all sorts have been successfully guessed. False otherwise.
Definition at line 956 of file parser_types.cpp.
References paramsBegin(), paramsEnd(), and ParseElement::PELEM_VARLIKE.
{
     bool foundAll = true;
     outSorts.clear();
     for (ParseElementList::const_iterator it = paramsBegin(); it != paramsEnd(); it++) {
         // Check if it's a variable, if it is then use it's sort.
         if ((*it)->getType() == PELEM_VARLIKE) {
             outSorts.push_back(((VariableLikeElement const*)*it)->domain());
         } else {
             // nope, it's not.
             outSorts.push_back(NULL);
             foundAll = false;
         }
     }
     return foundAll;
 }
bool BaseLikeElement::hasConstantParameters (unsigned int types) const protected
Checks to see if there is a nested constant matching the type mask within the parameter list.
Parameters
types A mask of the types of elements to look for.
Definition at line 1033 of file parser_types.cpp.
References paramsBegin(), and paramsEnd().
Referenced by ConstantLikeElement::hasConstants(), and ObjectLikeElement::hasConstants().
 {
     for(ParseElementList::const_iterator vIter = paramsBegin(); vIter != paramsEnd(); vIter++) {
         if (*vIter && (*vIter)->hasConstants(types, true)) return true;
     }
     return false;
 }
virtual bool BaseLikeElement::hasConstants (unsigned int types, bool includeParams = true, bool includeEq = true) const pure virtual
Returns true if the element (or any of its children) are constants of the provided types.
Parameters
types A mask containing flags for the types to search for. See ConstMask enum.
includeParams Whether to check the parameters of constants.
includeEq Whether to check the right side of equality within an atom. (The right hand side of comparisons will be checked regardless.)
Returns
True if the element, or any elements "beneach" it, are constants, false otherwise.
Implements ParseElement.
Implemented in VariableLikeElement, ObjectLikeElement, and ConstantLikeElement.
bool BaseLikeElement::hasLuaCallParameters () const protected
Determines if the base element has a LUA call in its parameter list.
Definition at line 1023 of file parser_types.cpp.
References paramsBegin(), and paramsEnd().
Referenced by ConstantLikeElement::hasLuaCalls(), and ObjectLikeElement::hasLuaCalls().
 {
     for(ParseElementList::const_iterator vIter = paramsBegin(); vIter != paramsEnd(); vIter++) {
         if (*vIter && (*vIter)->hasLuaCalls()) return true;
     }
     return false;
 }
virtual bool BaseLikeElement::hasLuaCalls (bool includeParams = true, bool includeEq = true) const pure virtual
Determines if the element contains any calls to LUA.
Parameters
includeParams Whether to search base element parameter lists.
includeEq Whether to check the right side of equality within an atom. (The right hand side of comparisons will be checked regardless.)
Returns
True if the element or any of its children is a LUA call.
Implements ParseElement.
Implemented in VariableLikeElement, ObjectLikeElement, and ConstantLikeElement.
virtual bool BaseLikeElement::isArithExpr () const inline virtual
Determines if the element is a valid arithmetic expression.
Returns
True if the element and all it's children are arithmetic expressions.
Implements ParseElement.
Definition at line 617 of file parser_types.h.
References isNumeric().
 { return isNumeric(); }
virtual bool BaseLikeElement::isBoolean () const pure virtual
Determines if the element ranges over boolean values.
Returns
True if the element ranges over strictly boolean values, false otherwise.
Implemented in VariableLikeElement, ObjectLikeElement, and ConstantLikeElement.
virtual bool BaseLikeElement::isDefinite (bool allowComparison = false, bool allowChoice = false, bool allowAtomicNegation = false) const pure virtual
Determines if the element contains a single atom, a unary expression w/ a single atom, or a conjunction thereof.
Parameters
allowComparison Whether to allow comparison operators in the formula.
allowChoice Whether to allow choice rules in the formula.
allowAtomicNegation whether to allow -p or "not p" where p is a boolean atom.
Returns
True if the element is a definite formula.
Implements ParseElement.
Implemented in VariableLikeElement, ObjectLikeElement, and ConstantLikeElement.
virtual bool BaseLikeElement::isNumeric () const pure virtual
Determines if the element ranges over numeric values.
Returns
True if the element ranges over strictly numeric values.
Implemented in VariableLikeElement, ObjectLikeElement, and ConstantLikeElement.
Referenced by isArithExpr().
virtual bool BaseLikeElement::isSingleAtom (bool allowAtomicNegation = false) const inline pure virtual
Whether the formula is a single atom.
Returns
True if the element is a single atom c=v (or just c if c is boolean).
Parameters
allowAtomicNegation whether to allow -p or "not p" where p is a boolean atom.
Implements ParseElement.
Implemented in VariableLikeElement, ObjectLikeElement, and ConstantLikeElement.
ParseElementList::const_iterator BaseLikeElement::paramsBegin () const inline
Gets an iterator for the beginning of the parameter list.
Definition at line 646 of file parser_types.h.
Referenced by ConstantLikeElement::copy(), ObjectLikeElement::copy(), fullName(), guessParamSorts(), hasConstantParameters(), ConstantLikeElement::hasConstants(), hasLuaCallParameters(), translateParams(), and ~BaseLikeElement().
 { return mParams.begin(); }
ParseElementList::iterator BaseLikeElement::paramsBegin () inline protected
Gets an iterator for the beginning of the parameter list.
Definition at line 685 of file parser_types.h.
 { return mParams.begin(); }
ParseElementList::const_iterator BaseLikeElement::paramsEnd () const inline
Gets an iterator for the end of the parameter list.
Definition at line 649 of file parser_types.h.
Referenced by ConstantLikeElement::copy(), ObjectLikeElement::copy(), fullName(), guessParamSorts(), hasConstantParameters(), ConstantLikeElement::hasConstants(), hasLuaCallParameters(), translateParams(), and ~BaseLikeElement().
 { return mParams.end(); }
ParseElementList::iterator BaseLikeElement::paramsEnd () inline protected
Gets an iterator for the end of the parameter list.
Definition at line 688 of file parser_types.h.
 { return mParams.end(); }
Element const* BaseLikeElement::ref () const inline
Gets a reference to the global symbol which this element is an instance of.
Definition at line 640 of file parser_types.h.
Referenced by aggregateUndefined(), ConstantLikeElement::copy(), ObjectLikeElement::copy(), VariableLikeElement::copy(), ConstantLikeElement::domain(), VariableLikeElement::domain(), ConstantLikeElement::hasConstants(), ObjectLikeElement::hasLuaCalls(), ConstantLikeElement::isBoolean(), ObjectLikeElement::isBoolean(), VariableLikeElement::isBoolean(), VariableLikeElement::isConstantVariable(), ConstantLikeElement::isContribConstant(), ConstantLikeElement::isDefinite(), VariableLikeElement::isDefinite(), ConstantLikeElement::isNumeric(), ObjectLikeElement::isNumeric(), VariableLikeElement::isNumeric(), ConstantLikeElement::isSingleAtom(), VariableLikeElement::isSingleAtom(), SimpleUnaryOperator::translate(), ConstantLikeElement::translate(), ObjectLikeElement::translate(), ConstantLikeElement::translateAsConstant(), VariableLikeElement::translateAsConstant(), ConstantLikeElement::translateAsVariable(), VariableLikeElement::translateAsVariable(), ConstantLikeElement::translatePostfix(), and ConstantLikeElement::translatePrefix().
 { return mSymbolRef; }
void BaseLikeElement::ref (Element const * _ref) inline
Sets the global symbol which this element is an instance of.
Definition at line 643 of file parser_types.h.
 { mSymbolRef = _ref; }
virtual std::ostream& BaseLikeElement::translate (std::ostream & out, Context & context) const pure virtual
Method that generates a translated string representation of the element with preceeding @ if a symbol is understood as a lua function call.
Parameters
[out] out - The output stream to write to.
context - The formula context to be used for translation.
Returns
out.
Implements ParseElement.
Implemented in VariableLikeElement, ObjectLikeElement, and ConstantLikeElement.
std::ostream & BaseLikeElement::translateParams (std::ostream & out, Context & context, bool force = false) const virtual
Internal helper to translate, creates a list of translated params.
Parameters
[out] out The stream to output to.
context The context used for translation.
force Whether to force the presence of parens regardless of the presence of arguments.
Returns
A parentheses-surrounded, comma-separated list of translated params, or a blank string if params is empty.
Definition at line 977 of file parser_types.cpp.
References arity(), paramsBegin(), and paramsEnd().
Referenced by ConstantLikeElement::translate(), ObjectLikeElement::translate(), and ConstantLikeElement::translateAsConstant().
 {
     Context localContext;
     if (context.getPos() != Context::POS_INTERNAL
             && context.getPos() != Context::POS_TERM
             && context.getPos() != Context::POS_MAXIMIZED_INTERNAL)
         localContext = context.mkPos(Context::POS_TERM);
     else
         localContext = context;
     int i = 0;
     if(arity() || force) {
         out <<  "(";
         for(ParseElementList::const_iterator vIter = paramsBegin(); vIter != paramsEnd(); vIter++)
         {
             if (*vIter) {
                 if(i++ > 0) out << ",";
                 (*vIter)->translate(out, localContext);
             }
         }
         out << ")";
     }
     return out;
 }
The documentation for this class was generated from the following files:
cplus2asp.bin/old/parser_types.h
cplus2asp.bin/old/parser_types.cpp