cplus2asp: bcplus::parser::detail::ScannerRawSource Class Reference
bcplus::parser::detail::ScannerRawSource Class Reference abstract
A simple base class for working with various raw text sources in the scanner.
#include <ScannerRawSource.h>
Classes
struct Status
Public Member Functions
ScannerRawSource (Configuration const *config)
virtual ~ScannerRawSource ()
Destructor.
Configuration const * config () const
Gets the system configuration.
char const *& cursor ()
Scanner state accessors / mutators.
char const *const & cursor () const
void cursor (char const *c)
char const *& limit ()
char const *const & limit () const
void limit (char const *l)
char const *& token ()
char const *const & token () const
void token (char const *t)
char const *& marker ()
char const *const & marker () const
void marker (char const *m)
char const *& ctxmarker ()
char const *const & ctxmarker () const
void ctxmarker (char const *m)
bool good () const
Determines if the source is ready to read from.
bool eof () const
virtual void newline ()=0
Callback which indicates that the scanner found a newline and the location should be updated.
virtual Location loc () const =0
Gets the current location of the source.
virtual Status::type status () const =0
Determines the status of the source.
virtual void close ()=0
Closes the source.
virtual void fill (size_t n)=0
Refills the buffer to the desired level.
Public Member Functions inherited from bcplus::parser::detail::ScannerSource
ScannerSource (Type::type type)
Basic Constructor.
virtual ~ScannerSource ()
Destructor stub.
Type::type type () const
Get the subtype of this source.
Public Member Functions inherited from babb::utils::Referenced
Referenced ()
Referenced ()
Additional Inherited Members
Protected Member Functions inherited from babb::utils::Referenced
virtual ~Referenced ()
virtual ~Referenced ()
Detailed Description
A simple base class for working with various raw text sources in the scanner.
Definition at line 21 of file ScannerRawSource.h.
Constructor & Destructor Documentation
bcplus::parser::detail::ScannerRawSource::ScannerRawSource (Configuration const * config)
Parameters
config The system wide configuration information
Definition at line 8 of file ScannerRawSource.cpp.
     : ScannerSource(ScannerSource::Type::RAW), _config(config), _cursor(NULL), _limit(NULL),
       _token(NULL), _marker(NULL), _ctxmarker(NULL) {
     // Intentionally left blank
 }
bcplus::parser::detail::ScannerRawSource::~ScannerRawSource () virtual
Destructor.
Definition at line 14 of file ScannerRawSource.cpp.
{
     // Intentionally left blank
 }
Member Function Documentation
virtual void bcplus::parser::detail::ScannerRawSource::close () pure virtual
Closes the source.
Implemented in bcplus::parser::detail::ScannerBufferSource, and bcplus::parser::detail::ScannerFileSource.
Configuration const* bcplus::parser::detail::ScannerRawSource::config () const inline
Gets the system configuration.
Definition at line 67 of file ScannerRawSource.h.
Referenced by bcplus::parser::detail::ScannerFileSource::fill(), and bcplus::parser::detail::ScannerFileSource::ScannerFileSource().
 { return _config; }
char const*& bcplus::parser::detail::ScannerRawSource::ctxmarker () inline
Definition at line 87 of file ScannerRawSource.h.
Referenced by bcplus::parser::detail::ScannerFileSource::fill(), bcplus::parser::detail::ScannerBufferSource::fill(), and bcplus::parser::detail::ScannerBufferSource::ScannerBufferSource().
 { return _ctxmarker; }
char const* const& bcplus::parser::detail::ScannerRawSource::ctxmarker () const inline
Definition at line 88 of file ScannerRawSource.h.
 { return _ctxmarker; }
void bcplus::parser::detail::ScannerRawSource::ctxmarker (char const * m) inline
Definition at line 89 of file ScannerRawSource.h.
 { _ctxmarker = m; }
char const*& bcplus::parser::detail::ScannerRawSource::cursor () inline
Scanner state accessors / mutators.
Definition at line 71 of file ScannerRawSource.h.
Referenced by bcplus::parser::detail::ScannerFileSource::fill(), bcplus::parser::detail::ScannerBufferSource::fill(), bcplus::parser::detail::ScannerFileSource::newline(), bcplus::parser::detail::ScannerBufferSource::newline(), bcplus::parser::detail::ScannerBufferSource::ScannerBufferSource(), bcplus::parser::detail::ScannerFileSource::status(), and bcplus::parser::detail::ScannerBufferSource::status().
 { return _cursor; }
char const* const& bcplus::parser::detail::ScannerRawSource::cursor () const inline
Definition at line 72 of file ScannerRawSource.h.
 { return _cursor; }
void bcplus::parser::detail::ScannerRawSource::cursor (char const * c) inline
Definition at line 73 of file ScannerRawSource.h.
 { _cursor = c; }
bool bcplus::parser::detail::ScannerRawSource::eof () const inline
Definition at line 94 of file ScannerRawSource.h.
References bcplus::parser::detail::ScannerRawSource::Status::END_INPUT, and status().
 { return status() == Status::END_INPUT; }
virtual void bcplus::parser::detail::ScannerRawSource::fill (size_t n) pure virtual
Refills the buffer to the desired level.
Parameters
n The minimum number of characters to fill.
Implemented in bcplus::parser::detail::ScannerBufferSource, and bcplus::parser::detail::ScannerFileSource.
bool bcplus::parser::detail::ScannerRawSource::good () const inline
Determines if the source is ready to read from.
Definition at line 93 of file ScannerRawSource.h.
References bcplus::parser::detail::ScannerRawSource::Status::OK, and status().
 { return status() == Status::OK; }
char const*& bcplus::parser::detail::ScannerRawSource::limit () inline
Definition at line 75 of file ScannerRawSource.h.
Referenced by bcplus::parser::detail::ScannerFileSource::fill(), bcplus::parser::detail::ScannerBufferSource::fill(), and bcplus::parser::detail::ScannerBufferSource::ScannerBufferSource().
 { return _limit; }
char const* const& bcplus::parser::detail::ScannerRawSource::limit () const inline
Definition at line 76 of file ScannerRawSource.h.
 { return _limit; }
void bcplus::parser::detail::ScannerRawSource::limit (char const * l) inline
Definition at line 77 of file ScannerRawSource.h.
 { _limit = l; }
virtual Location bcplus::parser::detail::ScannerRawSource::loc () const pure virtual
Gets the current location of the source.
Implements bcplus::parser::detail::ScannerSource.
Implemented in bcplus::parser::detail::ScannerBufferSource, and bcplus::parser::detail::ScannerFileSource.
char const*& bcplus::parser::detail::ScannerRawSource::marker () inline
Definition at line 83 of file ScannerRawSource.h.
Referenced by bcplus::parser::detail::ScannerFileSource::fill(), bcplus::parser::detail::ScannerBufferSource::fill(), and bcplus::parser::detail::ScannerBufferSource::ScannerBufferSource().
 { return _marker; }
char const* const& bcplus::parser::detail::ScannerRawSource::marker () const inline
Definition at line 84 of file ScannerRawSource.h.
 { return _marker; }
void bcplus::parser::detail::ScannerRawSource::marker (char const * m) inline
Definition at line 85 of file ScannerRawSource.h.
 { _marker = m; }
virtual void bcplus::parser::detail::ScannerRawSource::newline () pure virtual
Callback which indicates that the scanner found a newline and the location should be updated.
Implemented in bcplus::parser::detail::ScannerBufferSource, and bcplus::parser::detail::ScannerFileSource.
virtual Status::type bcplus::parser::detail::ScannerRawSource::status () const pure virtual
Determines the status of the source.
Implemented in bcplus::parser::detail::ScannerBufferSource, and bcplus::parser::detail::ScannerFileSource.
Referenced by eof(), and good().
char const*& bcplus::parser::detail::ScannerRawSource::token () inline
Definition at line 79 of file ScannerRawSource.h.
Referenced by bcplus::parser::detail::ScannerFileSource::col(), bcplus::parser::detail::ScannerBufferSource::col(), bcplus::parser::detail::ScannerFileSource::fill(), bcplus::parser::detail::ScannerBufferSource::fill(), and bcplus::parser::detail::ScannerBufferSource::ScannerBufferSource().
 { return _token; }
char const* const& bcplus::parser::detail::ScannerRawSource::token () const inline
Definition at line 80 of file ScannerRawSource.h.
 { return _token; }
void bcplus::parser::detail::ScannerRawSource::token (char const * t) inline
Definition at line 81 of file ScannerRawSource.h.
 { _token = t; }
The documentation for this class was generated from the following files:
bcplusparser/include/bcplus/parser/detail/ScannerRawSource.h
bcplusparser/src/bcplus/parser/detail/ScannerRawSource.cpp