cplus2asp: bcplus::symbols::Resolver Class Reference
bcplus::symbols::Resolver Class Reference abstract
A basic interface that resolves symbols based on their type, name, and arity.
#include <Resolver.h>
Public Member Functions
template<typename T >
T const * resolve (std::string const &name, size_t arity=0) const
Convenience resolve call for a single type.
template<typename T >
T * resolve (std::string const &name, size_t arity=0)
virtual Symbol const * resolve (size_t typemask, std::string const &name, size_t arity=0) const =0
Find a specific type of symbol matching the provided name/arity.
virtual Symbol * resolve (size_t typemask, std::string const &name, size_t arity=0)=0
virtual bool create (Symbol *symbol)=0
Attempt to create register the provided symbol in the table.
template<typename T >
T * resolveOrCreate (T *symbol)
Attempts to resolve a symbol matching the provided object and attempts to create it if not found.
template<typename T >
T * resolveOrCreate (babb::utils::ref_ptr< T > symbol)
Detailed Description
A basic interface that resolves symbols based on their type, name, and arity.
Definition at line 18 of file Resolver.h.
Member Function Documentation
virtual bool bcplus::symbols::Resolver::create (Symbol * symbol) pure virtual
Attempt to create register the provided symbol in the table.
Parameters
symbol The symbol to register.
Returns
True if successful, false othwerise.
Implemented in bcplus::symbols::SymbolTable.
template<typename T > T const* bcplus::symbols::Resolver::resolve (std::string const & name, size_t arity = 0) const inline
Convenience resolve call for a single type.
Definition at line 23 of file Resolver.h.
References resolve().
Referenced by bcplus::symbols::AttributeSymbol::AttributeSymbol(), bcplus::symbols::detail::BaseSymbol::BaseSymbol(), bcplus::symbols::ConstantSymbol::ConstantSymbol(), resolve(), and bcplus::symbols::VariableSymbol::VariableSymbol().
 { return (T const*)resolve(T::type_value, name, arity); }
template<typename T > T* bcplus::symbols::Resolver::resolve (std::string const & name, size_t arity = 0) inline
Definition at line 26 of file Resolver.h.
References resolve().
Referenced by resolve().
 { return (T*)resolve(T::type_value, name, arity); }
virtual Symbol const* bcplus::symbols::Resolver::resolve (size_t typemask, std::string const & name, size_t arity = 0) const pure virtual
Find a specific type of symbol matching the provided name/arity.
Parameters
typemask A mask of types that we should look for
base The base name of the symbol
arity The arity of the symbol
Returns
The symbol matching the parameters or NULL if it doesn't exist.
Implemented in bcplus::symbols::SymbolTable.
virtual Symbol* bcplus::symbols::Resolver::resolve (size_t typemask, std::string const & name, size_t arity = 0) pure virtual
Implemented in bcplus::symbols::SymbolTable.
template<typename T > T* bcplus::symbols::Resolver::resolveOrCreate (T * symbol) inline
Attempts to resolve a symbol matching the provided object and attempts to create it if not found.
Parameters
symbol The symbol to match.
Returns
The symbol within the symbol table matching 'symbol' if one exists, 'symbol' if it was successfully added to the symbol table, and NULL if an error occurred adding the symbol.
Definition at line 46 of file Resolver.h.
Referenced by bcplus::parser::BCParser::_newRangeSymbol(), bcplus::symbols::SortSymbol::loadDefinition(), bcplus::symbols::SymbolTable::plus(), and bcplus::symbols::SymbolTable::SymbolTable().
 {   return (T*)_resolveOrCreate(symbol); }
template<typename T > T* bcplus::symbols::Resolver::resolveOrCreate (babb::utils::ref_ptr< T > symbol) inline
Definition at line 49 of file Resolver.h.
 { return (T*)_resolveOrCreate(symbol); }
The documentation for this class was generated from the following file:
bcplusparser/include/bcplus/symbols/Resolver.h