cplus2asp: bcplus::elements::Macro Class Reference
bcplus::elements::Macro Class Reference
An arbitrary macro instance 'm(...)'.
#include <Macro.h>
Public Member Functions
Macro (symbols::MacroSymbol const *symbol, ArgumentList const *args, Location const &begin=Location(NULL, 0, 0), Location const &end=Location(NULL, 0, 0), bool parens=false)
Full constructor.
virtual ~Macro ()
Stub destructor.
ReferencedString const * expand () const
Expand this macro into its final form.
Public Member Functions inherited from bcplus::elements::detail::IdentifierElement< Element, Element::Type::MACRO, symbols::MacroSymbol, parser::Token >
IdentifierElement (symbols::MacroSymbolconst *symbol, ArgumentList const *args=NULL, Location const &begin=Location(NULL, 0, 0), Location const &end=Location(NULL, 0, 0), bool parens=false)
Full constructor.
virtual ~IdentifierElement ()
Destructor stub.
size_t arity () const
Get the number of arguments.
const_iterator begin () const
Argument list iterators.
const_iterator end () const
virtual Element * copy () const
virtual void output (std::ostream &out) const
Public Member Functions inherited from bcplus::elements::detail::IdentifierElement_bare< Element, type, symbols::MacroSymbol >
IdentifierElement_bare (symbols::MacroSymbolconst *symbol, Location const &begin=Location(NULL, 0, 0), Location const &end=Location(NULL, 0, 0), bool parens=false)
Full constructor.
virtual ~IdentifierElement_bare ()
Destructor stub.
symbols::MacroSymbolconst * symbol () const
The symbol entry for this identifier.
virtual DomainType::type domainType () const
Public Member Functions inherited from bcplus::elements::Element
Element (Type::type type, ConstantSet const *constants, VariableSet const *variables, int cmask, Location const &begin=Location(NULL, 0, 0), Location const &end=Location(NULL, 0, 0), bool parens=false)
Full constructor.
virtual ~Element ()
Destructor stub.
bool parens () const
Getter/setter for whether or not this element has parentheses.
void parens (bool p)
Type::type type () const
Determines the type of the element.
Location const & beginLoc () const
Get/set the starting location of this element.
void beginLoc (Location const &loc)
Location const & endLoc () const
Get the ending location of this element.
void endLoc (Location const &loc)
std::string str () const
Helper function to output a string representing this element.
int cmask () const
Get the mask of constant types occurring within the element.
ConstantSet const * constants () const
Iterate through the list of constants occurring within the element.
ConstantSet::const_iterator beginConstants () const
ConstantSet::const_iterator endConstants () const
VariableSet const * freeVariables () const
Iterate through the list of FREE variables occurring within the element.
VariableSet::const_iterator beginFreeVariables () const
VariableSet::const_iterator endFreeVariables () const
Public Member Functions inherited from babb::utils::Referenced
Referenced ()
Referenced ()
Additional Inherited Members
Public Types inherited from bcplus::elements::detail::IdentifierElement< Element, Element::Type::MACRO, symbols::MacroSymbol, parser::Token >
typedef parser::Token Argument
Argument type aliases.
typedef ReferencedVector
< babb::utils::ref_ptr< const
Argument > >::type ArgumentList
typedef
ArgumentList::const_iterator iterator
Argument iterators.
typedef
ArgumentList::const_iterator const_iterator
Public Types inherited from bcplus::elements::Element
typedef ReferencedSet
< babb::utils::ref_ptr< const
symbols::ConstantSymbol >
>::type ConstantSet
A set oc constant symbols.
typedef ReferencedSet
< babb::utils::ref_ptr< const
symbols::VariableSymbol >
>::type VariableSet
A set of variable symbols.
Protected Member Functions inherited from bcplus::elements::detail::IdentifierElement< Element, Element::Type::MACRO, symbols::MacroSymbol, parser::Token >
ArgumentList const * args () const
The argument list.
Protected Member Functions inherited from bcplus::elements::Element
void constants (ConstantSet const *set)
setter for the set of constants
void freeVariables (VariableSet const *set)
setter for the set of free variables (for use in constructors)
Protected Member Functions inherited from babb::utils::Referenced
virtual ~Referenced ()
virtual ~Referenced ()
Static Protected Member Functions inherited from bcplus::elements::Element
static ConstantSet * newConstSet (Element const *a=NULL, Element const *b=NULL)
Initializes a new constant set as the union of the two constant sets provided.
static ConstantSet * newConstSet (symbols::Symbol const *sym)
Initializes a new constant set and adds the provided symbol if it's a constant symbol.
static ConstantSet * insertConstants (ConstantSet *dest, Element const *src=NULL)
Adds the constants from an element to the provided set.
static VariableSet * newVarSet (Element const *a=NULL, Element const *b=NULL)
Iinitializes a new variable set as the union of the two variable sets provided.
static VariableSet * newVarSet (symbols::Symbol const *sym)
Initializes a new constant set and adds the provided symbol if it's a variable symbol.
static VariableSet * insertVariables (VariableSet *dest, Element const *src=NULL)
Adds the variables from an element to the provided set.
Detailed Description
An arbitrary macro instance 'm(...)'.
Definition at line 19 of file Macro.h.
Constructor & Destructor Documentation
bcplus::elements::Macro::Macro (symbols::MacroSymbol const * symbol, ArgumentList const * args, Location const & begin = Location(NULL, 0, 0), Location const & end = Location(NULL, 0, 0), bool parens = false)
Full constructor.
Parameters
symbol The symbol entry in the symbol table.
args The argument list for this macro.
begin The beginning location of this macro
end The ending location of this macro
parens Whether the macro is surrounded by parentheses
Definition at line 12 of file Macro.cpp.
References bcplus::elements::detail::IdentifierElement< Element, Element::Type::MACRO, symbols::MacroSymbol, parser::Token >::args(), and bcplus::symbols::MacroSymbol::expand().
     : detail::IdentifierElement<Element, Element::Type::MACRO, symbols::MacroSymbol, parser::Token>(symbol, a, begin, end, parens) {
     _expansion = new ReferencedString(symbol->expand(args()));
 }
bcplus::elements::Macro::~Macro () virtual
Stub destructor.
Definition at line 19 of file Macro.cpp.
               {
     /* Intentionally left blank */
 }
Member Function Documentation
ReferencedString const* bcplus::elements::Macro::expand () const inline
Expand this macro into its final form.
Definition at line 55 of file Macro.h.
Referenced by bcplus::parser::detail::MacroParser::_handle_macro().
 { return _expansion; }
The documentation for this class was generated from the following files:
bcplusparser/include/bcplus/elements/Macro.h
bcplusparser/src/bcplus/elements/Macro.cpp