cplus2asp: VariableLikeElement Class Reference
VariableLikeElement Class Reference
Child of BaseLikeElement that represents a base element with the behavior of a variable.
#include <parser_types.h>
Public Member Functions
VariableLikeElement (std::string const &baseName, Variable const *symbolRef, bool parens=false)
Full constructor.
virtual std::ostream & translate (std::ostream &out, Context &context) const
Method that generates a translated string representation of the element with preceeding @ if a symbol is understood as a lua function call.
virtual bool hasConstants (unsigned int types, bool includeParams=true, bool includeEq=true) const
Returns true if the element (or any of its children) are constants of the provided types.
virtual bool isDefinite (bool allowComparison=false, bool allowChoice=false, bool allowAtomicNegation=false) const
Determines if the element contains a single atom, a unary expression w/ a single atom, or a conjunction thereof.
virtual bool isSingleAtom (bool allowAtomicNegation=false) const
Whether the formula is a single atom.
virtual bool hasLuaCalls (bool includeParams=true, bool includeEq=true) const
Determines if the element contains any calls to LUA.
virtual IPart determineQueryIPart () const
Determines the proper IPart to place the formula in.
virtual ParseElement * copy () const
Returns an exact copy of the parse element.
virtual bool isNumeric () const
Determines if the element ranges over numeric values.
virtual bool isBoolean () const
Determines if the element ranges over boolean values.
Sort const * domain () const
Gets the domain of the variable (or null)
bool isConstantVariable () const
Checks if a variable-like element represents a constant of some kind.
virtual ~VariableLikeElement ()
Destructor.
Public Member Functions inherited from BaseLikeElement
BaseLikeElement (ParseElementType elemType, std::string const &baseName, Element const *symbolRef, ParseElementList *params=NULL, bool parens=false)
Full constructor.
virtual bool isArithExpr () const
Determines if the element is a valid arithmetic expression.
virtual std::ostream & fullName (std::ostream &out) const
Prints the untranslated element string.
virtual void aggregateUndefined (BaseElementList &outIdentifiers)
Aggregates all of the undefined identifiers (which are assumed to be constants).
std::string const & baseName () const
Gets the base name for the element.
Element const * ref () const
Gets a reference to the global symbol which this element is an instance of.
void ref (Element const *_ref)
Sets the global symbol which this element is an instance of.
ParseElementList::const_iterator paramsBegin () const
Gets an iterator for the beginning of the parameter list.
ParseElementList::const_iterator paramsEnd () const
Gets an iterator for the end of the parameter list.
size_t arity () const
Gets the number of parameters the element has.
void detachParams ()
Clears the list of parameters without deallocating them.
virtual bool guessParamSorts (ConstSortList &outSorts)
Attempts to guess the sorts of each parameter.
virtual std::ostream & translateParams (std::ostream &out, Context &context, bool force=false) const
Internal helper to translate, creates a list of translated params.
virtual ~BaseLikeElement ()
Destructor.
Public Member Functions inherited from ParseElement
ParseElement (ParseElementType elemType, bool parens=false)
Default constructor.
bool isTrivial (bool includeParams=true, bool includeEq=true) const
Determines if the element contains no (real) constants.
std::string fullName () const
Alternative helper to fullName(std::ostream&).
ParseElementType getType () const
Gets the type of the parse element.
void parens (bool parens)
Sets whether the expression is wrapped in parentheses.
bool parens () const
Gets whether the element is encompassed in parens.
virtual ~ParseElement ()
Destructor.
Protected Member Functions
virtual std::ostream & translateAsConstant (std::ostream &out, Context &context) const
Helper translator method to handle translating the variable as an atom.
virtual std::ostream & translateAsVariable (std::ostream &out, Context &context) const
Helper translator method to handle translating the variable as a variable.
Protected Member Functions inherited from BaseLikeElement
ParseElementList::iterator paramsBegin ()
Gets an iterator for the beginning of the parameter list.
ParseElementList::iterator paramsEnd ()
Gets an iterator for the end of the parameter list.
bool hasLuaCallParameters () const
Determines if the base element has a LUA call in its parameter list.
bool hasConstantParameters (unsigned int types) const
Checks to see if there is a nested constant matching the type mask within the parameter list.
Protected Member Functions inherited from ParseElement
bool hasParens () const
Determines if the element has parentheses around it.
std::string translateBeforeParen (bool forceParens=false) const
Helper to translate that intelligently handles the value of parenBefore.
std::string translateAfterParen (bool forceParens=false) const
Helper to translate that intelligently handles the value of parenAfter.
Additional Inherited Members
Public Types inherited from ParseElement
enum ParseElementType {
PELEM_PELEM, PELEM_UOP, PELEM_BOP, PELEM_QUANT,
PELEM_BASELIKE, PELEM_CONSTLIKE, PELEM_OBJLIKE, PELEM_VARLIKE
}
The possible types of a ParseElement instance.
enum ConstMask {
MASK_ACTION = 0x01, MASK_FLUENT = 0x02, MASK_RIGID = 0x04, MASK_STATIC_AB = 0x08,
MASK_DYNAMIC_AB = 0x10, MASK_TRUE_FALSE = 0x20, MASK_SDFLUENT = 0x40, MASK_AB = MASK_STATIC_AB | MASK_DYNAMIC_AB,
MASK_NON_TRIVIAL = ~MASK_TRUE_FALSE, MASK_NON_RIGID = MASK_NON_TRIVIAL & ~MASK_RIGID, MASK_NON_AB = MASK_NON_TRIVIAL & ~MASK_AB
}
Mask values for the various kinds of constants that can be in a formula.
Static Public Member Functions inherited from ParseElement
static std::string getNewVar ()
Gets a new variable whose name is unique within the rule we're translating.
Detailed Description
Child of BaseLikeElement that represents a base element with the behavior of a variable.
Definition at line 827 of file parser_types.h.
Constructor & Destructor Documentation
VariableLikeElement::VariableLikeElement (std::string const & baseName, Variable const * symbolRef, bool parens = false) inline
Full constructor.
Parameters
baseName The base name of the element that's being instantiated (without parameters).
symbolRef A pointer to the symbol that this element is an instance of.
parens Whether to encase the element in parens.
Definition at line 836 of file parser_types.h.
Referenced by copy().
         : BaseLikeElement(PELEM_VARLIKE, baseName, symbolRef, NULL, parens)
     { /* Intentionally left blank */ }
virtual VariableLikeElement::~VariableLikeElement () inline virtual
Destructor.
Does not deallocate anything.
Definition at line 867 of file parser_types.h.
 { /* Intentionally Left Blank */ }
Member Function Documentation
virtual ParseElement* VariableLikeElement::copy () const inline virtual
Returns an exact copy of the parse element.
Implements BaseLikeElement.
Definition at line 850 of file parser_types.h.
References BaseLikeElement::baseName(), ParseElement::parens(), BaseLikeElement::ref(), and VariableLikeElement().
 { return new VariableLikeElement(baseName(), (Variable const*)ref(), parens()); }
virtual IPart VariableLikeElement::determineQueryIPart () const inline virtual
Determines the proper IPart to place the formula in.
Returns
IPART_BASE if the formula is 0:(...), IPART_VOLATILE if the formula is X:(...), and IPART_CUMULATIVE if the formula is anything else.
Implements BaseLikeElement.
Definition at line 849 of file parser_types.h.
 { return IPART_BASE; }
Sort const* VariableLikeElement::domain () const inline
Gets the domain of the variable (or null)
Definition at line 856 of file parser_types.h.
References domain(), and BaseLikeElement::ref().
Referenced by domain().
 { return (ref()) ? ((Variable const*)ref())->domain() : NULL; }
bool VariableLikeElement::hasConstants (unsigned int types, bool includeParams = true, bool includeEq = true) const virtual
Returns true if the element (or any of its children) are constants of the provided types.
Parameters
types A mask containing flags for the types to search for. See ConstMask enum.
includeParams Whether to check the parameters of constants.
includeEq Whether to check the right side of equality within an atom. (The right hand side of comparisons will be checked regardless.)
Returns
True if the element, or any elements "beneach" it, are constants, false otherwise.
Implements BaseLikeElement.
Definition at line 1280 of file parser_types.cpp.
{
     return false;
 }
virtual bool VariableLikeElement::hasLuaCalls (bool includeParams = true, bool includeEq = true) const inline virtual
Determines if the element contains any calls to LUA.
Parameters
includeParams Whether to search base element parameter lists.
includeEq Whether to check the right side of equality within an atom. (The right hand side of comparisons will be checked regardless.)
Returns
True if the element or any of its children is a LUA call.
Implements BaseLikeElement.
Definition at line 847 of file parser_types.h.
                                                                 { return false; }
virtual bool VariableLikeElement::isBoolean () const inline virtual
Determines if the element ranges over boolean values.
Returns
True if the element ranges over strictly boolean values, false otherwise.
Implements BaseLikeElement.
Definition at line 853 of file parser_types.h.
References BaseLikeElement::ref().
 { return ref() && ref()->isBoolean(); }
bool VariableLikeElement::isConstantVariable () const inline
Checks if a variable-like element represents a constant of some kind.
Returns
True if the element is a constant variable, false otherwise.
Definition at line 862 of file parser_types.h.
References isConstantVariable(), and BaseLikeElement::ref().
Referenced by isConstantVariable(), isDefinite(), and isSingleAtom().
 { return ref() && ((Variable const*)ref())->isConstantVariable(); }
virtual bool VariableLikeElement::isDefinite (bool allowComparison = false, bool allowChoice = false, bool allowAtomicNegation = false) const inline virtual
Determines if the element contains a single atom, a unary expression w/ a single atom, or a conjunction thereof.
Parameters
allowComparison Whether to allow comparison operators in the formula.
allowChoice Whether to allow choice rules in the formula.
allowAtomicNegation whether to allow -p or "not p" where p is a boolean atom.
Returns
True if the element is a definite formula.
Implements BaseLikeElement.
Definition at line 843 of file parser_types.h.
References isConstantVariable(), and BaseLikeElement::ref().
         { return ref() && isConstantVariable() && ref()->isBoolean(); }
virtual bool VariableLikeElement::isNumeric () const inline virtual
Determines if the element ranges over numeric values.
Returns
True if the element ranges over strictly numeric values.
Implements BaseLikeElement.
Definition at line 852 of file parser_types.h.
References BaseLikeElement::ref().
 { return ref() && ref()->isNumeric(); }
virtual bool VariableLikeElement::isSingleAtom (bool allowAtomicNegation = false) const inline virtual
Whether the formula is a single atom.
Returns
True if the element is a single atom c=v (or just c if c is boolean).
Parameters
allowAtomicNegation whether to allow -p or "not p" where p is a boolean atom.
Implements BaseLikeElement.
Definition at line 845 of file parser_types.h.
References isConstantVariable(), and BaseLikeElement::ref().
         { return ref() && isConstantVariable() && ref()->isBoolean(); }
std::ostream & VariableLikeElement::translate (std::ostream & out, Context & context) const virtual
Method that generates a translated string representation of the element with preceeding @ if a symbol is understood as a lua function call.
Parameters
[out] out - The output stream to write to.
context - The formula context to be used for translation.
Returns
out.
Implements BaseLikeElement.
Definition at line 1257 of file parser_types.cpp.
References translateAsConstant(), and translateAsVariable().
Referenced by SimpleUnaryOperator::translate().
{
     switch (context.getPos()) {
     case Context::POS_HEAD:
     case Context::POS_BODY:
     case Context::POS_QUERY:
         // This occurs within the scope of a formula, we need to translate it as a constant.
         translateAsConstant(out, context);
         break;
     case Context::POS_TERM:
     case Context::POS_ARITHEXPR:
     case Context::POS_INTERNAL:
     case Context::POS_MAXIMIZED_INTERNAL:
         // Occurs as a term or within an arithmetic expression, translate as a variable.
         translateAsVariable(out, context);
         break;
     }
     return out;
 }
std::ostream & VariableLikeElement::translateAsConstant (std::ostream & out, Context & context) const protected virtual
Helper translator method to handle translating the variable as an atom.
Parameters
[out] out - The output stream to write the translation to. preceeding @ if a symbol is understood as a lua function call.
context - The formula context to be used for translation. Uses constant translating conventions for the base name.
Returns
A string containing the translated form of the element.
Definition at line 1299 of file parser_types.cpp.
References BaseLikeElement::baseName(), ParseElement::fullName(), ltsyyossErr, BaseLikeElement::ref(), Translator::sanitizeVariableName(), ParseElement::translateAfterParen(), and ParseElement::translateBeforeParen().
Referenced by translate().
{
     out << translateBeforeParen();
     Constant::ConstantType type = ref() ?
             ((Variable const*)ref())->getConstantType()
             : Constant::CONST_UNKNOWN;
     if (type == Constant::CONST_UNKNOWN) {
         ltsyystartWarning();
         ltsyyossErr << "In trying to treat variable \"";
         fullName(ltsyyossErr);
         ltsyyossErr << "\" like a constant, unable to determine the type of the constant. Using default behavior.";
         ltsyyreportWarning();
     }
     // start the predicate
     out << Constant::translatePrefix(type);
     if (ref()) {
         // Use the canonical translated variable name if it's available.
         out << ref()->fullTransName();
     } else {
         // Otherwise, just wing it with this instance's information.
         out << Translator::sanitizeVariableName(baseName());
     }
     // finish up the predicate
     out << Constant::translatePostfix(type, context);
     out << translateAfterParen();
     return out;
 }
std::ostream & VariableLikeElement::translateAsVariable (std::ostream & out, Context & context) const protected virtual
Helper translator method to handle translating the variable as a variable.
Parameters
[out] out - The output stream to write the translation to. preceeding @ if a symbol is understood as a lua function call.
context - The formula context to be used for translation. Uses constant translating conventions for the base name.
Returns
A string containing the translated form of the element.
Definition at line 1284 of file parser_types.cpp.
References BaseLikeElement::baseName(), BaseLikeElement::ref(), Translator::sanitizeVariableName(), ParseElement::translateAfterParen(), and ParseElement::translateBeforeParen().
Referenced by translate().
{
     out << translateBeforeParen();
     if(ref()) {
         // Use the canonical translated variable name if it's available.
         out << ref()->fullTransName();
     } else {
         // Otherwise, just wing it with this instance's base name.
         out << Translator::sanitizeVariableName(baseName());
     }
     out << translateAfterParen();
     return out;
 }
The documentation for this class was generated from the following files:
cplus2asp.bin/old/parser_types.h
cplus2asp.bin/old/parser_types.cpp