cplus2asp: bcplus::symbols::ConstantSymbol Class Reference
bcplus::symbols::ConstantSymbol Class Reference
#include <ConstantSymbol.h>
Classes
struct Type
The different types a constant can be.
Public Member Functions
ConstantSymbol (Type::type type, ReferencedString const *base, SortSymbol const *sort, SortList const *args=NULL)
Basic constructor.
ConstantSymbol (boost::property_tree::ptree const &node, Resolver const *resolver, std::ostream *err=NULL)
Loads the object from the property tree node.
virtual ~ConstantSymbol ()
Destructor stub.
SortSymbol const * sort () const
Get the sort this symbol ranges over.
Type::type constType () const
Get the type that this constant is.
char const * constTypeString () const
Get the string for the type taht this constant is.
virtual bool operator== (Symbol const &other) const
Check to see if two symbols are equal.
virtual DomainType::type domainType () const
Determine the domain type of this symbol.
virtual void save (boost::property_tree::ptree &node) const
Outputs the symbol to the provided property tree node.
Public Member Functions inherited from bcplus::symbols::detail::BaseSymbol
BaseSymbol (Symbol::Type::type type, ReferencedString const *name, SortList const *args=NULL)
Basic constructor.
BaseSymbol (Symbol::Type::type type, boost::property_tree::ptree const &node, Resolver const *resolver, std::ostream *err=NULL)
Loads the sort from the property tree node.
virtual ~BaseSymbol ()
Destructor stub.
const_iterator begin () const
Gets an iterator for the beginning of the parameters.
const_iterator end () const
Gets an iterator for the end of the parameters.
virtual void outputDefinition (std::ostream &out) const
Public Member Functions inherited from bcplus::symbols::Symbol
Symbol (Type::type type, babb::utils::ReferencedString const *base, size_t arity)
Basic Constructor.
Symbol (Type::type type, boost::property_tree::ptree const &node, std::ostream *err=NULL)
Attempts to load the symbol from the property tree node.
virtual ~Symbol ()
Destructor stub.
Type::type type () const
Get the symbol type.
char const * typeString () const
Get the symbol type as a cstring.
size_t arity () const
Get the arity of the symbol.
babb::utils::ReferencedString
const * base () const
Get the base name of the symbol.
babb::utils::ReferencedString
const * name () const
Get the full name of the symbol.
bool good () const
Determines if the symbol has been successfully loaded.
bool match (std::string const &b, size_t a) const
Determine if this symbol matches the provided detail.
bool match (std::string const &n) const
Determine if this symbol matches the provided detail.
Referenced * metadata () const
Get/set the metadata.
template<typename T >
T * metadata () const
Referenced * metadata ()
template<typename T >
T * metadata ()
void metadata (Referenced *data)
bool operator!= (Symbol const &other) const
Public Member Functions inherited from babb::utils::Referenced
Referenced ()
Referenced ()
Additional Inherited Members
Public Types inherited from bcplus::symbols::detail::BaseSymbol
typedef ReferencedVector
< babb::utils::ref_ptr< const
SortSymbol > >::type SortList
typedef SortList::iterator iterator
typedef SortList::const_iterator const_iterator
Static Public Member Functions inherited from bcplus::symbols::Symbol
static std::string genName (std::string const &base, size_t arity=0)
Generate the symbol's name from its base and arity.
Protected Member Functions inherited from bcplus::symbols::Symbol
void good (bool l)
Set the good flag.
Protected Member Functions inherited from babb::utils::Referenced
virtual ~Referenced ()
virtual ~Referenced ()
Detailed Description
Definition at line 20 of file ConstantSymbol.h.
Constructor & Destructor Documentation
bcplus::symbols::ConstantSymbol::ConstantSymbol (Type::type type, ReferencedString const * base, SortSymbol const * sort, SortList const * args = NULL)
Basic constructor.
Parameters
type The type that this constant is
base The name of this object
sort The sort that this constant ranges over
args The sorts for each of the arguments for this object.
Definition at line 843 of file ConstantSymbol.cpp.
     : BaseSymbol(Symbol::Type::CONSTANT, base, args) , _sort(sort), _type(type) {
     // intentionally left blank
 }
bcplus::symbols::ConstantSymbol::ConstantSymbol (boost::property_tree::ptree const & node, Resolver const * resolver, std::ostream * err = NULL)
Loads the object from the property tree node.
Parameters
node The node to load the symbol from
err An error strem to write to (or NULL) Sets the symbol's good flag if it was successful
Definition at line 848 of file ConstantSymbol.cpp.
References bcplus::symbols::ConstantSymbol::Type::ERR_UNKNOWN, bcplus::symbols::Symbol::good(), bcplus::symbols::Symbol::name(), bcplus::symbols::Resolver::resolve(), bcplus::symbols::Symbol::Type::SORT, sort(), and bcplus::symbols::ConstantSymbol::Type::value().
     : BaseSymbol(Symbol::Type::CONSTANT, node, resolver, err) {
     try {
         std::string sort_name = node.get<std::string>("<xmlattr>.sort");
         SortSymbol const* sort = (SortSymbol const*)resolver->resolve(Symbol::Type::SORT, sort_name);
         if (!sort) {
             good(false);
             if (err) *err << "ERROR: An error occurred while scanning the definition of \"" << *name() << "\". \"" << sort_name << "\" is not a valid sort." << std::endl;
         } else {
             _sort = sort;
         }
     } catch (boost::property_tree::ptree_error& e) {
         good(false);
         if (err) *err << "ERROR: An error occurred while scanning the definition of \"" << *name() << "\". Expected a 'sort' attribute declaring the constant's sort." << std::endl;
     }
     try {
         std::string type_name = node.get<std::string>("<xmlattr>.type");
         Type::type t = Type::value(type_name.c_str());
         if (t == Type::ERR_UNKNOWN) {
             good(false);
             if (err) *err << "ERROR: An error occurred while scanning the definition of \"" << *name() << "\". Encoutered an unknown type specifier \"" << type_name << "\"." << std::endl;
         } else _type = t;
     } catch (boost::property_tree::ptree_error& e) {
         good(false);
         if (err) *err << "ERROR: An error occurred while scanning the definition of \"" << *name() << "\". Expected a 'type' attribute declaring the constant's type." << std::endl;
     }
 }
bcplus::symbols::ConstantSymbol::~ConstantSymbol () virtual
Destructor stub.
Definition at line 888 of file ConstantSymbol.cpp.
{
     // Intentionally left blank
 }
Member Function Documentation
Type::type bcplus::symbols::ConstantSymbol::constType () const inline
Get the type that this constant is.
Definition at line 92 of file ConstantSymbol.h.
Referenced by cplus2asp::cplus2asp_bin::Translator::epilogue(), and cplus2asp::cplus2asp_bin::Translator::translate().
 { return _type; }
char const* bcplus::symbols::ConstantSymbol::constTypeString () const inline
Get the string for the type taht this constant is.
Definition at line 95 of file ConstantSymbol.h.
References bcplus::symbols::ConstantSymbol::Type::cstr().
Referenced by save().
 { return Type::cstr(_type); }
DomainType::type bcplus::symbols::ConstantSymbol::domainType () const virtual
Determine the domain type of this symbol.
Implements bcplus::symbols::detail::BaseSymbol.
Definition at line 893 of file ConstantSymbol.cpp.
{
     return _sort->domainType();
 }
bool bcplus::symbols::ConstantSymbol::operator== (Symbol const & other) const virtual
Check to see if two symbols are equal.
Parameters
other The other symbol to compare this one to
Returns
True if they are equal, false otherwise.
Reimplemented from bcplus::symbols::detail::BaseSymbol.
Reimplemented in bcplus::symbols::AttributeSymbol.
Definition at line 897 of file ConstantSymbol.cpp.
References sort().
{
     if (!BaseSymbol::operator==(other)) return false;
     ConstantSymbol const& o = (ConstantSymbol const&)other;
     // ensure the sort is the same
     if (sort() != o.sort()) return false;
     return true;
 }
void bcplus::symbols::ConstantSymbol::save (boost::property_tree::ptree & node) const virtual
Outputs the symbol to the provided property tree node.
Parameters
node The node to write to
Reimplemented from bcplus::symbols::detail::BaseSymbol.
Reimplemented in bcplus::symbols::AttributeSymbol.
Definition at line 907 of file ConstantSymbol.cpp.
References constTypeString().
Referenced by bcplus::symbols::AttributeSymbol::save().
{
     BaseSymbol::save(node);
     node.put("<xmlattr>.sort", *_sort->base());
     node.put("<xmlattr>.type", constTypeString());
 }
SortSymbol const* bcplus::symbols::ConstantSymbol::sort () const inline
Get the sort this symbol ranges over.
Definition at line 89 of file ConstantSymbol.h.
Referenced by ConstantSymbol(), cplus2asp::cplus2asp_bin::Translator::epilogue(), operator==(), and cplus2asp::cplus2asp_bin::Translator::translate().
 { return _sort; }
The documentation for this class was generated from the following files:
bcplusparser/include/bcplus/symbols/ConstantSymbol.h
bcplusparser/src/bcplus/symbols/ConstantSymbol.cpp