cplus2asp: as2transition::PredElement Class Reference
as2transition::PredElement Class Reference
Base class for predicate/object elements.
#include <PredElement.h>
Classes
struct Type
The type of element that this is...
Public Types
typedef ReferencedVector
< babb::utils::ref_ptr
< PredElement > >::type ElementList
typedef ElementList::iterator iterator
typedef ElementList::const_iterator const_iterator
Public Member Functions
PredElement (Type::type type, ReferencedString const *base, ElementList *args=NULL)
Basic constructor.
PredElement (Type::type type, ReferencedString const *base, PredElement *arg)
Basic constructor for unary predelement.
virtual ~PredElement ()
Basic Destructor.
ReferencedString const * base () const
Gets the base name of the element.
Type::type type () const
Gets the type of the element.
size_t arity () const
Get the number of arguments the element has.
iterator begin ()
Iterate over the arguments.
const_iterator begin () const
iterator end ()
const_iterator end () const
PredElement * get (size_t i)
Get a specific argument.
PredElement const * get (size_t i) const
PredElement * operator[] (int i)
PredElement const * operator[] (int i) const
bool operator< (PredElement const &other) const
comparison operators
bool operator> (PredElement const &other) const
bool operator== (PredElement const &other) const
bool operator!= (PredElement const &other) const
virtual PredElement * format (Config const *config) const
Reformat the element according the provided format rules.
Public Member Functions inherited from babb::utils::Referenced
Referenced ()
Referenced ()
Additional Inherited Members
Protected Member Functions inherited from babb::utils::Referenced
virtual ~Referenced ()
virtual ~Referenced ()
Detailed Description
Base class for predicate/object elements.
Definition at line 15 of file PredElement.h.
Member Typedef Documentation
typedef ElementList::const_iterator as2transition::PredElement::const_iterator
Definition at line 38 of file PredElement.h.
typedef ReferencedVector<babb::utils::ref_ptr<PredElement> >::type as2transition::PredElement::ElementList
Definition at line 36 of file PredElement.h.
typedef ElementList::iterator as2transition::PredElement::iterator
Definition at line 37 of file PredElement.h.
Constructor & Destructor Documentation
as2transition::PredElement::PredElement (Type::type type, ReferencedString const * base, ElementList * args = NULL)
Basic constructor.
Parameters
type The type of element that this is
base The base name of this element
args The arguments for this element or NULL if the element is nullary
Definition at line 20 of file PredElement.cpp.
Referenced by as2transition::Predicate::format(), format(), and as2transition::Predicate::Predicate().
     : _base(base), _args(args), _type(type) {
     if (!_args) _args = new ElementList();
 }
as2transition::PredElement::PredElement (Type::type type, ReferencedString const * base, PredElement * arg)
Basic constructor for unary predelement.
Parameters
type The type of element that this is
base The base name of this element
arg The argument for this element
Definition at line 26 of file PredElement.cpp.
     : _base(base), _type(type) {
     _args = new ElementList();
     _args->push_back(arg);
 }
as2transition::PredElement::~PredElement () virtual
Basic Destructor.
Definition at line 33 of file PredElement.cpp.
 { }
Member Function Documentation
size_t as2transition::PredElement::arity () const inline
Get the number of arguments the element has.
Definition at line 81 of file PredElement.h.
Referenced by operator!=(), operator<(), as2transition::operator<<(), operator==(), operator>(), and as2transition::Predicate::Predicate().
 { return _args->size(); }
ReferencedString const* as2transition::PredElement::base () const inline
Gets the base name of the element.
Definition at line 75 of file PredElement.h.
Referenced by format(), operator!=(), operator<(), as2transition::operator<<(), operator==(), operator>(), and as2transition::Predicate::Predicate().
 { return _base; }
iterator as2transition::PredElement::begin () inline
Iterate over the arguments.
Definition at line 85 of file PredElement.h.
Referenced by format(), and as2transition::operator<<().
 { return _args->begin(); }
const_iterator as2transition::PredElement::begin () const inline
Definition at line 86 of file PredElement.h.
 { return _args->begin(); }
iterator as2transition::PredElement::end () inline
Definition at line 87 of file PredElement.h.
Referenced by format(), and as2transition::operator<<().
 { return _args->end(); }
const_iterator as2transition::PredElement::end () const inline
Definition at line 88 of file PredElement.h.
 { return _args->end(); }
PredElement * as2transition::PredElement::format (Config const * config) const virtual
Reformat the element according the provided format rules.
Parameters
config How the element should be formatted.
Returns
The newline formatted element or NULL if the format rules specify the element should be removed
Reimplemented in as2transition::Predicate.
Definition at line 35 of file PredElement.cpp.
References base(), begin(), end(), as2transition::Config::noneAlias(), PredElement(), as2transition::Config::stripPrefix(), as2transition::Config::stripSanitization(), and type().
Referenced by as2transition::Predicate::format().
{
     u::ref_ptr<const ReferencedString> newbase = base();
     if (config->stripPrefix()) {
         // remove o_
         if (base()->find("o_") == 0) {
             newbase = new ReferencedString(base()->substr(2));
         // remove c_x_x_
         } else if (base()->find("c_") == 0) {
             size_t loc1 = base()->find("_", 2);
             if (loc1 != std::string::npos) {
                 size_t loc2 = base()->find("_", loc1+1);
                 if (loc2 != std::string::npos) {
                     newbase = new ReferencedString(base()->substr(loc2+1));
                 }
             }
         // remove e_x_x_
         } else if (base()->find("e_") == 0) {
             size_t loc1 = base()->find("_", 2);
             if (loc1 != std::string::npos) {
                 size_t loc2 = base()->find("_", loc1+1);
                 if (loc2 != std::string::npos) {
                     newbase = new ReferencedString(base()->substr(loc2+1));
                 }
             }
         }
     }
     if (config->stripSanitization()) {
         // remove "saniConst_"
         if (newbase->find("saniConst_") == 0) {
             newbase = new ReferencedString(newbase->substr(strlen("saniConst_")));
         }
         // remove "saniObj_"
         else if (newbase->find("saniObj_") == 0) {
             newbase = new ReferencedString(newbase->substr(strlen("saniObj_")));
         }
     }
     if (config->noneAlias() && *newbase == *config->noneAlias()) {
         newbase = new ReferencedString("none");
     }
     // recurse...
     u::ref_ptr<ElementList> newargs = new ElementList();
     for (const_iterator it = begin(); it != end(); it++) {
         newargs->push_back((*it)->format(config));
     }
     return new PredElement(type(), newbase, newargs);
 }
PredElement* as2transition::PredElement::get (size_t i) inline
Get a specific argument.
Definition at line 92 of file PredElement.h.
Referenced by operator!=(), operator<(), as2transition::operator<<(), operator==(), and operator>().
 { return (*_args)[i]; }
PredElement const* as2transition::PredElement::get (size_t i) const inline
Definition at line 93 of file PredElement.h.
 { return (*_args)[i]; }
bool as2transition::PredElement::operator!= (PredElement const & other) const
Definition at line 129 of file PredElement.cpp.
References arity(), base(), and get().
{
     if (*base() != *other.base()) return true;
     if (arity() != other.arity()) return true;
     for (size_t i = 0; i < arity(); i++) {
         if (*get(i) != *other.get(i)) return true;
     }
     return false;
 }
bool as2transition::PredElement::operator< (PredElement const & other) const
comparison operators
Definition at line 96 of file PredElement.cpp.
References arity(), base(), and get().
{
     if (*base() != *other.base()) return *base() < *other.base();
     if (arity() != other.arity()) return arity() < other.arity();
     for (size_t i = 0; i < arity(); i++) {
         if (*get(i) != *other.get(i)) return *get(i) < *other.get(i);
     }
     return false;
 }
bool as2transition::PredElement::operator== (PredElement const & other) const
Definition at line 118 of file PredElement.cpp.
References arity(), base(), and get().
{
     if (*base() != *other.base()) return false;
     if (arity() != other.arity()) return false;
     for (size_t i = 0; i < arity(); i++) {
         if (*get(i) != *other.get(i)) return false;
     }
     return true;
 }
bool as2transition::PredElement::operator> (PredElement const & other) const
Definition at line 106 of file PredElement.cpp.
References arity(), base(), and get().
{
     if (*base() != *other.base()) return *base() > *other.base();
     if (arity() != other.arity()) return arity() > other.arity();
     for (size_t i = 0; i < arity(); i++) {
         if (*get(i) != *other.get(i)) return *get(i) > *other.get(i);
     }
     return false;
 }
PredElement* as2transition::PredElement::operator[] (int i) inline
Definition at line 94 of file PredElement.h.
 { return (*_args)[i]; }
PredElement const* as2transition::PredElement::operator[] (int i) const inline
Definition at line 95 of file PredElement.h.
 { return (*_args)[i]; }
Type::type as2transition::PredElement::type () const inline
Gets the type of the element.
Definition at line 78 of file PredElement.h.
Referenced by format().
 { return _type; }
The documentation for this class was generated from the following files:
as2transition/include/as2transition/PredElement.h
as2transition/src/as2transition/PredElement.cpp