cplus2asp: ObjectLikeElement Class Reference
ObjectLikeElement Class Reference
Child of BaseLikeElement that represents a base element with the behavior of an object.
#include <parser_types.h>
Public Member Functions
ObjectLikeElement (std::string const &baseName, Object const *symbolRef, ParseElementList *params=NULL, bool parens=false)
Full constructor.
virtual std::ostream & translate (std::ostream &out, Context &context) const
Method that generates a translated string representation of the element with preceeding @ if a symbol is understood as a lua function call.
virtual bool hasConstants (unsigned int types, bool includeParams=true, bool includeEq=true) const
Returns true if the element (or any of its children) are constants of the provided types.
virtual bool isDefinite (bool allowComparison=false, bool allowChoice=false, bool allowAtomicNegation=false) const
Determines if the element contains a single atom, a unary expression w/ a single atom, or a conjunction thereof.
virtual bool isSingleAtom (bool allowAtomicNegation=false) const
Whether the formula is a single atom.
virtual bool hasLuaCalls (bool includeParams=true, bool includeEq=true) const
Determines if the element contains any calls to LUA.
virtual IPart determineQueryIPart () const
Determines the proper IPart to place the formula in.
virtual ParseElement * copy () const
Returns an exact copy of the parse element.
virtual bool isNumeric () const
Determines if the element ranges over numeric values.
virtual bool isBoolean () const
Determines if the element ranges over boolean values.
virtual ~ObjectLikeElement ()
Destructor.
Public Member Functions inherited from BaseLikeElement
BaseLikeElement (ParseElementType elemType, std::string const &baseName, Element const *symbolRef, ParseElementList *params=NULL, bool parens=false)
Full constructor.
virtual bool isArithExpr () const
Determines if the element is a valid arithmetic expression.
virtual std::ostream & fullName (std::ostream &out) const
Prints the untranslated element string.
virtual void aggregateUndefined (BaseElementList &outIdentifiers)
Aggregates all of the undefined identifiers (which are assumed to be constants).
std::string const & baseName () const
Gets the base name for the element.
Element const * ref () const
Gets a reference to the global symbol which this element is an instance of.
void ref (Element const *_ref)
Sets the global symbol which this element is an instance of.
ParseElementList::const_iterator paramsBegin () const
Gets an iterator for the beginning of the parameter list.
ParseElementList::const_iterator paramsEnd () const
Gets an iterator for the end of the parameter list.
size_t arity () const
Gets the number of parameters the element has.
void detachParams ()
Clears the list of parameters without deallocating them.
virtual bool guessParamSorts (ConstSortList &outSorts)
Attempts to guess the sorts of each parameter.
virtual std::ostream & translateParams (std::ostream &out, Context &context, bool force=false) const
Internal helper to translate, creates a list of translated params.
virtual ~BaseLikeElement ()
Destructor.
Public Member Functions inherited from ParseElement
ParseElement (ParseElementType elemType, bool parens=false)
Default constructor.
bool isTrivial (bool includeParams=true, bool includeEq=true) const
Determines if the element contains no (real) constants.
std::string fullName () const
Alternative helper to fullName(std::ostream&).
ParseElementType getType () const
Gets the type of the parse element.
void parens (bool parens)
Sets whether the expression is wrapped in parentheses.
bool parens () const
Gets whether the element is encompassed in parens.
virtual ~ParseElement ()
Destructor.
Additional Inherited Members
Public Types inherited from ParseElement
enum ParseElementType {
PELEM_PELEM, PELEM_UOP, PELEM_BOP, PELEM_QUANT,
PELEM_BASELIKE, PELEM_CONSTLIKE, PELEM_OBJLIKE, PELEM_VARLIKE
}
The possible types of a ParseElement instance.
enum ConstMask {
MASK_ACTION = 0x01, MASK_FLUENT = 0x02, MASK_RIGID = 0x04, MASK_STATIC_AB = 0x08,
MASK_DYNAMIC_AB = 0x10, MASK_TRUE_FALSE = 0x20, MASK_SDFLUENT = 0x40, MASK_AB = MASK_STATIC_AB | MASK_DYNAMIC_AB,
MASK_NON_TRIVIAL = ~MASK_TRUE_FALSE, MASK_NON_RIGID = MASK_NON_TRIVIAL & ~MASK_RIGID, MASK_NON_AB = MASK_NON_TRIVIAL & ~MASK_AB
}
Mask values for the various kinds of constants that can be in a formula.
Static Public Member Functions inherited from ParseElement
static std::string getNewVar ()
Gets a new variable whose name is unique within the rule we're translating.
Protected Member Functions inherited from BaseLikeElement
ParseElementList::iterator paramsBegin ()
Gets an iterator for the beginning of the parameter list.
ParseElementList::iterator paramsEnd ()
Gets an iterator for the end of the parameter list.
bool hasLuaCallParameters () const
Determines if the base element has a LUA call in its parameter list.
bool hasConstantParameters (unsigned int types) const
Checks to see if there is a nested constant matching the type mask within the parameter list.
Protected Member Functions inherited from ParseElement
bool hasParens () const
Determines if the element has parentheses around it.
std::string translateBeforeParen (bool forceParens=false) const
Helper to translate that intelligently handles the value of parenBefore.
std::string translateAfterParen (bool forceParens=false) const
Helper to translate that intelligently handles the value of parenAfter.
Detailed Description
Child of BaseLikeElement that represents a base element with the behavior of an object.
Definition at line 786 of file parser_types.h.
Constructor & Destructor Documentation
ObjectLikeElement::ObjectLikeElement (std::string const & baseName, Object const * symbolRef, ParseElementList * params = NULL, bool parens = false) inline
Full constructor.
Parameters
baseName The base name of the element that's being instantiated (without parameters).
symbolRef A pointer to the symbol that this element is an instance of.
params The list of parameters associated with this instance. Null if there are no parameters.
parens Whether to encase the element in parens.
Definition at line 797 of file parser_types.h.
Referenced by copy().
         : BaseLikeElement(PELEM_OBJLIKE, baseName, symbolRef, params, parens)
     { /* Intentionally left blank */ }
virtual ObjectLikeElement::~ObjectLikeElement () inline virtual
Destructor.
Does not deallocate anything.
Definition at line 820 of file parser_types.h.
 { /* Intentionally Left Blank */ }
Member Function Documentation
ParseElement * ObjectLikeElement::copy () const virtual
Returns an exact copy of the parse element.
Implements BaseLikeElement.
Definition at line 1193 of file parser_types.cpp.
References BaseLikeElement::baseName(), ObjectLikeElement(), BaseLikeElement::paramsBegin(), BaseLikeElement::paramsEnd(), ParseElement::parens(), and BaseLikeElement::ref().
{
     ParseElementList params;
     for (ParseElementList::const_iterator it = paramsBegin(); it != paramsEnd(); it++) {
         params.push_back((*it)->copy());
     }
     return new ObjectLikeElement(baseName(), (Object const*)ref(), &params, parens());
 }
virtual IPart ObjectLikeElement::determineQueryIPart () const inline virtual
Determines the proper IPart to place the formula in.
Returns
IPART_BASE if the formula is 0:(...), IPART_VOLATILE if the formula is X:(...), and IPART_CUMULATIVE if the formula is anything else.
Implements BaseLikeElement.
Definition at line 811 of file parser_types.h.
 { return IPART_BASE; }
bool ObjectLikeElement::hasConstants (unsigned int types, bool includeParams = true, bool includeEq = true) const virtual
Returns true if the element (or any of its children) are constants of the provided types.
Parameters
types A mask containing flags for the types to search for. See ConstMask enum.
includeParams Whether to check the parameters of constants.
includeEq Whether to check the right side of equality within an atom. (The right hand side of comparisons will be checked regardless.)
Returns
True if the element, or any elements "beneach" it, are constants, false otherwise.
Implements BaseLikeElement.
Definition at line 1235 of file parser_types.cpp.
References BaseLikeElement::arity(), BaseLikeElement::baseName(), BaseLikeElement::hasConstantParameters(), and ParseElement::MASK_TRUE_FALSE.
{
     return ((types & MASK_TRUE_FALSE) && arity() == 0 && (baseName() == "true" || baseName() == "false"))
         ||  (includeParams && hasConstantParameters(types));
 }
virtual bool ObjectLikeElement::hasLuaCalls (bool includeParams = true, bool includeEq = true) const inline virtual
Determines if the element contains any calls to LUA.
Parameters
includeParams Whether to search base element parameter lists.
includeEq Whether to check the right side of equality within an atom. (The right hand side of comparisons will be checked regardless.)
Returns
True if the element or any of its children is a LUA call.
Implements BaseLikeElement.
Definition at line 809 of file parser_types.h.
References BaseLikeElement::hasLuaCallParameters(), and BaseLikeElement::ref().
                                                         { return (ref() && ((Object const*)ref())->isLua()) || (includeParams && hasLuaCallParameters()); }
virtual bool ObjectLikeElement::isBoolean () const inline virtual
Determines if the element ranges over boolean values.
Returns
True if the element ranges over strictly boolean values, false otherwise.
Implements BaseLikeElement.
Definition at line 815 of file parser_types.h.
References BaseLikeElement::baseName(), isBoolean(), and BaseLikeElement::ref().
Referenced by isBoolean().
 { return (ref() && ref()->isBoolean() ) || baseName() == "true" || baseName() == "false"; }
virtual bool ObjectLikeElement::isDefinite (bool allowComparison = false, bool allowChoice = false, bool allowAtomicNegation = false) const inline virtual
Determines if the element contains a single atom, a unary expression w/ a single atom, or a conjunction thereof.
Parameters
allowComparison Whether to allow comparison operators in the formula.
allowChoice Whether to allow choice rules in the formula.
allowAtomicNegation whether to allow -p or "not p" where p is a boolean atom.
Returns
True if the element is a definite formula.
Implements BaseLikeElement.
Definition at line 805 of file parser_types.h.
References BaseLikeElement::baseName().
         { return baseName() == "true" || baseName() == "false"; }
bool ObjectLikeElement::isNumeric () const virtual
Determines if the element ranges over numeric values.
Returns
True if the element ranges over strictly numeric values.
Implements BaseLikeElement.
Definition at line 1241 of file parser_types.cpp.
References utils::from_string(), ParseElement::fullName(), and BaseLikeElement::ref().
{
     // This is only the case if the object is numeric.
     int tmp;
     std::stringstream fullname;
     fullName(fullname);
     return (ref() && ref()->isNumeric())
             || (!ref() && utils::from_string(tmp,fullname.str()));
 }
virtual bool ObjectLikeElement::isSingleAtom (bool allowAtomicNegation = false) const inline virtual
Whether the formula is a single atom.
Returns
True if the element is a single atom c=v (or just c if c is boolean).
Parameters
allowAtomicNegation whether to allow -p or "not p" where p is a boolean atom.
Implements BaseLikeElement.
Definition at line 807 of file parser_types.h.
         { return false; }
std::ostream & ObjectLikeElement::translate (std::ostream & out, Context & context) const virtual
Method that generates a translated string representation of the element with preceeding @ if a symbol is understood as a lua function call.
Parameters
[out] out - The output stream to write to.
context - The formula context to be used for translation.
Returns
out.
Implements BaseLikeElement.
Definition at line 1204 of file parser_types.cpp.
References BaseLikeElement::baseName(), BaseLikeElement::ref(), Translator::sanitizeObjectName(), and BaseLikeElement::translateParams().
Referenced by Translator::handleLUACall().
 {
 //  out << translateBeforeParen();
     if(ref())
     {   // Use the canonical translated object name if it's available.
         if(((Object const*)ref())->isLua()) out << "#spatom{";//need to make f2lp pass this through to ASP
         out << ref()->baseTransName();
     }
     else
     {   // Otherwise, just wing it with this instance's base name.
         out << Translator::sanitizeObjectName(baseName());
     }
     translateParams(out, context, ((Object const*)ref())->isLua());
 //  out << translateAfterParen();
     if(((Object const*)ref())->isLua()) {
             out << "}";
             if (context.getPos() != Context::POS_ARITHEXPR
                     && context.getPos() != Context::POS_TERM
                     && context.getPos() != Context::POS_MAXIMIZED_INTERNAL)
                 out << " == 1";
     }
     return out;
 }
The documentation for this class was generated from the following files:
cplus2asp.bin/old/parser_types.h
cplus2asp.bin/old/parser_types.cpp