cplus2asp: cplus2asp::cplus2asp_bin::Configuration Class Reference
cplus2asp::cplus2asp_bin::Configuration Class Reference
#include <Configuration.h>
Classes
struct Input
struct Option
struct Output
struct Status
struct TS
The different time step classes.
Public Types
typedef ReferencedList
< babb::utils::ref_ptr< const
ReferencedPath > >::type FileList
typedef FileList::iterator iterator
typedef FileList::const_iterator const_iterator
typedef FileList::reverse_iterator reverse_iterator
typedef
FileList::const_reverse_iterator const_reverse_iterator
Public Types inherited from bcplus::Configuration
typedef std::pair
< babb::utils::ref_ptr< const
ReferencedString >
, babb::utils::ref_ptr< const
ReferencedString > > MacroDefinition
typedef ReferencedList
< MacroDefinition >::type MacroList
typedef MacroList::iterator iterator
typedef MacroList::const_iterator const_iterator
Public Member Functions
Configuration (char const *bin, char const *version)
Basic Constructor Initializes all parameters to default.
virtual ~Configuration ()
Destructor stub.
void clearOutputFile ()
Clear the current output file (defaulting to std::cout)
ReferencedPath const * outputFile () const
Get/set the output file (and associated stream), if any.
bool outputFile (ReferencedPath const *file)
std::ostream & out () const
bool outputStream (std::ostream &out)
Set the output stream to the provided stream (overrides the output file selection)
Input::type inputLanguage () const
Get/set the input language.
void inputLanguage (Input::type lang)
Output::type outputLanguage () const
Get/set the output language.
void outputLanguage (Output::type lang)
bool enforceDomain () const
Get/set whether we're enforcing contant domains.
void enforceDomain (bool enforce)
bool enforceAdditiveDomain () const
Get/set whether we're enforcing additive constant domains.
void enforceAdditiveDomain (bool enforce)
ReferencedString const * ts (TS::type ts_class) const
Get the timestamp to be used for the provided timestamp class.
void push_front (ReferencedPath const *path)
Add an input file to the beginning of the list.
void push_back (ReferencedPath const *path)
Add an input file to the end of the list.
const_iterator begin () const
Iterate over the set of input files.
iterator begin ()
const_iterator end () const
iterator end ()
const_reverse_iterator rbegin () const
reverse_iterator rbegin ()
const_reverse_iterator rend () const
reverse_iterator rend ()
virtual bool good ()
Verifies the integrity of the configuration parameters.
Public Member Functions inherited from bcplus::Configuration
Configuration (char const *bin=NULL, char const *version=NULL)
Default constructor Initializes all parameters to defaults.
ReferencedString const * version () const
Get the application version.
ReferencedString const * binaryName () const
Get the name of this executable file.
ReferencedPath const * symtabInput () const
Get/set the input file for the symbol table.
void symtabInput (ReferencedPath const *input)
ReferencedPath const * symtabOutput () const
Get/set the output file for the symbol table.
void symtabOutput (ReferencedPath const *output)
size_t verbosity () const
Get/set the application verbosity level.
void verbosity (size_t verb)
bool parseTrace () const
Determine whether we should display parser trace information.
void parseTrace (bool trace)
const_iterator begin () const
iterate over the list of command line macros
iterator begin ()
const_iterator end () const
iterator end ()
void addMacro (ReferencedString const *name, ReferencedString const *def)
Add a macro definition.
void addMacro (MacroDefinition const &m)
std::ostream & ostream (Verb::type v) const
Get the output stream for the provided verbosity level This will return a null-sink, std::cerr, or std::cout.
void error (std::string const &err, Location const *loc=NULL) const
Output a formatted error.
virtual int load (int argc, char const **argv)
Loads configuration parameters from the provided arguments list.
std::ostream & outputVersion (std::ostream &out) const
Outputs the application version information.
std::ostream & outputHelp (std::ostream &out) const
Outputs a help dialog to the provided output stream.
Public Member Functions inherited from babb::utils::Referenced
Referenced ()
Referenced ()
Static Public Attributes
static const
babb::utils::ref_ptr< const
ReferencedString > s_ts_zero = new ReferencedString("0")
Various timestamps.
static const
babb::utils::ref_ptr< const
ReferencedString > s_ts_static_incr = new ReferencedString("t")
"t"
static const
babb::utils::ref_ptr< const
ReferencedString > s_ts_static_static = new ReferencedString("ST")
"ST"
static const
babb::utils::ref_ptr< const
ReferencedString > s_ts_dynamic_incr = s_ts_static_incr
"t"
static const
babb::utils::ref_ptr< const
ReferencedString > s_ts_dynamic_static = new ReferencedString("AT")
"AT"
static const
babb::utils::ref_ptr< const
ReferencedString > s_ts_action_incr = new ReferencedString("t-1")
"t-1"
static const
babb::utils::ref_ptr< const
ReferencedString > s_ts_action_static = new ReferencedString("AT-1")
"AT-1"
static const
babb::utils::ref_ptr< const
ReferencedString > s_ts_maxstep_incr = s_ts_static_incr
"t"
static const
babb::utils::ref_ptr< const
ReferencedString > s_ts_maxstep_static = new ReferencedString("maxstep")
"maxstep"
Static Public Attributes inherited from bcplus::Configuration
static const size_t DEFAULT_VERB_LEVEL = Verb::STD
Default verbosity level.
Protected Member Functions
virtual std::ostream & outputOptions (std::ostream &out) const
Outputs the options for this configuration FORMAT: (dash is a space) --—<category>: -------—<option> -------—<option2> ------------—
virtual int parseOption (char const *opt, char const *opt2=NULL)
Parses the string option and performs the task specified by it.
Protected Member Functions inherited from babb::utils::Referenced
virtual ~Referenced ()
virtual ~Referenced ()
Detailed Description
Definition at line 17 of file Configuration.h.
Member Typedef Documentation
typedef FileList::const_iterator cplus2asp::cplus2asp_bin::Configuration::const_iterator
Definition at line 82 of file Configuration.h.
typedef FileList::const_reverse_iterator cplus2asp::cplus2asp_bin::Configuration::const_reverse_iterator
Definition at line 84 of file Configuration.h.
typedef ReferencedList<babb::utils::ref_ptr<const ReferencedPath> >::type cplus2asp::cplus2asp_bin::Configuration::FileList
Definition at line 80 of file Configuration.h.
typedef FileList::iterator cplus2asp::cplus2asp_bin::Configuration::iterator
Definition at line 81 of file Configuration.h.
typedef FileList::reverse_iterator cplus2asp::cplus2asp_bin::Configuration::reverse_iterator
Definition at line 83 of file Configuration.h.
Constructor & Destructor Documentation
cplus2asp::cplus2asp_bin::Configuration::Configuration (char const * bin, char const * version)
Basic Constructor Initializes all parameters to default.
Parameters
bin The name of the binary
version The system version
Definition at line 34 of file Configuration.cpp.
     : bcplus::Configuration(bin, version), _ostream(&std::cout), _input_lang(Input::CPLUS), _output_lang(Output::INCREMENTAL), _enforceDomain(true), _enforceAdditiveDomain(true) {
     /* Intentionally left blank */
 }
cplus2asp::cplus2asp_bin::Configuration::~Configuration () virtual
Destructor stub.
Reimplemented from bcplus::Configuration.
Definition at line 39 of file Configuration.cpp.
References clearOutputFile().
{
     clearOutputFile();
 }
Member Function Documentation
const_iterator cplus2asp::cplus2asp_bin::Configuration::begin () const inline
Iterate over the set of input files.
Definition at line 188 of file Configuration.h.
 { return _input_files.begin(); }
iterator cplus2asp::cplus2asp_bin::Configuration::begin () inline
Definition at line 189 of file Configuration.h.
 { return _input_files.begin(); }
void cplus2asp::cplus2asp_bin::Configuration::clearOutputFile ()
Clear the current output file (defaulting to std::cout)
Definition at line 43 of file Configuration.cpp.
Referenced by outputFile(), outputStream(), and ~Configuration().
{
     if (_output_file && _ostream && _ostream != &std::cout) {
         ((fs::ofstream*)_ostream)->close();
         delete _ostream;
     }
     _output_file = NULL;
     _ostream = &std::cout;
 }
const_iterator cplus2asp::cplus2asp_bin::Configuration::end () const inline
Definition at line 190 of file Configuration.h.
 { return _input_files.end(); }
iterator cplus2asp::cplus2asp_bin::Configuration::end () inline
Definition at line 191 of file Configuration.h.
 { return _input_files.end(); }
bool cplus2asp::cplus2asp_bin::Configuration::enforceAdditiveDomain () const inline
Get/set whether we're enforcing additive constant domains.
Definition at line 171 of file Configuration.h.
 { return _enforceAdditiveDomain; }
void cplus2asp::cplus2asp_bin::Configuration::enforceAdditiveDomain (bool enforce) inline
Definition at line 172 of file Configuration.h.
 { _enforceAdditiveDomain = enforce; }
bool cplus2asp::cplus2asp_bin::Configuration::enforceDomain () const inline
Get/set whether we're enforcing contant domains.
Definition at line 167 of file Configuration.h.
 { return _enforceDomain; }
void cplus2asp::cplus2asp_bin::Configuration::enforceDomain (bool enforce) inline
Definition at line 168 of file Configuration.h.
 { _enforceDomain = enforce; }
bool cplus2asp::cplus2asp_bin::Configuration::good () virtual
Verifies the integrity of the configuration parameters.
Returns
True if the parameters appear to be correct. False otherwise.
Reimplemented from bcplus::Configuration.
Definition at line 80 of file Configuration.cpp.
Referenced by main().
{
     return true;
 }
Input::type cplus2asp::cplus2asp_bin::Configuration::inputLanguage () const inline
Get/set the input language.
Definition at line 159 of file Configuration.h.
Referenced by cplus2asp::cplus2asp_bin::Translator::epilogue(), and main().
 { return _input_lang; }
void cplus2asp::cplus2asp_bin::Configuration::inputLanguage (Input::type lang) inline
Definition at line 160 of file Configuration.h.
 { _input_lang = lang; }
std::ostream& cplus2asp::cplus2asp_bin::Configuration::out () const inline
Definition at line 152 of file Configuration.h.
Referenced by cplus2asp::cplus2asp_bin::Translator::epilogue(), outputStream(), cplus2asp::cplus2asp_bin::Translator::prologue(), and cplus2asp::cplus2asp_bin::Translator::translate().
 { return *(const_cast<std::ostream*>(_ostream)); }
ReferencedPath const* cplus2asp::cplus2asp_bin::Configuration::outputFile () const inline
Get/set the output file (and associated stream), if any.
Definition at line 150 of file Configuration.h.
Referenced by parseOption().
 { return _output_file; }
bool cplus2asp::cplus2asp_bin::Configuration::outputFile (ReferencedPath const * file)
Definition at line 54 of file Configuration.cpp.
References clearOutputFile().
{
     if (!file) {
         clearOutputFile();
         return true;
     }
     fs::ofstream* new_out = new fs::ofstream(*file);
     if (new_out->good()) {
         clearOutputFile();
         _output_file = file;
         _ostream = new_out;
         return true;
     } else {
         delete new_out;
         return false;
     }
 }
Output::type cplus2asp::cplus2asp_bin::Configuration::outputLanguage () const inline
Get/set the output language.
Definition at line 163 of file Configuration.h.
 { return _output_lang; }
void cplus2asp::cplus2asp_bin::Configuration::outputLanguage (Output::type lang) inline
Definition at line 164 of file Configuration.h.
 { _output_lang = lang; }
std::ostream & cplus2asp::cplus2asp_bin::Configuration::outputOptions (std::ostream & out) const protected virtual
Outputs the options for this configuration FORMAT: (dash is a space) --—<category>: -------—<option> -------—<option2> ------------—
Parameters
out The output stream to write to
Returns
out.
Reimplemented from bcplus::Configuration.
Definition at line 84 of file Configuration.cpp.
References bcplus::Configuration::outputOptions().
{
     out << "     Translator Options:"                                                               << std::endl
         << "          -l=<LANGUAGE>"                                                                << std::endl
         << "          --language=<LANGUAGE>"                                                        << std::endl
         << "               - Sets the language that should be accepted to <LANGUAGE>:"              << std::endl
         << "                    <LANGUAGE>: C+, BC, BC+, MVPF [default: C+]"                        << std::endl
         << "          -m=<MODE>"                                                                    << std::endl
         << "          --mode=<MODE>"                                                                << std::endl
         << "               - Sets the compilation mode to <MODE>:"                                  << std::endl
         << "                    <MODE>:"                                                            << std::endl
         << "                         STATIC - Targets standard ASP solvers such as Clingo"          << std::endl
         << "                         INCREMENTAL - Targets incremental ASP solvers such as iClingo" << std::endl
         << "          -o=<FILE>"                                                                    << std::endl
         << "          --output-file=<FILE>"                                                         << std::endl
         << "                - Outputs the translated program to <FILE>."                            << std::endl
         << "          -d"                                                                           << std::endl
         << "          --no-domain"                                                                  << std::endl
         << "                - Suppresses domain-enforcing rules for non-additive constants in the " << std::endl
         << "                  translated file."                                                     << std::endl
         << "          -a"                                                                           << std::endl
         << "          --no-additive-domain"                                                         << std::endl
         << "                - Suppresses domain-enforcing rules for additive constants in the "     << std::endl
         << "                  translated file."                                                     << std::endl
         << std::endl;
     return bcplus::Configuration::outputOptions(out);
 }
bool cplus2asp::cplus2asp_bin::Configuration::outputStream (std::ostream & out)
Set the output stream to the provided stream (overrides the output file selection)
Definition at line 74 of file Configuration.cpp.
References clearOutputFile(), and out().
{
     clearOutputFile();
     _ostream = &out;
     return true;
 }
int cplus2asp::cplus2asp_bin::Configuration::parseOption (char const * opt, char const * op2 = NULL) protected virtual
Parses the string option and performs the task specified by it.
Parameters
opt The option string to parse.
opt2 A second option which should be provided when STAT_NEXT_ARG is returned.
Returns
A status code indicating whether or not it was a success.
Reimplemented from bcplus::Configuration.
Definition at line 122 of file Configuration.cpp.
References cplus2asp::cplus2asp_bin::Configuration::Input::BC, cplus2asp::cplus2asp_bin::Configuration::Input::BCPLUS, cplus2asp::cplus2asp_bin::Configuration::Input::CPLUS, EXTRACT_NAME, EXTRACT_NAME_VAL, cplus2asp::cplus2asp_bin::Configuration::Output::INCREMENTAL, cplus2asp::cplus2asp_bin::Configuration::Option::INPUT_MODE, cplus2asp::cplus2asp_bin::Configuration::Input::MVPF, cplus2asp::cplus2asp_bin::Configuration::Option::NO_ADD_DOMAIN_ENFORCE, cplus2asp::cplus2asp_bin::Configuration::Option::NO_DOMAIN_ENFORCE, cplus2asp::cplus2asp_bin::Configuration::Option::OUTPUT_FILE, cplus2asp::cplus2asp_bin::Configuration::Option::OUTPUT_MODE, outputFile(), bcplus::Configuration::parseOption(), cplus2asp::cplus2asp_bin::Configuration::Status::STAT_BAD_ARG, cplus2asp::cplus2asp_bin::Configuration::Status::STAT_FILE_NOT_FOUND, cplus2asp::cplus2asp_bin::Configuration::Status::STAT_OK, and cplus2asp::cplus2asp_bin::Configuration::Output::STATIC.
{
     std::string val, val2;
     char const* token = opt;
     char const* marker;
     int option = 0;
 #line 130 "<stdout>"
     {
         char yych;
         yych = *opt;
         switch (yych) {
         case '\n':  goto yy2;
         case '-':   goto yy3;
         default:    goto yy5;
         }
 yy2:
         opt = marker;
         goto yy4;
 yy3:
         yych = *(marker = ++opt);
         switch (yych) {
         case '-':   goto yy6;
         case 'a':   goto yy9;
         case 'd':   goto yy11;
         case 'l':   goto yy15;
         case 'm':   goto yy13;
         case 'o':   goto yy7;
         default:    goto yy4;
         }
 yy4:
 #line 154 "Configuration.r2c"
         {
                                         goto re2c_other; }
 #line 158 "<stdout>"
 yy5:
         yych = *++opt;
         goto yy4;
 yy6:
         yych = *++opt;
         switch (yych) {
         case 'l':   goto yy20;
         case 'm':   goto yy21;
         case 'n':   goto yy22;
         case 'o':   goto yy23;
         default:    goto yy2;
         }
 yy7:
         ++opt;
         switch ((yych = *opt)) {
         case '=':   goto yy19;
         default:    goto yy8;
         }
 yy8:
 #line 150 "Configuration.r2c"
         {
                                         EXTRACT_NAME_VAL;
                                         option = Option::OUTPUT_FILE;
                                         goto re2c_finish; }
 #line 183 "<stdout>"
 yy9:
         ++opt;
 #line 146 "Configuration.r2c"
         {
                                         EXTRACT_NAME;
                                         option = Option::NO_ADD_DOMAIN_ENFORCE;
                                         goto re2c_finish; }
 #line 191 "<stdout>"
 yy11:
         ++opt;
 #line 142 "Configuration.r2c"
         {
                                         EXTRACT_NAME;
                                         option = Option::NO_DOMAIN_ENFORCE;
                                         goto re2c_finish; }
 #line 199 "<stdout>"
 yy13:
         ++opt;
         switch ((yych = *opt)) {
         case '=':   goto yy18;
         default:    goto yy14;
         }
 yy14:
 #line 138 "Configuration.r2c"
         {
                                         EXTRACT_NAME_VAL;
                                         option = Option::OUTPUT_MODE;
                                         goto re2c_finish; }
 #line 212 "<stdout>"
 yy15:
         ++opt;
         switch ((yych = *opt)) {
         case '=':   goto yy17;
         default:    goto yy16;
         }
 yy16:
 #line 133 "Configuration.r2c"
         {
                                         EXTRACT_NAME_VAL;
                                         option = Option::INPUT_MODE;
                                         goto re2c_finish; }
 #line 225 "<stdout>"
 yy17:
         yych = *++opt;
         goto yy16;
 yy18:
         yych = *++opt;
         goto yy14;
 yy19:
         yych = *++opt;
         goto yy8;
 yy20:
         yych = *++opt;
         switch (yych) {
         case 'a':   goto yy56;
         default:    goto yy2;
         }
 yy21:
         yych = *++opt;
         switch (yych) {
         case 'o':   goto yy54;
         default:    goto yy2;
         }
 yy22:
         yych = *++opt;
         switch (yych) {
         case 'o':   goto yy33;
         default:    goto yy2;
         }
 yy23:
         yych = *++opt;
         switch (yych) {
         case 'u':   goto yy24;
         default:    goto yy2;
         }
 yy24:
         yych = *++opt;
         switch (yych) {
         case 't':   goto yy25;
         default:    goto yy2;
         }
 yy25:
         yych = *++opt;
         switch (yych) {
         case 'p':   goto yy26;
         default:    goto yy2;
         }
 yy26:
         yych = *++opt;
         switch (yych) {
         case 'u':   goto yy27;
         default:    goto yy2;
         }
 yy27:
         yych = *++opt;
         switch (yych) {
         case 't':   goto yy28;
         default:    goto yy2;
         }
 yy28:
         yych = *++opt;
         switch (yych) {
         case '-':   goto yy29;
         default:    goto yy2;
         }
 yy29:
         yych = *++opt;
         switch (yych) {
         case 'f':   goto yy30;
         default:    goto yy2;
         }
 yy30:
         yych = *++opt;
         switch (yych) {
         case 'i':   goto yy31;
         default:    goto yy2;
         }
 yy31:
         yych = *++opt;
         switch (yych) {
         case 'l':   goto yy32;
         default:    goto yy2;
         }
 yy32:
         yych = *++opt;
         switch (yych) {
         case 'e':   goto yy7;
         default:    goto yy2;
         }
 yy33:
         yych = *++opt;
         switch (yych) {
         case '-':   goto yy34;
         default:    goto yy2;
         }
 yy34:
         yych = *++opt;
         switch (yych) {
         case 'a':   goto yy35;
         case 'd':   goto yy36;
         default:    goto yy2;
         }
 yy35:
         yych = *++opt;
         switch (yych) {
         case 'd':   goto yy41;
         default:    goto yy2;
         }
 yy36:
         yych = *++opt;
         switch (yych) {
         case 'o':   goto yy37;
         default:    goto yy2;
         }
 yy37:
         yych = *++opt;
         switch (yych) {
         case 'm':   goto yy38;
         default:    goto yy2;
         }
 yy38:
         yych = *++opt;
         switch (yych) {
         case 'a':   goto yy39;
         default:    goto yy2;
         }
 yy39:
         yych = *++opt;
         switch (yych) {
         case 'i':   goto yy40;
         default:    goto yy2;
         }
 yy40:
         yych = *++opt;
         switch (yych) {
         case 'n':   goto yy11;
         default:    goto yy2;
         }
 yy41:
         yych = *++opt;
         switch (yych) {
         case 'd':   goto yy42;
         default:    goto yy2;
         }
 yy42:
         yych = *++opt;
         switch (yych) {
         case 'i':   goto yy43;
         default:    goto yy2;
         }
 yy43:
         yych = *++opt;
         switch (yych) {
         case 't':   goto yy44;
         default:    goto yy2;
         }
 yy44:
         yych = *++opt;
         switch (yych) {
         case 'i':   goto yy45;
         default:    goto yy2;
         }
 yy45:
         yych = *++opt;
         switch (yych) {
         case 'v':   goto yy46;
         default:    goto yy2;
         }
 yy46:
         yych = *++opt;
         switch (yych) {
         case 'e':   goto yy47;
         default:    goto yy2;
         }
 yy47:
         yych = *++opt;
         switch (yych) {
         case '-':   goto yy48;
         default:    goto yy2;
         }
 yy48:
         yych = *++opt;
         switch (yych) {
         case 'd':   goto yy49;
         default:    goto yy2;
         }
 yy49:
         yych = *++opt;
         switch (yych) {
         case 'o':   goto yy50;
         default:    goto yy2;
         }
 yy50:
         yych = *++opt;
         switch (yych) {
         case 'm':   goto yy51;
         default:    goto yy2;
         }
 yy51:
         yych = *++opt;
         switch (yych) {
         case 'a':   goto yy52;
         default:    goto yy2;
         }
 yy52:
         yych = *++opt;
         switch (yych) {
         case 'i':   goto yy53;
         default:    goto yy2;
         }
 yy53:
         yych = *++opt;
         switch (yych) {
         case 'n':   goto yy9;
         default:    goto yy2;
         }
 yy54:
         yych = *++opt;
         switch (yych) {
         case 'd':   goto yy55;
         default:    goto yy2;
         }
 yy55:
         yych = *++opt;
         switch (yych) {
         case 'e':   goto yy13;
         default:    goto yy2;
         }
 yy56:
         yych = *++opt;
         switch (yych) {
         case 'n':   goto yy57;
         default:    goto yy2;
         }
 yy57:
         yych = *++opt;
         switch (yych) {
         case 'g':   goto yy58;
         default:    goto yy2;
         }
 yy58:
         yych = *++opt;
         switch (yych) {
         case 'u':   goto yy59;
         default:    goto yy2;
         }
 yy59:
         yych = *++opt;
         switch (yych) {
         case 'a':   goto yy60;
         default:    goto yy2;
         }
 yy60:
         yych = *++opt;
         switch (yych) {
         case 'g':   goto yy61;
         default:    goto yy2;
         }
 yy61:
         ++opt;
         switch ((yych = *opt)) {
         case 'e':   goto yy15;
         default:    goto yy2;
         }
     }
 #line 156 "Configuration.r2c"
 re2c_other:
     // It's an unrecognized argument, try the parser arguments
     int ret;
     if ((ret = bcplus::Configuration::parseOption(token,opt2)) == Status::STAT_BAD_ARG) {
         // not recognized by the parser, assume it's an input file
         if (token[0] != '-' && boost::filesystem::is_regular_file(token)) {
             _input_files.push_back(new ReferencedPath(token));
             return Status::STAT_OK;
         } else if (token[0] != '-') {
             std::cerr << "ERROR: Could not find file \"" << token << "\"." << std::endl;
             return Status::STAT_FILE_NOT_FOUND;
         } return Status::STAT_BAD_ARG;
     } else return ret;
 re2c_finish:
     // Recognized the argument... Validate
     switch (option) {
     case Option::INPUT_MODE:
         if (boost::iequals(val2, "c+") || boost::iequals(val2, "cplus")) {
             _input_lang = Input::CPLUS;
             return Status::STAT_OK;
         } else if (boost::iequals(val2, "bc")) {
             _input_lang = Input::BC;
             return Status::STAT_OK;
         } else if (boost::iequals(val2, "bc+") || boost::iequals(val2, "bcplus")) {
             _input_lang = Input::BCPLUS;
             return Status::STAT_OK;
         } else if (boost::iequals(val2, "mvpf")) {
             _input_lang = Input::MVPF;
             return Status::STAT_OK;
         } else {
             std::cerr << "ERROR: Bad value provided for command line option. Expected \"c+\", \"bc\", \"bc+\", or \"mvpf\" for argument \"" + val + "\"." << std::endl;
             return Status::STAT_BAD_ARG;
         }
     case Option::OUTPUT_MODE:
         if (boost::iequals(val2, "static")) {
             _output_lang = Output::STATIC;
             return Status::STAT_OK;
         } else if (boost::iequals(val2, "incremental")) {
             _output_lang = Output::INCREMENTAL;
             return Status::STAT_OK;
         } else {
             std::cerr << "ERROR: Bad value provided for command line option. Expected \"incremental\" or \"static\" for argument \"" + val + "\"." << std::endl;
             return Status::STAT_BAD_ARG;
         }
     case Option::NO_DOMAIN_ENFORCE:
         _enforceDomain = false;
         return Status::STAT_OK;
     case Option::NO_ADD_DOMAIN_ENFORCE:
         _enforceAdditiveDomain = false;
         return Status::STAT_OK;
     case Option::OUTPUT_FILE:
         if (boost::filesystem::native(val2)) {
             u::ref_ptr<const ReferencedPath> file = new ReferencedPath(val2);
             if (!outputFile(file)) {
                 std::cerr << "ERROR: Could not open \"" << val2 << "\" for writing." << std::endl;
                 return Status::STAT_FILE_NOT_FOUND;
             } else return Status::STAT_OK;
         } else {
             std::cerr << "ERROR: \"" << val2 << "\" is not a valid file path." << std::endl;
             return Status::STAT_BAD_ARG;
         }
     default:
         // this shouldn't happen
         std::cerr << "ERROR: INTERNAL ERROR: Received unknown option from option parser." << std::endl;
         return Status::STAT_BAD_ARG;
     };
     return Status::STAT_OK;
 }
void cplus2asp::cplus2asp_bin::Configuration::push_back (ReferencedPath const * path) inline
Add an input file to the end of the list.
Parameters
file The input file to add
Definition at line 185 of file Configuration.h.
 { _input_files.push_back(path); }
void cplus2asp::cplus2asp_bin::Configuration::push_front (ReferencedPath const * path) inline
Add an input file to the beginning of the list.
Parameters
file The input file to add
Definition at line 181 of file Configuration.h.
 { _input_files.push_front(path); }
const_reverse_iterator cplus2asp::cplus2asp_bin::Configuration::rbegin () const inline
Definition at line 193 of file Configuration.h.
 { return _input_files.rbegin(); }
reverse_iterator cplus2asp::cplus2asp_bin::Configuration::rbegin () inline
Definition at line 194 of file Configuration.h.
 { return _input_files.rbegin(); }
const_reverse_iterator cplus2asp::cplus2asp_bin::Configuration::rend () const inline
Definition at line 195 of file Configuration.h.
 { return _input_files.rend(); }
reverse_iterator cplus2asp::cplus2asp_bin::Configuration::rend () inline
Definition at line 196 of file Configuration.h.
 { return _input_files.rend(); }
ReferencedString const * cplus2asp::cplus2asp_bin::Configuration::ts (TS::type ts_class) const
Get the timestamp to be used for the provided timestamp class.
Parameters
ts_class The timestamp class to get
Definition at line 567 of file Configuration.cpp.
References cplus2asp::cplus2asp_bin::Configuration::TS::ACTION, cplus2asp::cplus2asp_bin::Configuration::TS::DYNAMIC, cplus2asp::cplus2asp_bin::Configuration::Output::INCREMENTAL, cplus2asp::cplus2asp_bin::Configuration::Output::INCREMENTAL_NO_DECL, cplus2asp::cplus2asp_bin::Configuration::TS::MAXSTEP, s_ts_action_incr, s_ts_action_static, s_ts_dynamic_incr, s_ts_dynamic_static, s_ts_maxstep_incr, s_ts_maxstep_static, s_ts_static_incr, s_ts_static_static, s_ts_zero, cplus2asp::cplus2asp_bin::Configuration::Output::STATIC, cplus2asp::cplus2asp_bin::Configuration::TS::STATIC, and cplus2asp::cplus2asp_bin::Configuration::TS::ZERO.
Referenced by cplus2asp::cplus2asp_bin::Context::Context(), cplus2asp::cplus2asp_bin::Translator::epilogue(), and cplus2asp::cplus2asp_bin::Translator::prologue().
{
     switch (_output_lang) {
     case Output::STATIC:
         switch (ts_class) {
         case TS::STATIC:    return s_ts_static_static;
         case TS::DYNAMIC:   return s_ts_dynamic_static;
         case TS::ACTION:    return s_ts_action_static;
         case TS::MAXSTEP:   return s_ts_maxstep_static;
         case TS::ZERO:
         default:            return s_ts_zero;
         };
         break;
     case Output::INCREMENTAL:
     case Output::INCREMENTAL_NO_DECL:
     default:
         switch (ts_class) {
         case TS::STATIC:    return s_ts_static_incr;
         case TS::DYNAMIC:   return s_ts_dynamic_incr;
         case TS::ACTION:    return s_ts_action_incr;
         case TS::MAXSTEP:   return s_ts_maxstep_incr;
         case TS::ZERO:
         default:            return s_ts_zero;
         };
     };
 }
Member Data Documentation
const u::ref_ptr< const ReferencedString > cplus2asp::cplus2asp_bin::Configuration::s_ts_action_incr = new ReferencedString("t-1") static
"t-1"
Definition at line 97 of file Configuration.h.
Referenced by ts().
const u::ref_ptr< const ReferencedString > cplus2asp::cplus2asp_bin::Configuration::s_ts_action_static = new ReferencedString("AT-1") static
"AT-1"
Definition at line 98 of file Configuration.h.
Referenced by ts().
const u::ref_ptr< const ReferencedString > cplus2asp::cplus2asp_bin::Configuration::s_ts_dynamic_incr = s_ts_static_incr static
"t"
Definition at line 95 of file Configuration.h.
Referenced by ts().
const u::ref_ptr< const ReferencedString > cplus2asp::cplus2asp_bin::Configuration::s_ts_dynamic_static = new ReferencedString("AT") static
"AT"
Definition at line 96 of file Configuration.h.
Referenced by ts().
const u::ref_ptr< const ReferencedString > cplus2asp::cplus2asp_bin::Configuration::s_ts_maxstep_incr = s_ts_static_incr static
"t"
Definition at line 99 of file Configuration.h.
Referenced by ts().
const u::ref_ptr< const ReferencedString > cplus2asp::cplus2asp_bin::Configuration::s_ts_maxstep_static = new ReferencedString("maxstep") static
"maxstep"
Definition at line 100 of file Configuration.h.
Referenced by ts().
const u::ref_ptr< const ReferencedString > cplus2asp::cplus2asp_bin::Configuration::s_ts_static_incr = new ReferencedString("t") static
"t"
Definition at line 93 of file Configuration.h.
Referenced by ts().
const u::ref_ptr< const ReferencedString > cplus2asp::cplus2asp_bin::Configuration::s_ts_static_static = new ReferencedString("ST") static
"ST"
Definition at line 94 of file Configuration.h.
Referenced by ts().
const u::ref_ptr< const ReferencedString > cplus2asp::cplus2asp_bin::Configuration::s_ts_zero = new ReferencedString("0") static
Various timestamps.
"0"
Definition at line 92 of file Configuration.h.
Referenced by ts().
The documentation for this class was generated from the following files:
cplus2asp.bin/Configuration.h
cplus2asp.bin/Configuration.cpp