cplus2asp: bcplus::parser::detail::ScannerFileSource Class Reference
bcplus::parser::detail::ScannerFileSource Class Reference
A simple class to track files being worked on by the scanner.
#include <ScannerFileSource.h>
Public Member Functions
ScannerFileSource (Configuration const *config, boost::filesystem::path const &file, bool squelch=false)
virtual ~ScannerFileSource ()
Destructor.
ReferencedPath const * file () const
Gets the current file being read from.
size_t line () const
Gets the current line number.
size_t col () const
Gets the current column number.
virtual void newline ()
Callback which indicates that the scanner found a newline and the location should be updated.
virtual Location loc () const
Gets the current location of the source.
virtual Status::type status () const
Determines the status of the source.
virtual void close ()
Closes the source.
virtual void fill (size_t n)
Refills the buffer to the desired level.
Public Member Functions inherited from bcplus::parser::detail::ScannerRawSource
ScannerRawSource (Configuration const *config)
virtual ~ScannerRawSource ()
Destructor.
Configuration const * config () const
Gets the system configuration.
char const *& cursor ()
Scanner state accessors / mutators.
char const *const & cursor () const
void cursor (char const *c)
char const *& limit ()
char const *const & limit () const
void limit (char const *l)
char const *& token ()
char const *const & token () const
void token (char const *t)
char const *& marker ()
char const *const & marker () const
void marker (char const *m)
char const *& ctxmarker ()
char const *const & ctxmarker () const
void ctxmarker (char const *m)
bool good () const
Determines if the source is ready to read from.
bool eof () const
Public Member Functions inherited from bcplus::parser::detail::ScannerSource
ScannerSource (Type::type type)
Basic Constructor.
virtual ~ScannerSource ()
Destructor stub.
Type::type type () const
Get the subtype of this source.
Public Member Functions inherited from babb::utils::Referenced
Referenced ()
Referenced ()
Additional Inherited Members
Protected Member Functions inherited from babb::utils::Referenced
virtual ~Referenced ()
virtual ~Referenced ()
Detailed Description
A simple class to track files being worked on by the scanner.
Definition at line 22 of file ScannerFileSource.h.
Constructor & Destructor Documentation
bcplus::parser::detail::ScannerFileSource::ScannerFileSource (Configuration const * config, boost::filesystem::path const & file, bool squelch = false)
Parameters
config The system wide configuration information
file The file to read from
squelch Whether to silence all errors resulting from this call.
Definition at line 14 of file ScannerFileSource.cpp.
References bcplus::parser::detail::ScannerRawSource::config(), bcplus::Verb::ERROR, file(), fill(), and bcplus::Configuration::ostream().
     : ScannerRawSource(c), _buffer(NULL), _buffer_sz(0), _line(1), _newline(NULL) {
     // Ensure the file exists
     if (!squelch && (!fs::exists(file) || !fs::is_regular_file(file))) {
         config()->ostream(Verb::ERROR) << "ERROR: Cannot load input from file \"" << file.native() << "\". The file does not exist." << std::endl;
     }
     _file = new ReferencedPath();
     // try to open the new file
     _input.open(file);
     if (!squelch && !_input.good()) {
         config()->ostream(Verb::ERROR) << "ERROR: An error occurred while opening \"" << file.native() <<"\"." << std::endl;
         _input.close();
         _input.clear();
     }
     // save the detail
     *_file += file;
     fill(10);
 }
bcplus::parser::detail::ScannerFileSource::~ScannerFileSource () virtual
Destructor.
Definition at line 39 of file ScannerFileSource.cpp.
{
     if (_buffer) delete[] _buffer;
     if (_input.is_open()) _input.close();
 }
Member Function Documentation
void bcplus::parser::detail::ScannerFileSource::close () virtual
Closes the source.
Implements bcplus::parser::detail::ScannerRawSource.
Definition at line 55 of file ScannerFileSource.cpp.
{
     if (_input.is_open()) _input.close();
 }
size_t bcplus::parser::detail::ScannerFileSource::col () const inline
Gets the current column number.
Definition at line 64 of file ScannerFileSource.h.
References bcplus::parser::detail::ScannerRawSource::token().
Referenced by loc().
 { return (size_t)(token() - _newline + 1); }
ReferencedPath const* bcplus::parser::detail::ScannerFileSource::file () const inline
Gets the current file being read from.
Definition at line 58 of file ScannerFileSource.h.
Referenced by loc(), and ScannerFileSource().
 { return _file; }
void bcplus::parser::detail::ScannerFileSource::fill (size_t n) virtual
Refills the buffer to the desired level.
Parameters
n The minimum number of characters to fill.
Implements bcplus::parser::detail::ScannerRawSource.
Definition at line 67 of file ScannerFileSource.cpp.
References bcplus::parser::detail::ScannerRawSource::config(), bcplus::parser::detail::ScannerRawSource::ctxmarker(), bcplus::parser::detail::ScannerRawSource::cursor(), bcplus::Verb::ERROR, bcplus::parser::detail::ScannerRawSource::limit(), bcplus::parser::detail::ScannerRawSource::marker(), bcplus::Configuration::ostream(), and bcplus::parser::detail::ScannerRawSource::token().
Referenced by ScannerFileSource().
{
     char const* first = (token() < marker()) ? token() : marker();
     first = (first < ctxmarker() ? first : ctxmarker());
     size_t remaining = limit() - first;
     size_t req_sz = remaining + n;
     if (req_sz > _buffer_sz) {
         // oh noes. need more buffer
         size_t new_sz = req_sz*2;
         char* new_buf = new char[new_sz];
         memcpy(new_buf, first, remaining);
         delete[] _buffer;
         _buffer = new_buf;
         _buffer_sz = new_sz;
         limit() = new_buf + new_sz;
     } else {
         // we can keep the buffer and shift the contents
         memmove(_buffer, first, remaining);
     }
     size_t marker_offset = (size_t)(marker() - first);
     size_t ctxmarker_offset = (size_t)(ctxmarker() - first);
     size_t token_offset = (size_t)(token() - first);
     size_t cursor_offset = (size_t)(cursor() - first);
     size_t newline_offset = (size_t)(_newline - first);
     cursor() = _buffer + cursor_offset;
     marker() = _buffer + marker_offset;
     ctxmarker() = _buffer + ctxmarker_offset;
     token() = _buffer + token_offset;
     _newline = _buffer + newline_offset;
     // Fill the remainder of the buffer
     char* readpos = _buffer + remaining;
     int read_amount = _buffer_sz - remaining;
     _input.read(readpos, read_amount);
     // if we hit the end fill with EOF
     if (_input.gcount() < read_amount) {
         readpos += _input.gcount();
         memset(readpos, '\0', read_amount - _input.gcount());
     }
     if (_input.fail() && !_input.eof()) {
         config()->ostream(Verb::ERROR) << "ERROR: An error occurred while reading from \"" << _file->native() << "\"." << std::endl;
     }
 }
size_t bcplus::parser::detail::ScannerFileSource::line () const inline
Gets the current line number.
Definition at line 61 of file ScannerFileSource.h.
Referenced by loc().
 { return _line; }
Location bcplus::parser::detail::ScannerFileSource::loc () const virtual
Gets the current location of the source.
Implements bcplus::parser::detail::ScannerRawSource.
Definition at line 50 of file ScannerFileSource.cpp.
References col(), file(), and line().
{
     return Location(file(), line(), col());
 }
void bcplus::parser::detail::ScannerFileSource::newline () virtual
Callback which indicates that the scanner found a newline and the location should be updated.
Implements bcplus::parser::detail::ScannerRawSource.
Definition at line 45 of file ScannerFileSource.cpp.
References bcplus::parser::detail::ScannerRawSource::cursor().
{
     _line++;
     _newline = cursor();
 }
ScannerFileSource::Status::type bcplus::parser::detail::ScannerFileSource::status () const virtual
Determines the status of the source.
Implements bcplus::parser::detail::ScannerRawSource.
Definition at line 59 of file ScannerFileSource.cpp.
References bcplus::parser::detail::ScannerRawSource::Status::CLOSED, bcplus::parser::detail::ScannerRawSource::cursor(), bcplus::parser::detail::ScannerRawSource::Status::END_INPUT, bcplus::parser::detail::ScannerRawSource::Status::FAIL, and bcplus::parser::detail::ScannerRawSource::Status::OK.
{
     if (_input.good() || (_input.eof() && cursor() && *cursor())) return Status::OK;
     else if (_input.eof()) return Status::END_INPUT;
     else if (!_input.is_open()) return Status::CLOSED;
     else return Status::FAIL;
 }
The documentation for this class was generated from the following files:
bcplusparser/include/bcplus/parser/detail/ScannerFileSource.h
bcplusparser/src/bcplus/parser/detail/ScannerFileSource.cpp