cplus2asp: as2transition::parser::PredicateParser Class Reference
as2transition::parser::PredicateParser Class Reference
A parser which allows us to scan a list of predicates.
#include <PredicateParser.h>
Classes
struct Status
Container for status codes.
Public Types
typedef std::list
< babb::utils::ref_ptr
< Predicate > > PredicateList
typedef PredicateList::iterator iterator
typedef
PredicateList::const_iterator const_iterator
Public Member Functions
PredicateParser (std::istream &input, bool stopnewline)
virtual ~PredicateParser ()
Destructor.
Status::type parse ()
Attempts to parser the predicate list.
size_t size () const
Get the number of parsed predicates.
iterator begin ()
Iterate through the list of parsed predicates.
const_iterator begin () const
iterator end ()
const_iterator end () const
void _add (Predicate *pred)
INTERNAL FUNCTION Adds a freshly parsed predicate to the list.
void _parse_error (std::string const &err)
INTERNAL FUNCTION Registers a parse error.
Public Member Functions inherited from babb::utils::Referenced
Referenced ()
Referenced ()
Additional Inherited Members
Protected Member Functions inherited from babb::utils::Referenced
virtual ~Referenced ()
virtual ~Referenced ()
Detailed Description
A parser which allows us to scan a list of predicates.
Definition at line 17 of file PredicateParser.h.
Member Typedef Documentation
typedef PredicateList::const_iterator as2transition::parser::PredicateParser::const_iterator
Definition at line 34 of file PredicateParser.h.
typedef PredicateList::iterator as2transition::parser::PredicateParser::iterator
Definition at line 33 of file PredicateParser.h.
typedef std::list<babb::utils::ref_ptr<Predicate> > as2transition::parser::PredicateParser::PredicateList
Definition at line 32 of file PredicateParser.h.
Constructor & Destructor Documentation
as2transition::parser::PredicateParser::PredicateParser (std::istream & input, bool stopnewline)
Parameters
input The input stream to read from
stopnewline Whether to stop reading the stream at a newline
Definition at line 28 of file PredicateParser.cpp.
References transition_parserAlloc().
     : _stat(Status::READY) {
     _scanner = new Scanner(input, stopnewline);
     _parser = transition_parserAlloc(malloc);
 }
as2transition::parser::PredicateParser::~PredicateParser () virtual
Destructor.
Definition at line 34 of file PredicateParser.cpp.
References transition_parserFree().
{
     transition_parserFree(_parser, free);
 }
Member Function Documentation
void as2transition::parser::PredicateParser::_add (Predicate * pred) inline
INTERNAL FUNCTION Adds a freshly parsed predicate to the list.
Parameters
pred The predicate to add
Definition at line 93 of file PredicateParser.h.
{
         _predicates.push_back(pred);
     }
void as2transition::parser::PredicateParser::_parse_error (std::string const & err)
INTERNAL FUNCTION Registers a parse error.
Parameters
err The error to register
Definition at line 78 of file PredicateParser.cpp.
References as2transition::parser::PredicateParser::Status::SYNTAX_ERR.
Referenced by parse().
{
     std::cerr << "ERROR: \"" << error << "\"";
     if (_last_token.size()) std::cerr << " while parsing token \"" << _last_token << "\".";
     std::cerr << std::endl;
     _stat = Status::SYNTAX_ERR;
 }
iterator as2transition::parser::PredicateParser::begin () inline
Iterate through the list of parsed predicates.
Definition at line 80 of file PredicateParser.h.
 { return _predicates.begin(); }
const_iterator as2transition::parser::PredicateParser::begin () const inline
Definition at line 81 of file PredicateParser.h.
 { return _predicates.begin(); }
iterator as2transition::parser::PredicateParser::end () inline
Definition at line 82 of file PredicateParser.h.
 { return _predicates.end(); }
const_iterator as2transition::parser::PredicateParser::end () const inline
Definition at line 83 of file PredicateParser.h.
 { return _predicates.end(); }
PredicateParser::Status::type as2transition::parser::PredicateParser::parse ()
Attempts to parser the predicate list.
Returns
A status code indicating whether it was successful
Definition at line 39 of file PredicateParser.cpp.
References _parse_error(), as2transition::parser::PredicateParser::Status::FINISHED, as2transition::parser::PredicateParser::Status::READY, T_EOF, T_ERR_UNKNOWN_SYMBOL, T_ERR_UNTERMINATED_STRING, transition_parser(), and transition_parserAttemptReduce().
{
     ReferencedString* token;
     int tcode;
     if (_stat == Status::FINISHED) return _stat;
     // parse the list...
     do {
         tcode = _scanner->readToken(token);
         _last_token = *token;
 //      std::cout << "Got token \"" << *token << "\" of type \"" << transition_parserTokenName(tcode) << "\"." << std::endl;
         switch (tcode) {
         case T_ERR_UNTERMINATED_STRING:
             _parse_error("Unexpected end of input. Unterminated string.");
             break;
         case T_EOF:
             transition_parser(_parser, tcode, token, this);
             transition_parserAttemptReduce(_parser, this);
             _stat = Status::FINISHED;
             break;
         case T_ERR_UNKNOWN_SYMBOL:
             _parse_error("Encountered an unexpected symbol \"" + *token + "\".");
         default:
             transition_parser(_parser, tcode, token, this);
             break;
         }
     } while (_stat == Status::READY);
     return _stat;
 }
size_t as2transition::parser::PredicateParser::size () const inline
Get the number of parsed predicates.
Definition at line 77 of file PredicateParser.h.
 { return _predicates.size(); }
The documentation for this class was generated from the following files:
as2transition/include/as2transition/parser/PredicateParser.h
as2transition/src/as2transition/parser/PredicateParser.cpp