cplus2asp: bcplus::symbols::VariableSymbol Class Reference
bcplus::symbols::VariableSymbol Class Reference
#include <VariableSymbol.h>
Public Member Functions
VariableSymbol (ReferencedString const *base, SortSymbol const *sort)
Basic constructor.
VariableSymbol (boost::property_tree::ptree const &node, Resolver const *resolver, std::ostream *err=NULL)
Loads the variable from the property tree node.
virtual ~VariableSymbol ()
Destructor stub.
SortSymbol const * sort () const
Get the variable's sort.
virtual DomainType::type domainType () const
Determine the domain type of this symbol.
virtual bool operator== (Symbol const &other) const
Check to see if two symbols are equal.
virtual void save (boost::property_tree::ptree &node) const
Outputs the symbol to the provided property tree node.
virtual void outputDefinition (std::ostream &out) const
Public Member Functions inherited from bcplus::symbols::Symbol
Symbol (Type::type type, babb::utils::ReferencedString const *base, size_t arity)
Basic Constructor.
Symbol (Type::type type, boost::property_tree::ptree const &node, std::ostream *err=NULL)
Attempts to load the symbol from the property tree node.
virtual ~Symbol ()
Destructor stub.
Type::type type () const
Get the symbol type.
char const * typeString () const
Get the symbol type as a cstring.
size_t arity () const
Get the arity of the symbol.
babb::utils::ReferencedString
const * base () const
Get the base name of the symbol.
babb::utils::ReferencedString
const * name () const
Get the full name of the symbol.
bool good () const
Determines if the symbol has been successfully loaded.
bool match (std::string const &b, size_t a) const
Determine if this symbol matches the provided detail.
bool match (std::string const &n) const
Determine if this symbol matches the provided detail.
Referenced * metadata () const
Get/set the metadata.
template<typename T >
T * metadata () const
Referenced * metadata ()
template<typename T >
T * metadata ()
void metadata (Referenced *data)
bool operator!= (Symbol const &other) const
Public Member Functions inherited from babb::utils::Referenced
Referenced ()
Referenced ()
Additional Inherited Members
Static Public Member Functions inherited from bcplus::symbols::Symbol
static std::string genName (std::string const &base, size_t arity=0)
Generate the symbol's name from its base and arity.
Protected Member Functions inherited from bcplus::symbols::Symbol
void good (bool l)
Set the good flag.
Protected Member Functions inherited from babb::utils::Referenced
virtual ~Referenced ()
virtual ~Referenced ()
Detailed Description
Definition at line 19 of file VariableSymbol.h.
Constructor & Destructor Documentation
bcplus::symbols::VariableSymbol::VariableSymbol (ReferencedString const * base, SortSymbol const * sort)
Basic constructor.
Parameters
base The name of the variable
sort The sort the variable ranges over
Definition at line 12 of file VariableSymbol.cpp.
     : Symbol(Symbol::Type::VARIABLE, base, 0), _sort(sort) {
     // Intentionally left blank
 }
bcplus::symbols::VariableSymbol::VariableSymbol (boost::property_tree::ptree const & node, Resolver const * resolver, std::ostream * err = NULL)
Loads the variable from the property tree node.
Parameters
node The node to load the symbol from
err An error strem to write to (or NULL) Sets the symbol's good flag if it was successful
Definition at line 17 of file VariableSymbol.cpp.
References bcplus::symbols::Symbol::arity(), bcplus::symbols::Symbol::base(), bcplus::symbols::Symbol::good(), bcplus::symbols::Resolver::resolve(), and bcplus::symbols::Symbol::Type::SORT.
     : Symbol(Symbol::Type::VARIABLE, node, err) {
     if (good() && arity()) {
         good(false);
         if (err) *err << "ERROR: Variable \"" << *base() << "\" cannot be declared with non-zero arity." << std::endl;
     }
     std::string sortname = node.get("<xmlattr>.sort", "");
     if (sortname  == "") {
         good(false);
         if (err) *err << "ERROR: Expected a 'sort' attribute in the declaration of variable \"" << *base() << "\"." << std::endl;
     } else {
         SortSymbol const* s = (SortSymbol const*)resolver->resolve(Symbol::Type::SORT, sortname);
         if (!s) {
             good(false);
             if (err) {
                 // see if the symbol is declared elsewhere
                 if (resolver->resolve(~Symbol::Type::SORT, sortname)) {
                     *err << "ERROR: Variable \"" << *base() << "\" has invalid 'sort' attribute. \"" << sortname << "\" is not a sort." << std::endl;
                 } else {
                     *err << "ERROR: Variable \"" << *base() << "\" has invlaid 'sort' attribute. \"" << sortname << "\" has not been declared." << std::endl;
                 }
             }
         }
         _sort = s;
     }
 }
bcplus::symbols::VariableSymbol::~VariableSymbol () virtual
Destructor stub.
Definition at line 49 of file VariableSymbol.cpp.
{
     // Intentionally left blank
 }
Member Function Documentation
DomainType::type bcplus::symbols::VariableSymbol::domainType () const virtual
Determine the domain type of this symbol.
Implements bcplus::symbols::Symbol.
Definition at line 53 of file VariableSymbol.cpp.
References bcplus::symbols::SortSymbol::domainType(), and sort().
{
     return sort()->domainType();
 }
bool bcplus::symbols::VariableSymbol::operator== (Symbol const & other) const virtual
Check to see if two symbols are equal.
Parameters
other The other symbol to compare this one to
Returns
True if they are equal, false otherwise.
Reimplemented from bcplus::symbols::Symbol.
Definition at line 57 of file VariableSymbol.cpp.
References sort().
{
     if (!Symbol::operator==(other)) return false;
     VariableSymbol const& o = (VariableSymbol const&)other;
     // we draw from the same set of symbols so we can use pointer comparison
     if (sort() != o.sort()) return false;
     return true;
 }
void bcplus::symbols::VariableSymbol::outputDefinition (std::ostream & out) const virtual
Definition at line 72 of file VariableSymbol.cpp.
References bcplus::symbols::Symbol::base().
{
     out << *base();
 }
void bcplus::symbols::VariableSymbol::save (boost::property_tree::ptree & node) const virtual
Outputs the symbol to the provided property tree node.
Parameters
node The node to write to
Reimplemented from bcplus::symbols::Symbol.
Definition at line 67 of file VariableSymbol.cpp.
References bcplus::symbols::Symbol::base(), bcplus::symbols::Symbol::save(), and sort().
{
     Symbol::save(node);
     node.put("<xmlattr>.sort", *(sort()->base()));
 }
SortSymbol const* bcplus::symbols::VariableSymbol::sort () const inline
Get the variable's sort.
Definition at line 44 of file VariableSymbol.h.
Referenced by domainType(), operator==(), save(), and cplus2asp::cplus2asp_bin::Translator::translate().
 { return _sort; }
The documentation for this class was generated from the following files:
bcplusparser/include/bcplus/symbols/VariableSymbol.h
bcplusparser/src/bcplus/symbols/VariableSymbol.cpp