cplus2asp: Config Class Reference
Config Class Reference
A basic structure to hold and manage various configuration options for the cplus2asp system.
#include <Config.h>
Classes
struct FileType
A basic structure used to identify the tool and running mode associated with a file.
struct Query
A structure which is used to describe a query.
struct RunConfig
A structure used to describe the current runtime subconfiguration (used for iterative runs where the configuration can change).
Public Types
enum Toolchain {
_TC_BEGIN_ = 0x00, TC_TRANSLATOR = 0x00, TC_PREPROC = 0x01, TC_GROUNDER = 0x02,
TC_SOLVER = 0x03, TC_POSTPROC = 0x04, TC_REACTIVE_BRIDGE = 0x05, _TC_END_ = 0x06,
_TC_LENGTH_ = 0x06
}
A list of each component of the toolchain.
enum Mode {
MODE_UNKNOWN = 0x00, MODE_STATIC_AUTO = 0x01, MODE_STATIC_MANUAL = 0x02, MODE_INCREMENTAL = 0x04,
MODE_REACTIVE = 0x08
}
The various operating modes that we can use.
enum Language { LANG_CPLUS, LANG_BC, LANG_BCPLUS, LANG_MVPF }
The various languages that we support.
enum ConfigOption {
_OPT_BEGIN_ = 0x00, OPT_DISCARD_F2LP = _OPT_BEGIN_, OPT_SUPPRESS_INTERACTION, OPT_SHIFT,
OPT_STATS, OPT_NO_DOMAIN_ENFORCE, OPT_NO_ADD_DOMAIN_ENFORCE, OPT_MINSTEP,
OPT_MAXSTEP, OPT_MAXADDITIVE, OPT_NUM_SOLN, OPT_EXT_PORT,
OPT_INT_PORT, _OPT_LENGTH_, _OPT_END_ = _OPT_LENGTH_
}
The various extra configurations that can be set.
enum StrOption {
_STR_BEGIN_ = 0, _STR_TC_BEGIN_ = 0, STR_TRANSLATOR = TC_TRANSLATOR, STR_PREPROC = TC_PREPROC,
STR_GROUNDER = TC_GROUNDER, STR_SOLVER = TC_SOLVER, STR_POSTPROC = TC_POSTPROC, STR_REACTIVE_BRIDGE = TC_REACTIVE_BRIDGE,
_STR_TC_OPT_BEGIN_ = STR_REACTIVE_BRIDGE + 1, STR_OPT_TRANSLATOR = _STR_TC_OPT_BEGIN_ + TC_TRANSLATOR, STR_OPT_PREPROC = _STR_TC_OPT_BEGIN_ + TC_PREPROC, STR_OPT_GROUNDER = _STR_TC_OPT_BEGIN_ + TC_GROUNDER,
STR_OPT_SOLVER = _STR_TC_OPT_BEGIN_ + TC_SOLVER, STR_OPT_POSTPROC = _STR_TC_OPT_BEGIN_ + TC_POSTPROC, STR_OPT_REACTIVE_BRIDGE = _STR_TC_OPT_BEGIN_ + TC_REACTIVE_BRIDGE, _STR_TC_OUT_BEGIN_ = STR_OPT_REACTIVE_BRIDGE+1,
STR_OUT_TRANSLATOR = _STR_TC_OUT_BEGIN_ + TC_TRANSLATOR, STR_OUT_PREPROC = _STR_TC_OUT_BEGIN_ + TC_PREPROC, STR_OUT_GROUNDER = _STR_TC_OUT_BEGIN_ + TC_GROUNDER, STR_OUT_SOLVER = _STR_TC_OUT_BEGIN_ + TC_SOLVER,
STR_OUT_POSTPROC = _STR_TC_OUT_BEGIN_ + TC_POSTPROC, STR_OUT_REACTIVE_BRIDGE = _STR_TC_OUT_BEGIN_ + TC_REACTIVE_BRIDGE, STR_QUERY, STR_SYMTAB_FILE,
STR_NONE_ALIAS, _STR_LENGTH_
}
A list of all string options.
typedef unsigned char Modes
A flag-type used to specify multiple modes simultaneously.
typedef std::map< std::string,
Query > QueryMap
A map of queries indexed by their commands.
typedef std::map< std::string,
std::string > ConstantMap
A map between constant names and their definitions.
typedef std::vector< std::string > InputList
A list of input files.
Public Member Functions
Config (std::string const &name="")
Default Constructor.
virtual ~Config ()
Destructor Does nothing.
Mode mode () const
Basic Accessor. Does what's on the box.
bool customMode () const
Language lang () const
bool customLang () const
bool boolConfigOpt (ConfigOption opt) const
unsigned int intConfigOpt (ConfigOption opt) const
bool customConfigOpt (ConfigOption opt) const
std::string const & strOpt (StrOption opt) const
bool customStrOpt (StrOption opt) const
std::string const & command (Toolchain tool) const
bool customCmd (Toolchain tool) const
bool run (Toolchain tool) const
bool customRun (Toolchain tool) const
std::string const & opts (Toolchain tool) const
bool customOpts (Toolchain tool) const
bool isDefined (std::string const &constant) const
std::string const * def (std::string const &constant) const
size_t queryCount () const
bool hasQuery (std::string const &queryCmd) const
Query const * activeQuery () const
Query const * query (std::string const &queryCmd) const
std::string const & errFile () const
std::string const & output (Toolchain tool) const
bool customOut (Toolchain tool) const
bool mode (Mode newMode)
Basic Mutators.
bool lang (Language newLang)
bool boolConfigOpt (ConfigOption opt, bool val)
bool intConfigOpt (ConfigOption opt, unsigned int val)
bool strOpt (StrOption opt, std::string const &val)
bool def (std::string const &constant, std::string const &value)
bool command (Toolchain tool, std::string const &val)
Sets the base command for a tool.
bool run (Toolchain tool, bool val)
bool opts (Toolchain tool, std::string const &val)
bool output (Toolchain tool, std::string const &file)
Sets the target output file for the toolchain component.
bool addQuery (std::string const &name, std::string const &cmd, unsigned int maxstep=UNDEFINED, unsigned int minstep=UNDEFINED)
Attempts to add a query to the list of known queries.
bool addQuery (Query const &query)
Attempts to add a query to the list of known queries.
bool parseLang (char const *str, Language &outLang)
Parses the language represented in the string.
FileType addInput (std::string const &input)
Adds an input file to the list, determining which toolchain component it appears to belong to based on its extension.
void addInput (Toolchain tool, std::string const &input)
Adds an input file the given tool's list.
size_t cumulativeInputCount (Toolchain tool) const
Tallies the number of user inputs that will be added to the provided too.
InputList::const_iterator beginInput (Toolchain tool) const
Gets an iterator pointing to the beginning of the list of input files for a tool.
InputList::const_iterator endInput (Toolchain tool) const
Gets an iterator pointing to the end of the list of input files for a tool.
ConstantMap::const_iterator beginConstants () const
Gets an iterator pointing to the beginning of the list of constant definitions.
ConstantMap::const_iterator endConstants () const
Gets an iterator pointing to the end of the list of constant definitions.
QueryMap::const_iterator beginQueries () const
Gets an iterator pointing to the beginning of the list of query definitions.
QueryMap::const_iterator endQueries () const
Gets an iterator pointing to the beginning of the list of query definitions.
InputList::iterator beginInput (Toolchain tool)
Gets an iterator pointing to the end of the list of input files for a tool.
InputList::iterator endInput (Toolchain tool)
Gets an iterator pointing to the beginning of the list of input files for a tool.
ConstantMap::iterator beginConstants ()
Gets an iterator pointing to the beginning of the list of constant definitions.
ConstantMap::iterator endConstants ()
Gets an iterator pointing to the end of the list of constant definitions.
QueryMap::iterator beginQueries ()
Gets an iterator pointing to the beginning of the list of query definitions.
QueryMap::iterator endQueries ()
Gets an iterator pointing to the beginning of the list of query definitions.
std::string compileCommandLine (Toolchain tool, RunConfig const *subconfig=NULL) const
Compiles the command line call for a specific element in the toolchain.
void compileArgs (Toolchain tool, std::list< std::string > &arglist, RunConfig const *subconfig=NULL) const
Compiles the set of arguments used to call a specific element in the toolchain.
bool setRunTo (Toolchain tool)
Sets the toolchain to run everything up to the desired tool and nothing else.
bool setRunFrom (Toolchain tool)
Sets the toolchain to run everything from the desired tool (including the tool) and nothing else.
bool setOnlyRun (Toolchain tool)
Sets the toolchain to run only the specified tool and nothing else.
bool captureOutput (Toolchain tool)
Whether the output from the provided toolchain component should be captured and filtered.
Static Public Member Functions
static std::pair< unsigned int,
unsigned int > parseMaxstep (std::string const &maxstep)
Parses a maxstep specification in the form a single unsigned integer or an integer range d..d.
Static Public Attributes
static unsigned int const UNDEFINED = UINT_MAX
Indicates an undefined configuration setting.
static unsigned int const INF = UINT_MAX - 4
Indicates an infinite value.
Protected Member Functions
void compileInputArgs (Toolchain tool, std::list< std::string > &arglist) const
Compiles a command which aggregates all the appropriate input files for a toolchain tool into stdout.
FileType & checkExtension (char const *ext, FileType &out) const
Attempts to identify the provided extension, providing information about which tool and running mode it's associated with.
Detailed Description
A basic structure to hold and manage various configuration options for the cplus2asp system.
Definition at line 114 of file Config.h.
Member Typedef Documentation
typedef std::map<std::string,std::string> Config::ConstantMap
A map between constant names and their definitions.
Definition at line 274 of file Config.h.
typedef std::vector<std::string> Config::InputList
A list of input files.
Definition at line 275 of file Config.h.
typedef unsigned char Config::Modes
A flag-type used to specify multiple modes simultaneously.
Definition at line 223 of file Config.h.
typedef std::map<std::string, Query> Config::QueryMap
A map of queries indexed by their commands.
Definition at line 273 of file Config.h.
Member Enumeration Documentation
enum Config::ConfigOption
The various extra configurations that can be set.
Enumerator
_OPT_BEGIN_
Dummy constant to mark the beginning of the configuration list.
OPT_DISCARD_F2LP
Whether we should discard all F2LP intermediate files when we're done.
OPT_SUPPRESS_INTERACTION
Whether we should operate in silent mode.
OPT_SHIFT
Whether we should assert the '–shift' flag, which tells gringo to shift disjunction into the body of the rules.
OPT_STATS
Whether we should show solving stats.
OPT_NO_DOMAIN_ENFORCE
Whether we should suppress domain enforcing rules from being generated.
OPT_NO_ADD_DOMAIN_ENFORCE
Whether we should suppress domain enforcing rules from being generated for additive constants.
OPT_MINSTEP
The currently configured minimum step, or UNDEFINED.
OPT_MAXSTEP
The currently configured maximum step, or UNDEFINED.
OPT_MAXADDITIVE
The currently configured maximum additive, or UNDEFINED.
OPT_NUM_SOLN
The currently configured # of solutions to find.
OPT_EXT_PORT
The port that we should make available for the user.
OPT_INT_PORT
The port which we should use internally to communicate with oClingo.
_OPT_LENGTH_
Dummy constant to provide the number configuration options.
_OPT_END_
Dummy constant to mark the end of the configuration list.
Definition at line 155 of file Config.h.
     {
         _OPT_BEGIN_ = 0x00,
         // boolean
         OPT_DISCARD_F2LP = _OPT_BEGIN_,
         OPT_SUPPRESS_INTERACTION,
         OPT_SHIFT,
         OPT_STATS,
         OPT_NO_DOMAIN_ENFORCE,
         OPT_NO_ADD_DOMAIN_ENFORCE,
         // integer
         OPT_MINSTEP,
         OPT_MAXSTEP,
         OPT_MAXADDITIVE,
         OPT_NUM_SOLN,
         OPT_EXT_PORT,
         OPT_INT_PORT,
         _OPT_LENGTH_,
         _OPT_END_ = _OPT_LENGTH_
     };
enum Config::Language
The various languages that we support.
Enumerator
LANG_CPLUS
The action language C+.
LANG_BC
The action language BC.
LANG_BCPLUS
Prototype extension of BC.
LANG_MVPF
Multi-valued propositional logic formulas.
Definition at line 146 of file Config.h.
     {
         LANG_CPLUS,
         LANG_BC,
         LANG_BCPLUS,
         LANG_MVPF
     };
enum Config::Mode
The various operating modes that we can use.
Enumerator
MODE_UNKNOWN
Unknown running mode. This should only be used when specifying multiple modes.
MODE_STATIC_AUTO
Automatically advancing static translation.
MODE_STATIC_MANUAL
Manually advancing static translation.
MODE_INCREMENTAL
Incremental translation.
MODE_REACTIVE
Reactive controller mode.
Definition at line 136 of file Config.h.
     {
         MODE_UNKNOWN = 0x00,
         MODE_STATIC_AUTO = 0x01,
         MODE_STATIC_MANUAL = 0x02,
         MODE_INCREMENTAL = 0x04,
         MODE_REACTIVE = 0x08
     };
enum Config::StrOption
A list of all string options.
Enumerator
_STR_BEGIN_
psuedo option marking the beginning of the string options.
_STR_TC_BEGIN_
psuedo option marking the toolchain beginning.
STR_TRANSLATOR
translator
STR_PREPROC
pre-processor
STR_GROUNDER
grounder
STR_SOLVER
solver
STR_POSTPROC
post-processor. Ignored in reactive mode.
STR_REACTIVE_BRIDGE
The process to launch which interacts with a reactive solver.
_STR_TC_OPT_BEGIN_
psuedo string option marking the toolchain options beginning
STR_OPT_TRANSLATOR
STR_OPT_PREPROC
STR_OPT_GROUNDER
STR_OPT_SOLVER
STR_OPT_POSTPROC
STR_OPT_REACTIVE_BRIDGE
_STR_TC_OUT_BEGIN_
psuedo string option marking the toolchain output files beginning
STR_OUT_TRANSLATOR
STR_OUT_PREPROC
STR_OUT_GROUNDER
STR_OUT_SOLVER
STR_OUT_POSTPROC
STR_OUT_REACTIVE_BRIDGE
STR_QUERY
The query to run.
STR_SYMTAB_FILE
The symbol table output file.
STR_NONE_ALIAS
The value to replace none with.
_STR_LENGTH_
psuedo string option marking the end of the options list.
Definition at line 180 of file Config.h.
     {
         // Toolchain commands
         _STR_BEGIN_ = 0,
         _STR_TC_BEGIN_ = 0,
         STR_TRANSLATOR = TC_TRANSLATOR,
         STR_PREPROC = TC_PREPROC,
         STR_GROUNDER = TC_GROUNDER,
         STR_SOLVER = TC_SOLVER,
         STR_POSTPROC = TC_POSTPROC,
         STR_REACTIVE_BRIDGE = TC_REACTIVE_BRIDGE,
         // Toolchain options
         _STR_TC_OPT_BEGIN_ = STR_REACTIVE_BRIDGE + 1,
         STR_OPT_TRANSLATOR = _STR_TC_OPT_BEGIN_ + TC_TRANSLATOR,
         STR_OPT_PREPROC = _STR_TC_OPT_BEGIN_ + TC_PREPROC,
         STR_OPT_GROUNDER = _STR_TC_OPT_BEGIN_ + TC_GROUNDER,
         STR_OPT_SOLVER = _STR_TC_OPT_BEGIN_ + TC_SOLVER,
         STR_OPT_POSTPROC = _STR_TC_OPT_BEGIN_ + TC_POSTPROC,
         STR_OPT_REACTIVE_BRIDGE = _STR_TC_OPT_BEGIN_ + TC_REACTIVE_BRIDGE,
         // Toolchain output files
         _STR_TC_OUT_BEGIN_ = STR_OPT_REACTIVE_BRIDGE+1,
         STR_OUT_TRANSLATOR = _STR_TC_OUT_BEGIN_ + TC_TRANSLATOR,
         STR_OUT_PREPROC = _STR_TC_OUT_BEGIN_ + TC_PREPROC,
         STR_OUT_GROUNDER = _STR_TC_OUT_BEGIN_ + TC_GROUNDER,
         STR_OUT_SOLVER = _STR_TC_OUT_BEGIN_ + TC_SOLVER,
         STR_OUT_POSTPROC = _STR_TC_OUT_BEGIN_ + TC_POSTPROC,
         STR_OUT_REACTIVE_BRIDGE = _STR_TC_OUT_BEGIN_ + TC_REACTIVE_BRIDGE,
         // other options
         STR_QUERY,
         STR_SYMTAB_FILE,
         STR_NONE_ALIAS,
         _STR_LENGTH_
     };
enum Config::Toolchain
A list of each component of the toolchain.
Enumerator
_TC_BEGIN_
An alias for the beginning of the toolchain.
TC_TRANSLATOR
translator
TC_PREPROC
pre-processor
TC_GROUNDER
grounder
TC_SOLVER
solver
TC_POSTPROC
post-processor. Ignored in reactive mode.
TC_REACTIVE_BRIDGE
The process to launch which interacts with a reactive solver.
_TC_END_
Dummy constant to provide the end of the toolchain command list.
_TC_LENGTH_
(Not a tool) Provides the total length of the toolchain command.
Definition at line 120 of file Config.h.
     {
         _TC_BEGIN_ = 0x00,
         TC_TRANSLATOR = 0x00,
         TC_PREPROC = 0x01,
         TC_GROUNDER = 0x02,
         TC_SOLVER = 0x03,
         TC_POSTPROC = 0x04,
         TC_REACTIVE_BRIDGE = 0x05,
         _TC_END_ = 0x06,
         _TC_LENGTH_ = 0x06
     };
Constructor & Destructor Documentation
Config::Config (std::string const & name = "")
Default Constructor.
Parameters
name The name of this executable. Initializes the configuration to defaults.
Definition at line 64 of file Config.cpp.
References _OPT_LENGTH_, _STR_LENGTH_, _TC_BEGIN_, _TC_LENGTH_, command(), CONST_QUERY_NONE, CONST_QUERY_STATES, CONST_QUERY_TRANSITIONS, DEF_DISCARD_F2LP, DEF_GRD_CMD, DEF_GRD_OPTS, DEF_INTERNAL_PORT, DEF_LANG, DEF_NO_ADD_DOMAIN_ENFORCE, DEF_NO_DOMAIN_ENFORCE, DEF_NUM_SOLN, DEF_POSTPROC_CMD, DEF_POSTPROC_OPTS, DEF_PREPROC_CMD, DEF_PREPROC_OPTS, DEF_REACTIVE_BRIDGE_CMD, DEF_REACTIVE_BRIDGE_OPTS, DEF_RUNNING_MODE, DEF_SHIFT, DEF_SO_CMD, DEF_SO_OPTS, DEF_STATS, DEF_SUPPRESS_INTERACTION, DEF_TRANS_CMD, DEF_TRANS_OPTS, OPT_DISCARD_F2LP, OPT_EXT_PORT, OPT_INT_PORT, OPT_MAXADDITIVE, OPT_MAXSTEP, OPT_MINSTEP, OPT_NO_ADD_DOMAIN_ENFORCE, OPT_NO_DOMAIN_ENFORCE, OPT_NUM_SOLN, OPT_SHIFT, OPT_STATS, OPT_SUPPRESS_INTERACTION, opts(), output(), STR_NONE_ALIAS, STR_SYMTAB_FILE, strOpt(), TC_GROUNDER, TC_POSTPROC, TC_PREPROC, TC_REACTIVE_BRIDGE, TC_SOLVER, TC_TRANSLATOR, and UNDEFINED.
{
     fs::path temppath = fs::temp_directory_path();
     mErrFile = (temppath /  fs::unique_path()).native();
     mRunningMode = DEF_RUNNING_MODE;
     mCustomRunningMode = 0;
     mLang = DEF_LANG;
     mCustomLang = 0;
     strOpt(STR_NONE_ALIAS, "");
     strOpt(STR_SYMTAB_FILE, (temppath / fs::unique_path()).native());
     mConfigOpts[OPT_DISCARD_F2LP] = DEF_DISCARD_F2LP;
     mConfigOpts[OPT_SUPPRESS_INTERACTION] = DEF_SUPPRESS_INTERACTION;
     mConfigOpts[OPT_MINSTEP] = UNDEFINED;
     mConfigOpts[OPT_MAXSTEP] = UNDEFINED;
     mConfigOpts[OPT_MAXADDITIVE] = UNDEFINED;
     mConfigOpts[OPT_NUM_SOLN] = DEF_NUM_SOLN;
     mConfigOpts[OPT_EXT_PORT] = UNDEFINED;
     mConfigOpts[OPT_INT_PORT] = DEF_INTERNAL_PORT;
     mConfigOpts[OPT_SHIFT] = DEF_SHIFT;
     mConfigOpts[OPT_STATS] = DEF_STATS;
     mConfigOpts[OPT_NO_DOMAIN_ENFORCE] = DEF_NO_DOMAIN_ENFORCE;
     mConfigOpts[OPT_NO_ADD_DOMAIN_ENFORCE] = DEF_NO_ADD_DOMAIN_ENFORCE;
     memset(mCustomConfig,0,_OPT_LENGTH_);
     memset(mRun,1,_TC_LENGTH_);
     command(TC_TRANSLATOR,DEF_TRANS_CMD);
     command(TC_PREPROC,DEF_PREPROC_CMD);
     command(TC_GROUNDER,DEF_GRD_CMD);
     command(TC_SOLVER,DEF_SO_CMD);
     command(TC_POSTPROC,DEF_POSTPROC_CMD);
     command(TC_REACTIVE_BRIDGE,DEF_REACTIVE_BRIDGE_CMD);
     memset(mRun,1,_TC_LENGTH_);
     mRun[TC_GROUNDER] = false;
     memset(mCustomRun,0,_TC_LENGTH_);
     opts(TC_TRANSLATOR,DEF_TRANS_OPTS);
     opts(TC_PREPROC,DEF_PREPROC_OPTS);
     opts(TC_GROUNDER,DEF_GRD_OPTS);
     opts(TC_SOLVER,DEF_SO_OPTS);
     opts(TC_POSTPROC,DEF_POSTPROC_OPTS);
     opts(TC_REACTIVE_BRIDGE,DEF_REACTIVE_BRIDGE_OPTS);
     for (int i = (int)_TC_BEGIN_; i < (int)_TC_LENGTH_; i++) {
         output((Toolchain)i,(temppath / fs::unique_path()).native());
     }
     memset(mCustomStr,0,_STR_LENGTH_);
     // Default queries which should always be made available...
     mQueries[CONST_QUERY_TRANSITIONS] = Query("System transitions", CONST_QUERY_TRANSITIONS, 1, 1);
     mQueries[CONST_QUERY_STATES] = Query("System states", CONST_QUERY_STATES, 0, 0);
     mQueries[CONST_QUERY_NONE] = Query("Satisfiability check (no query)", CONST_QUERY_NONE, 0, 0);
 }
virtual Config::~Config () inline virtual
Destructor Does nothing.
Definition at line 331 of file Config.h.
 { /* Intentionally Left Blank */ }
Member Function Documentation
Query const* Config::activeQuery () const inline
Definition at line 388 of file Config.h.
References query(), STR_QUERY, and strOpt().
 { return query(strOpt(STR_QUERY));  }
Config::FileType Config::addInput (std::string const & input)
Adds an input file to the list, determining which toolchain component it appears to belong to based on its extension.
Parameters
input The name of the input file.
Returns
Flags indicating the input's associated tool and running mode.
Definition at line 687 of file Config.cpp.
References _TC_BEGIN_, checkExtension(), utils::debug(), Config::FileType::known, MODE_UNKNOWN, and Config::FileType::tool.
Referenced by parseCommandOptions().
{
     char const* input_cstr = input.c_str();
     FileType type(false,_TC_BEGIN_, MODE_UNKNOWN);
     utils::debug("Adding input file '%s'.", true, input.c_str());
     // Try to find the extension the file extension.
     size_t pos = input.find_last_of('.');
     if (pos == std::string::npos) {
         // No file extension to speak of, default to the beginning of the toolchain.
         mInputs[_TC_BEGIN_].push_back(input);
         return type;
     }
     // We found an extension, let's test it against known extensions
     checkExtension(&input_cstr[pos], type);
     if (type.known) {
         utils::debug("Found the extension. It belongs to toolchain component '%d'", true, type.tool);
         mInputs[type.tool].push_back(input);
     } else {
         utils::debug("Unknown extension.", true);
         // Default to the beginning of the toolchain if we don't know what it is.
         mInputs[_TC_BEGIN_].push_back(input);
     }
     return type;
 }
void Config::addInput (Toolchain tool, std::string const & input) inline
Adds an input file the given tool's list.
Parameters
tool The tool to add the input file to.
input The name of the input file.
Definition at line 483 of file Config.h.
                                                             { mInputs[tool].push_back(input); }
bool Config::addQuery (std::string const & name, std::string const & cmd, unsigned int maxstep = UNDEFINED, unsigned int minstep = UNDEFINED)
Attempts to add a query to the list of known queries.
Parameters
name The human readable name of the query.
cmd The command used to select this query.
maxstep The maxstep of the query (or UNDEFINED).
minstep The minstep of the query (or UNDEFINED).
Returns
true if the add operation was a success. False if it failed (duplicate ID).
Definition at line 660 of file Config.cpp.
References hasQuery().
Referenced by main().
{
     bool unique = true;
     // ensure that the query is not already present...
     if (hasQuery(cmd)) unique = false;
     if (unique) {
         mQueries[cmd] = Query(name,cmd,minstep,maxstep);
     }
     return unique;
 }
bool Config::addQuery (Query const & query)
Attempts to add a query to the list of known queries.
Parameters
query The query to add.
Returns
true if the add operation was a success. False if it failed (duplicate ID).
Definition at line 674 of file Config.cpp.
References Config::Query::cmd, hasQuery(), and query().
{
     bool unique = true;
     // ensure that the query is not already present...
     if (hasQuery(query.cmd)) unique = false;
     if (unique) {
         mQueries[query.cmd] = query;
     }
     return unique;
 }
ConstantMap::const_iterator Config::beginConstants () const inline
Gets an iterator pointing to the beginning of the list of constant definitions.
Returns
An iterator pointing the beginning of the constant definitions.
Definition at line 520 of file Config.h.
Referenced by compileArgs().
 { return mConstDefs.begin(); }
ConstantMap::iterator Config::beginConstants () inline
Gets an iterator pointing to the beginning of the list of constant definitions.
Returns
An iterator pointing the beginning of the constant definitions.
Definition at line 565 of file Config.h.
 { return mConstDefs.begin(); }
InputList::const_iterator Config::beginInput (Toolchain tool) const inline
Gets an iterator pointing to the beginning of the list of input files for a tool.
Note: Be aware that these are user-specified files and do not include the files belonging to previous unran tools or their intermediate output.
Parameters
tool The tool to get the iterator for.
Returns
An iterator pointing the beginning of the input list.
Definition at line 505 of file Config.h.
Referenced by compileInputArgs(), and cumulativeInputCount().
 { return mInputs[tool].begin(); }
InputList::iterator Config::beginInput (Toolchain tool) inline
Gets an iterator pointing to the end of the list of input files for a tool.
Parameters
tool The tool to get the iterator for.
Returns
An iterator pointing the end of the input list.
Definition at line 550 of file Config.h.
 { return mInputs[tool].begin(); }
QueryMap::const_iterator Config::beginQueries () const inline
Gets an iterator pointing to the beginning of the list of query definitions.
Returns
An iterator pointing the beginning of the query definitions.
Definition at line 534 of file Config.h.
Referenced by queryUserForQuery(), and showQueries().
 { return mQueries.begin(); }
QueryMap::iterator Config::beginQueries () inline
Gets an iterator pointing to the beginning of the list of query definitions.
Returns
An iterator pointing the beginning of the query definitions.
Definition at line 579 of file Config.h.
 { return mQueries.begin(); }
bool Config::boolConfigOpt (ConfigOption opt) const inline
Returns
The boolean value of the specified option.
Definition at line 356 of file Config.h.
Referenced by cleanup(), compileArgs(), main(), and parseCommandOptions().
 { return (bool)mConfigOpts[opt]; }
bool Config::boolConfigOpt (ConfigOption opt, bool val)
Returns
If the option was previously set.
Definition at line 232 of file Config.cpp.
{
     mCustomConfig[opt]++;
     if (((bool)mConfigOpts[opt]) == val) return false;
     mConfigOpts[opt] = (unsigned int)val;
     return (bool)(mCustomConfig[opt] - 1);
 }
bool Config::captureOutput (Toolchain tool)
Whether the output from the provided toolchain component should be captured and filtered.
Config::FileType & Config::checkExtension (char const * ext, FileType & out) const protected
Attempts to identify the provided extension, providing information about which tool and running mode it's associated with.
Parameters
ext The extension to attempt to identify.
[out] out Flags indicating the associated tool and running mode.
Returns
out.
Definition at line 812 of file Config.cpp.
References _TC_BEGIN_, utils::debug(), Config::FileType::known, MODE_INCREMENTAL, MODE_REACTIVE, MODE_STATIC_AUTO, MODE_STATIC_MANUAL, MODE_UNKNOWN, Config::FileType::runningMode, TC_GROUNDER, TC_POSTPROC, TC_PREPROC, TC_REACTIVE_BRIDGE, TC_SOLVER, and Config::FileType::tool.
Referenced by addInput().
{
     char const* marker;
     out.known = true;
     out.runningMode = MODE_UNKNOWN;
     out.tool = _TC_BEGIN_;
     // Skip the period if they included it.
     if (ext[0] == '.') ext++;
     utils::debug("Checking extension '%s'.", true, ext);
     /*
         "cp"                        { out.tool = TC_TRANSLATOR; out.runningMode = MODE_STATIC_AUTO | MODE_STATIC_MANUAL | MODE_INCREMENTAL; return out;}
         "cplus"                     { out.tool = TC_TRANSLATOR; out.runningMode = MODE_STATIC_AUTO | MODE_STATIC_MANUAL | MODE_INCREMENTAL; return out;}
         "c+"                        { out.tool = TC_TRANSLATOR; out.runningMode = MODE_STATIC_AUTO | MODE_STATIC_MANUAL | MODE_INCREMENTAL; return out;}
         [ao]"cp"                    { out.tool = TC_TRANSLATOR; out.runningMode = MODE_REACTIVE; return out;}
         [ao]"cplus"                 { out.tool = TC_TRANSLATOR; out.runningMode = MODE_REACTIVE; return out;}
         [ao]"c+"                    { out.tool = TC_TRANSLATOR; out.runningMode = MODE_REACTIVE; return out;}
         "icp"                       { out.tool = TC_TRANSLATOR; out.runningMode = MODE_INCREMENTAL; return out;}
         "icplus"                    { out.tool = TC_TRANSLATOR; out.runningMode = MODE_INCREMENTAL; return out;}
         "ic+"                       { out.tool = TC_TRANSLATOR; out.runningMode = MODE_INCREMENTAL; return out;}
     */
 #line 840 "<stdout>"
     {
         char yych;
         yych = *ext;
         switch (yych) {
         case '\n':  goto yy2;
         case 'a':   goto yy5;
         case 'f':   goto yy3;
         case 'g':   goto yy9;
         case 'i':   goto yy7;
         case 'l':   goto yy8;
         case 'o':   goto yy6;
         case 's':   goto yy10;
         default:    goto yy11;
         }
 yy2:
         ext = marker;
         goto yy4;
 yy3:
         yych = *(marker = ++ext);
         switch (yych) {
         case '2':   goto yy65;
         case 'o':   goto yy66;
         default:    goto yy4;
         }
 yy4:
 #line 868 "Config.r2c"
         { out.known = false; return out;}
 #line 869 "<stdout>"
 yy5:
         yych = *(marker = ++ext);
         switch (yych) {
         case 'a':   goto yy43;
         case 'f':   goto yy45;
         case 'g':   goto yy42;
         case 'l':   goto yy44;
         case 's':   goto yy61;
         default:    goto yy4;
         }
 yy6:
         yych = *(marker = ++ext);
         switch (yych) {
         case 'a':   goto yy43;
         case 'f':   goto yy45;
         case 'g':   goto yy42;
         case 'l':   goto yy44;
         default:    goto yy4;
         }
 yy7:
         yych = *(marker = ++ext);
         switch (yych) {
         case 'a':   goto yy24;
         case 'f':   goto yy26;
         case 'g':   goto yy23;
         case 'l':   goto yy25;
         default:    goto yy4;
         }
 yy8:
         yych = *++ext;
         switch (yych) {
         case 'p':   goto yy21;
         default:    goto yy4;
         }
 yy9:
         yych = *(marker = ++ext);
         switch (yych) {
         case 'r':   goto yy18;
         default:    goto yy4;
         }
 yy10:
         yych = *(marker = ++ext);
         switch (yych) {
         case 'y':   goto yy12;
         default:    goto yy4;
         }
 yy11:
         yych = *++ext;
         goto yy4;
 yy12:
         yych = *++ext;
         switch (yych) {
         case 'm':   goto yy13;
         default:    goto yy2;
         }
 yy13:
         yych = *++ext;
         switch (yych) {
         case 't':   goto yy14;
         default:    goto yy2;
         }
 yy14:
         yych = *++ext;
         switch (yych) {
         case 'a':   goto yy15;
         default:    goto yy2;
         }
 yy15:
         yych = *++ext;
         switch (yych) {
         case 'b':   goto yy16;
         default:    goto yy2;
         }
 yy16:
         ++ext;
 #line 866 "Config.r2c"
         { out.tool = TC_REACTIVE_BRIDGE; out.runningMode = MODE_REACTIVE; return out;}
 #line 947 "<stdout>"
 yy18:
         yych = *++ext;
         switch (yych) {
         case 'd':   goto yy19;
         default:    goto yy2;
         }
 yy19:
         ++ext;
 #line 860 "Config.r2c"
         { out.tool = TC_SOLVER; out.runningMode = MODE_STATIC_AUTO | MODE_STATIC_MANUAL; return out;}
 #line 958 "<stdout>"
 yy21:
         ++ext;
 #line 852 "Config.r2c"
         { out.tool = TC_GROUNDER; out.runningMode = MODE_STATIC_AUTO | MODE_STATIC_MANUAL; return out;}
 #line 963 "<stdout>"
 yy23:
         yych = *++ext;
         switch (yych) {
         case 'r':   goto yy39;
         default:    goto yy2;
         }
 yy24:
         yych = *++ext;
         switch (yych) {
         case 's':   goto yy36;
         default:    goto yy2;
         }
 yy25:
         yych = *++ext;
         switch (yych) {
         case 'p':   goto yy34;
         default:    goto yy2;
         }
 yy26:
         yych = *++ext;
         switch (yych) {
         case '2':   goto yy28;
         case 'o':   goto yy27;
         default:    goto yy2;
         }
 yy27:
         yych = *++ext;
         switch (yych) {
         case 'f':   goto yy32;
         default:    goto yy2;
         }
 yy28:
         yych = *++ext;
         switch (yych) {
         case 'l':   goto yy29;
         default:    goto yy2;
         }
 yy29:
         yych = *++ext;
         switch (yych) {
         case 'p':   goto yy30;
         default:    goto yy2;
         }
 yy30:
         ++ext;
 #line 850 "Config.r2c"
         { out.tool = TC_PREPROC; out.runningMode = MODE_INCREMENTAL; return out;}
 #line 1011 "<stdout>"
 yy32:
         ++ext;
 #line 846 "Config.r2c"
         { out.tool = TC_PREPROC; out.runningMode = MODE_INCREMENTAL; return out;}
 #line 1016 "<stdout>"
 yy34:
         ++ext;
 #line 854 "Config.r2c"
         { out.tool = TC_GROUNDER; out.runningMode = MODE_INCREMENTAL; return out;}
 #line 1021 "<stdout>"
 yy36:
         yych = *++ext;
         switch (yych) {
         case 'p':   goto yy37;
         default:    goto yy2;
         }
 yy37:
         ++ext;
 #line 858 "Config.r2c"
         { out.tool = TC_GROUNDER; out.runningMode = MODE_INCREMENTAL; return out;}
 #line 1032 "<stdout>"
 yy39:
         yych = *++ext;
         switch (yych) {
         case 'd':   goto yy40;
         default:    goto yy2;
         }
 yy40:
         ++ext;
 #line 862 "Config.r2c"
         { out.tool = TC_SOLVER; out.runningMode = MODE_INCREMENTAL; return out;}
 #line 1043 "<stdout>"
 yy42:
         yych = *++ext;
         switch (yych) {
         case 'r':   goto yy58;
         default:    goto yy2;
         }
 yy43:
         yych = *++ext;
         switch (yych) {
         case 's':   goto yy55;
         default:    goto yy2;
         }
 yy44:
         yych = *++ext;
         switch (yych) {
         case 'p':   goto yy53;
         default:    goto yy2;
         }
 yy45:
         yych = *++ext;
         switch (yych) {
         case '2':   goto yy47;
         case 'o':   goto yy46;
         default:    goto yy2;
         }
 yy46:
         yych = *++ext;
         switch (yych) {
         case 'f':   goto yy51;
         default:    goto yy2;
         }
 yy47:
         yych = *++ext;
         switch (yych) {
         case 'l':   goto yy48;
         default:    goto yy2;
         }
 yy48:
         yych = *++ext;
         switch (yych) {
         case 'p':   goto yy49;
         default:    goto yy2;
         }
 yy49:
         ++ext;
 #line 849 "Config.r2c"
         { out.tool = TC_PREPROC; out.runningMode = MODE_REACTIVE; return out;}
 #line 1091 "<stdout>"
 yy51:
         ++ext;
 #line 845 "Config.r2c"
         { out.tool = TC_PREPROC; out.runningMode = MODE_REACTIVE; return out; }
 #line 1096 "<stdout>"
 yy53:
         ++ext;
 #line 853 "Config.r2c"
         { out.tool = TC_GROUNDER; out.runningMode = MODE_REACTIVE; return out;}
 #line 1101 "<stdout>"
 yy55:
         yych = *++ext;
         switch (yych) {
         case 'p':   goto yy56;
         default:    goto yy2;
         }
 yy56:
         ++ext;
 #line 857 "Config.r2c"
         { out.tool = TC_GROUNDER; out.runningMode = MODE_REACTIVE; return out;}
 #line 1112 "<stdout>"
 yy58:
         yych = *++ext;
         switch (yych) {
         case 'd':   goto yy59;
         default:    goto yy2;
         }
 yy59:
         ++ext;
 #line 861 "Config.r2c"
         { out.tool = TC_SOLVER; out.runningMode = MODE_REACTIVE; return out;}
 #line 1123 "<stdout>"
 yy61:
         ++ext;
         switch ((yych = *ext)) {
         case 'p':   goto yy63;
         default:    goto yy62;
         }
 yy62:
 #line 864 "Config.r2c"
         { out.tool = TC_POSTPROC; out.runningMode = MODE_STATIC_AUTO | MODE_STATIC_MANUAL | MODE_INCREMENTAL; return out;}
 #line 1133 "<stdout>"
 yy63:
         ++ext;
 #line 856 "Config.r2c"
         { out.tool = TC_GROUNDER; out.runningMode = MODE_STATIC_AUTO | MODE_STATIC_MANUAL; return out;}
 #line 1138 "<stdout>"
 yy65:
         yych = *++ext;
         switch (yych) {
         case 'l':   goto yy69;
         default:    goto yy2;
         }
 yy66:
         yych = *++ext;
         switch (yych) {
         case 'f':   goto yy67;
         default:    goto yy2;
         }
 yy67:
         ++ext;
 #line 844 "Config.r2c"
         { out.tool = TC_PREPROC; out.runningMode = MODE_STATIC_AUTO | MODE_STATIC_MANUAL; return out; }
 #line 1155 "<stdout>"
 yy69:
         yych = *++ext;
         switch (yych) {
         case 'p':   goto yy70;
         default:    goto yy2;
         }
 yy70:
         ++ext;
 #line 848 "Config.r2c"
         { out.tool = TC_PREPROC; out.runningMode = MODE_STATIC_AUTO | MODE_STATIC_MANUAL; return out; }
 #line 1166 "<stdout>"
     }
 #line 869 "Config.r2c"
     return out;
 }
std::string const& Config::command (Toolchain tool) const inline
Returns
The base command for the specifed tool.
Definition at line 368 of file Config.h.
References _STR_TC_BEGIN_, and strOpt().
Referenced by compileCommandLine(), Config(), main(), parseCommandOptions(), and runTool().
 { return strOpt((StrOption)(tool + _STR_TC_BEGIN_)); }
bool Config::command (Toolchain tool, std::string const & val) inline
Sets the base command for a tool.
An empty value will disable the tool. A non-empty value will enable the tool.
Returns
If the command has previously been changed.
Definition at line 423 of file Config.h.
References _STR_TC_BEGIN_, run(), and strOpt().
{
         return strOpt((StrOption)(tool + _STR_TC_BEGIN_), val) |/*non-shortcutting*/ run(tool, val != "");
     }
void Config::compileArgs (Toolchain tool, std::list< std::string > & arglist, RunConfig const * subconfig = NULL) const
Compiles the set of arguments used to call a specific element in the toolchain.
Parameters
tool The toolchain element we want to compile the call for.
subconfig The subconfiguration used to override settings for this specific run.
[out] arglist The compiled list of arguments. The list is not cleared.
Definition at line 401 of file Config.cpp.
References _TC_END_, beginConstants(), boolConfigOpt(), compileInputArgs(), endConstants(), intConfigOpt(), lang(), LANG_BC, LANG_BCPLUS, LANG_CPLUS, LANG_MVPF, Config::RunConfig::maxstep, Config::RunConfig::minstep, mode(), MODE_INCREMENTAL, MODE_REACTIVE, MODE_STATIC_AUTO, MODE_STATIC_MANUAL, Config::RunConfig::numSoln, OPT_EXT_PORT, OPT_INT_PORT, OPT_MAXADDITIVE, OPT_MAXSTEP, OPT_MINSTEP, OPT_NO_ADD_DOMAIN_ENFORCE, OPT_NO_DOMAIN_ENFORCE, OPT_NUM_SOLN, OPT_SHIFT, OPT_STATS, opts(), Config::RunConfig::query, run(), STR_NONE_ALIAS, STR_QUERY, STR_SYMTAB_FILE, strOpt(), TC_GROUNDER, TC_POSTPROC, TC_PREPROC, TC_REACTIVE_BRIDGE, TC_SOLVER, TC_TRANSLATOR, utils::to_string(), and UNDEFINED.
Referenced by compileCommandLine(), and runTool().
{
     std::stringstream tmpstream;
     std::string tmpstr;
     tmpstream << opts(tool);
     tmpstream >> tmpstr;
     while (tmpstream.good()) {
         arglist.push_back(tmpstr);
         tmpstream >> tmpstr;
     }
     // Add step specific instructions
     switch (tool) {
     case _TC_END_:
     case TC_TRANSLATOR:
         compileInputArgs(tool, arglist);
         // The translator should be told to output the symbol table
         arglist.push_back("--symtab-out");
         arglist.push_back(strOpt(STR_SYMTAB_FILE));
         switch (lang()) {
         case LANG_CPLUS:
             arglist.push_back("--language=c+");
             break;
         case LANG_BC:
             arglist.push_back("--language=bc");
             break;
         case LANG_BCPLUS:
             arglist.push_back("--language=bc+");
             break;
         case LANG_MVPF:
             arglist.push_back("--language=mvpf");
             break;
         }
         if (boolConfigOpt(OPT_NO_DOMAIN_ENFORCE)) {
             arglist.push_back("--no-domain");
         }
         if (boolConfigOpt(OPT_NO_ADD_DOMAIN_ENFORCE)) {
             arglist.push_back("--no-additive-domain");
         }
         // The translator should be told the translation mode.
         switch (mode()) {
         case MODE_STATIC_AUTO:
         case MODE_STATIC_MANUAL:
             arglist.push_back("--mode=static");
             break;
         case MODE_INCREMENTAL:
         case MODE_REACTIVE:
         default:
             break;
         }
         // defined constants
         for (ConstantMap::const_iterator it = beginConstants(); it != endConstants(); it++) {
             arglist.push_back(it->first + "=" + it->second);
         }
         break;
     case TC_PREPROC:
         arglist.push_back("-i");
         compileInputArgs(tool, arglist);
         break;
     case TC_SOLVER:
         // Solvers need:
         // * Number of solutions to find.
         // * Query information.
         // * Minimum step information
         // * Maximum step information.
         compileInputArgs(tool, arglist);
         // # solutions
         if (subconfig) {
             arglist.push_back(utils::to_string(subconfig->numSoln));
         } else {
             arglist.push_back(utils::to_string(intConfigOpt(OPT_NUM_SOLN)));
         }
         // special constants (if we're running what looks like a grounder/solver)
         if (!run(TC_GROUNDER)) {
             if (subconfig) {
                 if (subconfig->query != "") arglist.push_back("-c query=q_" +subconfig->query);
                 if (subconfig->maxstep != UNDEFINED) arglist.push_back("-c maxstep=" + utils::to_string(subconfig->maxstep));
                 if (subconfig->minstep != UNDEFINED) arglist.push_back("-c minstep=" + utils::to_string(subconfig->minstep));
             } else {
                 if (strOpt(STR_QUERY) != "") arglist.push_back("-c query=q_" + strOpt(STR_QUERY));
                 if (intConfigOpt(OPT_MAXSTEP) != UNDEFINED) arglist.push_back("-c maxstep=" + utils::to_string(intConfigOpt(OPT_MAXSTEP)));
                 if (intConfigOpt(OPT_MINSTEP) != UNDEFINED) arglist.push_back("-c minstep=" + utils::to_string(intConfigOpt(OPT_MINSTEP)));
             }
             if (intConfigOpt(OPT_MAXADDITIVE) != UNDEFINED) arglist.push_back("-c maxAdditive=" + utils::to_string(intConfigOpt(OPT_MAXADDITIVE)));
             if (strOpt(STR_NONE_ALIAS) != "") arglist.push_back("-c o_none=" + strOpt(STR_NONE_ALIAS));
             // The '--shift' flag signals that gringo should shift disjunction into the body of a rule.
             if (boolConfigOpt(OPT_SHIFT)) arglist.push_back("--shift");
         }
         // min/max step
         if (mode() == MODE_INCREMENTAL || mode() == MODE_REACTIVE) {
             if (subconfig) {
                 if (subconfig->minstep != UNDEFINED) arglist.push_back("--imin=" + utils::to_string(subconfig->minstep));
                 if (subconfig->maxstep != UNDEFINED) {
                     if (subconfig->maxstep > 0)
                         arglist.push_back("--imax=" + utils::to_string(subconfig->maxstep));
                     else
                         arglist.push_back("--ibase");
                 }
             } else {
                 if (intConfigOpt(OPT_MINSTEP) != UNDEFINED) arglist.push_back("--imin=" + utils::to_string(intConfigOpt(OPT_MINSTEP)));
                 if (intConfigOpt(OPT_MAXSTEP) != UNDEFINED){
                     if (intConfigOpt(OPT_MAXSTEP) > 0)
                         arglist.push_back("--imax=" + utils::to_string(intConfigOpt(OPT_MAXSTEP)));
                     else
                         arglist.push_back("--ibase");
                 }
             }
         }
         // The --stats option
         if (boolConfigOpt(OPT_STATS)) {
             arglist.push_back("--stats");
             if (mode() == MODE_REACTIVE || mode() == MODE_INCREMENTAL)
                 arglist.push_back("--istats");
         }
         if (mode() == MODE_REACTIVE && run(TC_REACTIVE_BRIDGE)) {
 #ifdef NO_REACTIVE_BRIDGE
             if (intConfigOpt(OPT_EXT_PORT) != UNDEFINED)
                 arglist.push_back("--port=" + utils::to_string(intConfigOpt(OPT_EXT_PORT)));
             else
 #endif
                 arglist.push_back("--port=" + utils::to_string(intConfigOpt(OPT_INT_PORT)));
         } else if (mode() == MODE_REACTIVE) {
             // we aren't running the reactive bridge.
             // connect to the external port instead.
             arglist.push_back("--port=" + utils::to_string(intConfigOpt(OPT_EXT_PORT)));
         }
         break;
     case TC_GROUNDER:
         compileInputArgs(tool, arglist);
         if (subconfig) {
             if (subconfig->query != "") arglist.push_back("-c query=q_" +subconfig->query);
             if (subconfig->maxstep != UNDEFINED) arglist.push_back("-c maxstep=" + utils::to_string(subconfig->maxstep));
             if (subconfig->minstep != UNDEFINED) arglist.push_back("-c minstep=" + utils::to_string(subconfig->minstep));
         } else {
             if (strOpt(STR_QUERY) != "") arglist.push_back("-c query=q_" + utils::to_string(strOpt(STR_QUERY)));
             if (intConfigOpt(OPT_MAXSTEP) != UNDEFINED) arglist.push_back("-c maxstep=" + utils::to_string(intConfigOpt(OPT_MAXSTEP)));
             if (intConfigOpt(OPT_MINSTEP) != UNDEFINED) arglist.push_back("-c minstep=" + utils::to_string(intConfigOpt(OPT_MINSTEP)));
         }
         if (intConfigOpt(OPT_MAXADDITIVE) != UNDEFINED) arglist.push_back("-c maxAdditive=" + utils::to_string(intConfigOpt(OPT_MAXADDITIVE)));
         if (strOpt(STR_NONE_ALIAS) != "") arglist.push_back("-c none=" + strOpt(STR_NONE_ALIAS));
         // The '--shift' flag signals that gringo should shift disjunction into the body of a rule.
         if (boolConfigOpt(OPT_SHIFT)) arglist.push_back("--shift");
         for (ConstantMap::const_iterator it = beginConstants(); it != endConstants(); it++) {
             arglist.push_back("-c");
             arglist.push_back(it->first + "=" + it->second);
         }
         break;
     case TC_REACTIVE_BRIDGE:
 #ifdef NO_REACTIVE_BRIDGE
         // Don't do anything!
 #else
         // The reactive client doesn't need to know much.
         // Just the ports to use and where to find the symbol table
 //      compileInputArgs(tool, arglist);
         arglist.push_back("--symbol-table=" + strOpt(STR_SYMTAB_FILE));
         arglist.push_back("--port=" + utils::to_string(intConfigOpt(OPT_INT_PORT)));
 //      if (intConfigOpt(OPT_EXT_PORT) != UNDEFINED)
 //          arglist.push_back("--client-port=" + utils::to_string(intConfigOpt(OPT_EXT_PORT)));
         if (strOpt(STR_NONE_ALIAS) != "")
             arglist.push_back("--none=" + strOpt(STR_NONE_ALIAS));
 #endif
         break;
     case TC_POSTPROC:
         compileInputArgs(tool, arglist);
         if (strOpt(STR_NONE_ALIAS) != "")
             arglist.push_back("--none=" + strOpt(STR_NONE_ALIAS));
         arglist.push_back("--strip-prefix");
         break;
     }
 }
std::string Config::compileCommandLine (Toolchain tool, RunConfig const * subconfig = NULL) const
Compiles the command line call for a specific element in the toolchain.
Parameters
tool The toolchain element we want to compile the call for.
subconfig The subconfiguration used to override settings for this specific run.
Returns
A command to send to the system to call the element.
Definition at line 385 of file Config.cpp.
References command(), and compileArgs().
Referenced by runTool().
{
     std::ostringstream out;
     std::list<std::string> tmp;
     compileArgs(tool, tmp, subconfig);
     out << command(tool);
     for (std::string const& arg : tmp) {
         out << " " << arg;
     }
     return out.str();
 }
void Config::compileInputArgs (Toolchain tool, std::list< std::string > & arglist) const protected
Compiles a command which aggregates all the appropriate input files for a toolchain tool into stdout.
Parameters
tool The tool to compile the inputs for.
[out] arglist The list of args to append the input args to.
Definition at line 753 of file Config.cpp.
References _TC_BEGIN_, _TC_END_, beginInput(), endInput(), output(), run(), TC_GROUNDER, TC_POSTPROC, TC_PREPROC, TC_REACTIVE_BRIDGE, TC_SOLVER, and TC_TRANSLATOR.
Referenced by compileArgs().
{
     // Otherwise, we need to aggregate all the input files
     // which belong to
     // a) The current tool,
     // b) The tools immediately preceeding the tool which we aren't running.
     // Compile the input files from previous step's outputs.
     switch (tool) {
     case _TC_END_:
     case TC_REACTIVE_BRIDGE:
         break;
     case TC_POSTPROC:
         if (run(TC_SOLVER)) {
             args.push_back(output(TC_SOLVER));
             break;
         }
         /* no break */
     case TC_SOLVER:
         if (run(TC_GROUNDER)) {
             args.push_back(output(TC_GROUNDER));
             break;
         }
         /* no break */
     case TC_GROUNDER:
         if (run(TC_PREPROC)) {
             args.push_back(output(TC_PREPROC));
             break;
         }
         /* no break */
     case TC_PREPROC:
         if (run(TC_TRANSLATOR)) {
             args.push_back(output(TC_TRANSLATOR));
             break;
         }
         /* no break */
     case TC_TRANSLATOR:
         // none
         break;
     }
     if (tool != TC_REACTIVE_BRIDGE) {
         for (int i = (int)tool; i >= (int)_TC_BEGIN_; i--) {
             // Only include files which haven't been included by a previous tool.
             if (i != (int)tool && run((Toolchain)i)) break;
             for (InputList::const_iterator it = beginInput((Toolchain)i); it != endInput((Toolchain)i); it++) {
                 args.push_back(*it);
             }
         }
     }
 }
size_t Config::cumulativeInputCount (Toolchain tool) const
Tallies the number of user inputs that will be added to the provided too.
This tally includes intermediate files from the previous step that will be ran, as well as input files from all steps between the specified tool and the previous step that was ran.
Parameters
tool The tool to get an input tally of.
Returns
The number of user input files that will be passed to that tool.
Definition at line 317 of file Config.cpp.
References _TC_BEGIN_, _TC_END_, beginInput(), endInput(), run(), TC_GROUNDER, TC_POSTPROC, TC_PREPROC, TC_REACTIVE_BRIDGE, TC_SOLVER, and TC_TRANSLATOR.
Referenced by runTool().
{
     size_t count = 0;
     // Let's count all the input files
     // which belong to
     // a) The current tool,
     // b) The tools immediately preceeding the tool which we aren't running.
     if (tool != TC_REACTIVE_BRIDGE) {
         for (Toolchain i = tool; i >= _TC_BEGIN_; i = (Toolchain)((int)i - 1)) {
             // Only include files which haven't been included by a previous tool.
             if (i != tool && run(i)) break;
             for (InputList::const_iterator it = beginInput((Toolchain)i); it != endInput((Toolchain)i); it++) {
                 count++;
             }
         }
     }
     // Compile the input files from previous step's outputs.
     switch (tool) {
     case _TC_END_:
     case TC_REACTIVE_BRIDGE:
         // Reactive bridge is different.
 //      if (run(TC_TRANSLATOR)) {
 //          count++;
 //      }
         break;
     case TC_POSTPROC:
         if (run(TC_SOLVER)) {
             count++;
             break;
         }
         /* no break */
     case TC_SOLVER:
         if (run(TC_GROUNDER)) {
             count++;
             break;
         }
         /* no break */
     case TC_GROUNDER:
         if (run(TC_PREPROC)) {
             count++;
             break;
         }
         /* no break */
     case TC_PREPROC:
         if (run(TC_TRANSLATOR)) {
             count++;
             break;
         }
         /* no break */
     case TC_TRANSLATOR:
         // none
         break;
     }
     return count;
 }
bool Config::customCmd (Toolchain tool) const inline
Returns
Whether the base command for the tool has been manually modififed.
Definition at line 370 of file Config.h.
References _STR_TC_BEGIN_, and customStrOpt().
Referenced by mode().
 { return customStrOpt((StrOption)(tool + _STR_TC_BEGIN_)); }
bool Config::customConfigOpt (ConfigOption opt) const inline
Returns
Whether the specified option has been manually modified.
Definition at line 360 of file Config.h.
Referenced by isDefined(), and showQueries().
 { return (bool)mCustomConfig[opt]; }
bool Config::customLang () const inline
Returns
Whether the input language has been manually modified.
Definition at line 352 of file Config.h.
 { return (bool)mLang; }
bool Config::customMode () const inline
Returns
Whether the running mode has been manually modified.
Definition at line 347 of file Config.h.
Referenced by main(), and parseCommandOptions().
 { return (bool)mCustomRunningMode; }
bool Config::customOpts (Toolchain tool) const inline
Returns
Whether the command options have been manually modififed.
Definition at line 378 of file Config.h.
References _STR_TC_OPT_BEGIN_, and customStrOpt().
 { return customStrOpt((StrOption)(tool + _STR_TC_OPT_BEGIN_)); }
bool Config::customOut (Toolchain tool) const inline
Returns
Whether the output file for the specified tool has been manually modified.
Definition at line 397 of file Config.h.
References _STR_TC_OUT_BEGIN_, and customStrOpt().
Referenced by cleanup(), and runTool().
 { return customStrOpt((StrOption)(tool + _STR_TC_OUT_BEGIN_)); }
bool Config::customRun (Toolchain tool) const inline
Returns
Whether the run status of the tool has been manually modified.
Definition at line 374 of file Config.h.
 { return (bool)mCustomRun[tool]; }
bool Config::customStrOpt (StrOption opt) const inline
Returns
Whether the specified option has been manually modified.
Definition at line 364 of file Config.h.
Referenced by customCmd(), customOpts(), customOut(), and isDefined().
 { return (bool)mCustomStr[opt]; }
std::string const * Config::def (std::string const & constant) const
Definition at line 132 of file Config.cpp.
Referenced by parseCommandOptions().
{
     try {
         return &mConstDefs.at(constant);
     }
     catch (std::out_of_range& e)
     {
         return NULL;
     }
     return NULL;
 }
bool Config::def (std::string const & constant, std::string const & value)
Returns
If the constant was previously defined.
Definition at line 265 of file Config.cpp.
References CONST_MAXADDITIVE, CONST_MAXSTEP, CONST_MINSTEP, CONST_QUERY, utils::from_string(), intConfigOpt(), OPT_MAXADDITIVE, OPT_MAXSTEP, OPT_MINSTEP, parseMaxstep(), STR_QUERY, strOpt(), utils::trimWhitespace(), UNDEFINED, and utils::warning().
{
     std::string constant_trimmed = utils::trimWhitespace(constant);
     std::string value_trimmed = utils::trimWhitespace(value);
     unsigned int tmpVal;
     bool redef = false;
     bool bad = false;
     // Check this against several known constants and update their values if necessary...
     if (constant_trimmed == CONST_MAXSTEP) {
         std::pair<unsigned int,unsigned int> stepvals = parseMaxstep(value_trimmed);
         if (stepvals.second == UNDEFINED) {
             bad = true;
         } else {
             redef = intConfigOpt(OPT_MAXSTEP, stepvals.second);
             if (stepvals.first != UNDEFINED) intConfigOpt(OPT_MINSTEP, stepvals.first);
         }
     } else if (constant_trimmed == CONST_MINSTEP) {
         if (utils::from_string(tmpVal,value_trimmed)) {
             redef = intConfigOpt(OPT_MINSTEP, tmpVal);
         } else {
             // Oops... Throw a warning, ignore it, and continue.
             bad = true;
         }
     } else if (constant_trimmed == CONST_QUERY) {
     redef = strOpt(STR_QUERY,value_trimmed);
     } else if (constant_trimmed == CONST_MAXADDITIVE) {
         if (utils::from_string(tmpVal,value_trimmed)) {
             redef = intConfigOpt(OPT_MAXADDITIVE,tmpVal);
         } else {
             // Oops... Throw a warning, ignore it, and continue.
             bad = true;
         }
     } else {
         // It's a normal constant...
         redef = (bool)mConstDefs.count(constant_trimmed);
         mConstDefs[constant_trimmed] = value_trimmed;
     }
     if (bad) {
         // If the value was bad then go ahead and warn the user.
         utils::warning("The value '%s' is not valid for the reserved constant '%s'. It will be ignored.",true, value_trimmed.c_str() ,constant_trimmed.c_str());
     }
     return redef;
 }
ConstantMap::const_iterator Config::endConstants () const inline
Gets an iterator pointing to the end of the list of constant definitions.
Returns
An iterator pointing the end of the constant definitions.
Definition at line 527 of file Config.h.
Referenced by compileArgs().
 { return mConstDefs.end(); }
ConstantMap::iterator Config::endConstants () inline
Gets an iterator pointing to the end of the list of constant definitions.
Returns
An iterator pointing the end of the constant definitions.
Definition at line 572 of file Config.h.
 { return mConstDefs.end(); }
InputList::const_iterator Config::endInput (Toolchain tool) const inline
Gets an iterator pointing to the end of the list of input files for a tool.
Parameters
tool The tool to get the iterator for.
Returns
An iterator pointing the end of the input list.
Definition at line 513 of file Config.h.
Referenced by compileInputArgs(), and cumulativeInputCount().
 { return mInputs[tool].end(); }
InputList::iterator Config::endInput (Toolchain tool) inline
Gets an iterator pointing to the beginning of the list of input files for a tool.
Parameters
tool The tool to get the iterator for.
Returns
An iterator pointing the beginning of the input list.
Definition at line 558 of file Config.h.
 { return mInputs[tool].begin(); }
QueryMap::const_iterator Config::endQueries () const inline
Gets an iterator pointing to the beginning of the list of query definitions.
Returns
An iterator pointing the beginning of the query definitions.
Definition at line 542 of file Config.h.
Referenced by queryUserForQuery(), and showQueries().
 { return mQueries.end(); }
QueryMap::iterator Config::endQueries () inline
Gets an iterator pointing to the beginning of the list of query definitions.
Returns
An iterator pointing the beginning of the query definitions.
Definition at line 587 of file Config.h.
 { return mQueries.end(); }
std::string const& Config::errFile () const inline
Returns
The file we should use for stderr from our children.
Definition at line 393 of file Config.h.
Referenced by cleanup(), and runTool().
 { return mErrFile; }
bool Config::hasQuery (std::string const & queryCmd) const inline
Definition at line 387 of file Config.h.
Referenced by addQuery(), and query().
 { return (bool)mQueries.count(queryCmd); }
unsigned int Config::intConfigOpt (ConfigOption opt) const inline
Returns
The integral value of the specified option.
Definition at line 358 of file Config.h.
Referenced by compileArgs(), def(), main(), parseCommandOptions(), and showConfig().
 { return mConfigOpts[opt]; }
bool Config::intConfigOpt (ConfigOption opt, unsigned int val)
Returns
If the option was previously set.
Definition at line 240 of file Config.cpp.
{
     mCustomConfig[opt]++;
     if (mConfigOpts[opt] == val) return false;
     mConfigOpts[opt] = val;
     return (bool)(mCustomConfig[opt] - 1);
 }
bool Config::isDefined (std::string const & constant) const inline
Definition at line 215 of file Config.cpp.
References CONST_MAXADDITIVE, CONST_MAXSTEP, CONST_MINSTEP, CONST_QUERY, customConfigOpt(), customStrOpt(), OPT_MAXADDITIVE, OPT_MAXSTEP, OPT_MINSTEP, STR_QUERY, and utils::trimWhitespace().
{
     std::string constant_trimmed = utils::trimWhitespace(constant);
     if (constant_trimmed == CONST_MAXSTEP) {
         return customConfigOpt(OPT_MAXSTEP);
     } else if (constant_trimmed == CONST_MINSTEP) {
         return customConfigOpt(OPT_MINSTEP);
     } else if (constant_trimmed == CONST_QUERY) {
         return customStrOpt(STR_QUERY);
     } else if (constant_trimmed == CONST_MAXADDITIVE) {
         return customConfigOpt(OPT_MAXADDITIVE);
     } else {
         return (bool)mConstDefs.count(constant_trimmed);
     }
 }
Language Config::lang () const inline
Returns
The currently configured input language
Definition at line 350 of file Config.h.
Referenced by compileArgs(), and parseCommandOptions().
 { return mLang; }
bool Config::lang (Language newLang)
Returns
If the input language has been previously set.
Definition at line 192 of file Config.cpp.
References CONST_QUERY_NONE, CONST_QUERY_STATES, CONST_QUERY_TRANSITIONS, LANG_MVPF, mode(), MODE_STATIC_AUTO, STR_QUERY, and strOpt().
{
     mCustomLang++;
     if (mLang == newLang) return false;
     mLang = newLang;
     if (newLang == LANG_MVPF) {
         mQueries.erase(CONST_QUERY_TRANSITIONS);
         mQueries.erase(CONST_QUERY_STATES);
         strOpt(STR_QUERY, CONST_QUERY_NONE);
         if (!mCustomRunningMode) {
             mode(MODE_STATIC_AUTO);
             mCustomRunningMode = 0;
         }
     } else {
         mQueries[CONST_QUERY_TRANSITIONS] = Query("System transitions", CONST_QUERY_TRANSITIONS, 1, 1);
         mQueries[CONST_QUERY_STATES] = Query("System states", CONST_QUERY_STATES, 0, 0);
     }
     return (bool)(mCustomLang - 1);
  }
Mode Config::mode () const inline
Basic Accessor. Does what's on the box.
Returns
The currently configured running mode
Definition at line 345 of file Config.h.
Referenced by compileArgs(), lang(), main(), parseCommandOptions(), runTool(), and showConfig().
 { return mRunningMode; }
bool Config::mode (Mode newMode)
Basic Mutators.
Returns
If the running mode has been previously set.
Definition at line 152 of file Config.cpp.
References _STR_TC_BEGIN_, customCmd(), DEF_GRD_INCREMENTAL_CMD, DEF_GRD_REACTIVE_CMD, DEF_GRD_STATIC_CMD, DEF_SO_INCREMENTAL_CMD, DEF_SO_REACTIVE_CMD, DEF_SO_STATIC_CMD, MODE_INCREMENTAL, MODE_REACTIVE, MODE_STATIC_AUTO, MODE_STATIC_MANUAL, MODE_UNKNOWN, TC_GROUNDER, TC_POSTPROC, and TC_SOLVER.
{
     mCustomRunningMode++;
     if (mRunningMode == newMode) return false;
     mRunningMode = newMode;
     switch (newMode) {
     case MODE_STATIC_AUTO:
     case MODE_STATIC_MANUAL:
         if (!customCmd(TC_GROUNDER)) mStrOpts[TC_GROUNDER + _STR_TC_BEGIN_] = DEF_GRD_STATIC_CMD;
         if (!customCmd(TC_SOLVER)) mStrOpts[TC_SOLVER + _STR_TC_BEGIN_] = DEF_SO_STATIC_CMD;
         break;
     case MODE_INCREMENTAL:
         if (!customCmd(TC_GROUNDER)) mStrOpts[TC_GROUNDER + _STR_TC_BEGIN_] = DEF_GRD_INCREMENTAL_CMD;
         if (!customCmd(TC_SOLVER)) mStrOpts[TC_SOLVER + _STR_TC_BEGIN_] = DEF_SO_INCREMENTAL_CMD;
         break;
     case MODE_REACTIVE:
         if (!customCmd(TC_GROUNDER)) mStrOpts[TC_GROUNDER + _STR_TC_BEGIN_] = DEF_GRD_REACTIVE_CMD;
         if (!customCmd(TC_POSTPROC)) mRun[TC_POSTPROC] = false;
         if (!customCmd(TC_SOLVER)) mStrOpts[TC_SOLVER + _STR_TC_BEGIN_] = DEF_SO_REACTIVE_CMD;
         break;
     case MODE_UNKNOWN:
         break;
     }
     return (bool)(mCustomRunningMode - 1);
  }
std::string const& Config::opts (Toolchain tool) const inline
Returns
The user-defined command options for the specified tool.
Definition at line 376 of file Config.h.
References _STR_TC_OPT_BEGIN_, and strOpt().
Referenced by compileArgs(), Config(), and parseCommandOptions().
 { return strOpt((StrOption)(tool + _STR_TC_OPT_BEGIN_)); }
bool Config::opts (Toolchain tool, std::string const & val) inline
Returns
Whether the option has been previously set.
Definition at line 431 of file Config.h.
References _STR_TC_OPT_BEGIN_, and strOpt().
{
         return strOpt((StrOption)(tool + _STR_TC_OPT_BEGIN_), val);
     }
std::string const& Config::output (Toolchain tool) const inline
Returns
A description of the output file for the provided tool.
Definition at line 395 of file Config.h.
References _STR_TC_OUT_BEGIN_, and strOpt().
Referenced by cleanup(), compileInputArgs(), Config(), main(), parseCommandOptions(), and runTool().
 { return strOpt((StrOption)(tool + _STR_TC_OUT_BEGIN_)); }
bool Config::output (Toolchain tool, std::string const & file) inline
Sets the target output file for the toolchain component.
Parameters
file The new output file.
Returns
True if this overrode a previous configuration.
Definition at line 439 of file Config.h.
References _STR_TC_OUT_BEGIN_, and strOpt().
{
         return strOpt((StrOption)(tool + _STR_TC_OUT_BEGIN_), file);
     }
bool Config::parseLang (char const * str, Language & outLang)
Parses the language represented in the string.
Parameters
str The string containing the language specification.
[out] outLang The language stored in the string.
Returns
True if successful, false otherwise.
Definition at line 182 of file Config.cpp.
References LANG_BC, LANG_BCPLUS, LANG_CPLUS, and LANG_MVPF.
Referenced by parseCommandOptions().
{
     if (boost::iequals(str, "bc")) outLang = LANG_BC;
     else if (boost::iequals(str, "bc+")) outLang = LANG_BCPLUS;
     else if (boost::iequals(str, "c+")) outLang = LANG_CPLUS;
     else if (boost::iequals(str, "mvpf")) outLang = LANG_MVPF;
     else return false;
     return true;
 }
std::pair< unsigned int, unsigned int > Config::parseMaxstep (std::string const & maxstep) static
Parses a maxstep specification in the form a single unsigned integer or an integer range d..d.
Parses a maxstep specification.
Parameters
maxstep The maxstep specification.
Returns
A pair (minstep,maxstep) corresponding to the specification. If the specification is malformed both will be UNDEFINED. If it's a single integer, minstep will be UNDEFINED.
Definition at line 719 of file Config.cpp.
References CONST_MAXSTEP_INFINITE, utils::from_string(), INF, utils::trimWhitespace(), and UNDEFINED.
Referenced by def(), parseCommandOptions(), and queryUserForQuery().
{
     size_t pos;
     std::pair<unsigned int, unsigned int> ret(UNDEFINED, UNDEFINED);
     std::string tmp;
     if ((pos = maxstep.find("..")) != std::string::npos) {
         // They've provided a range. Interpret it as a minstep and maxstep.
         tmp = utils::trimWhitespace(maxstep.substr(pos+2));
     } else {
         tmp = maxstep;
     }
     if (tmp == CONST_MAXSTEP_INFINITE) {
         ret.second = INF;
     } else  if (!utils::from_string(ret.second,tmp)) {
         // error
         ret.first = UNDEFINED;
         ret.second = UNDEFINED;
     }
     if (ret.second != UNDEFINED
         && pos != std::string::npos
         && !utils::from_string(ret.first,utils::trimWhitespace(maxstep.substr(0,pos)))) {
         // error
         ret.first = UNDEFINED;
         ret.second = UNDEFINED;
     }
     return ret;
 }
Config::Query const * Config::query (std::string const & queryCmd) const
Definition at line 145 of file Config.cpp.
References hasQuery().
Referenced by activeQuery(), addQuery(), and main().
{
     if (hasQuery(queryCmd)) return &(mQueries.at(queryCmd));
     else return NULL;
 }
size_t Config::queryCount () const inline
Definition at line 386 of file Config.h.
 { return mQueries.size(); }
bool Config::run (Toolchain tool) const inline
Returns
Whether the tool is configured to run.
Definition at line 372 of file Config.h.
Referenced by command(), compileArgs(), compileInputArgs(), cumulativeInputCount(), main(), runTool(), setOnlyRun(), setRunFrom(), and setRunTo().
 { return mRun[tool]; }
bool Config::run (Toolchain tool, bool val)
Returns
If the run status has been previously changed.
Definition at line 256 of file Config.cpp.
{
     mCustomRun[tool]++;
     if(mRun[tool] == val) return false;
     mRun[tool] = val;
     return (bool)(mCustomRun[tool] - 1);
 }
bool Config::setOnlyRun (Toolchain tool)
Sets the toolchain to run only the specified tool and nothing else.
Parameters
tool The toolchain tool to run.
Returns
True if this command has overriden one or more previous configuration options.
Definition at line 646 of file Config.cpp.
References _TC_BEGIN_, _TC_END_, and run().
Referenced by parseCommandOptions().
{
     bool conflict = false;
     for (int i = (int)_TC_BEGIN_; i < (int)tool; i++) {
         conflict |= run((Toolchain)i, false);
     }
     conflict |= run(tool,true);
     for (int i = ((int)tool)+1; i < (int)_TC_END_; i++) {
         conflict |= run((Toolchain)i, false);
     }
     return conflict;
 }
bool Config::setRunFrom (Toolchain tool)
Sets the toolchain to run everything from the desired tool (including the tool) and nothing else.
Parameters
tool The toolchain tool to run from.
Returns
True if this command has overriden one or more previous configuration options.
Definition at line 633 of file Config.cpp.
References _TC_BEGIN_, and run().
Referenced by parseCommandOptions().
{
     bool conflict = false;
     for (int i = (int)_TC_BEGIN_; i < (int)tool; i++) {
         conflict |= run((Toolchain)i, false);
     }
 //  for (int i = (int)tool; i < (int)TC_END; i++) {
 //      conflict |= run((Toolchain)i, true);
 //  }
     return conflict;
 }
bool Config::setRunTo (Toolchain tool)
Sets the toolchain to run everything up to the desired tool and nothing else.
Parameters
tool The toolchain tool to run to.
Returns
True if this command has overidden one or more previous configuration options.
Definition at line 620 of file Config.cpp.
References _TC_END_, and run().
Referenced by parseCommandOptions().
{
     bool conflict = false;
 //  for (int i = (int)_TC_BEGIN_; i < (int)tool+1; i++) {
 //      conflict |= run((Toolchain)i, true);
 //  }
     for (int i = ((int)tool)+1; i < (int)_TC_END_; i++) {
         conflict |= run((Toolchain)i, false);
     }
     return conflict;
 }
std::string const& Config::strOpt (StrOption opt) const inline
Returns
The string value of the specified option.
Definition at line 362 of file Config.h.
Referenced by activeQuery(), command(), compileArgs(), Config(), def(), lang(), main(), opts(), output(), and parseCommandOptions().
 { return mStrOpts[opt]; }
bool Config::strOpt (StrOption opt, std::string const & val)
Returns
If the option was previously set.
Definition at line 248 of file Config.cpp.
{
     mCustomStr[opt]++;
     if (mStrOpts[opt] == val) return false;
     mStrOpts[opt] = val;
     return (bool)(mCustomStr[opt] - 1);
 }
Member Data Documentation
unsigned int const Config::INF = UINT_MAX - 4 static
Indicates an infinite value.
Definition at line 287 of file Config.h.
Referenced by parseMaxstep(), and showConfig().
unsigned int const Config::UNDEFINED = UINT_MAX static
Indicates an undefined configuration setting.
Definition at line 284 of file Config.h.
Referenced by compileArgs(), Config(), def(), main(), parseCommandOptions(), parseMaxstep(), queryUserForConstant(), queryUserForQuery(), showConfig(), and showQueries().
The documentation for this class was generated from the following files:
cplus2asp/Config.h
cplus2asp/Config.cpp