cplus2asp: SimpleBinaryOperator Class Reference
SimpleBinaryOperator Class Reference
Child of ParseElement that represents a binary operator and the associated elements it operates on.
#include <parser_types.h>
Public Types
enum BinaryOperatorType {
BOP_UNKNOWN, BOP_PLUS, BOP_MINUS, BOP_TIMES,
BOP_DIVIDE, BOP_MOD, BOP_AND, BOP_OR,
BOP_EQUIV, BOP_IMPL, BOP_REV_IMPL, BOP_EQ,
BOP_NEQ, BOP_DBL_EQ, BOP_LTHAN, BOP_GTHAN,
BOP_LTHAN_EQ, BOP_GTHAN_EQ, BOP_BIND_STEP
}
Enum of the kinds of unary operators this class can be.
Public Types inherited from ParseElement
enum ParseElementType {
PELEM_PELEM, PELEM_UOP, PELEM_BOP, PELEM_QUANT,
PELEM_BASELIKE, PELEM_CONSTLIKE, PELEM_OBJLIKE, PELEM_VARLIKE
}
The possible types of a ParseElement instance.
enum ConstMask {
MASK_ACTION = 0x01, MASK_FLUENT = 0x02, MASK_RIGID = 0x04, MASK_STATIC_AB = 0x08,
MASK_DYNAMIC_AB = 0x10, MASK_TRUE_FALSE = 0x20, MASK_SDFLUENT = 0x40, MASK_AB = MASK_STATIC_AB | MASK_DYNAMIC_AB,
MASK_NON_TRIVIAL = ~MASK_TRUE_FALSE, MASK_NON_RIGID = MASK_NON_TRIVIAL & ~MASK_RIGID, MASK_NON_AB = MASK_NON_TRIVIAL & ~MASK_AB
}
Mask values for the various kinds of constants that can be in a formula.
Public Member Functions
SimpleBinaryOperator (ParseElement *preOp, BinaryOperatorType opType, ParseElement *postOp, bool parens=false)
Full constructor.
virtual std::ostream & translate (std::ostream &out, Context &context) const
Method that generates a translated string representation of the element with preceeding @ if a symbol is understood as a lua function call.
virtual bool hasConstants (unsigned int types, bool includeParams=true, bool includeEq=true) const
Returns true if the element (or any of its children) are constants of the provided types.
virtual bool isDefinite (bool allowComparison=false, bool allowChoice=false, bool allowAtomicNegation=false) const
Determines if the element contains a single atom, a unary expression w/ a single atom, or a conjunction thereof.
virtual bool isSingleAtom (bool allowAtomicNegation=false) const
Whether the formula is a single atom.
virtual bool isArithExpr () const
Determines if the element is a valid arithmetic expression.
virtual bool hasLuaCalls (bool includeParams=true, bool includeEq=true) const
Determines if the element contains any calls to LUA.
virtual IPart determineQueryIPart () const
Determines the proper IPart to place the formula in.
virtual std::ostream & fullName (std::ostream &out) const
Prints the untranslated element string.
virtual ParseElement * copy () const
Returns an exact copy of the parse element.
virtual void aggregateUndefined (BaseElementList &outIdentifiers)
Aggregates all of the undefined identifiers (which are assumed to be constants).
BinaryOperatorType opType () const
Gets the operator's type.
void opType (BinaryOperatorType op)
Sets the operator's type.
bool isAtomicEq () const
Determines if this binary operator is an atomic equality.
ParseElement const * postOp () const
Gets the operator's sub expression.
ParseElement const * preOp () const
void postOp (ParseElement *postOp)
Sets the operator's sub expression, deallocating any existing sub expression.
void preOp (ParseElement *postOp)
ParseElement * detachPostOp ()
Detaches the operator's sub expression, returning it.
ParseElement * detachPreOp ()
virtual ~SimpleBinaryOperator ()
Destructor.
Public Member Functions inherited from ParseElement
ParseElement (ParseElementType elemType, bool parens=false)
Default constructor.
bool isTrivial (bool includeParams=true, bool includeEq=true) const
Determines if the element contains no (real) constants.
std::string fullName () const
Alternative helper to fullName(std::ostream&).
ParseElementType getType () const
Gets the type of the parse element.
void parens (bool parens)
Sets whether the expression is wrapped in parentheses.
bool parens () const
Gets whether the element is encompassed in parens.
virtual ~ParseElement ()
Destructor.
Protected Member Functions
std::ostream & translate (std::ostream &out, Context &context, BinaryOperatorType type, bool forceParens=false) const
Translates the expression with the provided operator type.
Protected Member Functions inherited from ParseElement
bool hasParens () const
Determines if the element has parentheses around it.
std::string translateBeforeParen (bool forceParens=false) const
Helper to translate that intelligently handles the value of parenBefore.
std::string translateAfterParen (bool forceParens=false) const
Helper to translate that intelligently handles the value of parenAfter.
Static Protected Member Functions
static std::string translateOpType (BinaryOperatorType op)
Simple helper function.
Friends
class SimpleBinaryOperatorWrapper
Additional Inherited Members
Static Public Member Functions inherited from ParseElement
static std::string getNewVar ()
Gets a new variable whose name is unique within the rule we're translating.
Detailed Description
Child of ParseElement that represents a binary operator and the associated elements it operates on.
Definition at line 330 of file parser_types.h.
Member Enumeration Documentation
enum SimpleBinaryOperator::BinaryOperatorType
Enum of the kinds of unary operators this class can be.
Enumerator
BOP_UNKNOWN
BOP_PLUS
BOP_MINUS
BOP_TIMES
BOP_DIVIDE
BOP_MOD
BOP_AND
BOP_OR
BOP_EQUIV
BOP_IMPL
BOP_REV_IMPL
BOP_EQ
BOP_NEQ
BOP_DBL_EQ
BOP_LTHAN
BOP_GTHAN
BOP_LTHAN_EQ
BOP_GTHAN_EQ
BOP_BIND_STEP
Definition at line 337 of file parser_types.h.
{
             BOP_UNKNOWN,
             BOP_PLUS,
             BOP_MINUS,
             BOP_TIMES,
             BOP_DIVIDE,
             BOP_MOD,
             BOP_AND,
             BOP_OR,
             BOP_EQUIV,
             BOP_IMPL,
             BOP_REV_IMPL, // fake operator to simulate F <- G.
             BOP_EQ,
             BOP_NEQ,
             BOP_DBL_EQ,
             BOP_LTHAN,
             BOP_GTHAN,
             BOP_LTHAN_EQ,
             BOP_GTHAN_EQ,
             BOP_BIND_STEP
         };
Constructor & Destructor Documentation
SimpleBinaryOperator::SimpleBinaryOperator (ParseElement * preOp, BinaryOperatorType opType, ParseElement * postOp, bool parens = false) inline
Full constructor.
Parameters
preOp The sub expression that comes before the operator.
opType The binary operator.
postOp The sub expression that comes after the operator.
parens Whether to encase the expression in parens.
Definition at line 372 of file parser_types.h.
Referenced by copy(), and translate().
         : ParseElement(PELEM_BOP, parens), mOpType(opType), mPreOp(preOp), mPostOp(postOp)
     { /* Intentionally Left Blank */ }
SimpleBinaryOperator::~SimpleBinaryOperator () virtual
Destructor.
Deallocates preOp and postOp.
Definition at line 804 of file parser_types.cpp.
 {
     if(mPreOp)
     {
         delete mPreOp;
         mPreOp = NULL;
     }
     if(mPostOp)
     {
         delete mPostOp;
         mPostOp = NULL;
     }
 }
Member Function Documentation
void SimpleBinaryOperator::aggregateUndefined (BaseElementList & outIdentifiers) virtual
Aggregates all of the undefined identifiers (which are assumed to be constants).
Parameters
outIdentifiers The undefined identifiers.
Implements ParseElement.
Definition at line 723 of file parser_types.cpp.
References ParseElement::aggregateUndefined(), postOp(), and preOp().
{
         if (preOp()) mPreOp->aggregateUndefined(outIdentifiers);
         if (postOp()) mPostOp->aggregateUndefined(outIdentifiers);
 }
virtual ParseElement* SimpleBinaryOperator::copy () const inline virtual
Returns an exact copy of the parse element.
Implements ParseElement.
Definition at line 386 of file parser_types.h.
References copy(), opType(), ParseElement::parens(), postOp(), preOp(), and SimpleBinaryOperator().
Referenced by copy().
 { return new SimpleBinaryOperator(preOp()->copy(), opType(), postOp()->copy(), parens()); }
ParseElement * SimpleBinaryOperator::detachPostOp ()
Detaches the operator's sub expression, returning it.
Definition at line 729 of file parser_types.cpp.
Referenced by Translator::translateCausalLaw(), Translator::translateCausesLaw(), Translator::translateDefaultLaw(), Translator::translateMayCauseLaw(), Translator::translateNonexecutableLaw(), and Translator::translatePossiblyCausedLaw().
{
     ParseElement* ret = mPostOp;
     mPostOp = NULL;
     return ret;
 }
ParseElement * SimpleBinaryOperator::detachPreOp ()
Definition at line 736 of file parser_types.cpp.
Referenced by Translator::translateCausalLaw(), Translator::translateCausesLaw(), Translator::translateDefaultLaw(), Translator::translateMayCauseLaw(), Translator::translateNonexecutableLaw(), and Translator::translatePossiblyCausedLaw().
{
     ParseElement* ret = mPreOp;
     mPreOp = NULL;
     return ret;
 }
IPart SimpleBinaryOperator::determineQueryIPart () const virtual
Determines the proper IPart to place the formula in.
Returns
IPART_BASE if the formula is 0:(...), IPART_VOLATILE if the formula is X:(...), and IPART_CUMULATIVE if the formula is anything else.
Implements ParseElement.
Definition at line 650 of file parser_types.cpp.
References BOP_BIND_STEP, ParseElement::determineQueryIPart(), ParseElement::fullName(), opType(), postOp(), and preOp().
Referenced by SimpleBinaryOperatorWrapper::determineQueryIPart().
{
     std::ostringstream tmp;
     IPart ret1, ret2;
     if (opType() == BOP_BIND_STEP) {
         // This is a bind statement. Figure out what we're doing.
         preOp()->fullName(tmp);
         if (tmp.str() == "0") {
             return IPART_BASE;
         } else {
             return IPART_VOLATILE;
         }
     } else {
         ret1 = (preOp()) ? preOp()->determineQueryIPart() : IPART_BASE;
         ret2 = (postOp()) ? postOp()->determineQueryIPart() : IPART_BASE;
         if (ret1 == IPART_CUMULATIVE || ret2 == IPART_CUMULATIVE) return IPART_CUMULATIVE;
         else if (ret1 == IPART_VOLATILE || ret2 == IPART_VOLATILE) return IPART_VOLATILE;
         else return IPART_BASE;
     }
 }
std::ostream & SimpleBinaryOperator::fullName (std::ostream & out) const virtual
Prints the untranslated element string.
Parameters
out The output stream to print to.
Returns
out.
Implements ParseElement.
Definition at line 707 of file parser_types.cpp.
References ParseElement::fullName(), opType(), postOp(), preOp(), and translateOpType().
Referenced by SimpleBinaryOperatorWrapper::fullName().
 {
     if(preOp() && postOp()) {
         preOp()->fullName(out);
         out << translateOpType(opType());
         postOp()->fullName(out);
     }
     else if(!preOp() && postOp()) {
         postOp()->fullName(out);
     }
     else if(!postOp() && preOp()) {
         preOp()->fullName(out);
     }
     return out;
 }
bool SimpleBinaryOperator::hasConstants (unsigned int types, bool includeParams = true, bool includeEq = true) const virtual
Returns true if the element (or any of its children) are constants of the provided types.
Parameters
types A mask containing flags for the types to search for. See ConstMask enum.
includeParams Whether to check the parameters of constants.
includeEq Whether to check the right side of equality within an atom. (The right hand side of comparisons will be checked regardless.)
Returns
True if the element, or any elements "beneach" it, are constants, false otherwise.
Implements ParseElement.
Definition at line 569 of file parser_types.cpp.
References ParseElement::hasConstants(), isAtomicEq(), postOp(), and preOp().
Referenced by SimpleBinaryOperatorWrapper::hasConstants(), isAtomicEq(), and isDefinite().
{
     bool ret = false;
     if (preOp()) {
         ret = preOp()->hasConstants(types, includeParams, includeEq);
         if (!ret) {
             if (isAtomicEq()) {
                 // Atomic Equality
                 ret = includeEq && postOp() && postOp()->hasConstants(types, includeParams, includeEq);
             } else {
                 // not atomic equality.
                 ret = postOp() && postOp()->hasConstants(types, includeParams, includeEq);
             }
         }
     } else if (postOp()) {
         ret = postOp() && postOp()->hasConstants(types, includeParams, includeEq);
     }
     return ret;
 }
bool SimpleBinaryOperator::hasLuaCalls (bool includeParams = true, bool includeEq = true) const virtual
Determines if the element contains any calls to LUA.
Parameters
includeParams Whether to search base element parameter lists.
includeEq Whether to check the right side of equality within an atom. (The right hand side of comparisons will be checked regardless.)
Returns
True if the element or any of its children is a LUA call.
Implements ParseElement.
Definition at line 626 of file parser_types.cpp.
References ParseElement::hasLuaCalls(), isAtomicEq(), postOp(), and preOp().
Referenced by SimpleBinaryOperatorWrapper::hasLuaCalls().
{
     bool ret = false;
     if (preOp()) {
         ret = preOp()->hasLuaCalls(includeParams, includeEq);
         if (postOp() && !ret) {
             if (isAtomicEq()) {
                 // This is equality within an atom.
                 ret = includeEq && postOp()->hasLuaCalls(includeParams, includeEq);
             } else {
                 // Not atomic equality
                 ret = postOp()->hasLuaCalls(includeParams, includeEq);
             }
         }
     }
     else if (postOp()) {
         ret = postOp()->hasLuaCalls(includeParams, includeEq);
     }
     return ret;
 }
bool SimpleBinaryOperator::isArithExpr () const virtual
Determines if the element is a valid arithmetic expression.
Returns
True if the element and all it's children are arithmetic expressions.
Implements ParseElement.
Definition at line 675 of file parser_types.cpp.
References BOP_AND, BOP_DBL_EQ, BOP_DIVIDE, BOP_EQ, BOP_EQUIV, BOP_GTHAN, BOP_GTHAN_EQ, BOP_IMPL, BOP_LTHAN, BOP_LTHAN_EQ, BOP_MINUS, BOP_MOD, BOP_NEQ, BOP_OR, BOP_PLUS, BOP_TIMES, BOP_UNKNOWN, ParseElement::isArithExpr(), opType(), postOp(), and preOp().
Referenced by SimpleBinaryOperatorWrapper::isArithExpr().
{
     if (!postOp() && !preOp()) return false;
     else if (!preOp()) return postOp()->isArithExpr();
     else if (!postOp()) return preOp()->isArithExpr();
     else {
         switch (opType()) {
         case BOP_PLUS:
         case BOP_MINUS:
         case BOP_TIMES:
         case BOP_DIVIDE:
         case BOP_MOD:
             return postOp()->isArithExpr() && preOp()->isArithExpr();
         case BOP_UNKNOWN:
         case BOP_AND:
         case BOP_OR:
         case BOP_EQUIV:
         case BOP_IMPL:
         case BOP_EQ:
         case BOP_NEQ:
         case BOP_DBL_EQ:
         case BOP_LTHAN:
         case BOP_GTHAN:
         case BOP_LTHAN_EQ:
         case BOP_GTHAN_EQ:
         default:
             return false;
         }
     }
 }
bool SimpleBinaryOperator::isAtomicEq () const inline
Determines if this binary operator is an atomic equality.
(ie. c=v where c is a constant and v is some value.
Definition at line 397 of file parser_types.h.
References BOP_EQ, ParseElement::getType(), hasConstants(), ParseElement::MASK_NON_TRIVIAL, opType(), ParseElement::PELEM_CONSTLIKE, postOp(), and preOp().
Referenced by hasConstants(), hasLuaCalls(), and translate().
{
         return (opType() == BOP_EQ
                     && preOp() && postOp()
                     && preOp()->getType() == PELEM_CONSTLIKE
                     && preOp()->hasConstants(MASK_NON_TRIVIAL, false, false)
                     && !postOp()->hasConstants(MASK_NON_TRIVIAL, false, true));
     }
bool SimpleBinaryOperator::isDefinite (bool allowComparison = false, bool allowChoice = false, bool allowAtomicNegation = false) const virtual
Determines if the element contains a single atom, a unary expression w/ a single atom, or a conjunction thereof.
Parameters
allowComparison Whether to allow comparison operators in the formula.
allowChoice Whether to allow choice rules in the formula.
allowAtomicNegation whether to allow -p or "not p" where p is a boolean atom.
Returns
True if the element is a definite formula.
Implements ParseElement.
Definition at line 593 of file parser_types.cpp.
References BOP_AND, BOP_DBL_EQ, BOP_EQ, BOP_GTHAN, BOP_GTHAN_EQ, BOP_LTHAN, BOP_LTHAN_EQ, BOP_NEQ, ParseElement::getType(), ParseElement::hasConstants(), hasConstants(), ParseElement::isDefinite(), ParseElement::MASK_NON_TRIVIAL, opType(), ParseElement::PELEM_CONSTLIKE, postOp(), and preOp().
Referenced by SimpleBinaryOperatorWrapper::isDefinite().
{
     // The only time when this is true is if one of the children is NULL and the other is a single atom OR if it's of the form c=v
     // OR if it's a conjunction of single atoms.
     if (!preOp() && postOp()) return postOp()->isDefinite(allowComparison, allowChoice, allowAtomicNegation);
     else if (!postOp() && preOp()) return preOp()->isDefinite(allowComparison, allowChoice, allowAtomicNegation);
     else if (opType() == BOP_AND) {
         return preOp()->isDefinite(allowComparison, allowChoice, allowAtomicNegation) && postOp()->isDefinite(allowComparison, allowChoice, allowAtomicNegation);
     } else if (opType() == BOP_EQ) {
         return ((preOp()->getType() == ParseElement::PELEM_CONSTLIKE) || !preOp()->hasConstants(MASK_NON_TRIVIAL, false, true))
                 && !postOp()->hasConstants(MASK_NON_TRIVIAL, false, true);
     } else if (allowComparison
             && ( opType() == BOP_DBL_EQ || opType() == BOP_NEQ || opType() == BOP_LTHAN
                 || opType() == BOP_GTHAN || opType() == BOP_LTHAN_EQ || opType() == BOP_GTHAN_EQ)) {
         // Comparison-like operator. Make sure that we aren't comparing two constants.
         return !postOp()->hasConstants(MASK_NON_TRIVIAL, false, true)
             || !preOp()->hasConstants(MASK_NON_TRIVIAL, false, true);
     } else return false;
 }
bool SimpleBinaryOperator::isSingleAtom (bool allowAtomicNegation = false) const virtual
Whether the formula is a single atom.
Returns
True if the element is a single atom c=v (or just c if c is boolean).
Parameters
allowAtomicNegation whether to allow -p or "not p" where p is a boolean atom.
Implements ParseElement.
Definition at line 615 of file parser_types.cpp.
References BOP_EQ, ParseElement::getType(), ParseElement::hasConstants(), ParseElement::isSingleAtom(), ParseElement::MASK_NON_TRIVIAL, opType(), ParseElement::PELEM_CONSTLIKE, postOp(), and preOp().
Referenced by SimpleBinaryOperatorWrapper::isSingleAtom().
{
     // The only time when this is true is if one of the children is NULL and the other is a single atom OR if it's of the form c=v
     if (!preOp() && postOp()) return postOp()->isSingleAtom(allowAtomicNegation);
     else if (!postOp() && preOp()) return preOp()->isSingleAtom(allowAtomicNegation);
     else if (opType() == BOP_EQ) {
         return (preOp()->getType() == ParseElement::PELEM_CONSTLIKE)
                 && !postOp()->hasConstants(MASK_NON_TRIVIAL, false, true);
     } else return false;
 }
BinaryOperatorType SimpleBinaryOperator::opType () const inline
Gets the operator's type.
Definition at line 390 of file parser_types.h.
Referenced by copy(), determineQueryIPart(), fullName(), isArithExpr(), isAtomicEq(), isDefinite(), isSingleAtom(), and translate().
 { return mOpType; }
void SimpleBinaryOperator::opType (BinaryOperatorType op) inline
Sets the operator's type.
Definition at line 393 of file parser_types.h.
 { mOpType = op; }
ParseElement const* SimpleBinaryOperator::postOp () const inline
Gets the operator's sub expression.
Definition at line 407 of file parser_types.h.
Referenced by aggregateUndefined(), copy(), determineQueryIPart(), fullName(), hasConstants(), hasLuaCalls(), isArithExpr(), isAtomicEq(), isDefinite(), isSingleAtom(), SimpleBinaryOperatorWrapper::postOp(), preOp(), and translate().
 { return mPostOp; }
void SimpleBinaryOperator::postOp (ParseElement * postOp) inline
Sets the operator's sub expression, deallocating any existing sub expression.
Definition at line 411 of file parser_types.h.
References postOp().
Referenced by postOp().
 { if (mPostOp) delete mPostOp; mPostOp = postOp; }
ParseElement const* SimpleBinaryOperator::preOp () const inline
Definition at line 408 of file parser_types.h.
Referenced by aggregateUndefined(), copy(), determineQueryIPart(), fullName(), hasConstants(), hasLuaCalls(), isArithExpr(), isAtomicEq(), isDefinite(), isSingleAtom(), SimpleBinaryOperatorWrapper::preOp(), and translate().
 { return mPreOp; }
void SimpleBinaryOperator::preOp (ParseElement * postOp) inline
Definition at line 412 of file parser_types.h.
References postOp().
 { if (mPreOp) delete mPreOp; mPreOp = postOp; }
virtual std::ostream& SimpleBinaryOperator::translate (std::ostream & out, Context & context) const inline virtual
Method that generates a translated string representation of the element with preceeding @ if a symbol is understood as a lua function call.
Parameters
[out] out - The output stream to write to.
context - The formula context to be used for translation.
Returns
out.
Implements ParseElement.
Definition at line 378 of file parser_types.h.
References opType(), and translate().
Referenced by translate(), and SimpleBinaryOperatorWrapper::translate().
 { return translate(out, context, opType()); }
std::ostream & SimpleBinaryOperator::translate (std::ostream & out, Context & context, BinaryOperatorType type, bool forceParens = false) const protected
Translates the expression with the provided operator type.
Parameters
[out] out - The output stream to write to.
context - The formula context to be used for translation.
type - The operator type to use for the translation.
forceParens - Whether to force the presence of parens around the expression.
Returns
out.
Definition at line 398 of file parser_types.cpp.
References Translator::bindAndTranslate(), BOP_AND, BOP_BIND_STEP, BOP_DBL_EQ, BOP_DIVIDE, BOP_EQ, BOP_EQUIV, BOP_GTHAN, BOP_GTHAN_EQ, BOP_IMPL, BOP_LTHAN, BOP_LTHAN_EQ, BOP_MINUS, BOP_MOD, BOP_NEQ, BOP_PLUS, BOP_REV_IMPL, BOP_TIMES, ParseElement::getNewVar(), ParseElement::getType(), isAtomicEq(), ParseElement::PELEM_CONSTLIKE, postOp(), preOp(), SimpleBinaryOperator(), SimpleBinaryOperatorWrapper, ParseElement::translate(), translate(), ParseElement::translateAfterParen(), ParseElement::translateBeforeParen(), and translateOpType().
 {
     Context localContext;
     std::ostringstream tmp;
     std::string tmpstr;
     SimpleBinaryOperator* tmpOp;
     out << translateBeforeParen(forceParens);
     if (!preOp() && !postOp()) {
         // TODO: Throw error
         return out;
     } else if(!preOp()) {
         // If just preOp is NULL, pretend there's just postOp and translate it.
         postOp()->translate(out, context);
     } else if(!postOp()) {
         // If just postOp is NULL, pretend there's just preOp and translate it.
         preOp()->translate(out, context);
     }
     else
     {   // Then, perform different translations based on what the operator is.
         // Lack of breaks is intentional.
         switch(type) {
         case BOP_BIND_STEP:
             // This is an expression of the form X:F which binds F to have maximum step value X.
             localContext = context.mkPos(Context::POS_ARITHEXPR);
             preOp()->translate(tmp, localContext);
             tmpstr = tmp.str();
             localContext = context.mkTime(tmpstr);
             Translator::bindAndTranslate(out, postOp(), localContext, false);
             break;
         /* This special case isn't actually neccessary.
         case BOP_NEQ:
             // Special case. X\=Y <-> not (X==Y)
             out << "not (";
             tmpOp = new SimpleBinaryOperatorWrapper(this, BOP_EQ);
             localContext = context.mkNegated();
             Translator::bindAndTranslate(out, tmpOp, localContext, false);
             delete tmpOp;
             out << ")";
             break;
         */
         case BOP_EQ:
             if (isAtomicEq()) {
                 // special case, direct assignment to a constant...
                 // just translate the constant with the appropriate value.
                 localContext = context.mkPos(Context::POS_TERM);
                 postOp()->translate(tmp, localContext);
                 std::string tmpstr = tmp.str();
                 localContext = context.mkValue(tmpstr);
                 preOp()->translate(out, localContext);
                 break;
             } else if (preOp()->getType() == PELEM_CONSTLIKE && postOp()->getType() == PELEM_CONSTLIKE) {
                 // special case, equality between two constants.
                 // c=d is translated to (exists x)(c(x) & d(x))
                 // Setup the new variable
                 std::string tmpvar = getNewVar();
                 Sort const* domain = (((ConstantLikeElement const*)preOp())->domain()) ?
                         ((ConstantLikeElement const*)preOp())->domain()
                         : ((ConstantLikeElement const*)postOp())->domain();
                 context.addFreeVariable(tmpvar, domain);
                 localContext = context.mkValue(tmpvar);
                 // Make sure the constants are equal.
                 preOp()->translate(out, localContext);
                 out << " & ";
                 postOp()->translate(out, localContext);
                 break;
             }
             /* no break */
         case BOP_DBL_EQ:
         case BOP_NEQ:
         case BOP_PLUS:
         case BOP_MINUS:
         case BOP_TIMES:
         case BOP_DIVIDE:
         case BOP_MOD:
         case BOP_LTHAN:
         case BOP_GTHAN:
         case BOP_LTHAN_EQ:
         case BOP_GTHAN_EQ:
             // arithmetic expressions...
             if (context.getPos() == Context::POS_ARITHEXPR
                 || context.getPos() == Context::POS_TERM
                 || context.getPos() == Context::POS_MAXIMIZED_INTERNAL
                 || context.getPos() == Context::POS_CHOICE_RULE ) {
                 // Already inside an arithmetic expression.
                 // pass all the variables up to the highest arith-expr level.
                 preOp()->translate(out, context);
                 out << translateOpType(type);
                 postOp()->translate(out, context);
             } else {
                 // Entering an arithmetic expression
                 // Bind all of the local variables as we may need existential quantifiers.
                 localContext = context.mkPos(Context::POS_ARITHEXPR);
                 Translator::bindAndTranslate(out, this, localContext, true);
             }
             break;
         case BOP_EQUIV:
             // Special case: F <-> G
             // F2LP can't handle equivalence in general.
             // Translate to (F -> G) & (G -> F)
             // Setup the wrapper expression
             tmpOp = new SimpleBinaryOperator(
                     new SimpleBinaryOperatorWrapper(this, BOP_IMPL, true),
                     BOP_AND,
                     new SimpleBinaryOperatorWrapper(this, BOP_REV_IMPL, true)
             );
             // Translate
             tmpOp->translate(out, context);
             // Tear down
             delete tmpOp;
             break;
         case BOP_REV_IMPL:
             // Special case: F <- G.
             // Translate as G -> F.
             Translator::bindAndTranslate(out, postOp(), context, false);
             out << translateOpType(BOP_IMPL);
             Translator::bindAndTranslate(out, preOp(), context, false);
             break;
         default:
             // Logical operations...
             // If this isn't conjunction, then we want to capture local clauses for each term.
             // otherwise we'll just pass the clauses upward.
             if (type != BOP_AND && context.getPos() != Context::POS_HEAD && context.getPos() != Context::POS_CHOICE_RULE) {
                 // preop
                 Translator::bindAndTranslate(out, preOp(), context, false);
                 // operand
                 out << translateOpType(type);
                 // postOp
                 Translator::bindAndTranslate(out, postOp(), context, false);
             } else {
                 // conjunction (hopefully), just pass the clauses upward.
                 preOp()->translate(out, context);
                 out << translateOpType(type);
                 postOp()->translate(out, context);
             }
             break;
         }
     }
     out << translateAfterParen(forceParens);
     return out;
 }
std::string SimpleBinaryOperator::translateOpType (BinaryOperatorType op) static protected
Simple helper function.
Converts the provided operator to a string representation.
Parameters
op The operator to convert
Returns
A string corresponding to that operator.
Definition at line 743 of file parser_types.cpp.
References BOP_AND, BOP_DBL_EQ, BOP_DIVIDE, BOP_EQ, BOP_EQUIV, BOP_GTHAN, BOP_GTHAN_EQ, BOP_IMPL, BOP_LTHAN, BOP_LTHAN_EQ, BOP_MINUS, BOP_MOD, BOP_NEQ, BOP_OR, BOP_PLUS, and BOP_TIMES.
Referenced by fullName(), and translate().
{
     std::string opStr;
     switch(op)
     {
     case BOP_PLUS:
         opStr = " + ";
         break;
     case BOP_MINUS:
         opStr = " - ";
         break;
     case BOP_TIMES:
         opStr = " * ";
         break;
     case BOP_DIVIDE:
         opStr = " / ";
         break;
     case BOP_MOD:
         opStr = " \\ ";
         break;
     case BOP_AND:
         opStr = " & ";
         break;
     case BOP_OR:
         opStr = " | ";
         break;
     case BOP_EQUIV:
         opStr = " <--> ";
         break;
     case BOP_IMPL:
         opStr = " -> ";
         break;
     case BOP_EQ:
         opStr = " == ";
         break;
     case BOP_NEQ:
         opStr = " != ";
         break;
     case BOP_DBL_EQ:
         opStr = " == ";
         break;
     case BOP_LTHAN:
         opStr = " < ";
         break;
     case BOP_GTHAN:
         opStr = " > ";
         break;
     case BOP_LTHAN_EQ:
         opStr = " <= ";
         break;
     case BOP_GTHAN_EQ:
         opStr = " >= ";
         break;
     default:
         // Unknown, this is a problem...
         opStr = " BAD_OP ";
         break;
     }
     return opStr;
 }
Friends And Related Function Documentation
friend class SimpleBinaryOperatorWrapper friend
Definition at line 333 of file parser_types.h.
Referenced by translate().
The documentation for this class was generated from the following files:
cplus2asp.bin/old/parser_types.h
cplus2asp.bin/old/parser_types.cpp