cplus2asp: SimpleBinaryOperatorWrapper Class Reference
SimpleBinaryOperatorWrapper Class Reference
A simple (readonly) wrapper class to easily and efficiently change the operator.
#include <parser_types.h>
Public Member Functions
SimpleBinaryOperatorWrapper (SimpleBinaryOperator const *wrappedExpr, SimpleBinaryOperator::BinaryOperatorType type, bool forceParens=false)
Constructor.
virtual std::ostream & translate (std::ostream &out, Context &context) const
Method that generates a translated string representation of the element with preceeding @ if a symbol is understood as a lua function call.
virtual bool hasConstants (unsigned int types, bool includeParams=true, bool includeEq=true) const
Returns true if the element (or any of its children) are constants of the provided types.
virtual bool isDefinite (bool allowComparison=false, bool allowChoice=false, bool allowAtomicNegation=false) const
Determines if the element contains a single atom, a unary expression w/ a single atom, or a conjunction thereof.
virtual bool isSingleAtom (bool allowAtomicNegation=false) const
Whether the formula is a single atom.
virtual bool isArithExpr () const
Determines if the element is a valid arithmetic expression.
virtual bool hasLuaCalls (bool includeParams=true, bool includeEq=true) const
Determines if the element contains any calls to LUA.
virtual IPart determineQueryIPart () const
Determines the proper IPart to place the formula in.
virtual std::ostream & fullName (std::ostream &out) const
Prints the untranslated element string.
virtual ParseElement * copy () const
Returns an exact copy of the parse element.
virtual void aggregateUndefined (BaseElementList &outIdentifiers)
Aggregates all of the undefined identifiers (which are assumed to be constants).
SimpleBinaryOperator::BinaryOperatorType opType () const
Gets the operator's type.
void opType (SimpleBinaryOperator::BinaryOperatorType op)
Sets the operator's type.
ParseElement const * postOp () const
Gets the operator's sub expression.
ParseElement const * preOp () const
virtual ~SimpleBinaryOperatorWrapper ()
Destructor. Does nothing.
Public Member Functions inherited from ParseElement
ParseElement (ParseElementType elemType, bool parens=false)
Default constructor.
bool isTrivial (bool includeParams=true, bool includeEq=true) const
Determines if the element contains no (real) constants.
std::string fullName () const
Alternative helper to fullName(std::ostream&).
ParseElementType getType () const
Gets the type of the parse element.
void parens (bool parens)
Sets whether the expression is wrapped in parentheses.
bool parens () const
Gets whether the element is encompassed in parens.
virtual ~ParseElement ()
Destructor.
Additional Inherited Members
Public Types inherited from ParseElement
enum ParseElementType {
PELEM_PELEM, PELEM_UOP, PELEM_BOP, PELEM_QUANT,
PELEM_BASELIKE, PELEM_CONSTLIKE, PELEM_OBJLIKE, PELEM_VARLIKE
}
The possible types of a ParseElement instance.
enum ConstMask {
MASK_ACTION = 0x01, MASK_FLUENT = 0x02, MASK_RIGID = 0x04, MASK_STATIC_AB = 0x08,
MASK_DYNAMIC_AB = 0x10, MASK_TRUE_FALSE = 0x20, MASK_SDFLUENT = 0x40, MASK_AB = MASK_STATIC_AB | MASK_DYNAMIC_AB,
MASK_NON_TRIVIAL = ~MASK_TRUE_FALSE, MASK_NON_RIGID = MASK_NON_TRIVIAL & ~MASK_RIGID, MASK_NON_AB = MASK_NON_TRIVIAL & ~MASK_AB
}
Mask values for the various kinds of constants that can be in a formula.
Static Public Member Functions inherited from ParseElement
static std::string getNewVar ()
Gets a new variable whose name is unique within the rule we're translating.
Protected Member Functions inherited from ParseElement
bool hasParens () const
Determines if the element has parentheses around it.
std::string translateBeforeParen (bool forceParens=false) const
Helper to translate that intelligently handles the value of parenBefore.
std::string translateAfterParen (bool forceParens=false) const
Helper to translate that intelligently handles the value of parenAfter.
Detailed Description
A simple (readonly) wrapper class to easily and efficiently change the operator.
Definition at line 531 of file parser_types.h.
Constructor & Destructor Documentation
SimpleBinaryOperatorWrapper::SimpleBinaryOperatorWrapper (SimpleBinaryOperator const * wrappedExpr, SimpleBinaryOperator::BinaryOperatorType type, bool forceParens = false) inline
Constructor.
Parameters
wrappedExpr The expression to wrap.
type The new operator type.
forceParens Whether to force the presence of parens around the expression.
Definition at line 544 of file parser_types.h.
Referenced by copy().
         : ParseElement(wrappedExpr->getType(), wrappedExpr->parens()), mWrapped(wrappedExpr), mType(type), mForceParens(forceParens)
     { /* Intetionally Left Blank */ }
virtual SimpleBinaryOperatorWrapper::~SimpleBinaryOperatorWrapper () inline virtual
Destructor. Does nothing.
Definition at line 579 of file parser_types.h.
 { /* Intetionally Left Blank */ }
Member Function Documentation
virtual void SimpleBinaryOperatorWrapper::aggregateUndefined (BaseElementList & outIdentifiers) inline virtual
Aggregates all of the undefined identifiers (which are assumed to be constants).
Parameters
outIdentifiers The undefined identifiers.
Implements ParseElement.
Definition at line 563 of file parser_types.h.
 { /* Not Supported */ }
virtual ParseElement* SimpleBinaryOperatorWrapper::copy () const inline virtual
Returns an exact copy of the parse element.
Implements ParseElement.
Definition at line 562 of file parser_types.h.
References SimpleBinaryOperatorWrapper().
 { return new SimpleBinaryOperatorWrapper(mWrapped, mType, mForceParens); }
virtual IPart SimpleBinaryOperatorWrapper::determineQueryIPart () const inline virtual
Determines the proper IPart to place the formula in.
Returns
IPART_BASE if the formula is 0:(...), IPART_VOLATILE if the formula is X:(...), and IPART_CUMULATIVE if the formula is anything else.
Implements ParseElement.
Definition at line 559 of file parser_types.h.
References SimpleBinaryOperator::determineQueryIPart().
 { return mWrapped->determineQueryIPart(); }
virtual std::ostream& SimpleBinaryOperatorWrapper::fullName (std::ostream & out) const inline virtual
Prints the untranslated element string.
Parameters
out The output stream to print to.
Returns
out.
Implements ParseElement.
Definition at line 560 of file parser_types.h.
References SimpleBinaryOperator::fullName().
                                                                 { return mWrapped->fullName(out); }
virtual bool SimpleBinaryOperatorWrapper::hasConstants (unsigned int types, bool includeParams = true, bool includeEq = true) const inline virtual
Returns true if the element (or any of its children) are constants of the provided types.
Parameters
types A mask containing flags for the types to search for. See ConstMask enum.
includeParams Whether to check the parameters of constants.
includeEq Whether to check the right side of equality within an atom. (The right hand side of comparisons will be checked regardless.)
Returns
True if the element, or any elements "beneach" it, are constants, false otherwise.
Implements ParseElement.
Definition at line 551 of file parser_types.h.
References SimpleBinaryOperator::hasConstants().
                                                                 { return mWrapped->hasConstants(types, includeParams); }
virtual bool SimpleBinaryOperatorWrapper::hasLuaCalls (bool includeParams = true, bool includeEq = true) const inline virtual
Determines if the element contains any calls to LUA.
Parameters
includeParams Whether to search base element parameter lists.
includeEq Whether to check the right side of equality within an atom. (The right hand side of comparisons will be checked regardless.)
Returns
True if the element or any of its children is a LUA call.
Implements ParseElement.
Definition at line 557 of file parser_types.h.
References SimpleBinaryOperator::hasLuaCalls().
                                                                 { return mWrapped->hasLuaCalls(includeParams, includeEq); }
virtual bool SimpleBinaryOperatorWrapper::isArithExpr () const inline virtual
Determines if the element is a valid arithmetic expression.
Returns
True if the element and all it's children are arithmetic expressions.
Implements ParseElement.
Definition at line 556 of file parser_types.h.
References SimpleBinaryOperator::isArithExpr().
 { return mWrapped->isArithExpr(); }
virtual bool SimpleBinaryOperatorWrapper::isDefinite (bool allowComparison = false, bool allowChoice = false, bool allowAtomicNegation = false) const inline virtual
Determines if the element contains a single atom, a unary expression w/ a single atom, or a conjunction thereof.
Parameters
allowComparison Whether to allow comparison operators in the formula.
allowChoice Whether to allow choice rules in the formula.
allowAtomicNegation whether to allow -p or "not p" where p is a boolean atom.
Returns
True if the element is a definite formula.
Implements ParseElement.
Definition at line 553 of file parser_types.h.
References SimpleBinaryOperator::isDefinite().
             { return mWrapped->isDefinite(allowComparison, allowChoice, allowAtomicNegation); }
virtual bool SimpleBinaryOperatorWrapper::isSingleAtom (bool allowAtomicNegation = false) const inline virtual
Whether the formula is a single atom.
Returns
True if the element is a single atom c=v (or just c if c is boolean).
Parameters
allowAtomicNegation whether to allow -p or "not p" where p is a boolean atom.
Implements ParseElement.
Definition at line 555 of file parser_types.h.
References SimpleBinaryOperator::isSingleAtom().
 { return mWrapped->isSingleAtom(allowAtomicNegation); }
SimpleBinaryOperator::BinaryOperatorType SimpleBinaryOperatorWrapper::opType () const inline
Gets the operator's type.
Definition at line 566 of file parser_types.h.
Referenced by translate().
 { return mType; }
void SimpleBinaryOperatorWrapper::opType (SimpleBinaryOperator::BinaryOperatorType op) inline
Sets the operator's type.
Definition at line 569 of file parser_types.h.
 { mType = op; }
ParseElement const* SimpleBinaryOperatorWrapper::postOp () const inline
Gets the operator's sub expression.
Definition at line 574 of file parser_types.h.
References SimpleBinaryOperator::postOp().
 { return mWrapped->postOp(); }
ParseElement const* SimpleBinaryOperatorWrapper::preOp () const inline
Definition at line 575 of file parser_types.h.
References SimpleBinaryOperator::preOp().
 { return mWrapped->preOp(); }
virtual std::ostream& SimpleBinaryOperatorWrapper::translate (std::ostream & out, Context & context) const inline virtual
Method that generates a translated string representation of the element with preceeding @ if a symbol is understood as a lua function call.
Parameters
[out] out - The output stream to write to.
context - The formula context to be used for translation.
Returns
out.
Implements ParseElement.
Definition at line 549 of file parser_types.h.
References opType(), and SimpleBinaryOperator::translate().
                                                                 { return mWrapped->translate(out, context, opType(), mForceParens); }
The documentation for this class was generated from the following file:
cplus2asp.bin/old/parser_types.h