cplus2asp: ParseElement Class Reference
ParseElement Class Reference abstract
General parent of all self-contained, self-translating parse tree elements.
#include <parser_types.h>
Public Types
enum ParseElementType {
PELEM_PELEM, PELEM_UOP, PELEM_BOP, PELEM_QUANT,
PELEM_BASELIKE, PELEM_CONSTLIKE, PELEM_OBJLIKE, PELEM_VARLIKE
}
The possible types of a ParseElement instance.
enum ConstMask {
MASK_ACTION = 0x01, MASK_FLUENT = 0x02, MASK_RIGID = 0x04, MASK_STATIC_AB = 0x08,
MASK_DYNAMIC_AB = 0x10, MASK_TRUE_FALSE = 0x20, MASK_SDFLUENT = 0x40, MASK_AB = MASK_STATIC_AB | MASK_DYNAMIC_AB,
MASK_NON_TRIVIAL = ~MASK_TRUE_FALSE, MASK_NON_RIGID = MASK_NON_TRIVIAL & ~MASK_RIGID, MASK_NON_AB = MASK_NON_TRIVIAL & ~MASK_AB
}
Mask values for the various kinds of constants that can be in a formula.
Public Member Functions
ParseElement (ParseElementType elemType, bool parens=false)
Default constructor.
virtual std::ostream & translate (std::ostream &out, Context &context) const =0
Method that generates a translated string representation of the element with preceeding @ if a symbol is understood as a lua function call.
virtual bool hasConstants (unsigned int types, bool includeParams=true, bool includeEq=true) const =0
Returns true if the element (or any of its children) are constants of the provided types.
virtual bool isDefinite (bool allowComparison=false, bool allowChoice=false, bool allowAtomicNegation=false) const =0
Determines if the element contains a single atom, a unary expression w/ a single atom, or a conjunction thereof.
virtual bool isSingleAtom (bool allowAtomicNegation=false) const =0
Whether the formula is a single atom.
bool isTrivial (bool includeParams=true, bool includeEq=true) const
Determines if the element contains no (real) constants.
virtual bool isArithExpr () const =0
Determines if the element is a valid arithmetic expression.
virtual bool hasLuaCalls (bool includeParams=true, bool includeEq=true) const =0
Determines if the element contains any calls to LUA.
virtual IPart determineQueryIPart () const =0
Determines the proper IPart to place the formula in.
virtual std::ostream & fullName (std::ostream &out) const =0
Prints the untranslated element string.
virtual ParseElement * copy () const =0
Returns an exact copy of the parse element.
virtual void aggregateUndefined (BaseElementList &outIdentifiers)=0
Aggregates all of the undefined identifiers (which are assumed to be constants).
std::string fullName () const
Alternative helper to fullName(std::ostream&).
ParseElementType getType () const
Gets the type of the parse element.
void parens (bool parens)
Sets whether the expression is wrapped in parentheses.
bool parens () const
Gets whether the element is encompassed in parens.
virtual ~ParseElement ()
Destructor.
Static Public Member Functions
static std::string getNewVar ()
Gets a new variable whose name is unique within the rule we're translating.
Protected Member Functions
bool hasParens () const
Determines if the element has parentheses around it.
std::string translateBeforeParen (bool forceParens=false) const
Helper to translate that intelligently handles the value of parenBefore.
std::string translateAfterParen (bool forceParens=false) const
Helper to translate that intelligently handles the value of parenAfter.
Detailed Description
General parent of all self-contained, self-translating parse tree elements.
Empty except for the virtual translate function.
Definition at line 76 of file parser_types.h.
Member Enumeration Documentation
enum ParseElement::ConstMask
Mask values for the various kinds of constants that can be in a formula.
Enumerator
MASK_ACTION
MASK_FLUENT
MASK_RIGID
MASK_STATIC_AB
MASK_DYNAMIC_AB
MASK_TRUE_FALSE
MASK_SDFLUENT
MASK_AB
MASK_NON_TRIVIAL
MASK_NON_RIGID
MASK_NON_AB
Definition at line 83 of file parser_types.h.
                    {
         MASK_ACTION     = 0x01,
         MASK_FLUENT     = 0x02,
         MASK_RIGID      = 0x04,
         MASK_STATIC_AB  = 0x08,
         MASK_DYNAMIC_AB = 0x10,
         MASK_TRUE_FALSE = 0x20,
         MASK_SDFLUENT = 0x40,           // NOTE: sdFluent's are also contained within the FLUENT group.
         MASK_AB = MASK_STATIC_AB | MASK_DYNAMIC_AB,
         MASK_NON_TRIVIAL = ~MASK_TRUE_FALSE,
         MASK_NON_RIGID = MASK_NON_TRIVIAL & ~MASK_RIGID,
         MASK_NON_AB = MASK_NON_TRIVIAL & ~MASK_AB
     };
enum ParseElement::ParseElementType
The possible types of a ParseElement instance.
Enumerator
PELEM_PELEM
PELEM_UOP
PELEM_BOP
PELEM_QUANT
PELEM_BASELIKE
PELEM_CONSTLIKE
PELEM_OBJLIKE
PELEM_VARLIKE
Definition at line 80 of file parser_types.h.
 { PELEM_PELEM, PELEM_UOP, PELEM_BOP, PELEM_QUANT, PELEM_BASELIKE, PELEM_CONSTLIKE, PELEM_OBJLIKE, PELEM_VARLIKE };
Constructor & Destructor Documentation
ParseElement::ParseElement (ParseElementType elemType, bool parens = false) inline
Default constructor.
Sets elemType.
Parameters
elemType The type that the element is.
parens Whether to add parens around the element.
Definition at line 117 of file parser_types.h.
         : mQueryTimeStamp(""), mParens(parens), mElemType(elemType)
         { /* Intentionally Left Blank */ }
virtual ParseElement::~ParseElement () inline virtual
Destructor.
Empty.
Definition at line 219 of file parser_types.h.
 { /* Intentionally Left Blank */};
Member Function Documentation
virtual void ParseElement::aggregateUndefined (BaseElementList & outIdentifiers) pure virtual
Aggregates all of the undefined identifiers (which are assumed to be constants).
Parameters
outIdentifiers The undefined identifiers.
Implemented in BaseLikeElement, SimpleBinaryOperatorWrapper, BigQuantifiers, SimpleBinaryOperator, and SimpleUnaryOperator.
Referenced by SimpleUnaryOperator::aggregateUndefined(), SimpleBinaryOperator::aggregateUndefined(), BigQuantifiers::aggregateUndefined(), and Translator::translateCausalLaw().
virtual ParseElement* ParseElement::copy () const pure virtual
Returns an exact copy of the parse element.
Implemented in VariableLikeElement, ObjectLikeElement, ConstantLikeElement, BaseLikeElement, SimpleBinaryOperatorWrapper, BigQuantifiers, SimpleBinaryOperator, and SimpleUnaryOperator.
virtual IPart ParseElement::determineQueryIPart () const pure virtual
Determines the proper IPart to place the formula in.
Returns
IPART_BASE if the formula is 0:(...), IPART_VOLATILE if the formula is X:(...), and IPART_CUMULATIVE if the formula is anything else.
Implemented in VariableLikeElement, ObjectLikeElement, ConstantLikeElement, BaseLikeElement, SimpleBinaryOperatorWrapper, BigQuantifiers, SimpleBinaryOperator, and SimpleUnaryOperator.
Referenced by SimpleUnaryOperator::determineQueryIPart(), SimpleBinaryOperator::determineQueryIPart(), and BigQuantifiers::determineQueryIPart().
virtual std::ostream& ParseElement::fullName (std::ostream & out) const pure virtual
Prints the untranslated element string.
Parameters
out The output stream to print to.
Returns
out.
Implemented in BaseLikeElement, SimpleBinaryOperatorWrapper, BigQuantifiers, SimpleBinaryOperator, and SimpleUnaryOperator.
Referenced by SimpleBinaryOperator::determineQueryIPart(), SimpleUnaryOperator::fullName(), SimpleBinaryOperator::fullName(), BigQuantifiers::fullName(), SimpleUnaryOperator::translate(), Translator::translateCausalLaw(), Translator::translateCausesLaw(), Translator::translateConstraintLaw(), Translator::translateIncrementLaw(), Translator::translateMayCauseLaw(), and Translator::translateNonexecutableLaw().
std::string ParseElement::fullName () const inline
Alternative helper to fullName(std::ostream&).
Definition at line 202 of file parser_types.h.
References fullName().
Referenced by fullName(), ObjectLikeElement::isNumeric(), VariableLikeElement::translateAsConstant(), and ConstantLikeElement::translateAsVariable().
 { std::ostringstream ret; fullName(ret); return ret.str(); }
static std::string ParseElement::getNewVar () inline static
Gets a new variable whose name is unique within the rule we're translating.
Returns
The name of the new variable.
Definition at line 229 of file parser_types.h.
References utils::to_string().
Referenced by SimpleBinaryOperator::translate(), and ConstantLikeElement::translateAsVariable().
 { return std::string("X_Value_") + utils::to_string(sVarCount++); }
ParseElementType ParseElement::getType () const inline
Gets the type of the parse element.
Definition at line 205 of file parser_types.h.
Referenced by SimpleBinaryOperator::isAtomicEq(), SimpleUnaryOperator::isDefinite(), SimpleBinaryOperator::isDefinite(), SimpleUnaryOperator::isSingleAtom(), SimpleBinaryOperator::isSingleAtom(), SimpleUnaryOperator::translate(), SimpleBinaryOperator::translate(), Translator::translateConstraintLaw(), and Translator::translateIncrementLaw().
 { return mElemType; }
virtual bool ParseElement::hasConstants (unsigned int types, bool includeParams = true, bool includeEq = true) const pure virtual
Returns true if the element (or any of its children) are constants of the provided types.
Parameters
types A mask containing flags for the types to search for. See ConstMask enum.
includeParams Whether to check the parameters of constants.
includeEq Whether to check the right side of equality within an atom. (The right hand side of comparisons will be checked regardless.)
Returns
True if the element, or any elements "beneach" it, are constants, false otherwise.
Implemented in VariableLikeElement, ObjectLikeElement, ConstantLikeElement, BaseLikeElement, SimpleBinaryOperatorWrapper, BigQuantifiers, SimpleBinaryOperator, and SimpleUnaryOperator.
Referenced by SimpleUnaryOperator::hasConstants(), SimpleBinaryOperator::hasConstants(), BigQuantifiers::hasConstants(), SimpleBinaryOperator::isDefinite(), SimpleBinaryOperator::isSingleAtom(), isTrivial(), Translator::makeCausalTranslation(), Translator::makeShowStmt(), SimpleUnaryOperator::translate(), Translator::translateCausalLaw(), Translator::translateCausesLaw(), Translator::translateConstraintLaw(), Translator::translateIncrementLaw(), Translator::translateMayCauseLaw(), and Translator::translateNonexecutableLaw().
virtual bool ParseElement::hasLuaCalls (bool includeParams = true, bool includeEq = true) const pure virtual
Determines if the element contains any calls to LUA.
Parameters
includeParams Whether to search base element parameter lists.
includeEq Whether to check the right side of equality within an atom. (The right hand side of comparisons will be checked regardless.)
Returns
True if the element or any of its children is a LUA call.
Implemented in VariableLikeElement, ObjectLikeElement, ConstantLikeElement, BaseLikeElement, SimpleBinaryOperatorWrapper, BigQuantifiers, SimpleBinaryOperator, and SimpleUnaryOperator.
Referenced by SimpleUnaryOperator::hasLuaCalls(), SimpleBinaryOperator::hasLuaCalls(), BigQuantifiers::hasLuaCalls(), and Translator::translateCausalLaw().
bool ParseElement::hasParens () const inline protected
Determines if the element has parentheses around it.
Returns
True if the element has parentheses around it, false otherwise.
Definition at line 238 of file parser_types.h.
Referenced by translateAfterParen(), and translateBeforeParen().
 { return mParens; }
virtual bool ParseElement::isArithExpr () const pure virtual
Determines if the element is a valid arithmetic expression.
Returns
True if the element and all it's children are arithmetic expressions.
Implemented in BaseLikeElement, SimpleBinaryOperatorWrapper, BigQuantifiers, SimpleBinaryOperator, and SimpleUnaryOperator.
Referenced by SimpleUnaryOperator::isArithExpr(), SimpleBinaryOperator::isArithExpr(), and Translator::translateIncrementLaw().
virtual bool ParseElement::isDefinite (bool allowComparison = false, bool allowChoice = false, bool allowAtomicNegation = false) const pure virtual
Determines if the element contains a single atom, a unary expression w/ a single atom, or a conjunction thereof.
Parameters
allowComparison Whether to allow comparison operators in the formula.
allowChoice Whether to allow choice rules in the formula.
allowAtomicNegation whether to allow -p or "not p" where p is a boolean atom.
Returns
True if the element is a definite formula.
Implemented in VariableLikeElement, ObjectLikeElement, ConstantLikeElement, BaseLikeElement, SimpleBinaryOperatorWrapper, BigQuantifiers, SimpleBinaryOperator, and SimpleUnaryOperator.
Referenced by SimpleBinaryOperator::isDefinite(), and Translator::translateCausalLaw().
virtual bool ParseElement::isSingleAtom (bool allowAtomicNegation = false) const pure virtual
Whether the formula is a single atom.
Returns
True if the element is a single atom c=v (or just c if c is boolean).
Parameters
allowAtomicNegation whether to allow -p or "not p" where p is a boolean atom.
Implemented in VariableLikeElement, ObjectLikeElement, ConstantLikeElement, BaseLikeElement, SimpleBinaryOperatorWrapper, BigQuantifiers, SimpleBinaryOperator, and SimpleUnaryOperator.
Referenced by SimpleUnaryOperator::isDefinite(), and SimpleBinaryOperator::isSingleAtom().
bool ParseElement::isTrivial (bool includeParams = true, bool includeEq = true) const inline
Determines if the element contains no (real) constants.
(i.e. only "true" and/or "false").
Parameters
includeParams Whether we should check parameter lists.
includeEq Whether we should check atomic equality.
Returns
True if the only constants contained in the formula are "true" and "false".
Definition at line 162 of file parser_types.h.
References hasConstants(), and MASK_NON_TRIVIAL.
Referenced by Translator::translateCausalLaw().
 { return !hasConstants(MASK_NON_TRIVIAL, includeParams, includeEq); }
void ParseElement::parens (bool parens) inline
Sets whether the expression is wrapped in parentheses.
Parameters
parens Whether the expression should be wrapped in parentheses.
Definition at line 211 of file parser_types.h.
References parens().
Referenced by parens(), Translator::translateCausalLaw(), Translator::translateCausesLaw(), Translator::translateDefaultLaw(), Translator::translateIncrementLaw(), Translator::translateMayCauseLaw(), Translator::translateNonexecutableLaw(), and Translator::translatePossiblyCausedLaw().
 { this->mParens = parens; }
bool ParseElement::parens () const inline
Gets whether the element is encompassed in parens.
Definition at line 214 of file parser_types.h.
Referenced by SimpleUnaryOperator::copy(), SimpleBinaryOperator::copy(), BigQuantifiers::copy(), ConstantLikeElement::copy(), ObjectLikeElement::copy(), and VariableLikeElement::copy().
 { return mParens; }
virtual std::ostream& ParseElement::translate (std::ostream & out, Context & context) const pure virtual
Method that generates a translated string representation of the element with preceeding @ if a symbol is understood as a lua function call.
Parameters
[out] out - The output stream to write to.
context - The formula context to be used for translation.
Returns
out.
Implemented in VariableLikeElement, ObjectLikeElement, ConstantLikeElement, BaseLikeElement, SimpleBinaryOperatorWrapper, BigQuantifiers, SimpleBinaryOperator, and SimpleUnaryOperator.
Referenced by Translator::bindAndTranslate(), Translator::makeCausalTranslation(), Translator::makeShowStmt(), SimpleUnaryOperator::translate(), and SimpleBinaryOperator::translate().
std::string ParseElement::translateAfterParen (bool forceParens = false) const inline protected
Helper to translate that intelligently handles the value of parenAfter.
Parameters
forceParens Whether to force the presence of parens.
Returns
A blank string if parenAfter is false, ")" if it's true.
Definition at line 252 of file parser_types.h.
References hasParens().
Referenced by SimpleUnaryOperator::translate(), SimpleBinaryOperator::translate(), BigQuantifiers::translate(), ConstantLikeElement::translateAsConstant(), VariableLikeElement::translateAsConstant(), and VariableLikeElement::translateAsVariable().
 { return (hasParens() | forceParens) ? ")" : ""; }
std::string ParseElement::translateBeforeParen (bool forceParens = false) const inline protected
Helper to translate that intelligently handles the value of parenBefore.
Parameters
forceParens Whether to force the presence of parens.
Returns
A blank string if parenBefore is false, "(" if it's true.
Definition at line 245 of file parser_types.h.
References hasParens().
Referenced by SimpleUnaryOperator::translate(), SimpleBinaryOperator::translate(), BigQuantifiers::translate(), ConstantLikeElement::translateAsConstant(), VariableLikeElement::translateAsConstant(), and VariableLikeElement::translateAsVariable().
 { return (hasParens() | forceParens) ? "(" : ""; }
The documentation for this class was generated from the following files:
cplus2asp.bin/old/parser_types.h
cplus2asp.bin/old/parser_types.cpp