cplus2asp: bcplus::Location Class Reference
bcplus::Location Class Reference
A simple location structure.
#include <Location.h>
Public Member Functions
Location ()
Default constructor.
Location (ReferencedPath const *file, size_t line, size_t col)
Full constructor.
virtual ~Location ()
Destructor.
ReferencedPath const * file () const
Accessors.
size_t line () const
size_t col () const
void file (ReferencedPath const *f)
Mutators.
void line (size_t l)
void col (size_t c)
std::string filename () const
Generate the name of the file or use a placeholder if it's null.
void output (std::ostream &out) const
Output the location to the provided stream.
std::string str () const
Helper function for output to generate a string.
Detailed Description
A simple location structure.
Definition at line 16 of file Location.h.
Constructor & Destructor Documentation
bcplus::Location::Location ()
Default constructor.
Definition at line 11 of file Location.cpp.
     : _line(0), _col(0) {
     // intentionally left blank
 }
bcplus::Location::Location (ReferencedPath const * file, size_t line, size_t col)
Full constructor.
Definition at line 16 of file Location.cpp.
     : _file(file), _line(line), _col(col) {
     // intentionally left blank
 }
bcplus::Location::~Location () virtual
Destructor.
Definition at line 21 of file Location.cpp.
                     {
     // intentionally left blank
 }
Member Function Documentation
size_t bcplus::Location::col () const inline
Definition at line 36 of file Location.h.
Referenced by output(), and bcplus::parser::detail::ScannerBufferSource::ScannerBufferSource().
 { return _col; }
void bcplus::Location::col (size_t c) inline
Definition at line 41 of file Location.h.
 { _col = c; }
ReferencedPath const* bcplus::Location::file () const inline
Accessors.
Definition at line 34 of file Location.h.
Referenced by bcplus::parser::detail::MacroParser::_handle_include(), and bcplus::parser::detail::Scanner::readToken().
 { return _file; }
void bcplus::Location::file (ReferencedPath const * f) inline
Mutators.
Definition at line 39 of file Location.h.
 { _file = f; }
std::string bcplus::Location::filename () const
Generate the name of the file or use a placeholder if it's null.
Definition at line 25 of file Location.cpp.
Referenced by output().
{
     return (_file ? _file->native() : std::string("<NULL>"));
 }
size_t bcplus::Location::line () const inline
Definition at line 35 of file Location.h.
Referenced by output().
 { return _line; }
void bcplus::Location::line (size_t l) inline
Definition at line 40 of file Location.h.
 { _line = l; }
void bcplus::Location::output (std::ostream & out) const
Output the location to the provided stream.
Parameters
out The stream to write to.
Definition at line 29 of file Location.cpp.
References col(), filename(), and line().
Referenced by operator<<(), and str().
{
     out << "[" << filename() << ":" << line() << ":" << col() << "]";
 }
std::string bcplus::Location::str () const inline
Helper function for output to generate a string.
Definition at line 51 of file Location.h.
References output(), and str().
Referenced by str().
 { std::stringstream str; output(str); return str.str(); }
The documentation for this class was generated from the following files:
bcplusparser/include/bcplus/Location.h
bcplusparser/src/bcplus/Location.cpp