cplus2asp: cplus2asp::cplus2asp_bin::Context Class Reference
cplus2asp::cplus2asp_bin::Context Class Reference
A translation context container which gives information required during translation.
#include <Context.h>
Classes
struct Position
The various positions we can be working in.
Public Member Functions
Context (Configuration const *config, Position::type pos, IPart::type ipart, StatementList *preStatements=NULL, ClauseList *extraClauses=NULL, ClauseList *existsVars=NULL, bool neg=false, ReferencedString const *timestamp=NULL, VariableSubstitutionList const *subs=NULL)
Initialize a fresh context.
~Context ()
stub destructor
Context * mkPos (Position::type pos, bool negated=false)
Change the position of the context.
Context * mkPos (Position::type pos, IPart::type ipart, bool negated=false)
Change the position and incremental part of the context.
Context * mkTime (ReferencedString const *ts)
Change the timestamp of the context.
Context * mkBinds (ClauseList *extraClauses, ClauseList *existsList)
Change the clause / variable bindings.
Context * mkBindStmts (StatementList *preStatements)
Change the statement binding.
Context * mkVarSubstitutions (VariableSubstitutionList const &subs)
Add variable substitutations to the substitution list.
Configuration const * config ()
Get the system configuration.
Position::type pos () const
Get the position.
bool neg () const
Determine if the context is negated.
ReferencedString const * ts () const
Determine the timestamp that should be applied.
void addClause (std::string const &clause)
Append a clause to the list.
void addExists (std::string const &var)
Append a variable to the list of existentially quantified variables.
void addPreStmt (std::string const &stmt, IPart::type ipart)
Append a statement to the list.
ReferencedString const * getVarSubstitution (bcplus::symbols::VariableSymbol const *var) const
Get the string which should substitute the provided variable, or NULL if no such string has been defined.
IPart::type ipart () const
Get the active ipart for the translation.
Public Member Functions inherited from babb::utils::Referenced
Referenced ()
Referenced ()
Additional Inherited Members
Protected Member Functions inherited from babb::utils::Referenced
virtual ~Referenced ()
virtual ~Referenced ()
Detailed Description
A translation context container which gives information required during translation.
Definition at line 15 of file Context.h.
Constructor & Destructor Documentation
cplus2asp::cplus2asp_bin::Context::Context (Configuration const * config, Position::type pos, IPart::type ipart, StatementList * preStatements = NULL, ClauseList * extraClauses = NULL, ClauseList * existsVars = NULL, bool neg = false, ReferencedString const * timestamp = NULL, VariableSubstitutionList const * subs = NULL)
Initialize a fresh context.
Parameters
config The system wide configuration.
pos The position that the context occurs within
ipart The incremental part the translation is operating within.
preStatements A list to append prerequisite statements to
extraClauses A list to append extra clauses to
extraClauses A list to append existentially quantified variables to
neg Whether the context occurs within the scope of negation
timestamp The timestamp the formula refers to (null defaults to the configuration's DEFAULT or ZERO time depending on ipart).
Definition at line 11 of file Context.cpp.
References cplus2asp::cplus2asp_bin::IPart::BASE, config(), cplus2asp::cplus2asp_bin::IPart::CUMULATIVE, cplus2asp::cplus2asp_bin::IPart::NONE, cplus2asp::cplus2asp_bin::Configuration::TS::STATIC, cplus2asp::cplus2asp_bin::Configuration::ts(), cplus2asp::cplus2asp_bin::IPart::VOLATILE, and cplus2asp::cplus2asp_bin::Configuration::TS::ZERO.
Referenced by mkBinds(), mkBindStmts(), mkPos(), mkTime(), and mkVarSubstitutions().
     : _config(conf), _pos(pos), _neg(neg), _ts(timestamp), _extraClauses(extraClauses), _preStmts(preStatements), _existsVars(existsVars), _ipart(ipart) {
     if (subs) _subs.insert(subs->begin(), subs->end());
     if (!timestamp) {
         switch (ipart) {
         case IPart::CUMULATIVE:
         case IPart::VOLATILE:       _ts = config()->ts(Configuration::TS::STATIC);      break;
         case IPart::NONE:
         case IPart::BASE:
         default:                    _ts = config()->ts(Configuration::TS::ZERO);        break;
         }
     }
 }
cplus2asp::cplus2asp_bin::Context::~Context ()
stub destructor
Definition at line 28 of file Context.cpp.
                   {
     /* Intentionally left blank */
 }
Member Function Documentation
void cplus2asp::cplus2asp_bin::Context::addClause (std::string const & clause) inline
Append a clause to the list.
Definition at line 133 of file Context.h.
 { if (_extraClauses) _extraClauses->push_back(clause); }
void cplus2asp::cplus2asp_bin::Context::addExists (std::string const & var) inline
Append a variable to the list of existentially quantified variables.
Definition at line 136 of file Context.h.
 { if (_existsVars) _existsVars->push_back(var); }
void cplus2asp::cplus2asp_bin::Context::addPreStmt (std::string const & stmt, IPart::type ipart) inline
Append a statement to the list.
Definition at line 139 of file Context.h.
 { if (_preStmts) _preStmts->push_back(TranslationStatement(stmt, ipart)); }
Configuration const* cplus2asp::cplus2asp_bin::Context::config () inline
Get the system configuration.
Definition at line 121 of file Context.h.
Referenced by Context().
 { return _config; }
ReferencedString const* cplus2asp::cplus2asp_bin::Context::getVarSubstitution (bcplus::symbols::VariableSymbol const * var) const inline
Get the string which should substitute the provided variable, or NULL if no such string has been defined.
Definition at line 144 of file Context.h.
                                                                 { VariableSubstitutionList::const_iterator it = _subs.find(var);
                                                                   return (it != _subs.end() ? (it->second) : NULL); }
IPart::type cplus2asp::cplus2asp_bin::Context::ipart () const inline
Get the active ipart for the translation.
Definition at line 148 of file Context.h.
 { return _ipart; }
Context * cplus2asp::cplus2asp_bin::Context::mkBinds (ClauseList * extraClauses, ClauseList * existsList)
Change the clause / variable bindings.
Definition at line 45 of file Context.cpp.
References Context().
{
     return new Context(_config, _pos, _ipart, _preStmts, extraClauses, existsVars, _neg, _ts, &_subs);
 }
Context * cplus2asp::cplus2asp_bin::Context::mkBindStmts (StatementList * preStatements)
Change the statement binding.
Definition at line 49 of file Context.cpp.
References Context().
{
     return new Context(_config, _pos, _ipart, preStatements, _extraClauses, _existsVars, _neg, _ts, &_subs);
 }
Context * cplus2asp::cplus2asp_bin::Context::mkPos (Position::type pos, bool negated = false)
Change the position of the context.
Definition at line 32 of file Context.cpp.
References Context().
{
     return new Context(_config, pos, _ipart, _preStmts, _extraClauses, _existsVars, negated, _ts, &_subs);
 }
Context * cplus2asp::cplus2asp_bin::Context::mkPos (Position::type pos, IPart::type ipart, bool negated = false)
Change the position and incremental part of the context.
Definition at line 36 of file Context.cpp.
References Context().
{
     return new Context(_config, pos, ipart, _preStmts, _extraClauses, _existsVars, negated, _ts, &_subs);
 }
Context * cplus2asp::cplus2asp_bin::Context::mkTime (ReferencedString const * ts)
Change the timestamp of the context.
Definition at line 40 of file Context.cpp.
References Context().
{
     return new Context(_config, _pos, _ipart, _preStmts, _extraClauses, _existsVars, _neg, ts, &_subs);
 }
Context * cplus2asp::cplus2asp_bin::Context::mkVarSubstitutions (VariableSubstitutionList const & subs)
Add variable substitutations to the substitution list.
Definition at line 53 of file Context.cpp.
References Context().
{
     Context* ret = new Context(_config, _pos, _ipart, _preStmts, _extraClauses, _existsVars, _neg, _ts, &_subs);
     for(VariableSubstitutionList::const_iterator it = subs.begin(); it != subs.end(); it++) {
         ret->_subs[it->first] = it->second;
     }
     return ret;
 }
bool cplus2asp::cplus2asp_bin::Context::neg () const inline
Determine if the context is negated.
Definition at line 127 of file Context.h.
 { return _neg; }
Position::type cplus2asp::cplus2asp_bin::Context::pos () const inline
Get the position.
Definition at line 124 of file Context.h.
 { return _pos; }
ReferencedString const* cplus2asp::cplus2asp_bin::Context::ts () const inline
Determine the timestamp that should be applied.
Definition at line 130 of file Context.h.
 { return _ts; }
The documentation for this class was generated from the following files:
cplus2asp.bin/Context.h
cplus2asp.bin/Context.cpp