cplus2asp: bcplus::symbols::Symbol Class Reference
bcplus::symbols::Symbol Class Reference abstract
A base symbol class for building symbol tables.
#include <Symbol.h>
Classes
struct Type
Container for the types of symbols.
Public Member Functions
Symbol (Type::type type, babb::utils::ReferencedString const *base, size_t arity)
Basic Constructor.
Symbol (Type::type type, boost::property_tree::ptree const &node, std::ostream *err=NULL)
Attempts to load the symbol from the property tree node.
virtual ~Symbol ()
Destructor stub.
Type::type type () const
Get the symbol type.
char const * typeString () const
Get the symbol type as a cstring.
size_t arity () const
Get the arity of the symbol.
babb::utils::ReferencedString
const * base () const
Get the base name of the symbol.
babb::utils::ReferencedString
const * name () const
Get the full name of the symbol.
bool good () const
Determines if the symbol has been successfully loaded.
bool match (std::string const &b, size_t a) const
Determine if this symbol matches the provided detail.
bool match (std::string const &n) const
Determine if this symbol matches the provided detail.
Referenced * metadata () const
Get/set the metadata.
template<typename T >
T * metadata () const
Referenced * metadata ()
template<typename T >
T * metadata ()
void metadata (Referenced *data)
virtual bool operator== (Symbol const &other) const
Check to see if two symbols are equal.
bool operator!= (Symbol const &other) const
virtual void save (boost::property_tree::ptree &node) const
Outputs the symbol to the provided property tree node.
virtual DomainType::type domainType () const =0
Determine the domain type of this symbol.
Public Member Functions inherited from babb::utils::Referenced
Referenced ()
Referenced ()
Static Public Member Functions
static std::string genName (std::string const &base, size_t arity=0)
Generate the symbol's name from its base and arity.
Protected Member Functions
void good (bool l)
Set the good flag.
Protected Member Functions inherited from babb::utils::Referenced
virtual ~Referenced ()
virtual ~Referenced ()
Detailed Description
A base symbol class for building symbol tables.
Definition at line 19 of file Symbol.h.
Constructor & Destructor Documentation
bcplus::symbols::Symbol::Symbol (Type::type type, babb::utils::ReferencedString const * base, size_t arity)
Basic Constructor.
Parameters
type The type of symbol being instantiated
base The base name of the symbol
arity The arity of symbol
Definition at line 353 of file Symbol.cpp.
References genName().
     : _type(type), _arity(arity), _base(base), _good(true) {
     _name = new ReferencedString(genName(*base, arity));
     _metadata = NULL;
 }
bcplus::symbols::Symbol::Symbol (Type::type type, boost::property_tree::ptree const & node, std::ostream * err = NULL)
Attempts to load the symbol from the property tree node.
Parameters
type The type of symbol being instantiated
node The node to load the symbol from
err An error stream to write to or NULL. Sets the symbol's good flag if it was successful.
Definition at line 359 of file Symbol.cpp.
References arity(), base(), genName(), good(), and type().
{
     bool good = true;
     try {
         std::string base = node.get("<xmlattr>.base","");
         int arity = node.get("<xmlattr>.arity",0);
         if (base == "") {
             good = false;
             if (err) *err << "ERROR: Encountered malformed symbol declaration. Expected a 'base' attribute." << std::endl;
         }
         if (arity < 0) {
             good = false;
             if (err) *err << "ERROR: Encountered malformed symbol declaration. Expected an non-negative integer 'arity' attribute." << std::endl;
         }
         _type = type;
         _arity = (size_t)arity;
         _base = new ReferencedString(base);
         _name = new ReferencedString(genName(base, arity));
     } catch (boost::property_tree::ptree_error const& e) {
         good = false;
         if (err) *err << "ERROR: Encountered malformed symbol declaration. Expected an non-negative integer 'arity' attribute." << std::endl;
     }
     _good = good;
     _metadata = NULL;
 }
bcplus::symbols::Symbol::~Symbol () virtual
Destructor stub.
Definition at line 391 of file Symbol.cpp.
                 {
     /* Intentionally left blank */
 }
Member Function Documentation
size_t bcplus::symbols::Symbol::arity () const inline
Get the arity of the symbol.
Definition at line 108 of file Symbol.h.
Referenced by bcplus::symbols::detail::BaseSymbol::BaseSymbol(), bcplus::symbols::SymbolTable::create(), cplus2asp::cplus2asp_bin::Translator::epilogue(), bcplus::symbols::MacroSymbol::expand(), genName(), bcplus::symbols::MacroSymbol::MacroSymbol(), match(), operator==(), bcplus::symbols::detail::BaseSymbol::outputDefinition(), bcplus::symbols::MacroSymbol::outputDefinition(), bcplus::symbols::QuerySymbol::QuerySymbol(), save(), bcplus::symbols::SortSymbol::SortSymbol(), Symbol(), and bcplus::symbols::VariableSymbol::VariableSymbol().
 { return _arity; }
babb::utils::ReferencedString const* bcplus::symbols::Symbol::base () const inline
Get the base name of the symbol.
Definition at line 111 of file Symbol.h.
Referenced by bcplus::symbols::SymbolTable::create(), bcplus::symbols::SortSymbol::loadDefinition(), main(), match(), operator==(), bcplus::elements::CardinalityFormula::output(), bcplus::symbols::VariableSymbol::outputDefinition(), bcplus::symbols::QuerySymbol::outputDefinition(), bcplus::symbols::detail::BaseSymbol::outputDefinition(), bcplus::symbols::MacroSymbol::outputDefinition(), bcplus::symbols::SortSymbol::outputDefinition(), bcplus::symbols::SymbolTable::plus(), bcplus::symbols::QuerySymbol::QuerySymbol(), bcplus::symbols::VariableSymbol::save(), bcplus::symbols::detail::BaseSymbol::save(), save(), bcplus::symbols::SortSymbol::save(), bcplus::symbols::SortSymbol::SortSymbol(), Symbol(), cplus2asp::cplus2asp_bin::Translator::translate(), and bcplus::symbols::VariableSymbol::VariableSymbol().
 { return _base; }
virtual DomainType::type bcplus::symbols::Symbol::domainType () const pure virtual
Determine the domain type of this symbol.
Implemented in bcplus::symbols::SortSymbol, bcplus::symbols::ConstantSymbol, bcplus::symbols::MacroSymbol, bcplus::symbols::detail::BaseSymbol, bcplus::symbols::ObjectSymbol, bcplus::symbols::NumberRangeSymbol, bcplus::symbols::QuerySymbol, and bcplus::symbols::VariableSymbol.
std::string bcplus::symbols::Symbol::genName (std::string const & base, size_t arity = 0) static
Generate the symbol's name from its base and arity.
Definition at line 348 of file Symbol.cpp.
References arity().
Referenced by Symbol().
{
     return base + "/" + boost::lexical_cast<std::string>(arity);
 }
bool bcplus::symbols::Symbol::good () const inline
Determines if the symbol has been successfully loaded.
Definition at line 117 of file Symbol.h.
Referenced by bcplus::symbols::AttributeSymbol::AttributeSymbol(), bcplus::symbols::detail::BaseSymbol::BaseSymbol(), bcplus::symbols::ConstantSymbol::ConstantSymbol(), bcplus::symbols::SortSymbol::loadDefinition(), bcplus::symbols::MacroSymbol::MacroSymbol(), operator==(), bcplus::symbols::QuerySymbol::QuerySymbol(), bcplus::symbols::SortSymbol::SortSymbol(), Symbol(), and bcplus::symbols::VariableSymbol::VariableSymbol().
 { return _good; }
void bcplus::symbols::Symbol::good (bool l) inline protected
Set the good flag.
Definition at line 156 of file Symbol.h.
 { _good = l; }
bool bcplus::symbols::Symbol::match (std::string const & b, size_t a) const inline
Determine if this symbol matches the provided detail.
Parameters
b The base name to match against.
a The arity to match against
Definition at line 122 of file Symbol.h.
References arity(), and base().
                                                     {return (a == arity()) && (b == *base()); }
bool bcplus::symbols::Symbol::match (std::string const & n) const inline
Determine if this symbol matches the provided detail.
Parameters
n The full name of the symbol to match against (base/arity)
Definition at line 126 of file Symbol.h.
References name().
 { return n == *name(); }
Referenced* bcplus::symbols::Symbol::metadata () const inline
Get/set the metadata.
Definition at line 129 of file Symbol.h.
References babb::utils::ref_ptr< T >::get(), and babb::utils::Referenced::Referenced().
Referenced by cplus2asp::cplus2asp_bin::SortData::addTranslatedSubSort(), and cplus2asp::cplus2asp_bin::SortData::addTranslatedSuperSort().
 { return const_cast<Referenced*>(_metadata.get()); }
template<typename T > T* bcplus::symbols::Symbol::metadata () const inline
Definition at line 131 of file Symbol.h.
References babb::utils::ref_ptr< T >::get().
 { return const_cast<T*>((T const*)_metadata.get()); }
Referenced* bcplus::symbols::Symbol::metadata () inline
Definition at line 133 of file Symbol.h.
 { return _metadata; }
template<typename T > T* bcplus::symbols::Symbol::metadata () inline
Definition at line 135 of file Symbol.h.
 { return (T*)_metadata; }
void bcplus::symbols::Symbol::metadata (Referenced * data) inline
Definition at line 136 of file Symbol.h.
 { _metadata = data; }
babb::utils::ReferencedString const* bcplus::symbols::Symbol::name () const inline
Get the full name of the symbol.
Definition at line 114 of file Symbol.h.
Referenced by bcplus::symbols::AttributeSymbol::AttributeSymbol(), bcplus::symbols::detail::BaseSymbol::BaseSymbol(), bcplus::symbols::ConstantSymbol::ConstantSymbol(), bcplus::symbols::SymbolTable::create(), bcplus::symbols::MacroSymbol::MacroSymbol(), and match().
 { return _name; }
bool bcplus::symbols::Symbol::operator!= (Symbol const & other) const inline
Definition at line 144 of file Symbol.h.
 { return !(*this == other); }
bool bcplus::symbols::Symbol::operator== (Symbol const & other) const virtual
Check to see if two symbols are equal.
Parameters
other The other symbol to compare this one to
Returns
True if they are equal, false otherwise.
Reimplemented in bcplus::symbols::SortSymbol, bcplus::symbols::ConstantSymbol, bcplus::symbols::detail::BaseSymbol, bcplus::symbols::QuerySymbol, bcplus::symbols::AttributeSymbol, and bcplus::symbols::VariableSymbol.
Definition at line 395 of file Symbol.cpp.
References arity(), base(), good(), and type().
{
     if (!good() || !other.good()) return false;
     if (type() != other.type()) return false;
     if (arity() != other.arity()) return false;
     if (*base() != *(other.base())) return false;
     return true;
 }
void bcplus::symbols::Symbol::save (boost::property_tree::ptree & node) const virtual
Outputs the symbol to the provided property tree node.
Parameters
node The node to write to
Reimplemented in bcplus::symbols::SortSymbol, bcplus::symbols::ConstantSymbol, bcplus::symbols::MacroSymbol, bcplus::symbols::detail::BaseSymbol, bcplus::symbols::NumberRangeSymbol, bcplus::symbols::QuerySymbol, bcplus::symbols::AttributeSymbol, and bcplus::symbols::VariableSymbol.
Definition at line 403 of file Symbol.cpp.
References arity(), and base().
Referenced by bcplus::symbols::VariableSymbol::save(), bcplus::symbols::QuerySymbol::save(), bcplus::symbols::NumberRangeSymbol::save(), bcplus::symbols::detail::BaseSymbol::save(), bcplus::symbols::MacroSymbol::save(), and bcplus::symbols::SortSymbol::save().
{
     node.put("<xmlattr>.base", *base());
     if (arity()) node.put("<xmlattr>.arity", arity());
 }
Type::type bcplus::symbols::Symbol::type () const inline
Get the symbol type.
Definition at line 102 of file Symbol.h.
Referenced by bcplus::symbols::SymbolTable::create(), bcplus::elements::Element::newConstSet(), bcplus::elements::Element::newVarSet(), operator==(), Symbol(), cplus2asp::cplus2asp_bin::Translator::translate(), and typeString().
 { return _type; }
char const* bcplus::symbols::Symbol::typeString () const inline
Get the symbol type as a cstring.
Definition at line 105 of file Symbol.h.
References bcplus::symbols::Symbol::Type::cstr(), and type().
Referenced by bcplus::symbols::SymbolTable::create().
 { return Type::cstr(type()); }
The documentation for this class was generated from the following files:
bcplusparser/include/bcplus/symbols/Symbol.h
bcplusparser/src/bcplus/symbols/Symbol.cpp