cplus2asp: babb::utils::unsafe_ptr< T > Class Template Reference
babb::utils::unsafe_ptr< T > Class Template Reference
A lighter version of ref_ptr that can be used in unions (no constructor/destructor) This pointer assumes that a value is assigned when useage begins and NULL is assigned before usage ends.
#include <ref_ptr.h>
Public Member Functions
T * get () const
bool valid () const
operator T * () const
T * release ()
Release the memory location from this pointer without deallocating it.
unsafe_ptr< T > & operator= (T *other)
Assignment.
unsafe_ptr< T > & operator= (ref_ptr< T > const &other)
unsafe_ptr< T > & operator= (weak_ptr< T > const &other)
unsafe_ptr< T > & operator= (unsafe_ptr< T > const &other)
T & operator* () const
Dereference.
T * operator-> () const
T * get () const
bool valid () const
operator T * () const
T * release ()
Release the memory location from this pointer without deallocating it.
unsafe_ptr< T > & operator= (T *other)
Assignment.
unsafe_ptr< T > & operator= (ref_ptr< T > const &other)
unsafe_ptr< T > & operator= (weak_ptr< T > const &other)
unsafe_ptr< T > & operator= (unsafe_ptr< T > const &other)
T & operator* () const
Dereference.
T * operator-> () const
Detailed Description
template<typename T>
class babb::utils::unsafe_ptr< T >
A lighter version of ref_ptr that can be used in unions (no constructor/destructor) This pointer assumes that a value is assigned when useage begins and NULL is assigned before usage ends.
Parameters
T The type which it's referencing. Should ONLY be descendant of Reference.
Definition at line 10 of file ref_ptr.h.
Member Function Documentation
template<typename T> T* babb::utils::unsafe_ptr< T >::get () const inline
Definition at line 37 of file unsafe_ptr.h.
Referenced by babb::utils::weak_ptr< const bcplus::symbols::ObjectSymbol >::operator=(), and babb::utils::ref_ptr< bcplus::elements::detail::ElementClass >::operator=().
 { return _ptr; }
template<typename T> T* babb::utils::unsafe_ptr< T >::get () const inline
Definition at line 37 of file unsafe_ptr.h.
 { return _ptr; }
template<typename T> babb::utils::unsafe_ptr< T >::operator T * () const inline
Definition at line 41 of file unsafe_ptr.h.
 { return _ptr; }
template<typename T> babb::utils::unsafe_ptr< T >::operator T * () const inline
Definition at line 41 of file unsafe_ptr.h.
 { return _ptr; }
template<typename T> T& babb::utils::unsafe_ptr< T >::operator* () const inline
Dereference.
Definition at line 86 of file unsafe_ptr.h.
{
         return *_ptr;
     }
template<typename T> T& babb::utils::unsafe_ptr< T >::operator* () const inline
Dereference.
Definition at line 86 of file unsafe_ptr.h.
{
         return *_ptr;
     }
template<typename T> T* babb::utils::unsafe_ptr< T >::operator-> () const inline
Definition at line 90 of file unsafe_ptr.h.
{
         return _ptr;
     }
template<typename T> T* babb::utils::unsafe_ptr< T >::operator-> () const inline
Definition at line 90 of file unsafe_ptr.h.
{
         return _ptr;
     }
template<typename T> unsafe_ptr<T>& babb::utils::unsafe_ptr< T >::operator= (T * other) inline
Assignment.
Definition at line 55 of file unsafe_ptr.h.
{
         if (_ptr == other) return *this;
         //  Make sure to remove the reference from the current pointer.
         if (_ptr && !_ptr->_unref()) {
             delete _ptr;
         }
         _ptr = other;
         if (_ptr) _ptr->_ref();
         return *this;
     }
template<typename T> unsafe_ptr<T>& babb::utils::unsafe_ptr< T >::operator= (T * other) inline
Assignment.
Definition at line 55 of file unsafe_ptr.h.
{
         if (_ptr == other) return *this;
         //  Make sure to remove the reference from the current pointer.
         if (_ptr && !_ptr->_unref()) {
             delete _ptr;
         }
         _ptr = other;
         if (_ptr) _ptr->_ref();
         return *this;
     }
template<typename T> unsafe_ptr<T>& babb::utils::unsafe_ptr< T >::operator= (ref_ptr< T > const & other) inline
Definition at line 68 of file unsafe_ptr.h.
References babb::utils::ref_ptr< T >::get().
{
         return *this = other.get();
     }
template<typename T> unsafe_ptr<T>& babb::utils::unsafe_ptr< T >::operator= (ref_ptr< T > const & other) inline
Definition at line 68 of file unsafe_ptr.h.
References babb::utils::ref_ptr< T >::get().
{
         return *this = other.get();
     }
template<typename T> unsafe_ptr<T>& babb::utils::unsafe_ptr< T >::operator= (weak_ptr< T > const & other) inline
Definition at line 72 of file unsafe_ptr.h.
References babb::utils::weak_ptr< T >::get().
{
         return *this = other.get();
     }
template<typename T> unsafe_ptr<T>& babb::utils::unsafe_ptr< T >::operator= (weak_ptr< T > const & other) inline
Definition at line 72 of file unsafe_ptr.h.
References babb::utils::weak_ptr< T >::get().
{
         return *this = other.get();
     }
template<typename T> unsafe_ptr<T>& babb::utils::unsafe_ptr< T >::operator= (unsafe_ptr< T > const & other) inline
Definition at line 76 of file unsafe_ptr.h.
{
         return *this = other.get();
     }
template<typename T> unsafe_ptr<T>& babb::utils::unsafe_ptr< T >::operator= (unsafe_ptr< T > const & other) inline
Definition at line 76 of file unsafe_ptr.h.
{
         return *this = other.get();
     }
template<typename T> T* babb::utils::unsafe_ptr< T >::release () inline
Release the memory location from this pointer without deallocating it.
Definition at line 44 of file unsafe_ptr.h.
{
         if (!_ptr) return NULL;
         _ptr->_unref();
         _ptr = NULL;
     }
template<typename T> T* babb::utils::unsafe_ptr< T >::release () inline
Release the memory location from this pointer without deallocating it.
Definition at line 44 of file unsafe_ptr.h.
{
         if (!_ptr) return NULL;
         _ptr->_unref();
         _ptr = NULL;
     }
template<typename T> bool babb::utils::unsafe_ptr< T >::valid () const inline
Definition at line 38 of file unsafe_ptr.h.
 { return _ptr != NULL; }
template<typename T> bool babb::utils::unsafe_ptr< T >::valid () const inline
Definition at line 38 of file unsafe_ptr.h.
 { return _ptr != NULL; }
The documentation for this class was generated from the following files:
as2transition/include/babb/utils/memory/ref_ptr.h
as2transition/include/babb/utils/memory/unsafe_ptr.h