cplus2asp: as2transition::Config Class Reference
as2transition::Config Class Reference
#include <Config.h>
Classes
struct PredFormat
struct PredType
struct Solver
Public Member Functions
Config (int showmask, PredFormat::type format, ReferencedString const *noneAlias=NULL, bool stripSanitization=true, bool stripPrefix=false, bool separateExternal=true, bool separateActions=true, bool onePredPerLine=false)
Basic Constructor.
Config (Config const &other)
Copy constructor...
~Config ()
Basic Destructor.
int showmask () const
Get/set the showmask.
void showmask (int m)
bool show (int predmask) const
Determine whether or not to show a predicate based on the current showmask.
PredFormat::type format () const
Get/set the format.
void format (PredFormat::type f)
ReferencedString const * noneAlias () const
Get/set the none Alias.
void noneAlias (ReferencedString const *na)
bool stripSanitization () const
Get/set whether we should strip "saniObj_" and "saniConst_" from the base element names.
void stripSanitization (bool s)
bool stripPrefix () const
Get/set whether we should strip "o_" and "c_x_x_" from the base element names.
void stripPrefix (bool s)
bool separateExternal () const
Get/set whether we should separate external constants...
void separateExternal (bool s)
bool separateActions () const
Get/set whether we should separate actions.
void separateActions (bool s)
bool onePredPerLine () const
Get/set whether we should print each predicate on its own line.
void onePredPerLine (bool s)
Solver::type solver () const
Get/set the current solver we're working with.
void solver (Solver::type t)
Public Member Functions inherited from babb::utils::Referenced
Referenced ()
Referenced ()
Additional Inherited Members
Protected Member Functions inherited from babb::utils::Referenced
virtual ~Referenced ()
virtual ~Referenced ()
Detailed Description
Definition at line 9 of file Config.h.
Constructor & Destructor Documentation
Config::Config (int showmask, PredFormat::type format, ReferencedString const * noneAlias = NULL, bool stripSanitization = true, bool stripPrefix = false, bool separateExternal = true, bool separateActions = true, bool onePredPerLine = false)
Basic Constructor.
Parameters
showmask A mask of predicate types to display
format The format to put each predicate in
noneAlias A string to replace to replace with "none" or NULL
stripSanitization Whether we should strip "saniObj_" and "saniConst_" from base element names
stripPrefix Whether we should strip "o_" and "c_x_x_" from base element names.
separateExternal Whether we should separate external constants from their internal counterpart.
separateActions Whether we should separate actions from fluents
onePredPerLine Whether we should print each predicate on its own line
Definition at line 10 of file Config.cpp.
     : _showmask(showmask), _format(format), _stripSanitization(stripSanitization),
       _stripPrefix(stripPrefix), _noneAlias(noneAlias), _separateExternal(separateExternal),
       _separateActions(separateActions), _solver(Solver::UNKNOWN) {
     // intentionally left blank
 }
Config::Config (Config const & other)
Copy constructor...
Definition at line 19 of file Config.cpp.
     : _showmask(other._showmask), _format(other._format), _stripSanitization(other._stripSanitization),
       _stripPrefix(other._stripPrefix), _noneAlias(other._noneAlias), _separateExternal(other._separateExternal),
       _separateActions(other._separateActions), _solver(other._solver) {
     // Intentionally left blank
 }
Config::~Config ()
Basic Destructor.
Definition at line 28 of file Config.cpp.
                 {
     // intentionally left blank
 }
Member Function Documentation
PredFormat::type as2transition::Config::format () const inline
Get/set the format.
Definition at line 116 of file Config.h.
Referenced by as2transition::Predicate::format(), and as2transition::TransitionFormatter::setOption().
 { return _format; }
void as2transition::Config::format (PredFormat::type f) inline
Definition at line 117 of file Config.h.
 { _format = f; }
ReferencedString const* as2transition::Config::noneAlias () const inline
Get/set the none Alias.
Definition at line 120 of file Config.h.
Referenced by as2transition::PredElement::format(), and as2transition::TransitionFormatter::setOption().
 { return _noneAlias; }
void as2transition::Config::noneAlias (ReferencedString const * na) inline
Definition at line 121 of file Config.h.
 { _noneAlias = na; }
bool as2transition::Config::onePredPerLine () const inline
Get/set whether we should print each predicate on its own line.
Definition at line 140 of file Config.h.
Referenced by as2transition::TransitionFormatter::setOption().
 { return _onePredPerLine; }
void as2transition::Config::onePredPerLine (bool s) inline
Definition at line 141 of file Config.h.
 { _onePredPerLine = s; }
bool as2transition::Config::separateActions () const inline
Get/set whether we should separate actions.
Definition at line 136 of file Config.h.
Referenced by as2transition::TransitionFormatter::setOption().
 { return _separateActions; }
void as2transition::Config::separateActions (bool s) inline
Definition at line 137 of file Config.h.
 { _separateActions = s; }
bool as2transition::Config::separateExternal () const inline
Get/set whether we should separate external constants...
Definition at line 132 of file Config.h.
Referenced by as2transition::TransitionFormatter::setOption().
 { return _separateExternal; }
void as2transition::Config::separateExternal (bool s) inline
Definition at line 133 of file Config.h.
 { _separateExternal = s; }
bool as2transition::Config::show (int predmask) const inline
Determine whether or not to show a predicate based on the current showmask.
Definition at line 113 of file Config.h.
References showmask().
Referenced by as2transition::Predicate::format().
 { return !(predmask & ~showmask()); }
int as2transition::Config::showmask () const inline
Get/set the showmask.
Definition at line 109 of file Config.h.
Referenced by as2transition::TransitionFormatter::setOption(), and show().
 { return _showmask; }
void as2transition::Config::showmask (int m) inline
Definition at line 110 of file Config.h.
 { _showmask = m; }
Solver::type as2transition::Config::solver () const inline
Get/set the current solver we're working with.
Definition at line 144 of file Config.h.
 { return _solver; }
void as2transition::Config::solver (Solver::type t) inline
Definition at line 145 of file Config.h.
 { _solver = t; }
bool as2transition::Config::stripPrefix () const inline
Get/set whether we should strip "o_" and "c_x_x_" from the base element names.
Definition at line 128 of file Config.h.
Referenced by cplus2asp::bcbridge::Driver::Driver(), as2transition::PredElement::format(), and as2transition::TransitionFormatter::setOption().
 { return _stripPrefix; }
void as2transition::Config::stripPrefix (bool s) inline
Definition at line 129 of file Config.h.
 { _stripPrefix = s; }
bool as2transition::Config::stripSanitization () const inline
Get/set whether we should strip "saniObj_" and "saniConst_" from the base element names.
Definition at line 124 of file Config.h.
Referenced by as2transition::PredElement::format(), and as2transition::TransitionFormatter::setOption().
 { return _stripSanitization; }
void as2transition::Config::stripSanitization (bool s) inline
Definition at line 125 of file Config.h.
 { _stripSanitization = s; }
The documentation for this class was generated from the following files:
as2transition/include/as2transition/Config.h
as2transition/src/as2transition/Config.cpp