cplus2asp: bcplus::symbols::SortSymbol Class Reference
bcplus::symbols::SortSymbol Class Reference
#include <SortSymbol.h>
Public Types
typedef ReferencedSet
< babb::utils::ref_ptr< const
ObjectSymbol > >::type ObjectList
List of object symbols in this sort.
typedef ReferencedSet
< babb::utils::ref_ptr< const
Symbol > >::type RangeList
List of range symbols in this sort.
typedef ObjectList::iterator iterator
Object list iterators.
typedef ObjectList::const_iterator const_iterator
typedef ReferencedSet
< babb::utils::weak_ptr
< SortSymbol > >::type SortList
List of sorts.
Public Member Functions
SortSymbol (ReferencedString const *name, ObjectList *objects=NULL, SortList *subsorts=NULL, RangeList *ranges=NULL)
Basic constructor.
SortSymbol (boost::property_tree::ptree const &node, std::ostream *err=NULL)
Loads the sort from the property tree node.
virtual ~SortSymbol ()
Destructor stub.
const_iterator begin () const
Gets an iterator for the beginning of the object list.
const_iterator end () const
Gets an iterator for the end of the object list.
RangeList::const_iterator beginRanges () const
Gets an iterator for the begginning of the range list.
RangeList::const_iterator endRanges () const
Gets an iterator for the end of the range list.
size_t size () const
Gets the number of elements in the sort.
SortList::const_iterator beginSuperSorts () const
Gets an iterator for the super sorts.
SortList::const_iterator endSuperSorts () const
SortList::iterator beginSuperSorts ()
SortList::iterator endSuperSorts ()
size_t numSuperSorts () const
Get the number of registered super sorts.
SortList::const_iterator beginSubSorts () const
Gets an iterator for the sub sorts.
SortList::const_iterator endSubSorts () const
SortList::iterator beginSubSorts ()
SortList::iterator endSubSorts ()
size_t numSubSorts () const
Get the number of registered subsorts.
bool add (ObjectSymbol const *obj)
Add an object or range symbol to the list of objects.
bool add (NumberRangeSymbol const *obj)
bool contains (ObjectSymbol const *obj) const
Determines if an object or range symbol is in the wort.
bool contains (NumberRangeSymbol const *r) const
bool addSuperSort (SortSymbol *super)
Adds a sort symbol as a superset to this one.
bool addSubSort (SortSymbol *sub)
Adds a sort symbol as a subset to this one.
bool loadDefinition (boost::property_tree::ptree const &node, Resolver *resolver, std::ostream *err=NULL)
Completely loads the sort including initializing subsorts and member objects NOTE: This may fail if member objects refer to a sort not yet instantiated.
virtual bool operator== (Symbol const &other) const
Check to see if two symbols are equal.
virtual void save (boost::property_tree::ptree &node) const
Outputs the symbol to the provided property tree node.
virtual void outputDefinition (std::ostream &out) const
virtual DomainType::type domainType () const
Determine the domain type of this symbol.
Public Member Functions inherited from bcplus::symbols::Symbol
Symbol (Type::type type, babb::utils::ReferencedString const *base, size_t arity)
Basic Constructor.
Symbol (Type::type type, boost::property_tree::ptree const &node, std::ostream *err=NULL)
Attempts to load the symbol from the property tree node.
virtual ~Symbol ()
Destructor stub.
Type::type type () const
Get the symbol type.
char const * typeString () const
Get the symbol type as a cstring.
size_t arity () const
Get the arity of the symbol.
babb::utils::ReferencedString
const * base () const
Get the base name of the symbol.
babb::utils::ReferencedString
const * name () const
Get the full name of the symbol.
bool good () const
Determines if the symbol has been successfully loaded.
bool match (std::string const &b, size_t a) const
Determine if this symbol matches the provided detail.
bool match (std::string const &n) const
Determine if this symbol matches the provided detail.
Referenced * metadata () const
Get/set the metadata.
template<typename T >
T * metadata () const
Referenced * metadata ()
template<typename T >
T * metadata ()
void metadata (Referenced *data)
bool operator!= (Symbol const &other) const
Public Member Functions inherited from babb::utils::Referenced
Referenced ()
Referenced ()
Additional Inherited Members
Static Public Member Functions inherited from bcplus::symbols::Symbol
static std::string genName (std::string const &base, size_t arity=0)
Generate the symbol's name from its base and arity.
Protected Member Functions inherited from bcplus::symbols::Symbol
void good (bool l)
Set the good flag.
Protected Member Functions inherited from babb::utils::Referenced
virtual ~Referenced ()
virtual ~Referenced ()
Detailed Description
Definition at line 22 of file SortSymbol.h.
Member Typedef Documentation
typedef ObjectList::const_iterator bcplus::symbols::SortSymbol::const_iterator
Definition at line 36 of file SortSymbol.h.
typedef ObjectList::iterator bcplus::symbols::SortSymbol::iterator
Object list iterators.
Definition at line 35 of file SortSymbol.h.
typedef ReferencedSet<babb::utils::ref_ptr<const ObjectSymbol> >::type bcplus::symbols::SortSymbol::ObjectList
List of object symbols in this sort.
Definition at line 29 of file SortSymbol.h.
typedef ReferencedSet<babb::utils::ref_ptr<const Symbol> >::type bcplus::symbols::SortSymbol::RangeList
List of range symbols in this sort.
Definition at line 32 of file SortSymbol.h.
typedef ReferencedSet<babb::utils::weak_ptr<SortSymbol> >::type bcplus::symbols::SortSymbol::SortList
List of sorts.
Definition at line 39 of file SortSymbol.h.
Constructor & Destructor Documentation
bcplus::symbols::SortSymbol::SortSymbol (ReferencedString const * name, ObjectList * objects = NULL, SortList * subsorts = NULL, RangeList * ranges = NULL)
Basic constructor.
Parameters
base The name of the sort
objects The objects within the sort
subsorts A list of sorts that this sort fully encompasses
ranges A list of numeric ranges contained within this sort.
Definition at line 21 of file SortSymbol.cpp.
References addSuperSort(), bcplus::symbols::ObjectSymbol::domainType(), domainType(), bcplus::DomainType::NO_DOMAIN, and bcplus::DomainType::OTHER.
Referenced by loadDefinition().
     : Symbol(Symbol::Type::SORT, base, 0) {
     if (!objects) _objects = new ObjectList();
     else _objects = objects;
     _supersorts = new SortList();
     if (!subsorts) _subsorts = new SortList();
     else {
         _subsorts = subsorts;
         BOOST_FOREACH(SortSymbol* sort, *_subsorts) {
             sort->addSuperSort(this);
         }
     }
     if (!ranges) _ranges = new RangeList();
     else _ranges = ranges;
     _dt = DomainType::NO_DOMAIN;
     BOOST_FOREACH(ObjectSymbol const* obj, *_objects) {
         if (_dt == DomainType::NO_DOMAIN) _dt = obj->domainType();
         else if (_dt != obj->domainType()) _dt = DomainType::OTHER;
     }
     BOOST_FOREACH(Symbol const* r, *_ranges) {
         if (_dt == DomainType::NO_DOMAIN) _dt = ((NumberRangeSymbol const*)r)->domainType();
         else if (_dt != ((NumberRangeSymbol const*)r)->domainType()) _dt = DomainType::OTHER;
     }
 }
bcplus::symbols::SortSymbol::SortSymbol (boost::property_tree::ptree const & node, std::ostream * err = NULL)
Loads the sort from the property tree node.
Parameters
node The node to load the symbol from
err An error stream to write to (or NULL) Sets the symbol's good flag if it was successful NOTE: This just initializes the sort, it does not load any of the objects or subsorts, see {loadDefinition}.
Definition at line 51 of file SortSymbol.cpp.
References bcplus::symbols::Symbol::arity(), bcplus::symbols::Symbol::base(), bcplus::symbols::Symbol::good(), and bcplus::DomainType::NO_DOMAIN.
     : Symbol(Symbol::Type::SORT, node, err) {
     _objects = new ObjectList();
     _supersorts = new SortList();
     _subsorts = new SortList();
     _ranges = new RangeList();
     _dt = DomainType::NO_DOMAIN;
     // Ensure arity = 0 for sorts
     if (good() && arity()) {
         good(false);
         if (err) *err << "ERROR: Sort \"" << *base() << "\" cannot be declared with non-zero arity." << std::endl;
     }
 }
bcplus::symbols::SortSymbol::~SortSymbol () virtual
Destructor stub.
Definition at line 69 of file SortSymbol.cpp.
{
     // Intentionally left blank
 }
Member Function Documentation
bool bcplus::symbols::SortSymbol::add (ObjectSymbol const * obj)
Add an object or range symbol to the list of objects.
Returns
True if successful, false if the object was already in the sort.
Definition at line 73 of file SortSymbol.cpp.
References add(), bcplus::symbols::ObjectSymbol::domainType(), bcplus::DomainType::NO_DOMAIN, and bcplus::DomainType::OTHER.
Referenced by add(), addSuperSort(), and loadDefinition().
{
     if (_objects->insert(obj).second) {
         // update domain type
         if (_dt == DomainType::NO_DOMAIN) _dt = obj->domainType();
         else if (_dt != obj->domainType()) _dt = DomainType::OTHER;
         // update any supersorts
         BOOST_FOREACH(SortSymbol* sort, *_supersorts) {
             sort->add(obj);
         }
         return true;
     } else return false;
 }
bool bcplus::symbols::SortSymbol::add (NumberRangeSymbol const * obj)
Definition at line 87 of file SortSymbol.cpp.
References add(), bcplus::symbols::NumberRangeSymbol::domainType(), bcplus::DomainType::NO_DOMAIN, and bcplus::DomainType::OTHER.
{
     if (_ranges->insert(r).second) {
         // update domain type
         if (_dt == DomainType::NO_DOMAIN) _dt = r->domainType();
         else if (_dt != r->domainType()) _dt = DomainType::OTHER;
         // update any supersorts
         BOOST_FOREACH(SortSymbol* sort, *_supersorts) {
             sort->add(r);
         }
         return true;
     } else return false;
 }
bool bcplus::symbols::SortSymbol::addSubSort (SortSymbol * sub)
Adds a sort symbol as a subset to this one.
Parameters
sub The sort to add as a subset.
Returns
True if successful, false if the sort was already a subsort of this one
Definition at line 117 of file SortSymbol.cpp.
References addSuperSort().
Referenced by addSuperSort(), and loadDefinition().
{
     if (_subsorts->insert(sub).second) {
         sub->addSuperSort(this);
         return true;
     } else return false;
 }
bool bcplus::symbols::SortSymbol::addSuperSort (SortSymbol * super)
Adds a sort symbol as a superset to this one.
Parameters
super The sort to add as a superset.
Returns
True if successful, false if the sort was already a supersort of this one
Definition at line 101 of file SortSymbol.cpp.
References add(), and addSubSort().
Referenced by addSubSort(), and SortSymbol().
{
     if (_supersorts->insert(super).second) {
         super->addSubSort(this);
         // update the supersort's objects
         BOOST_FOREACH(ObjectSymbol const* obj, *_objects) {
             super->add(obj);
         }
         BOOST_FOREACH(Symbol const* r, *_ranges) {
             super->add((NumberRangeSymbol const*)r);
         }
         return true;
     } else return false;
 }
const_iterator bcplus::symbols::SortSymbol::begin () const inline
Gets an iterator for the beginning of the object list.
Definition at line 89 of file SortSymbol.h.
Referenced by operator==().
 { return _objects->begin(); }
RangeList::const_iterator bcplus::symbols::SortSymbol::beginRanges () const inline
Gets an iterator for the begginning of the range list.
Definition at line 95 of file SortSymbol.h.
Referenced by operator==().
 { return _ranges->begin(); }
SortList::const_iterator bcplus::symbols::SortSymbol::beginSubSorts () const inline
Gets an iterator for the sub sorts.
Definition at line 113 of file SortSymbol.h.
Referenced by operator==().
 { return _subsorts->begin(); }
SortList::iterator bcplus::symbols::SortSymbol::beginSubSorts () inline
Definition at line 115 of file SortSymbol.h.
 { return _subsorts->begin(); }
SortList::const_iterator bcplus::symbols::SortSymbol::beginSuperSorts () const inline
Gets an iterator for the super sorts.
Definition at line 104 of file SortSymbol.h.
Referenced by operator==().
 { return _supersorts->begin(); }
SortList::iterator bcplus::symbols::SortSymbol::beginSuperSorts () inline
Definition at line 106 of file SortSymbol.h.
 { return _supersorts->begin(); }
bool bcplus::symbols::SortSymbol::contains (ObjectSymbol const * obj) const inline
Determines if an object or range symbol is in the wort.
Returns
True if the object symbol is in the sort, false otherwise.
Definition at line 128 of file SortSymbol.h.
Referenced by bcplus::symbols::SymbolTable::plus().
 { return _objects->count(obj) != 0; }
bool bcplus::symbols::SortSymbol::contains (NumberRangeSymbol const * r) const inline
Definition at line 129 of file SortSymbol.h.
 { return _ranges->count((Symbol const*)r) != 0; }
DomainType::type bcplus::symbols::SortSymbol::domainType () const virtual
Determine the domain type of this symbol.
Implements bcplus::symbols::Symbol.
Definition at line 256 of file SortSymbol.cpp.
Referenced by bcplus::symbols::VariableSymbol::domainType(), cplus2asp::cplus2asp_bin::Translator::epilogue(), and SortSymbol().
{
     return _dt;
 }
const_iterator bcplus::symbols::SortSymbol::end () const inline
Gets an iterator for the end of the object list.
Definition at line 92 of file SortSymbol.h.
Referenced by operator==().
 { return _objects->end(); }
RangeList::const_iterator bcplus::symbols::SortSymbol::endRanges () const inline
Gets an iterator for the end of the range list.
Definition at line 98 of file SortSymbol.h.
Referenced by operator==().
 { return _ranges->end(); }
SortList::const_iterator bcplus::symbols::SortSymbol::endSubSorts () const inline
Definition at line 114 of file SortSymbol.h.
Referenced by operator==().
 { return _subsorts->end(); }
SortList::iterator bcplus::symbols::SortSymbol::endSubSorts () inline
Definition at line 116 of file SortSymbol.h.
 { return _subsorts->end(); }
SortList::const_iterator bcplus::symbols::SortSymbol::endSuperSorts () const inline
Definition at line 105 of file SortSymbol.h.
Referenced by operator==().
 { return _supersorts->end(); }
SortList::iterator bcplus::symbols::SortSymbol::endSuperSorts () inline
Definition at line 107 of file SortSymbol.h.
 { return _supersorts->end(); }
bool bcplus::symbols::SortSymbol::loadDefinition (boost::property_tree::ptree const & node, Resolver * resolver, std::ostream * err = NULL)
Completely loads the sort including initializing subsorts and member objects NOTE: This may fail if member objects refer to a sort not yet instantiated.
Parameters
node The property_tree node load the sort from.
resolver A resolver used to resolve external references.
err An error stream to write to.
Returns
True if successful, false otherwise.
Definition at line 124 of file SortSymbol.cpp.
References add(), addSubSort(), bcplus::symbols::Symbol::base(), bcplus::symbols::Symbol::good(), bcplus::symbols::Resolver::resolveOrCreate(), and SortSymbol().
{
     // verify symbol name
     std::string node_name = node.get("<xmlattr>.base", "");
     int node_arity = node.get("<xmlattr>.arity", 0);
     if (node_arity || node_name != *base()) {
         good(false);
         if (err) *err << "INTERNAL ERROR: Cannot load definition for sort \"" << *base() << "\". Identifier \"" << node_name << "/" << node_arity << "\" does not match this sort." << std::endl;
     } else {
         BOOST_FOREACH(boost::property_tree::ptree::value_type const& n, node) {
             if (boost::iequals(n.first, "subsort")) {
                 // subsort
                 u::ref_ptr<SortSymbol> subsort = new SortSymbol(n.second, err);
                 if (subsort) {
                     u::ref_ptr<SortSymbol> subsort_resolved = resolver->resolveOrCreate(subsort);
                     if (!subsort_resolved) {
                         good(false);
                         if (err) *err << "ERROR: An error occurred while scanning the definition of sort \"" << *base() << "\".  SubSort \"" << *(subsort->base()) << "\" is not a declared sort." << std::endl;
                     } else addSubSort(subsort_resolved);
                 } else {
                     good(false);
                     if (err) *err << "ERROR: An error occurred while scanning the definition of sort \"" << *base() << "\". Expected a 'name' attribute which was not provided in a subset declaration." << std::endl;
                 }
             } else if (boost::iequals(n.first, "object")) {
                 // object
                 u::ref_ptr<ObjectSymbol> obj = new ObjectSymbol(n.second, resolver, err);
                 if (!obj || !obj->good()) {
                     good(false);
                     if (err) *err << "ERROR: An error occurred while scanning the definition of sort \"" << *base() << "\". Encountered a malformed object declaration." << std::endl;
                 } else {
                     // resolve it with previous definitions
                     u::ref_ptr<ObjectSymbol> obj_resolved = (ObjectSymbol*)resolver->resolveOrCreate(obj);
                     if (!obj_resolved) {
                         good(false);
                         if (err) *err << "ERROR: An error occurred while scanning the definition of sort \"" << *base() << "\". Encountered a conflicting definition of symbol \"" << *(obj->name()) << "\"." << std::endl;
                     } else {
                         // Good to go. Add the object
                         add(obj_resolved);
                     }
                 }
             } else if (n.first == "range") {
                 // numeric range
                 u::ref_ptr<NumberRangeSymbol> range = new NumberRangeSymbol(n.second, resolver, err);
                 if (!range || !range->good()) {
                     good(false);
                     if (err) *err << "ERROR: An error occurred while scanning the definition of sort \"" << *base() << "\". Encountered a malformed range declaration." << std::endl;
                 } else {
                     // resolve it with previous definitions
                     u::ref_ptr<NumberRangeSymbol> range_resolved = (NumberRangeSymbol*)resolver->resolveOrCreate(range);
                     if (!range_resolved) {
                         good(false);
                         if (err) *err << "ERROR: An error occurred while scanning the definition of sort \"" << *base() << "\". Encountered a conflicting definition of symbol \"" << *(range->name()) << "\"." << std::endl;
                     } else {
                         // Good to go. Add the object
                         add(range_resolved);
                     }
                 }
             } else if (n.first == "<xmlattr>") {
                 // ignore xml attributes.
             } else {
                 // who knows
                 good(false);
                 if (err) *err << "ERROR: Encountered an unexpected element \"" << n.first << "\" while scanning the definition of sort \"" << *base() << "\". Expected \"subsort\", \"object\", or \"range\"." << std::endl;
             }
         }
     }
     return good();
 }
size_t bcplus::symbols::SortSymbol::numSubSorts () const inline
Get the number of registered subsorts.
Definition at line 119 of file SortSymbol.h.
 { return _subsorts->size(); }
size_t bcplus::symbols::SortSymbol::numSuperSorts () const inline
Get the number of registered super sorts.
Definition at line 110 of file SortSymbol.h.
 { return _supersorts->size(); }
bool bcplus::symbols::SortSymbol::operator== (Symbol const & other) const virtual
Check to see if two symbols are equal.
Parameters
other The other symbol to compare this one to
Returns
True if they are equal, false otherwise.
Reimplemented from bcplus::symbols::Symbol.
Definition at line 195 of file SortSymbol.cpp.
References begin(), beginRanges(), beginSubSorts(), beginSuperSorts(), end(), endRanges(), endSubSorts(), and endSuperSorts().
{
     // sort symbols are special as they have complex interaction with each other
     // a sort symbol is only equal to another if it's the same object
 //  return this == &other;
     if (!Symbol::operator==(other)) return false;
     SortSymbol const& o = (SortSymbol const&)other;
     // check objects
     {
         const_iterator oit = o.begin();
         for (const_iterator it = begin() ; it != end(); it++) {
             // Everything draws from the same set of symbols, so we can use pointer comparison here
             if (oit == o.end()) return false;
             if (*it != *oit) return false;
             oit++;
         }
         if (oit != o.end()) return false;
     }
     // check ranges
     {
         RangeList::const_iterator oit = o.beginRanges();
         for (RangeList::const_iterator it = beginRanges() ; it != endRanges(); it++) {
             // Everything draws from the same set of symbols, so we can use pointer comparison here
             if (oit == o.endRanges()) return false;
             if (*it != *oit) return false;
             oit++;
         }
         if (oit != o.endRanges()) return false;
     }
     // check superset
     {
         SortList::const_iterator oit = o.beginSuperSorts();
         for (SortList::const_iterator it = beginSuperSorts() ; it != endSuperSorts(); it++) {
             // Everything draws from the same set of symbols, so we can use pointer comparison here
             if (oit == o.endSuperSorts()) return false;
             if (*it != *oit) return false;
             oit++;
         }
         if (oit != o.endSuperSorts()) return false;
     }
     // check subsets
     {
         SortList::const_iterator oit = o.beginSubSorts();
         for (SortList::const_iterator it = beginSubSorts() ; it != endSubSorts(); it++) {
             // Everything draws from the same set of symbols, so we can use pointer comparison here
             if (oit == o.endSubSorts()) return false;
             if (*it != *oit) return false;
             oit++;
         }
         if (oit != o.endSubSorts()) return false;
     }
     return true;
 }
void bcplus::symbols::SortSymbol::outputDefinition (std::ostream & out) const virtual
Definition at line 278 of file SortSymbol.cpp.
References bcplus::symbols::Symbol::base().
{
     out << *base();
 }
void bcplus::symbols::SortSymbol::save (boost::property_tree::ptree & node) const virtual
Outputs the symbol to the provided property tree node.
Parameters
node The node to write to
Reimplemented from bcplus::symbols::Symbol.
Definition at line 260 of file SortSymbol.cpp.
References bcplus::symbols::Symbol::base(), bcplus::symbols::detail::BaseSymbol::save(), and bcplus::symbols::Symbol::save().
{
     Symbol::save(node);
     BOOST_FOREACH(ObjectSymbol const* obj, *_objects) {
         boost::property_tree::ptree& tmp = node.add("object", "");
         obj->save(tmp);
     }
     BOOST_FOREACH(Symbol const* r, *_ranges) {
         boost::property_tree::ptree& tmp = node.add("range", "");
         r->save(tmp);
     }
     BOOST_FOREACH(SortSymbol const* sort, *_subsorts) {
         boost::property_tree::ptree& tmp = node.add("subsort", "");
         tmp.put("<xmlattr>.base", *(sort->base()));
     }
 }
size_t bcplus::symbols::SortSymbol::size () const inline
Gets the number of elements in the sort.
Definition at line 101 of file SortSymbol.h.
 { return _objects->size(); }
The documentation for this class was generated from the following files:
bcplusparser/include/bcplus/symbols/SortSymbol.h
bcplusparser/src/bcplus/symbols/SortSymbol.cpp