cplus2asp: bcplus::statements::Statement Class Reference
bcplus::statements::Statement Class Reference abstract
Abstract base class for a statement.
#include <Statement.h>
Classes
struct Type
Container for the list of statement types.
Public Member Functions
Statement (Type::type type, Location const &begin=Location(NULL, 0, 0), Location const &end=Location(NULL, 0, 0))
Basic Contructor.
~Statement ()
Destructor Stub.
Type::type type () const
Get the type of this statement.
char const * typeString () const
Get the string representation of the statement type.
Location const & beginLoc () const
Get the beginning location of this statement.
Location const & endLoc () const
Get the ending location of this statement.
virtual Statement * copy () const =0
Perform a dep copy of this statement.
Public Member Functions inherited from babb::utils::Referenced
Referenced ()
Referenced ()
Additional Inherited Members
Protected Member Functions inherited from babb::utils::Referenced
virtual ~Referenced ()
virtual ~Referenced ()
Detailed Description
Abstract base class for a statement.
Definition at line 16 of file Statement.h.
Constructor & Destructor Documentation
bcplus::statements::Statement::Statement (Type::type type, Location const & begin = Location(NULL, 0, 0), Location const & end = Location(NULL, 0, 0))
Basic Contructor.
Parameters
type The statement type
begin The beginning location of the statmenet
end The ending location of the statement
Definition at line 56 of file Statement.cpp.
     : _begin(begin), _end(end), _type(type) {
     /* Intentionally left blank */
 }
bcplus::statements::Statement::~Statement ()
Destructor Stub.
Definition at line 61 of file Statement.cpp.
                       {
     /* Intentionally left blank */
 }
Member Function Documentation
Location const& bcplus::statements::Statement::beginLoc () const inline
Get the beginning location of this statement.
Definition at line 111 of file Statement.h.
Referenced by bcplus::parser::detail::MacroParser::_handle_include(), and bcplus::statements::QueryStatement::copy().
 { return _begin; }
virtual Statement* bcplus::statements::Statement::copy () const pure virtual
Perform a dep copy of this statement.
Implemented in bcplus::statements::detail::BasicLawForm< type, head_t, ifbody_t, ifcons_t, after_t, unless_t, where_t >, bcplus::statements::detail::DynamicValueLawForm< type, body_t, head_t, value_t, ifbody_t, unless_t, where_t >, bcplus::statements::detail::DynamicLawForm< type, body_t, head_t, ifbody_t, unless_t, where_t >, bcplus::statements::QueryStatement, bcplus::statements::detail::ConstraintLawForm< type, body_t, after_t, unless_t, where_t >, bcplus::statements::detail::DynamicConstraintLawForm< type, body_t, ifbody_t, unless_t, where_t >, bcplus::statements::detail::ImplLawForm< type, head_t, body_t, where_t >, bcplus::statements::detail::SimpleLawForm< type, head_t, where_t >, bcplus::statements::detail::TemporalLawForm< type, head_t, at_t >, bcplus::statements::detail::ListStatement< type, T >, bcplus::statements::detail::SimpleStatement< type, value_t, valuearg_t >, and bcplus::statements::detail::VoidStatement< type >.
Location const& bcplus::statements::Statement::endLoc () const inline
Get the ending location of this statement.
Definition at line 114 of file Statement.h.
Referenced by bcplus::statements::QueryStatement::copy().
 { return _end; }
Type::type bcplus::statements::Statement::type () const inline
Get the type of this statement.
Definition at line 105 of file Statement.h.
Referenced by cplus2asp::bcbridge::Driver::run(), cplus2asp::cplus2asp_bin::Translator::translate(), and typeString().
 { return _type; }
char const* bcplus::statements::Statement::typeString () const inline
Get the string representation of the statement type.
Definition at line 108 of file Statement.h.
References type(), and bcplus::statements::Statement::Type::typeString().
Referenced by bcplus::parser::BCParser::_handle_stmt(), and cplus2asp::cplus2asp_bin::Translator::translate().
 { return Type::typeString(type()); }
The documentation for this class was generated from the following files:
bcplusparser/include/bcplus/statements/Statement.h
bcplusparser/src/bcplus/statements/Statement.cpp