cplus2asp: bcplus::elements::Element Class Reference
bcplus::elements::Element Class Reference abstract
Base class for a parser element.
#include <Element.h>
Classes
struct Type
Container of enumeration of possible types.
Public Types
typedef ReferencedSet
< babb::utils::ref_ptr< const
symbols::ConstantSymbol >
>::type ConstantSet
A set oc constant symbols.
typedef ReferencedSet
< babb::utils::ref_ptr< const
symbols::VariableSymbol >
>::type VariableSet
A set of variable symbols.
Public Member Functions
Element (Type::type type, ConstantSet const *constants, VariableSet const *variables, int cmask, Location const &begin=Location(NULL, 0, 0), Location const &end=Location(NULL, 0, 0), bool parens=false)
Full constructor.
virtual ~Element ()
Destructor stub.
bool parens () const
Getter/setter for whether or not this element has parentheses.
void parens (bool p)
Type::type type () const
Determines the type of the element.
Location const & beginLoc () const
Get/set the starting location of this element.
void beginLoc (Location const &loc)
Location const & endLoc () const
Get the ending location of this element.
void endLoc (Location const &loc)
std::string str () const
Helper function to output a string representing this element.
int cmask () const
Get the mask of constant types occurring within the element.
ConstantSet const * constants () const
Iterate through the list of constants occurring within the element.
ConstantSet::const_iterator beginConstants () const
ConstantSet::const_iterator endConstants () const
VariableSet const * freeVariables () const
Iterate through the list of FREE variables occurring within the element.
VariableSet::const_iterator beginFreeVariables () const
VariableSet::const_iterator endFreeVariables () const
virtual Element * copy () const =0
Does a deep copy of the element.
virtual void output (std::ostream &out) const =0
Outputs the element to the given stream.
virtual DomainType::type domainType () const =0
Get a description of the domain this element ranges over.
Public Member Functions inherited from babb::utils::Referenced
Referenced ()
Referenced ()
Protected Member Functions
void constants (ConstantSet const *set)
setter for the set of constants
void freeVariables (VariableSet const *set)
setter for the set of free variables (for use in constructors)
Protected Member Functions inherited from babb::utils::Referenced
virtual ~Referenced ()
virtual ~Referenced ()
Static Protected Member Functions
static ConstantSet * newConstSet (Element const *a=NULL, Element const *b=NULL)
Initializes a new constant set as the union of the two constant sets provided.
static ConstantSet * newConstSet (symbols::Symbol const *sym)
Initializes a new constant set and adds the provided symbol if it's a constant symbol.
static ConstantSet * insertConstants (ConstantSet *dest, Element const *src=NULL)
Adds the constants from an element to the provided set.
static VariableSet * newVarSet (Element const *a=NULL, Element const *b=NULL)
Iinitializes a new variable set as the union of the two variable sets provided.
static VariableSet * newVarSet (symbols::Symbol const *sym)
Initializes a new constant set and adds the provided symbol if it's a variable symbol.
static VariableSet * insertVariables (VariableSet *dest, Element const *src=NULL)
Adds the variables from an element to the provided set.
Detailed Description
Base class for a parser element.
Definition at line 21 of file Element.h.
Member Typedef Documentation
typedef ReferencedSet<babb::utils::ref_ptr<const symbols::ConstantSymbol> >::type bcplus::elements::Element::ConstantSet
A set oc constant symbols.
Definition at line 42 of file Element.h.
typedef ReferencedSet<babb::utils::ref_ptr<const symbols::VariableSymbol> >::type bcplus::elements::Element::VariableSet
A set of variable symbols.
Definition at line 45 of file Element.h.
Constructor & Destructor Documentation
bcplus::elements::Element::Element (Type::type type, ConstantSet const * constants, VariableSet const * variables, int cmask, Location const & begin = Location(NULL, 0, 0), Location const & end = Location(NULL, 0, 0), bool parens = false)
Full constructor.
Parameters
type The type of element this is
The set of constants occurring within the element.
The set of variables occurring within the element.
A mask of constant types occurring within the element.
begin The beginning location of this element
end The ending location of this element
parens Whether the element is surrounded by parentheses
Definition at line 18 of file Element.cpp.
     : _parens(parens), _type(type), _begin(begin), _end(end), _constants(constants), _variables(variables), _cmask(cmask) {
     /* Intentionally left blank */
 }
bcplus::elements::Element::~Element () virtual
Destructor stub.
Definition at line 23 of file Element.cpp.
                   {
     /* Intentionally left blank */
 }
Member Function Documentation
ConstantSet::const_iterator bcplus::elements::Element::beginConstants () const inline
Definition at line 117 of file Element.h.
Referenced by insertConstants(), and newConstSet().
 { return _constants->begin(); }
VariableSet::const_iterator bcplus::elements::Element::beginFreeVariables () const inline
Definition at line 122 of file Element.h.
Referenced by bcplus::elements::CardinalityFormula::CardinalityFormula(), insertVariables(), and newVarSet().
 { return _variables->begin(); }
Location const& bcplus::elements::Element::beginLoc () const inline
Get/set the starting location of this element.
Definition at line 102 of file Element.h.
Referenced by bcplus::parser::detail::MacroParser::_handle_macro(), bcplus::elements::AtomicFormula::copy(), bcplus::elements::QuantifierFormula::copy(), and bcplus::elements::CardinalityFormula::copy().
 { return _begin; }
void bcplus::elements::Element::beginLoc (Location const & loc) inline
Definition at line 103 of file Element.h.
 { _begin = loc; }
int bcplus::elements::Element::cmask () const inline
Get the mask of constant types occurring within the element.
Definition at line 113 of file Element.h.
 { return _cmask; }
ConstantSet const* bcplus::elements::Element::constants () const inline
Iterate through the list of constants occurring within the element.
Definition at line 116 of file Element.h.
 { return _constants; }
void bcplus::elements::Element::constants (ConstantSet const * set) inline protected
setter for the set of constants
Definition at line 160 of file Element.h.
 { _constants = set; }
virtual Element* bcplus::elements::Element::copy () const pure virtual
Does a deep copy of the element.
Implemented in bcplus::elements::detail::IdentifierElement< Element, Element::Type::MACRO, symbols::MacroSymbol, parser::Token >, bcplus::elements::CardinalityFormula, bcplus::elements::QuantifierFormula, bcplus::elements::detail::ElementClass< type, Subtypes >, bcplus::elements::AtomicFormula, and bcplus::elements::detail::IdentifierElement_bare< Element, type, symbols::MacroSymbol >.
virtual DomainType::type bcplus::elements::Element::domainType () const pure virtual
Get a description of the domain this element ranges over.
Implemented in bcplus::elements::CardinalityFormula, bcplus::elements::QuantifierFormula, bcplus::elements::detail::ElementClass< type, Subtypes >, bcplus::elements::AtomicFormula, and bcplus::elements::detail::IdentifierElement_bare< Element, type, symbols::MacroSymbol >.
ConstantSet::const_iterator bcplus::elements::Element::endConstants () const inline
Definition at line 118 of file Element.h.
Referenced by insertConstants(), and newConstSet().
 { return _constants->end(); }
VariableSet::const_iterator bcplus::elements::Element::endFreeVariables () const inline
Definition at line 123 of file Element.h.
Referenced by bcplus::elements::CardinalityFormula::CardinalityFormula(), insertVariables(), and newVarSet().
 { return _variables->end(); }
Location const& bcplus::elements::Element::endLoc () const inline
Get the ending location of this element.
Definition at line 106 of file Element.h.
Referenced by bcplus::elements::AtomicFormula::copy(), bcplus::elements::QuantifierFormula::copy(), and bcplus::elements::CardinalityFormula::copy().
 { return _end; }
void bcplus::elements::Element::endLoc (Location const & loc) inline
Definition at line 107 of file Element.h.
 { _end = loc; }
VariableSet const* bcplus::elements::Element::freeVariables () const inline
Iterate through the list of FREE variables occurring within the element.
Definition at line 121 of file Element.h.
Referenced by bcplus::elements::CardinalityFormula::CardinalityFormula(), and bcplus::elements::QuantifierFormula::QuantifierFormula().
 { return _variables; }
void bcplus::elements::Element::freeVariables (VariableSet const * set) inline protected
setter for the set of free variables (for use in constructors)
Definition at line 163 of file Element.h.
 { _variables = set; }
Element::ConstantSet * bcplus::elements::Element::insertConstants (ConstantSet * dest, Element const * src = NULL) static protected
Adds the constants from an element to the provided set.
Definition at line 55 of file Element.cpp.
References beginConstants(), and endConstants().
{
     if (src) {
         for (ConstantSet::const_iterator it = src->beginConstants(); it != src->endConstants(); it++) {
             dest->insert(*it);
         }
     }
     return dest;
 }
Element::VariableSet * bcplus::elements::Element::insertVariables (VariableSet * dest, Element const * src = NULL) static protected
Adds the variables from an element to the provided set.
Definition at line 91 of file Element.cpp.
References beginFreeVariables(), and endFreeVariables().
{
     if (src) {
         for (VariableSet::const_iterator it = src->beginFreeVariables(); it != src->endFreeVariables(); it++) {
             dest->insert(*it);
         }
     }
     return dest;
 }
Element::ConstantSet * bcplus::elements::Element::newConstSet (Element const * a = NULL, Element const * b = NULL) static protected
Initializes a new constant set as the union of the two constant sets provided.
Definition at line 28 of file Element.cpp.
References beginConstants(), endConstants(), and babb::utils::ref_ptr< T >::release().
{
     u::ref_ptr<ConstantSet> set = new ConstantSet();
     if (a) {
         for (ConstantSet::const_iterator it = a->beginConstants(); it != a->endConstants(); it++) {
             set->insert(*it);
         }
     }
     if (b) {
         for (ConstantSet::const_iterator it = b->beginConstants(); it != b->endConstants(); it++) {
             set->insert(*it);
         }
     }
     return set.release();
 }
Element::ConstantSet * bcplus::elements::Element::newConstSet (symbols::Symbol const * sym) static protected
Initializes a new constant set and adds the provided symbol if it's a constant symbol.
Definition at line 46 of file Element.cpp.
References babb::utils::ref_ptr< T >::release(), and bcplus::symbols::Symbol::type().
{
     u::ref_ptr<ConstantSet> set = new ConstantSet();
     if (sym->type() == sy::Symbol::Type::CONSTANT) {
         set->insert((sy::ConstantSymbol const*)sym);
     }
     return set.release();
 }
Element::VariableSet * bcplus::elements::Element::newVarSet (Element const * a = NULL, Element const * b = NULL) static protected
Iinitializes a new variable set as the union of the two variable sets provided.
Definition at line 64 of file Element.cpp.
References beginFreeVariables(), endFreeVariables(), and babb::utils::ref_ptr< T >::release().
Referenced by bcplus::elements::CardinalityFormula::CardinalityFormula(), and bcplus::elements::QuantifierFormula::QuantifierFormula().
{
     u::ref_ptr<VariableSet> set = new VariableSet();
     if (a) {
         for (VariableSet::const_iterator it = a->beginFreeVariables(); it != a->endFreeVariables(); it++) {
             set->insert(*it);
         }
     }
     if (b) {
         for (VariableSet::const_iterator it = b->beginFreeVariables(); it != b->endFreeVariables(); it++) {
             set->insert(*it);
         }
     }
     return set.release();
 }
Element::VariableSet * bcplus::elements::Element::newVarSet (symbols::Symbol const * sym) static protected
Initializes a new constant set and adds the provided symbol if it's a variable symbol.
Definition at line 82 of file Element.cpp.
References babb::utils::ref_ptr< T >::release(), and bcplus::symbols::Symbol::type().
{
     u::ref_ptr<VariableSet> set = new VariableSet();
     if (sym->type() == sy::Symbol::Type::VARIABLE) {
         set->insert((sy::VariableSymbol const*)sym);
     }
     return set.release();
 }
virtual void bcplus::elements::Element::output (std::ostream & out) const pure virtual
Outputs the element to the given stream.
Parameters
out The output stream to write to
Implemented in bcplus::elements::detail::IdentifierElement< Element, Element::Type::MACRO, symbols::MacroSymbol, parser::Token >, bcplus::elements::CardinalityFormula, bcplus::elements::QuantifierFormula, bcplus::elements::detail::ElementClass< type, Subtypes >, bcplus::elements::AtomicFormula, and bcplus::elements::detail::IdentifierElement_bare< Element, type, symbols::MacroSymbol >.
Referenced by operator<<(), and str().
bool bcplus::elements::Element::parens () const inline
Getter/setter for whether or not this element has parentheses.
Definition at line 95 of file Element.h.
Referenced by bcplus::elements::AtomicFormula::copy(), bcplus::elements::QuantifierFormula::copy(), bcplus::elements::CardinalityFormula::copy(), bcplus::elements::AtomicFormula::output(), and bcplus::elements::QuantifierFormula::output().
 { return _parens; }
void bcplus::elements::Element::parens (bool p) inline
Definition at line 96 of file Element.h.
 { _parens = p; }
std::string bcplus::elements::Element::str () const inline
Helper function to output a string representing this element.
Definition at line 110 of file Element.h.
References output().
 { std::stringstream out; output(out); return out.str(); }
Type::type bcplus::elements::Element::type () const inline
Determines the type of the element.
Definition at line 99 of file Element.h.
 { return _type; }
The documentation for this class was generated from the following files:
bcplusparser/include/bcplus/elements/Element.h
bcplusparser/src/bcplus/elements/Element.cpp