cplus2asp: bcplus::symbols::QuerySymbol Class Reference
bcplus::symbols::QuerySymbol Class Reference
#include <QuerySymbol.h>
Public Member Functions
QuerySymbol (ReferencedString const *base, int minmax, int maxmax)
Basic constructor.
QuerySymbol (boost::property_tree::ptree const &node, Resolver const *resolver, std::ostream *err=NULL)
Loads the query from the property tree node.
virtual ~QuerySymbol ()
Destructor stub.
int minmax () const
Get the query's minimum maximum step value (or a negative integer if undefined)
int maxmax () const
Get the query's maximum maximum step value (or a negative integer if undefined)
virtual DomainType::type domainType () const
Determine the domain type of this symbol.
virtual bool operator== (Symbol const &other) const
Check to see if two symbols are equal.
virtual void save (boost::property_tree::ptree &node) const
Outputs the symbol to the provided property tree node.
virtual void outputDefinition (std::ostream &out) const
Public Member Functions inherited from bcplus::symbols::Symbol
Symbol (Type::type type, babb::utils::ReferencedString const *base, size_t arity)
Basic Constructor.
Symbol (Type::type type, boost::property_tree::ptree const &node, std::ostream *err=NULL)
Attempts to load the symbol from the property tree node.
virtual ~Symbol ()
Destructor stub.
Type::type type () const
Get the symbol type.
char const * typeString () const
Get the symbol type as a cstring.
size_t arity () const
Get the arity of the symbol.
babb::utils::ReferencedString
const * base () const
Get the base name of the symbol.
babb::utils::ReferencedString
const * name () const
Get the full name of the symbol.
bool good () const
Determines if the symbol has been successfully loaded.
bool match (std::string const &b, size_t a) const
Determine if this symbol matches the provided detail.
bool match (std::string const &n) const
Determine if this symbol matches the provided detail.
Referenced * metadata () const
Get/set the metadata.
template<typename T >
T * metadata () const
Referenced * metadata ()
template<typename T >
T * metadata ()
void metadata (Referenced *data)
bool operator!= (Symbol const &other) const
Public Member Functions inherited from babb::utils::Referenced
Referenced ()
Referenced ()
Additional Inherited Members
Static Public Member Functions inherited from bcplus::symbols::Symbol
static std::string genName (std::string const &base, size_t arity=0)
Generate the symbol's name from its base and arity.
Protected Member Functions inherited from bcplus::symbols::Symbol
void good (bool l)
Set the good flag.
Protected Member Functions inherited from babb::utils::Referenced
virtual ~Referenced ()
virtual ~Referenced ()
Detailed Description
Definition at line 19 of file QuerySymbol.h.
Constructor & Destructor Documentation
bcplus::symbols::QuerySymbol::QuerySymbol (ReferencedString const * base, int minmax, int maxmax)
Basic constructor.
Parameters
base The name of the query
minmax The minimum maximum step value, or a negative integer for undefined.
maxmax The maximum maximum step value, or a negative integer for undefined.
Definition at line 15 of file QuerySymbol.cpp.
     : Symbol(Symbol::Type::QUERY, base, 0), _minmax(minmax), _maxmax(maxmax) {
     // Intentionally left blank
 }
bcplus::symbols::QuerySymbol::QuerySymbol (boost::property_tree::ptree const & node, Resolver const * resolver, std::ostream * err = NULL)
Loads the query from the property tree node.
Parameters
node The node to load the symbol from
err An error strem to write to (or NULL) Sets the symbol's good flag if it was successful
Definition at line 20 of file QuerySymbol.cpp.
References bcplus::symbols::Symbol::arity(), bcplus::symbols::Symbol::base(), bcplus::symbols::Symbol::good(), maxmax(), and minmax().
     : Symbol(Symbol::Type::QUERY, node, err) {
     if (good() && arity()) {
         good(false);
         if (err) *err << "ERROR: Query \"" << *base() << "\" cannot be declared with non-zero arity." << std::endl;
     }
     int minmax = -1;
     int maxmax = -1;
     try {
         minmax = node.get("<xmlattr>.minmax", -1);
         maxmax = node.get("<xmlattr>.maxmax", -1);
     } catch (boost::property_tree::ptree_error const& e) {
         good(false);
         if (err) *err << "Error: Encountered a malformed query symbol declaration. Expected integers for attributes \"minmax\" and \"maxmax\"." << std::endl;
     }
     _minmax = minmax;
     _maxmax = maxmax;
 }
bcplus::symbols::QuerySymbol::~QuerySymbol () virtual
Destructor stub.
Definition at line 43 of file QuerySymbol.cpp.
{
     // Intentionally left blank
 }
Member Function Documentation
DomainType::type bcplus::symbols::QuerySymbol::domainType () const virtual
Determine the domain type of this symbol.
Implements bcplus::symbols::Symbol.
Definition at line 47 of file QuerySymbol.cpp.
References bcplus::DomainType::NO_DOMAIN.
{
     return DomainType::NO_DOMAIN;
 }
int bcplus::symbols::QuerySymbol::maxmax () const inline
Get the query's maximum maximum step value (or a negative integer if undefined)
Definition at line 52 of file QuerySymbol.h.
Referenced by main(), and QuerySymbol().
 { return _maxmax; }
int bcplus::symbols::QuerySymbol::minmax () const inline
Get the query's minimum maximum step value (or a negative integer if undefined)
Definition at line 49 of file QuerySymbol.h.
Referenced by main(), and QuerySymbol().
 { return _minmax; }
bool bcplus::symbols::QuerySymbol::operator== (Symbol const & other) const virtual
Check to see if two symbols are equal.
Parameters
other The other symbol to compare this one to
Returns
True if they are equal, false otherwise.
Reimplemented from bcplus::symbols::Symbol.
Definition at line 51 of file QuerySymbol.cpp.
{
     // The query symbol doesn't have all of the information.
     // Thus we assume these are not equal if they're not the same
     // object
     return &other != this;
 }
void bcplus::symbols::QuerySymbol::outputDefinition (std::ostream & out) const virtual
Definition at line 64 of file QuerySymbol.cpp.
References bcplus::symbols::Symbol::base().
{
     out << *base();
 }
void bcplus::symbols::QuerySymbol::save (boost::property_tree::ptree & node) const virtual
Outputs the symbol to the provided property tree node.
Parameters
node The node to write to
Reimplemented from bcplus::symbols::Symbol.
Definition at line 58 of file QuerySymbol.cpp.
References bcplus::symbols::Symbol::save().
{
     Symbol::save(node);
     if (_minmax >= 0) node.put("<xmlattr>.minmax", _minmax);
     if (_maxmax >= 0) node.put("<xmlattr>.maxmax", _maxmax);
 }
The documentation for this class was generated from the following files:
bcplusparser/include/bcplus/symbols/QuerySymbol.h
bcplusparser/src/bcplus/symbols/QuerySymbol.cpp