cplus2asp: bcplus::symbols::AttributeSymbol Class Reference
bcplus::symbols::AttributeSymbol Class Reference
#include <AttributeSymbol.h>
Public Member Functions
AttributeSymbol (ReferencedString const *base, SortSymbol const *sort, ConstantSymbol const *attribOf, SortList const *args=NULL)
Basic constructor.
AttributeSymbol (boost::property_tree::ptree const &node, Resolver const *resolver, std::ostream *err=NULL)
Loads the object from the property tree node.
virtual ~AttributeSymbol ()
Destructor stub.
ConstantSymbol const * attribOf () const
Get the constant this symbol is an attribute of (if any)
virtual bool operator== (Symbol const &other) const
Check to see if two symbols are equal.
virtual void save (boost::property_tree::ptree &node) const
Outputs the symbol to the provided property tree node.
Public Member Functions inherited from bcplus::symbols::ConstantSymbol
ConstantSymbol (Type::type type, ReferencedString const *base, SortSymbol const *sort, SortList const *args=NULL)
Basic constructor.
ConstantSymbol (boost::property_tree::ptree const &node, Resolver const *resolver, std::ostream *err=NULL)
Loads the object from the property tree node.
virtual ~ConstantSymbol ()
Destructor stub.
SortSymbol const * sort () const
Get the sort this symbol ranges over.
Type::type constType () const
Get the type that this constant is.
char const * constTypeString () const
Get the string for the type taht this constant is.
virtual DomainType::type domainType () const
Determine the domain type of this symbol.
Public Member Functions inherited from bcplus::symbols::detail::BaseSymbol
BaseSymbol (Symbol::Type::type type, ReferencedString const *name, SortList const *args=NULL)
Basic constructor.
BaseSymbol (Symbol::Type::type type, boost::property_tree::ptree const &node, Resolver const *resolver, std::ostream *err=NULL)
Loads the sort from the property tree node.
virtual ~BaseSymbol ()
Destructor stub.
const_iterator begin () const
Gets an iterator for the beginning of the parameters.
const_iterator end () const
Gets an iterator for the end of the parameters.
virtual void outputDefinition (std::ostream &out) const
Public Member Functions inherited from bcplus::symbols::Symbol
Symbol (Type::type type, babb::utils::ReferencedString const *base, size_t arity)
Basic Constructor.
Symbol (Type::type type, boost::property_tree::ptree const &node, std::ostream *err=NULL)
Attempts to load the symbol from the property tree node.
virtual ~Symbol ()
Destructor stub.
Type::type type () const
Get the symbol type.
char const * typeString () const
Get the symbol type as a cstring.
size_t arity () const
Get the arity of the symbol.
babb::utils::ReferencedString
const * base () const
Get the base name of the symbol.
babb::utils::ReferencedString
const * name () const
Get the full name of the symbol.
bool good () const
Determines if the symbol has been successfully loaded.
bool match (std::string const &b, size_t a) const
Determine if this symbol matches the provided detail.
bool match (std::string const &n) const
Determine if this symbol matches the provided detail.
Referenced * metadata () const
Get/set the metadata.
template<typename T >
T * metadata () const
Referenced * metadata ()
template<typename T >
T * metadata ()
void metadata (Referenced *data)
bool operator!= (Symbol const &other) const
Public Member Functions inherited from babb::utils::Referenced
Referenced ()
Referenced ()
Additional Inherited Members
Public Types inherited from bcplus::symbols::detail::BaseSymbol
typedef ReferencedVector
< babb::utils::ref_ptr< const
SortSymbol > >::type SortList
typedef SortList::iterator iterator
typedef SortList::const_iterator const_iterator
Static Public Member Functions inherited from bcplus::symbols::Symbol
static std::string genName (std::string const &base, size_t arity=0)
Generate the symbol's name from its base and arity.
Protected Member Functions inherited from bcplus::symbols::Symbol
void good (bool l)
Set the good flag.
Protected Member Functions inherited from babb::utils::Referenced
virtual ~Referenced ()
virtual ~Referenced ()
Detailed Description
Definition at line 20 of file AttributeSymbol.h.
Constructor & Destructor Documentation
bcplus::symbols::AttributeSymbol::AttributeSymbol (ReferencedString const * base, SortSymbol const * sort, ConstantSymbol const * attribOf, SortList const * args = NULL)
Basic constructor.
Parameters
base The name of this object
sort The sort that this constant ranges over
args The sorts for each of the arguments for this object.
attribOf The constant this constant is an attribute of (or NULL)
Definition at line 19 of file AttributeSymbol.cpp.
     : ConstantSymbol(ConstantSymbol::Type::ATTRIBUTE, base, sort, args) , _attribof(attribOf) {
     // intentionally left blank
 }
bcplus::symbols::AttributeSymbol::AttributeSymbol (boost::property_tree::ptree const & node, Resolver const * resolver, std::ostream * err = NULL)
Loads the object from the property tree node.
Parameters
node The node to load the symbol from
err An error strem to write to (or NULL) Sets the symbol's good flag if it was successful
Definition at line 24 of file AttributeSymbol.cpp.
References bcplus::symbols::ConstantSymbol::Type::ABACTION, bcplus::symbols::ConstantSymbol::Type::ACTION, bcplus::symbols::Symbol::Type::CONSTANT, bcplus::symbols::ConstantSymbol::Type::EXOGENOUSACTION, bcplus::symbols::Symbol::good(), bcplus::symbols::Symbol::name(), and bcplus::symbols::Resolver::resolve().
     : ConstantSymbol(node, resolver, err) {
     try {
         std::string c_name = node.get<std::string>("<xmlattr>.attributeOf");
         ConstantSymbol const* c = (ConstantSymbol const*)resolver->resolve(Symbol::Type::CONSTANT, c_name);
         if (!c) {
             good(false);
             if (err) *err << "ERROR: An error occurred while scanning the definition of \"" << *name() << "\". \"" << c_name << "\" is not a valid action constant." << std::endl;
         } else {
             if (c->constType() != ConstantSymbol::Type::ABACTION && c->constType() != ConstantSymbol::Type::ACTION && c->constType() != ConstantSymbol::Type::EXOGENOUSACTION) {
                 good(false);
                 if (err) *err << "ERROR: An error occurred while scanning the definition of \"" << *name() << "\". \"" << c_name << "\" is not a valid target for an attribue. Expected an \"abAction\" or \"action\" type constant." << std::endl;
             } else {
                 _attribof = c;
             }
         }
     } catch (boost::property_tree::ptree_error& e) {
         good(false);
         if (err) *err << "ERROR: An error occurred while scanning the definition of \"" << *name() << "\". Expected a 'sort' attribute declaring the constant's sort." << std::endl;
     }
 }
bcplus::symbols::AttributeSymbol::~AttributeSymbol () virtual
Destructor stub.
Definition at line 49 of file AttributeSymbol.cpp.
{
     // Intentionally left blank
 }
Member Function Documentation
ConstantSymbol const* bcplus::symbols::AttributeSymbol::attribOf () const inline
Get the constant this symbol is an attribute of (if any)
Definition at line 48 of file AttributeSymbol.h.
Referenced by operator==().
 { return _attribof; }
bool bcplus::symbols::AttributeSymbol::operator== (Symbol const & other) const virtual
Check to see if two symbols are equal.
Parameters
other The other symbol to compare this one to
Returns
True if they are equal, false otherwise.
Reimplemented from bcplus::symbols::ConstantSymbol.
Definition at line 54 of file AttributeSymbol.cpp.
References attribOf().
{
     if (!ConstantSymbol::operator==(other)) return false;
     AttributeSymbol const& o = (AttributeSymbol const&)other;
     // ensure the parent constants are the same
     if (attribOf() != o.attribOf()) return false;
     return true;
 }
void bcplus::symbols::AttributeSymbol::save (boost::property_tree::ptree & node) const virtual
Outputs the symbol to the provided property tree node.
Parameters
node The node to write to
Reimplemented from bcplus::symbols::ConstantSymbol.
Definition at line 63 of file AttributeSymbol.cpp.
References bcplus::symbols::ConstantSymbol::save().
{
     ConstantSymbol::save(node);
     node.put("<xmlattr>.attributeOf", *_attribof->name());
 }
The documentation for this class was generated from the following files:
bcplusparser/include/bcplus/symbols/AttributeSymbol.h
bcplusparser/src/bcplus/symbols/AttributeSymbol.cpp