cplus2asp: bcplus::statements::detail::ConstraintLawForm< type, body_t, after_t, unless_t, where_t > Class Template Reference
bcplus::statements::detail::ConstraintLawForm< type, body_t, after_t, unless_t, where_t > Class Template Reference
Base law form for basic laws.
#include <ConstraintLawForm.h>
Public Types
typedef body_t body_type
typedef after_t after_type
typedef unless_t unless_type
typedef where_t where_type
Public Member Functions
ConstraintLawForm (body_t const *body, after_t const *after, unless_t const *unless, where_t const *where, Location const &begin=Location(NULL, 0, 0), Location const &end=Location(NULL, 0, 0))
virtual ~ConstraintLawForm ()
body_t const * body () const
Get the 'if' clause.
after_t const * after () const
Get the 'after' clause.
unless_t const * unless () const
Get the 'unless' clause.
where_t const * where () const
Get the 'where' clause.
virtual Statement * copy () const
Perform a dep copy of this statement.
Public Member Functions inherited from bcplus::statements::Statement
Statement (Type::type type, Location const &begin=Location(NULL, 0, 0), Location const &end=Location(NULL, 0, 0))
Basic Contructor.
~Statement ()
Destructor Stub.
Type::type type () const
Get the type of this statement.
char const * typeString () const
Get the string representation of the statement type.
Location const & beginLoc () const
Get the beginning location of this statement.
Location const & endLoc () const
Get the ending location of this statement.
Public Member Functions inherited from babb::utils::Referenced
Referenced ()
Referenced ()
Additional Inherited Members
Protected Member Functions inherited from babb::utils::Referenced
virtual ~Referenced ()
virtual ~Referenced ()
Detailed Description
template<Statement::Type::type type, typename body_t, typename after_t, typename unless_t, typename where_t>
class bcplus::statements::detail::ConstraintLawForm< type, body_t, after_t, unless_t, where_t >
Base law form for basic laws.
Definition at line 15 of file ConstraintLawForm.h.
Member Typedef Documentation
template<Statement::Type::type type, typename body_t , typename after_t , typename unless_t , typename where_t > typedef after_t bcplus::statements::detail::ConstraintLawForm< type, body_t, after_t, unless_t, where_t >::after_type
Definition at line 22 of file ConstraintLawForm.h.
template<Statement::Type::type type, typename body_t , typename after_t , typename unless_t , typename where_t > typedef body_t bcplus::statements::detail::ConstraintLawForm< type, body_t, after_t, unless_t, where_t >::body_type
Definition at line 21 of file ConstraintLawForm.h.
template<Statement::Type::type type, typename body_t , typename after_t , typename unless_t , typename where_t > typedef unless_t bcplus::statements::detail::ConstraintLawForm< type, body_t, after_t, unless_t, where_t >::unless_type
Definition at line 23 of file ConstraintLawForm.h.
template<Statement::Type::type type, typename body_t , typename after_t , typename unless_t , typename where_t > typedef where_t bcplus::statements::detail::ConstraintLawForm< type, body_t, after_t, unless_t, where_t >::where_type
Definition at line 24 of file ConstraintLawForm.h.
Constructor & Destructor Documentation
template<Statement::Type::type t, typename body_t , typename after_t , typename unless_t , typename where_t > bcplus::statements::detail::ConstraintLawForm< t, body_t, after_t, unless_t, where_t >::ConstraintLawForm (body_t const * body, after_t const * after, unless_t const * unless, where_t const * where, Location const & begin = Location(NULL, 0, 0), Location const & end = Location(NULL, 0, 0))
Definition at line 13 of file ConstraintLawForm.impl.h.
     : Statement(t, begin, end), _body(body), _after(after), _unless(unless), _where(where) {
     /* Intentionally left blank */
 }
template<Statement::Type::type t, typename body_t , typename after_t , typename unless_t , typename where_t > bcplus::statements::detail::ConstraintLawForm< t, body_t, after_t, unless_t, where_t >::~ConstraintLawForm () virtual
Definition at line 21 of file ConstraintLawForm.impl.h.
{
     /* Intentionally left blank */
 }
Member Function Documentation
template<Statement::Type::type type, typename body_t , typename after_t , typename unless_t , typename where_t > after_t const* bcplus::statements::detail::ConstraintLawForm< type, body_t, after_t, unless_t, where_t >::after () const inline
Get the 'after' clause.
Definition at line 64 of file ConstraintLawForm.h.
Referenced by cplus2asp::cplus2asp_bin::Translator::translate().
 { return _after; }
template<Statement::Type::type type, typename body_t , typename after_t , typename unless_t , typename where_t > body_t const* bcplus::statements::detail::ConstraintLawForm< type, body_t, after_t, unless_t, where_t >::body () const inline
Get the 'if' clause.
Definition at line 61 of file ConstraintLawForm.h.
Referenced by cplus2asp::cplus2asp_bin::Translator::translate().
 { return _body; }
template<Statement::Type::type t, typename body_t , typename after_t , typename unless_t , typename where_t > Statement * bcplus::statements::detail::ConstraintLawForm< t, body_t, after_t, unless_t, where_t >::copy () const virtual
Perform a dep copy of this statement.
Implements bcplus::statements::Statement.
Definition at line 26 of file ConstraintLawForm.impl.h.
{
     return new ConstraintLawForm<t, body_t, after_t, unless_t, where_t>(body(), after(), unless(), where(), beginLoc(), endLoc());
 }
template<Statement::Type::type type, typename body_t , typename after_t , typename unless_t , typename where_t > unless_t const* bcplus::statements::detail::ConstraintLawForm< type, body_t, after_t, unless_t, where_t >::unless () const inline
Get the 'unless' clause.
Definition at line 67 of file ConstraintLawForm.h.
Referenced by cplus2asp::cplus2asp_bin::Translator::translate().
 { return _unless; }
template<Statement::Type::type type, typename body_t , typename after_t , typename unless_t , typename where_t > where_t const* bcplus::statements::detail::ConstraintLawForm< type, body_t, after_t, unless_t, where_t >::where () const inline
Get the 'where' clause.
Definition at line 70 of file ConstraintLawForm.h.
Referenced by cplus2asp::cplus2asp_bin::Translator::translate().
 { return _where; }
The documentation for this class was generated from the following files:
bcplusparser/include/bcplus/statements/detail/ConstraintLawForm.h
bcplusparser/include/bcplus/statements/detail/ConstraintLawForm.impl.h