cplus2asp: SimpleUnaryOperator Class Reference
SimpleUnaryOperator Class Reference
Child of ParseElement that represents a unary operator and the associated elements it operates on.
#include <parser_types.h>
Public Types
enum UnaryOperatorType {
UOP_UNKNOWN, UOP_NOT, UOP_STRONG_NOT, UOP_NEGATIVE,
UOP_ABS, UOP_EXOGENOUS, UOP_INERTIAL, UOP_RIGID,
UOP_CHOICE
}
Enum of the kinds of unary operators this class can be.
Public Types inherited from ParseElement
enum ParseElementType {
PELEM_PELEM, PELEM_UOP, PELEM_BOP, PELEM_QUANT,
PELEM_BASELIKE, PELEM_CONSTLIKE, PELEM_OBJLIKE, PELEM_VARLIKE
}
The possible types of a ParseElement instance.
enum ConstMask {
MASK_ACTION = 0x01, MASK_FLUENT = 0x02, MASK_RIGID = 0x04, MASK_STATIC_AB = 0x08,
MASK_DYNAMIC_AB = 0x10, MASK_TRUE_FALSE = 0x20, MASK_SDFLUENT = 0x40, MASK_AB = MASK_STATIC_AB | MASK_DYNAMIC_AB,
MASK_NON_TRIVIAL = ~MASK_TRUE_FALSE, MASK_NON_RIGID = MASK_NON_TRIVIAL & ~MASK_RIGID, MASK_NON_AB = MASK_NON_TRIVIAL & ~MASK_AB
}
Mask values for the various kinds of constants that can be in a formula.
Public Member Functions
SimpleUnaryOperator (UnaryOperatorType opType, ParseElement *postOp, bool parens=false)
Full constructor.
virtual std::ostream & translate (std::ostream &out, Context &context) const
Method that generates a translated string representation of the element with preceeding @ if a symbol is understood as a lua function call.
virtual bool hasConstants (unsigned int types, bool includeParams=true, bool includeEq=true) const
Returns true if the element (or any of its children) are constants of the provided types.
virtual bool isDefinite (bool allowComparison=false, bool allowChoice=false, bool allowAtomicNegation=false) const
Determines if the element contains a single atom, a unary expression w/ a single atom, or a conjunction thereof.
virtual bool isSingleAtom (bool allowAtomicNegation=false) const
Whether the formula is a single atom.
virtual bool isArithExpr () const
Determines if the element is a valid arithmetic expression.
virtual bool hasLuaCalls (bool includeParams=true, bool includeEq=true) const
Determines if the element contains any calls to LUA.
virtual IPart determineQueryIPart () const
Determines the proper IPart to place the formula in.
virtual std::ostream & fullName (std::ostream &out) const
Prints the untranslated element string.
virtual ParseElement * copy () const
Returns an exact copy of the parse element.
virtual void aggregateUndefined (BaseElementList &outIdentifiers)
Aggregates all of the undefined identifiers (which are assumed to be constants).
UnaryOperatorType opType () const
Gets the operator's type.
void opType (UnaryOperatorType op)
Sets the operator's type.
ParseElement const * postOp () const
Gets the operator's sub expression.
void postOp (ParseElement *postOp)
Sets the operator's sub expression, deallocating any existing sub expression.
ParseElement * detachPostOp ()
Detaches the operator's sub expression, returning it.
virtual ~SimpleUnaryOperator ()
Destructor.
Public Member Functions inherited from ParseElement
ParseElement (ParseElementType elemType, bool parens=false)
Default constructor.
bool isTrivial (bool includeParams=true, bool includeEq=true) const
Determines if the element contains no (real) constants.
std::string fullName () const
Alternative helper to fullName(std::ostream&).
ParseElementType getType () const
Gets the type of the parse element.
void parens (bool parens)
Sets whether the expression is wrapped in parentheses.
bool parens () const
Gets whether the element is encompassed in parens.
virtual ~ParseElement ()
Destructor.
Static Protected Member Functions
static std::string translateOpType (UnaryOperatorType op)
Simple helper function.
Additional Inherited Members
Static Public Member Functions inherited from ParseElement
static std::string getNewVar ()
Gets a new variable whose name is unique within the rule we're translating.
Protected Member Functions inherited from ParseElement
bool hasParens () const
Determines if the element has parentheses around it.
std::string translateBeforeParen (bool forceParens=false) const
Helper to translate that intelligently handles the value of parenBefore.
std::string translateAfterParen (bool forceParens=false) const
Helper to translate that intelligently handles the value of parenAfter.
Detailed Description
Child of ParseElement that represents a unary operator and the associated elements it operates on.
Definition at line 258 of file parser_types.h.
Member Enumeration Documentation
enum SimpleUnaryOperator::UnaryOperatorType
Enum of the kinds of unary operators this class can be.
Enumerator
UOP_UNKNOWN
UOP_NOT
UOP_STRONG_NOT
UOP_NEGATIVE
UOP_ABS
UOP_EXOGENOUS
UOP_INERTIAL
UOP_RIGID
UOP_CHOICE
Definition at line 262 of file parser_types.h.
 { UOP_UNKNOWN, UOP_NOT, UOP_STRONG_NOT, UOP_NEGATIVE, UOP_ABS, UOP_EXOGENOUS, UOP_INERTIAL, UOP_RIGID, UOP_CHOICE };
Constructor & Destructor Documentation
SimpleUnaryOperator::SimpleUnaryOperator (UnaryOperatorType opType, ParseElement * postOp, bool parens = false) inline
Full constructor.
Parameters
opType the type of operation the operator should perform.
postOp the subexpression which occurs after the operator.
parens Whether to add parens around the element.
Definition at line 276 of file parser_types.h.
Referenced by copy().
         : ParseElement(PELEM_UOP, parens), mOpType(opType), mPostOp(postOp)
     { /* IntentionallY Left Blank */ }
SimpleUnaryOperator::~SimpleUnaryOperator () virtual
Destructor.
Deallocates postOp.
Definition at line 385 of file parser_types.cpp.
 {
     if(mPostOp) delete mPostOp;
 }
Member Function Documentation
virtual void SimpleUnaryOperator::aggregateUndefined (BaseElementList & outIdentifiers) inline virtual
Aggregates all of the undefined identifiers (which are assumed to be constants).
Parameters
outIdentifiers The undefined identifiers.
Implements ParseElement.
Definition at line 291 of file parser_types.h.
References ParseElement::aggregateUndefined(), and postOp().
 { if (postOp()) mPostOp->aggregateUndefined(outIdentifiers); }
virtual ParseElement* SimpleUnaryOperator::copy () const inline virtual
Returns an exact copy of the parse element.
Implements ParseElement.
Definition at line 290 of file parser_types.h.
References copy(), opType(), ParseElement::parens(), postOp(), and SimpleUnaryOperator().
Referenced by copy().
 { return new SimpleUnaryOperator(opType(), (postOp()) ? postOp()->copy() : NULL, parens()); }
ParseElement * SimpleUnaryOperator::detachPostOp ()
Detaches the operator's sub expression, returning it.
Definition at line 355 of file parser_types.cpp.
Referenced by Translator::translateAlwaysLaw(), Translator::translateConstraintLaw(), and Translator::translateDeclarativeLaw().
{
     ParseElement* ret = mPostOp;
     mPostOp = NULL;
     return ret;
 }
virtual IPart SimpleUnaryOperator::determineQueryIPart () const inline virtual
Determines the proper IPart to place the formula in.
Returns
IPART_BASE if the formula is 0:(...), IPART_VOLATILE if the formula is X:(...), and IPART_CUMULATIVE if the formula is anything else.
Implements ParseElement.
Definition at line 288 of file parser_types.h.
References ParseElement::determineQueryIPart(), and postOp().
 { return (postOp()) ? postOp()->determineQueryIPart() : IPART_BASE; }
std::ostream & SimpleUnaryOperator::fullName (std::ostream & out) const virtual
Prints the untranslated element string.
Parameters
out The output stream to print to.
Returns
out.
Implements ParseElement.
Definition at line 316 of file parser_types.cpp.
References ParseElement::fullName(), opType(), postOp(), UOP_ABS, UOP_EXOGENOUS, UOP_INERTIAL, UOP_NEGATIVE, UOP_NOT, UOP_RIGID, and UOP_STRONG_NOT.
 {
     if(postOp())
     {
         // Create a CCalc-compatible representation of the operator first.
         switch(opType())
         {
         case UOP_STRONG_NOT:
             out << "~";
             break;
         case UOP_NOT:
             out << "not ";
             break;
         case UOP_NEGATIVE:
             out << "-";
             break;
         case UOP_ABS:
             out << "abs ";
             break;
         case UOP_EXOGENOUS:
             out << "exogenous ";
             break;
         case UOP_INERTIAL:
             out << "inertial ";
             break;
         case UOP_RIGID:
             out << "rigid ";
             break;
         default:
             // Unknown operator, this should never happen
             out << " UNKNOWN ";
             break;
         }
         postOp()->fullName(out);
     }
     return out;
 }
bool SimpleUnaryOperator::hasConstants (unsigned int types, bool includeParams = true, bool includeEq = true) const virtual
Returns true if the element (or any of its children) are constants of the provided types.
Parameters
types A mask containing flags for the types to search for. See ConstMask enum.
includeParams Whether to check the parameters of constants.
includeEq Whether to check the right side of equality within an atom. (The right hand side of comparisons will be checked regardless.)
Returns
True if the element, or any elements "beneach" it, are constants, false otherwise.
Implements ParseElement.
Definition at line 237 of file parser_types.cpp.
References ParseElement::hasConstants(), ParseElement::MASK_RIGID, opType(), postOp(), UOP_EXOGENOUS, UOP_INERTIAL, and UOP_RIGID.
Referenced by translate().
{
     if (postOp()) {
         if ((types & MASK_RIGID))
             return  opType() == UOP_EXOGENOUS
                         || opType() == UOP_INERTIAL
                         || opType() == UOP_RIGID
                         || postOp()->hasConstants(types, includeParams, includeEq);
         else
             return  opType() != UOP_EXOGENOUS
                         && opType() != UOP_INERTIAL
                         && opType() != UOP_RIGID
                         && postOp()->hasConstants(types, includeParams, includeEq);
     } else return false;
 }
virtual bool SimpleUnaryOperator::hasLuaCalls (bool includeParams = true, bool includeEq = true) const inline virtual
Determines if the element contains any calls to LUA.
Parameters
includeParams Whether to search base element parameter lists.
includeEq Whether to check the right side of equality within an atom. (The right hand side of comparisons will be checked regardless.)
Returns
True if the element or any of its children is a LUA call.
Implements ParseElement.
Definition at line 286 of file parser_types.h.
References ParseElement::hasLuaCalls(), and postOp().
                                                                 { return postOp() && postOp()->hasLuaCalls(includeParams, includeEq); }
bool SimpleUnaryOperator::isArithExpr () const virtual
Determines if the element is a valid arithmetic expression.
Returns
True if the element and all it's children are arithmetic expressions.
Implements ParseElement.
Definition at line 296 of file parser_types.cpp.
References ParseElement::isArithExpr(), opType(), postOp(), UOP_ABS, UOP_EXOGENOUS, UOP_INERTIAL, UOP_NEGATIVE, UOP_NOT, UOP_RIGID, UOP_STRONG_NOT, and UOP_UNKNOWN.
{
     if (!postOp()) return false;
     else {
         switch (opType()) {
         case UOP_NEGATIVE:
         case UOP_ABS:
             return postOp()->isArithExpr();
         case UOP_UNKNOWN:
         case UOP_NOT:
         case UOP_STRONG_NOT:
         case UOP_EXOGENOUS:
         case UOP_INERTIAL:
         case UOP_RIGID:
         default:
             return false;
         }
     }
 }
bool SimpleUnaryOperator::isDefinite (bool allowComparison = false, bool allowChoice = false, bool allowAtomicNegation = false) const virtual
Determines if the element contains a single atom, a unary expression w/ a single atom, or a conjunction thereof.
Parameters
allowComparison Whether to allow comparison operators in the formula.
allowChoice Whether to allow choice rules in the formula.
allowAtomicNegation whether to allow -p or "not p" where p is a boolean atom.
Returns
True if the element is a definite formula.
Implements ParseElement.
Definition at line 255 of file parser_types.cpp.
References ParseElement::getType(), ParseElement::isSingleAtom(), isSingleAtom(), opType(), ParseElement::PELEM_CONSTLIKE, ParseElement::PELEM_VARLIKE, postOp(), UOP_CHOICE, UOP_EXOGENOUS, UOP_INERTIAL, and UOP_RIGID.
 {
     // Three cases:
     // the expression is '~p' as this is shorthand for p=false.
     // or this is a declarative law such as exogenous p. where p is a constant.
     // Alternatively, in the event we are working with a declarative law it may be one of UOP_EXOGENOUS, UOP_INERTIAL, UOP_RIGID
         // Finally, If we are allowing choice rules, then we should check if this is a choice rule and if below us is a single assignment
         // or boolean atom.
     // sanity
     if (!postOp()) return false;
     // case 1
     if (isSingleAtom(allowAtomicNegation)) return true;
     // case 2
     if (opType() == UOP_INERTIAL || opType() == UOP_RIGID || opType() == UOP_EXOGENOUS) {
         return postOp()->getType() == ParseElement::PELEM_CONSTLIKE
                 || (postOp()->getType() == ParseElement::PELEM_VARLIKE);
     }
     // case three
     if (allowChoice && opType() == UOP_CHOICE) {
         return (postOp()->isSingleAtom(allowAtomicNegation));
     }
     return false;
 }
bool SimpleUnaryOperator::isSingleAtom (bool allowAtomicNegation = false) const virtual
Whether the formula is a single atom.
Returns
True if the element is a single atom c=v (or just c if c is boolean).
Parameters
allowAtomicNegation whether to allow -p or "not p" where p is a boolean atom.
Implements ParseElement.
Definition at line 286 of file parser_types.cpp.
References ParseElement::getType(), opType(), ParseElement::PELEM_CONSTLIKE, ParseElement::PELEM_VARLIKE, postOp(), UOP_NOT, and UOP_STRONG_NOT.
Referenced by isDefinite().
 {
     if (opType() == UOP_STRONG_NOT || (allowAtomicNegation && opType() == UOP_NOT)) {
         return (postOp()->getType() == ParseElement::PELEM_CONSTLIKE || postOp()->getType() == ParseElement::PELEM_VARLIKE)
                 && (((BaseLikeElement*)postOp())->ref()->isBoolean());
     }
     return false;
 }
UnaryOperatorType SimpleUnaryOperator::opType () const inline
Gets the operator's type.
Definition at line 295 of file parser_types.h.
Referenced by copy(), fullName(), hasConstants(), isArithExpr(), isDefinite(), isSingleAtom(), and translate().
 { return mOpType; }
void SimpleUnaryOperator::opType (UnaryOperatorType op) inline
Sets the operator's type.
Definition at line 298 of file parser_types.h.
 { mOpType = op; }
ParseElement const* SimpleUnaryOperator::postOp () const inline
Gets the operator's sub expression.
Definition at line 301 of file parser_types.h.
Referenced by aggregateUndefined(), copy(), determineQueryIPart(), fullName(), hasConstants(), hasLuaCalls(), isArithExpr(), isDefinite(), isSingleAtom(), translate(), and Translator::translateConstraintLaw().
 { return mPostOp; }
void SimpleUnaryOperator::postOp (ParseElement * postOp) inline
Sets the operator's sub expression, deallocating any existing sub expression.
Definition at line 304 of file parser_types.h.
References postOp().
Referenced by postOp().
 { if (mPostOp) delete mPostOp; mPostOp = postOp; }
std::ostream & SimpleUnaryOperator::translate (std::ostream & out, Context & context) const virtual
Method that generates a translated string representation of the element with preceeding @ if a symbol is understood as a lua function call.
Parameters
[out] out - The output stream to write to.
context - The formula context to be used for translation.
Returns
out.
Implements ParseElement.
Definition at line 70 of file parser_types.cpp.
References Translator::bindAndTranslate(), ParseElement::fullName(), BaseLikeElement::fullName(), ParseElement::getType(), ParseElement::hasConstants(), hasConstants(), ltsyyossErr, ParseElement::MASK_AB, opType(), ParseElement::PELEM_CONSTLIKE, ParseElement::PELEM_VARLIKE, postOp(), BaseLikeElement::ref(), ParseElement::translate(), VariableLikeElement::translate(), ParseElement::translateAfterParen(), ParseElement::translateBeforeParen(), translateOpType(), UOP_ABS, UOP_CHOICE, UOP_EXOGENOUS, UOP_INERTIAL, UOP_NEGATIVE, UOP_NOT, UOP_RIGID, and UOP_STRONG_NOT.
 {
     Context localContext;
     out << translateBeforeParen();
     // Sanity check: is the argument to the operator not NULL?
     if(!postOp()) {
         // TODO: Throw warning
         return out;
     }
     // Then, perform different translations based on what the operator is.
     switch(opType())
     {
     case UOP_STRONG_NOT: // Logical Strong negation "~"
         // Only applicable to bare booleans.
         if(postOp()->getType() == PELEM_CONSTLIKE && !postOp()->hasConstants(MASK_AB)) {
             // some validation, make sure it's boolean
             if (!((ConstantLikeElement*)postOp())->isBoolean()) {
                 // Not a boolean constant, but still used in bare "~c" style, this doesn't make sense.
                 ltsyystartParseError();
                 ltsyyossErr << "Can't use \"~\" to negate non-Boolean constant \"";
                 postOp()->fullName(ltsyyossErr);
                 ltsyyossErr << "\".";
                 ltsyyreportError();
                 return out;
             }
             // output the constant with value false
             localContext = context.mkValue(Context::FALSE_STR);
             postOp()->translate(out, localContext);
         } else if(postOp()->getType() == PELEM_VARLIKE && ((VariableLikeElement*)postOp())->isConstantVariable()) {
             // This variable actually stands for a constant of some kind, treat this as "~constant".
             // Throw up a warning, as using "~V" with V being a constant is not guaranteed to work.
             VariableLikeElement* varPostOp = (VariableLikeElement*)postOp();
             ltsyystartWarning();
             ltsyyossErr << "Using \"~\" on variable \"";
             varPostOp->fullName(ltsyyossErr);
             ltsyyossErr << "\" representing constant type \"";
             ltsyyossErr << ((Variable const*)varPostOp->ref())->domain()->fullName();
             ltsyyossErr << "\" is not a good idea, and is almost guaranteed to not work as expected unless you know exactly what you're doing.";
             ltsyyreportWarning();
             localContext = context.mkValue(Context::FALSE_STR);
             varPostOp->translate(out, localContext);
         } else {
             // Not a bare constant,
             ltsyystartParseError();
             ltsyyossErr << "Invalid use of \"~\" preceeding \"";
             postOp()->fullName(ltsyyossErr);
             ltsyyossErr << "\". \"~\" must immediately preceede a bare boolean constant.";
             ltsyyreportError();
             return out;
         }
         break;
     case UOP_NOT: // Logical negation.
         // Negation works differently for bare booleans within the scope of negation (or if this is C+), check for them.
         if ((context.getLang() == LANG_CPLUS || context.getNegated()) && postOp()->getType() == PELEM_CONSTLIKE && !postOp()->hasConstants(MASK_AB)) {
             // some validation, make sure it's boolean
             if (!((ConstantLikeElement*)postOp())->isBoolean()) {
                 // Not a boolean constant, but still used in bare "not c" style, this doesn't make sense.
                 ltsyystartParseError();
                 ltsyyossErr << "Can't use \"not\" to negate non-Boolean constant \"";
                 postOp()->fullName(ltsyyossErr);
                 ltsyyossErr << "\" without specifying which value is being negated. Try something like \"";
                 postOp()->fullName(ltsyyossErr);
                 ltsyyossErr << "=some_value\".";
                 ltsyyreportError();
                 return out;
             }
             // output the constant with value false
             localContext = context.mkValue(Context::FALSE_STR);
             postOp()->translate(out, localContext);
         } else {
             // Just a normal negation.
             // Sanity check, make sure that we're not in the head of a rule before capturing clauses../
             // Make sure we capture the clauses locally...
             if (context.getPos() != Context::POS_HEAD && context.getPos() != Context::POS_CHOICE_RULE) {
                 out << translateOpType(opType()) + "(";
                 Translator::bindAndTranslate(out, postOp(), context, false);
                 out << ")";
             } else {
                 // crap, we are. Just pass em up and hope for the best.
                 // TODO
                 localContext = context.mkNegated();
                 out << translateOpType(opType()) << "(";
                 postOp()->translate(out, localContext);
                 out << ")";
             }
         }
         break;
     case UOP_NEGATIVE: // Numeric negative.
     case UOP_ABS:   // Absolute value.
         localContext = context.mkPos(Context::POS_ARITHEXPR);
         out << translateOpType(opType()) << "(";
         postOp()->translate(out, localContext);
         out << ")";
         break;
     case UOP_EXOGENOUS: // Exogenous declaration.
     case UOP_INERTIAL: // Inertial declaration.
     case UOP_RIGID: // Rigid declaration.
         // All three "operators" do the same thing, it's just a matter of what name to use.
         if(postOp()->getType() == PELEM_CONSTLIKE)
         {
             localContext = context.mkPos(Context::POS_INTERNAL);
             out << translateOpType(opType()) << "(";
             postOp()->translate(out, localContext);
             out << ")";
         }
         else
         {
             ltsyystartParseError();
             ltsyyossErr << "Declaring \"";
             postOp()->fullName(ltsyyossErr);
             ltsyyossErr << "\" as " << translateOpType(opType()) << " is not supported.";
             ltsyyreportError();
         }
         break;
         case UOP_CHOICE:
                 localContext = context.mkPos(Context::POS_CHOICE_RULE);
         out << "{";
         postOp()->translate(out, localContext);
         out << "}";
                 break;
     default:
         // Unknown operator, just do a blind translation.
         out << translateOpType(opType()) << "(";
         postOp()->translate(out, context);
         out << ")";
         break;
     }
     out << translateAfterParen();
     return out;
 }
std::string SimpleUnaryOperator::translateOpType (UnaryOperatorType op) static protected
Simple helper function.
Converts the provided operator to a string representation.
Parameters
op The operator to convert
Returns
A string corresponding to that operator.
Definition at line 362 of file parser_types.cpp.
References UOP_ABS, UOP_EXOGENOUS, UOP_INERTIAL, UOP_NEGATIVE, UOP_NOT, UOP_RIGID, and UOP_STRONG_NOT.
Referenced by translate().
{
     switch(op)
     {
     case UOP_STRONG_NOT:
         return "~";
     case UOP_NOT:
         return "not ";
     case UOP_NEGATIVE:
         return "-";
     case UOP_ABS:
         return "#abs";
     case UOP_EXOGENOUS:
         return "exogenous";
     case UOP_INERTIAL:
         return "inertial";
     case UOP_RIGID:
         return "rigid";
     default:
         return " UNKNOWN ";
     }
 }
The documentation for this class was generated from the following files:
cplus2asp.bin/old/parser_types.h
cplus2asp.bin/old/parser_types.cpp