cplus2asp: BigQuantifiers Class Reference
BigQuantifiers Class Reference
Child of ParseElement that represents a big quantifier group and its associated subformula.
#include <parser_types.h>
Public Types
enum QuantifierType { QUANT_UNKNOWN, QUANT_CONJ, QUANT_DISJ }
Which kinds of "quantifiers" can be present.
typedef std::pair
< BigQuantifiers::QuantifierType,
ParseElement * > Quantifier
A single quantifier.
typedef std::list< Quantifier * > QuantifierList
A list of quantifiers and their associated variable.
Public Types inherited from ParseElement
enum ParseElementType {
PELEM_PELEM, PELEM_UOP, PELEM_BOP, PELEM_QUANT,
PELEM_BASELIKE, PELEM_CONSTLIKE, PELEM_OBJLIKE, PELEM_VARLIKE
}
The possible types of a ParseElement instance.
enum ConstMask {
MASK_ACTION = 0x01, MASK_FLUENT = 0x02, MASK_RIGID = 0x04, MASK_STATIC_AB = 0x08,
MASK_DYNAMIC_AB = 0x10, MASK_TRUE_FALSE = 0x20, MASK_SDFLUENT = 0x40, MASK_AB = MASK_STATIC_AB | MASK_DYNAMIC_AB,
MASK_NON_TRIVIAL = ~MASK_TRUE_FALSE, MASK_NON_RIGID = MASK_NON_TRIVIAL & ~MASK_RIGID, MASK_NON_AB = MASK_NON_TRIVIAL & ~MASK_AB
}
Mask values for the various kinds of constants that can be in a formula.
Public Member Functions
BigQuantifiers (QuantifierList const *quants=NULL, ParseElement *postOp=NULL, bool parens=false)
Full Constructor.
virtual std::ostream & translate (std::ostream &out, Context &context) const
Method that generates a translated string representation of the element with preceeding @ if a symbol is understood as a lua function call.
virtual bool hasConstants (unsigned int types, bool includeParams=true, bool includeEq=true) const
Returns true if the element (or any of its children) are constants of the provided types.
virtual bool isDefinite (bool allowComparison=false, bool allowChoice=false, bool allowAtomicNegation=false) const
Determines if the element contains a single atom, a unary expression w/ a single atom, or a conjunction thereof.
virtual bool isSingleAtom (bool allowAtomicNegation=false) const
Whether the formula is a single atom.
virtual bool isArithExpr () const
Determines if the element is a valid arithmetic expression.
virtual bool hasLuaCalls (bool includeParams=true, bool includeEq=true) const
Determines if the element contains any calls to LUA.
virtual IPart determineQueryIPart () const
Determines the proper IPart to place the formula in.
virtual std::ostream & fullName (std::ostream &out) const
Prints the untranslated element string.
virtual ParseElement * copy () const
Returns an exact copy of the parse element.
virtual void aggregateUndefined (BaseElementList &outIdentifiers)
Aggregates all of the undefined identifiers (which are assumed to be constants).
QuantifierList::const_iterator quantsBegin () const
Gets the begining of the list of quantifiers.
QuantifierList::const_iterator quantsEnd () const
Gets the end of the list of quantifiers.
size_t numQuants () const
Gets the number of quantifiers associated with this instance.
void addQuant (Quantifier *newQuant)
Adds a quantifier to the list.
ParseElement const * postOp () const
Gets the operator's sub expression.
void postOp (ParseElement *postOp)
Sets the operator's sub expression, deallocating any existing sub expression.
ParseElement * detachPostOp ()
Detaches the operator's sub expression, returning it.
virtual ~BigQuantifiers ()
Destructor.
Public Member Functions inherited from ParseElement
ParseElement (ParseElementType elemType, bool parens=false)
Default constructor.
bool isTrivial (bool includeParams=true, bool includeEq=true) const
Determines if the element contains no (real) constants.
std::string fullName () const
Alternative helper to fullName(std::ostream&).
ParseElementType getType () const
Gets the type of the parse element.
void parens (bool parens)
Sets whether the expression is wrapped in parentheses.
bool parens () const
Gets whether the element is encompassed in parens.
virtual ~ParseElement ()
Destructor.
Protected Member Functions
QuantifierList::iterator quantsBegin ()
Gets the begining of the list of quantifiers.
QuantifierList::iterator quantsEnd ()
Gets the end of the list of quantifiers.
Protected Member Functions inherited from ParseElement
bool hasParens () const
Determines if the element has parentheses around it.
std::string translateBeforeParen (bool forceParens=false) const
Helper to translate that intelligently handles the value of parenBefore.
std::string translateAfterParen (bool forceParens=false) const
Helper to translate that intelligently handles the value of parenAfter.
Additional Inherited Members
Static Public Member Functions inherited from ParseElement
static std::string getNewVar ()
Gets a new variable whose name is unique within the rule we're translating.
Detailed Description
Child of ParseElement that represents a big quantifier group and its associated subformula.
Definition at line 446 of file parser_types.h.
Member Typedef Documentation
typedef std::pair<BigQuantifiers::QuantifierType, ParseElement*> BigQuantifiers::Quantifier
A single quantifier.
Definition at line 453 of file parser_types.h.
typedef std::list<Quantifier*> BigQuantifiers::QuantifierList
A list of quantifiers and their associated variable.
Definition at line 456 of file parser_types.h.
Member Enumeration Documentation
enum BigQuantifiers::QuantifierType
Which kinds of "quantifiers" can be present.
Enumerator
QUANT_UNKNOWN
QUANT_CONJ
QUANT_DISJ
Definition at line 450 of file parser_types.h.
 { QUANT_UNKNOWN, QUANT_CONJ, QUANT_DISJ };
Constructor & Destructor Documentation
BigQuantifiers::BigQuantifiers (QuantifierList const * quants = NULL, ParseElement * postOp = NULL, bool parens = false) inline
Full Constructor.
Parameters
quants The list of quantifiers that encase the sub expression. (Null initializes the expression to have no quantifiers).
postOp The sub expression that occurs after the quantifiers.
parens Whether to encase the expression in parens.
Definition at line 473 of file parser_types.h.
Referenced by copy().
         : ParseElement(ParseElement::PELEM_QUANT, parens), mPostOp(postOp) {
         if (quants) mQuants = *quants;
     }
BigQuantifiers::~BigQuantifiers () virtual
Destructor.
Deallocates postOp and the contents of quants.
Definition at line 936 of file parser_types.cpp.
References quantsBegin(), and quantsEnd().
 {
     for(QuantifierList::iterator lIter = quantsBegin(); lIter != quantsEnd(); lIter++)
     {
         if((*lIter)->second)
         {
             delete (*lIter)->second;
         }
         delete (*lIter);
     }
     if(mPostOp)
         delete mPostOp;
 }
Member Function Documentation
void BigQuantifiers::addQuant (Quantifier * newQuant) inline
Adds a quantifier to the list.
Definition at line 503 of file parser_types.h.
Referenced by copy().
 { mQuants.push_back(newQuant); }
void BigQuantifiers::aggregateUndefined (BaseElementList & outIdentifiers) virtual
Aggregates all of the undefined identifiers (which are assumed to be constants).
Parameters
outIdentifiers The undefined identifiers.
Implements ParseElement.
Definition at line 919 of file parser_types.cpp.
References ParseElement::aggregateUndefined(), postOp(), quantsBegin(), and quantsEnd().
{
     for (QuantifierList::const_iterator it = quantsBegin(); it != quantsEnd(); it++) {
         if ((*it)->second) {
             (*it)->second->aggregateUndefined(outIdentifiers);
         }
     }
     if (postOp()) mPostOp->aggregateUndefined(outIdentifiers);
 }
ParseElement * BigQuantifiers::copy () const virtual
Returns an exact copy of the parse element.
Implements ParseElement.
Definition at line 909 of file parser_types.cpp.
References addQuant(), BigQuantifiers(), ParseElement::parens(), postOp(), quantsBegin(), and quantsEnd().
{
     BigQuantifiers* res = new BigQuantifiers(NULL, NULL, parens());
     res->postOp((postOp()) ? postOp()->copy() : NULL);
     for (QuantifierList::const_iterator it = quantsBegin(); it != quantsEnd(); it++) {
         if ((*it)->second)
             res->addQuant(new Quantifier((*it)->first, (*it)->second->copy()));
     }
     return res;
 }
ParseElement * BigQuantifiers::detachPostOp ()
Detaches the operator's sub expression, returning it.
Definition at line 929 of file parser_types.cpp.
{
     ParseElement* ret = mPostOp;
     mPostOp = NULL;
     return ret;
 }
virtual IPart BigQuantifiers::determineQueryIPart () const inline virtual
Determines the proper IPart to place the formula in.
Returns
IPART_BASE if the formula is 0:(...), IPART_VOLATILE if the formula is X:(...), and IPART_CUMULATIVE if the formula is anything else.
Implements ParseElement.
Definition at line 487 of file parser_types.h.
References ParseElement::determineQueryIPart(), and postOp().
 { return (postOp()) ? postOp()->determineQueryIPart() : IPART_BASE; }
std::ostream & BigQuantifiers::fullName (std::ostream & out) const virtual
Prints the untranslated element string.
Parameters
out The output stream to print to.
Returns
out.
Implements ParseElement.
Definition at line 879 of file parser_types.cpp.
References ParseElement::fullName(), numQuants(), postOp(), QUANT_CONJ, QUANT_DISJ, quantsBegin(), and quantsEnd().
 {
     if(postOp() && numQuants())
     {
         out << "[ ";
         for(QuantifierList::const_iterator lIter = quantsBegin(); lIter != quantsEnd(); lIter++)
         {
             if((*lIter) && (*lIter)->second)
             {
                 switch((*lIter)->first)
                 {
                 case QUANT_CONJ:
                     out << "/\\ ";
                     break;
                 case QUANT_DISJ:
                     out << "\\/ ";
                     break;
                 default:
                     break;
                 }
                 (*lIter)->second->fullName(out);
             }
         }
         out << " | ";
         postOp()->fullName(out);
         out << " ]";
     }
     return out;
 }
bool BigQuantifiers::hasConstants (unsigned int types, bool includeParams = true, bool includeEq = true) const virtual
Returns true if the element (or any of its children) are constants of the provided types.
Parameters
types A mask containing flags for the types to search for. See ConstMask enum.
includeParams Whether to check the parameters of constants.
includeEq Whether to check the right side of equality within an atom. (The right hand side of comparisons will be checked regardless.)
Returns
True if the element, or any elements "beneach" it, are constants, false otherwise.
Implements ParseElement.
Definition at line 874 of file parser_types.cpp.
References ParseElement::hasConstants(), and postOp().
{
     return postOp() && postOp()->hasConstants(types, includeParams, includeEq);
 }
virtual bool BigQuantifiers::hasLuaCalls (bool includeParams = true, bool includeEq = true) const inline virtual
Determines if the element contains any calls to LUA.
Parameters
includeParams Whether to search base element parameter lists.
includeEq Whether to check the right side of equality within an atom. (The right hand side of comparisons will be checked regardless.)
Returns
True if the element or any of its children is a LUA call.
Implements ParseElement.
Definition at line 485 of file parser_types.h.
References ParseElement::hasLuaCalls(), and postOp().
                                                                 { return postOp() && postOp()->hasLuaCalls(includeParams, includeEq); }
virtual bool BigQuantifiers::isArithExpr () const inline virtual
Determines if the element is a valid arithmetic expression.
Returns
True if the element and all it's children are arithmetic expressions.
Implements ParseElement.
Definition at line 484 of file parser_types.h.
 { return false; }
virtual bool BigQuantifiers::isDefinite (bool allowComparison = false, bool allowChoice = false, bool allowAtomicNegation = false) const inline virtual
Determines if the element contains a single atom, a unary expression w/ a single atom, or a conjunction thereof.
Parameters
allowComparison Whether to allow comparison operators in the formula.
allowChoice Whether to allow choice rules in the formula.
allowAtomicNegation whether to allow -p or "not p" where p is a boolean atom.
Returns
True if the element is a definite formula.
Implements ParseElement.
Definition at line 482 of file parser_types.h.
 { return false; }
virtual bool BigQuantifiers::isSingleAtom (bool allowAtomicNegation = false) const inline virtual
Whether the formula is a single atom.
Returns
True if the element is a single atom c=v (or just c if c is boolean).
Parameters
allowAtomicNegation whether to allow -p or "not p" where p is a boolean atom.
Implements ParseElement.
Definition at line 483 of file parser_types.h.
 { return false; }
size_t BigQuantifiers::numQuants () const inline
Gets the number of quantifiers associated with this instance.
Definition at line 499 of file parser_types.h.
Referenced by fullName().
 { return mQuants.size(); }
ParseElement const* BigQuantifiers::postOp () const inline
Gets the operator's sub expression.
Definition at line 506 of file parser_types.h.
Referenced by aggregateUndefined(), copy(), determineQueryIPart(), fullName(), hasConstants(), hasLuaCalls(), and translate().
 { return mPostOp; }
void BigQuantifiers::postOp (ParseElement * postOp) inline
Sets the operator's sub expression, deallocating any existing sub expression.
Definition at line 509 of file parser_types.h.
References postOp().
Referenced by postOp().
 { if (mPostOp) delete mPostOp; mPostOp = postOp; }
QuantifierList::const_iterator BigQuantifiers::quantsBegin () const inline
Gets the begining of the list of quantifiers.
Definition at line 493 of file parser_types.h.
Referenced by aggregateUndefined(), copy(), fullName(), translate(), and ~BigQuantifiers().
 { return mQuants.begin(); }
QuantifierList::iterator BigQuantifiers::quantsBegin () inline protected
Gets the begining of the list of quantifiers.
Definition at line 521 of file parser_types.h.
 { return mQuants.begin(); }
QuantifierList::const_iterator BigQuantifiers::quantsEnd () const inline
Gets the end of the list of quantifiers.
Definition at line 496 of file parser_types.h.
Referenced by aggregateUndefined(), copy(), fullName(), translate(), and ~BigQuantifiers().
 { return mQuants.end(); }
QuantifierList::iterator BigQuantifiers::quantsEnd () inline protected
Gets the end of the list of quantifiers.
Definition at line 524 of file parser_types.h.
 { return mQuants.end(); }
std::ostream & BigQuantifiers::translate (std::ostream & out, Context & context) const virtual
Method that generates a translated string representation of the element with preceeding @ if a symbol is understood as a lua function call.
Parameters
[out] out - The output stream to write to.
context - The formula context to be used for translation.
Returns
out.
Implements ParseElement.
Definition at line 824 of file parser_types.cpp.
References Translator::bindAndTranslate(), postOp(), QUANT_CONJ, QUANT_DISJ, quantsBegin(), quantsEnd(), ParseElement::translateAfterParen(), and ParseElement::translateBeforeParen().
 {
     // The local context is used for variable list.
     // They _shouldn't_ be declaring free variables and clauses.
     Context localContext = context.mkPos(Context::POS_TERM).mkBindVars(NULL).mkBindClauses(NULL);
     out << translateBeforeParen();
     for(QuantifierList::const_iterator lIter = quantsBegin(); lIter != quantsEnd(); lIter++)
     {
         switch((*lIter)->first)
         {
         case QUANT_CONJ:
             out << "![";
             if((*lIter)->second)
                 (*lIter)->second->translate(out, localContext);
             out << "]:(";
             break;
         case QUANT_DISJ:
             out << "?[";
             if((*lIter)->second)
                 (*lIter)->second->translate(out, localContext);
             out << "]:(";
             break;
         default:
             // Unknown, just open a parenthesis.
             out << "(";
             break;
         }
         // Instead of having a bunch of linked lists lying around, we'll just push on a marker string for every nested quantifier.
     }
     // Next, translate whatever subformula was in the big quantifiers.
     if(postOp())
         Translator::bindAndTranslate(out, postOp(), context, false);
     // Nested parens
     for(QuantifierList::const_iterator lIter = quantsBegin(); lIter != quantsEnd(); lIter++) {
         out << ")";
     }
     out << translateAfterParen();
     return out;
 }
The documentation for this class was generated from the following files:
cplus2asp.bin/old/parser_types.h
cplus2asp.bin/old/parser_types.cpp