cplus2asp: bcplus::parser::detail::ScannerBufferSource Class Reference
bcplus::parser::detail::ScannerBufferSource Class Reference
A scanner source which draws directly from a pre-defined in-memory buffer.
#include <ScannerBufferSource.h>
Public Member Functions
ScannerBufferSource (Configuration const *config, char const *buffer, Location const &loc=Location(NULL, 0, 0), bool track_position=false)
virtual ~ScannerBufferSource ()
Destructor.
ReferencedPath const * file () const
The file provided as the location.
size_t line () const
The current line number (or the provided line number if we're not tracking position)
size_t col () const
Gets the current column (or the provided column if we're not tracking position)
virtual void newline ()
Callback which indicates that the scanner found a newline and the location should be updated.
virtual Location loc () const
Gets the current location of the source.
virtual Status::type status () const
Determines the status of the source.
virtual void close ()
Closes the source.
virtual void fill (size_t n)
Refills the buffer to the desired level.
Public Member Functions inherited from bcplus::parser::detail::ScannerRawSource
ScannerRawSource (Configuration const *config)
virtual ~ScannerRawSource ()
Destructor.
Configuration const * config () const
Gets the system configuration.
char const *& cursor ()
Scanner state accessors / mutators.
char const *const & cursor () const
void cursor (char const *c)
char const *& limit ()
char const *const & limit () const
void limit (char const *l)
char const *& token ()
char const *const & token () const
void token (char const *t)
char const *& marker ()
char const *const & marker () const
void marker (char const *m)
char const *& ctxmarker ()
char const *const & ctxmarker () const
void ctxmarker (char const *m)
bool good () const
Determines if the source is ready to read from.
bool eof () const
Public Member Functions inherited from bcplus::parser::detail::ScannerSource
ScannerSource (Type::type type)
Basic Constructor.
virtual ~ScannerSource ()
Destructor stub.
Type::type type () const
Get the subtype of this source.
Public Member Functions inherited from babb::utils::Referenced
Referenced ()
Referenced ()
Additional Inherited Members
Protected Member Functions inherited from babb::utils::Referenced
virtual ~Referenced ()
virtual ~Referenced ()
Detailed Description
A scanner source which draws directly from a pre-defined in-memory buffer.
Definition at line 22 of file ScannerBufferSource.h.
Constructor & Destructor Documentation
bcplus::parser::detail::ScannerBufferSource::ScannerBufferSource (Configuration const * config, char const * buffer, Location const & loc = Location(NULL, 0, 0), bool track_position = false)
Parameters
config The system wide configuration information
buffer The null-terminated buffer to read from.
loc The location that should be displayed in output messages partaining to this source
track_position Whether the position relative to the starting position should be tracked.
Definition at line 12 of file ScannerBufferSource.cpp.
References bcplus::Location::col(), bcplus::parser::detail::ScannerRawSource::ctxmarker(), bcplus::parser::detail::ScannerRawSource::cursor(), bcplus::parser::detail::ScannerRawSource::limit(), bcplus::parser::detail::ScannerRawSource::marker(), and bcplus::parser::detail::ScannerRawSource::token().
     : ScannerRawSource(config), _file(loc.file()), _line(loc.line()), _first_col(loc.col()), _track(track_position) {
     // figure out the size of the buffer
     _buffer_sz = strlen(buffer) + 1;
     _buffer = new char[_buffer_sz];
     memcpy(_buffer, buffer, _buffer_sz);
     cursor() = _buffer;
     token() = _buffer;
     marker() = _buffer;
     ctxmarker() = _buffer;
     limit() = _buffer + _buffer_sz;
     _newline = _buffer - loc.col();
 }
bcplus::parser::detail::ScannerBufferSource::~ScannerBufferSource () virtual
Destructor.
Definition at line 28 of file ScannerBufferSource.cpp.
{
     delete[] _buffer;
 }
Member Function Documentation
void bcplus::parser::detail::ScannerBufferSource::close () virtual
Closes the source.
Implements bcplus::parser::detail::ScannerRawSource.
Definition at line 50 of file ScannerBufferSource.cpp.
{
     // intentionaly left blankd
 }
size_t bcplus::parser::detail::ScannerBufferSource::col () const inline
Gets the current column (or the provided column if we're not tracking position)
Definition at line 69 of file ScannerBufferSource.h.
References bcplus::parser::detail::ScannerRawSource::token().
Referenced by loc().
 { return (_track ? (size_t)(token() - _newline + 1) : _first_col); }
ReferencedPath const* bcplus::parser::detail::ScannerBufferSource::file () const inline
The file provided as the location.
Definition at line 63 of file ScannerBufferSource.h.
Referenced by loc().
 { return _file; }
void bcplus::parser::detail::ScannerBufferSource::fill (size_t n) virtual
Refills the buffer to the desired level.
Parameters
n The minimum number of characters to fill.
Implements bcplus::parser::detail::ScannerRawSource.
Definition at line 55 of file ScannerBufferSource.cpp.
References bcplus::parser::detail::ScannerRawSource::ctxmarker(), bcplus::parser::detail::ScannerRawSource::cursor(), bcplus::parser::detail::ScannerRawSource::limit(), bcplus::parser::detail::ScannerRawSource::marker(), and bcplus::parser::detail::ScannerRawSource::token().
{
     char const* first = (token() < marker()) ? token() : marker();
     first = (first < ctxmarker() ? first : ctxmarker());
     size_t remaining = limit() - first;
     size_t req_sz = remaining + n;
     if (req_sz > _buffer_sz) {
         // oh noes. need more buffer
         size_t new_sz = req_sz*2;
         char* new_buf = new char[new_sz];
         memcpy(new_buf, first, remaining);
         delete[] _buffer;
         _buffer = new_buf;
         _buffer_sz = new_sz;
         limit() = new_buf + new_sz;
     } else {
         // we can keep the buffer and shift the contents
         memmove(_buffer, first, remaining);
     }
     size_t marker_offset = (size_t)(marker() - first);
     size_t ctxmarker_offset = (size_t)(ctxmarker() - first);
     size_t token_offset = (size_t)(token() - first);
     size_t cursor_offset = (size_t)(cursor() - first);
     size_t newline_offset = (size_t)(_newline - first);
     cursor() = _buffer + cursor_offset;
     marker() = _buffer + marker_offset;
     token() = _buffer + token_offset;
     ctxmarker() = _buffer + ctxmarker_offset;
     _newline = _buffer + newline_offset;
     // Fill the remainder of the buffer
     char* readpos = _buffer + remaining;
     int read_amount = _buffer_sz - remaining;
     memset(readpos,'\0', read_amount);
 }
size_t bcplus::parser::detail::ScannerBufferSource::line () const inline
The current line number (or the provided line number if we're not tracking position)
Definition at line 66 of file ScannerBufferSource.h.
Referenced by loc().
 { return _line; }
Location bcplus::parser::detail::ScannerBufferSource::loc () const virtual
Gets the current location of the source.
Implements bcplus::parser::detail::ScannerRawSource.
Definition at line 39 of file ScannerBufferSource.cpp.
References col(), file(), and line().
{
     return Location(file(), line(), col());
 }
void bcplus::parser::detail::ScannerBufferSource::newline () virtual
Callback which indicates that the scanner found a newline and the location should be updated.
Implements bcplus::parser::detail::ScannerRawSource.
Definition at line 32 of file ScannerBufferSource.cpp.
References bcplus::parser::detail::ScannerRawSource::cursor().
{
     if (_track) {
         _line++;
         _newline = cursor();
     }
 }
ScannerBufferSource::Status::type bcplus::parser::detail::ScannerBufferSource::status () const virtual
Determines the status of the source.
Implements bcplus::parser::detail::ScannerRawSource.
Definition at line 43 of file ScannerBufferSource.cpp.
References bcplus::parser::detail::ScannerRawSource::cursor(), bcplus::parser::detail::ScannerRawSource::Status::END_INPUT, and bcplus::parser::detail::ScannerRawSource::Status::OK.
{
     if (cursor() && !*cursor()) return Status::END_INPUT;
     else return Status::OK;
 }
The documentation for this class was generated from the following files:
bcplusparser/include/bcplus/parser/detail/ScannerBufferSource.h
bcplusparser/src/bcplus/parser/detail/ScannerBufferSource.cpp