cplus2asp: cplus2asp::bcbridge::Driver Class Reference
cplus2asp::bcbridge::Driver Class Reference
#include <Driver.h>
Public Member Functions
Driver (std::string const &host=DEF_OCLINGO_HOST, std::string const &port=DEF_OCLINGO_PORT)
Basic constructor.
~Driver ()
Destructor. Closes connections, frees memory.
int run ()
Runs the driver program.
as2transition::TransitionFormatter & formatter ()
Gets the as2transition object used to format the oClingo output.
as2transition::TransitionFormatter
const & formatter () const
std::string const & port () const
Gets the port being used to connect to oClingo.
bool port (std::string const &port)
Sets the port being used to connect to oClingo.
std::string const & host () const
Gets the host that we're connecting to oClingo on.
bool host (std::string const &host)
Sets the host that we're connecting to oClingo on.
bool symtab (std::string const &symtab)
Sets the file that we're reading the symbol table from.
Static Public Attributes
static std::string const DEF_OCLINGO_PORT
The default port to attempt to connect to oClingo with.
static std::string const DEF_OCLINGO_HOST
The default host to attempt to connect to oClingo at.
Detailed Description
Definition at line 52 of file Driver.h.
Constructor & Destructor Documentation
cplus2asp::bcbridge::Driver::Driver (std::string const & host = DEF_OCLINGO_HOST, std::string const & port = DEF_OCLINGO_PORT)
Basic constructor.
Prepares everything but does not initialize the connections.
Parameters
host The host to establish the connection to.
port The port to establish the connection to.
Definition at line 71 of file Driver.cpp.
References as2transition::TransitionFormatter::config(), as2transition::Config::stripPrefix(), and symtab().
             : mHost(host),
             mPort(port),
             mLastStep(0),
             mClosing(false),
 #ifdef BOOST_TIMER
             mShowTime(false)
 #endif
     {
     mFormatter.config()->stripPrefix(true);
     symtab("");
 }
cplus2asp::bcbridge::Driver::~Driver () inline
Destructor. Closes connections, frees memory.
Definition at line 104 of file Driver.h.
                      {
         if (mClient) {
             if (mClient->open()) mClient->close();
         }
     }
Member Function Documentation
as2transition::TransitionFormatter& cplus2asp::bcbridge::Driver::formatter () inline
Gets the as2transition object used to format the oClingo output.
Definition at line 118 of file Driver.h.
Referenced by main().
 { return mFormatter; }
as2transition::TransitionFormatter const& cplus2asp::bcbridge::Driver::formatter () const inline
Definition at line 119 of file Driver.h.
 { return mFormatter; }
std::string const& cplus2asp::bcbridge::Driver::host () const inline
Gets the host that we're connecting to oClingo on.
Definition at line 133 of file Driver.h.
Referenced by main().
 { return mHost; }
bool cplus2asp::bcbridge::Driver::host (std::string const & host) inline
Sets the host that we're connecting to oClingo on.
Parameters
host the new host.
Returns
true if the host was valid, false otherwise. TODO: Validation.
Definition at line 139 of file Driver.h.
References host().
Referenced by host().
 { mHost = host; return true; }
std::string const& cplus2asp::bcbridge::Driver::port () const inline
Gets the port being used to connect to oClingo.
Definition at line 123 of file Driver.h.
Referenced by main().
 { return mPort; }
bool cplus2asp::bcbridge::Driver::port (std::string const & port) inline
Sets the port being used to connect to oClingo.
Parameters
port THe new port.
Returns
true if the port was valid, false otherwise. TODO: Validation.
Definition at line 129 of file Driver.h.
References port().
Referenced by port().
 { mPort = port; return true; }
int cplus2asp::bcbridge::Driver::run ()
Runs the driver program.
Definition at line 131 of file Driver.cpp.
References bcplus::statements::detail::TemporalLawForm< type, head_t, at_t >::at(), cplus2asp::bcbridge::copy_and_close(), babb::utils::ref_ptr< T >::get(), bcplus::statements::detail::TemporalLawForm< type, head_t, at_t >::head(), bcplus::parser::BCParser::parse(), bcplus::parser::BCParser::push_back(), bcplus::parser::BCParser::reset(), and bcplus::statements::Statement::type().
Referenced by main().
                 {
   try
   {
 /*
     std::cout   << "Entering user-interactive mode. "                                                               << std::endl
                 << "NOTICE: The reactive bridge is in alpha and is not yet complete."                               << std::endl
                 << "It's currently required that the user provide input directly in the input language of oClingo." << std::endl
                 << "Valid oClingo input consists of four components:"                                               << std::endl
                 << "    - A step declaration '#step t.' where t is a positive integer. "                            << std::endl
                 << "      This specifies the current step."                                                         << std::endl
                 << "    - A number of facts specifying the abnormality constants that have occurred."               << std::endl
                 << "      This should be of one of the forms:"                                                      << std::endl
                 << "              'ab_h(<static-abnormality>, t).' OR"                                              << std::endl
                 << "              'ab_occ(<dynamic-abnormality>,t-1).'"                                             << std::endl
                 << "      where t is the step provided in the step declaration."                                    << std::endl
                 << "    - A line containing only '#endstep.' specifying the end of input. "                         << std::endl
                 << "When you're finished, you should input 'exit' on a line by itself."                             << std::endl;
 */
     std::cout << "% Attempting to connect to oClingo..." << std::endl;
     mClient = new NetworkClient(
         mHost,
         mPort,
         boost::bind(&Driver::processOclingoPacket, this, _1, _2, _3));
     while (!mClient->open()) {
         boost::this_thread::sleep( boost::posix_time::milliseconds(200));
     }
     std::cout   << "% Connected succesfully." << std::endl
                 << "% Please provide an observation stream to send to oclingo." << std::endl
                 << "% An observation stream component is of the form:" << std::endl
                 << "% \t#step." << std::endl
                 << "% \t<rules>"<< std::endl
                 << "% \t#endstep."<<std::endl
                 << "% where <rules> is a set of observational laws " << std::endl
                 << "% \tobserved F at t." << std::endl
                 << "% and temporal constraint laws " << std::endl
                 << "% \tconstraint F at t." << std::endl
                 << "% containing no variables." << std::endl
                 << "% At any time you can input the line \"#done.\" to finish and exit." << std::endl << std::endl;
     std::string line;
     std::string trimmed;
 //  Providied by initial oClingo prompt.
 //  std::cout << "?- ";
     while (!mClosing && mClient->open() && std::getline(std::cin, line))
     {
         trimmed = line;
         boost::trim(trimmed);
         if (trimmed == "#step.") {
             mTransIn.str("");
             bool endstep = false, empty = true;
             // got a new step... collect the data until they say to stop...
             while (!mClosing && !endstep && mClient->open() && std::getline(std::cin, line)) {
                 trimmed = line;
                 boost::trim(trimmed);
                 if (trimmed == "#endstep.") {
                     endstep = true;
                 } else if (trimmed == "#done.") {
                     endstep = true;
                     mClosing = true;
                 } else {
                     empty = false;
                     // add the line to our input to parse
                     mTransIn << line << std::endl;
                 }
             }
             if (mClosing) continue;
             // parse the input
             if (!empty) {
                 std::string transin = mTransIn.str();
                 mTransOut.str("");
                 mParser->reset();
                 mParser->push_back(transin.c_str());
                 pa::BCParser::ParseType result;
                 bool ret = true;
                 int step = 0;
                 do {
                     result = mParser->parse();
                     if (result.first == pa::BCParser::Status::IO_ERR ||
                         result.first == pa::BCParser::Status::SYNTAX_ERR) ret = false;
                         if (result.second) {
                             u::ref_ptr<st::Statement> stmt = result.second;
                             switch (stmt->type()) {
                             case st::Statement::Type::LAW_OBSERVED:
{
                                     u::ref_ptr<const st::ObservedLaw> l = (st::ObservedLaw const*)stmt.get();
                                     int step2 = l->at()->val();
                                     if (l->head()->cmask() & sy::ConstantSymbol::Type::M_ACTIONS) step2++;
                                     step = (step2 > step ? step2 : step);
                                 }
                                 break;
                             case st::Statement::Type::LAW_TEMPORAL_CONSTRAINT:
{
                                     u::ref_ptr<const st::TemporalConstraintLaw> l = (st::TemporalConstraintLaw const*)stmt.get();
                                     int step2 = l->at()->val();
                                     if (l->head()->cmask() & sy::ConstantSymbol::Type::M_ACTIONS) step2++;
                                     step = (step2 > step ? step2 : step);
                                 }
                                 break;
                             default:
                                 break;
                             }
                             ret = mTranslator->translate(stmt) && ret;
                         }
                 } while (result.first != pa::BCParser::Status::END_INPUT);
                 // process it through F2LP
                 if (ret) {
                     bp::context ctx;
                     ctx.environment = bp::self::get_environment();
                     ctx.stdin_behavior  = bp::capture_stream();
                     ctx.stdout_behavior = bp::capture_stream();
                     ctx.stderr_behavior = bp::inherit_stream();
                     std::list<std::string> arglist;
                     arglist.push_back("-c");
                     arglist.push_back("-i");
                     bp::child c = bp::launch(bp::find_executable_in_path("f2lp"), arglist, ctx);
                     // send our translation data as input
 /*
 E
                     copy(std::istreambuf_iterator<char>(mTransOut), std::istreambuf_iterator<char>(),
                         std::ostreambuf_iterator<char>(c.get_stdin()));
 */
                     boost::thread workerthread(boost::bind(&copy_and_close, &mTransOut, &c.get_stdin()));
                     mF2lpOut.str("");
                     // receive data back as input
                     copy(std::istreambuf_iterator<char>(c.get_stdout()), std::istreambuf_iterator<char>(),
                         std::ostreambuf_iterator<char>(mF2lpOut));
                     // wait for F2LP to finish
                     workerthread.join();
                     bp::status s = c.wait();
                     if (s.exited() && s.exit_status()) ret = false;
                 }
                 // sanitize F2LP output for use with oClingo
                 std::stringstream tmp;
                 std::string line;
                 while (mF2lpOut.good()) {
                     std::getline(mF2lpOut, line);
                     boost::trim(line);
                     if (line[0] == '%' || line[0] == '#') continue;
                     if (line.find(":- false.") == 0) continue;
                     if (line.find("true.") == 0) continue;
 //                  if (line.find("false") == 0) line = line.substr(5);
                     tmp << line << "\n";
                 }
                 if (!ret) {
                     std::cerr << "% ERROR: An error occurred parsing the online module. The module will be ignored." << std::endl;
                 } else {
                     send(tmp.str(), step, mClosing);
                 }
         } else {
             send("", 0, mClosing);
         }
         } else if (trimmed == "#done.") {
             mClosing = true;
         } else {
             std::cerr << "% ERROR: Ignoring invalid input. Expected one of \"#step.\" or \"#done.\"." << std::endl;
         }
     }
     close(0);
   }
   catch (std::exception& e)
   {
     std::cerr << "Error: " << e.what() << std::endl;
     return 1;
   }
     return 0;
 }
bool cplus2asp::bcbridge::Driver::symtab (std::string const & symtab)
Sets the file that we're reading the symbol table from.
Parameters
symtab The new symbol table file
Returns
True if the file was read successfully, false otherwise.
Definition at line 96 of file Driver.cpp.
References cplus2asp::cplus2asp_bin::Configuration::Input::BCPLUS, and bcplus::symbols::SymbolTable::good().
Referenced by Driver(), and main().
{
     bool ret = true;
     u::ref_ptr<cplus2asp_bin::Configuration> conf = new cplus2asp_bin::Configuration("bcbridge", "1.0");
     if (symtab.size()) {
         conf->symtabInput(new ReferencedPath(symtab));
     }
     // setup the translation unit...
     conf->outputStream(mTransOut);
     conf->inputLanguage(cplus2asp_bin::Configuration::Input::BCPLUS);
     u::ref_ptr<sy::SymbolTable> st = new sy::SymbolTable(conf);
     if (!st->good()) {
         ret = false;
         conf->symtabInput(NULL);
         st = new sy::SymbolTable(conf);
     }
     mParser = new pa::BCParser(conf, new la::OBCPlus(), st);
     mTranslator = new cplus2asp_bin::Translator(conf, st);
     return ret;
 }
Member Data Documentation
std::string const cplus2asp::bcbridge::Driver::DEF_OCLINGO_HOST static
The default host to attempt to connect to oClingo at.
Definition at line 58 of file Driver.h.
Referenced by showHelp().
std::string const cplus2asp::bcbridge::Driver::DEF_OCLINGO_PORT static
The default port to attempt to connect to oClingo with.
Definition at line 55 of file Driver.h.
Referenced by showHelp().
The documentation for this class was generated from the following files:
bcbridge/Driver.h
bcbridge/Driver.cpp