cplus2asp: bcplus::parser::BCParser Class Reference
bcplus::parser::BCParser Class Reference
A parser which allows us to scan a BC+ program.
#include <BCParser.h>
Classes
struct Status
Container for status codes.
Public Types
typedef std::pair
< Status::type,
babb::utils::ref_ptr
< statements::Statement > > ParseType
The type returned by the parse function.
Public Member Functions
BCParser (Configuration const *config, languages::Language const *lang, symbols::SymbolTable *symtab=NULL)
virtual ~BCParser ()
Destructor.
ParseType parse ()
Attempts to parse the next rule from the scanner.
void reset ()
Resets the parser clearing all previous input.
bool push_back (boost::filesystem::path const &file, bool squelch=false)
Attempts to open the provided file and append it to the end of the stream being read by the scanner.
void push_back (char const *buffer, Location const &loc=Location(NULL, 0, 0))
Appends the provided null-terminated buffer to the end of the stream being read by the scanner.
symbols::SymbolTable * symtab ()
Gets the symbol table for the parser.
symbols::SymbolTable const * symtab () const
languages::Language const * lang () const
Get the language specification being enforced.
Configuration const * config () const
Get the configuration information.
void _feature_error (languages::Language::Feature::type feature, Location const *loc=NULL)
INTERNAL FUNCTION Reports the use of an unsupported feature.
void _parse_error (std::string const &err, Location const *loc=NULL)
INTERNAL FUNCTION Registers a parse error.
void _handle_stmt (statements::Statement *stmt)
symbols::SortSymbol * _newRange (elements::Term *min, elements::Term *max)
INTERNAL FUNCTION Creates a new sort containing a range provided by the min and max terms.
symbols::NumberRangeSymbol * _newRangeSymbol (elements::Term *min, elements::Term *max)
Creates a new symbol containing a range provided by the min and max terms.
Public Member Functions inherited from babb::utils::Referenced
Referenced ()
Referenced ()
Additional Inherited Members
Protected Member Functions inherited from babb::utils::Referenced
virtual ~Referenced ()
virtual ~Referenced ()
Detailed Description
A parser which allows us to scan a BC+ program.
Definition at line 28 of file BCParser.h.
Member Typedef Documentation
typedef std::pair<Status::type, babb::utils::ref_ptr<statements::Statement> > bcplus::parser::BCParser::ParseType
The type returned by the parse function.
Definition at line 44 of file BCParser.h.
Constructor & Destructor Documentation
bcplus::parser::BCParser::BCParser (Configuration const * config, languages::Language const * lang, symbols::SymbolTable * symtab = NULL)
Parameters
config The system-wide configuration information
lang The language specification that we will be enforcing
symtab The symbol table to use, or NULL to create one using the configuration options.
Definition at line 38 of file BCParser.cpp.
References lemon_parserAlloc(), bcplus::parser::BCParser::Status::OK, and symtab().
     : _config(config), _lang(lang), _rangeCount(0) {
     if (symtab) _symtab = symtab;
     else _symtab = new symbols::SymbolTable(config);
     _scanner = new detail::MacroParser(config, lang, _symtab);
     _parser = lemon_parserAlloc(malloc);
     _stat = Status::OK;
 }
bcplus::parser::BCParser::~BCParser () virtual
Destructor.
Definition at line 48 of file BCParser.cpp.
References lemon_parserFree().
                     {
     lemon_parserFree(_parser, free);
 }
Member Function Documentation
void bcplus::parser::BCParser::_feature_error (languages::Language::Feature::type feature, Location const * loc = NULL)
INTERNAL FUNCTION Reports the use of an unsupported feature.
Parameters
feature The unsupported feature that was used.
loc The location of the error.
Definition at line 206 of file BCParser.cpp.
References bcplus::parser::Token::beginLoc(), bcplus::Verb::ERROR, bcplus::languages::Language::featureDescription(), lang(), bcplus::languages::Language::name(), and bcplus::parser::BCParser::Status::SYNTAX_ERR.
{
     std::ostream& out = _config->ostream(Verb::ERROR);
     out << "ERROR: ";
     if (loc) {
         out << *loc << ": ";
     } else {
         Token const* t = _last_token;
         if (t) {
             out << t->beginLoc() << ": \"" << *t << "\": ";
         }
     }
     out << lang()->featureDescription(feature) << " are not supported by language " << lang()->name() << "." << std::endl;
     _stat = Status::SYNTAX_ERR;
 }
void bcplus::parser::BCParser::_handle_stmt (statements::Statement * stmt)
Definition at line 236 of file BCParser.cpp.
References bcplus::Verb::TRACE_PARSER, and bcplus::statements::Statement::typeString().
{
 #ifndef NDEBUG
     _config->ostream(Verb::TRACE_PARSER) << "TRACE: Got statement of type \"" << stmt->typeString() << "\"." << std::endl;
 #endif
     _stmt = stmt;
 }
symbols::SortSymbol * bcplus::parser::BCParser::_newRange (elements::Term * min, elements::Term * max)
INTERNAL FUNCTION Creates a new sort containing a range provided by the min and max terms.
Definition at line 244 of file BCParser.cpp.
References _newRangeSymbol(), babb::utils::ref_ptr< T >::release(), and symtab().
{
     u::ref_ptr<elements::Term> minptr = min, maxptr = max;
     // create a new number range object
     u::ref_ptr<const symbols::NumberRangeSymbol> rsym = _newRangeSymbol(min,max);
     if (!rsym) return NULL;
     // create a new sort
     u::ref_ptr<symbols::SortSymbol> s = new symbols::SortSymbol(new ReferencedString("_rsort_" + boost::lexical_cast<std::string>(_rangeCount)));
     if (!symtab()->create(s)) {
         return NULL;
     }
     // add the range
     s->add(rsym);
     return s.release();
 }
symbols::NumberRangeSymbol * bcplus::parser::BCParser::_newRangeSymbol (elements::Term * min, elements::Term * max)
Creates a new symbol containing a range provided by the min and max terms.
Definition at line 264 of file BCParser.cpp.
References babb::utils::ref_ptr< T >::release(), bcplus::symbols::Resolver::resolveOrCreate(), and symtab().
Referenced by _newRange().
{
     u::ref_ptr<elements::Term> minptr = min, maxptr = max;
     // create a new number range object
     u::ref_ptr<symbols::NumberRangeSymbol> rsym = symtab()->resolveOrCreate(
         new symbols::NumberRangeSymbol(
             new ReferencedString("_range_" + boost::lexical_cast<std::string>(++_rangeCount)),
             min, max));
     return rsym.release();
 }
void bcplus::parser::BCParser::_parse_error (std::string const & err, Location const * loc = NULL)
INTERNAL FUNCTION Registers a parse error.
Parameters
err The error to register
loc The location of the error.
Definition at line 221 of file BCParser.cpp.
References bcplus::parser::Token::beginLoc(), bcplus::Verb::ERROR, and bcplus::parser::BCParser::Status::SYNTAX_ERR.
Referenced by parse().
{
     std::ostream& out = _config->ostream(Verb::ERROR);
     out << "ERROR: ";
     if (loc) {
         out << *loc << ": ";
     } else {
         Token const* t = _last_token;
         if (t) {
             out << t->beginLoc() << ": \"" << *t << "\": ";
         }
     }
     out << error << std::endl;
     _stat = Status::SYNTAX_ERR;
 }
Configuration const* bcplus::parser::BCParser::config () const inline
Get the configuration information.
Definition at line 124 of file BCParser.h.
 { return _config; }
languages::Language const* bcplus::parser::BCParser::lang () const inline
Get the language specification being enforced.
Definition at line 121 of file BCParser.h.
Referenced by _feature_error().
 { return _lang; }
BCParser::ParseType bcplus::parser::BCParser::parse ()
Attempts to parse the next rule from the scanner.
Returns
A status code and the parsed rule if the status is OK, or NULL otherwise.
Definition at line 67 of file BCParser.cpp.
References _parse_error(), bcplus::parser::BCParser::Status::END_INPUT, lemon_parser(), lemon_parserAttemptReduce(), lemon_parserTrace(), bcplus::parser::BCParser::Status::OK, babb::utils::ref_ptr< T >::release(), T_EOF, T_ERR_IO, T_ERR_PAREN_MISMATCH, T_ERR_SYNTAX, T_ERR_UNKNOWN_SYMBOL, T_ERR_UNTERMINATED_ASP, T_ERR_UNTERMINATED_BLK_COMMENT, T_ERR_UNTERMINATED_F2LP, T_ERR_UNTERMINATED_LUA, T_ERR_UNTERMINATED_STRING, T_PERIOD, and bcplus::Verb::TRACE_PARSER.
Referenced by main(), and cplus2asp::bcbridge::Driver::run().
{
     u::ref_ptr<const Token> token;
     u::ref_ptr<statements::Statement> stmt;
     // output any comments
     if (stmt = makeCommentStmt()) return ParseType(Status::OK, stmt);
     // output existing statement
     if (_stmt) {
         stmt = _stmt;
         _stmt = NULL;
         return ParseType(Status::OK, stmt);
     }
     // if we're at the end of input don't bother progressing
     if (_stat == Status::END_INPUT) {
         return ParseType(Status::END_INPUT, NULL);
     }
     _stat = Status::OK;
 #ifndef NDEBUG
     if (_config->parseTrace())
         lemon_parserTrace(stdout, "TRACE: Parser: ");
 #endif
     // parse a new statement
     do {
         token = _scanner->next();
         int type = token->type();
         // track the soft end of file flag
         if (type != T_EOF) _soft_eof = false;
         switch (type) {
         case T_ERR_IO:
             // an IO error occurred
             _parse_error("An IO error occurred reading from \"" + token->beginLoc().filename() + "\".", &token->beginLoc());
             break;
         case T_ERR_UNTERMINATED_STRING:
             _parse_error("Unexpected end of input. Unterminated string.", &token->beginLoc());
             break;
         case T_ERR_UNTERMINATED_ASP:
             _parse_error("Unexpected end of input. Unterminated ASP code block.", &token->beginLoc());
             break;
         case T_ERR_UNTERMINATED_LUA:
             _parse_error("Unexpected end of input. Unterminated LUA code block.", &token->beginLoc());
             break;
         case T_ERR_UNTERMINATED_F2LP:
             _parse_error("Unexpected end of input. Unterminated F2LP code block.", &token->beginLoc());
             break;
         case T_ERR_UNTERMINATED_BLK_COMMENT:
             _parse_error("Unexpected end of input. Unterminated block comment.", &token->beginLoc());
             break;
         case T_ERR_SYNTAX:
             _parse_error("Syntax error.", &token->beginLoc());
             break;
         case T_ERR_UNKNOWN_SYMBOL:
             _parse_error("Unknown symbol \"" + *token->str() + "\".", &token->beginLoc());
             break;
         case T_ERR_PAREN_MISMATCH:
             _parse_error("Detected umatched open parentheses.", &token->beginLoc());
             break;
         case T_EOF:
 #ifndef NDEBUG
             _config->ostream(Verb::TRACE_PARSER) << "TRACE: Hard EOF." << std::endl;
 #endif
             _last_token = token;
             lemon_parser(_parser, type, token.release(), this);
             lemon_parserAttemptReduce(_parser, this);
             _stat = Status::END_INPUT;
             break;
         default:
             _last_token = token;
             lemon_parser(_parser, type, token.release(), this);
             // This forces this parser to reduce each previous statement before
             // looking ahead. This allows the MacroParser to perform just-in-time
             // identifier binding to disambiguate our grammer at this level.
             if (type == T_PERIOD) {
                 lemon_parserAttemptReduce(_parser, this);
             }
             break;
         }
     } while (!_stmt && _stat == Status::OK);
 #ifndef NDEBUG
     if (_config->parseTrace())
         lemon_parserTrace(NULL, NULL);
 #endif
     // Figure out exactly why we stopped
     if (_stat != Status::OK && _stat != Status::END_INPUT) {
         return ParseType(_stat, NULL);
 //  } else if (stmt = makeCommentStmt()) {
 //      return ParseType(Status::OK, stmt);
     } else {
         stmt = _stmt;
         _stmt = NULL;
         return ParseType(Status::OK, stmt);
     }
 }
bool bcplus::parser::BCParser::push_back (boost::filesystem::path const & file, bool squelch = false)
Attempts to open the provided file and append it to the end of the stream being read by the scanner.
Parameters
file The file to read from.
squelch Whether to silence all errors resulting from this call.
Returns
True if successful, false otherwise.
Referenced by main(), and cplus2asp::bcbridge::Driver::run().
void bcplus::parser::BCParser::push_back (char const * buffer, Location const & loc = Location(NULL, 0, 0))
Appends the provided null-terminated buffer to the end of the stream being read by the scanner.
Parameters
buffer The null-terminated buffer to read from.
loc The location to display in messages partaining to this buffer.
Definition at line 202 of file BCParser.cpp.
{
     _scanner->push_back(buffer, loc);
 }
void bcplus::parser::BCParser::reset ()
Resets the parser clearing all previous input.
Definition at line 187 of file BCParser.cpp.
References lemon_parserAlloc(), lemon_parserFree(), and bcplus::parser::BCParser::Status::OK.
Referenced by cplus2asp::bcbridge::Driver::run().
                      {
     _scanner->reset();
     lemon_parserFree(_parser, free);
     _parser = lemon_parserAlloc(malloc);
     _stat = Status::OK;
     _stmt = NULL;
     _soft_eof = false;
 }
symbols::SymbolTable* bcplus::parser::BCParser::symtab () inline
Gets the symbol table for the parser.
Definition at line 117 of file BCParser.h.
Referenced by _newRange(), _newRangeSymbol(), and BCParser().
 { return _symtab; }
symbols::SymbolTable const* bcplus::parser::BCParser::symtab () const inline
Definition at line 118 of file BCParser.h.
 { return _symtab; }
The documentation for this class was generated from the following files:
bcplusparser/include/bcplus/parser/BCParser.h
bcplusparser/src/bcplus/parser/BCParser.cpp