cplus2asp: bcplus::parser::detail::ScannerTokenSource Class Reference
bcplus::parser::detail::ScannerTokenSource Class Reference
Scanner source encapsulates a stream of scanner tokens.
#include <ScannerTokenSource.h>
Public Types
typedef ReferencedList
< babb::utils::ref_ptr< Token >
>::type TokenList
typedef TokenList::iterator iterator
typedef TokenList::const_iterator const_iterator
Public Member Functions
ScannerTokenSource (TokenList *stream)
Initalizes the token stream to the provided value.
ScannerTokenSource (Token *token=NULL)
Initializes the token stream with one or no tokens.
virtual ~ScannerTokenSource ()
Destructor stub.
void push_front (Token *token)
injects a token into the stream to be read next
void push_front (TokenList *tokens)
injects tokens into the stream to be read next
void push_back (Token *token)
Adds a token to the end of the stream to be read last.
void push_back (TokenList *tokens)
Adds tokens to the end of the stream to be read last.
size_t size () const
Determines how many tokens are in the stream.
Token * next ()
Pops the next token in the stream and returns it.
Token * peak () const
Peaks at the next token in the stream.
const_iterator begin () const
Iterates over the token stream.
iterator begin ()
const_iterator end () const
iterator end ()
virtual Location loc () const
Get the location that the source stream is at.
Public Member Functions inherited from bcplus::parser::detail::ScannerSource
ScannerSource (Type::type type)
Basic Constructor.
virtual ~ScannerSource ()
Destructor stub.
Type::type type () const
Get the subtype of this source.
Public Member Functions inherited from babb::utils::Referenced
Referenced ()
Referenced ()
Additional Inherited Members
Protected Member Functions inherited from babb::utils::Referenced
virtual ~Referenced ()
virtual ~Referenced ()
Detailed Description
Scanner source encapsulates a stream of scanner tokens.
Definition at line 18 of file ScannerTokenSource.h.
Member Typedef Documentation
typedef TokenList::const_iterator bcplus::parser::detail::ScannerTokenSource::const_iterator
Definition at line 29 of file ScannerTokenSource.h.
typedef TokenList::iterator bcplus::parser::detail::ScannerTokenSource::iterator
Definition at line 28 of file ScannerTokenSource.h.
typedef ReferencedList<babb::utils::ref_ptr<Token> >::type bcplus::parser::detail::ScannerTokenSource::TokenList
Definition at line 25 of file ScannerTokenSource.h.
Constructor & Destructor Documentation
bcplus::parser::detail::ScannerTokenSource::ScannerTokenSource (TokenList * stream)
Initalizes the token stream to the provided value.
Parameters
stream The token stream to use for this source.
Definition at line 11 of file ScannerTokenSource.cpp.
     : ScannerSource(ScannerSource::Type::TOKENS), _stream(stream) {
     /* Intentionally left blank */
 }
bcplus::parser::detail::ScannerTokenSource::ScannerTokenSource (Token * token = NULL)
Initializes the token stream with one or no tokens.
Parameters
token The token to add to the token stream (or NULL to create an empty stream)
Definition at line 16 of file ScannerTokenSource.cpp.
     : ScannerSource(ScannerSource::Type::TOKENS) {
     _stream = new TokenList();
     if (token) _stream->push_back(token);
 }
bcplus::parser::detail::ScannerTokenSource::~ScannerTokenSource () virtual
Destructor stub.
Definition at line 22 of file ScannerTokenSource.cpp.
{
     /* Intentionally left blank */
 }
Member Function Documentation
const_iterator bcplus::parser::detail::ScannerTokenSource::begin () const inline
Iterates over the token stream.
Definition at line 91 of file ScannerTokenSource.h.
 { return _stream->begin(); }
iterator bcplus::parser::detail::ScannerTokenSource::begin () inline
Definition at line 92 of file ScannerTokenSource.h.
 { return _stream->begin(); }
const_iterator bcplus::parser::detail::ScannerTokenSource::end () const inline
Definition at line 93 of file ScannerTokenSource.h.
 { return _stream->end(); }
iterator bcplus::parser::detail::ScannerTokenSource::end () inline
Definition at line 94 of file ScannerTokenSource.h.
 { return _stream->end(); }
Location bcplus::parser::detail::ScannerTokenSource::loc () const virtual
Get the location that the source stream is at.
Implements bcplus::parser::detail::ScannerSource.
Definition at line 54 of file ScannerTokenSource.cpp.
References size().
{
     return (size() ? _stream->front()->beginLoc() : Location(NULL, 0, 0));
 }
Token * bcplus::parser::detail::ScannerTokenSource::next ()
Pops the next token in the stream and returns it.
Returns
The next token or NULL if the stream is empty
Definition at line 40 of file ScannerTokenSource.cpp.
References size(), and T_EOF.
{
     if (size()) {
         Token* t = _stream->front().release();
         _stream->pop_front();
         return t;
     } else return new Token(T_EOF, new ReferencedString("<EOF>"), Location(NULL, 0, 0), Location(NULL, 0, 0));
 }
Token * bcplus::parser::detail::ScannerTokenSource::peak () const
Peaks at the next token in the stream.
Returns
The next token or NULL if the stream is empty
Definition at line 49 of file ScannerTokenSource.cpp.
References size().
{
     if (size()) return _stream->front().release();
     else return NULL;
 }
void bcplus::parser::detail::ScannerTokenSource::push_back (Token * token) inline
Adds a token to the end of the stream to be read last.
Parameters
token The token to inject
Definition at line 71 of file ScannerTokenSource.h.
 { _stream->push_back(token); }
void bcplus::parser::detail::ScannerTokenSource::push_back (TokenList * tokens)
Adds tokens to the end of the stream to be read last.
Parameters
tokens The tokens to inject
Definition at line 33 of file ScannerTokenSource.cpp.
{
     for (const_iterator it = tokens->begin(); it != tokens->end(); it++) {
         _stream->push_back(*it);
     }
 }
void bcplus::parser::detail::ScannerTokenSource::push_front (Token * token) inline
injects a token into the stream to be read next
Parameters
token the token to inject
Definition at line 63 of file ScannerTokenSource.h.
 { _stream->push_front(token); }
void bcplus::parser::detail::ScannerTokenSource::push_front (TokenList * tokens)
injects tokens into the stream to be read next
Parameters
tokens the tokens to inject
Definition at line 26 of file ScannerTokenSource.cpp.
{
     for (const_iterator it = tokens->end(); it != tokens->begin(); it--) {
         _stream->push_front(*it);
     }
 }
size_t bcplus::parser::detail::ScannerTokenSource::size () const inline
Determines how many tokens are in the stream.
Parameters
the number of tokens in the stream
Definition at line 79 of file ScannerTokenSource.h.
Referenced by loc(), next(), and peak().
 { return _stream->size(); }
The documentation for this class was generated from the following files:
bcplusparser/include/bcplus/parser/detail/ScannerTokenSource.h
bcplusparser/src/bcplus/parser/detail/ScannerTokenSource.cpp