cplus2asp: bcplus::parser::Token Class Reference
bcplus::parser::Token Class Reference
A simple token structure.
#include <Token.h>
Public Member Functions
Token (int type, ReferencedString const *string, Location const &begin, Location const &end)
Basic Constructor.
virtual ~Token ()
Destructor.
int type () const
Accessors.
ReferencedString const * str () const
Location const & beginLoc () const
Location const & endLoc () const
char const * typeString () const
void type (int t)
Change the token type.
Token * copy () const
Deep copies the token.
int macroType () const
determines the macro parser equivalent for the token type
std::ostream & output (std::ostream &out) const
Outputs the token to the provided output stream.
Public Member Functions inherited from babb::utils::Referenced
Referenced ()
Referenced ()
Static Public Member Functions
static char const * typeString (int token)
Static functions Get the name of the provided token type.
Additional Inherited Members
Protected Member Functions inherited from babb::utils::Referenced
virtual ~Referenced ()
virtual ~Referenced ()
Detailed Description
A simple token structure.
Definition at line 15 of file Token.h.
Constructor & Destructor Documentation
bcplus::parser::Token::Token (int type, ReferencedString const * string, Location const & begin, Location const & end)
Basic Constructor.
Definition at line 11 of file Token.cpp.
Referenced by copy().
     : _type(type), _string(string), _begin(begin), _end(end) {
     // Inentionally left blank
 }
bcplus::parser::Token::~Token () virtual
Destructor.
Definition at line 16 of file Token.cpp.
               {
     // Intentionally left blank
 }
Member Function Documentation
Location const& bcplus::parser::Token::beginLoc () const inline
Definition at line 37 of file Token.h.
Referenced by bcplus::parser::BCParser::_feature_error(), bcplus::parser::detail::MacroParser::_feature_error(), bcplus::parser::BCParser::_parse_error(), bcplus::parser::detail::MacroParser::_parse_error(), and copy().
 { return _begin; }
Token * bcplus::parser::Token::copy () const
Deep copies the token.
Definition at line 20 of file Token.cpp.
References beginLoc(), endLoc(), str(), Token(), and type().
{
     return new Token(type(), str(), beginLoc(), endLoc());
 }
Location const& bcplus::parser::Token::endLoc () const inline
Definition at line 38 of file Token.h.
Referenced by copy().
 { return _end; }
int bcplus::parser::Token::macroType () const
determines the macro parser equivalent for the token type
Definition at line 28 of file Token.cpp.
References M_ARG, M_COLON_DASH, M_COMMA, M_EOF, M_IDENTIFIER, M_INCLUDE, M_INTEGER, M_OTHER, M_PAREN_L, M_PAREN_R, M_PERIOD, M_SEMICOLON, M_STRING_LITERAL, T_ARG, T_COLON_DASH, T_COMMA, T_EOF, T_IDENTIFIER, T_INCLUDE, T_INTEGER, T_PAREN_L, T_PAREN_R, T_PERIOD, T_SEMICOLON, T_STRING_LITERAL, and type().
{
     switch (type()) {
         case T_COMMA:                           return M_COMMA;
         case T_PAREN_L:                         return M_PAREN_L;
         case T_PAREN_R:                         return M_PAREN_R;
         case T_ARG:                             return M_ARG;
         case T_EOF:                             return M_EOF;
         case T_IDENTIFIER:                      return M_IDENTIFIER;
         case T_INTEGER:                         return M_INTEGER;
         case T_INCLUDE:                         return M_INCLUDE;
         case T_COLON_DASH:                      return M_COLON_DASH;
         case T_PERIOD:                          return M_PERIOD;
         case T_SEMICOLON:                       return M_SEMICOLON;
         case T_STRING_LITERAL:                  return M_STRING_LITERAL;
         default:                                return M_OTHER;
     }
 }
std::ostream & bcplus::parser::Token::output (std::ostream & out) const
Outputs the token to the provided output stream.
Parameters
out The output stream to write to
Definition at line 46 of file Token.cpp.
References str().
Referenced by operator<<().
{
     out << *str();
     return out;
 }
ReferencedString const* bcplus::parser::Token::str () const inline
Definition at line 36 of file Token.h.
Referenced by copy(), output(), and cplus2asp::cplus2asp_bin::Translator::translate().
 { return _string; }
int bcplus::parser::Token::type () const inline
Accessors.
Definition at line 35 of file Token.h.
Referenced by copy(), macroType(), and typeString().
 { return _type; }
void bcplus::parser::Token::type (int t) inline
Change the token type.
Definition at line 42 of file Token.h.
 { _type = t; }
char const * bcplus::parser::Token::typeString (int token) static
Static functions Get the name of the provided token type.
Definition at line 24 of file Token.cpp.
References lemon_parserTokenName().
{
     return lemon_parserTokenName(token);
 }
char const* bcplus::parser::Token::typeString () const inline
Definition at line 39 of file Token.h.
References type(), and typeString().
Referenced by typeString().
 { return typeString(type()); }
The documentation for this class was generated from the following files:
bcplusparser/include/bcplus/parser/Token.h
bcplusparser/src/bcplus/parser/Token.cpp