cplus2asp: bcplus::parser::detail::MacroParser Class Reference
bcplus::parser::detail::MacroParser Class Reference
A parser which allows us to scan a BC+ program.
#include <MacroParser.h>
Classes
struct Status
Public Types
typedef ReferencedList
< babb::utils::ref_ptr< Token >
>::type TokenBuffer
The type returned by the parse function.
Public Member Functions
MacroParser (Configuration const *config, languages::Language const *lang, symbols::SymbolTable *symtab=NULL)
virtual ~MacroParser ()
Destructor.
Token const * next ()
Attempts to parse the next non-comment token, resolving all macros and include statements in the process.
Token const * comment ()
Determines if there is a comment token waiting, if there is it returns it.
void reset ()
Resets the parser clearing all previous input.
symbols::SymbolTable * symtab ()
Gets the symbol table for the parser.
symbols::SymbolTable const * symtab () const
languages::Language const * lang () const
Get the language specification being enforced.
Configuration const * config () const
Get the configuration information.
bool push_back (boost::filesystem::path const &file, bool squelch=false)
Attempts to open the provided file and append it to the end of the stream being read by the scanner.
void push_back (char const *buffer, Location const &loc=Location(NULL, 0, 0), bool track=false)
Appends the provided null-terminated buffer to the end of the stream being read by the scanner.
void push_back (Token *token)
Appends the provided token to the end of the stream being read by the scanner.
void _feature_error (languages::Language::Feature::type feature, Location const *loc=NULL)
INTERNAL FUNCTION Reports the use of an unsupported feature.
void _parse_error (std::string const &err, Location const *loc=NULL)
INTERNAL FUNCTION Registers a parse error.
void _token (Token *token)
callback for the lemon parser to provide another token to the post-parse token stream.
void _handle_macro (elements::Macro const *macro)
callback for the lemon parser to handle macro expansion
void _handle_include (statements::IncludeStatement const *incl)
callback for the lemon parser to handle file inclusion
void _handle_macro_def (statements::MacroDeclaration *decl)
callback for the lemon parser to handle macro definitions
bool _push_front (boost::filesystem::path const &file, bool squelch=false)
Attempts to open the provided file and append it to the beginning of the input stream being read from.
void _push_front (char const *buffer, Location const &loc=Location(NULL, 0, 0), bool track=false)
Appends the provided null-terminated buffer to the beginning of the inptu stream being read from.
void _push_front (Token *token)
Appends the provided token to beginning of the input stream being read from.
Public Member Functions inherited from babb::utils::Referenced
Referenced ()
Referenced ()
Additional Inherited Members
Protected Member Functions inherited from babb::utils::Referenced
virtual ~Referenced ()
virtual ~Referenced ()
Detailed Description
A parser which allows us to scan a BC+ program.
Definition at line 27 of file MacroParser.h.
Member Typedef Documentation
typedef ReferencedList<babb::utils::ref_ptr<Token> >::type bcplus::parser::detail::MacroParser::TokenBuffer
The type returned by the parse function.
Definition at line 43 of file MacroParser.h.
Constructor & Destructor Documentation
bcplus::parser::detail::MacroParser::MacroParser (Configuration const * config, languages::Language const * lang, symbols::SymbolTable * symtab = NULL)
Parameters
config The system-wide configuration information
lang The language specification that we will be enforcing
symtab The symbol table to use, or NULL to create one using the configuration options.
Definition at line 32 of file MacroParser.cpp.
References lemon_macroAlloc(), bcplus::parser::detail::MacroParser::Status::OK, and symtab().
     : _config(config), _lang(lang) {
     if (symtab) _symtab = symtab;
     else _symtab = new symbols::SymbolTable(config);
     _scanner = new detail::Scanner(config);
     _parser = lemon_macroAlloc(malloc);
     _stat = Status::OK;
 }
bcplus::parser::detail::MacroParser::~MacroParser () virtual
Destructor.
Definition at line 41 of file MacroParser.cpp.
References lemon_macroFree().
{
     lemon_macroFree(_parser, free);
 }
Member Function Documentation
void bcplus::parser::detail::MacroParser::_feature_error (languages::Language::Feature::type feature, Location const * loc = NULL)
INTERNAL FUNCTION Reports the use of an unsupported feature.
Parameters
feature The unsupported feature that was used.
loc The location of the error
Definition at line 146 of file MacroParser.cpp.
References bcplus::parser::Token::beginLoc(), bcplus::parser::detail::MacroParser::Status::ERR_SYNTAX, bcplus::Verb::ERROR, bcplus::languages::Language::featureDescription(), lang(), and bcplus::languages::Language::name().
{
     std::ostream& out = _config->ostream(Verb::ERROR);
     out << "ERROR: ";
     if (loc) {
         out << *loc << ": ";
     } else {
         Token const* t = _last_token;
         if (t) {
             out << t->beginLoc() << ": \"" << *t << "\": ";
         }
     }
     out << lang()->featureDescription(feature) << " are not supported by language " << lang()->name() << "." << std::endl;
     _stat = Status::ERR_SYNTAX;
 }
void bcplus::parser::detail::MacroParser::_handle_include (statements::IncludeStatement const * incl)
callback for the lemon parser to handle file inclusion
Definition at line 180 of file MacroParser.cpp.
References _push_front(), bcplus::statements::Statement::beginLoc(), bcplus::Verb::DETAIL, bcplus::parser::detail::MacroParser::Status::ERR_IO, bcplus::parser::detail::MacroParser::Status::ERR_SYNTAX, bcplus::Verb::ERROR, and bcplus::Location::file().
{
 #ifndef NDEBUG
     _config->ostream(Verb::DETAIL) << "TRACE: Got include statement!" << std::endl;
 #endif
     Location l = stmt->beginLoc();
     BOOST_FOREACH(ReferencedString const* name, *stmt) {
         fs::path p = fs::path(*name);
         try {
             // Try to resolve the name
             fs::path fullpath;
             // try to resolve the path of the file
             if (p.is_absolute() || !l.file()) {
                 fullpath = p;
             } else if (!l.file()) {
                 fullpath = fs::current_path() / p;
             } else {
                 // Try a path relative to the current file we're in first
                 // Then try resolving with our default path.
                 fullpath = l.file()->parent_path() / p;
                 if (!fs::exists(fullpath) || fs::is_directory(fullpath)) {
                     fullpath = fs::current_path() / p;
                 }
             }
             if (!fs::exists(fullpath)) {
                 // We were unable to resolve the file..
                 std::ostream& out = _config->ostream(Verb::ERROR);
                 out << "ERROR: " << l << ": Could not open file \"" << p.native() << "\". File does not exist." << std::endl;
                 _stat = Status::ERR_SYNTAX;
                 break;
             }
             if (fs::is_directory(fullpath)) {
                 // We were unable to resolve the file..
                 std::ostream& out = _config->ostream(Verb::ERROR);
                 out << "ERROR: " << l << ": Could not open file \"" << p.native() << "\". The file is a directory." << std::endl;
                 _stat = Status::ERR_SYNTAX;
                 break;
                 // We can't open a directory.
             }
             // The file appears to be good.
             if (!_push_front(fullpath, false)) {
                 std::ostream& out = _config->ostream(Verb::ERROR);
                 out << "ERROR: " << l << ": An error occurred openning file \"" << p.native() << "\"." << std::endl;
                 _stat = Status::ERR_IO;
                 break;
             }
         } catch (fs::filesystem_error& err) {
             std::ostream& out = _config->ostream(Verb::ERROR);
             out << "ERROR: " << l << ": An error occurred openning file \"" << p.native() << "\"." << std::endl;
             _stat = Status::ERR_IO;
             break;
         }
     }
 }
void bcplus::parser::detail::MacroParser::_handle_macro (elements::Macro const * macro)
callback for the lemon parser to handle macro expansion
Definition at line 275 of file MacroParser.cpp.
References _push_front(), bcplus::elements::Element::beginLoc(), and bcplus::elements::Macro::expand().
{
     u::ref_ptr<const elements::Macro> macro_ptr = macro;
     // Expand it!
     _push_front(macro->expand()->c_str(), macro->beginLoc(), false);
 }
void bcplus::parser::detail::MacroParser::_handle_macro_def (statements::MacroDeclaration * decl)
callback for the lemon parser to handle macro definitions
void bcplus::parser::detail::MacroParser::_parse_error (std::string const & err, Location const * loc = NULL)
INTERNAL FUNCTION Registers a parse error.
Parameters
err The error to register
loc The location of the error
Definition at line 161 of file MacroParser.cpp.
References bcplus::parser::Token::beginLoc(), bcplus::parser::detail::MacroParser::Status::ERR_SYNTAX, and bcplus::Verb::ERROR.
{
     std::ostream& out = _config->ostream(Verb::ERROR);
     out << "ERROR: ";
     if (loc) {
         out << *loc << ": ";
     } else {
         Token const* t = _last_token;
         if (t) {
             out << t->beginLoc() << ": \"" << *t << "\": ";
         }
     }
     out << error << std::endl;
     _stat = Status::ERR_SYNTAX;
 }
bool bcplus::parser::detail::MacroParser::_push_front (boost::filesystem::path const & file, bool squelch = false)
Attempts to open the provided file and append it to the beginning of the input stream being read from.
Parameters
file The file to read from.
squelch Whether to silence all errors resulting from this call.
Returns
True if successful, false otherwise.
Referenced by _handle_include(), and _handle_macro().
void bcplus::parser::detail::MacroParser::_push_front (char const * buffer, Location const & loc = Location(NULL, 0, 0), bool track = false)
Appends the provided null-terminated buffer to the beginning of the inptu stream being read from.
Parameters
buffer The null-terminated buffer to read from.
loc The location to display in messages partaining to this buffer.
track Whether to track the position offset of each token within the buffer.
Definition at line 249 of file MacroParser.cpp.
{
     preInjectPrep();
     _scanner->push_front(buffer, loc, track);
 }
void bcplus::parser::detail::MacroParser::_push_front (Token * token)
Appends the provided token to beginning of the input stream being read from.
Parameters
token The token to append.
Definition at line 254 of file MacroParser.cpp.
{
     preInjectPrep();
     _scanner->push_front(token);
 }
void bcplus::parser::detail::MacroParser::_token (Token * token)
callback for the lemon parser to provide another token to the post-parse token stream.
Definition at line 176 of file MacroParser.cpp.
{
     _tokens.push_back(t);
 }
Token const * bcplus::parser::detail::MacroParser::comment ()
Determines if there is a comment token waiting, if there is it returns it.
Definition at line 116 of file MacroParser.cpp.
{
     if (_comments.size()) {
         Token const* t = _comments.front().release();
         _comments.pop_front();
         return t;
     } else return NULL;
 }
Configuration const* bcplus::parser::detail::MacroParser::config () const inline
Get the configuration information.
Definition at line 111 of file MacroParser.h.
 { return _config; }
languages::Language const* bcplus::parser::detail::MacroParser::lang () const inline
Get the language specification being enforced.
Definition at line 108 of file MacroParser.h.
Referenced by _feature_error().
 { return _lang; }
Token const * bcplus::parser::detail::MacroParser::next ()
Attempts to parse the next non-comment token, resolving all macros and include statements in the process.
Returns
The parsed token (if any).
Definition at line 46 of file MacroParser.cpp.
References bcplus::parser::detail::MacroParser::Status::END_INPUT, lemon_macro(), lemon_macroAttemptReduce(), M_PAREN_R, bcplus::parser::detail::MacroParser::Status::OK, babb::utils::ref_ptr< T >::release(), T_COMMENT, T_EOF, T_ERR_SYNTAX, and bcplus::Verb::TRACE_MACRO_PARSER.
{
     u::ref_ptr<Token> token;
     // pick up any statement that was generated simultaneously with an error (just in case)
     if (_tokens.size()) {
         token = _tokens.front();
         _tokens.pop_front();
     } else if (_stat == Status::END_INPUT) {
         token = new Token(T_EOF, new ReferencedString("<EOF>"), _scanner->loc(), _scanner->loc());
     } else {
         _stat = Status::OK;
         bool soft_eof = false;
         do {
             token = _scanner->readToken();
             int macro_type = token->macroType();
             switch (token->type()) {
             case T_EOF:
                 // only fed it to the parser if it's a hard EOF (i.e. we already encoutnered a soft EOF)
                 if (soft_eof) {
 #ifndef NDEBUG
                     _config->ostream(Verb::TRACE_MACRO_PARSER) << "TRACE: Macro parser hard EOF." << std::endl;
 #endif
                     _last_token = token;
                     lemon_macro(_parser, macro_type, token.release(), this);
                     _stat = Status::END_INPUT;
                 } else {
 #ifndef NDEBUG
                     _config->ostream(Verb::TRACE_MACRO_PARSER) << "TRACE: Macro parser soft EOF." << std::endl;
 #endif
                     soft_eof = true;
                     lemon_macroAttemptReduce(_parser, this);
                 }
                 break;
             case T_COMMENT:
                 _comments.push_back(token);
                 break;
             default:
                 _last_token = token;
                 lemon_macro(_parser, macro_type, token.release(), this);
                 // if it was a close paren try to reduce the parser stack right away.
                 // this is to avoid having the argument expansion process gum up the
                 // scanner conditions.
                 if (macro_type == M_PAREN_R) lemon_macroAttemptReduce(_parser, this);
                 break;
             }
         } while (!_tokens.size() && _stat == Status::OK);
         if (_stat == Status::END_INPUT && !_tokens.size()) {
             token = new Token(T_EOF, new ReferencedString("<EOF>"), _scanner->loc(), _scanner->loc());
         } else if (_stat == Status::END_INPUT || _stat == Status::OK) {
             token = _tokens.front();
             _tokens.pop_front();
         } else {
             token = new Token(T_ERR_SYNTAX, new ReferencedString("<ERR_SYNTAX>"), _scanner->loc(), _scanner->loc());
         }
     }
 #ifndef NDEBUG
     _config->ostream(Verb::TRACE_MACRO_PARSER) << "TRACE: " << token->beginLoc() << ": (" << token->typeString() << "): \"" << *token << "\": Read from macro parser." << std::endl;
 #endif
     return token.release();
 }
bool bcplus::parser::detail::MacroParser::push_back (boost::filesystem::path const & file, bool squelch = false)
Attempts to open the provided file and append it to the end of the stream being read by the scanner.
Parameters
file The file to read from.
squelch Whether to silence all errors resulting from this call.
Returns
True if successful, false otherwise.
void bcplus::parser::detail::MacroParser::push_back (char const * buffer, Location const & loc = Location(NULL, 0, 0), bool track = false)
Appends the provided null-terminated buffer to the end of the stream being read by the scanner.
Parameters
buffer The null-terminated buffer to read from.
loc The location to display in messages partaining to this buffer.
track Whether to track the position offset of each token within the buffer.
Definition at line 137 of file MacroParser.cpp.
{
     _scanner->push_back(buffer, loc, track);
 }
void bcplus::parser::detail::MacroParser::push_back (Token * token)
Appends the provided token to the end of the stream being read by the scanner.
Parameters
token The token to append.
Definition at line 141 of file MacroParser.cpp.
{
     _scanner->push_back(token);
 }
void bcplus::parser::detail::MacroParser::reset ()
Resets the parser clearing all previous input.
Definition at line 125 of file MacroParser.cpp.
References lemon_macroAlloc(), lemon_macroFree(), and bcplus::parser::detail::MacroParser::Status::OK.
{
     _scanner = new detail::Scanner(_config);
     lemon_macroFree(_parser, free);
     _parser = lemon_macroAlloc(malloc);
     _stat = Status::OK;
     _tokens.clear();
 }
symbols::SymbolTable* bcplus::parser::detail::MacroParser::symtab () inline
Gets the symbol table for the parser.
Definition at line 104 of file MacroParser.h.
Referenced by MacroParser().
 { return _symtab; }
symbols::SymbolTable const* bcplus::parser::detail::MacroParser::symtab () const inline
Definition at line 105 of file MacroParser.h.
 { return _symtab; }
The documentation for this class was generated from the following files:
bcplusparser/include/bcplus/parser/detail/MacroParser.h
bcplusparser/src/bcplus/parser/detail/MacroParser.cpp