cplus2asp: bcplus::statements::detail::BasicLawForm< type, head_t, ifbody_t, ifcons_t, after_t, unless_t, where_t > Class Template Reference
bcplus::statements::detail::BasicLawForm< type, head_t, ifbody_t, ifcons_t, after_t, unless_t, where_t > Class Template Reference
Base law form for basic laws.
#include <BasicLawForm.h>
Public Types
typedef head_t head_type
typedef ifbody_t ifbody_type
typedef ifcons_t ifcons_type
typedef after_t after_type
typedef unless_t unless_type
typedef where_t where_type
Public Member Functions
BasicLawForm (head_t const *head, ifbody_t const *ifbody, ifcons_t const *ifcons, after_t const *after, unless_t const *unless, where_t const *where, Location const &begin=Location(NULL, 0, 0), Location const &end=Location(NULL, 0, 0))
virtual ~BasicLawForm ()
head_t const * head () const
Get the head element.
ifbody_t const * ifbody () const
Get the 'if' clause.
ifcons_t const * ifcons () const
Get the 'ifcons' clause.
after_t const * after () const
Get the 'after' clause.
unless_t const * unless () const
Get the 'unless' clause.
where_t const * where () const
Get the 'where' clause.
virtual Statement * copy () const
Perform a dep copy of this statement.
Public Member Functions inherited from bcplus::statements::Statement
Statement (Type::type type, Location const &begin=Location(NULL, 0, 0), Location const &end=Location(NULL, 0, 0))
Basic Contructor.
~Statement ()
Destructor Stub.
Type::type type () const
Get the type of this statement.
char const * typeString () const
Get the string representation of the statement type.
Location const & beginLoc () const
Get the beginning location of this statement.
Location const & endLoc () const
Get the ending location of this statement.
Public Member Functions inherited from babb::utils::Referenced
Referenced ()
Referenced ()
Additional Inherited Members
Protected Member Functions inherited from babb::utils::Referenced
virtual ~Referenced ()
virtual ~Referenced ()
Detailed Description
template<Statement::Type::type type, typename head_t, typename ifbody_t, typename ifcons_t, typename after_t, typename unless_t, typename where_t>
class bcplus::statements::detail::BasicLawForm< type, head_t, ifbody_t, ifcons_t, after_t, unless_t, where_t >
Base law form for basic laws.
Definition at line 15 of file BasicLawForm.h.
Member Typedef Documentation
template<Statement::Type::type type, typename head_t , typename ifbody_t , typename ifcons_t , typename after_t , typename unless_t , typename where_t > typedef after_t bcplus::statements::detail::BasicLawForm< type, head_t, ifbody_t, ifcons_t, after_t, unless_t, where_t >::after_type
Definition at line 24 of file BasicLawForm.h.
template<Statement::Type::type type, typename head_t , typename ifbody_t , typename ifcons_t , typename after_t , typename unless_t , typename where_t > typedef head_t bcplus::statements::detail::BasicLawForm< type, head_t, ifbody_t, ifcons_t, after_t, unless_t, where_t >::head_type
Definition at line 21 of file BasicLawForm.h.
template<Statement::Type::type type, typename head_t , typename ifbody_t , typename ifcons_t , typename after_t , typename unless_t , typename where_t > typedef ifbody_t bcplus::statements::detail::BasicLawForm< type, head_t, ifbody_t, ifcons_t, after_t, unless_t, where_t >::ifbody_type
Definition at line 22 of file BasicLawForm.h.
template<Statement::Type::type type, typename head_t , typename ifbody_t , typename ifcons_t , typename after_t , typename unless_t , typename where_t > typedef ifcons_t bcplus::statements::detail::BasicLawForm< type, head_t, ifbody_t, ifcons_t, after_t, unless_t, where_t >::ifcons_type
Definition at line 23 of file BasicLawForm.h.
template<Statement::Type::type type, typename head_t , typename ifbody_t , typename ifcons_t , typename after_t , typename unless_t , typename where_t > typedef unless_t bcplus::statements::detail::BasicLawForm< type, head_t, ifbody_t, ifcons_t, after_t, unless_t, where_t >::unless_type
Definition at line 25 of file BasicLawForm.h.
template<Statement::Type::type type, typename head_t , typename ifbody_t , typename ifcons_t , typename after_t , typename unless_t , typename where_t > typedef where_t bcplus::statements::detail::BasicLawForm< type, head_t, ifbody_t, ifcons_t, after_t, unless_t, where_t >::where_type
Definition at line 26 of file BasicLawForm.h.
Constructor & Destructor Documentation
template<Statement::Type::type t, typename head_t , typename ifbody_t , typename ifcons_t , typename after_t , typename unless_t , typename where_t > bcplus::statements::detail::BasicLawForm< t, head_t, ifbody_t, ifcons_t, after_t, unless_t, where_t >::BasicLawForm (head_t const * head, ifbody_t const * ifbody, ifcons_t const * ifcons, after_t const * after, unless_t const * unless, where_t const * where, Location const & begin = Location(NULL, 0, 0), Location const & end = Location(NULL, 0, 0))
Definition at line 13 of file BasicLawForm.impl.h.
     : Statement(t, begin, end), _head(head), _ifbody(ifbody), _ifcons(ifcons), _after(after), _unless(unless), _where(where) {
     /* Intentionally left blank */
 }
template<Statement::Type::type t, typename head_t , typename ifbody_t , typename ifcons_t , typename after_t , typename unless_t , typename where_t > bcplus::statements::detail::BasicLawForm< t, head_t, ifbody_t, ifcons_t, after_t, unless_t, where_t >::~BasicLawForm () virtual
Definition at line 21 of file BasicLawForm.impl.h.
{
     /* Intentionally left blank */
 }
Member Function Documentation
template<Statement::Type::type type, typename head_t , typename ifbody_t , typename ifcons_t , typename after_t , typename unless_t , typename where_t > after_t const* bcplus::statements::detail::BasicLawForm< type, head_t, ifbody_t, ifcons_t, after_t, unless_t, where_t >::after () const inline
Get the 'after' clause.
Definition at line 78 of file BasicLawForm.h.
Referenced by cplus2asp::cplus2asp_bin::Translator::translate().
 { return _after; }
template<Statement::Type::type t, typename head_t , typename ifbody_t , typename ifcons_t , typename after_t , typename unless_t , typename where_t > Statement * bcplus::statements::detail::BasicLawForm< t, head_t, ifbody_t, ifcons_t, after_t, unless_t, where_t >::copy () const virtual
Perform a dep copy of this statement.
Implements bcplus::statements::Statement.
Definition at line 26 of file BasicLawForm.impl.h.
{
     return new BasicLawForm<t, head_t, ifbody_t, ifcons_t, after_t, unless_t, where_t>(head(), ifbody(), ifcons(), after(), unless(), where(), beginLoc(), endLoc());
 }
template<Statement::Type::type type, typename head_t , typename ifbody_t , typename ifcons_t , typename after_t , typename unless_t , typename where_t > head_t const* bcplus::statements::detail::BasicLawForm< type, head_t, ifbody_t, ifcons_t, after_t, unless_t, where_t >::head () const inline
Get the head element.
Definition at line 69 of file BasicLawForm.h.
Referenced by cplus2asp::cplus2asp_bin::Translator::translate().
 { return _head; }
template<Statement::Type::type type, typename head_t , typename ifbody_t , typename ifcons_t , typename after_t , typename unless_t , typename where_t > ifbody_t const* bcplus::statements::detail::BasicLawForm< type, head_t, ifbody_t, ifcons_t, after_t, unless_t, where_t >::ifbody () const inline
Get the 'if' clause.
Definition at line 72 of file BasicLawForm.h.
Referenced by cplus2asp::cplus2asp_bin::Translator::translate().
 { return _ifbody; }
template<Statement::Type::type type, typename head_t , typename ifbody_t , typename ifcons_t , typename after_t , typename unless_t , typename where_t > ifcons_t const* bcplus::statements::detail::BasicLawForm< type, head_t, ifbody_t, ifcons_t, after_t, unless_t, where_t >::ifcons () const inline
Get the 'ifcons' clause.
Definition at line 75 of file BasicLawForm.h.
Referenced by cplus2asp::cplus2asp_bin::Translator::translate().
 { return _ifcons; }
template<Statement::Type::type type, typename head_t , typename ifbody_t , typename ifcons_t , typename after_t , typename unless_t , typename where_t > unless_t const* bcplus::statements::detail::BasicLawForm< type, head_t, ifbody_t, ifcons_t, after_t, unless_t, where_t >::unless () const inline
Get the 'unless' clause.
Definition at line 81 of file BasicLawForm.h.
Referenced by cplus2asp::cplus2asp_bin::Translator::translate().
 { return _unless; }
template<Statement::Type::type type, typename head_t , typename ifbody_t , typename ifcons_t , typename after_t , typename unless_t , typename where_t > where_t const* bcplus::statements::detail::BasicLawForm< type, head_t, ifbody_t, ifcons_t, after_t, unless_t, where_t >::where () const inline
Get the 'where' clause.
Definition at line 84 of file BasicLawForm.h.
Referenced by cplus2asp::cplus2asp_bin::Translator::translate().
 { return _where; }
The documentation for this class was generated from the following files:
bcplusparser/include/bcplus/statements/detail/BasicLawForm.h
bcplusparser/include/bcplus/statements/detail/BasicLawForm.impl.h