cplus2asp: bcplus::Configuration Class Reference
bcplus::Configuration Class Reference
#include <Configuration.h>
Classes
struct Option
Container for option enumeration information.
struct Status
Public Types
typedef std::pair
< babb::utils::ref_ptr< const
ReferencedString >
, babb::utils::ref_ptr< const
ReferencedString > > MacroDefinition
typedef ReferencedList
< MacroDefinition >::type MacroList
typedef MacroList::iterator iterator
typedef MacroList::const_iterator const_iterator
Public Member Functions
Configuration (char const *bin=NULL, char const *version=NULL)
Default constructor Initializes all parameters to defaults.
virtual ~Configuration ()
Destructor.
ReferencedString const * version () const
Get the application version.
ReferencedString const * binaryName () const
Get the name of this executable file.
ReferencedPath const * symtabInput () const
Get/set the input file for the symbol table.
void symtabInput (ReferencedPath const *input)
ReferencedPath const * symtabOutput () const
Get/set the output file for the symbol table.
void symtabOutput (ReferencedPath const *output)
size_t verbosity () const
Get/set the application verbosity level.
void verbosity (size_t verb)
bool parseTrace () const
Determine whether we should display parser trace information.
void parseTrace (bool trace)
const_iterator begin () const
iterate over the list of command line macros
iterator begin ()
const_iterator end () const
iterator end ()
void addMacro (ReferencedString const *name, ReferencedString const *def)
Add a macro definition.
void addMacro (MacroDefinition const &m)
std::ostream & ostream (Verb::type v) const
Get the output stream for the provided verbosity level This will return a null-sink, std::cerr, or std::cout.
void error (std::string const &err, Location const *loc=NULL) const
Output a formatted error.
virtual int load (int argc, char const **argv)
Loads configuration parameters from the provided arguments list.
virtual bool good ()
Verifies the integrity of the configuration parameters.
std::ostream & outputVersion (std::ostream &out) const
Outputs the application version information.
std::ostream & outputHelp (std::ostream &out) const
Outputs a help dialog to the provided output stream.
Public Member Functions inherited from babb::utils::Referenced
Referenced ()
Referenced ()
Static Public Attributes
static const size_t DEFAULT_VERB_LEVEL = Verb::STD
Default verbosity level.
Protected Member Functions
virtual int parseOption (char const *opt, char const *op2=NULL)
Parses the string option and performs the task specified by it.
virtual std::ostream & outputOptions (std::ostream &out) const
Outputs the options for this configuration FORMAT: (dash is a space) --—<category>: -------—<option> -------—<option2> ------------—
Protected Member Functions inherited from babb::utils::Referenced
virtual ~Referenced ()
virtual ~Referenced ()
Detailed Description
Definition at line 44 of file Configuration.h.
Member Typedef Documentation
typedef MacroList::const_iterator bcplus::Configuration::const_iterator
Definition at line 85 of file Configuration.h.
typedef MacroList::iterator bcplus::Configuration::iterator
Definition at line 84 of file Configuration.h.
typedef std::pair<babb::utils::ref_ptr<const ReferencedString>, babb::utils::ref_ptr<const ReferencedString> > bcplus::Configuration::MacroDefinition
Definition at line 82 of file Configuration.h.
typedef ReferencedList<MacroDefinition>::type bcplus::Configuration::MacroList
Definition at line 83 of file Configuration.h.
Constructor & Destructor Documentation
bcplus::Configuration::Configuration (char const * bin = NULL, char const * version = NULL)
Default constructor Initializes all parameters to defaults.
Parameters
bin The name of the binary
version The system version.
Definition at line 27 of file Configuration.cpp.
References DEFAULT_VERB_LEVEL.
 {
     _verb = DEFAULT_VERB_LEVEL;
     if (version) _version = new ReferencedString(version);
     if (bin) _bin_name = new ReferencedString(fs::path(bin).filename().native());
     _parse_trace = false;
 }
bcplus::Configuration::~Configuration () virtual
Destructor.
Reimplemented in cplus2asp::cplus2asp_bin::Configuration.
Definition at line 36 of file Configuration.cpp.
 { /* Intentionally left blank */ }
Member Function Documentation
void bcplus::Configuration::addMacro (ReferencedString const * name, ReferencedString const * def) inline
Add a macro definition.
Definition at line 152 of file Configuration.h.
Referenced by parseOption().
                                                                 { _macros.push_back(MacroDefinition(name,def)); }
void bcplus::Configuration::addMacro (MacroDefinition const & m) inline
Definition at line 154 of file Configuration.h.
 { _macros.push_back(m); }
const_iterator bcplus::Configuration::begin () const inline
iterate over the list of command line macros
Definition at line 146 of file Configuration.h.
 { return _macros.begin(); }
iterator bcplus::Configuration::begin () inline
Definition at line 147 of file Configuration.h.
 { return _macros.begin(); }
ReferencedString const* bcplus::Configuration::binaryName () const inline
Get the name of this executable file.
Definition at line 127 of file Configuration.h.
Referenced by outputHelp(), and outputVersion().
 { return _bin_name; }
const_iterator bcplus::Configuration::end () const inline
Definition at line 148 of file Configuration.h.
 { return _macros.end(); }
iterator bcplus::Configuration::end () inline
Definition at line 149 of file Configuration.h.
 { return _macros.end(); }
void bcplus::Configuration::error (std::string const & err, Location const * loc = NULL) const
Output a formatted error.
Parameters
err The error message to output
loc The locatio nthe error occurred (if any)
Definition at line 91 of file Configuration.cpp.
References bcplus::Verb::ERROR, and ostream().
Referenced by cplus2asp::cplus2asp_bin::Translator::translate().
{
     std::ostream& out = ostream(Verb::ERROR);
     out << "ERROR: ";
     if (loc) out << *loc << ": ";
     out << err << std::endl;
 }
bool bcplus::Configuration::good () virtual
Verifies the integrity of the configuration parameters.
Returns
True if the parameters appear to be correct. False otherwise.
Reimplemented in cplus2asp::cplus2asp_bin::Configuration.
Definition at line 77 of file Configuration.cpp.
Referenced by main(), and parseOption().
{
     return true;
 }
int bcplus::Configuration::load (int argc, char const ** argv) virtual
Loads configuration parameters from the provided arguments list.
Parameters
argc The number of arguments.
argv An array of these arguments.
Returns
The status of the load
Definition at line 40 of file Configuration.cpp.
References parseOption(), bcplus::Configuration::Status::STAT_BAD_ARG, bcplus::Configuration::Status::STAT_HELP, bcplus::Configuration::Status::STAT_NEXT_ARG, bcplus::Configuration::Status::STAT_OK, and bcplus::Configuration::Status::STAT_VERSION.
Referenced by main().
{
     int ret = Status::STAT_OK;
     // Figure out who we are
     fs::path bin = argv[0];
     _bin_name = new ReferencedString(bin.filename().native());
     // parse arguments
     for (int i = 1; i < argc; i++) {
         ret = parseOption(argv[i], NULL);
         if (ret == Status::STAT_NEXT_ARG) {
             if (i < argc-1 && argv[i+1][0] != '-') {
                 ret = parseOption(argv[i], argv[i+1]);
                 i++;
             } else {
                 std::cerr << "ERROR: Expected an option following \"" << argv[i] << "\"." << std::endl;
                 return Status::STAT_BAD_ARG;
             }
         }
         switch (ret) {
         case Status::STAT_BAD_ARG:
             std::cerr << "ERROR: Unrecognized option: \"" << argv[i] << "\"." << std::endl;
             /* no break */
         case Status::STAT_HELP:
         case Status::STAT_VERSION:
             return ret;
         default:
             continue;
         };
     }
     return ret;
 }
std::ostream & bcplus::Configuration::ostream (Verb::type v) const
Get the output stream for the provided verbosity level This will return a null-sink, std::cerr, or std::cout.
Definition at line 81 of file Configuration.cpp.
References bcplus::Verb::ERROR, bcplus::Verb::STD, and bcplus::Verb::WARN.
Referenced by error(), bcplus::parser::detail::ScannerFileSource::fill(), main(), bcplus::parser::detail::ScannerFileSource::ScannerFileSource(), bcplus::symbols::SymbolTable::SymbolTable(), and cplus2asp::cplus2asp_bin::Translator::translate().
{
     static ios::stream<ios::null_sink> NULLSTREAM( (ios::null_sink()) );
     if (v > _verb) return NULLSTREAM;
     else if (v == Verb::ERROR || v == Verb::WARN) return std::cerr;
 #ifdef NDEBUG
     else if (v > Verb::STD) return NULLSTREAM;
 #endif
     else return std::cout;
 }
std::ostream & bcplus::Configuration::outputHelp (std::ostream & out) const
Outputs a help dialog to the provided output stream.
Parameters
out The output stream to write the help dialog to.
Returns
out
Definition at line 677 of file Configuration.cpp.
References binaryName(), outputOptions(), and outputVersion().
Referenced by main().
{
     out << "---------------------------------------------------------------------------------------"<< std::endl;
     outputVersion(out)
         << "---------------------------------------------------------------------------------------"<< std::endl
         << "Usage: " ;
         if (binaryName()) out << *binaryName();
         else out << "<binary>";
         out << " [<OPTIONS>] [<CONSTANTS>] <INPUT_FILES>"                                           << std::endl
         << "---------------------------------------------------------------------------------------"<< std::endl
         << "OPTIONS:"                                                                               << std::endl;
     outputOptions(out);
     out                                                                                             << std::endl
         << "CONSTANTS:"                                                                             << std::endl
         << "     <identifier>=<value>"                                                              << std::endl
         << "          - Defines <identifier> to be a macro which expands to <value>"                << std::endl;
     return out;
 }
std::ostream & bcplus::Configuration::outputOptions (std::ostream & out) const protected virtual
Outputs the options for this configuration FORMAT: (dash is a space) --—<category>: -------—<option> -------—<option2> ------------—
Parameters
out The output stream to write to
Returns
out.
Reimplemented in cplus2asp::cplus2asp_bin::Configuration.
Definition at line 695 of file Configuration.cpp.
References bcplus::Verb::DETAIL, bcplus::Verb::ERROR, bcplus::Verb::OP, bcplus::Verb::STD, bcplus::Verb::TRACE_PARSER, and bcplus::Verb::WARN.
Referenced by outputHelp(), and cplus2asp::cplus2asp_bin::Configuration::outputOptions().
{
     out << "     Parser Options:"                                                                   << std::endl
         << "          -s=<FILE>"                                                                    << std::endl
         << "          --symtab-in=<FILE>"                                                           << std::endl
         << "               - An XML file to read the initial symbol table in from. [none]"          << std::endl
         << "          --symtab-out=<FILE>"                                                          << std::endl
         << "               - A file to write the final symbol table to. [none]"                     << std::endl
         << "          --verb=<LEVEL>"                                                               << std::endl
         << "               - The level of output to show:"                                          << std::endl
         << "                    " << Verb::ERROR        << "  - Error output only"                  << std::endl
         << "                    " << Verb::WARN         << "  - Warnings"                           << std::endl
         << "                    " << Verb::STD          << "  - Standard messages [default]"        << std::endl
         << "                 Only available when compiled in debug mode:"                           << std::endl
         << "                    " << Verb::OP           << "  - Operation level trace output"       << std::endl
         << "                    " << Verb::DETAIL       << "  - Detailed debugging messages"        << std::endl
         << "                    " << Verb::TRACE_PARSER << "+ - Parser debugging messages"          << std::endl
         << "          --parse-trace"                                                                << std::endl
         << "               - Enable lemon parser trace output."                                     << std::endl
                                                                                                     << std::endl
         << "     Other Options:"                                                                    << std::endl
         << "          -v"                                                                           << std::endl
         << "          --version"                                                                    << std::endl
         << "               - Displays the version dialog."                                          << std::endl
         << "          -h"                                                                           << std::endl
         << "          --help"                                                                       << std::endl
         << "               - Shows this dialog."                                                    << std::endl;
     return out;
 }
std::ostream & bcplus::Configuration::outputVersion (std::ostream & out) const
Outputs the application version information.
Parameters
out The output stream to write to.
Returns
out
Definition at line 671 of file Configuration.cpp.
References binaryName(), and version().
Referenced by main(), and outputHelp().
{
     if (binaryName()) out << *binaryName() << " ";
     if (version()) out << "version " << *version() << std::endl;
     return out;
 }
int bcplus::Configuration::parseOption (char const * opt, char const * op2 = NULL) protected virtual
Parses the string option and performs the task specified by it.
Parameters
opt The option string to parse.
opt2 A second option which should be provided when STAT_NEXT_ARG is returned.
Returns
A status code indicating whether or not it was a success.
Reimplemented in cplus2asp::cplus2asp_bin::Configuration.
Definition at line 109 of file Configuration.cpp.
References addMacro(), bcplus::Configuration::Option::BAD, EXTRACT_NAME, EXTRACT_NAME_VAL, babb::utils::fromString(), good(), bcplus::Configuration::Option::HELP, bcplus::Configuration::Option::MACRO_DEF, bcplus::Configuration::Option::PARSE_TRACE, bcplus::Configuration::Status::STAT_BAD_ARG, bcplus::Configuration::Status::STAT_HELP, bcplus::Configuration::Status::STAT_OK, bcplus::Configuration::Status::STAT_VERSION, bcplus::Configuration::Option::SYMTAB_INPUT, bcplus::Configuration::Option::SYMTAB_OUTPUT, bcplus::Configuration::Option::VERBOSITY, verbosity(), and bcplus::Configuration::Option::VERSION.
Referenced by load(), and cplus2asp::cplus2asp_bin::Configuration::parseOption().
{
     int ret = Status::STAT_OK;
     std::string val, val2;
     char const* marker;
     char const* token = opt;
     int option, int_v;
     bool good;
 #line 121 "<stdout>"
     {
         char yych;
         yych = *opt;
         switch (yych) {
         case '\n':  goto yy2;
         case '-':   goto yy3;
         case 'A':
         case 'B':
         case 'C':
         case 'D':
         case 'E':
         case 'F':
         case 'G':
         case 'H':
         case 'I':
         case 'J':
         case 'K':
         case 'L':
         case 'M':
         case 'N':
         case 'O':
         case 'P':
         case 'Q':
         case 'R':
         case 'S':
         case 'T':
         case 'U':
         case 'V':
         case 'W':
         case 'X':
         case 'Y':
         case 'Z':
         case '_':
         case 'a':
         case 'b':
         case 'c':
         case 'd':
         case 'e':
         case 'f':
         case 'g':
         case 'h':
         case 'i':
         case 'j':
         case 'k':
         case 'l':
         case 'm':
         case 'n':
         case 'o':
         case 'p':
         case 'q':
         case 'r':
         case 's':
         case 't':
         case 'u':
         case 'v':
         case 'w':
         case 'x':
         case 'y':
         case 'z':   goto yy5;
         default:    goto yy6;
         }
 yy2:
         opt = marker;
         goto yy4;
 yy3:
         yych = *(marker = ++opt);
         switch (yych) {
         case '-':   goto yy12;
         case '?':
         case 'h':   goto yy15;
         case 's':   goto yy17;
         case 'v':   goto yy13;
         default:    goto yy4;
         }
 yy4:
 #line 156 "bcplus/Configuration.r2c"
         {
                                                   val = token;
                                                   option = Option::BAD;
                                                   goto re2c_finish; }
 #line 203 "<stdout>"
 yy5:
         yych = *(marker = ++opt);
         switch (yych) {
         case '0':
         case '1':
         case '2':
         case '3':
         case '4':
         case '5':
         case '6':
         case '7':
         case '8':
         case '9':
         case 'A':
         case 'B':
         case 'C':
         case 'D':
         case 'E':
         case 'F':
         case 'G':
         case 'H':
         case 'I':
         case 'J':
         case 'K':
         case 'L':
         case 'M':
         case 'N':
         case 'O':
         case 'P':
         case 'Q':
         case 'R':
         case 'S':
         case 'T':
         case 'U':
         case 'V':
         case 'W':
         case 'X':
         case 'Y':
         case 'Z':
         case '_':
         case 'a':
         case 'b':
         case 'c':
         case 'd':
         case 'e':
         case 'f':
         case 'g':
         case 'h':
         case 'i':
         case 'j':
         case 'k':
         case 'l':
         case 'm':
         case 'n':
         case 'o':
         case 'p':
         case 'q':
         case 'r':
         case 's':
         case 't':
         case 'u':
         case 'v':
         case 'w':
         case 'x':
         case 'y':
         case 'z':   goto yy7;
         case '=':   goto yy9;
         default:    goto yy4;
         }
 yy6:
         yych = *++opt;
         goto yy4;
 yy7:
         ++opt;
         yych = *opt;
         switch (yych) {
         case '0':
         case '1':
         case '2':
         case '3':
         case '4':
         case '5':
         case '6':
         case '7':
         case '8':
         case '9':
         case 'A':
         case 'B':
         case 'C':
         case 'D':
         case 'E':
         case 'F':
         case 'G':
         case 'H':
         case 'I':
         case 'J':
         case 'K':
         case 'L':
         case 'M':
         case 'N':
         case 'O':
         case 'P':
         case 'Q':
         case 'R':
         case 'S':
         case 'T':
         case 'U':
         case 'V':
         case 'W':
         case 'X':
         case 'Y':
         case 'Z':
         case '_':
         case 'a':
         case 'b':
         case 'c':
         case 'd':
         case 'e':
         case 'f':
         case 'g':
         case 'h':
         case 'i':
         case 'j':
         case 'k':
         case 'l':
         case 'm':
         case 'n':
         case 'o':
         case 'p':
         case 'q':
         case 'r':
         case 's':
         case 't':
         case 'u':
         case 'v':
         case 'w':
         case 'x':
         case 'y':
         case 'z':   goto yy7;
         case '=':   goto yy9;
         default:    goto yy2;
         }
 yy9:
         ++opt;
         yych = *opt;
         if (yych >= 0x01) goto yy9;
 #line 150 "bcplus/Configuration.r2c"
         {
                                                   char const* c = strchr(token, '=');
                                                   val.assign(token, (size_t)(c - token));
                                                   val2.assign(c+1,opt-c-1);
                                                   option = Option::MACRO_DEF;
                                                   goto re2c_finish; }
 #line 357 "<stdout>"
 yy12:
         yych = *++opt;
         switch (yych) {
         case 'h':   goto yy23;
         case 'p':   goto yy22;
         case 's':   goto yy20;
         case 'v':   goto yy21;
         default:    goto yy2;
         }
 yy13:
         ++opt;
 #line 146 "bcplus/Configuration.r2c"
         {
                                                   EXTRACT_NAME;
                                                   option = Option::VERSION;
                                                   goto re2c_finish; }
 #line 374 "<stdout>"
 yy15:
         ++opt;
 #line 142 "bcplus/Configuration.r2c"
         {
                                                   EXTRACT_NAME;
                                                   option =  Option::HELP;
                                                   goto re2c_finish; }
 #line 382 "<stdout>"
 yy17:
         ++opt;
         switch ((yych = *opt)) {
         case '=':   goto yy19;
         default:    goto yy18;
         }
 yy18:
 #line 126 "bcplus/Configuration.r2c"
         {
                                                   EXTRACT_NAME_VAL;
                                                   option = Option::SYMTAB_INPUT;
                                                   goto re2c_finish; }
 #line 395 "<stdout>"
 yy19:
         yych = *++opt;
         goto yy18;
 yy20:
         yych = *++opt;
         switch (yych) {
         case 'y':   goto yy45;
         default:    goto yy2;
         }
 yy21:
         yych = *++opt;
         switch (yych) {
         case 'e':   goto yy37;
         default:    goto yy2;
         }
 yy22:
         yych = *++opt;
         switch (yych) {
         case 'a':   goto yy26;
         default:    goto yy2;
         }
 yy23:
         yych = *++opt;
         switch (yych) {
         case 'e':   goto yy24;
         default:    goto yy2;
         }
 yy24:
         yych = *++opt;
         switch (yych) {
         case 'l':   goto yy25;
         default:    goto yy2;
         }
 yy25:
         yych = *++opt;
         switch (yych) {
         case 'p':   goto yy15;
         default:    goto yy2;
         }
 yy26:
         yych = *++opt;
         switch (yych) {
         case 'r':   goto yy27;
         default:    goto yy2;
         }
 yy27:
         yych = *++opt;
         switch (yych) {
         case 's':   goto yy28;
         default:    goto yy2;
         }
 yy28:
         yych = *++opt;
         switch (yych) {
         case 'e':   goto yy29;
         default:    goto yy2;
         }
 yy29:
         yych = *++opt;
         switch (yych) {
         case '-':   goto yy30;
         default:    goto yy2;
         }
 yy30:
         yych = *++opt;
         switch (yych) {
         case 't':   goto yy31;
         default:    goto yy2;
         }
 yy31:
         yych = *++opt;
         switch (yych) {
         case 'r':   goto yy32;
         default:    goto yy2;
         }
 yy32:
         yych = *++opt;
         switch (yych) {
         case 'a':   goto yy33;
         default:    goto yy2;
         }
 yy33:
         yych = *++opt;
         switch (yych) {
         case 'c':   goto yy34;
         default:    goto yy2;
         }
 yy34:
         yych = *++opt;
         switch (yych) {
         case 'e':   goto yy35;
         default:    goto yy2;
         }
 yy35:
         ++opt;
 #line 138 "bcplus/Configuration.r2c"
         {
                                                   EXTRACT_NAME;
                                                   option = Option::PARSE_TRACE;
                                                   goto re2c_finish; }
 #line 496 "<stdout>"
 yy37:
         yych = *++opt;
         switch (yych) {
         case 'r':   goto yy38;
         default:    goto yy2;
         }
 yy38:
         yych = *++opt;
         switch (yych) {
         case 'b':   goto yy40;
         case 's':   goto yy39;
         default:    goto yy2;
         }
 yy39:
         yych = *++opt;
         switch (yych) {
         case 'i':   goto yy43;
         default:    goto yy2;
         }
 yy40:
         ++opt;
         switch ((yych = *opt)) {
         case '=':   goto yy42;
         default:    goto yy41;
         }
 yy41:
 #line 134 "bcplus/Configuration.r2c"
         {
                                                   EXTRACT_NAME_VAL;
                                                   option = Option::VERBOSITY;
                                                   goto re2c_finish; }
 #line 528 "<stdout>"
 yy42:
         yych = *++opt;
         goto yy41;
 yy43:
         yych = *++opt;
         switch (yych) {
         case 'o':   goto yy44;
         default:    goto yy2;
         }
 yy44:
         yych = *++opt;
         switch (yych) {
         case 'n':   goto yy13;
         default:    goto yy2;
         }
 yy45:
         yych = *++opt;
         switch (yych) {
         case 'm':   goto yy46;
         default:    goto yy2;
         }
 yy46:
         yych = *++opt;
         switch (yych) {
         case 't':   goto yy47;
         default:    goto yy2;
         }
 yy47:
         yych = *++opt;
         switch (yych) {
         case 'a':   goto yy48;
         default:    goto yy2;
         }
 yy48:
         yych = *++opt;
         switch (yych) {
         case 'b':   goto yy49;
         default:    goto yy2;
         }
 yy49:
         yych = *++opt;
         switch (yych) {
         case '-':   goto yy50;
         default:    goto yy2;
         }
 yy50:
         yych = *++opt;
         switch (yych) {
         case 'i':   goto yy52;
         case 'o':   goto yy51;
         default:    goto yy2;
         }
 yy51:
         yych = *++opt;
         switch (yych) {
         case 'u':   goto yy53;
         default:    goto yy2;
         }
 yy52:
         yych = *++opt;
         switch (yych) {
         case 'n':   goto yy17;
         default:    goto yy2;
         }
 yy53:
         yych = *++opt;
         switch (yych) {
         case 't':   goto yy54;
         default:    goto yy2;
         }
 yy54:
         ++opt;
         switch ((yych = *opt)) {
         case '=':   goto yy56;
         default:    goto yy55;
         }
 yy55:
 #line 130 "bcplus/Configuration.r2c"
         {
                                                   EXTRACT_NAME_VAL;
                                                   option = Option::SYMTAB_OUTPUT;
                                                   goto re2c_finish; }
 #line 611 "<stdout>"
 yy56:
         ++opt;
         yych = *opt;
         goto yy55;
     }
 #line 160 "bcplus/Configuration.r2c"
 re2c_finish:
     switch (option) {
     case Option::SYMTAB_INPUT:
 //      if (fs::native(val2)) {
             _symtab_in = new ReferencedPath(val2);
 //      } else {
 //          ret = Status::STAT_BAD_ARG;
 //          std::cerr << "ERROR: \"" << val2 << "\" is not a valid file path." << std::endl;
 //      }
         break;
     case Option::SYMTAB_OUTPUT:
 //      if (fs::native(val2)) {
             _symtab_out = new ReferencedPath(val2);
 //      } else {
 //          ret = Status::STAT_BAD_ARG;
 //          std::cerr << "ERROR: \"" << val2 << "\" is not a valid file path." << std::endl;
 //
 //      }
         break;
     case Option::VERBOSITY:
         good = babb::utils::fromString(val2.c_str(), int_v);
         if (!good || int_v < 0) {
             ret = Status::STAT_BAD_ARG;
             std::cerr << "ERROR: Bad value provided for command line option. Expected a non-negative integer for argument \"" << val << "\"." << std::endl;
         } else {
             verbosity(int_v);
         }
         break;
     case Option::PARSE_TRACE:
         _parse_trace = true;
         break;
     case Option::MACRO_DEF:
         addMacro(new ReferencedString(val), new ReferencedString(val2));
         break;
     case Option::HELP:
         ret = Status::STAT_HELP;
         break;
     case Option::VERSION:
         ret = Status::STAT_VERSION;
         break;
     case Option::BAD:
     default:
         ret = Status::STAT_BAD_ARG;
         break;
     }
     return ret;
 }
bool bcplus::Configuration::parseTrace () const inline
Determine whether we should display parser trace information.
Definition at line 142 of file Configuration.h.
 { return _parse_trace; }
void bcplus::Configuration::parseTrace (bool trace) inline
Definition at line 143 of file Configuration.h.
 { _parse_trace = trace; }
ReferencedPath const* bcplus::Configuration::symtabInput () const inline
Get/set the input file for the symbol table.
Definition at line 130 of file Configuration.h.
Referenced by main(), and bcplus::symbols::SymbolTable::SymbolTable().
 { return _symtab_in; }
void bcplus::Configuration::symtabInput (ReferencedPath const * input) inline
Definition at line 131 of file Configuration.h.
 { _symtab_in = input; }
ReferencedPath const* bcplus::Configuration::symtabOutput () const inline
Get/set the output file for the symbol table.
Definition at line 134 of file Configuration.h.
 { return _symtab_out; }
void bcplus::Configuration::symtabOutput (ReferencedPath const * output) inline
Definition at line 135 of file Configuration.h.
 { _symtab_out = output; }
size_t bcplus::Configuration::verbosity () const inline
Get/set the application verbosity level.
Definition at line 138 of file Configuration.h.
Referenced by parseOption().
 { return _verb; }
void bcplus::Configuration::verbosity (size_t verb) inline
Definition at line 139 of file Configuration.h.
 { _verb = verb; }
ReferencedString const* bcplus::Configuration::version () const inline
Get the application version.
Definition at line 124 of file Configuration.h.
Referenced by outputVersion().
 { return _version; }
Member Data Documentation
const size_t bcplus::Configuration::DEFAULT_VERB_LEVEL = Verb::STD static
Default verbosity level.
Definition at line 52 of file Configuration.h.
Referenced by Configuration().
The documentation for this class was generated from the following files:
bcplusparser/include/bcplus/Configuration.h
bcplusparser/src/bcplus/Configuration.cpp