cplus2asp: bcplus::parser::detail::Scanner Class Reference
bcplus::parser::detail::Scanner Class Reference
#include <Scanner.h>
Public Types
typedef
ScannerTokenSource::TokenList TokenList
A list of tokens.
Public Member Functions
Scanner (Configuration const *config)
virtual ~Scanner ()
Destructor.
bool push_front (boost::filesystem::path const &file, bool squelch=false)
Attempts to open the provided file and inject it into the front of the stream being read by the scanner.
bool push_back (boost::filesystem::path const &file, bool squelch=false)
Attempts to open the provided file and append it to the end of the stream being read by the scanner.
void push_front (char const *buffer, Location const &loc=Location(NULL, 0, 0), bool track_position=false)
Injects the provided null-terminated buffer into the front of the stream being read by the scanner.
void push_back (char const *buffer, Location const &loc=Location(NULL, 0, 0), bool track_position=false)
Appends the provided null-terminated buffer to the end of the stream being read by the scanner.
void push_front (Token *token)
Injects the provided token into the from of the stream being read by the scanner.
void push_back (Token *token)
Appends the provided token to the end of the stream being read by the scanner.
void push_front (TokenList *tokens)
Injects the provided tokens into the from of the stream being read by the scanner.
void push_back (TokenList *tokens)
Appends the provided token to the end of the stream being read by the scanner.
size_t size () const
Gets the number of input streams associated with this scanner.
Token * readToken ()
Reads a token from the currently open file.
Location loc () const
Gets the current location of the scanner.
void close ()
Closes all streams open by the scanner and resets its state.
Public Member Functions inherited from babb::utils::Referenced
Referenced ()
Referenced ()
Additional Inherited Members
Protected Member Functions inherited from babb::utils::Referenced
virtual ~Referenced ()
virtual ~Referenced ()
Detailed Description
Definition at line 22 of file Scanner.h.
Member Typedef Documentation
typedef ScannerTokenSource::TokenList bcplus::parser::detail::Scanner::TokenList
A list of tokens.
Definition at line 28 of file Scanner.h.
Constructor & Destructor Documentation
bcplus::parser::detail::Scanner::Scanner (Configuration const * config)
Parameters
config System wide configuration information
Definition at line 28 of file Scanner.1.cpp.
     : _cond(yycNORMAL), _config(config), _in_macro(false) {
     // Intentionally left blank
 }
bcplus::parser::detail::Scanner::~Scanner () virtual
Destructor.
Definition at line 33 of file Scanner.1.cpp.
                   {
     // Intentionally left blank
 }
Member Function Documentation
void bcplus::parser::detail::Scanner::close ()
Closes all streams open by the scanner and resets its state.
Definition at line 566 of file Scanner.1.cpp.
                     {
     _sources.clear();
 }
Location bcplus::parser::detail::Scanner::loc () const inline
Gets the current location of the scanner.
Definition at line 133 of file Scanner.h.
Referenced by readToken().
 { return (_sources.size() ? _sources.front()->loc() : Location(NULL, 0, 0)); }
bool bcplus::parser::detail::Scanner::push_back (boost::filesystem::path const & file, bool squelch = false)
Attempts to open the provided file and append it to the end of the stream being read by the scanner.
Parameters
file The file to read from.
squelch Whether to silence all errors resulting from this call.
Returns
True if successful, false otherwise.
Referenced by push_back().
void bcplus::parser::detail::Scanner::push_back (char const * buffer, Location const & loc = Location(NULL, 0, 0), bool track_position = false)
Appends the provided null-terminated buffer to the end of the stream being read by the scanner.
Parameters
buffer The null-terminated buffer to read from.
loc The location to display in messages partaining to this buffer.
track_position Whether the position should be tracked within this buffer (starting from {loc})
Definition at line 56 of file Scanner.1.cpp.
References babb::utils::ref_ptr< T >::get().
{
     u::ref_ptr<ScannerBufferSource> src = new ScannerBufferSource(_config, buffer, loc, track_position);
     _sources.push_back(src.get());
 }
void bcplus::parser::detail::Scanner::push_back (Token * token)
Appends the provided token to the end of the stream being read by the scanner.
Parameters
token The token to inject
Definition at line 61 of file Scanner.1.cpp.
References push_back(), and bcplus::parser::detail::ScannerSource::Type::TOKENS.
{
     if (!_sources.size() || _sources.back()->type() != ScannerSource::Type::TOKENS) {
         _sources.push_back(new ScannerTokenSource(token));
     } else ((ScannerTokenSource*)_sources.back().get())->push_back(token);
 }
void bcplus::parser::detail::Scanner::push_back (TokenList * tokens)
Appends the provided token to the end of the stream being read by the scanner.
Parameters
tokens The tokens to inject
Definition at line 73 of file Scanner.1.cpp.
References push_back(), and bcplus::parser::detail::ScannerSource::Type::TOKENS.
{
     if (!_sources.size() || _sources.back()->type() != ScannerSource::Type::TOKENS) {
         _sources.push_back(new ScannerTokenSource(tokens));
     } else ((ScannerTokenSource*)_sources.back().get())->push_back(tokens);
 }
bool bcplus::parser::detail::Scanner::push_front (boost::filesystem::path const & file, bool squelch = false)
Attempts to open the provided file and inject it into the front of the stream being read by the scanner.
Parameters
file The file to read from.
squelch Whether to silence all errors resulting from this call.
Returns
True if successful, false otherwise.
Referenced by push_front().
void bcplus::parser::detail::Scanner::push_front (char const * buffer, Location const & loc = Location(NULL, 0, 0), bool track_position = false)
Injects the provided null-terminated buffer into the front of the stream being read by the scanner.
Parameters
buffer The null-terminated buffer to read from.
loc The location to display in messages partaining to this buffer.
track_position Whether the position should be tracked within this buffer (starting from {loc})
Definition at line 51 of file Scanner.1.cpp.
References babb::utils::ref_ptr< T >::get().
{
     u::ref_ptr<ScannerBufferSource> src = new ScannerBufferSource(_config, buffer, loc, track_position);
     _sources.push_front(src.get());
 }
void bcplus::parser::detail::Scanner::push_front (Token * token)
Injects the provided token into the from of the stream being read by the scanner.
Parameters
token The token to inject
Definition at line 67 of file Scanner.1.cpp.
References push_front(), and bcplus::parser::detail::ScannerSource::Type::TOKENS.
{
     if (!_sources.size() || _sources.front()->type() != ScannerSource::Type::TOKENS) {
         _sources.push_front(new ScannerTokenSource(token));
     } else ((ScannerTokenSource*)_sources.front().get())->push_front(token);
 }
void bcplus::parser::detail::Scanner::push_front (TokenList * tokens)
Injects the provided tokens into the from of the stream being read by the scanner.
Parameters
tokens The tokens to inject
Definition at line 79 of file Scanner.1.cpp.
References push_front(), and bcplus::parser::detail::ScannerSource::Type::TOKENS.
{
     if (!_sources.size() || _sources.front()->type() != ScannerSource::Type::TOKENS) {
         _sources.push_front(new ScannerTokenSource(tokens));
     } else ((ScannerTokenSource*)_sources.front().get())->push_front(tokens);
 }
Token * bcplus::parser::detail::Scanner::readToken ()
Reads a token from the currently open file.
Returns
The token that was read in.
Definition at line 86 of file Scanner.1.cpp.
References bcplus::Location::file(), bcplus::parser::detail::ScannerSource::loc(), loc(), bcplus::parser::detail::ScannerSource::Type::RAW, babb::utils::ref_ptr< T >::release(), size(), T_EOF, T_ERR_IO, bcplus::parser::detail::ScannerSource::Type::TOKENS, bcplus::Verb::TRACE_SCANNER, and bcplus::parser::detail::ScannerSource::type().
{
     u::ref_ptr<Token> token = NULL;
     if (!size()) {
         Location l = loc();
         token  = new Token(T_EOF, new ReferencedString("<EOF>"), l, l);
     } else {
         do {
             ScannerSource* src = _sources.front();
 #ifndef NDEBUG
             _config->ostream(Verb::TRACE_SCANNER) << "TRACE: " << size() << " sources, reading from \""
                 << (src->loc().file() ? src->loc().file()->native() : std::string("<NULL>")) << "\"." << std::endl;
 #endif
             switch(src->type()) {
             case ScannerSource::Type::RAW:
                 token = tokenize((ScannerRawSource*)src);
                 break;
             case ScannerSource::Type::TOKENS:
                 token = ((ScannerTokenSource*)src)->next();
                 break;
             }
             if (!token || token->type() == T_ERR_IO) {
 #ifndef NDEBUG
                 _config->ostream(Verb::TRACE_SCANNER) << "TRACE: Scanner encountered IO error." << std::endl;
 #endif
                 _sources.pop_front();
             } else if (token->type() == T_EOF) {
 #ifndef NDEBUG
                 _config->ostream(Verb::TRACE_SCANNER) << "TRACE: Scanner encountered end of input source." << std::endl;
 #endif
                 _sources.pop_front();
             }
         } while (token && token->type() == T_EOF && size());
     }
     if (!token) {
         Location l = loc();
 #ifndef NDEBUG
         _config->ostream(Verb::TRACE_SCANNER) << "TRACE: Scanner got a null token." << std::endl;
 #endif
         token  = new Token(T_ERR_IO, new ReferencedString("<IO ERROR>"), l, l);
     }
 #ifndef NDEBUG
     _config->ostream(Verb::TRACE_SCANNER) << "TRACE: " << token->beginLoc() << ": (" << token->typeString() << "): \"" << *token << "\": Read from scanner." << std::endl;
 #endif
     return token.release();
 }
size_t bcplus::parser::detail::Scanner::size () const inline
Gets the number of input streams associated with this scanner.
Definition at line 126 of file Scanner.h.
Referenced by readToken().
 { return _sources.size(); }
The documentation for this class was generated from the following files:
bcplusparser/include/bcplus/parser/detail/Scanner.h
bcplusparser/src/bcplus/parser/detail/Scanner.1.cpp
bcplusparser/src/bcplus/parser/detail/Scanner.2.cpp
bcplusparser/src/bcplus/parser/detail/Scanner.3.cpp