cplus2asp: bcplus::statements::detail::DynamicLawForm< type, body_t, head_t, ifbody_t, unless_t, where_t > Class Template Reference
bcplus::statements::detail::DynamicLawForm< type, body_t, head_t, ifbody_t, unless_t, where_t > Class Template Reference
Base law form for basic laws.
#include <DynamicLawForm.h>
Public Types
typedef body_t body_type
typedef head_t head_type
typedef ifbody_t ifbody_type
typedef unless_t unless_type
typedef where_t where_type
Public Member Functions
DynamicLawForm (body_t const *body, head_t const *head, ifbody_t const *ifbody, unless_t const *unless, where_t const *where, Location const &begin=Location(NULL, 0, 0), Location const &end=Location(NULL, 0, 0))
virtual ~DynamicLawForm ()
body_t const * body () const
Get the body element.
head_t const * head () const
Get the head element.
ifbody_t const * ifbody () const
Get the 'if' clause.
unless_t const * unless () const
Get the 'unless' clause.
where_t const * where () const
Get the 'where' clause.
virtual Statement * copy () const
Perform a dep copy of this statement.
Public Member Functions inherited from bcplus::statements::Statement
Statement (Type::type type, Location const &begin=Location(NULL, 0, 0), Location const &end=Location(NULL, 0, 0))
Basic Contructor.
~Statement ()
Destructor Stub.
Type::type type () const
Get the type of this statement.
char const * typeString () const
Get the string representation of the statement type.
Location const & beginLoc () const
Get the beginning location of this statement.
Location const & endLoc () const
Get the ending location of this statement.
Public Member Functions inherited from babb::utils::Referenced
Referenced ()
Referenced ()
Additional Inherited Members
Protected Member Functions inherited from babb::utils::Referenced
virtual ~Referenced ()
virtual ~Referenced ()
Detailed Description
template<Statement::Type::type type, typename body_t, typename head_t, typename ifbody_t, typename unless_t, typename where_t>
class bcplus::statements::detail::DynamicLawForm< type, body_t, head_t, ifbody_t, unless_t, where_t >
Base law form for basic laws.
Definition at line 15 of file DynamicLawForm.h.
Member Typedef Documentation
template<Statement::Type::type type, typename body_t , typename head_t , typename ifbody_t , typename unless_t , typename where_t > typedef body_t bcplus::statements::detail::DynamicLawForm< type, body_t, head_t, ifbody_t, unless_t, where_t >::body_type
Definition at line 21 of file DynamicLawForm.h.
template<Statement::Type::type type, typename body_t , typename head_t , typename ifbody_t , typename unless_t , typename where_t > typedef head_t bcplus::statements::detail::DynamicLawForm< type, body_t, head_t, ifbody_t, unless_t, where_t >::head_type
Definition at line 22 of file DynamicLawForm.h.
template<Statement::Type::type type, typename body_t , typename head_t , typename ifbody_t , typename unless_t , typename where_t > typedef ifbody_t bcplus::statements::detail::DynamicLawForm< type, body_t, head_t, ifbody_t, unless_t, where_t >::ifbody_type
Definition at line 23 of file DynamicLawForm.h.
template<Statement::Type::type type, typename body_t , typename head_t , typename ifbody_t , typename unless_t , typename where_t > typedef unless_t bcplus::statements::detail::DynamicLawForm< type, body_t, head_t, ifbody_t, unless_t, where_t >::unless_type
Definition at line 24 of file DynamicLawForm.h.
template<Statement::Type::type type, typename body_t , typename head_t , typename ifbody_t , typename unless_t , typename where_t > typedef where_t bcplus::statements::detail::DynamicLawForm< type, body_t, head_t, ifbody_t, unless_t, where_t >::where_type
Definition at line 25 of file DynamicLawForm.h.
Constructor & Destructor Documentation
template<Statement::Type::type t, typename body_t , typename head_t , typename ifbody_t , typename unless_t , typename where_t > bcplus::statements::detail::DynamicLawForm< t, body_t, head_t, ifbody_t, unless_t, where_t >::DynamicLawForm (body_t const * body, head_t const * head, ifbody_t const * ifbody, unless_t const * unless, where_t const * where, Location const & begin = Location(NULL, 0, 0), Location const & end = Location(NULL, 0, 0))
Definition at line 13 of file DynamicLawForm.impl.h.
     : Statement(t, begin, end), _body(body), _head(head), _ifbody(ifbody), _unless(unless), _where(where) {
     /* Intentionally left blank */
 }
template<Statement::Type::type t, typename body_t , typename head_t , typename ifbody_t , typename unless_t , typename where_t > bcplus::statements::detail::DynamicLawForm< t, body_t, head_t, ifbody_t, unless_t, where_t >::~DynamicLawForm () virtual
Definition at line 21 of file DynamicLawForm.impl.h.
{
     /* Intentionally left blank */
 }
Member Function Documentation
template<Statement::Type::type type, typename body_t , typename head_t , typename ifbody_t , typename unless_t , typename where_t > body_t const* bcplus::statements::detail::DynamicLawForm< type, body_t, head_t, ifbody_t, unless_t, where_t >::body () const inline
Get the body element.
Definition at line 65 of file DynamicLawForm.h.
Referenced by cplus2asp::cplus2asp_bin::Translator::translate().
 { return _body; }
template<Statement::Type::type t, typename body_t , typename head_t , typename ifbody_t , typename unless_t , typename where_t > Statement * bcplus::statements::detail::DynamicLawForm< t, body_t, head_t, ifbody_t, unless_t, where_t >::copy () const virtual
Perform a dep copy of this statement.
Implements bcplus::statements::Statement.
Definition at line 26 of file DynamicLawForm.impl.h.
{
     return new DynamicLawForm<t, body_t, head_t, ifbody_t,  unless_t, where_t>(body(), head(), ifbody(), unless(), where(), beginLoc(), endLoc());
 }
template<Statement::Type::type type, typename body_t , typename head_t , typename ifbody_t , typename unless_t , typename where_t > head_t const* bcplus::statements::detail::DynamicLawForm< type, body_t, head_t, ifbody_t, unless_t, where_t >::head () const inline
Get the head element.
Definition at line 68 of file DynamicLawForm.h.
Referenced by cplus2asp::cplus2asp_bin::Translator::translate().
 { return _head; }
template<Statement::Type::type type, typename body_t , typename head_t , typename ifbody_t , typename unless_t , typename where_t > ifbody_t const* bcplus::statements::detail::DynamicLawForm< type, body_t, head_t, ifbody_t, unless_t, where_t >::ifbody () const inline
Get the 'if' clause.
Definition at line 71 of file DynamicLawForm.h.
Referenced by cplus2asp::cplus2asp_bin::Translator::translate().
 { return _ifbody; }
template<Statement::Type::type type, typename body_t , typename head_t , typename ifbody_t , typename unless_t , typename where_t > unless_t const* bcplus::statements::detail::DynamicLawForm< type, body_t, head_t, ifbody_t, unless_t, where_t >::unless () const inline
Get the 'unless' clause.
Definition at line 74 of file DynamicLawForm.h.
Referenced by cplus2asp::cplus2asp_bin::Translator::translate().
 { return _unless; }
template<Statement::Type::type type, typename body_t , typename head_t , typename ifbody_t , typename unless_t , typename where_t > where_t const* bcplus::statements::detail::DynamicLawForm< type, body_t, head_t, ifbody_t, unless_t, where_t >::where () const inline
Get the 'where' clause.
Definition at line 77 of file DynamicLawForm.h.
Referenced by cplus2asp::cplus2asp_bin::Translator::translate().
 { return _where; }
The documentation for this class was generated from the following files:
bcplusparser/include/bcplus/statements/detail/DynamicLawForm.h
bcplusparser/include/bcplus/statements/detail/DynamicLawForm.impl.h