cplus2asp: cplus2asp::bcbridge::NetworkClient Class Reference
cplus2asp::bcbridge::NetworkClient Class Reference
A client wrapper in order to facilitate interaction with oClingo.
#include <NetworkClient.h>
Public Member Functions
NetworkClient (std::string const &hostname, std::string const &port, boost::function< void(boost::system::error_code const &error, char const *msg, size_t length)> callback, size_t readBufferSize=READ_BUFFER_DEFAULT)
Initializes the client, binding it to the socket and prepping it to read/write.
~NetworkClient ()
Destructor. Closes the connection.
void write (std::string const &msg, bool eom=false)
Asynchronously writes a message to the socket.
void close ()
Asynchronously closes the socket connection.
bool open ()
Determines whether the client connection is open.
void lock ()
Provides thread synchronization services by locking a mutex that must be acquired by this object prior to calling the read callback.
void unlock ()
Provides thread synchronization services by unlocking a mutex that must be acquired by this object prior to calling the read callback.
Public Member Functions inherited from babb::utils::Referenced
Referenced ()
Referenced ()
Static Public Attributes
static size_t const READ_BUFFER_DEFAULT = 4096
Default buffer size.
Additional Inherited Members
Protected Member Functions inherited from babb::utils::Referenced
virtual ~Referenced ()
virtual ~Referenced ()
Detailed Description
A client wrapper in order to facilitate interaction with oClingo.
Based on the boost ASIO example provided here: http://www.boost.org/doc/libs/1_39_0/doc/html/boost_asio/example/chat/chat_client.cpp
Definition at line 46 of file NetworkClient.h.
Constructor & Destructor Documentation
cplus2asp::bcbridge::NetworkClient::NetworkClient (std::string const & hostname, std::string const & port, boost::function< void(boost::system::error_code const &error, char const *msg, size_t length)> callback, size_t readBufferSize = READ_BUFFER_DEFAULT) inline
Initializes the client, binding it to the socket and prepping it to read/write.
Parameters
hostname The hostname to connect to.
port The port to connect to.
callback The function called whenever a message is received.
readBufferSize The size of the read buffer. callback should have the signature (boost::system::error_code error, char const* msg, size_t length) s.t.: error - describes any I/O errors that have occurred. msg - The buffer containing the message contents. length - The number of bytes received.
Definition at line 99 of file NetworkClient.h.
References utils::error().
         : mIOService(),
           mSocket(mIOService),
           mResolver(mIOService),
           mQuery(hostname, port),
           mOpen(false)
     {
         mEndpointIterator = mResolver.resolve(mQuery);
         mCallback = callback;
             // initialize buffers
         mReadBufSz = readBufferSize;
         mReadBuf = new char[readBufferSize];
 //      boost::asio::ip::tcp::endpoint endpoint = *mEndpointIterator;
         // Bind to port.
         //mSocket.async_connect(endpoint,
         //  boost::bind(&NetworkClient::handler_connect, this,
     //      boost::asio::placeholders::error, ++mEndpointIterator));
         async_connect(mSocket,  mEndpointIterator,
             boost::bind(&NetworkClient::infinite_connect, this,
                 boost::asio::placeholders::error, boost::asio::placeholders::iterator),
             boost::bind(&NetworkClient::handler_connect, this,
                 boost::asio::placeholders::error, boost::asio::placeholders::iterator));
           mIOThread = new boost::thread(boost::bind(&boost::asio::io_service::run, &mIOService));
     }
cplus2asp::bcbridge::NetworkClient::~NetworkClient () inline
Destructor. Closes the connection.
Definition at line 136 of file NetworkClient.h.
References close().
 { close(); }
Member Function Documentation
void cplus2asp::bcbridge::NetworkClient::close () inline
Asynchronously closes the socket connection.
Definition at line 151 of file NetworkClient.h.
Referenced by ~NetworkClient().
{
         std::cout << "Closing.\n";
         //mIOService.post(boost::bind(&NetworkClient::do_close, this));
         do_close();
 //      mIOThread->join();
         delete mIOThread;
         std::cout << "Closed.\n";
     }
void cplus2asp::bcbridge::NetworkClient::lock () inline
Provides thread synchronization services by locking a mutex that must be acquired by this object prior to calling the read callback.
Definition at line 165 of file NetworkClient.h.
{
         mExternalMutex.lock();
     }
bool cplus2asp::bcbridge::NetworkClient::open () inline
Determines whether the client connection is open.
Definition at line 161 of file NetworkClient.h.
 { return mOpen; }
void cplus2asp::bcbridge::NetworkClient::unlock () inline
Provides thread synchronization services by unlocking a mutex that must be acquired by this object prior to calling the read callback.
Definition at line 171 of file NetworkClient.h.
{
         mExternalMutex.unlock();
     }
void cplus2asp::bcbridge::NetworkClient::write (std::string const & msg, bool eom = false)
Asynchronously writes a message to the socket.
Parameters
msg The message to write.
Whether to append the EOM byte to the message.
Definition at line 44 of file NetworkClient.cpp.
References utils::error().
{
     mInternalMutex.lock();
     bool write_in_progress = !mWriteBuf.empty();
     mWriteBuf.push_back("");
     mWriteBuf.back() = msg;
     if (eom) mWriteBuf.back() += '\0';
     mInternalMutex.unlock();
     if (!write_in_progress)
     {
         // Request to write if we aren't already.
         boost::asio::async_write(mSocket,
             boost::asio::buffer(mWriteBuf.front().data(), mWriteBuf.front().size()),
             boost::bind(&NetworkClient::handler_write, this,
                 boost::asio::placeholders::error));
     }
 }
Member Data Documentation
size_t const cplus2asp::bcbridge::NetworkClient::READ_BUFFER_DEFAULT = 4096 static
Default buffer size.
Definition at line 54 of file NetworkClient.h.
The documentation for this class was generated from the following files:
bcbridge/NetworkClient.h
bcbridge/NetworkClient.cpp