cplus2asp: babb::utils::ref_ptr< T > Class Template Reference
babb::utils::ref_ptr< T > Class Template Reference
Referenced counted pointer class.
#include <ref_ptr.h>
Public Member Functions
ref_ptr (T *ptr=NULL)
Constructor.
ref_ptr (ref_ptr< T > const &other)
Copy constructor.
~ref_ptr ()
Destructor.
T * get () const
bool valid () const
operator T * ()
operator T const * () const
T * release ()
Release the memory location from this pointer without deallocating it.
ref_ptr< T > & operator= (T *other)
Assignment.
ref_ptr< T > & operator= (ref_ptr< T > const &other)
ref_ptr< T > & operator= (weak_ptr< T > const &other)
ref_ptr< T > & operator= (unsafe_ptr< T > const &other)
T & operator* () const
Dereference.
T * operator-> () const
ref_ptr (T *ptr=NULL)
Constructor.
ref_ptr (ref_ptr< T > const &other)
Copy constructor.
~ref_ptr ()
Destructor.
T * get () const
bool valid () const
operator T * ()
operator T const * () const
T * release ()
Release the memory location from this pointer without deallocating it.
ref_ptr< T > & operator= (T *other)
Assignment.
ref_ptr< T > & operator= (ref_ptr< T > const &other)
ref_ptr< T > & operator= (weak_ptr< T > const &other)
ref_ptr< T > & operator= (unsafe_ptr< T > const &other)
T & operator* () const
Dereference.
T * operator-> () const
Detailed Description
template<typename T>
class babb::utils::ref_ptr< T >
Referenced counted pointer class.
Parameters
T The type which it's referencing. Should ONLY be descendant of Reference.
Definition at line 15 of file ref_ptr.h.
Constructor & Destructor Documentation
template<typename T> babb::utils::ref_ptr< T >::ref_ptr (T * ptr = NULL) inline
Constructor.
Definition at line 36 of file ref_ptr.h.
{
         _ptr = ptr;
         if (ptr) ptr->_ref();
     }
template<typename T> babb::utils::ref_ptr< T >::ref_ptr (ref_ptr< T > const & other) inline
Copy constructor.
Definition at line 42 of file ref_ptr.h.
{
         _ptr = const_cast<T*>(other.get());
         if (_ptr) _ptr->_ref();
     }
template<typename T> babb::utils::ref_ptr< T >::~ref_ptr () inline
Destructor.
Definition at line 49 of file ref_ptr.h.
                       {
         if (_ptr && !_ptr->_unref()) {
             delete _ptr;
         }
     }
template<typename T> babb::utils::ref_ptr< T >::ref_ptr (T * ptr = NULL) inline
Constructor.
Definition at line 36 of file ref_ptr.h.
{
         _ptr = ptr;
         if (ptr) ptr->_ref();
     }
template<typename T> babb::utils::ref_ptr< T >::ref_ptr (ref_ptr< T > const & other) inline
Copy constructor.
Definition at line 42 of file ref_ptr.h.
{
         _ptr = const_cast<T*>(other.get());
         if (_ptr) _ptr->_ref();
     }
template<typename T> babb::utils::ref_ptr< T >::~ref_ptr () inline
Destructor.
Definition at line 49 of file ref_ptr.h.
                       {
         if (_ptr && !_ptr->_unref()) {
             delete _ptr;
         }
     }
Member Function Documentation
template<typename T> T* babb::utils::ref_ptr< T >::get () const inline
Definition at line 58 of file ref_ptr.h.
Referenced by bcplus::symbols::Symbol::metadata(), babb::utils::unsafe_ptr< T >::operator=(), babb::utils::weak_ptr< const bcplus::symbols::ObjectSymbol >::operator=(), babb::utils::ref_ptr< bcplus::elements::detail::ElementClass >::operator=(), bcplus::parser::detail::Scanner::push_back(), bcplus::parser::detail::Scanner::push_front(), babb::utils::ref_ptr< bcplus::elements::detail::ElementClass >::ref_ptr(), cplus2asp::bcbridge::Driver::run(), cplus2asp::cplus2asp_bin::Translator::translate(), and babb::utils::weak_ptr< const bcplus::symbols::ObjectSymbol >::weak_ptr().
 { return _ptr; }
template<typename T> T* babb::utils::ref_ptr< T >::get () const inline
Definition at line 58 of file ref_ptr.h.
 { return _ptr; }
template<typename T> babb::utils::ref_ptr< T >::operator T * () inline
Definition at line 62 of file ref_ptr.h.
 { return _ptr; }
template<typename T> babb::utils::ref_ptr< T >::operator T * () inline
Definition at line 62 of file ref_ptr.h.
 { return _ptr; }
template<typename T> babb::utils::ref_ptr< T >::operator T const * () const inline
Definition at line 63 of file ref_ptr.h.
 { return _ptr; }
template<typename T> babb::utils::ref_ptr< T >::operator T const * () const inline
Definition at line 63 of file ref_ptr.h.
 { return _ptr; }
template<typename T> T& babb::utils::ref_ptr< T >::operator* () const inline
Dereference.
Definition at line 111 of file ref_ptr.h.
{
         return *_ptr;
     }
template<typename T> T& babb::utils::ref_ptr< T >::operator* () const inline
Dereference.
Definition at line 111 of file ref_ptr.h.
{
         return *_ptr;
     }
template<typename T> T* babb::utils::ref_ptr< T >::operator-> () const inline
Definition at line 115 of file ref_ptr.h.
{
         return _ptr;
     }
template<typename T> T* babb::utils::ref_ptr< T >::operator-> () const inline
Definition at line 115 of file ref_ptr.h.
{
         return _ptr;
     }
template<typename T> ref_ptr<T>& babb::utils::ref_ptr< T >::operator= (T * other) inline
Assignment.
Definition at line 79 of file ref_ptr.h.
{
         if (_ptr == other) return *this;
         //  Make sure to remove the reference from the current pointer.
         if (_ptr && !_ptr->_unref()) {
             delete _ptr;
         }
         _ptr = other;
         if (_ptr) _ptr->_ref();
         return *this;
     }
template<typename T> ref_ptr<T>& babb::utils::ref_ptr< T >::operator= (T * other) inline
Assignment.
Definition at line 79 of file ref_ptr.h.
{
         if (_ptr == other) return *this;
         //  Make sure to remove the reference from the current pointer.
         if (_ptr && !_ptr->_unref()) {
             delete _ptr;
         }
         _ptr = other;
         if (_ptr) _ptr->_ref();
         return *this;
     }
template<typename T> ref_ptr<T>& babb::utils::ref_ptr< T >::operator= (ref_ptr< T > const & other) inline
Definition at line 92 of file ref_ptr.h.
{
         return *this = other.get();
     }
template<typename T> ref_ptr<T>& babb::utils::ref_ptr< T >::operator= (ref_ptr< T > const & other) inline
Definition at line 92 of file ref_ptr.h.
{
         return *this = other.get();
     }
template<typename T> ref_ptr<T>& babb::utils::ref_ptr< T >::operator= (weak_ptr< T > const & other) inline
Definition at line 96 of file ref_ptr.h.
{
         return *this = other.get();
     }
template<typename T> ref_ptr<T>& babb::utils::ref_ptr< T >::operator= (weak_ptr< T > const & other) inline
Definition at line 96 of file ref_ptr.h.
{
         return *this = other.get();
     }
template<typename T> ref_ptr<T>& babb::utils::ref_ptr< T >::operator= (unsafe_ptr< T > const & other) inline
Definition at line 100 of file ref_ptr.h.
{
         return *this = other.get();
     }
template<typename T> ref_ptr<T>& babb::utils::ref_ptr< T >::operator= (unsafe_ptr< T > const & other) inline
Definition at line 100 of file ref_ptr.h.
{
         return *this = other.get();
     }
template<typename T> T* babb::utils::ref_ptr< T >::release () inline
Release the memory location from this pointer without deallocating it.
Definition at line 66 of file ref_ptr.h.
{
         if (!_ptr) return NULL;
         T* p = _ptr;
         _ptr->_unref();
         _ptr = NULL;
         return p;
     }
template<typename T> T* babb::utils::ref_ptr< T >::release () inline
Release the memory location from this pointer without deallocating it.
Definition at line 66 of file ref_ptr.h.
Referenced by bcplus::parser::BCParser::_newRange(), bcplus::parser::BCParser::_newRangeSymbol(), as2transition::Predicate::format(), bcplus::elements::Element::newConstSet(), bcplus::elements::Element::newVarSet(), bcplus::parser::detail::MacroParser::next(), bcplus::parser::BCParser::parse(), and bcplus::parser::detail::Scanner::readToken().
{
         if (!_ptr) return NULL;
         T* p = _ptr;
         _ptr->_unref();
         _ptr = NULL;
         return p;
     }
template<typename T> bool babb::utils::ref_ptr< T >::valid () const inline
Definition at line 59 of file ref_ptr.h.
 { return _ptr != NULL; }
template<typename T> bool babb::utils::ref_ptr< T >::valid () const inline
Definition at line 59 of file ref_ptr.h.
 { return _ptr != NULL; }
The documentation for this class was generated from the following file:
as2transition/include/babb/utils/memory/ref_ptr.h