cplus2asp: ConstantLikeElement Class Reference
ConstantLikeElement Class Reference
Child of BaseLikeElement that represents a base element with the behavior of a constant.
#include <parser_types.h>
Public Member Functions
ConstantLikeElement (std::string const &baseName, Constant const *symbolRef, ParseElementList *params=NULL, bool parens=false)
Full constructor.
virtual std::ostream & translate (std::ostream &out, Context &context) const
Method that generates a translated string representation of the element with preceeding @ if a symbol is understood as a lua function call.
virtual bool hasConstants (unsigned int types, bool includeParams=true, bool includeEq=true) const
Returns true if the element (or any of its children) are constants of the provided types.
virtual bool isDefinite (bool allowComparison=false, bool allowChoice=false, bool allowAtomicNegation=false) const
Determines if the element contains a single atom, a unary expression w/ a single atom, or a conjunction thereof.
virtual bool isSingleAtom (bool allowAtomicNegation=false) const
Whether the formula is a single atom.
virtual bool hasLuaCalls (bool includeParams=true, bool includeEq=true) const
Determines if the element contains any calls to LUA.
virtual IPart determineQueryIPart () const
Determines the proper IPart to place the formula in.
virtual ParseElement * copy () const
Returns an exact copy of the parse element.
virtual bool isNumeric () const
Determines if the element ranges over numeric values.
virtual bool isBoolean () const
Determines if the element ranges over boolean values.
Sort const * domain () const
Gets the domain of the constant (or null)
bool isContribConstant () const
virtual ~ConstantLikeElement ()
Destructor.
Public Member Functions inherited from BaseLikeElement
BaseLikeElement (ParseElementType elemType, std::string const &baseName, Element const *symbolRef, ParseElementList *params=NULL, bool parens=false)
Full constructor.
virtual bool isArithExpr () const
Determines if the element is a valid arithmetic expression.
virtual std::ostream & fullName (std::ostream &out) const
Prints the untranslated element string.
virtual void aggregateUndefined (BaseElementList &outIdentifiers)
Aggregates all of the undefined identifiers (which are assumed to be constants).
std::string const & baseName () const
Gets the base name for the element.
Element const * ref () const
Gets a reference to the global symbol which this element is an instance of.
void ref (Element const *_ref)
Sets the global symbol which this element is an instance of.
ParseElementList::const_iterator paramsBegin () const
Gets an iterator for the beginning of the parameter list.
ParseElementList::const_iterator paramsEnd () const
Gets an iterator for the end of the parameter list.
size_t arity () const
Gets the number of parameters the element has.
void detachParams ()
Clears the list of parameters without deallocating them.
virtual bool guessParamSorts (ConstSortList &outSorts)
Attempts to guess the sorts of each parameter.
virtual std::ostream & translateParams (std::ostream &out, Context &context, bool force=false) const
Internal helper to translate, creates a list of translated params.
virtual ~BaseLikeElement ()
Destructor.
Public Member Functions inherited from ParseElement
ParseElement (ParseElementType elemType, bool parens=false)
Default constructor.
bool isTrivial (bool includeParams=true, bool includeEq=true) const
Determines if the element contains no (real) constants.
std::string fullName () const
Alternative helper to fullName(std::ostream&).
ParseElementType getType () const
Gets the type of the parse element.
void parens (bool parens)
Sets whether the expression is wrapped in parentheses.
bool parens () const
Gets whether the element is encompassed in parens.
virtual ~ParseElement ()
Destructor.
Protected Member Functions
std::string translatePrefix () const
Outputs the string this constant uses as a prefix for the atom.
std::string translatePostfix (Context &context) const
Outputs the string used as a postfix.
virtual std::ostream & translateAsConstant (std::ostream &out, Context &context) const
Helper translator method to handle translating the constant as an atom.
virtual std::ostream & translateAsVariable (std::ostream &out, Context &context) const
Helper translator method to handle translating the constant as a variable.
Protected Member Functions inherited from BaseLikeElement
ParseElementList::iterator paramsBegin ()
Gets an iterator for the beginning of the parameter list.
ParseElementList::iterator paramsEnd ()
Gets an iterator for the end of the parameter list.
bool hasLuaCallParameters () const
Determines if the base element has a LUA call in its parameter list.
bool hasConstantParameters (unsigned int types) const
Checks to see if there is a nested constant matching the type mask within the parameter list.
Protected Member Functions inherited from ParseElement
bool hasParens () const
Determines if the element has parentheses around it.
std::string translateBeforeParen (bool forceParens=false) const
Helper to translate that intelligently handles the value of parenBefore.
std::string translateAfterParen (bool forceParens=false) const
Helper to translate that intelligently handles the value of parenAfter.
Additional Inherited Members
Public Types inherited from ParseElement
enum ParseElementType {
PELEM_PELEM, PELEM_UOP, PELEM_BOP, PELEM_QUANT,
PELEM_BASELIKE, PELEM_CONSTLIKE, PELEM_OBJLIKE, PELEM_VARLIKE
}
The possible types of a ParseElement instance.
enum ConstMask {
MASK_ACTION = 0x01, MASK_FLUENT = 0x02, MASK_RIGID = 0x04, MASK_STATIC_AB = 0x08,
MASK_DYNAMIC_AB = 0x10, MASK_TRUE_FALSE = 0x20, MASK_SDFLUENT = 0x40, MASK_AB = MASK_STATIC_AB | MASK_DYNAMIC_AB,
MASK_NON_TRIVIAL = ~MASK_TRUE_FALSE, MASK_NON_RIGID = MASK_NON_TRIVIAL & ~MASK_RIGID, MASK_NON_AB = MASK_NON_TRIVIAL & ~MASK_AB
}
Mask values for the various kinds of constants that can be in a formula.
Static Public Member Functions inherited from ParseElement
static std::string getNewVar ()
Gets a new variable whose name is unique within the rule we're translating.
Detailed Description
Child of BaseLikeElement that represents a base element with the behavior of a constant.
Definition at line 703 of file parser_types.h.
Constructor & Destructor Documentation
ConstantLikeElement::ConstantLikeElement (std::string const & baseName, Constant const * symbolRef, ParseElementList * params = NULL, bool parens = false) inline
Full constructor.
Parameters
baseName The base name of the element that's being instantiated (without parameters).
symbolRef A pointer to the symbol that this element is an instance of.
params The list of parameters associated with this instance. Null if there are no parameters.
parens Whether to encase the element in parens.
Definition at line 714 of file parser_types.h.
Referenced by copy().
         : BaseLikeElement(PELEM_CONSTLIKE, baseName, symbolRef, params, parens)
     { /* Intentionally Left Blank */ }
virtual ConstantLikeElement::~ConstantLikeElement () inline virtual
Destructor.
Does not deallocate anything.
Definition at line 742 of file parser_types.h.
 { /* Intentionally Left Blank */ }
Member Function Documentation
ParseElement * ConstantLikeElement::copy () const virtual
Returns an exact copy of the parse element.
Implements BaseLikeElement.
Definition at line 1056 of file parser_types.cpp.
References BaseLikeElement::baseName(), ConstantLikeElement(), BaseLikeElement::paramsBegin(), BaseLikeElement::paramsEnd(), ParseElement::parens(), and BaseLikeElement::ref().
{
     ParseElementList params;
     for (ParseElementList::const_iterator it = paramsBegin(); it != paramsEnd(); it++) {
         params.push_back((*it)->copy());
     }
     return new ConstantLikeElement(baseName(), (Constant const*)ref(), &params, parens());
 }
virtual IPart ConstantLikeElement::determineQueryIPart () const inline virtual
Determines the proper IPart to place the formula in.
Returns
IPART_BASE if the formula is 0:(...), IPART_VOLATILE if the formula is X:(...), and IPART_CUMULATIVE if the formula is anything else.
Implements BaseLikeElement.
Definition at line 728 of file parser_types.h.
 { return IPART_CUMULATIVE; }
Sort const* ConstantLikeElement::domain () const inline
Gets the domain of the constant (or null)
Definition at line 736 of file parser_types.h.
References domain(), and BaseLikeElement::ref().
Referenced by domain(), translateAsVariable(), and Translator::translateShowStmt().
 { return (ref()) ? ((Constant const*)ref())->domain() : NULL; }
bool ConstantLikeElement::hasConstants (unsigned int types, bool includeParams = true, bool includeEq = true) const virtual
Returns true if the element (or any of its children) are constants of the provided types.
Parameters
types A mask containing flags for the types to search for. See ConstMask enum.
includeParams Whether to check the parameters of constants.
includeEq Whether to check the right side of equality within an atom. (The right hand side of comparisons will be checked regardless.)
Returns
True if the element, or any elements "beneach" it, are constants, false otherwise.
Implements BaseLikeElement.
Definition at line 1094 of file parser_types.cpp.
References BaseLikeElement::hasConstantParameters(), isContribConstant(), ParseElement::MASK_ACTION, ParseElement::MASK_DYNAMIC_AB, ParseElement::MASK_FLUENT, ParseElement::MASK_RIGID, ParseElement::MASK_SDFLUENT, ParseElement::MASK_STATIC_AB, BaseLikeElement::paramsBegin(), BaseLikeElement::paramsEnd(), and BaseLikeElement::ref().
{
     bool ret = false;
     Constant::ConstantType type = (ref()) ? ((Constant const*)ref())->constType() : Constant::CONST_UNKNOWN;
     if (types & MASK_ACTION)        ret |= Constant::isActionType(type);
     if (types & MASK_FLUENT)        ret |= Constant::isFluentType(type, false);
     if (types & MASK_SDFLUENT)      ret |= type == Constant::CONST_SDFLUENT;
     if (types & MASK_RIGID)         ret |= type == Constant::CONST_RIGID || type == Constant::CONST_UNKNOWN;
     if (types & MASK_STATIC_AB)     ret |= type == Constant::CONST_STATICAB;
     if (types & MASK_DYNAMIC_AB)    ret |= type == Constant::CONST_DYNAMICAB;
     if (!ret && includeParams) {
         // check the parameters for constants.
         // If this is a contribution constant we should skip the first layer.
         if (isContribConstant()) {
             for(ParseElementList::const_iterator vIter = paramsBegin(); vIter != paramsEnd(); vIter++) {
                 if (((ConstantLikeElement const*)(*vIter))->hasConstantParameters(types)) {
                     ret = true;
                     break;
                 }
             }
         } else {
             ret = hasConstantParameters(types);
         }
     }
     return ret;
 }
virtual bool ConstantLikeElement::hasLuaCalls (bool includeParams = true, bool includeEq = true) const inline virtual
Determines if the element contains any calls to LUA.
Parameters
includeParams Whether to search base element parameter lists.
includeEq Whether to check the right side of equality within an atom. (The right hand side of comparisons will be checked regardless.)
Returns
True if the element or any of its children is a LUA call.
Implements BaseLikeElement.
Definition at line 726 of file parser_types.h.
References BaseLikeElement::hasLuaCallParameters().
                                                         { return includeParams && hasLuaCallParameters(); }
virtual bool ConstantLikeElement::isBoolean () const inline virtual
Determines if the element ranges over boolean values.
Returns
True if the element ranges over strictly boolean values, false otherwise.
Implements BaseLikeElement.
Definition at line 733 of file parser_types.h.
References BaseLikeElement::ref().
Referenced by isDefinite(), and isSingleAtom().
 { return !ref() || ref()->isBoolean(); }
bool ConstantLikeElement::isContribConstant () const inline
Definition at line 737 of file parser_types.h.
References isContribConstant(), and BaseLikeElement::ref().
Referenced by hasConstants(), isContribConstant(), and translateAsConstant().
 { return ref() && ((Constant const*)ref())->isContribConstant(); }
virtual bool ConstantLikeElement::isDefinite (bool allowComparison = false, bool allowChoice = false, bool allowAtomicNegation = false) const inline virtual
Determines if the element contains a single atom, a unary expression w/ a single atom, or a conjunction thereof.
Parameters
allowComparison Whether to allow comparison operators in the formula.
allowChoice Whether to allow choice rules in the formula.
allowAtomicNegation whether to allow -p or "not p" where p is a boolean atom.
Returns
True if the element is a definite formula.
Implements BaseLikeElement.
Definition at line 722 of file parser_types.h.
References isBoolean(), and BaseLikeElement::ref().
         { return ref() && ((Constant const*)ref())->isBoolean(); }
virtual bool ConstantLikeElement::isNumeric () const inline virtual
Determines if the element ranges over numeric values.
Returns
True if the element ranges over strictly numeric values.
Implements BaseLikeElement.
Definition at line 732 of file parser_types.h.
References BaseLikeElement::ref().
 { return ref() && ref()->isNumeric(); }
virtual bool ConstantLikeElement::isSingleAtom (bool allowAtomicNegation = false) const inline virtual
Whether the formula is a single atom.
Returns
True if the element is a single atom c=v (or just c if c is boolean).
Parameters
allowAtomicNegation whether to allow -p or "not p" where p is a boolean atom.
Implements BaseLikeElement.
Definition at line 724 of file parser_types.h.
References isBoolean(), and BaseLikeElement::ref().
         { return ref() && ((Constant const*)ref())->isBoolean(); }
std::ostream & ConstantLikeElement::translate (std::ostream & out, Context & context) const virtual
Method that generates a translated string representation of the element with preceeding @ if a symbol is understood as a lua function call.
Parameters
[out] out - The output stream to write to.
context - The formula context to be used for translation.
Returns
out.
Implements BaseLikeElement.
Definition at line 1068 of file parser_types.cpp.
References BaseLikeElement::baseName(), BaseLikeElement::ref(), Translator::sanitizeConstantName(), translateAsConstant(), translateAsVariable(), and BaseLikeElement::translateParams().
Referenced by translateAsVariable().
 {
     // This tries it's best to output a wrapped atom (i.e. h(eql(<name>(<args>),<value>),<timestep>)).
     // If, for one reason or another, the constant's type isn't available, it'll wing it producing a bare atom <name>(<args>).
     switch (context.getPos()) {
     case Context::POS_INTERNAL:
         // Used for internal sorts and whatnot, just return the bare name.
         out << (ref() ? ref()->baseTransName() : Translator::sanitizeConstantName(baseName()));
         translateParams(out, context);
         break;
     case Context::POS_HEAD:
     case Context::POS_BODY:
     case Context::POS_QUERY:
     case Context::POS_CHOICE_RULE:
         translateAsConstant(out, context);
         break;
     case Context::POS_TERM:
     case Context::POS_ARITHEXPR:
     case Context::POS_MAXIMIZED_INTERNAL:
         translateAsVariable(out, context);
         break;
     }
     return out;
 }
std::ostream & ConstantLikeElement::translateAsConstant (std::ostream & out, Context & context) const protected virtual
Helper translator method to handle translating the constant as an atom.
Parameters
[out] out - The output stream to write the translation to. preceeding @ if a symbol is understood as a lua function call.
context - The formula context to be used for translation. Uses constant translating conventions for the base name.
Returns
A string containing the translated form of the element.
Definition at line 1126 of file parser_types.cpp.
References BaseLikeElement::baseName(), isContribConstant(), BaseLikeElement::ref(), Translator::sanitizeConstantName(), ParseElement::translateAfterParen(), ParseElement::translateBeforeParen(), BaseLikeElement::translateParams(), translatePostfix(), and translatePrefix().
Referenced by translate().
{
     // We are in a logical formula, translate it as an atom
     out <<  translateBeforeParen()
                 << translatePrefix()
                 << (ref() ? ref()->baseTransName() : Translator::sanitizeConstantName(baseName()));
     Context localContext;
     if ( isContribConstant()) {
         localContext = context.mkPos(Context::POS_INTERNAL);
     } else {
         localContext = context;
     }
     translateParams(out, localContext);
     out << translatePostfix(context)
                 << translateAfterParen();
     return out;
 }
std::ostream & ConstantLikeElement::translateAsVariable (std::ostream & out, Context & context) const protected virtual
Helper translator method to handle translating the constant as a variable.
Parameters
[out] out - The output stream to write the translation to. preceeding @ if a symbol is understood as a lua function call.
context - The formula context to be used for translation. Uses constant translating conventions for the base name.
Returns
A string containing the translated form of the element.
Definition at line 1147 of file parser_types.cpp.
References domain(), ParseElement::fullName(), ParseElement::getNewVar(), ltsyyossErr, BaseLikeElement::ref(), and translate().
Referenced by translate().
{
     Context localContext;
     std::ostringstream tmp;
     // We are in a term or arithmetic expression, translate it as a temporary variable.
     if (ref() && !((Constant const*)ref())->isAbnormal())
     {
         // The variable that holds the intermediate value (and register it!).
         std::string var = getNewVar();
         context.addFreeVariable(var, domain());
         // add the appropriate extra clause
         if (context.getPos() != Context::POS_MAXIMIZED_INTERNAL) {
             localContext = context.mkPos(Context::POS_BODY).mkValue(var);
             translate(tmp, localContext);
             context.addExtraClause(tmp.str());
         } else {
             context.addExtraClause(domain()->fullTransName() + "(" + var + ")");
         }
         // return the variable name
 //      out << translateBeforeParen() + var + translateAfterParen();
         out << var;
     } else if (!ref()) {
         ltsyystartParseError();
         ltsyyossErr << "An error occurred while translating the constant ";
         fullName(ltsyyossErr);
         ltsyyossErr << ". The constant doesn't appear to be properly declared.";
         ltsyyreportError();
     } else {
         // This should never happen, as the syntax to trigger this is prohibited in the parser.
         ltsyystartParseError();
         ltsyyossErr << "An error occurred while translating an abnormality constant ";
         fullName(ltsyyossErr);
         ltsyyossErr << ". The constant appears to be used as a function.";
         ltsyyreportError();
     }
     return out;
 }
std::string ConstantLikeElement::translatePostfix (Context & context) const inline protected
Outputs the string used as a postfix.
This is usually ",<value>),<timestamp>)".
Parameters
context - The context to be used for translation.
Returns
A postfix to the atom's name.
Definition at line 758 of file parser_types.h.
References BaseLikeElement::ref().
Referenced by translateAsConstant().
         { return (ref()) ? Constant::translatePostfix(((Constant const*)ref())->constType(), context) : ""; }
std::string ConstantLikeElement::translatePrefix () const inline protected
Outputs the string this constant uses as a prefix for the atom.
Returns
A prefix to the atom's name, usually "h(eql(".
Definition at line 750 of file parser_types.h.
References BaseLikeElement::ref().
Referenced by translateAsConstant().
         { return (ref()) ? Constant::translatePrefix(((Constant const*)ref())->constType()) : ""; }
The documentation for this class was generated from the following files:
cplus2asp.bin/old/parser_types.h
cplus2asp.bin/old/parser_types.cpp