cplus2asp: as2transition/src/main.cpp File Reference
main.cpp File Reference
#include <fstream>
#include <iostream>
#include <string>
#include <cstdlib>
#include <cstring>
#include <algorithm>
#include <cctype>
#include "babb/utils/memory.h"
#include "as2transition/TransitionFormatter.h"
Macros
#define VERSION_MAJOR 3
#define VERSION_MINOR 0
#define VERSION_REV 0
Enumerations
enum ExitCodes { EXIT_NO_SOLUTIONS = 100, EXIT_SOLUTIONS = 101, EXIT_ERROR = 1 }
Functions
void nice_exit (int exitCode, const char *message)
A wrapper for exit() that can output an optional custom message before leaving.
std::istream & skipline (std::istream &in)
Skips the current line of an input stream.
std::ostream & printline (std::istream &in, std::ostream &out)
Skips the current line of an input stream.
int main (int argc, char **argv)
Macro Definition Documentation
#define VERSION_MAJOR 3
Definition at line 84 of file main.cpp.
Referenced by main().
#define VERSION_MINOR 0
Definition at line 85 of file main.cpp.
Referenced by main().
#define VERSION_REV 0
Definition at line 86 of file main.cpp.
Referenced by main().
Enumeration Type Documentation
enum ExitCodes
Enumerator
EXIT_NO_SOLUTIONS
EXIT_SOLUTIONS
EXIT_ERROR
Definition at line 123 of file main.cpp.
 { EXIT_NO_SOLUTIONS = 100, EXIT_SOLUTIONS = 101, EXIT_ERROR = 1 };
Function Documentation
int main (int argc, char ** argv)
Definition at line 126 of file main.cpp.
References EXIT_ERROR, EXIT_NO_SOLUTIONS, EXIT_SOLUTIONS, as2transition::TransitionFormatter::format(), as2transition::TransitionFormatter::help(), nice_exit(), as2transition::TransitionFormatter::parseOption(), printline(), skipline(), VERSION_MAJOR, VERSION_MINOR, and VERSION_REV.
 {
     ifstream ifsFileIn;
     ofstream ofsFileOut;
     istream istIn(cin.rdbuf()); // Gets given a different buffer later.
     ostream ostOut(cout.rdbuf()); // Gets given a different buffer later.
     ExitCodes intExitCode = EXIT_ERROR; // What to exit with on successful program completion. 100 = No solutions, 101 = Solution(s) found.
     string strInFile, strOutFile, strTempString;
     u::ref_ptr<TransitionFormatter> formatter = new TransitionFormatter();
     size_t solutionNum = 0; // The number of the solution (answer set) currently being processed. 1-based (first solution is #1).
     bool blnShowHelp = false, blnBadArgs = false;
     for(int i = 1; i < argc && !blnBadArgs && !blnShowHelp; i++)
     {
         if(!formatter->parseOption(argv[i], true)) {
             if(strcmp(argv[i], "-f") == 0)
             {   // Input file being specified.  Verify they actually gave us a file argument (and they haven't already given this option).
                 if(i < argc-1 && strInFile == "") {
                     i++;
                     strInFile = argv[i];
                 } else {
                     blnBadArgs = true;
                 }
             }
             else if(strcmp(argv[i], "-o") == 0)
             {   // Output file being specified.  Verify they actually gave us a file argument (and they haven't already given this option).
                 if(i < argc-1 && strOutFile == "") {
                     i++;
                     strOutFile = argv[i];
                 } else {
                     blnBadArgs = true;
                 }
             }
             else if(strcmp(argv[i], "-v") == 0 || strcmp(argv[i], "--version") == 0)
             {   // Show version information and quit.
                 cout << argv[0] << " version " << VERSION_MAJOR;
                 cout << "." << VERSION_MINOR;
                 if(VERSION_REV > 0) { cout << "." << VERSION_REV; }
                 cout << endl;
                 nice_exit(0, NULL);
             }
             else if (!strcmp(argv[i], "--help") || !strcmp(argv[i], "-?")) {
                 // They've asked for help
                 blnShowHelp = true;
             }
             else {
                 // Unrecognized option. Hopefully this is a file.
                 if (argv[i][0] != '-'
                         && strInFile == "") {
                     strInFile = argv[i];
                 } else {
                     blnBadArgs = true;
                 }
             }
         }
     }
     // If the user needs help, provide basic usage info and then exit.
     if(blnBadArgs || blnShowHelp)
     {
         if (blnBadArgs) std::cerr << "Error parsing command options.\n";
         cout
             << "Usage: " << argv[0] << " [OPTIONS] [-f IN_FILE] [IN_FILE] [-o OUT_FILE]" << endl
             << "Transforms answer sets from answer set solvers into CCalc-style model lists." << endl
             << "If given a value for IN_FILE, will parse that file, otherwise" << endl
             << "will parse standard in (to support piping input)." << endl
             << "If given a value for OUT_FILE, will output results to OUT_FILE," << endl
             << "otherwise will output to standard out." << endl << endl;
         TransitionFormatter::help(std::cout, true);
         cout
             << "Other Options:" << endl
             << "  --help shows this usage message." << endl
             << "  -v  (or --version) outputs version information." << endl << endl
             << "  Example: gringo some_asp_file.lp | clasp | " << argv[0] << endl
             << "           would pass the answer sets generated by clasp directly" << endl
             << "           to " << argv[0] << ", which would output the models to standard out." << endl
             << "  Example: " << argv[0] << " -f answer_sets.txt -o models.txt" << endl
             << "           would process the answer_sets.txt file and output the" << endl
             << "           results to the file models.txt." << endl << endl << endl;
         if (blnBadArgs) nice_exit(1, NULL);
         else nice_exit(0, NULL);
     }
     // Now we have the input & output files (if given), let's process the input!
     // Figure out which input source we'll be using.
     if(strInFile != "")
     {
         ifsFileIn.open(strInFile.c_str());
         if(!ifsFileIn)
         {
             strTempString = "Error: Unable to open input file \"";
             strTempString += strInFile;
             strTempString += "\".";
             nice_exit(1, strTempString.c_str());
         }
         istIn.rdbuf(ifsFileIn.rdbuf());
     }
     else
     {
         istIn.rdbuf(cin.rdbuf());
     }
     // Figure out which output source we'll be using.
     if(strOutFile != "")
     {
         ofsFileOut.open(strOutFile.c_str());
         if(!ofsFileOut)
         {
             strTempString = "Error: Unable to open output file \"";
             strTempString += strOutFile;
             strTempString += "\".";
             nice_exit(1, strTempString.c_str());
         }
         ostOut.rdbuf(ofsFileOut.rdbuf());
     }
     else
     {
         ostOut.rdbuf(cout.rdbuf());
     }
     // In a loop, go looking for an answer set from the input.
     // get the first token of the line
     istIn >> strTempString;
     while(istIn.good())
     {
         // skip the header
         // clasp
         if (strTempString == "clasp")       { skipline(istIn); istIn >> strTempString; continue; }
         if (strTempString == "Reading")     { skipline(istIn); istIn >> strTempString; continue; }  // 'Reading from'
         if (strTempString == "Solving")     { skipline(istIn); istIn >> strTempString; continue; }  // 'Solving...'
         // cmodels
         if (strTempString == "cmodels")     { skipline(istIn); istIn >> strTempString; continue; }
         if (strTempString == "Program")     { skipline(istIn); istIn >> strTempString; continue; }  // 'Prograim is tight'
         if (strTempString == "Calling")     { skipline(istIn); istIn >> strTempString; continue; }  // 'Calling SAT solver'
         // smodels
         if (strTempString == "smodels")     { skipline(istIn); istIn >> strTempString; continue; }
         // oclingo
         // no header
         // ---------------------------------------------------------------------------
         // clasp
 /*
         if (strTempString == "SATISFIABLE" || strTempString == "UNSATISFIABLE") {
             // skip it.
             skipline(istIn);
             continue;
         }
 */
         // cmodels
         // no footer
         // smodels
 /*
         if (strTempString == "True" || strTempString == "False") {
             // skip it.
             skipline(istIn);
             continue;
         }
 */
         // oclingo
         // no footer
         // ---------------------------------------------------------------------------
         // Show the answer sets, which are in lines following "Answer:"
         if (strTempString == "Answer:") {
             // print the line first
             // printline(istIn, ostOut, oldpos)
             solutionNum++;
             ostOut << "Solution:";
             printline(istIn, ostOut);
             // show the answer set
             formatter->format(istIn, ostOut, false);
             istIn >> strTempString;
             continue;
         } else if (strTempString == "Step:") {
             // oClingo compatibility: Prefaced with 'Step:'
             skipline(istIn);
             solutionNum++;
             formatter->format(istIn, ostOut, false);
             istIn >> strTempString;
             continue;
         }
         // If we are still here we have no idea what this output is. Show it.
         ostOut << strTempString;
         printline(istIn, ostOut);
         istIn >> strTempString;
     }
     if (solutionNum) intExitCode = EXIT_SOLUTIONS;
     // We broke out of that loop either because we hit a footer or we don't have any
     // more to read. Just output whatever is left over.
     while (istIn.good()) {
         if (getline(istIn, strTempString))
             ostOut << strTempString << "\n";
     }
     // If we were using a file as the input source, close it now that we're done with input.
     if(ifsFileIn)
     {
         ifsFileIn.close();
     }
     // Did we get any solutions? If not, output a message indicating so.
     if(intExitCode != EXIT_SOLUTIONS)
     {
         ostOut << "No solution." << endl << endl;
         intExitCode = EXIT_NO_SOLUTIONS; // We didn't find any answer sets, so return the "no solutions" exit code.
     }
     // If we were using a file as the output destination, close it now that we're done with output.
     if(ofsFileOut)
     {
         ofsFileOut.close();
     }
     return intExitCode;
 }
void nice_exit (int exitCode, const char * message)
A wrapper for exit() that can output an optional custom message before leaving.
Outputs message to stdout if exitCode is 0, stderr otherwise. Doesn't output anything if message is NULL.
Parameters
exitCode - The exit code to pass to exit.
message - A message to output to standard out before exiting (terminating newline automatically added).
Definition at line 94 of file main.cpp.
Referenced by main().
 {
     if(exitCode != 0 && message != NULL)
     {
         cerr << message << endl;
     }
     if(exitCode == 0 && message != NULL)
     {
         cout << message << endl;
     }
     exit(exitCode);
 }
std::ostream& printline (std::istream & in, std::ostream & out)
Skips the current line of an input stream.
Definition at line 115 of file main.cpp.
Referenced by main().
{
     std::string tmp;
     getline(in, tmp);
     out << tmp << std::endl;
     return out;
 }
std::istream& skipline (std::istream & in)
Skips the current line of an input stream.
Definition at line 108 of file main.cpp.
Referenced by main().
{
     std::string tmp;
     getline(in, tmp);
     return in;
 }