cplus2asp: bcplusparser/src/bcplus/parser/detail/MacroParser.cpp File Reference
MacroParser.cpp File Reference
#include <string>
#include <iostream>
#include <boost/foreach.hpp>
#include <boost/filesystem.hpp>
#include "babb/utils/memory.h"
#include "memwrappers.h"
#include "bcplus/Configuration.h"
#include "bcplus/parser/detail/lemon_macro.h"
#include "bcplus/parser/detail/lemon_parser.h"
#include "bcplus/parser/Token.h"
#include "bcplus/parser/detail/Scanner.h"
#include "bcplus/parser/detail/MacroParser.h"
#include "bcplus/symbols/SymbolTable.h"
Namespaces
bcplus
bcplus::parser
bcplus::parser::detail
Functions
void * lemon_macroAlloc (void *(*mallocProc)(size_t))
void * lemon_macroFree (void *yyp, void(*freeProc)(void *))
void lemon_macro (void *yyp, int tokentype, bcplus::parser::Token *token, bcplus::parser::detail::MacroParser *parser)
int lemon_macroPreInject (void *yyp, int pop, bcplus::parser::Token **token)
void lemon_macroAttemptReduce (void *yyp, bcplus::parser::detail::MacroParser *parser)
Function Documentation
void lemon_macro (void * yyp, int tokentype, bcplus::parser::Token * token, bcplus::parser::detail::MacroParser * parser)
Referenced by bcplus::parser::detail::MacroParser::next().
void* lemon_macroAlloc (void *(*)(size_t) mallocProc)
Definition at line 396 of file lemon_macro.cpp.
References yyParser::yyidx, yyParser::yylookmajor, yyParser::yylookminor, YYNOCODE, yyParser::yystack, yyParser::yystksz, and yyParser::yysyntaxerr.
Referenced by bcplus::parser::detail::MacroParser::MacroParser(), and bcplus::parser::detail::MacroParser::reset().
{
   yyParser *pParser;
   pParser = (yyParser*)(*mallocProc)( (size_t)sizeof(yyParser) );
   if( pParser ){
     pParser->yyidx = -1;
 #ifdef YYTRACKMAXSTACKDEPTH
     pParser->yyidxMax = 0;
 #endif
 #if YYSTACKDEPTH<=0
     pParser->yystack = NULL;
     pParser->yystksz = 0;
     yyGrowStack(pParser);
 #endif
     pParser->yylookmajor = YYNOCODE;
     pParser->yylookminor = yyzerominor;
     pParser->yysyntaxerr = 0;
   }
   return pParser;
 }
void lemon_macroAttemptReduce (void * yyp, bcplus::parser::detail::MacroParser * parser)
Referenced by bcplus::parser::detail::MacroParser::next().
void* lemon_macroFree (void * yyp, void(*)(void *) freeProc)
Definition at line 535 of file lemon_macro.cpp.
References YYCODETYPE, yyParser::yyidx, yyParser::yylookmajor, yyParser::yylookminor, YYNOCODE, and yyParser::yystack.
Referenced by bcplus::parser::detail::MacroParser::reset(), and bcplus::parser::detail::MacroParser::~MacroParser().
  {
   yyParser *pParser = (yyParser*)p;
   if( pParser==0 ) return;
   if( pParser->yylookmajor != YYNOCODE ) yy_destructor(pParser, (YYCODETYPE)pParser->yylookmajor, &pParser->yylookminor);
   while( pParser->yyidx>=0 ) yy_pop_parser_stack(pParser);
 #if YYSTACKDEPTH<=0
   free(pParser->yystack);
 #endif
   (*freeProc)((void*)pParser);
 }
int lemon_macroPreInject (void * yyp, int pop, bcplus::parser::Token ** token)