cplus2asp: as2transition Namespace Reference
as2transition Namespace Reference
Namespaces
parser
Classes
class Config
class PredElement
Base class for predicate/object elements.
class Predicate
Specialized predicate container used primarily for formatting.
class Timestep
Holds information about the predicates that are true at a given time step.
class TransitionFormatter
An exposed API for formatting answer sets using as2transition.
class TransitionPath
Represents a path through a transition system consisting of a number of timesteps (with assoicated states / actions / abnormalities)
Functions
std::ostream & operator<< (std::ostream &out, PredElement const &elem)
Outputs the predicate element to the provided stream...
std::ostream & operator<< (std::ostream &lhs, Timestep const &rhs)
Prints the step to the provided output strea.
std::ostream & operator<< (std::ostream &lhs, TransitionPath const &rhs)
Prints the path to the provided output strea.
bool isIntegerString (std::string const &str)
Checks if the provided string consists of just integers.
Function Documentation
bool as2transition::isIntegerString (std::string const & str)
Checks if the provided string consists of just integers.
Parameters
str The string to check.
Returns
True if str contains only [0-9].
Definition at line 48 of file TransitionFormatter.cpp.
{
     char const* c_str = str.c_str();
     size_t sz = str.size();
     for (size_t i = 0; i < sz; i++) {
         if (!isdigit(c_str[i])) return false;
     }
     return true;
 }
std::ostream& as2transition::operator<< (std::ostream & lhs, TransitionPath const & rhs) inline
Prints the path to the provided output strea.
Definition at line 111 of file TransitionPath.h.
References as2transition::TransitionPath::output().
 { return rhs.output(lhs); }
std::ostream & as2transition::operator<< (std::ostream & out, PredElement const & elem)
Outputs the predicate element to the provided stream...
Definition at line 141 of file PredElement.cpp.
References as2transition::PredElement::arity(), as2transition::PredElement::base(), as2transition::PredElement::begin(), as2transition::PredElement::end(), and as2transition::PredElement::get().
{
     if (*elem.base() == "=" && elem.arity() == 2) {
         // special case... if the element is =(c,v) then use infix notation...
         out << *elem.get(0);
         out << *elem.base();
         out << *elem.get(1);
     } else if (*elem.base() == "~" && elem.arity() == 1) {
         // special case... if the elemen is ~(c) then omit the parens...
         out << *elem.base() << *elem.get(0);
     } else if (*elem.base() == "-" && elem.arity() == 1) {
         // special case... if the elemen is ~(c) then omit the parens...
         out << *elem.base() << *elem.get(0);
     } else {
         out << *elem.base();
         if (elem.arity()) {
             out << "(";
             bool first = true;
             for (PredElement::const_iterator it = elem.begin(); it != elem.end(); it++) {
                 if (first) first = false;
                 else out << ", ";
                 out << **it;
             }
             out << ")";
         }
     }
     return out;
 }
std::ostream& as2transition::operator<< (std::ostream & lhs, Timestep const & rhs) inline
Prints the step to the provided output strea.
Definition at line 163 of file Timestep.h.
References lhs, and as2transition::Timestep::output().
 { rhs.output(lhs); return lhs; }