cplus2asp: utils Namespace Reference
utils Namespace Reference
Contains miscellaneous utility functions for manipulating and ouputting data.
Enumerations
enum ExitCodes {
EXT_CODE_GOOD = 0x00, EXT_CODE_BAD_ARGS = 0x80, EXT_CODE_TOOLCHAIN_TRANS_ERR = 0xC0, EXT_CODE_TOOLCHAIN_PREPROC_ERR = 0xC1,
EXT_CODE_TOOLCHAIN_GROUNDER_ERR = 0xC2, EXT_CODE_TOOLCHAIN_SOLVER_ERR = 0xC3, EXT_CODE_TOOLCHAIN_POSTPROC_ERR = 0xC4, EXT_CODE_TOOLCHAIN_REACTIVE_BRIDGE_ERR = 0xC5,
EXT_CODE_UNDEFINED_CONSTANTS = 0xA0, EXT_CODE_INVALID_STEP_VALUE = 0xA1, EXT_CODE_INVALID_QUERY = 0xA2
}
A list of possible exit codes...
Functions
bool isInteger (const char *str)
Checks if a c-string represents an integer or not.
void nice_exit (int exitCode, const char *message)
A wrapper for exit() that can output an optional custom message before leaving.
std::string trimWhitespace (std::string const &text)
Trims whitespace from both ends of a text string.
void pragma (char const *fmt, bool newline,...)
Generates a pragma message and sends it to the user via stdout.
void warning (char const *fmt, bool newline,...)
Generates a warning message and sends it to the user via stderr.
void error (char const *fmt, bool newline, unsigned char exitCode,...)
Generates an error message and sends it to the user via stderr.
template<class T >
bool from_string (T &val, const std::string &s, std::ios_base &(*fmt)(std::ios_base &)=std::dec)
Attempts to transform a string into a numeric representation of itself.
template<class T >
std::string to_string (T val, std::ios_base &(*fmt)(std::ios_base &)=std::dec, int precision=-1)
Transforms something (usually a number) into a string representation of itself.
size_t findFirstNotWhitespace (std::string const &text, size_t index=0)
Starting from position index, finds the first character in text that isn't whitespace, returns its position.
size_t findFirstWhitespace (std::string const &text, size_t index=0)
Starting from position index, finds the first character in text that is whitespace, returns its position.
void debug (char const *fmt, bool newline,...)
Generates and displays a debug message if the binary was compiled in debug mode.
bool isDigit (char testChar)
Checks if a character represents a digit or not.
bool isLowercase (char testChar)
Checks if a character is an lower-case (English) letter or not.
bool isUppercase (char testChar)
Checks if a character is an upper-case (English) letter or not.
bool isLetter (char testChar)
Checks if a character is an English letter or not, regardless of case.
template<class T >
std::string elementListToNameString (const std::list< T > &lst, bool useFullName=false, bool useTransName=false, const char *separator=", ", bool prettyPrint=false)
Given a list of pointers to Element objects (or subclasses of Element), will create a human-readable string representation of the list using the names of each element.
template<class T >
std::string elementListToFullNameString (const std::list< T > &lst, const char *separator=", ", bool prettyPrint=false)
Convenience function that calls elementListToNameString with useFullName set to true.
template<class T >
std::string elementListToTransNameString (const std::list< T > &lst, const char *separator=", ", bool prettyPrint=false)
Convenience function that calls elementListToNameString with useTransName set to true.
template<class T >
std::string elementListToFullTransNameString (const std::list< T > &lst, const char *separator=", ", bool prettyPrint=false)
Convenience function that calls elementListToNameString with useFullName and useTransName set to true.
template<class T >
std::string elementVectorToNameString (const std::vector< T > &vec, bool useFullName=false, bool useTransName=false, const char *separator=", ", bool prettyPrint=false)
Given a vector of pointers to Element objects (or subclasses of Element), will create a human-readable string representation of the vector using the names of each element.
template<class T >
std::string elementVectorToFullNameString (const std::vector< T > &vec, const char *separator=", ", bool prettyPrint=false)
Convenience function that calls elementVectorToNameString with useFullName set to true.
template<class T >
std::string elementVectorToTransNameString (const std::vector< T > &vec, const char *separator=", ", bool prettyPrint=false)
Convenience function that calls elementVectorToNameString with useTransName set to true.
template<class T >
std::string elementVectorToFullTransNameString (const std::vector< T > &vec, const char *separator=", ", bool prettyPrint=false)
Convenience function that calls elementVectorToNameString with useFullName and useTransName set to true.
template<class T >
void elementVectorToNameVector (const std::vector< T > &vec, NameList &out, bool useFullName=false, bool useTransName=false)
Grabs the names of Element objects in a vector and forms a vector of those names.
template<class T >
void elementVectorToFullNameVector (const std::vector< T > &vec, NameList &out)
Convenience function that calls elementVectorToNameVector with useFullName set to true.
template<class T >
std::vector< std::string > elementVectorToTransNameVector (const std::vector< T > &vec, NameList &out)
Convenience function that calls elementVectorToNameVector with useTransName set to true.
template<class T >
std::vector< std::string > elementVectorToFullTransNameVector (const std::vector< T > &vec, NameList &out)
Convenience function that calls elementVectorToNameVector with useFullName and useTransName set to true.
template<class T >
std::vector< T > elementListToElementVector (const std::list< T > &lst)
Takes a list of Element objects and makes a vector out of it.
template<class T >
void deallocateListContents (std::list< T * > &lst)
Safely deallocates and clears the contents of a list whose elements are pointers.
template<typename T >
bool areVectorsEqual (const std::vector< T & > &vec1, const std::vector< T & > &vec2)
Checks if the contents of two vectors are equal.
Detailed Description
Contains miscellaneous utility functions for manipulating and ouputting data.
Enumeration Type Documentation
enum utils::ExitCodes
A list of possible exit codes...
Enumerator
EXT_CODE_GOOD
EXT_CODE_BAD_ARGS
EXT_CODE_TOOLCHAIN_TRANS_ERR
EXT_CODE_TOOLCHAIN_PREPROC_ERR
EXT_CODE_TOOLCHAIN_GROUNDER_ERR
EXT_CODE_TOOLCHAIN_SOLVER_ERR
EXT_CODE_TOOLCHAIN_POSTPROC_ERR
EXT_CODE_TOOLCHAIN_REACTIVE_BRIDGE_ERR
EXT_CODE_UNDEFINED_CONSTANTS
EXT_CODE_INVALID_STEP_VALUE
EXT_CODE_INVALID_QUERY
Definition at line 40 of file utils.h.
 {
     EXT_CODE_GOOD = 0x00,
     EXT_CODE_BAD_ARGS = 0x80,
     EXT_CODE_TOOLCHAIN_TRANS_ERR = 0xC0,
     EXT_CODE_TOOLCHAIN_PREPROC_ERR = 0xC1,
     EXT_CODE_TOOLCHAIN_GROUNDER_ERR = 0xC2,
     EXT_CODE_TOOLCHAIN_SOLVER_ERR = 0xC3,
     EXT_CODE_TOOLCHAIN_POSTPROC_ERR = 0xC4,
     EXT_CODE_TOOLCHAIN_REACTIVE_BRIDGE_ERR = 0xC5,
     EXT_CODE_UNDEFINED_CONSTANTS = 0xA0,
     EXT_CODE_INVALID_STEP_VALUE = 0xA1,
     EXT_CODE_INVALID_QUERY = 0xA2
 };
Function Documentation
template<typename T > bool utils::areVectorsEqual (const std::vector< T & > & vec1, const std::vector< T & > & vec2)
Checks if the contents of two vectors are equal.
To be true, the vectors must be the same size, and each element must match in the vectors. Uses the != operator for comparison. Two empty vectors are considered equal.
Parameters
vec1 - The first vector to compare.
vec2 - The second vector to compare.
Returns
True if both vectors are the same size and all elements match, false otherwise.
Definition at line 426 of file utilities.h.
 {
     bool retVal = true; // Start optimistic.
     if(vec1.size() != vec2.size())
     {
         retVal = false;
     }
     else
     {
         for(size_t i = 0; i < vec1.size() && i < vec2.size(); i++)
         {
             if(vec1[i] != vec2[i])
             {
                 retVal = false;
                 break;
             }
         }
     }
     return retVal;
 }
template<class T > void utils::deallocateListContents (std::list< T * > & lst)
Safely deallocates and clears the contents of a list whose elements are pointers.
Parameters
lst - The list whose contents should be deallocated and cleared.
Definition at line 360 of file utilities.h.
 {
     class std::list<T*>::iterator lIter;
     for(lIter = lst.begin(); lIter != lst.end(); ++lIter)
     {
         if(*lIter != NULL)
         {
             delete *lIter;
         }
     }
     lst.clear();
 }
void utils::debug (char const * fmt, bool newline, ...) inline
Generates and displays a debug message if the binary was compiled in debug mode.
Otherwise does nothing.
Parameters
fmt The formatting string for the message.
newline Whether to include a newline after the message.
... Additional parameters for the format.
Definition at line 172 of file utils.h.
Referenced by Config::addInput(), Config::checkExtension(), cleanup(), main(), parseCommandOptions(), and runTool().
 { /* Intentionally left blank */ }
template<class T > std::vector<T> utils::elementListToElementVector (const std::list< T > & lst)
Takes a list of Element objects and makes a vector out of it.
Parameters
lst - The list to transform.
Returns
A vector containing the same elements in the same order as lst.
Definition at line 344 of file utilities.h.
 {
     class std::vector<T> retVec;
     class std::list<T>::const_iterator lIter;
     for(lIter = lst.begin(); lIter != lst.end(); ++lIter)
     {
         retVec.push_back(*lIter);
     }
     return retVec;
 }
template<class T > std::string utils::elementListToFullNameString (const std::list< T > & lst, const char * separator = ", ", bool prettyPrint = false)
Convenience function that calls elementListToNameString with useFullName set to true.
Leaves useTransName set to false.
Parameters
lst - A list of Element (or a subclass of Element) pointers to be stringified.
separator - What string to insert between elements of the list. (Default: ", ")
prettyPrint - If true, will add extra formatting around the names assuming they're being displayed as part of a toString function or output to a log. (Default: false)
Returns
A string representation of the vector's contents, using the full name of each element.
Definition at line 116 of file utilities.h.
 {
     return elementListToNameString<T>(lst, true, false, separator, prettyPrint);
 }
template<class T > std::string utils::elementListToFullTransNameString (const std::list< T > & lst, const char * separator = ", ", bool prettyPrint = false)
Convenience function that calls elementListToNameString with useFullName and useTransName set to true.
Parameters
lst - A list of Element (or a subclass of Element) pointers to be stringified.
separator - What string to insert between elements of the list. (Default: ", ")
prettyPrint - If true, will add extra formatting around the names assuming they're being displayed as part of a toString function or output to a log. (Default: false)
Returns
A string representation of the vector's contents, using the translated full name of each element.
Definition at line 143 of file utilities.h.
 {
     return elementListToNameString<T>(lst, true, true, separator, prettyPrint);
 }
template<class T > std::string utils::elementListToNameString (const std::list< T > & lst, bool useFullName = false, bool useTransName = false, const char * separator = ", ", bool prettyPrint = false)
Given a list of pointers to Element objects (or subclasses of Element), will create a human-readable string representation of the list using the names of each element.
The template allows for lists of subclasses of Element to be passed in without any casting issues.
Parameters
lst - A list of Element (or a subclass of Element) pointers to be stringified.
useFullName - If true, will use the elements' full names (including any parameters) instead of just their base names. (Default: false)
useTransName - If true, will use the elements' translated names instead of their original names. (Default: false)
separator - What string to insert between elements of the list. (Default: ", ")
prettyPrint - If true, will add extra formatting around the names assuming they're being displayed as part of a toString function or output to a log. (Default: false)
Returns
A string representation of the vector's contents.
Definition at line 53 of file utilities.h.
 {
     std::string tempStr = "";
     std::ostringstream sout; // Use a string stream to form the string, then copy it to tempStr.
     class std::list<T>::const_iterator lIter;
     std::string prettyPrintQuotes = "";
     if(prettyPrint)
     {
         prettyPrintQuotes = "\"";
     }
     // Output the name of each element of lst.
     for(lIter = lst.begin(); lIter != lst.end(); ++lIter)
     {
         if(lIter != lst.begin())
         {   // If this isn't the first element, stick a list separator before it.
             sout << separator;
         }
         // Protect from accessing a NULL pointer, inserting "NULL" in if the pointer is invalid.
         if(*lIter == NULL)
         {
             sout << "NULL";
         }
         else
         {
             if(useFullName)
             {
                 if(useTransName)
                 {
                     sout << prettyPrintQuotes << ((Element*)(*lIter))->fullTransName() << prettyPrintQuotes;
                 }
                 else
                 {
                     sout << prettyPrintQuotes << ((Element*)(*lIter))->fullName() << prettyPrintQuotes;
                 }
             }
             else
             {
                 if(useTransName)
                 {
                     sout << prettyPrintQuotes << ((Element*)(*lIter))->baseName() << prettyPrintQuotes;
                 }
                 else
                 {
                     sout << prettyPrintQuotes << ((Element*)(*lIter))->baseName() << prettyPrintQuotes;
                 }
             }
         }
     }
     tempStr = sout.str();
     return tempStr;
 }
template<class T > std::string utils::elementListToTransNameString (const std::list< T > & lst, const char * separator = ", ", bool prettyPrint = false)
Convenience function that calls elementListToNameString with useTransName set to true.
Leaves useFullName set to false.
Parameters
lst - A list of Element (or a subclass of Element) pointers to be stringified.
separator - What string to insert between elements of the list. (Default: ", ")
prettyPrint - If true, will add extra formatting around the names assuming they're being displayed as part of a toString function or output to a log. (Default: false)
Returns
A string representation of the vector's contents, using the translated name of each element.
Definition at line 130 of file utilities.h.
 {
     return elementListToNameString<T>(lst, false, true, separator, prettyPrint);
 }
template<class T > std::string utils::elementVectorToFullNameString (const std::vector< T > & vec, const char * separator = ", ", bool prettyPrint = false)
Convenience function that calls elementVectorToNameString with useFullName set to true.
Passes false for useTransName.
Parameters
vec - A vector of Element (or a subclass of Element) pointers to be stringified.
separator - What string to insert between elements of the list. (Default: ", ")
prettyPrint - If true, will add extra formatting around the names assuming they're being displayed as part of a toString function or output to a log. (Default: false)
Returns
A string representation of the vector's contents, using the full name of each element.
Definition at line 225 of file utilities.h.
 {
     return elementVectorToNameString<T>(vec, true, false, separator, prettyPrint);
 }
template<class T > void utils::elementVectorToFullNameVector (const std::vector< T > & vec, NameList & out)
Convenience function that calls elementVectorToNameVector with useFullName set to true.
Passes false for useTransName.
Parameters
vec - The Element vector to extract names from.
[out] out - A vector of strings representing the full names of each element.
Definition at line 310 of file utilities.h.
References elementVectorToNameVector().
 {
     elementVectorToNameVector(vec, out, true, false);
 }
template<class T > std::string utils::elementVectorToFullTransNameString (const std::vector< T > & vec, const char * separator = ", ", bool prettyPrint = false)
Convenience function that calls elementVectorToNameString with useFullName and useTransName set to true.
Parameters
vec - A vector of Element (or a subclass of Element) pointers to be stringified.
separator - What string to insert between elements of the list. (Default: ", ")
prettyPrint - If true, will add extra formatting around the names assuming they're being displayed as part of a toString function or output to a log. (Default: false)
Returns
A string representation of the vector's contents, using the translated full name of each element.
Definition at line 252 of file utilities.h.
 {
     return elementVectorToNameString<T>(vec, true, true, separator, prettyPrint);
 }
template<class T > std::vector<std::string> utils::elementVectorToFullTransNameVector (const std::vector< T > & vec, NameList & out)
Convenience function that calls elementVectorToNameVector with useFullName and useTransName set to true.
Parameters
vec - The Element vector to extract names from.
[out] out - A vector of strings representing the translated full names of each element.
Definition at line 333 of file utilities.h.
References elementVectorToNameVector().
 {
     return elementVectorToNameVector(vec, out, true, true);
 }
template<class T > std::string utils::elementVectorToNameString (const std::vector< T > & vec, bool useFullName = false, bool useTransName = false, const char * separator = ", ", bool prettyPrint = false)
Given a vector of pointers to Element objects (or subclasses of Element), will create a human-readable string representation of the vector using the names of each element.
The template allows for vectors of subclasses of Element to be passed in without any casting issues.
Parameters
vec - A vector of Element (or a subclass of Element) pointers to be stringified.
useFullName - If true, will use the elements' full names (including any parameters) instead of just their base names. (Default: false)
useTransName - If true, will use the elements' translated names instead of their original names. (Default: false)
separator - What string to insert between elements of the list. (Default: ", ")
prettyPrint - If true, will add extra formatting around the names assuming they're being displayed as part of a toString function or output to a log. (Default: false)
Returns
A string representation of the vector's contents.
Definition at line 159 of file utilities.h.
 {
     std::string tempStr = "";
     std::ostringstream sout; // Use a string stream to form the string, then copy it to tempStr.
     std::string prettyPrintQuotes = "";
     if(prettyPrint)
     {
         prettyPrintQuotes = "\"";
     }
     // Output the name of each element of vec.
     for(size_t i = 0; i < vec.size(); i++)
     {
         if(i > 0)
         {   // If this isn't the first element, stick a list separator before it.
             sout << separator;
         }
         if(prettyPrint)
         {
             sout << "[" << i << "]=";
         }
         // Protect from accessing a NULL pointer, inserting "NULL" in if the pointer is invalid.
         if(vec[i] == NULL)
         {
             sout << "_";
         }
         else
         {
             if(useFullName)
             {
                 if(useTransName)
                 {
                     sout << prettyPrintQuotes << vec[i]->fullTransName() << prettyPrintQuotes;
                 }
                 else
                 {
                     sout << prettyPrintQuotes << vec[i]->fullName() << prettyPrintQuotes;
                 }
             }
             else
             {
                 if(useTransName)
                 {
                     sout << prettyPrintQuotes << vec[i]->baseTransName() << prettyPrintQuotes;
                 }
                 else
                 {
                     sout << prettyPrintQuotes << vec[i]->baseName() << prettyPrintQuotes;
                 }
             }
         }
     }
     tempStr = sout.str();
     return tempStr;
 }
template<class T > void utils::elementVectorToNameVector (const std::vector< T > & vec, NameList & out, bool useFullName = false, bool useTransName = false)
Grabs the names of Element objects in a vector and forms a vector of those names.
Parameters
vec - The Element vector to extract names from.
useFullName - If true, will use the elements' full names (including any parameters) instead of just their base names. (Default: false)
useTransName - If true, will use the translated names of the elements instead of their original names. (Default: false)
[out] out - A vector of strings representing the base names of each element.
Definition at line 265 of file utilities.h.
Referenced by elementVectorToFullNameVector(), elementVectorToFullTransNameVector(), and elementVectorToTransNameVector().
 {
     // Add the name of each element to tempVec.
     for(size_t i = 0; i < vec.size(); i++)
     {
         // Protect from accessing a NULL pointer, inserting "NULL" in if the pointer is invalid.
         if(vec[i] == NULL)
         {
             out.push_back(std::string("NULL"));
         }
         else
         {
             if(useFullName)
             {
                 if(useTransName)
                 {
                     out.push_back(vec[i]->fullTransName());
                 }
                 else
                 {
                     out.push_back(vec[i]->fullName());
                 }
             }
             else
             {
                 if(useTransName)
                 {
                     out.push_back(vec[i]->baseTransName());
                 }
                 else
                 {
                     out.push_back(vec[i]->baseName());
                 }
             }
         }
     }
 }
template<class T > std::string utils::elementVectorToTransNameString (const std::vector< T > & vec, const char * separator = ", ", bool prettyPrint = false)
Convenience function that calls elementVectorToNameString with useTransName set to true.
Passes false for useFullName.
Parameters
vec - A vector of Element (or a subclass of Element) pointers to be stringified.
separator - What string to insert between elements of the list. (Default: ", ")
prettyPrint - If true, will add extra formatting around the names assuming they're being displayed as part of a toString function or output to a log. (Default: false)
Returns
A string representation of the vector's contents, using the translated name of each element.
Definition at line 239 of file utilities.h.
 {
     return elementVectorToNameString<T>(vec, false, true, separator, prettyPrint);
 }
template<class T > std::vector<std::string> utils::elementVectorToTransNameVector (const std::vector< T > & vec, NameList & out)
Convenience function that calls elementVectorToNameVector with useTransName set to true.
Passes false for useFullName.
Parameters
vec - The Element vector to extract names from.
[out] out - A vector of strings representing the translated base names of each element.
Definition at line 322 of file utilities.h.
References elementVectorToNameVector().
 {
     return elementVectorToNameVector(vec, out, false, true);
 }
void utils::error (char const * fmt, bool newline, unsigned char exitCode, ...)
Generates an error message and sends it to the user via stderr.
Exits if the provided exit code is non-zero.
Parameters
fmt The formatting string for the message.
newline Whether to include a newline after the message.
exitCode The code to exit with. An exit code of 0 will prevent the program from exiting.
... Additional parameters for the format.
Definition at line 128 of file utils.cpp.
Referenced by main(), cplus2asp::bcbridge::NetworkClient::NetworkClient(), parseCommandOptions(), processErrors(), runTool(), and cplus2asp::bcbridge::NetworkClient::write().
{
        va_list arg;
        fprintf(stderr, "%% Error: ");
        va_start(arg, exitCode);
        vfprintf(stderr, fmt, arg);
        va_end(arg);
        if (newline)
            fprintf(stderr, "\n");
        if (exitCode) exit(exitCode);
 }
size_t utils::findFirstNotWhitespace (std::string const & text, size_t index = 0) inline
Starting from position index, finds the first character in text that isn't whitespace, returns its position.
Parameters
text - The string to search.
index - Optional parameter specifying starting index of the search. Defaults to 0.
Returns
The index of the first character in text that isn't whitespace, or string::npos if it's all whitespace.
Definition at line 121 of file utils.h.
 {
     return text.find_first_not_of(" \n\f\r\t\v", index);
 }
size_t utils::findFirstWhitespace (std::string const & text, size_t index = 0) inline
Starting from position index, finds the first character in text that is whitespace, returns its position.
Parameters
text - The string to search through.
index - Optional parameter specifying starting index of the search. Defaults to 0.
Returns
The index of the first character in text that is whitespace, or string::npos if none of it is whitespace.
Definition at line 132 of file utils.h.
 {
     return text.find_first_of(" \n\f\r\t\v", index);
 }
template<class T > bool utils::from_string (T & val, const std::string & s, std::ios_base &(*)(std::ios_base &) fmt = std::dec)
Attempts to transform a string into a numeric representation of itself.
For numbers, fmt should be dec, hex, or oct.
Parameters
val - A reference to the recipient of the generated number.
s - The string to convert.
fmt - An optional parameter that specifies what kind of numeric conversion to attempt. If not given, will default to std::dec.
Returns
True if s could be converted into a number using fmt, false if there was a problem performing the conversion.
Definition at line 72 of file utils.h.
Referenced by Config::def(), ObjectLikeElement::isNumeric(), parseCommandOptions(), Config::parseMaxstep(), queryUserForConstant(), and queryUserForQuery().
 {
     std::istringstream iss(s);
     return !((iss >> fmt >> val).fail());
 }
bool utils::isDigit (char testChar)
Checks if a character represents a digit or not.
Parameters
testChar - The character to test.
Returns
True if it's a digit, false otherwise.
Definition at line 57 of file utilities.cpp.
Referenced by Translator::sanitizeConstantName(), Translator::sanitizeSortName(), Translator::sanitizeString(), and Translator::sanitizeVariableName().
 {
     bool retVal = false;
     if(testChar >= '0' && testChar <= '9')
     {
         retVal = true;
     }
     return retVal;
 }
bool utils::isInteger (const char * str)
Checks if a c-string represents an integer or not.
The whole string must count as an integer, no spaces or other nonsense allowed. Number may start with + or -.
Parameters
str - The string to test.
Returns
True if str is an integer, false otherwise.
Definition at line 42 of file utils.cpp.
Referenced by parseCommandOptions().
 {
     bool retVal = true; // Start optimistic.
     size_t strLength = strlen(str);
     if(strLength == 0 || !(isdigit(str[0]) || str[0] == '+' || str[0] == '-'))
     { // Must be >0 length and start with a digit, +, or -.
         retVal = false;
     }
     else
     {
         // The rest of the string must be digits.
         for(unsigned int i = 1; i < strLength; i++)
         {
             if(!isdigit(str[i]))
             {
                 retVal = false;
                 break;
             }
         }
     }
     return retVal;
 }
bool utils::isLetter (char testChar)
Checks if a character is an English letter or not, regardless of case.
Parameters
testChar - The character to test.
Returns
True if it's an upper- or lower-case letter, false otherwise.
Definition at line 90 of file utilities.cpp.
References isLowercase(), and isUppercase().
Referenced by Translator::sanitizeString().
 {
     return (isUppercase(testChar) || isLowercase(testChar));
 }
bool utils::isLowercase (char testChar)
Checks if a character is an lower-case (English) letter or not.
Parameters
testChar - The character to test.
Returns
True if it's a lower-case letter, false otherwise.
Definition at line 68 of file utilities.cpp.
Referenced by isLetter(), and Translator::sanitizeVariableName().
 {
     bool retVal = false;
     if(testChar >= 'a' && testChar <= 'z')
     {
         retVal = true;
     }
     return retVal;
 }
bool utils::isUppercase (char testChar)
Checks if a character is an upper-case (English) letter or not.
Parameters
testChar - The character to test.
Returns
True if it's an upper-case letter, false otherwise.
Definition at line 79 of file utilities.cpp.
Referenced by isLetter(), Translator::sanitizeConstantName(), Translator::sanitizeObjectName(), Translator::sanitizeSortName(), and Translator::sanitizeString().
 {
     bool retVal = false;
     if(testChar >= 'A' && testChar <= 'Z')
     {
         retVal = true;
     }
     return retVal;
 }
void utils::nice_exit (int exitCode, const char * message)
A wrapper for exit() that can output an optional custom message before leaving.
Outputs to stdout if exitCode is 0, stderr otherwise.
Parameters
exitCode - The exit code to pass to exit.
message - A message to output to standard out before exiting (terminating newline automatically added).
Definition at line 65 of file utils.cpp.
Referenced by main().
 {
     if(exitCode == 0 && message != NULL)
     {
         std::cout << message << std::endl;
     }
     else if(exitCode != 0 && message != NULL)
     {
         std::cerr << message << std::endl;
     }
     exit(exitCode);
 }
void utils::pragma (char const * fmt, bool newline, ...)
Generates a pragma message and sends it to the user via stdout.
Parameters
fmt The formatting string for the message.
newline Whether to include a newline after the message.
... Additional parameters for the format.
Definition at line 100 of file utils.cpp.
Referenced by main(), parseCommandOptions(), and runTool().
{
        va_list arg;
        fprintf(stdout, "%% Pragma: ");
        va_start(arg, newline);
        vfprintf(stdout, fmt, arg);
        va_end(arg);
        if (newline)
            fprintf(stdout, "\n");
 }
template<class T > std::string utils::to_string (T val, std::ios_base &(*)(std::ios_base &) fmt = std::dec, int precision = -1)
Transforms something (usually a number) into a string representation of itself.
For integers, fmt should be dec, hex, or oct. For floating-point numbers, fmt should be fixed or scientific. Precision will help control the precision of floating-point numbers.
Parameters
val - The number to transform into a string.
fmt - An optional parameter controlling what kind of number val should be treated as. Defaults to std::dec.
precision - The decimal precision to use with floating-point numbers. Defaults to -1.
Returns
The string version of val on success, a blank string on failure.
Definition at line 88 of file utils.h.
Referenced by Translator::addSort(), Config::compileArgs(), Translator::createInternalObject(), ParseElement::getNewVar(), Translator::getOrCreateObject(), Translator::outputSymbolTable(), and Translator::translateCausalLaw().
 {
     std::stringstream ss;
     if(precision > -1)
     {
         ss.precision(precision);
     }
     ss << fmt << val;
     return ss.str();
 }
std::string utils::trimWhitespace (std::string const & text)
Trims whitespace from both ends of a text string.
Trims whitespace from a string.
Parameters
text - The text to trim.
Returns
The string stripped of whitespace on both sides.
Definition at line 78 of file utils.cpp.
Referenced by Translator::addSort(), Config::def(), Interpreter::interpret(), Config::isDefined(), Config::parseMaxstep(), and queryUserForConstant().
 {
     std::string retVal = "";
     std::string whitespace = " \n\f\r\t\v";
     size_t sztFirstPos = 0, sztSecondPos = 0;
     if(text.length() > 0)
     {
         sztFirstPos = text.find_first_not_of(whitespace);
         sztSecondPos = text.find_last_not_of(whitespace);
         if(sztFirstPos != std::string::npos)
         {   // We got two valid positions, trim accordingly.
             retVal = text.substr(sztFirstPos, sztSecondPos - sztFirstPos + 1);
         }
         else
         {   // The whole dang string is whitespace, return blank.
             retVal = "";
         }
     }
     return retVal;
 }
void utils::warning (char const * fmt, bool newline, ...)
Generates a warning message and sends it to the user via stderr.
Parameters
fmt The formatting string for the message.
newline Whether to include a newline after the message.
... Additional parameters for the format.
Definition at line 114 of file utils.cpp.
Referenced by Config::def(), main(), parseCommandOptions(), and runTool().
{
        va_list arg;
        fprintf(stderr, "%% Warning: ");
        va_start(arg, newline);
        vfprintf(stderr, fmt, arg);
        va_end(arg);
        if (newline)
            fprintf(stderr, "\n");
 }