cplus2asp: as2transition/src/as2transition/parser/PredicateParser.cpp File Reference
PredicateParser.cpp File Reference
#include <string>
#include <iostream>
#include "babb/utils/memory.h"
#include "memwrappers.h"
#include "as2transition/parser/lemon_parser.h"
#include "as2transition/parser/PredicateParser.h"
Namespaces
as2transition
as2transition::parser
Functions
void * transition_parserAlloc (void *(*mallocProc)(size_t))
void * transition_parserFree (void *yyp, void(*freeProc)(void *))
void transition_parser (void *yyp, int tokentype, ReferencedString const *token, as2transition::parser::PredicateParser *parser)
int transition_parserPreInject (void *yyp, int pop, ReferencedString const **token)
void transition_parserAttemptReduce (void *yyp, as2transition::parser::PredicateParser *parser)
void transition_parserTrace (FILE *TraceFILE, char const *zTracePrompt)
char const * transition_parserTokenName (int tcode)
Function Documentation
void transition_parser (void * yyp, int tokentype, ReferencedString const * token, as2transition::parser::PredicateParser * parser)
Referenced by as2transition::parser::PredicateParser::parse().
void* transition_parserAlloc (void *(*)(size_t) mallocProc)
Definition at line 367 of file lemon_parser.cpp.
References yyParser::yyidx, yyParser::yylookmajor, yyParser::yylookminor, YYNOCODE, yyParser::yystack, yyParser::yystksz, and yyParser::yysyntaxerr.
Referenced by as2transition::parser::PredicateParser::PredicateParser().
{
   yyParser *pParser;
   pParser = (yyParser*)(*mallocProc)( (size_t)sizeof(yyParser) );
   if( pParser ){
     pParser->yyidx = -1;
 #ifdef YYTRACKMAXSTACKDEPTH
     pParser->yyidxMax = 0;
 #endif
 #if YYSTACKDEPTH<=0
     pParser->yystack = NULL;
     pParser->yystksz = 0;
     yyGrowStack(pParser);
 #endif
     pParser->yylookmajor = YYNOCODE;
     pParser->yylookminor = yyzerominor;
     pParser->yysyntaxerr = 0;
   }
   return pParser;
 }
void transition_parserAttemptReduce (void * yyp, as2transition::parser::PredicateParser * parser)
Referenced by as2transition::parser::PredicateParser::parse().
void* transition_parserFree (void * yyp, void(*)(void *) freeProc)
Definition at line 498 of file lemon_parser.cpp.
References YYCODETYPE, yyParser::yyidx, yyParser::yylookmajor, yyParser::yylookminor, YYNOCODE, and yyParser::yystack.
Referenced by as2transition::parser::PredicateParser::~PredicateParser().
  {
   yyParser *pParser = (yyParser*)p;
   if( pParser==0 ) return;
   if( pParser->yylookmajor != YYNOCODE ) yy_destructor(pParser, (YYCODETYPE)pParser->yylookmajor, &pParser->yylookminor);
   while( pParser->yyidx>=0 ) yy_pop_parser_stack(pParser);
 #if YYSTACKDEPTH<=0
   free(pParser->yystack);
 #endif
   (*freeProc)((void*)pParser);
 }
int transition_parserPreInject (void * yyp, int pop, ReferencedString const ** token)
char const* transition_parserTokenName (int tcode)
Definition at line 1072 of file lemon_parser.cpp.
References YYERRORSYMBOL, and YYNOCODE.
{
     if (tok < 1) return "<INVALID_TOKEN>";
     else if (tok == YYNOCODE) return "<NOCODE_TOKEN>";
 #ifdef YYERRORSYMBOL
     else if (tok == YYERRORSYMBOL) return "<ERROR_TOKEN>";
 #endif
     return yyTokenName[tok];
 }
void transition_parserTrace (FILE * TraceFILE, char const * zTracePrompt)
Definition at line 289 of file lemon_parser.cpp.
{
   yyTraceFILE = TraceFILE;
   yyTracePrompt = zTracePrompt;
   if( yyTraceFILE==0 ) yyTracePrompt = 0;
   else if( yyTracePrompt==0 ) yyTraceFILE = 0;
 }