cplus2asp: bcbridge/main.cpp File Reference
main.cpp File Reference
#include "Driver.h"
#include "babb/utils/memory.h"
#include "as2transition/TransitionFormatter.h"
Macros
#define VERSION_MAJOR 0
#define VERSION_MINOR 1
#define VERSION_REV 0
Functions
void showHelp (std::ostream &out, char const *name)
Displays the help dialog/.
void printVersion (std::ostream &out)
Prints the version string to out.
int main (int argc, char const *argv[])
Macro Definition Documentation
#define VERSION_MAJOR 0
Definition at line 40 of file main.cpp.
Referenced by printVersion().
#define VERSION_MINOR 1
Definition at line 41 of file main.cpp.
Referenced by printVersion().
#define VERSION_REV 0
Definition at line 42 of file main.cpp.
Referenced by printVersion().
Function Documentation
int main (int argc, char const * argv[])
Definition at line 58 of file main.cpp.
References cplus2asp::bcbridge::Driver::formatter(), cplus2asp::bcbridge::Driver::host(), as2transition::TransitionFormatter::parseOption(), cplus2asp::bcbridge::Driver::port(), cplus2asp::bcbridge::Driver::run(), showHelp(), and cplus2asp::bcbridge::Driver::symtab().
 {
     Driver driver;
     // -------------------------------------------------- Option Parsing.
     for (int i = 1; i < argc; i++) {
         if (!driver.formatter().parseOption(argv[i], true)) {
             if (!strncmp(argv[i], "--port=", strlen("--port="))) {
                 if (strlen(argv[i]) <= strlen("--port=") ||!driver.port(argv[i] + strlen("--port="))) {
                     std::cerr << "Error: '" << argv[i] << "' is not a valid port specification.\n";
                     showHelp(std::cout, argv[0]);
                     return 1;
                 }
             } else if (!strcmp(argv[i], "-p")) {
                 if (++i < argc) {
                     if (!driver.port(argv[i])) {
                         std::cerr << "Error: '" << argv[i] << "' is not a valid port.\n";
                         showHelp(std::cout, argv[0]);
                         return 1;
                     }
                 } else {
                     std::cerr << "Error: Expected a port number following '" << argv[i-1] << "'.\n";
                     showHelp(std::cout, argv[0]);
                     return 1;
                 }
             } else if (!strncmp(argv[i], "--host=", strlen("--host="))) {
                 if (strlen(argv[i]) <= strlen("--host=") ||!driver.host(argv[i] + strlen("--host="))) {
                     std::cerr << "Error: '" << argv[i] << "' is not a valid host specification.\n";
                     showHelp(std::cout, argv[0]);
                     return 1;
                 }
             } else if (!strcmp(argv[i], "--time") || !strcmp(argv[i],"-t")) {
 #ifdef BOOST_TIMER
                 // display time
                 driver.displayTime(true);
 #else
                 std::cerr << "Warning: The '" << argv[i] << "' flag requires that the Boost.Timer library is present at compile time. " << std::endl;
                 std::cerr << "Warning: Ignoring '" << argv[i] << "'" << std::endl;
 #endif
             } else if (!strcmp(argv[i], "-h")) {
                 if (++i < argc) {
                     if (!driver.host(argv[i])) {
                         std::cerr << "Error: '" << argv[i] << "' is not a host.\n";
                         showHelp(std::cout, argv[0]);
                         return 1;
                     }
                 } else {
                     std::cerr << "Error: Expected a host name following '" << argv[i-1] << "'.\n";
                     showHelp(std::cout, argv[0]);
                     return 1;
                 }
             } else if (!strcmp(argv[i],"-s")) {
                 if (++i < argc) {
                     if (!driver.symtab(argv[i])) {
                         std::cerr << "Error: '" << argv[i] << "' is not a valid symbol table file.\n";
                         showHelp(std::cout, argv[0]);
                         return 1;
                     }
                 } else {
                     std::cerr << "Error: Expected a file name following '" << argv[i-1] << "'.\n";
                     showHelp(std::cout, argv[0]);
                     return 1;
                 }
             } else if (!strncmp(argv[i],"--symbol-table=", strlen("--symbol-table="))) {
                 if (strlen(argv[i]) <= strlen("--symbol-table=") || !driver.symtab(argv[i] + strlen("--symbol-table="))) {
                         std::cerr << "Error: '" << argv[i] << "' is not a valid symbol table file.\n";
                         showHelp(std::cout, argv[0]);
                         return 1;
                 }
             } else if (!strcmp(argv[i], "--help") || !strcmp(argv[i],"-?") || !strcmp(argv[i],"?")) {
                 showHelp(std::cout, argv[0]);
                 return 0;
             } else {
                 if (!driver.formatter().parseOption(argv[i], false)) {
                     std::cerr << "Error: Unknown option: '" << argv[i] << "'.\n";
                     return 1;
                 }
             }
         }
     }
     // ----------------------------------------------------- The hard work.
     return driver.run();
 }
void printVersion (std::ostream & out)
Prints the version string to out.
Definition at line 54 of file main.cpp.
References VERSION_MAJOR, VERSION_MINOR, and VERSION_REV.
Referenced by showHelp().
{
     out << VERSION_MAJOR << "." << VERSION_MINOR << "." << VERSION_REV;
 }
void showHelp (std::ostream & out, char const * name)
Displays the help dialog/.
Parameters
out The output stream to write the help dialog to.
the name of this application.
Definition at line 148 of file main.cpp.
References cplus2asp::bcbridge::Driver::DEF_OCLINGO_HOST, cplus2asp::bcbridge::Driver::DEF_OCLINGO_PORT, as2transition::TransitionFormatter::help(), and printVersion().
Referenced by main().
{
     out << name << " version "; printVersion(out); out                                                  << std::endl
     << "USAGE: " << name << " [OPTIONS]"                                                                << std::endl
                                                                                                         << std::endl
     << "Available Options: "                                                                            << std::endl
     << "  --port=PORT OR -p PORT "                                                                      << std::endl
     << "        Specifies the port to connect to oClingo with. [Default: " << Driver::DEF_OCLINGO_PORT << " ]." << std::endl
     << "  --host=HOST OR -h HOST "                                                                      << std::endl
     << "        Specifies the host that oClingo is running on. [Default: " << Driver::DEF_OCLINGO_HOST << " ]." << std::endl
     << "  --time OR -t "                                                                                << std::endl
     << "        Prints the time oClingo took to respond after each iteration."                          << std::endl
 #ifndef BOOST_TIMER
     << "        NOTICE: Requires recompilation with the Boost.Timer library."                           << std::endl
 #endif
     << "  --symbol-table=SYMTAB OR -s SYMTAB "                                                          << std::endl
     << "        Specifies a symbol table to load pre-defined BC+ symbols from."                         << std::endl
     << "  --version OR -v "                                                                             << std::endl
     << "        Displays the version of the program."                                                   << std::endl
     << "  --help OR -? OR ?"                                                                            << std::endl
     << "        Shows this dialog."                                                                     << std::endl
                                                                                                         << std::endl;
     out << "AS2Transition Options: " << std::endl;
     as2transition::TransitionFormatter::help(out, true);
 }